### ISSUE TITLE
Refactor checking of forecasting horizon (_set_fh)

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#1006]
#### Reference issues/PR
Conditional on #955 
Related to #510 

#### Suggested changes
I've thought about this a bit more and I prefer the option where we pass the name of the calling method to `_set_fh` in the `BaseForecaster`, e.g. `_set_fh(fh, method="fit")`. For me, the main reasons are:
* it keeps the functionality for checking/setting the fh contained to that function and does not assume state changes elsewhere in the code, like at the beginning of fit,
* it keeps it closer to the implementation of other estimator types where we do not re-set the state at the beginning of fit,
* it avoids the redundancy of having to set _is_fitted=False in the constructor and at the beginning of fit.

**Comment by fkiraly** [comment]
what do you think of `is_fitted=?` instead of `method=?`

**Comment by fkiraly** [comment]
and what do you think of making the method entirely pure?

I.e., calling it `self._fh = _set_fh(fh, is_fitted)?

Following the general design principle that pure methods are preferable if the method is not clearly state change associated.

**Comment by mloning** [comment]
* There is a `check_fh` already which checks the forecasting horizon, but we could have a separate one that lives in the same file as the base forecaster.  
* I agree about the idea of pure method, but the error message reads much nicer when you have additional info such as the object name, which seems important for this check, because it's not very intuitive why a forecaster requires `fh` already in fit.  
* The checking also depends on the method, not just the is-fitted state if I remember correctly, so we would need the `method` argument in there if that's true.

**Comment by fkiraly** [comment]
>I agree about the idea of pure method, but the error message reads much nicer when you have additional info such as the object name, which seems important for this check, because it's not very intuitive why a forecaster requires fh already in fit.

You could pass the object name

>The checking also depends on the method, not just the is-fitted state if I remember correctly, so we would need the method argument in there if that's true.

`is_fitted` would just be an alias whether it's in `fit` or not. If it's in `fit`, the assumption is automatically that it's not fitted. I.e., in `fit` we would run `_set_fh(..., is_fitted=False)`

**Comment by mloning** [comment]
> `is_fitted` would just be an alias whether it's in `fit` or not. If it's in `fit`, the assumption is automatically that it's not fitted. I.e., in `fit` we would run `_set_fh(..., is_fitted=False)`

Okay but then we should call it `method` or `caller` as that's what it is rather than an alias.

Stand-alone function with good error message seems good to me.

**Comment by fkiraly** [comment]
The function is called `_check_fh`, and uses the state of `self` instead of a caller argument.
