### ISSUE TITLE
Proximity forest testing

### ISSUE THREAD

**Issue by goastler** [alan-turing-institute/sktime#101]
Proximity forest needs to be tested under the new parameter spaces, as old ones were incorrect and likely the issue of ~3% accuracy missing.

**Comment by TonyBagnall** [comment]
I can also test this when I can bring myself back (kicking and screaming) to python world. But if you have queue space, use it

**Comment by TonyBagnall** [comment]
err, whats going on here? 
![image](https://user-images.githubusercontent.com/9594042/61914139-7905dc00-af37-11e9-8683-4836cd05d69a.png)

**Comment by mloning** [comment]
Could we perhaps also make the proximity forest unit test a little faster (looking only data subsamples for example), would really appreciate this!

**Comment by TonyBagnall** [comment]
Gone through and tidied it up, and am running it next week, fingers crossed! I'll put some minor queries here that might be addressed in due course (i.e. in the next master push after this one)
1) there are a lot of functions not in a class. This seems messy to me, whole lot of getters etc. Could they not be inside base class
2) I think the CachedTransformer should be moved back to transformers, it has generic usage. As far as I see can see its just a wrapper for and Transformer that caches instances for the use case of multiple calls with the same data set.
3) However, I'm not sure it is set up to take sktime Pandas, i.e. where the whole series are in columns? If true, (also suggested by later functions) leave it here for now.
4) all the distance function getters use dim_to_use, which we are removing. If efficiency is an issue, just use column 0, if not, check if it has more and ditch if it has.

**Comment by mloning** [comment]
I've re-activated the unit tests for proximity forest (#116), I tried to make them faster but the array for the true predictions seems to be formatted in a weird way, values are not comma separated?

**Comment by mloning** [comment]
Fixed by #145
