### ISSUE TITLE
test_estimator or a variant should work with object (not classes)

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1027]
For easy testing and debugging, it would be great if `test_estimator` or a variant thereof could be extended to work with object instances, not classes; alternatively, classes with default parameter settings not read from a file, but given as an argument.

This is for:
* making it easier for local (non-contributing) extenders to write their own tests
* making new estimators easier to debug, e.g., by making it easier to vary the parameters in the test
* to enable extension and manual testing without having to clone the repository (with a simple workflow that could be added to the tutorials)

**Comment by fkiraly** [comment]
@mloning, @aiwalter, @TonyBagnall - thoughts?

**Comment by mloning** [comment]
Closed in favour of #1032

**Comment by fkiraly** [comment]
I think this is separate - this is a minor change.

Refactoring the entirety of tests is a big change.

We don't need to do a massive refactoring to allow users to run the *current* `test_estimator`.
