### ISSUE TITLE
Make transformer for detrending support multivariate series

### ISSUE THREAD

**Issue by SveaMeyer13** [alan-turing-institute/sktime#1030]
**Is your feature request related to a problem? Please describe.**
For the EEG applications we need a transformer that detrends each channel. Currently the detrending transformer only supports univariate time series.

**Describe the solution you'd like**
Detrend each univariate series separately

**Comment by fkiraly** [comment]
@SveaMeyer13, what do you think about the solution in #1038? That way, you can apply everything, not just the detrender, to multivariate EEG data.

**Comment by SveaMeyer13** [comment]
@fkiraly, yes I like the idea in #1038 - for now, I just took inspiration by how it was done in the imputer.

**Comment by fkiraly** [comment]
well, we can always do both.

It's a bit of a `sktime` bad habit to ask for more general solutions that take more time, than go for the "fit for purpose" fix - sorry for doing that here.

I think the solution you proposed is robust, and definitely more suitable to get you quicker to your goal and less of a distraction than mine.
