### ISSUE TITLE
Make multivariate compositor/reducer, that creates multivariate method by applying transformers/forecasters per-variable

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1038]
We should make the following compositors:

- [ ] a transformer that applies an univariate (or any other) series-to-series transformer to each series/variable
- [ ] a forecaster that applies an univariate (or any other) series-to-series forecaster to each series/variable

The first should be possible right now, the second will require #980.

The first one should solve #1030.

**Comment by SveaMeyer13** [comment]
Happy to work on this!

**Comment by aiwalter** [comment]
great idea, would this be sth equivalent to `sklearn.ColumnTransformer`, right? So would it be possible to select some columns or would it apply a transformer just to all columns?
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by SveaMeyer13** [comment]
@fkiraly would smth like this go into the direction you have in mind: 

class MultivariateCompositor(_SeriesToSeriesTransformer):
    """
    Parameters
    ----------
    transformer : series-to-series transformer to be applied to each series

    """
    _required_parameters = ["transformer"]


    def __init__(self, transformer):
        self.transformer = transformer
        self.transformers_ = None
        super(MultivariateCompositor, self).__init__()

    def fit(self, Z, X=None):
        """
        Iterates over columns (series) and applies the fit function of the transformer
        """
        if not isinstance(Z, pd.DataFrame):
            raise ValueError("Z needs to be a multivariate series as a pd.DataFrame")
        self._is_fitted = False
        z = check_series(Z)
        self.transformers_ = []
        for col in z:
            transformer = clone(self.transformer)
            self.transformers_.append(transformer)
        self._is_fitted = True
        return self

    def transform(self, Z, X=None):
        """
        calls transform on every single transformer (one transformer per series)
        """
        self.check_is_fitted()
        if not isinstance(Z, pd.DataFrame):
            raise ValueError("Z needs to be a multivariate series as a pd.DataFrame")
        z = check_series(Z)
        for col, transformer in enumerate(self.transformers_):
            transformer.check_is_fitted()
            z[col] = transformer.transform(Z,X)
        return z

@aiwalter Happy to change it in a way that it only iterates over specified columns


But what I find hard to decide is how to include functions that are peculiar to a specific transformer (everything that is not fit or transform). The detrender for example also has the functions update and inverse transform.

**Comment by fkiraly** [comment]
PS: @mloning has said that the forecaster does not depend on #980. I think that's right, though it means implementing the conversion and case distinction functionality in `_fit`.

**Comment by Lovkush-A** [comment]
I'm happy to work on the second task.

@fkiraly @mloning Are there any design discussion we need to have in advance? I anticipate something like this:

* Have a function `make_multivariate_forecaster`, similar to `make_reduction`
  * For now, there will only be one strategy, `by-column`, or similarly named
  * I do not know if there are other reduction strategies, but maybe there are. Regardless, I think we should write it in a way that fits into a potential general reduction framework of 'input scitype, output scitype, strategy'
* Have a new class like `ColumnByColumnForecaster`
  * to initialise object, have something like new_forecaster = ColumnForecater(univariate_forecaster)
  * while waiting for #980, this new class would over-write `fit` and `predict` to skip the checks (and prevent various tests from failing), and when that is sorted, method names changed to `_fit` and `_predict`

**Comment by fkiraly** [comment]
This is the `ColumnEnsembleForecatser`, added in #1082.
