### ISSUE TITLE
simple refactor of data io

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1043]
the function load_UCR_UEA_dataset is currently in datasets/base.py. I would prefer it in utils/data_io.py. If someone wants an easy issue to get started, then they can refactor this function so it is in data_io.py.

**Comment by TonyBagnall** [comment]
further to this, the method _load_dataset should also move.

**Comment by fkiraly** [comment]
agreed, should all be in one place. Perhaps sorted by the "scitype" of data it loads

**Comment by Patil2099** [comment]
I would love to pick this up.

**Comment by TonyBagnall** [comment]
its yours!

**Comment by mloning** [comment]
Isn't `utils.data_io` for utility functions, whereas `datasets` is for data sets? In scikit-learn these functions are also in `datasets`. But no strong preference here.

**Comment by TonyBagnall** [comment]
well I view datasets for datasets, not for data processing or input output myself. I view loading or saving data as a utility. Once its all sorted out in one place we can move it if necessary, I'll look at the scikit structure

**Comment by mloning** [comment]
I think it also makes sense to distinguish between loading data from files included in the package and fetching/downloading new data (see scikit-learn) in the function names.

**Comment by TonyBagnall** [comment]
> I think it also makes sense to distinguish between loading data from files included in the package and fetching/downloading new data (see scikit-learn) in the function names.

I dont really agree with this, I dont like the whole load_airplane etc model, since it gives the user absolutely no clue of how to load their own data. Likewise I dont like examples that simply create an array, the R style.

**Comment by KishenSharma6** [comment]
@TonyBagnall is this still open? I'd like to take a stab at this one as a newbie to open-source

**Comment by TonyBagnall** [comment]
hi @KishenSharma6, sure go for it.

**Comment by TonyBagnall** [comment]
however, I am just pushing a change to the data_io, so you might want to wait a bit

**Comment by TonyBagnall** [comment]
hi @KishenSharma6, after a review of this and the problems I've had with testing using using a global singleton root, I have reversed my position and will move all the data_io to datasets, so this issue is no longer required, sorry. If you want a good starter issue let me know and we can find you one

**Comment by KishenSharma6** [comment]
Ah thanks for letting me know @TonyBagnall ! Yes, feel free to add me to a few other issues you see fit. I am still getting familiar with the docs, happy to contribute as much as I can
