### ISSUE TITLE
[DOC] forecasting tutorial - too large file witih printouts?

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1052]
It seems that the forecasting tutorial, as current, is too large to be viewed inside the browser on GitHub directly, with images (3.3 MB).

Not sure what to do about this - only load some images? Remove some plots?

I've reverted to the "small" version for the time being.

Thoughts, @aiwalter, @mloning?

**Comment by aiwalter** [comment]
was it the "Reload?" problem when you tried to view the notebook in the browser? Because this is a longer existing bug of Github that you have to press this sometimes 5-10 times to get the notebook loaded in the end.

**Comment by fkiraly** [comment]
>Because this is a longer existing bug of Github that you have to press this sometimes 5-10 times to get the notebook loaded in the end.

Yes, but I believe it has to do with the file size?

**Comment by aiwalter** [comment]
I also faced it with short notebooks

**Comment by mloning** [comment]
Note that the notebooks are also shown at: https://www.sktime.org/en/latest/tutorials.html.

**Comment by fkiraly** [comment]
@mloning, what's wrong with the section headers in the html? Why does it not recognize all?

**Comment by fkiraly** [comment]
there isn't a clear pattern that I can recognize whith section headers are in the table of contents box and which aren't - any great ideas how to get only the "level 3 and higher" headers?

**Comment by mloning** [comment]
Sorry, no idea about the section headers.

**Comment by fkiraly** [comment]
The current tutorial does not contain images that are re-computed, so resolved.
