### ISSUE TITLE
unit tests for estimator method side effects

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1073]
Currently, it seems we have no tests that check estimator methods for side effects on the arguments?
(see also #1042 - before I thought we had)

This should be relatively easy to add - checking whether passing arguments to `fit` etc changes the argument.
The only complication is that some methods have to be called before others, e.g., `fit` before `predict`.

**Comment by fkiraly** [comment]
Being worked on here #1078

**Comment by mloning** [comment]
It's interesting that scikit-learn does not test for this but instead exposes this through `copy` hyper-parameters in estimators. This may be a sensible option, especially for larger data sets and more complex models in which now all components would store a copy of the data if I understand this correctly. 

#1078 still seems like the next logical step at this point. If we want to allow for side effects for better memory efficiency, we could then modify the tests that checks if a `copy=False` hyper-parameter has been set.

**Comment by fkiraly** [comment]
>I'm not sure though if eventually we want to allow for side effects again on the input data

If at all, we really need to think this through very carefully...
