### ISSUE TITLE
Forecasters to have a default ForecastingHorizon of fh=[1] if fh is not given (None)

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#1076]
**Is your feature request related to a problem? Please describe.**
I would like to propose to have a default 1-step ahead `fh` for all forecasters. Motivation is, that 1-step ahead forecast is often used and a default would simplify the interface and UX.

**Describe the solution you'd like**
We could just catch cases where `fh is None` and set it to `fh=[1]`. We have to see how this works with absolute `fh`.
```python
forecaster = NaiveForecaster()
forecaster.fit(y)
forecaster.predict()
```
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by fkiraly** [comment]
Agreed, this is a very sensible default.

The only thing we should think about what would happen if the index of `y` is not regular, and not float/integer but some date index. Error message? Sth else?

**Comment by mloning** [comment]
Agreed, this makes sense. 

One potential source of confusion may be the forecasters that require `fh` in `fit` if users are not aware of this. In that case, passing no `fh` in `fit` would result in `fh=1` during fitting and if a users passes some other `fh` in `predict` it won't work.  Not sure how to best handle this.

**Comment by aiwalter** [comment]
the index type is already checked somewhere when fitting the model I think?

**Comment by aiwalter** [comment]
@mloning we could handle this by just setting the default `fh=[1]` in `predict()` and not before? Not sure also if the default should be given in the function already like
```python
def predict(fh=[1], X=None):
    sth = "sth"
    return y_pred
```
or if we should still have `fh=None` and then have a separate check inside `predict()` to set default `fh`?

**Comment by TonyBagnall** [comment]
having just done some forecasting from completely cold, I agree this is a good idea, it took me a bit  of time to figure out the horizon

**Comment by mloning** [comment]
@aiwalter the problem with that is that if people specify a different horizon in `_fit` for the forecasters that need the horizon, having a default in `_predict` which may be different from what was passed in `_fit` may lead to errors and more confusion. 

If we just want to provide a default for the forecasters that do not require `fh` in `fit`, it needs to happen in `_set_fh` I think. Alternatively, we can set the default in `fit` for all forecasters, but then users may be confused if they want to pass it `predict`. This turns out to be a bit trickier than I thought ...

**Comment by fkiraly** [comment]
Regarding handling the default, I think the issue above is simple to cover by substituting the default the first time you need it. That's precisely the time the errors would be raised in the `_set_fh` logic when none is passed - so you would replace the error by the default. 
Though I do agree that this makes the behaviour a bit opaque to the user.

**Comment by mloning** [comment]
@fkiraly would that mean that in `_fit` and `_predict` we always have to use `self.fh` rather than the `fh` passed as an argument?

**Comment by fkiraly** [comment]
No, that's not what I mean. I mean that whenever the "no `fh` found but is needed" error would be raised, instead the default could be substituted - inside `_set_fh` which has the error raising logic.

**Comment by mloning** [comment]
Ah, okay, yes, if I understand it correctly that would currently happen in the property `self.fh`, not sure if that's the right place though.

However, note that this may still be confusing for the forecasters that require `fh` in fit, as users may expect to be able to pass the `fh` in predict, but predict will then complain that it has already been fitted using a different `fh`. 

Given this potential confusion, I'm not sure if we want to set a default. Let me know if I misunderstand anything here.

**Comment by fkiraly** [comment]
>Ah, okay, yes, if I understand it correctly that would currently happen in the property `self.fh`, not sure if that's the right place though.

>However, note that this may still be confusing for the forecasters that require `fh` in fit, as users may expect to be able to pass the `fh` in predict, but predict will then complain that it has already been fitted using a different `fh`. 

No, I think you are still misunderstanding, and also you are missing a "do not" before "require"?

Look at the `_set_fh` method and how it is called in `fit` and `predict`. Inside `_set_fh` there is a decision tree which raises an error "`fh` must have been passed", and this is raised whenever the latest point is at which the `fh` must e passed.

If you set the default at the point where this error would be raised (which is what I am suggesting), then the behaviour that you describe would not occur. Because in the forecasters that do not require `fh` in `fit`, the default would only be set if no `fh` is passed in `predict`.

Happy to spell this out in more detail, is this still unclear?

**Comment by mloning** [comment]
Okay so the idea is to set a default fh for forecasters that do not require fh in fit, but not for those that do, yes?

**Comment by fkiraly** [comment]
Coming from the discussion #1106 with @angelpone, I was wondering whether a more sensible default for the `fh` wouldn't just be `y.index`, i.e., default is always to make in-sample forecasts. I think that might actually be more natural.

Opinoins, @angelpone, @aiwalter, @mloning?

**Comment by aiwalter** [comment]
I think the default should cover ideally the most intuitive and most often applied case. I think this is

- forecasting in the future not in the past
- forecasting with 1 step ahead. Other common use case might be forecasting one season (`sp`) but not each data has a season and its not always possible to capture it automatically from the data. 

So that is why `fh=[1]` is the most reasonable default in my opinion.

**Comment by mloning** [comment]
I agree with @aiwalter, the only problem is that `fh=1` will introduce confusion for forecasters that require the `fh` in fitting. Don't have a preference here over whether the benefit of a default outweighs the potential confusion it introduces.

**Comment by fkiraly** [comment]
>So that is why fh=[1] is the most reasonable default in my opinion.

Disagree, because it's not obvious what this should be in the non-periodically (irregularly) indexed case.
Whereas the in-sample forecast generalizes easily to that case.

**Comment by TonyBagnall** [comment]
I'm just butting in, feel free to ignore me, but this seems to have gone from being a simple enhancement to something quite complex. Perhaps drop the idea for now?

**Comment by fkiraly** [comment]
maybe that's the best of all the ideas, @TonyBagnall?

**Comment by aiwalter** [comment]
agree, seems the impact of implementing this is much bigger than the benefit it will bring. So I will close this issue for now. Thx anyway for the discussion.
