### ISSUE TITLE
[BUG] Prophet with logistic growth does not work

### ISSUE THREAD

**Issue by muzibai** [alan-turing-institute/sktime#1079]
**Describe the bug**
It is not compatible with the case that the growth parameter of prophet is equal to ‘logistic‘

**To Reproduce**
```python

from sktime.datasets import load_airline
y = load_airline()
y = y.to_timestamp(freq="M")
y_train, y_test = temporal_train_test_split(y, test_size=36)

y_train_df = pd.DataFrame(y_train,index = y_train.index,columns=['y'])
y_train_df["cap"] = max(y_train_df["y"])
y_train_df['floor'] = 0

forecaster = Prophet(
    growth = 'logistic'
)

forecaster.fit(y_train_df)
```

**Expected behavior**

The growth parameter compatible with prophet is equal to ‘logistic‘
**Additional context**

**Versions**
<details>

from sktime import show_versions; show_versions()

System:
    python: 3.8.3 (default, Jul  2 2020, 11:26:31)  [Clang 10.0.0 ]
executable: /Users/baixiaotiao/opt/anaconda3/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
          pip: 20.1.1
   setuptools: 49.2.0.post20200714
      sklearn: 0.24.2
       sktime: 0.6.1
  statsmodels: 0.12.2
        numpy: 1.20.3
        scipy: 1.5.0
       Cython: 0.29.21
       pandas: 1.2.5
   matplotlib: 3.2.2
       joblib: 0.16.0
        numba: 0.50.1
     pmdarima: 1.8.2
      tsfresh: None

</details>

**Comment by mloning** [comment]
Yes, I can confirm this, this is because setting the growth parameter to "logistic" requires passing a `pd.DataFrame` with additional columns "cap" and "floor". 

This is related to #980.

**Comment by Lovkush-A** [comment]
> Yes, I can confirm this, this is because setting the growth parameter to "logistic" requires passing a `pd.DataFrame` with additional columns "cap" and "floor".

What do you mean by 'I can confirm this'. Are you saying there should be a bug? Or are you saying that passing the correct dataframe would fix the bug?

I ask because in the example code, a dataframe with columns cap and floor has been passed.

**Comment by mloning** [comment]
@Lovkush-A I just meant that I can reproduce the error and that I agree with @muzibai that we're currently not covering that use case.

**Comment by Lovkush-A** [comment]
Thanks for explaining Markus. I think this bug would be a useful way to compare the different input/output frameworks that are in discussion!

@fkiraly How would your framework deal with a class in which the inner-type depends on user-input?

**Comment by fkiraly** [comment]
>@fkiraly How would your framework deal with a class in which the inner-type depends on user-input?

Assuming that "user input" means behaviour controlled in parameters, the paradigm would be reading the parameter in `_fit` and dealing with any additional conversion or input logic there. `fit` would be set up to pass through the supported inner types and otherwise convert to them.

**Comment by fkiraly** [comment]
Abandoned attempt to fix this here, maybe a good starting point for future developers
https://github.com/alan-turing-institute/sktime/pull/1868

**Comment by fkiraly** [comment]
Report of closely related behaviour by @obtorres here:
https://github.com/alan-turing-institute/sktime/issues/2444
