### ISSUE TITLE
[BUG] HampelFilter has side effects on arguments

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1080]
`HampelFilter` has side effects on its arguments - see #1078 and test logs.

No estimator should have side effects, so this needs fixing.

**Comment by aiwalter** [comment]
good catch, thx! I will fix it. What do you think about handling this `y = y.copy()` stuff in the parent class? Basically each transformer needs to have it I think. I could create an issue for it, but would anyway first fix the `HampelFilter` issue separately.
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by fkiraly** [comment]
Yes, we need a big transformer refactor soon-ish, I think - I'd suggest to focus on `HampelFilter` though first so we can move the side effect test in before we start with the refactor.

**Comment by fkiraly** [comment]
>good catch, thx! 

And that's exactly why I wrote the test!
