### ISSUE TITLE
Redesign check_X and check_X_y, factor out conversion functionality

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1087]
check_X and check_X_y follow the scikit learn strategy and do more than check_X and y. They also convert data types. This is poor engineering and, with classifiers in particular, makes modular design complicated. I propose we decouple these two operations into separate functions, so that check_X simply checks the validity of input (is it a series or a panda?) and then "coercion" happens separately. We can in the first instance decide on how to do this without deciding on where to do it (related structural issues). Decide on names, what checks, what coercion etc

check_X and y varients
    simply makes sure the input is actually valid (and we decide what that means)
data structure transform:
we can either do this in one function, or write a range of functions

as to where to do these in a fit/_fit model, in the first instance I think checking can always be done in the base class fit, but data structure transform is, in the first instance, done in the estimator _fit.

**Comment by fkiraly** [comment]
Agree with everything except the last sentence, last half: I think data transform should *by default* be done in `fit`, controlled by descriptive estimator tags/capabilities or declarative init parameters, and can be done additionally (as "exception to the rule") in `_fit`. This is to avoid boilerplate code, where we have repeated conversion logic on the estimator `_fit` (implemented by individual estimators, base class many locations) as opposed in `fit` (in the base class, one location).

**Comment by TonyBagnall** [comment]
ok, that is an open question of design and touches on a lot of issues. I think first lets decide on how to do it in a practical sense rather than where it should happen.

1. What to call the data transform function/functions?
2. Where to put them?
2. should it be one function to do it all, or a pick and mix?
3. what transforms do we need?

**Comment by fkiraly** [comment]
(renamed the issue since it´s not side effects in the sense of the word)
