### ISSUE TITLE
Refactor (mini)rocket transformers / classifiers

### ISSUE THREAD

**Issue by Lovkush-A** [alan-turing-institute/sktime#1095]
In PR #1041, we discussed possibility of refactoring rocket transformers. Following an excellent call with @angus924, this will be going ahead!

Steps required:
- [ ] design refactored transformers/classifiers
- [ ] decide how best to track/record historical versions of algorithm used in prevoius papers
- [ ] create appropriate documentation
- [ ] create appropriate unittests

**Comment by TonyBagnall** [comment]
thanks Matt, I think close the other issue and just go with this one

**Comment by Lovkush-A** [comment]
@TonyBagnall Hey Tony, Thanks for the nudge! I am no longer working on this nor will I be for foreseeable future.

The main thoughts I had were:
* break up code into more modular functions
* add docstrings for these modular functions to help explain what is happening
* maybe change variable names

I am fine with whatever you want to do with this issue. Can either label it as good first issue, or just remove it.

**Comment by TonyBagnall** [comment]
hi @Lovkush-A I think its a bit more than a good first issue. I agree a tidy up would be good, but I am trying to keep a lid on the number of stale issues. I'll add it to my classifier dev list though
