### ISSUE TITLE
tests refactor: move default parameter settings into concrete classes

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1098]
The framework has been refactored as descriged below.

Now, all there is to do is to move the defaults from the `tests/_config` file into the individual estimator's `get_testing_params`.

PRs are appreciated - if you work on this, please post below which estimators you are helping with refactoring to avoid duplication.

---

We should refactor the default settings in `_config`.

Currently, `_config` has two things related to default settings:

* default "inhabitants" of key scitypes, within and outside `sktime`
* default parameter settings for each individual concrete estimator

I would go and locate these within the boundaries of their "natural concern":

* default parameter settings as an inspectable attribute of the class it is a default for. This should support a single setting, or multiple settings. I would make a method `get_testing_param_defaults` or similar. Imports of components etc should happen inside this method, to avoid strong coupling of modules and circular imports.
* default inhabitants of scitypes should move to the registry. I would suggest a method `get_example(scitype : str)`, which implements an extensible dispatch mechanusm similar to #1097.

I think this would declutter the logic a lot, and make extending `sktime` much easier - since it reduces the "points of extension" by one. Defaeult parameters would no longer have to be entered in `_config`, but become part of the list of things to implement, in the extension template.

**Comment by Aparna-Sakshi** [comment]
@fkiraly I want to work on this issue. From what I understood, instead of setting the parameters every time inside _config, one could use a function like get_testing_param_defaults to set the default parameters. Could you please guide me as to how I should approach this task as I am new to sktime?

**Comment by fkiraly** [comment]
Yes, very much agreed! You can have the issue, no one is working on this.

I'll try post some more details as a STEP today evening.

**Comment by Aparna-Sakshi** [comment]
@fkiraly Thanks a lot! I have also sent you a dm in discord.

**Comment by fkiraly** [comment]
I created a STEP here, have a look:
https://github.com/sktime/enhancement-proposals/pull/14

**Comment by fkiraly** [comment]
closing this in favour of #1678 which has a list of estimators
