### ISSUE TITLE
error in _predict_in_sample of ARIMA models

### ISSUE THREAD

**Issue by AngelPone** [alan-turing-institute/sktime#1106]
**Describe the bug**

I try to get all in_sample forecasts of fitted models, but error raised.

```python
ValueError: In-sample predictions undefined for start=0 when d=1
```

**To Reproduce**

```python
from sktime.forecasting.arima import AutoARIMA
from sktime.forecasting.base import ForecastingHorizon
from sktime.datasets import load_airline

y = load_airline()
model = AutoARIMA()
model.fit(y)
fh = ForecastingHorizon(y.index, is_relative=False)
model.predict(fh=fh)
```

**Additional context**

I checked out the source code, the error raised because `_pmdarima.py` use all absolute `fh`, e.g. `start=0, end=143` for the airplane series. But `ARIMA.predict_in_sample()` can't be `start=0` if there is difference `d`

**Versions**

same as latest `main`

**Comment by fkiraly** [comment]
Hm, is this truly a bug? `ARIMA` can't make an in-sample prediction for the first time points it's seen, it needs to "burn in" (I believe you need to see at least `d` many and better more).

So what I would do is to first `fit` it, and then use `update_predict_single` to get predictions for new data points - if you want in-sample, then ask for predictions at the time points you predict at (`fh = y.index`). Does this work?

**Comment by fkiraly** [comment]
Also, what behaviour would you *expect*, @AngelPone, can you perhaps sketch an example and command plus result? Not sure what it should be.

**Comment by AngelPone** [comment]
> Hm, is this truly a bug? `ARIMA` can't make an in-sample prediction for the first time points it's seen, it needs to "burn in" (I believe you need to see at least `d` many and better more).

I think it is.

> So what I would do is to first `fit` it, and then use `update_predict_single` to get predictions for new data points - if you want in-sample, then ask for predictions at the time points you predict at (`fh = y.index`). Does this work?

As shown in the sample code, the error raised when you try to pass `fh=y.index` to get in-sample forecasts for all observations, which are usually unexpected for the user, because  the **optimal** ARIMA model found by `AutoARIMA()` may have `d=0 or 1 or 2 ...`. Thus, if user want to get all in-sample forecasts, they would pass `fh=y.index`, and this error would raise.
