### ISSUE TITLE
[BUG] AutoARIMA, AutoETS, BATS, et al. can't be used in EnsembleForecaster

### ISSUE THREAD

**Issue by AngelPone** [alan-turing-institute/sktime#1111]
**Describe the bug**

I tried to use AutoARIMA and AutoETS in EnsembleForecaster, error raised

```
ValueError: The estimator type should be a Forecaster.
```

**To Reproduce**

```python
from sktime.forecasting.arima import AutoARIMA
from sktime.forecasting.ets import AutoETS
from sktime.forecasting.bats import BATS
from sktime.datasets import load_airline
from sktime.forecasting.compose import EnsembleForecaster

ensemble = EnsembleForecaster([("ARIMA", AutoARIMA),
                               ("ETS", AutoETS),
                               ("BATS", BATS)])
y = load_airline()
ensemble.fit(y)
```

**Expected behavior**

They can be used in EnsembleForecaster

**Additional context**

`EnsembleForecaster` checks the forecasters if are instance of `BaseForecaster` , but the models above inherit their adapters but not `BaseForecaster`, so the error raised

**Comment by aiwalter** [comment]
You forgot `()` like `AutoARIMA()`

**Comment by fkiraly** [comment]
@AngelPone, can you confirm that using objects (not classes) resolves your problem?

**Comment by AngelPone** [comment]
yes @fkiraly  problem solved.
