### ISSUE TITLE
[BUG] unexpected behaviour in Proximity Forest (unspecified)

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1114]
This is arising from #1026, TSC refactoring to the new `fit/_fit` model, which causes orchestration tests to break post-refactor, in `test_stat` in `test_orchestration.py`.

There is a `ProximityForest` used in the current orchestration test, which fails after the refactor. If it is switched out for basically any other time series classifier, the orchestration test passes. A medium-depth look at the tracebeek seems to suggest that it is some unexpected behaviour of `ProximityForest` rather than of the orchestration framework.

To reproduce the bug: clone #1026, but revert `test_orchestration.test_stat` to the pre-PR state.
Run `test_orchestration.test_stat`.

**Comment by TonyBagnall** [comment]
what is the actual error thrown and do you have a stack trace to give an indication of where it occurs? I am not familiar with the orchestration code. What is it actually testing?

**Comment by fkiraly** [comment]
I've opened a branch that reproduces the error, see PR #1122.

You should be able to see the trace if you go on any failing check.

Alternatively, you can manually run `test_orchestration.test_stat` in that branch.

**Comment by fkiraly** [comment]
Here is the traceback, @TonyBagnall:

```

    def test_stat():
        data = load_gunpoint(split="train")
        dataset = RAMDataset(dataset=data, name="gunpoint")
        task = TSCTask(target="class_val")
    
        fc = ComposableTimeSeriesForestClassifier(n_estimators=1, random_state=1)
        strategy_fc = TSCStrategy(fc, name="tsf")
        pf = ProximityForest(n_estimators=1, random_state=1)
        strategy_pf = TSCStrategy(pf, name="pf")
    
        # result backend
        results = RAMResults()
        orchestrator = Orchestrator(
            datasets=[dataset],
            tasks=[task],
            strategies=[strategy_pf, strategy_fc],
            cv=SingleSplit(random_state=1),
            results=results,
        )
    
>       orchestrator.fit_predict(save_fitted_strategies=False)

data       =                                                 dim_0 class_val
0   0     -0.64789
1     -0.64199
der        = []
x          = nan

/opt/_internal/cpython-3.6.14/lib/python3.6/site-packages/sktime/transformations/panel/summarize/_extract.py:120: TypeError
```

**Comment by TonyBagnall** [comment]
I have rolled this into the general PF issue, so will close this
https://github.com/alan-turing-institute/sktime/issues/1715

**Comment by fkiraly** [comment]
#1715, right?
