### ISSUE TITLE
Transformer refactor and refactor design

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1115]
With major modules undergoing interface change and uniformization, we should next look at the transformers.

Part of this should be settling on the target design.

What I could imagine is one or two tags that encode the transformer type, e.g., `trafo_input_type` and `trafo_output_type`, to replace the sub-classes/mixins that correpond to the individual type combinations here. Perhaps even a `scitype` tag that is a dict with these two?

This could be similar to what we did with the fh-mixins in forecasting.

Ideas, comments? @ABostrom, @aiwalter, @chrisholder, @Lovkush-A, @mloning, @SveaMeyer13, @TonyBagnall (pinging people who I know have recently worked and thought about transformers, feel free to add more or comment)

**Comment by RNKuhns** [comment]
What is everyone's thoughts about also adding deprecation to how the transformers are accessed, while doing the refactor? We already have to look into each class as part of the refactor, so it might be a good time to do this. 

Currently there isn't the ability to access the transformers from the `transformations` module or even `transformations.series`. 

So to access the BoxCox transformer, a user has to specify `from sktime.transformations.series.boxcox import BoxCoxTransformer`. I propose we shift toward `from sktime.transformations.series import BoxCoxTransformer` or `from sktime.transformations import BoxCoxTransformer`. 

The individual files would eventually become non-public (e.g. boxcox.py would then eventually become _boxcox.py). This would shift things towards the interface to the new clustering module (where implementations of `TimeSeriesKMeans` and `TimeSeriesKMediods` are accessed from `sktime.clustering`) after a suitable period of maintaining the current access with a deprecation message.

**Comment by fkiraly** [comment]
STEP is here https://github.com/sktime/enhancement-proposals/blob/main/steps/11_transformer_refactor/step.md

and draft refactor #1365

**Comment by mloning** [comment]
Closed by #1365
