### ISSUE TITLE
[ENH] Implement the Co-Eye algorithm

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1120]
hi, we would like to port in Co-Eye

Abdallah, Z.S., Gaber, M.M. Co-eye: a multi-resolution ensemble classifier for symbolically approximated time series. Mach Learn 109, 2029–2061 (2020). https://doi.org/10.1007/s10994-020-05887-3

invented by Zahraa Abdallah, who I think will be happy to help. It looks pretty easy, except for factoring out two dependencies from pyts and imblearn, which stops me making it a good first issue.  

https://github.com/zabdallah

Tony

**Comment by bilal-196** [comment]
Hi @TonyBagnall, I intend to implement Co-Eye, with regards to the pyts and imblearn dependencies, what do you suggest? The algorithm utilizes Symbolic Aggregate approXimation and SymbolicFourierApproximation which is imported from pyts and over sampling such as SMOTE from imblearn.

**Comment by TonyBagnall** [comment]
Hi @bilal-196 get it working with the imports on your fork first, and try to recreate some subset of their results (we can discuss which). Only then look at porting and pr into sktime

**Comment by fkiraly** [comment]
Can you kindly be more explicit about the reason for closing? Is this implemented? Or no longer relevant?
