### ISSUE TITLE
release 0.7.0 incomplete - investigate non-macos wheels

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1131]
it would appear that only the macos wheels for the 0.7.0 release were uploaded to pypi (via GitHub actions).

It is currently not entirely clear why, this had worked seamlessly before for 0.6.1, we ought to investigate this.

We're looking into this, but @mloning and myself are a bit short on time this week due to `scipy` conf and day jobs, so any help with looking into this is appreciated.

**Comment by mloning** [comment]
We should push single tags in `build_tools/make_release.py`, not all tags: `git push origin <tag_name>`

**Comment by fkiraly** [comment]
I assume the mistake was those "garbage tags" we pushed that were left over from 2019? So the command pushed 5 tags, not 1.

**Comment by mloning** [comment]
Yes, it seems like it was a combination of old tags and using annotated tags. Annotated tags do not trigger appveyor build through web hooks, only lightweight tags (see links below for more info).

I deleted the tag `v0.7.0`, both locally and on the remote repo, recreated it using `git tag v0.7.0` (without any annotations) and re-pushed it using `git push origin v0.7.0`. Both appveyor and azure are now triggered by the tags, let's wait for the builds to finish. 

Appveyor links:
* https://help.appveyor.com/discussions/problems/6209-build-is-not-triggered-for-tag
* https://help.appveyor.com/discussions/problems/2213-github-tag-not-recognized
* https://help.appveyor.com/discussions/problems/4267-pushing-tag-v040-results-in-build-of-branch-v040-tagged-v040
* https://help.appveyor.com/discussions/problems/3960-build-on-tag-wrongly-thinks-its-on-a-different-branch-than-master#comment_38902190
* https://help.appveyor.com/discussions/questions/2133-deploy-setting-for-nuget#comment_39280964

**Comment by fkiraly** [comment]
fascinating - google actions was triggered though!

**Comment by mloning** [comment]
Everything is working now, all wheels are online: https://pypi.org/simple/sktime/
