### ISSUE TITLE
ForecastingGridSearchCV to optionally return also best n forecaster

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#1136]
**Is your feature request related to a problem? Please describe.**
Currently, `ForecastingGridSearchCV` can only return `best_forecaster_`, however I would like to also get best `n` forecasters in order to create an `EnsembleForecaster` with them. Ensembling would probably especially work well in combination with using `MultiplexForecaster` to find the models which to use inside the ensemble.

**Describe the solution you'd like**
We could add a param like `return_n_forecaster=1` and if `>1` we could return a list `best_n_forecasters_`. The information of best `n` forecaster can be easily extracted from `results`, like done here for `best_forecaster_`:
https://github.com/alan-turing-institute/sktime/blob/7343dc36566935b42167878c45d570099af96dab/sktime/forecasting/model_selection/_tune.py#L292-L296

**Describe alternatives you've considered**
I could write a custom function to get this forecasters without contributing it to `sktime`. However I would need to be able to access `results` which is a `pd.DataFrame`.
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by mloning** [comment]
Sounds like a reasonable extension to me. But can you not get them from `gscv.cv_results_` already? 

If we want to add this, I would:
* call the kwarg `return_n_best_forecasters=1`
* add object variable `n_best_forecasters_` which is a list of length `(f"rank_{i}", <forecaster>)` tuples (for i = 1 ... n), that way they can be passed directly into an ensemble class

**Comment by aiwalter** [comment]
Ok, thx for quick feedback. Ah yes, using `gscv.cv_results_` would already work also probably. I will implement this then as you have proposed.

**Comment by aiwalter** [comment]
closed by #1139
