### ISSUE TITLE
TSC refactor

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1146]
Time series classifiers should be refactored according to the [new extension template](https://github.com/alan-turing-institute/sktime/blob/main/extension_templates/classification.py).

If you would like to work on this: *please post here* and which classifier you are taking on, to avoid duplication of work.
A core dev will then add your name to the classifier under refactor and/or link the PR.

Checklist of classifiers:

- [ ] `BaseColumnEnsembleClassifier`
- [ ] `ComposableTimeSeriesForestClassifier`
- [x] `BOSSEnsemble`, `IndividualBOSS` https://github.com/alan-turing-institute/sktime/pull/1544
- [x] `ContractableBOSS` https://github.com/alan-turing-institute/sktime/pull/1295
- [x] `MUSE` https://github.com/alan-turing-institute/sktime/pull/1359
- [x] `TemporalDictionaryEnsemble`, `IndividualTDE` https://github.com/alan-turing-institute/sktime/pull/1357
- [x] `WEASEL` https://github.com/alan-turing-institute/sktime/pull/1544
- [x] `MUSE` https://github.com/alan-turing-institute/sktime/pull/1544
- [x] `ElasticEnsemble` #1584
- [x] `ProximityForest`, `ProximityStump`, `ProximityTree` #1584
- [x] `ShapeDTW` https://github.com/alan-turing-institute/sktime/pull/1554
- [ ] ~~`KNeighborsTimeSeriesClassifier`~~ (inherits from _KNeighborsClassifier and calls a version of self._fit in its current fit)
- [x] `Catch22Classifier` #1487
- [x] `MatrixProfileClassifier` https://github.com/alan-turing-institute/sktime/pull/1545
- [x] `SignatureClassifier` https://github.com/alan-turing-institute/sktime/pull/1545
- [x] `TSFreshClassifier` #1473 
- [x] `HIVECOTEV1`  #1504
- [x] `CanonicalIntervalForest` https://github.com/alan-turing-institute/sktime/pull/1269
- [x] `DrCIF` https://github.com/alan-turing-institute/sktime/pull/1269
- [ ] ~~`TimeSeriesForestClassifier`~~ (bit complicated, involves the series_as_features base class)
- [x] `RandomIntervalSpectralForest` #1583
- [x] `SupervisedTimeSeriesForest` #1583
- [x] `Arsenal` https://github.com/alan-turing-institute/sktime/pull/1305
- [x] `ROCKETClassifier` https://github.com/alan-turing-institute/sktime/pull/1239
- [ ] ~~`MrSEQL`~~ (deprecated)
- [x] `ShapeletTransformClassifier` #1490

A general recipe for the refactor is as follows:

* go through all the public methods, `fit`, `predict`, etc, and change them to the new private version `_fit`, `_predict`, etc
* remove input checks (e.g., `check_X`) and output operations (e.g., set cutoff) from the private version; make sure these are already all present in the `BaseClassifier`.
* if there's an input or output check/operation that looks like it should be in `BaseClassifier` but isn't, add a note to your PR and make it very explicit; consider adding it to `BaseClassifier` but make sure @TonyBagnall  and @fkiraly are aware of such a change (ping in PR and ask for review).
* make sure all the tests pass. Don't change any of the tests. (unless there is a really good reason, in which case please explain)
* if there's an inheritance tree (not just a single class) downstream from `BaseClassifier`, make sure you do the above for all nodes in the inheritance tree
* move any "properties" or "capabilities" fields to the `_tags` dictionary.
* If new tags are added, ensure they are added to the [tag registry](https://github.com/alan-turing-institute/sktime/blob/main/sktime/registry/_tags.py). Look up the classifier tags (using `registry.all_tags`) before you add any new ones. Ensure @TonyBagnall and @fkiraly are aware of changes to the tag registry (ping in PR and ask for review).

**Comment by bilal-196** [comment]
Hi @fkiraly, I have refactored BOSSEnsemble classifier, great if you could have a look at the below 3 points and share your feedback.

1. The capabilities tag in the class has been updated as below,

    _capabilities = {
        "multivariate": False,
        "unequal_length": False,
        "missing_values": False,
        "train_estimate": True,
        "contractable": False,
    }

2. I have also updated fit and predict methods as below,

 def _fit(self, X, y):
        """Fit a boss ensemble on cases (X,y), where y is the target variable.

        Build an ensemble of BOSS classifiers from the training set (X,
        y), through  creating a variable size ensemble of those within a
        threshold of the best.

        Parameters
        ----------
        X : pd.DataFrame of shape [n_instances, 1]
            Nested dataframe with univariate time-series in cells.
        y : array-like, shape = [n_instances] The class labels.

        Returns
        -------
        self : object
        """
        X, y = check_X_y(X, y, enforce_univariate=True, coerce_to_numpy=True)

def _predict(self, X):
        """Predict class values of n instances in X.

        Parameters
        ----------
        X : pd.DataFrame of shape [n, 1]

        Returns
        -------
        array of shape [n, 1]
        """
        rng = check_random_state(self.random_state)
        return np.array(
            [
                self.classes_[int(rng.choice(np.flatnonzero(prob == prob.max())))]
                for prob in self.predict_proba(X)
            ]
        )

3. In the tag register, I have added tags as below, please have a look and confirm if it is the right approach or you want any modifications,

BOSSEnsemble_TAG_REGISTER = [
    (
        "multivariate",
        "classifier",
        "False",
        "can classifier handle multivariate data (X)? no",
    ),
    (
        "unequal_length",
        "classifier",
        "False",
        "can classifier handle unequal length data (X)? no",
    ),
    (
        "missing_values",
        "classifier",
        "False",
        "can classifier handle missing values data (X)? no",
    ),

**Comment by fkiraly** [comment]
Great, thanks, @bilal-196!

Some comments, suggesting minor tweaks here and there:

* the capabilities should actually go in the `_tags` dictionary, not in a `_capabilities` dictionary.
* I would also give them the "capability" prefix and a postfix which input it refers to, i.e., `capability:unequal_length_X` and similar. Maybe @TonyBagnall has some comments/suggestions...
* the tags should not be added in a `BOSSEnsemble_TAG_REGISTER`, but in `sktime.registry._tags.ESTIMATOR_TAG_REGISTER`, and only once per tag.
* the change from `fit` to `_fit` looks good, but ultimately there shouldn't be any `check_` functions remaining in it. This should already be covered in the `fit` of `BaseClassifier.

Generally, happy to look at a PR and comment directly there.

**Comment by BINAYKUMAR943** [comment]
@fkiraly I would like to do this for cboss classifier.

**Comment by fkiraly** [comment]
@BINAYKUMAR943, sure, go ahead and make a PR!

@bilal-196, quick question: dud you end up making a PR for BOSSEnsemble, which might be useful for @BINAYKUMAR943?

**Comment by bilal-196** [comment]
@fkiraly , yes indeed. I can share it with @BINAYKUMAR943 and also will discuss with him how to proceed. Thanks

**Comment by fkiraly** [comment]
@bilal-196, so I don't see a PR, is there one?
I think the best way to share would be making a draft PR to sktime directly, and sharing the link with @BINAYKUMAR943.

**Comment by bilal-196** [comment]
@fkiraly , Let me raise a draft PR now.

**Comment by bilal-196** [comment]
@fkiraly, @TonyBagnall , @ABostrom please have a look at this draft PR and share your feedback. Thanks

**Comment by victordremov** [comment]
Made a [PR for RocketClassifier](https://github.com/alan-turing-institute/sktime/pull/1239), could you kindly look at it? cc @TonyBagnall @fkiraly @MatthewMiddlehurst

**Comment by victordremov** [comment]
I've made a PR https://github.com/alan-turing-institute/sktime/pull/1332 for refactoring `Arsenal` classifier, but I guess it'd better wait until #1305 is merged to avoid very awful merge conflicts.

**Comment by kejsitake** [comment]
Hi! I made a PR #1341 for refactoring the _cif classifier, could you please look at it when you have some time?

**Comment by TonyBagnall** [comment]
this is done with the active classifiers, I'll close this @fkiraly and will raise specific issues for the compose and TSF, which are generally problematic.

**Comment by fkiraly** [comment]
What's with `BaseColumnEnsembleClassifier` and `ComposableTimeSeriesForestClassifier`?
