### ISSUE TITLE
[DOC] Declutter root directory

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#1159]
#### Describe the issue linked to the documentation
There are many files in the root directory at the moment. 

#### Suggest a potential alternative/fix
I suggest to move some of them into the docs folder, since they are also linked in the readme now. 

* GOVERNANCE.rst
* ROADMAP.rst
* ESTIMATOR_OVERVIEW.md
* CHANGELOG.rst

**Comment by fkiraly** [comment]
I think it's better if some of these remain in root with capitals, at least `CHANGELOG`.
Since there is some expectation to find it there. `ESTIMATOR_OVERVIEW` can go, perhaps even `ROADMAP`. I'd leave `GOVERNANCE` there though.

**Comment by fkiraly** [comment]
done by #1707
