### ISSUE TITLE
Add weights hyperparemeter to EnsembleForecaster API

### ISSUE THREAD

**Issue by RNKuhns** [alan-turing-institute/sktime#1162]
**Is your feature request related to a problem? Please describe.**
EnsembleForecaster does not currently accept weights. With #1136  and #1139 being worked on it would be nice to optionally allow users to pass weights to `EnsembleForecaster`. 

This would give users an out-of-the-box way to use ainverse error based weighting strategy in forecasting ensembles. Users could also supply other types of weights (information criterion, etc).  

**Describe the solution you'd like**
An update to the `EnsembleForecaster` API to allow weights to be passed (number weights should equal number of forecasters passed). 

This would require altering the `__init__` to store the weights, adding a check (in `_fit`?), and then updating `_predict` to use versions of the `aggfunc` that allow weights (for examples of this see use of _weighted_percentile, _weighted_geometric_mean, and np.average in performance_metrics\_functions.py).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fkiraly** [comment]
Hm, how does this relate to the online weighted ensemble and the hedge forecasters?
Would be good if you could look at both in detail, to avoid duplication or interface inconsistency.

**Comment by RNKuhns** [comment]
@fkiraly they are definately related. 

As a start, this would essentially be the "non-online" version of the `PredictionWeightedEnsemble` from the tutorial (which is built from the online ensemble). 

Since `OnlineEnsembleForecaster` inherits from `EnsembleForecaster` a second option (but not necessarily something we'd need to do) would be to also add a weights hyperparameter to the `OnlineEnsembleForecaster` that would initialize the weights based on user input (default would be to initialize as 1 / # of forecasters like currently done). 

I'd also like to improve the documentation in this area so its a bit more accessible, but have a few questions to verify my understanding. We can work on that separately.

**Comment by fkiraly** [comment]
>I'd also like to improve the documentation in this area so its a bit more accessible, but have a few questions to verify my understanding. We can work on that separately.

Yes, indeed - especially the methodological documentation. I have to admit I'm not exactly sure which algorithms are implemented there exactly, and this needs to be clarified and improved in the docs.

**Comment by RNKuhns** [comment]
Yep -- it is hard to figure that out from the documentation we have currently. I actually want take a crack at the user guide for forecasting to help make things more clear (and of course fix the docstrings as I go through that).

**Comment by GuzalBulatova** [comment]
Hi @RNKuhns I'd like to work on this 🚀

**Comment by RNKuhns** [comment]
@GuzalBulatova that works for me. @aiwalter and I have been talking about some options for the functionality. Maybe the three of us can find a quick time to talk. 

After digging into the online ensemblers per @fkiraly's comment above. I think that the current differences between that and `EnsembleForecaster` are currently that the online ensemblers use weights and update those weights (the online part). 

I think that it would be reasonable if the only difference was that the online ensembles update their weights (`EnsembleForecaster` would fix its weights based on the new `weights` hyperparameter).
