### ISSUE TITLE
Derive ForecastingHorizon from DatetimeIndex in predict method

### ISSUE THREAD

**Issue by Flix6x** [alan-turing-institute/sktime#1167]
**Is your feature request related to a problem? Please describe.**
Basically just a simplification request: converting from DatetimeIndex to ForecastingHorizon seems to me like a step that the `BaseForecaster` should be able to handle by itself. So instead of:

```
model = NaiveForecaster()
model.fit(train_data)
fh = ForecastingHorizon(test_data.index, is_relative=False)
forecast_data = model.predict(fh)
```

I would suggest users should be able to do:

```
model = NaiveForecaster()
model.fit(train_data)
forecast_data = model.predict(test_data.index)
```
which would be very elegant imo. It also removes the need to import `ForecastingHorizon`, which shortens user code and—and here's my selfish reason—possibly avoids adding sktime as an explicit dependency in libraries that want to be sktime compatible but do not want to depend on it.

**Describe the solution you'd like**
Perhaps the `BaseForecaster.predict` method can check whether its `fh` argument is a DatetimeIndex instance and run the necessary conversion itself?

**Comment by fkiraly** [comment]
Hm, could you kindly specify an example explicitly, with how it fails currently and what you want to happen instead?

Personally I think it should just forecast whatever index you pass, as long as it is compatible with the index in `fit`.

Currently, I think index inputs are being automatically wrapped by `ForecastingHorizon`, so if you are getting problems, it would mean it can't deal with `DatetimeIndex`?

>possibly avoids adding sktime as an explicit dependency in libraries that want to be sktime compatible but do not want to depend on it.

Yes, I think this is in line with `sktime` philosophy - extensible means it should be easy to be compatible without coupling, e.g., by using the extension templates and specifications.

Also, we're trying to move the "heavy" dependencies out of `sktime` in companion packages on mid-term, in case `prophet` and its friends worry you here...

**Comment by Flix6x** [comment]
Happy to oblige. Explicit example (from a different issue I worked on) below.

This one runs fine:

```
import numpy as np
import pandas as pd
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.naive import NaiveForecaster

data = pd.Series(
    index=pd.date_range(
        "2021-06-01 00:00", periods=12, freq="1h", closed="left"
    ),
    data=[1, 2, 3, 1, 2, 3, np.nan, 2, 3, 1, 2, 3]
)
train_data = data[:7]
test_data = data[7:]

print(train_data)
# 2021-06-01 00:00:00    1.0
# 2021-06-01 01:00:00    2.0
# 2021-06-01 02:00:00    3.0
# 2021-06-01 03:00:00    1.0
# 2021-06-01 04:00:00    2.0
# 2021-06-01 05:00:00    3.0
# 2021-06-01 06:00:00    NaN
# Freq: H, dtype: float64

fh = ForecastingHorizon(test_data.index, is_relative=False)  # Hoping to remove this step
model = NaiveForecaster(strategy="last", sp=3)
model.fit(train_data)
forecast_data = model.predict(fh)

print(forecast_data)
# 2021-06-01 07:00:00    2.0
# 2021-06-01 08:00:00    3.0
# 2021-06-01 09:00:00    NaN  # GH918
# 2021-06-01 10:00:00    2.0
# 2021-06-01 11:00:00    3.0
# dtype: float64
```

While this one fails on `check_fh`:

```
import numpy as np
import pandas as pd
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.naive import NaiveForecaster

data = pd.Series(
    index=pd.date_range(
        "2021-06-01 00:00", periods=12, freq="1h", closed="left"
    ),
    data=[1, 2, 3, 1, 2, 3, np.nan, 2, 3, 1, 2, 3]
)
train_data = data[:7]
test_data = data[7:]

print(train_data)
# 2021-06-01 00:00:00    1.0
# 2021-06-01 01:00:00    2.0
# 2021-06-01 02:00:00    3.0
# 2021-06-01 03:00:00    1.0
# 2021-06-01 04:00:00    2.0
# 2021-06-01 05:00:00    3.0
# 2021-06-01 06:00:00    NaN
# Freq: H, dtype: float64

model = NaiveForecaster(strategy="last", sp=3)
model.fit(train_data)
forecast_data = model.predict(test_data.index)

print(forecast_data)
# 2021-06-01 07:00:00    2.0
# 2021-06-01 08:00:00    3.0
# 2021-06-01 09:00:00    NaN  # GH918
# 2021-06-01 10:00:00    2.0
# 2021-06-01 11:00:00    3.0
# dtype: float64
```

**Comment by fkiraly** [comment]
I quickly mocked sth up, @Flix6x, in #1169 - it appears the `ForecastingHorizon` constructor complains when getting a `pd.DatetimeIndex` instead of doing what I'd think is the obvious thing (from user perspective).

The tests still run for some time and I have to sign off now, but feel free to have a look (and help me debugging in case they break 😃 )

**Comment by fkiraly** [comment]
Well, thanks for bringing it up, @Flix6x! This behaviour was not on my mental map.
