### ISSUE TITLE
[BUG] load_japanese_vowels() returns the same dataset for training and testing

### ISSUE THREAD

**Issue by off99555** [alan-turing-institute/sktime#1171]
**Describe the bug**
`load_japanese_vowels` function returns the same dataset when `split="train"` and `split="test"`.
This causes the test accuracy to be 1.0 in the [Rocket multivariate demo](https://www.sktime.org/en/latest/examples/rocket.html#3.5-Classify-the-Test-Data)

**To Reproduce**

Just run this code and if there's no assertion error then my point is valid:

```python
from sktime.datasets.base import load_japanese_vowels  # multivariate dataset

X_train, y_train = load_japanese_vowels(split="train", return_X_y=True)
X_test, y_test = load_japanese_vowels(split="test", return_X_y=True)
for i in range(len(X_train)):
    for j in range(X_train.shape[1]):
        assert np.all(X_train.iloc[i,j] == X_test.iloc[i,j])
```

**Expected behavior**
Assertion fails because at least one of the series must not be equal. In fact, all the series must not be equal! So it needs to fail as early as in the first iteration.

**Versions**
<details>

System:
    python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\off99\anaconda3\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 52.0.0.post20210125
      sklearn: 0.24.1
       sktime: 0.7.0
  statsmodels: 0.12.2
        numpy: 1.19.5
        scipy: 1.6.2
       Cython: 0.29.23
       pandas: 1.2.4
   matplotlib: 3.3.4
       joblib: 1.0.1
        numba: 0.51.2
     pmdarima: None
      tsfresh: None

</details>

**Comment by mloning** [comment]
Thanks @off99555 - it looks like the loading functionality is correct but the train and test files [here](https://github.com/alan-turing-institute/sktime/tree/main/sktime/datasets/data/JapaneseVowels) are the same. Would you like to open a PR based on the data on timeseriesclassification.com?

**Comment by off99555** [comment]
@mloning Yes. Done that. Please check associated PR.

**Comment by TonyBagnall** [comment]
thanks for that, we will need to update the unit tests for other classifiers before we can merge your pull request @MatthewMiddlehurst could you take a look please?
