### ISSUE TITLE
[DOC] Update related software

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#1183]
#### Suggest a potential alternative/fix
* add a table for the packages we interface 
* add column for learning task if applicable

**Comment by RNKuhns** [comment]
The `tspreprocess` module should probably be removed as part of this. I was looking through some related software and noticed that it hadn't been updated in 4 years and most of its functionality was not implemented (classes just had `pass`).

**Comment by fkiraly** [comment]
well, I think it's still worth having abandoned packages on the list, but perhaps sort them in their own section.

Reason is, for me the table is like "citations", you'd still cite a paper if the authors are no longer working on the topic.

**Comment by mloning** [comment]
Closed in favour of https://github.com/alan-turing-institute/sktime/issues/1204
