### ISSUE TITLE
Critical difference diagrams

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1186]
as part of the development of analysis tools, it would be nice to be implement a way of generating critical difference diagrams for comparing multiple classifiers over multiple data sets of the form

![image](https://user-images.githubusercontent.com/9594042/126643854-43725afa-e8a6-4fe1-b26f-020eb53c5c2b.png)

solid bars represent cliques, within which it is assumed there is no signficant difference between classifiers. The test of difference can be the post hoc test suggested in the original paper 
https://www.jmlr.org/papers/v7/demsar06a.html
or the pairwise test used in tsml 
https://github.com/uea-machine-learning/tsml/tree/master/src/main/matlab
or if you really want to go to town, port in the Bayesian tests
https://github.com/janezd/baycomp/blob/master/tests/test_multiple.py

**Comment by fkiraly** [comment]
For cd diagrams, we could consider helping this repository
https://github.com/hfawaz/cd-diagram
to become a proper pypi package?

**Comment by TonyBagnall** [comment]
I'm not sure Hassan is still maintaining that repo, and I don't think we want to add it as a dependency. Better to adapt the matlab linked to above. @SveaMeyer13 the function criticaldifference.m does it the original way, criticaldifferencePairwise.m takes the cliques as input. Actually finding the p-values and then finding cliques are separate tasks

**Comment by fkiraly** [comment]
hm, this closely relates to @RNKuhns´s issue #1175 (which I wanted to give some input on later this week) - you get different CD for different tests, so there is a direct interface point.

**Comment by TonyBagnall** [comment]
See my comment on that thread already :)

**Comment by SveaMeyer13** [comment]
Hmm, I just figured that the benchmarking module already contains a function `plot_critical_difference_diagram()`. How exactly is my task different from what is done there? Can't we just use that?

**Comment by fkiraly** [comment]
oops - perhaps you really want to sit together with @ViktorKaz then, as I recommended?

**Comment by ViktorKaz** [comment]
yes, this is right, critical difference diagrams are already implemented. Initially, I was relying on [Orange](https://orangedatamining.com/) for the CD plots. At some point it was decided that we didn't want Orange as a dependency in sktime and @mloning implemented the method that you are referring to. I think the method does exactly what @TonyBagnall is describing but you can maybe double check that it behaves as you expect before closing the issue.

**Comment by TonyBagnall** [comment]
I had not seen this, although @mloning made some reference to his implementation which he couldnt find, I'm not sure why this is a class function rather than a static function, seems a bit OO for sktime. This does not function in the way I would like (input accuracies or errors, get a graph) and it does not input the errors or accuracies nor does it input cliques. @SveaMeyer13 I think your method will be much easier to use in stand alone code.

**Comment by fkiraly** [comment]
yes, and in the stand-up today I also suggested that perhaps the evaluator class should be refactored to call the standalone code instead of implementing the logic inside. Which may imply that it might be good to make a comparison between the functionality in the evaluator and outside.

**Comment by TonyBagnall** [comment]
I agree, but I think there is quite a lot to do there, and I think a roadmap for benchmarking  would be good. But it is not a high priority for me right now, I am focussing on improving classification and clustering
