### ISSUE TITLE
your main markdown page has broken links

### ISSUE THREAD

**Issue by m-r-munroe** [alan-turing-institute/sktime#1188]
**Describe the bug**

image showing error
https://imgur.com/2tJQVmO

**Comment by fkiraly** [comment]
very strange - not for me?
![image](https://user-images.githubusercontent.com/7985502/126710379-7b1781ac-f0ea-40b9-a03a-cbd4115dda84.png)

**Comment by m-r-munroe** [comment]
@fkiraly you wrote:
>> very strange - not for me?

Which is why the screenshot is a key element.  I don't know how to directly include images, but yours looks nice.

I have a new shot, which shows different than yours, but is at least not missing parts.  
https://imgur.com/lM3ub5w

Does it depend on the OS of the viewer?

**Comment by mloning** [comment]
Sometimes the badges fail to load, see https://github.com/badges/shields/issues/1568.

The other links should work hopefully.

**Comment by fkiraly** [comment]
so, it's resolved? or "not an issue"?

**Comment by fkiraly** [comment]
>Which is why the screenshot is a key element. I don't know how to directly include images, but yours looks nice.

Copy-past should do it, the GitHub interface will automatically recognize image files and embed them.

ALso, @m-r-munroe I guess it turned out not to be a bug, so we can close?

**Comment by m-r-munroe** [comment]
Team,

>> I guess it turned out not to be a bug, so we can close?

Yes please.

Michael Munroe | Lead Data Scientist | Cold Chain
Emerson COMRES | 1675 West Campbell Road | Sidney, OH 45365
T +1 937 493-8088 | M +1 480 316-9644

This e-mail and any attachments to it are intended solely for the addressee(s) named herein and may contain proprietary, confidential, or otherwise legally privileged information. If you are not the intended recipient, then be advised that any further dissemination, distribution, disclosure, use, or copying of the e-mail or its attachments is strictly prohibited and may result in civil and criminal penalties. If you received this e-mail in error, then please notify the sender by replying to this message, and also please permanently delete the e-mail and all of its attachments without copying or disclosing their contents.

From: Franz Király ***@***.***>
Sent: Friday, July 23, 2021 7:06 PM
To: alan-turing-institute/sktime ***@***.***>
Cc: Munroe, Michael [COMRES/REF/SID] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [alan-turing-institute/sktime] your main markdown page has broken links (#1188)


Which is why the screenshot is a key element. I don't know how to directly include images, but yours looks nice.

Copy-past should do it, the GitHub interface will automatically recognize image files and embed them.

ALso, @m-r-munroe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_m-2Dr-2Dmunroe&d=DwMCaQ&c=jOURTkCZzT8tVB5xPEYIm3YJGoxoTaQsQPzPKJGaWbo&r=XwjE-lBATU-G5-hERTMkA0J1y-FPtmNvQFKt7SQzhsc&m=GLCMBI91hIFmmesTOSv97JhpyzROoTrxkk1HMkj6E5Q&s=032kdihY2HmG089ErTWayW6Edm2gHI6OmoJJMcdlpO8&e=> I guess it turned out not to be a bug, so we can close?
