### ISSUE TITLE
Goals for release 4

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#122]
hi, release 3 is out, hurrah. We are all pro bono now, and there is a danger we all just leave it where it is. So I have started a project with a wish list for release 4 (or after). Please self assign to any projects you fancy contributing to, and then contact the initial proposer (person who added it in the first place).

**Comment by mloning** [comment]
Should we use milstones for that purpose? https://github.com/alan-turing-institute/sktime/milestones

**Comment by TonyBagnall** [comment]
good idea
