### ISSUE TITLE
Speed up classifier unit tests

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1235]
decrease the time taken by  the top 10 slowest significantly, I'll report progress here

![image](https://user-images.githubusercontent.com/9594042/127700492-6ab08707-5e9d-45da-8453-b1cdd7b4eb00.png)

**Comment by TonyBagnall** [comment]
![image](https://user-images.githubusercontent.com/9594042/128545702-c81ea0b8-a91e-4021-8abb-96f1ee739712.png)

simplest way to speed up the test_all_estimator tests would be to make the test set smaller. Any thoughts on that @mloning ?

**Comment by MatthewMiddlehurst** [comment]
Top 10 as of HC2 PR (build macos-10.15, 3.7).

![Capture](https://user-images.githubusercontent.com/25731235/137407258-60863f23-b09a-4970-ab3f-39d02aa23cfb.PNG)

**Comment by MatthewMiddlehurst** [comment]
I think 20s is a good goal for now at least. I don’t think reducing the top 5 will be a major challenge.

**Comment by TonyBagnall** [comment]
job done now, nice one @MatthewMiddlehurst 
![image](https://user-images.githubusercontent.com/9594042/141201452-85f8e0ac-4ff0-4414-a623-7353e2558ab6.png)
