### ISSUE TITLE
[ENH] Exception when X of predict(X) has not same length/index as given fh

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#1241]
**Is your feature request related to a problem? Please describe.**
When using a forecaster with exog data and giving e.g. an `fh=[1,2,3]` but the `X` in `predict(fh=fh, X=X)` has a different length or index shape, then there is only a cryptic error like this:
```
ValueError: X array dims (n_rows) != n_periods
```
But it should tell the user what exactly was wrong.
To reproduce:
```python
import pandas as pd 

from sklearn.model_selection import train_test_split
from sktime.datasets import load_longley

from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.arima import AutoARIMA

y, X = load_longley()
# enlarge data to be used by arima model
y = pd.concat([y]*5, ignore_index=True)
X = pd.concat([X]*5, ignore_index=True)

y_train, _, X_train, X_test = temporal_train_test_split(y, X)
forecaster = AutoARIMA(suppress_warnings=True, sp=12)
forecaster.fit(X=X_train,y=y_train)
forecaster.predict(X=X_test, fh=[1,2,3])
```
**Describe the solution you'd like**
Adding this to e.g. `check_X` and `check_y_X` so that we can give also an `fh` and it will compare them and raise a more descriptive exception if they dont match together. We have to add it to `BaseForecaster` then.

Exception message could be sth like:
```
Given ForecastingHorizon and X in predict() must have same length and index values.
```
@dbart79 fyi

**Comment by fkiraly** [comment]
This is related to the tags issue #981, namely the proposed capability whether the forecaster can deal with different time indices in `X`/`y`, or different time indices in `fh`,`X`.

**Comment by fkiraly** [comment]
This is a sub-case of current checks in `_check_X_y`, i.e., an error is raised for estimators with the tag `X-y-must-have-same-index` if the `X` indices do not *contain` the `fh` indices.
