### ISSUE TITLE
[DOC] Docstrings issues for upcoming Docsprint

### ISSUE THREAD

**Issue by RNKuhns** [alan-turing-institute/sktime#1245]
#### Describe the issue linked to the documentation

This will be used to track issues related to docstring improvements needed as part of the upcoming docsprint. 

Expectations about docstrings in sktime are summarized in #1297, and include the following: 

- Follow NumPy docstring conventions so they render in sktime's updated documentation website (https://www.sktime.org/en/latest/) and the documentation guide portion (https://www.sktime.org/en/latest/developer_guide/documentation.html)
- Ensuring all parameters and attributes (classes) are documented completely and consistantly
- Including links to the relevant topics in the online documentation's glossary and user guide's in the extended summary
- Including an `Examples` section that demonstrates at least basic functionality in all public code artifacts
- Adding a `See Also` section that references related sktime code artifacts as applicable
- Including citations to relevant sources in a `References` section

Module level docstrings should generally follow the format used by `scikit-learn`. For example, see [column transformer](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/compose/_column_transformer.py) or [compose](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/compose/__init__.py) or [ensemble](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/ensemble/__init__.py). Additional, but brief, information could also be included in some cases, but check with a core developer.

Note: when updating docstrings prioritization should be given to code artifacts that are part of the public API, followed by heavily used non-public code objects. 

#### Suggest a potential alternative/fix
The goal of the docstring section of the docsprint is to reform all docstrings in the following modules to our preferred format:
   - [ ] annotation
   - [ ] base
   - [ ] classification
   - [ ] clustering
   - [ ] distances
   - [ ] forecasting
   - [ ] performance_metrics
   - [ ] regression
   - [ ] transformations
        - [ ] Boxcox -- Ryan
        - [ ] LogTransformer -- Ryan
        - [ ] ExponentTransformer -- Ryan
        - [ ] SqrtTransformer -- Ryan
        - [ ] ThetaLines -- Guzal
        - [ ] Columnwise -- Guzal
        - [ ] TabularAdapter -- Guzal
        - [ ] Detrender -- Svea
        - [ ] Deseasonalizer -- Svea
        - [ ] ConditionalDeasonalizer -- Svea

**Comment by GuzalBulatova** [comment]
Working on 
[] transformations
     [] Theta -- Guzal

**Comment by SveaMeyer13** [comment]
I'll take care of the detrend module

**Comment by GuzalBulatova** [comment]
Will take care of 
- `ColumnWiseTransformer` in compose.py and 
- `TabularToSeriesAdaptor` in adapt.py

**Comment by fkiraly** [comment]
The 2021 docstring has concluded.
