### ISSUE TITLE
forecasting: rename misleading `univariate_only` tag to `uses_exogeneous`, correct instances

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1267]
Currently, the tag that indicates whether a forecaster makes use of exogeneous data or just ignores them is called `univariate_only`. This is misleading, since `y` could be multivariate, even though no exogeneous data are used - also, exogeneous data can be univariate if it hast just one column.

So, the tag should be renamed to sth like `uses_exogeneous`.

I also noticed it's not correct in a number of places, possibly due to extenders being confused by the name.
For instance, `pmdarima`'s AutoARIMA can make use of exogeneous variables, but the tag says it can't.

**Comment by RNKuhns** [comment]
The tag name does seem confusing. I was under the impression that it represented what it sounded like: the forecaster could only be used with univariate (not multivariate or panel) input data.
