### ISSUE TITLE
implement rotation forest

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#127]
Just to keep track of a few questions regarding the implementation of rotation forest:
* What do you do if the number of instances is smaller than the number of columns after subsetting, given that the number of components in PCA is `min(n_instances, n_columns)`? Add zeros?
* In the original paper, they resample instances with replacement (bootstrapped) as far as I understand, why do we sample without replacements?

Current versions are here:
* [Tony](https://github.com/TonyBagnall/py-hive-cote/blob/master/classifiers/time_domain_classification/RotationForestLastTony.py)
* [Markus](https://github.com/mloning/rotation_forest/blob/master/rotation_forest/rotation_forest.py), older version [here](https://github.com/alan-turing-institute/sktime/blob/rotf/sktime/contrib/rotation_forest/rotation_forest_reworked.py)
* [UEA implementation in Java](https://github.com/uea-machine-learning/tsml/blob/master/src/main/java/weka/classifiers/meta/RotationForest.java)
* [original implementation in Java](https://github.com/Waikato/weka-trunk/blob/master/packages/external/rotationForest/src/main/java/weka/classifiers/meta/RotationForest.java)

**Comment by TonyBagnall** [comment]
hi markus, I've assigned this to Aaron who wrote the initial Rotation Forest implementation. From distant memory
1) It does a weird generation of random samples if the matrix is ill conditioned and
2) in the code they sample without replacement. Sampling occurs independently on each sub group. 

but I cannot swear to either! I think your version and Aarons are out of sync, worth talking to him about it.

**Comment by ABostrom** [comment]
Hi,

Tony is correct. 

I'm going to have a look at this some more today.

**Comment by fkiraly** [comment]
About the question of @mloning :

>What do you do if the number of instances is smaller than the number of columns after subsetting, given that the number of components in PCA is min(n_instances, n_columns)? Add zeros?

PCA should still return the desired number of columns in this case, no?

**Comment by mloning** [comment]
Not sure what it should do in that case, but it returned number of components is min(n_instances, n_columns) or even min(n_instances, n_columns) - 1, see https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

**Comment by mloning** [comment]
Moved outside of sktime, as not time series specific.
