### ISSUE TITLE
[ENH] panel forecasting capability

### ISSUE THREAD

**Issue by roboswell** [alan-turing-institute/sktime#1272]
[edited by fkiraly, adding a description to an empty issue]

from [this discussion thread](https://github.com/alan-turing-institute/sktime/discussions/1271)

I think what this implicitly asks for is panel forecasting functionality, which is a special extended case of multivariate forecasting where the variables are indexed by a categorical.

It's also related to hierarchical forecasting, as the sub-case of a flat hierarchy - which is being worked on based on [this STEP](https://github.com/sktime/enhancement-proposals/pull/9)

**Comment by fkiraly** [comment]
@roboswell, you could use `pyhts` for now, as another alternative - we're looking to interface it.

FYI @angelpone

**Comment by fkiraly** [comment]
FYI @aiwalter, @danielbartling, @ltsaprounis, @satya-pattnaik

**Comment by fkiraly** [comment]
The merged PR #1818 includes framework functionality for panel, global, and hierarchical forecasting.
For now, this only upgrades all existing forecasters to make such forecasts by fitting an individual model per granular unit aka lower hierarchy level.
"Proper" panel and hierarchical forecasters, including reconciliation strategies, will be merged subsequently and implemented individually.
