### ISSUE TITLE
latex documentation compile errors

### ISSUE THREAD

**Issue by bldrake** [alan-turing-institute/sktime#1276]
version: sktime-0.7.0

command line:
make latexpdf

Failed to import 'sktime.transformations.panel.signature_based': no module named sktime.transformations.panel.signature_based
Failed to import 'sktime.datatypes': no module named sktime.datatypes
Failed to import 'sktime.benchmarking.experiments': no module named sktime.benchmarking.experiments
Failed to import 'sktime.utils.sampling': no module named sktime.utils.sampling
Failed to import 'sktime.forecasting.arima': no module named sktime.forecasting.arima
Failed to import 'sktime.forecasting.tbats': no module named sktime.forecasting.tbats
Failed to import 'sktime.classification.feature_based': no module named sktime.classification.feature_based
Failed to import 'sktime.benchmarking.evaluation': no module named sktime.benchmarking.evaluation
Failed to import 'sktime.forecasting.fbprophet': no module named sktime.forecasting.fbprophet
Failed to import 'sktime.forecasting.bats': no module named sktime.forecasting.bats
Failed to import 'sktime.classification.signature_based': no module named sktime.classification.signature_based
Failed to import 'sktime.transformations.series.exponent': no module named sktime.transformations.series.exponent

**Comment by bldrake** [comment]
updated issue:

Tried some fixes. Now have the one error:

Extension error:
Handler <function _make_estimator_overview at 0x7fbe434d4f70> for event 'builder-inited' threw an exception (exception: cannot import name 'all_estimators' from 'sktime.registry'

**Comment by mloning** [comment]
Hi @bldrake, I haven't actually tried to compile it to latex. Would be very interested in seeing your fixes. We're currently working on a new website (see https://github.com/alan-turing-institute/sktime/pull/1205). 

As to the import error, what sktime version are you using? The registry module was something we added relatively recently.

**Comment by bldrake** [comment]
Hello Markus,

Thanks for your reply! 
I am using sktime-0.7.0.
I think I have a work-around for the one remaining error. Haven't had time to implement and test.

Thanks,
Barry


________________________________________

**Comment by mloning** [comment]
Closing this now, @bldrake feel free to reach out again if you think we can help.
