### ISSUE TITLE
Improve documentation and tutorials

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#128]
- [x] add badge from https://zenodo.org
- [x] update sphinx generated website, see e.g. [tslearn's website](https://tslearn.readthedocs.io/en/latest/#)
- [x] use https://sphinx-gallery.github.io for displaying example notebooks on the website
- [x] add binder
- [x] update contributing and extension guidelines (folder structure, necessary API elements to implement, inheritance, etc.); for a new draft, see this [wiki entry](https://github.com/alan-turing-institute/sktime/wiki/How-to-get-started)
- [x] add `ESTIMATOR_OVERVIEW.md` to website and mention in `README.md`, it's already linked in the PR template (#225)
- [x] add [all-contributors](https://github.com/all-contributors/all-contributors) specification
- [x] add more issue templates, see https://github.com/scikit-learn/scikit-learn/tree/master/.github/ISSUE_TEMPLATE
- [x] include Changelog.md, see https://keepachangelog.com/en/1.0.0/ and https://www.conventionalcommits.org/en/v1.0.0/, numpy's helper function: https://github.com/numpy/numpy/blob/f1a247f9952085db72c3f8248f8336a0961d825c/tools/changelog.py
- [x] move website to our new domain in https://github.com/alan-turing-institute/sktime/settings

**Comment by MotoRZR** [comment]
I'd also add, show basic examples of going from typical long format time series to the nested dataframe.  The nested dataframe format is not something most are going to be familiar with and I've found the guidance here unintuitive.

**Comment by mloning** [comment]
Thanks for your feedback, I agree, the tutorials have to be improved here, if you worked through it yourself, we would really appreciate a PR!
