### ISSUE TITLE
should `test_examples` github action use build requirements, not binder requiremenets?

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1281]
From #1266, noticed that `test_examples` check uses binder requirements, and not build requirements, as I had naively expected.

Is there a good reason for that? Should it be changed? @mloning?

**Comment by mloning** [comment]
I don't remember, probably wanted to make sure that they work on Binder, hoping that if they work there, they work in general.

**Comment by fkiraly** [comment]
Since the CI-CD refactor #1620, this uses the `all_extras, binder, dev` dependency sets.
