### ISSUE TITLE
Implement Catch22 transformer

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#129]
Implement Catch22, described here https://link.springer.com/article/10.1007%2Fs10618-019-00647-x, as an sktime transformer.

Hopefully Carl Lubba and Bun Fulcher will help us with this. They have C implementations, I'm not sure whether we can just port in C or whether it needs to be made into Cython. Perhaps someone who knows more can comment, with the constraint we want to minimise dependencies

**Comment by mloning** [comment]
Closed by #453

**Comment by MatthewMiddlehurst** [comment]
Re-opening this. Road testing a number of classifiers that use the catch22 transform, they use a lot of memory even on relatively small datasets. Just calling the catch22 method from the C wrapper we use without storing anything rapidly increases memory used. Most likely a memory leak in the wrapper itself. Best option IMO would be to reimplement the catch22 features in Python for sktime using numba or something.

I may do this myself at some point, but if anyone else would like to take it on I can lend a hand. There are implementations in C and Matlab by the author, and a Java implementation by myself to draw from if necessary.

**Comment by TonyBagnall** [comment]
hi matt, I was thinking of asking an MSc student to work on this. I may also be able to fund a UEA intern, and this could be good for them too.

**Comment by TonyBagnall** [comment]
although if someone wants to take it on before that its completely fine! It is a good, fairly technical, first issue

**Comment by MatthewMiddlehurst** [comment]
Working on replacing the wrapper currently. Will hopefully make a PR this week.

**Comment by TonyBagnall** [comment]
@MatthewMiddlehurst this is done isnt it? Can we close?

**Comment by MatthewMiddlehurst** [comment]
Yeah I would consider this done. Any problems with the revamped transformer can be raised as new issues
