### ISSUE TITLE
branch protection on dev

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#130]
We should also protect dev, forcing everyone to work off their own branches. Any objections?

See similar discussion here: https://github.com/uea-machine-learning/tsml/issues/137

**Comment by TonyBagnall** [comment]
no objections, but I dont really want to require approval once it has passed travis checks

**Comment by mloning** [comment]
Yeah, code reviews/approvals are not necessary for dev I think

**Comment by mloning** [comment]
Put branch protection on dev, no reviews/approvals required
