### ISSUE TITLE
[DOC] Page for community showcase 

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#1313]
#### Describe the issue linked to the documentation
I would be nice to add a page to the About section on the website with community contributions (blog posts, reports, contributions, etc).

#### Suggest a potential alternative/fix
* Add community showcase page by adding a `sktime/docs/source/about/showcase.rst` file
* Remove Extra Resources section in `sktime/docs/source/user_guide/`
* Use https://github.com/sloria/sphinx-issues extension to link to GitHub users
* Adding a table for blogposts on that page would be a good start with 3 columns: title, date, short description, user. The first blog post to add could be:
  *  https://towardsdatascience.com/sktime-a-unified-python-library-for-time-series-machine-learning-3c103c139a55
  * https://medium.com/@jlenczuk/why-start-using-sktime-for-forecasting-8d6881c0a518

**Comment by afzal442** [comment]
Thanks @mloning for bringing up this nice gist of that issue. 

> Add a table for blogposts on that page would be a good start with 3 columns. 

Does this kind of feature already exist on the sktime website? plz let me know if it is so.

**Comment by mloning** [comment]
@afzal442 no, there isn't anything there yet

**Comment by mloning** [comment]
@afzal442 adding the `:user:` reference from the `github_issues` extension would also be a nice extension to the estimator overview, so that the authors who are listed in the table are linked to the GitHub accounts.
