### ISSUE TITLE
[BUG] failed building wheel for fbprophet

### ISSUE THREAD

**Issue by Lovkush-A** [alan-turing-institute/sktime#1327]
**Describe the bug**
When doing `pip install -r build_tools/requirements.txt`, I got error message:

```
  ModuleNotFoundError: No module named 'convertdate'
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
```

This did *NOT* break the installation, but it will break the installation at some point. `pip` produced this warning at the end of the installation process:

```
 DEPRECATION: fbprophet was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
```

**To Reproduce**
I am using MacOS. The steps I had taken in the environment were:
* create and activate new conda environment
* `conda install python=3.8`
* do the steps for mac involving `libomp` and adding things to environment file.
* `pip install cython`
* `pip install -e .`
* install precommit
* `pip install -r build_tools/requirements.txt`

**Expected behavior**
no error messages while (correctly) following installation instructions

**Additional context**

**Comment by mloning** [comment]
Hi @Lovkush-A, see if the trouble shooting section in the advanced installation instructions help: https://www.sktime.org/en/latest/installation.html#facebook-prophet

**Comment by Lovkush-A** [comment]
Thanks, @mloning. Using conda to install prophet avoided the building wheel error. Are there any potential issues with having `prophet` (as given installation guide) and `fbprophet` (which is in `build_tools/requirements`)? Do we want to move everything to `prophet`?

**Comment by RNKuhns** [comment]
I think this may also be related to #841.

**Comment by Lovkush-A** [comment]
Closing this issue. Main question has been answered and issue with prophet versus fbprophet is being dealt with in 841.
