### ISSUE TITLE
[ENH] ClaSP (Time Series Segmentation paper in CIKM '21)

### ISSUE THREAD

**Issue by patrickzib** [alan-turing-institute/sktime#1346]
**Is your feature request related to a problem? Please describe.**

I would like to add ClaSP (CIKM '21), a state-of-the-art method for time series segmentation (similar to FLOSS) and a SeriesToSeriesTransform to sktime.

**Describe the solution you'd like**

ClaSP create a single profile per time series. However, it would be nice to also return some additional information computed along ClaSP: 

Thus, I am currently struggling with the definition of:
`_SeriesToSeriesTransformer`

As a reference, I had a look at matrix_profile, which returns:
`return pd.Series(Xt[:, 0])`

Sorry, if I am missing out on something: Is there any means to return a tuple from transform?
`return profile, k_nn_distances, ...`

**Comment by fkiraly** [comment]
Great idea, though it should be an annotator, not a transformer - segmentation is a case of annotation..

have a look at the extension template here:
https://github.com/alan-turing-institute/sktime/blob/main/extension_templates/annotation.py

If you want to return more than the segmentation, you can use `get_fitted_params` where you can return anything you'd like.
I've noticed it's not in the annotation template, but the format is as in the [forecasting template](https://github.com/alan-turing-institute/sktime/blob/main/extension_templates/forecasting.py), it simply should return a dict and can return anything you'd like.

For distances, you may want to consider implementing a separate distance transformer, using the [time series distance/kernel extension template](https://github.com/alan-turing-institute/sktime/blob/main/extension_templates/dist_kern_panel.py).

**Comment by patrickzib** [comment]
Thank you very much! That was very helpful!

I am now trying to provide a Jupyter-Notebook alongside the code. However, when I import sktime packages, these are imported from my Anaconda sktime installation. Is there any way to import from my developer version instead?

**Comment by patrickzib** [comment]
@fkiraly This seems to be a workaround for my problem. 

```
import sys
sys.path.insert(0,"..")
```

Is there any better way?

**Comment by fkiraly** [comment]
yes, `sys.path.insert` and `sys.path.append` works - the other option is `pip install -e [dir location]`

Also see here: https://www.sktime.org/en/latest/installation.html
(section: development versions)

**Comment by patrickzib** [comment]
@fkiraly 
```
have a look at the extension template here:
https://github.com/alan-turing-institute/sktime/blob/main/extension_templates/annotation.py

If you want to return more than the segmentation, you can use get_fitted_params where you can return anything you'd like.
```
How would you implement the logic for segmentation: 

1. Do the segmentation in fit and use predict to return just the segmentation and get_fitted_params to return all other parameters?
2. Do the segmentation in predict and return just the segmentation and get_fitted_params to return all other parameters?

Intuitively, I thought about using predict to do the computation - but then get_fitted_params is misleading, as the computation was done in predict ...

**Comment by patrickzib** [comment]
@fkiraly Maybe my problem is that segmentation is an unsupervised task. Thus, we do not really have a need for fitting a model - instead we do a combined fit_predict() for every series. Thus it is a bit unclear how to match it to the framework.

**Comment by fkiraly** [comment]
@patrickzib added clasp in #1352 but we forgot to close this issue.
