### ISSUE TITLE
"Data must be univariate" on pipe.fit

### ISSUE THREAD

**Issue by roboswell** [alan-turing-institute/sktime#1350]
**Describe the bug**
 1 pipe.fit(y=y_train, fh=fh, X=X_train)
      2 y_pred = pipe.predict(fh=fh, X=X_test, y=y_test)

4 frames
/usr/local/lib/python3.7/dist-packages/sktime/utils/validation/series.py in _check_is_univariate(y)
     22     """Check if series is univariate."""
     23     if isinstance(y, pd.DataFrame):
---> 24         raise ValueError("Data must be univariate, but found a pd.DataFrame")
     25     if isinstance(y, np.ndarray) and y.ndim > 1:
     26         raise ValueError(

ValueError: Data must be univariate, but found a pd.DataFrame

Is there a way to use multivariate data in an X dataframe that will not give me this error?

**Comment by aiwalter** [comment]
hi @roboswell , could you pls provide the full code to reproduce? Pls also take care of formatting the code

**Comment by fkiraly** [comment]
in general, `X` can be multivariate - the error message sounds like it's coming from the `y` though.
Not all forecasters can handle multivariate `y`. As @aiwalter said, full code to reproduce the problem would be helpful.

**Comment by aiwalter** [comment]
I already see that sth is wrong here:

> pipe.predict(fh=fh, X=X_test, y=y_test)

`y` should not be given in `predict()`

**Comment by fkiraly** [comment]
yes, it's `_predict(self, fh, X)`

**Comment by roboswell** [comment]
> hi @roboswell , could you pls provide the full code to reproduce? Pls also take care of formatting the code/exception message

The actual dataframe is huge, so I can't reproduce the whole thing, but here is a snapshot:

![image](https://user-images.githubusercontent.com/72875675/130527193-957b2fdf-b92d-4272-8980-a68b46d6d12e.png)

import sktime

df['date'] = pd.to_datetime(df.date)
df['date'] = df['date'].dt.date

df.sort_values(by=['date', 'country'], inplace=True)
df.index=pd.MultiIndex.from_arrays(df[['date','country']].values.T, names=['date','country'])

df.index.freq = 'M'

df=df.drop('country', axis='columns')
df=df.drop('date', axis='columns')

from sktime.utils.data_processing import from_multi_index_to_nested

df = from_multi_index_to_nested(df, instance_index='date')

from sktime.forecasting.model_selection import temporal_train_test_split

y = df.fatalities
X = df

y_train, y_test, X_train, X_test = temporal_train_test_split(X,y, test_size=96)

import numpy as np

from sktime.forecasting.base import ForecastingHorizon

fh = np.arange(1, 12)

from sktime.forecasting.compose import ForecastingPipeline
from sktime.transformations.series.adapt import TabularToSeriesAdaptor
from sklearn.preprocessing import StandardScaler
from sktime.forecasting.compose import make_reduction
from xgboost.sklearn import XGBRegressor

regressor = XGBRegressor
forecaster = make_reduction(regressor, window_length=24, strategy="recursive", scitype="tabular-regressor")

pipe = ForecastingPipeline(steps=[
    ("standardscaler", TabularToSeriesAdaptor(StandardScaler())),
    ("forecaster", forecaster)])

pipe.fit(y=y_train, fh=fh, X=X_train)
y_pred = pipe.predict(fh=fh, X=X_test, y=y_test)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-100-4dbd8bf41874> in <module>()
----> 1 pipe.fit(y=y_train, fh=fh, X=X_train)
      2 y_pred = pipe.predict(fh=fh, X=X_test, y=y_test)

4 frames
/usr/local/lib/python3.7/dist-packages/sktime/forecasting/base/_base.py in fit(self, y, X, fh)
    109 
    110         self._set_fh(fh)
--> 111         y, X = check_y_X(y, X)
    112 
    113         self._X = X

/usr/local/lib/python3.7/dist-packages/sktime/utils/validation/forecasting.py in check_y_X(y, X, allow_empty, allow_constant, enforce_index_type)
     55         allow_empty=allow_empty,
     56         allow_constant=allow_constant,
---> 57         enforce_index_type=enforce_index_type,
     58     )
     59 

/usr/local/lib/python3.7/dist-packages/sktime/utils/validation/forecasting.py in check_y(y, allow_empty, allow_constant, enforce_index_type)
    134         allow_empty=allow_empty,
    135         allow_numpy=False,
--> 136         enforce_index_type=enforce_index_type,
    137     )
    138 

/usr/local/lib/python3.7/dist-packages/sktime/utils/validation/series.py in check_series(Z, enforce_univariate, enforce_multivariate, allow_empty, allow_numpy, enforce_index_type)
     88 
     89     if enforce_univariate:
---> 90         _check_is_univariate(Z)
     91 
     92     if enforce_multivariate:

/usr/local/lib/python3.7/dist-packages/sktime/utils/validation/series.py in _check_is_univariate(y)
     22     """Check if series is univariate."""
     23     if isinstance(y, pd.DataFrame):
---> 24         raise ValueError("Data must be univariate, but found a pd.DataFrame")
     25     if isinstance(y, np.ndarray) and y.ndim > 1:
     26         raise ValueError(

ValueError: Data must be univariate, but found a pd.DataFrame

**Comment by fkiraly** [comment]
this is actually coming from `fit`

**Comment by aiwalter** [comment]
> y_train, y_test, X_train, X_test = temporal_train_test_split(X,y, test_size=96)

you have to switch it to `temporal_train_test_split(y, X, test_size=96)` I guess

**Comment by fkiraly** [comment]
I think there are multiple problems:

* your data is panel data - currently `sktime` doesn't forecast panels (although we're working on supporting it)
check the [forecasting notebook](https://mybinder.org/v2/gh/alan-turing-institute/sktime/main?filepath=examples) for examples, `X` and `y` should be non-nested pandas series or data frames 
* now if you would have a multivariate series, it probably wouldn't work either, since it seems the forecaster you are constructing is univariate. Currently the reducer does not support multivariate forecasts.
* You can make the reducer support multivariate by wrapping the `pipe` or the `forecaster` in a `ColumnEnsembleForecaster`.

**Comment by fkiraly** [comment]
>you have to switch it to temporal_train_test_split(y, X, test_size=96) I guess

and that.

**Comment by roboswell** [comment]
> > y_train, y_test, X_train, X_test = temporal_train_test_split(X,y, test_size=96)
> 
> you have to switch it to `temporal_train_test_split(y, X, test_size=96)` I guess



> I think there are multiple problems:
> 
> * your data is panel data - currently `sktime` doesn't forecast panels (although we're working on supporting it)
>   check the [forecasting notebook](https://mybinder.org/v2/gh/alan-turing-institute/sktime/main?filepath=examples) for examples, `X` and `y` should be non-nested pandas series or data frames
> * now if you would have a multivariate series, it probably wouldn't work either, since it seems the forecaster you are constructing is univariate. Currently the reducer does not support multivariate forecasts.
> * You can make the reducer support multivariate by wrapping the `pipe` or the `forecaster` in a `ColumnEnsembleForecaster`.

**Comment by roboswell** [comment]
Could you provide an example code of how `pipe` or `forecaster` could be wrapped in  `ColumnEnsembleForecaster` to make it work with multivariate data?
