### ISSUE TITLE
How to Import  `ColumnEnsembleForecaster` ?

### ISSUE THREAD

**Issue by roboswell** [alan-turing-institute/sktime#1351]
What is the correct code for importing `ColumnEnsembleForecaster`? Thank you

Could you provide an example code of how `pipe` or `forecaster` could be wrapped in  `ColumnEnsembleForecaster` to make it work with multivariate data?

_Originally posted by @roboswell in https://github.com/alan-turing-institute/sktime/issues/1350#issuecomment-904181293_

**Comment by roboswell** [comment]
from sktime.forecasting.compose import ColumnEnsembleForecaster
forecasters = [("XGB", forecaster0, 0), ("RF", forecaster1, 1)]
forecaster = ColumnEnsembleForecaster(forecasters=forecasters)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-130-4b67ea91a499> in <module>()
----> 1 from sktime.forecasting.compose import ColumnEnsembleForecaster
      2 forecasters = [("XGB", forecaster0, 0), ("RF", forecaster1, 1)]
      3 forecaster = ColumnEnsembleForecaster(forecasters=forecasters)

ImportError: cannot import name 'ColumnEnsembleForecaster' from 'sktime.forecasting.compose' (/usr/local/lib/python3.7/dist-packages/sktime/forecasting/compose/__init__.py)

**Comment by ltsaprounis** [comment]
ColumnEnsembleForecaster is a new feature and not part of the latest release. See the latest release docs here: https://www.sktime.org/en/stable/api_reference.html#id5

If you want to try it out before the next release you can do so by installing the development version of sktime. Instructions on how to do that are here: 
https://www.sktime.org/en/latest/installation.html#development-versions

**Comment by fkiraly** [comment]
I think this resolves the question, @roboswell?
There will be a new releast in the next weeks probably, so it's not a long wait - or, install the development version.

Please reopen the issue if you think it's not resolved.

**Comment by roboswell** [comment]
Thank you for your help, and that's great news that there will be a new
release shortly. I installed the development version, but I keep getting
the same error as before even with the development version. I'm unsure why.

**Comment by fkiraly** [comment]
>I installed the development version, but I keep getting the same error as before even with the development version.

Really? How strange. Perhaps you have an older version cloned? When did you clone the repository?

Can you load anything else from `sktime` using the development version?

**Comment by roboswell** [comment]
I think that the issue might be that, although I have followed all of the
steps for installing the development version on Anaconda, Jupyter Notebook
doesn't recognize that it is supposed to be running in the development mode
for some reason, but it might instead be accessing the regular version.
Everything else runs normal, except for import ColumnEnsembleForecaster

**Comment by fkiraly** [comment]
probably you're using the wrong environment then? You need to use an environment where you have installed the dev version (`pip install -e .` and *not* the pip/conda version (`pip install sktime`)

**Comment by roboswell** [comment]
I'm pretty new at this, so I'm a bit confused. I apologize. Do I need to
install the development version using the actual Python environment (e.g.,
Python 3.7 (64-bit) window and not any other type of command prompt/power
shell, and also not using an Anaconda based environment like Jupyter
Notebooks or Spyder?  If so, then I'm confused about how to get the Python
prompt to accept code like  cd sktime and then pip install -e that would be
necessary for me to navigate to the cloned sktime directory.

**Comment by fkiraly** [comment]
If you use anaconda, you need to create a new environment, and in it you install `sktime` and its dependencies using `pip install`, on the anaconda prompt. I can look at your screen on discord if you're there in the next hour or so; or, you could come to the community collaboration session on Fridays (12noon UTC).

**Comment by roboswell** [comment]
Perhaps discord would be the easiest option. I just created a discord
account. My username is: robboswell. I'll make sure to be logged at that
time. Thank you, Rob

**Comment by roboswell** [comment]
It looks like you may also need the 4-digit number to connect with me on
discord. It's #6799

**Comment by fkiraly** [comment]
does it ask for that? I thought you could just click the button on our landing page
![image](https://user-images.githubusercontent.com/7985502/131232923-cc8307c8-e6ac-4f00-bfd0-37ff55200719.png)

**Comment by roboswell** [comment]
I downloaded the app, which I guess normally requires the number. But now I
clicked on the button you  showed me, and it doesn't require it. So, now
I'm in the sktime discord chat area

**Comment by fkiraly** [comment]
ah, sorry - already went to bed when you were there. But indeed that´s the right place. Feel free to join the Fri collab session or ping me a message to find another time.
