### ISSUE TITLE
Potential license issue with code in elastic distances and contributed time series distances

### ISSUE THREAD

**Issue by hyandell** [alan-turing-institute/sktime#1366]
**Describe the bug**
Not a bug per se, but an oddity on the software licensing.

As a whole sktime is BSD-3-Clause licensed, but there are three files that contain AGPL-3.0:

*  sktime/distances/elastic.py
*  sktime/contrib/distance_based/ts_distance_measures.py 
*  sktime/distances/elastic_cython.pyx 

Does this cause problems for your overall licensing model?

**Comment by fkiraly** [comment]
>Does this cause problems for your overall licensing model?

Oops, yes it does!
This is a "license clash", which looks like it's accidental.

@hyandell, now I can't find the license in those files - what makes you think it's AGPL-3.0?
I have looked into it and can't find a license statement.

Is it copied from somewhere else?
@TonyBagnall? @jasonlines?

If it's indeed copied from somewhere (and there is a potential license violation), this would need to be rectified immediately.
@hyandell, can you confirm why you think it is AGPL? If you think it's copied from somewhere, can you please point out the source?

**Comment by hyandell** [comment]
Sure. Sorry for not giving you direct links. Here's one:

https://github.com/alan-turing-institute/sktime/blob/main/sktime/distances/elastic.py#L280

**Comment by fkiraly** [comment]
Got it - so it's not license infringement, just license clash.
We'll have to check how we deal with this.

Perhaps fortunately, we'll be refactoring the distances anyway, so one could think of re-implementing. It looks anyway it could easily be vectorized, there's just too many loops in there.

Would that be sth you'd be interested in, e.g., a vectorized re-implementation?
Let's just check that this is not already underway with @chrisholder, @MatthewMiddlehurst, @TonyBagnall.

**Comment by MatthewMiddlehurst** [comment]
Not something I am currently doing or planning to do. I think @chrisholder may be doing some distance based stuff related to clustering?

**Comment by hyandell** [comment]
Thanks for the update Franz; hoping this can be resolved soon. Currently I worry it means treating the PyPI package as AGPL-3.0 (as AGPL-3.0 is pretty much a superset of sktime's BSD-3-Clause licensing). Which is a very different license.

**Comment by fkiraly** [comment]
as per the above, there was not an issue to start with due to permissive licensing (agpl-3.0).

Further, the code in question has left `sktime` in release 0.10.0, so this is resolved.
