### ISSUE TITLE
[BUG] Signature transformers are not compliant with transform template

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1369]
I'm just refactoring the transformers module, and I'm surprised to fine the signature transformers incompliant with the basic interface template.

How did we end up with `transform(data, labels)` instead of the usual `transform(X, y)`??
How did the tests not pick this up?

I think this needs to be fixed both in the transformer and in the tests, which also need to check that the arguments are correctly named.

@jambo6, perhaps you could shed light on this?

I see I approved it as interface compliant, and so did @mloning, but perhaps we just looked at the classifier and not the transformer?

**Comment by jambo6** [comment]
Sorry, I'm used to writing (data, labels) rather than (X, y) and evidently, I missed this. 

Are my tests supposed to have picked this up, or existing sktime tests?

**Comment by fkiraly** [comment]
>Are my tests supposed to have picked this up, or existing sktime tests?

The generic tests should probably have picked this up, so I'm worried that they didn't.
The transformer is correctly added in `_config`, so there must be a problem with the tests.

I've now pushed some tentative updates to the signature method as part of #1365 (using the conversion machinery since you need numpy 3D inside), would you mind having a look at the signature module therein?

**Comment by jambo6** [comment]
It shouldn't have been necessary to change any of the transformers other than `SignatureTransformer` and `SignatureClassifier`. None of the other transform methods are ever used by anything other than within those classes so it shouldn't have mattered that they did not have the `y=None` argument for example. 

The only issue seems to be incorrect naming of `data, labels` rather than `X, y` which are just positional arguments so I don't see why they would have been picked up in tests as essentially stylistic.

**Comment by fkiraly** [comment]
>It shouldn't have been necessary to change any of the transformers other than SignatureTransformer and SignatureClassifier. None of the other transform methods are ever used by anything other than within those classes so it shouldn't have mattered that they did not have the y=None argument for example.

No, it does matter, because the `sklearn` `pipeline` calls `fit_transform`, which in turn calls `transform(X, y)`, which for some reason passes a `y`, which breaks the transform elements.

I didn't follow exactly through the logic, but if you could track it down and provide an alternative fix, I wouldn't mind if you would revert changes, as long as it doesn't break things.

**Comment by jambo6** [comment]
Ok, I see. That's very weird though. sklearns pipeline does not require a `y` argument to be in the transform method unless this is a new thing?

**Comment by fkiraly** [comment]
Something ends up calling the `sktime` transformer which has a `y`, one would have to look at the trace back of what happens if you remove the change in the signatures files.

**Comment by fkiraly** [comment]
This was solved in the transformers refactor, PR #1365.
