### ISSUE TITLE
[ENH] Add `UnobservedComponents` model wrapper (statsmodels)

### ISSUE THREAD

**Issue by juanitorduz** [alan-turing-institute/sktime#1371]
## Description

**Is your feature request related to a problem? Please describe.**

The unobserved components forecasting models has proven to very effective for some time series prediction problems (in my experience)

**Describe the solution you'd like**

I would suggest to use the `sktime.forecasting.base.adapters._StatsModelsAdapter` class to wrap the [statsmodels implementation](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.structural.UnobservedComponents.html)

**Additional context**
`sktime` already supports ETS and ARIMA, so the unobserved components model is a natural addition (given that the implementation exists already in statsmodels)

---

## References:

- [Statsmodels documentation](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.structural.UnobservedComponents.html)
- [Time Series Analysis by State Space Methods](https://oxford.universitypressscholarship.com/view/10.1093/acprof:oso/9780199641178.001.0001/acprof-9780199641178), Durbin, James, and Siem Jan Koopman.
- [Time Series Analysis and Its Applications - Chapter 6: Space Space Models](https://www.stat.pitt.edu/stoffer/tsa4/Chapter6.pdf)
- [Forecasting with the Kalman Filter (PyData Chicago 2016)](https://www.youtube.com/watch?v=GmSXhmbv5Zg), by Mike Mull
- [Modern Time Series Analysis (SciPy 2019 Tutorial)](https://www.youtube.com/watch?v=v5ijNXvlC5A&t=10813s), by Aileen Nielsen

**Comment by juanitorduz** [comment]
I could potentially work on this enhancement by following the logic of [https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/ets.py](https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/ets.py) (plus some additional support). Any tips / suggestion on how to get started?

**Comment by aiwalter** [comment]
Would be nice if you can work on it

**Comment by mloning** [comment]
Hey @juanitorduz - sounds good, happy to help if you get stuck. Also take a look at the extension template here: https://github.com/alan-turing-institute/sktime/blob/main/extension_templates/forecasting.py

**Comment by juanitorduz** [comment]
I will start to work on it sometime this week. I'll create a draft PR whenever I feel I need some help 😅.
