### ISSUE TITLE
[ENH] classifier family as estimator tag

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1390]
I think the classifier family (distance based etc) whould also be a classifier tag.

That way, we can look up classifiers using the tag with `all_estimators`.

Opinions or preferences here, @tonybagnall?

**Comment by TonyBagnall** [comment]
Yes @fkiraly i think that's a good idea, I'll do it in my base class refactor

**Comment by MatthewMiddlehurst** [comment]
We now have a classifier_type tag, and relevant classifiers have been updated to use it.
