### ISSUE TITLE
[ENH] All univariate _SeriesToSeriesTransformer should internally use the ColumnwiseTransformer to make them multivariate

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#1393]
**Is your feature request related to a problem? Please describe.**
All univariate `_SeriesToSeriesTransformer `should internally use the `ColumnwiseTransformer `to make them multivariate. This should however be mentioned in the docstring that it internally applies just a `ColumnwiseTransformer ` and that the algorithm itself is still a univariate.

**Additional context**
Refactor `Detrender` which internally uses sth similar to `ColumnwiseTransformer` which should be raplaced with a `ColumnwiseTransformer ` then also.

tagging @SveaMeyer13 who wrote the `ColumnwiseTransformer`

**Comment by SveaMeyer13** [comment]
Happy to work on this :)

**Comment by SveaMeyer13** [comment]
Would it make sense to wait for the overall transformer-refactor though?

**Comment by fkiraly** [comment]
Yes, that's an excellent idea - the current transformers refactor #1365 contains a similar feature, where a Series transformer is applied to all elements in a Panel automatically.

**Comment by fkiraly** [comment]
I would suggest we include it as a part in the transformers refactor, since this is really base class functionality!

**Comment by fkiraly** [comment]
A similar question: should univariate forecasters not automatically be applied this way too?

**Comment by aiwalter** [comment]
> A similar question: should univariate forecasters not automatically be applied this way too?

yes I was thinking the same. but I think normally you would not apply the same hyperparameters to each column, right? So you would probably rather use a `ForecastingGirdSeachCV` in combination with a `ColumnsEnsembleForecaster` I guess. But we could have it anyway as a default. Its just the risk that users dont know about that they actually apply a univariate model, but thas also for transformers. So we should definitely mention it in docstring then. Also I wanted to add multivariate `NaiveForecaster`, but maybe I can directly add it to base class so it would work for all univariate?

**Comment by fkiraly** [comment]
Yes, that's an interesting point - there is potential syntatic ambiguity here, since it's unclear whether applying `ForecastingGridSearchCV` to a univariate forecaster would tune all columns simultaneously or not. I guess one could use the scitype label to control this, though it might not be obvious to the user.

**Comment by mloning** [comment]
Yes I like the idea for transformers. For forecasters, classifiers and so on, I'm less sure, it may end up being more confusing than helpful, especially for models like AR and VAR and so on.

**Comment by RNKuhns** [comment]
What are the performance implications of this? For some transformers, the combined interface of Series and DataFrames in pandas may provide an alternative. If we use `ColumnEnsembleForecaster`  to iteratively apply the transformer to each column, do we know  what the performance of that is like relative to using the combined pandas interface?

**Comment by mloning** [comment]
I think we should use the column-ensembling as the default fall-back option for transformers implemented in the base class (still not sure about forecasters). Concrete transformers should have the option to override that if they implement bespoke ways of handling both univariate and multivariate data by using the combined pd.Series/pd.DataFrame interface. I think that what the tags would allow us to do quite easily.

**Comment by fkiraly** [comment]
This is now done via https://github.com/alan-turing-institute/sktime/pull/2937
