### ISSUE TITLE
[BUG] "no hosted parallelism granted" in azure DevOps

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1415]
Just an issue to track the resolution of "no hosted parallelism granted" error message when trying to run ADO pipelines since today.

@mloning believes that this may be due to `sktime` reaching high usage of free ADO pipelines time, and Microsoft switching them off.
@mloning has written to Microsoft for authorization, which is expected to take 2-3 days or more

**Comment by mloning** [comment]
It's not so much about our usage I think, but rather about them trying to prevent abuse of their pipelines for other things (see e.g. https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/).

**Comment by mloning** [comment]
Azure DevOps pipelines are working again, received the confirmation earlier today.
