### ISSUE TITLE
[BUG] make_forecasting_error is not working

### ISSUE THREAD

**Issue by eyalshafran** [alan-turing-institute/sktime#1422]
**Describe the bug**
When calling make_forecasting_error I get - AttributeError: '_BaseForecastingScoreMetric' object has no attribute 'func'

**To Reproduce**
```python
from sktime.performance_metrics.forecasting import mean_absolute_error, make_forecasting_scorer
make_forecasting_scorer(func=mean_absolute_error, name='mae')
```

**Versions**
System:
    python: 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]
executable: /opt/anaconda3/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
          pip: 20.2.4
   setuptools: 50.3.1.post20201107
      sklearn: 0.24.2
       sktime: 0.7.0
  statsmodels: 0.12.2
        numpy: 1.19.2
        scipy: 1.4.1
       Cython: 0.29.21
       pandas: 1.3.1
   matplotlib: 3.3.2
       joblib: 0.17.0
        numba: 0.51.2
     pmdarima: 1.8.2
      tsfresh: None

**Comment by fkiraly** [comment]
@RNKuhns, can you kindly have a look at this, since you wrote the function/classes involved?

**Comment by fkiraly** [comment]
@RNKuhns?

**Comment by fkiraly** [comment]
and, we should probably add a test. Might be a good thing to add to `estimator_checks`.

**Comment by RNKuhns** [comment]
We originally had the `func` param stored in the `func` attribute, but then changed it later on. I can't remember why at this point. But I'm pushing a PR to fix this today.
