### ISSUE TITLE
[DOC] add estimator list/overview and tags explanation at start of forecasting notebook, section 2

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1425]
Section 2 of the forecasting notebook explains the main classes of forecasters.

Since we wrote this, we have introduced and extended the `all_estimators` registry lookup which can be used to list all forecasters, and the `all_tags` lookup which can list all forecaster tags (both in the `registry` module).

I think it would be a good idea to add usage of these two utility functions at the start of section 2, explain the most important forecaster tags, and showcase the lookup - so users won't look at the notebook but at the registry functions to search for forecasters.

**Comment by mloning** [comment]
This is now done.
