### ISSUE TITLE
[BUG] link in `contributing.md` is dead

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1427]
The link in our `contributing.md` (in root folder) 404s, this needs to be fixed.

**Comment by fkiraly** [comment]
Also, the main page "contribute" link links there, so also to a 404.

We need to fix this asap! Where should it link to?

@mloning, @TonyBagnall ??

FYI, @GuzalBulatova, @Aparna-Sakshi, @xiaobenbenecho

**Comment by Aparna-Sakshi** [comment]
I haven't updated the link in README.md as it points to CONTRIBUTING.md and not the wrong link.
I have only updated in CONTRIBUTING.md

**Comment by fkiraly** [comment]
>I haven't updated the link in README.md as it points to CONTRIBUTING.md and not the wrong link.
> I have only updated in CONTRIBUTING.md

Yes, thanks a lot!
Though I think it's a better user experience if the `README.md` points directly to the correct place instead of pointing to another place that points to the correct place - would appreciate a fix for that too (or I can do it later today).

**Comment by Aparna-Sakshi** [comment]
Ok, sure I'll do that right now.
