### ISSUE TITLE
[DOC] Remove license info from module docstrings

### ISSUE THREAD

**Issue by RNKuhns** [alan-turing-institute/sktime#1433]
#### Describe the issue linked to the documentation

There has been cases popping up where module docstrings are including our licensing information. 

Licensing should not be in docstrings (See [numpydoc module docstrings](https://numpydoc.readthedocs.io/en/latest/format.html#documenting-modules). It should be in a comment line. 

#### Suggest a potential alternative/fix

Solution is manually going through and finding the cases where we have included licensing information in the module docstrings and moving it to a comment line above the docstring.

The result should look something like this:

``` python
#!/usr/bin/env python3 -u
# -*- coding: utf-8 -*-
# copyright: sktime developers, BSD-3-Clause License (see LICENSE file)
"""Some docstring (single or multiple line) here."""
```

**Comment by ronnie-llamado** [comment]
I'd like to take on this issue.
