### ISSUE TITLE
[DOC] Broken links on 'Estimator Overview' page

### ISSUE THREAD

**Issue by FutureTribute** [alan-turing-institute/sktime#1438]
#### Describe the issue linked to the documentation

There was a new doc page added in recent update called 'Estimator Overview'.
`https://www.sktime.org/en/latest/estimator_overview.html`
![image](https://user-images.githubusercontent.com/25502260/133971754-d492f54a-9a80-4ee9-a59a-598b985860fe.png)

While it is very useful, there's an issue with it: all links to pages of estimators are broken.
Problem is that all links contain additional `/modules` path in it, where an actual link to a page doesn't have such part.
See below:
`n = "https://www.sktime.org/en/latest/api_reference/modules/auto_generated/sktime.forecasting.arima.ARIMA.html"`
`m = "https://www.sktime.org/en/latest/api_reference/auto_generated/sktime.forecasting.arima.ARIMA.html"`
where `n` - link from 'estimator overview' page, `m` - actual link.

#### Suggest a potential alternative/fix

Potential fix would be to remove `/modules` from the path.
But I see that this page is auto-updating so I don't know if there's an actual way to fix this or how it's done at all.

UPD: I tried to look through codebase and doc auto-generator files but found nothing. I guess without any experience w/ Sphinx it's impossible to find the root of the issue.

**Comment by fkiraly** [comment]
ouch, this must have broken with the doc migration?

Also, didn't we use to have a version where you could search for tags? See #997?

FYI @afzal442 (for the automation part) and @mloning (for the documentation migration).

**Comment by afzal442** [comment]
Ah, I see! thanks @FutureTribute @fkiraly ! I think this is discovered due to the latest changes pulled down.

> Potential fix would be to remove /modules from the path.

Yes, you are r8, @FutureTribute would like to raise a PR for this? let me know if you are interested;

>  I tried to look through codebase and doc auto-generator files but ....

Here you can find the following link to the codebase to get through;
https://github.com/alan-turing-institute/sktime/blob/5a2c1e133b677166a4b3063fd08669c2fc65238f/docs/source/conf.py#L355

**Comment by FutureTribute** [comment]
> Yes, you are r8, @FutureTribute would like to raise a PR for this? let me know if you are interested and have followed the [contribution guide](https://www.sktime.org/en/latest/get_involved/contributing.html) earlier;

Yes, I would like to. After all, it sounds like a good "good first issue".

**Comment by FutureTribute** [comment]
But as much as I would like to submit PR, I'm not sure about it. After looking at `_make_estimator_overview` it seems like all there's need to be done is to change the line you mentioned to `'<a href="https://www.sktime.org/en/latest/api_reference'` but after trying to build docs on my device I have encountered a lot of errors and my 'Estimator Overview" page is broken. My guess would be is that it must be something due to my environment as it is conda + pip. But because of that I don't feel confident about submitting PR.

**Comment by fkiraly** [comment]
hm, if it's really just a single line, you could give it a try, @futuretribute?

Can you build the docs without the change to it?

We can also look at your developer set-up separately to this if you are considering future contributions, e.g., in one of the community collaboration sessions.

**Comment by FutureTribute** [comment]
Thanks for the reply. Unfortunately, it wasn't about lacking dependencies. And as much as I would like to be a contributor, I don't have much time in my hands these days so I give up on the PR. But still want to see bug fixed because 'Estimator Overview' page is very convenient.

**Comment by fkiraly** [comment]
alright - @afzal442, it sounded like the error has been identified though, so perhaps it's an easy fix from your background?
(personally, I don't quite know what I would do)

**Comment by afzal442** [comment]
Thanks @FutureTribute for your investigation; feel free to connect with us; stay tuned! 🚀 

yes @fkiraly, it is. but I also discovered the some issue while building docs with `make docs` command; so generally it can be fixed in that way I described above but one needs to be sure if it works locally. thanks.

cc: @mloning

**Comment by mloning** [comment]
@afzal442 if you push your changes we can see if the ReadTheDocs build succeeds. Please ping me in the PR to review.
