### ISSUE TITLE
[ENH] Multivariate forecasting/timeseries regression

### ISSUE THREAD

**Issue by iamzeynepcetin** [alan-turing-institute/sktime#1439]
I need to work with multivariate version for regression models. Is that possible, because I couldnt find any example, if you know could you share the links? Thanks

**Comment by mloning** [comment]
Hi @iamzeynepcetin, could you add a bit more detail to your question. Are you trying to forecast multiple series at the same time?

**Comment by fkiraly** [comment]
sktime has multivariate models and tags for it, I consider this resolved hence.
Of course, not all forecasters or classifiers will be multivariate.
