### ISSUE TITLE
Can't use multivariate time series REGRESSİON with sktime 

### ISSUE THREAD

**Issue by ozkanuysal** [alan-turing-institute/sktime#1440]
Hi everyone ı have a question for sktime multivariate problem.We try to solve multivariate regression predict but we can't use sktime.In the other hand we can predict, Univariate time series classification with sktime, we know we can use multivariate with classification but we try to use in Regression problem how we can do it is there anyone know ?

**Comment by fkiraly** [comment]
v.0.8.0 added multivariate support for foreasting.
The time series regression module (which you are looking for?) is still experimental and doesn't support multivariate afaik.

Is this correct, @tonybagnall?

**Comment by fkiraly** [comment]
Due to the "heart" emoji, I think this question is now answered?
For multivariate *forecasting*, use the `registry.all_estimators` lookup to list estimators with the `scitype:y` tag being `"both"` or `"multivariate"`.
