### ISSUE TITLE
[DOC] Add multivariate forecasting examples to forecasting tutorial

### ISSUE THREAD

**Issue by eldritchhh** [alan-turing-institute/sktime#1446]
Update by @fkiraly: examples for multivariate forecasting should be added to the forecasting notebook.

---
There are any multivariate forecasting example?

**Comment by fkiraly** [comment]
No, currently not - good point! This should be added.

I think it's a good first issue?

**Comment by fkiraly** [comment]
@kejsitake has expressed interest - assigned to track interest, revisit later.

**Comment by fkiraly** [comment]
now included by https://github.com/alan-turing-institute/sktime/pull/2041
