### ISSUE TITLE
[DOC] clean developer set-up instructions and installation instructions - the two current sets of installations instructions are confusing

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1448]
I've now seen multiple instances how the two sets of installation instructions create confusion:

* the short instructions in https://www.sktime.org/en/latest/get_involved/contributing.html
* the detail instructions in https://www.sktime.org/en/latest/installation.html

I think this needs to be resolved, e.g., that following the short instructions likely results in problems since build requirements need to be satisfied, the instructions being incomplete.

Concretely, here's what I propose to do:

* remove any `pip install` commands from the short instructions on the "contributing" page
* create a separate "developer set-up" page, which refers to the "install sktime from source" page. The "developer set-up" page is referred to from the "contributions" page. At the end there should be only two installation instructions - one for developers, one for the development version of sktime. It should be clear which is which, both should be comprehensive when followed from start to end, and none should have parts on the "contributing" page.
* stuff like precommits and testing setup should move to the "developer set-up" page

**Comment by mloning** [comment]
Yes, I agree, the contributing page should give an overview and point to other more specific resources. The developer setup page should go under the Development rubric on the website.

**Comment by fkiraly-shell** [comment]
Further content that should move from the "how to contribute" page to the developer guide rubric:
* Git(Hub) flow for sktime
* any content about the developer installation

Generally, "how to contribute" should point to the developer guide, which should point to individual rubrics such as "developer set-up" and "GitHub flow model for contributions". The developer guide should have a "prerequisites" section which contains as one step "install a complete local developer set-up" (and then point to the sub-section of the installation isntruction).

**Comment by fkiraly-shell** [comment]
related issue: #1203

**Comment by fkiraly** [comment]
This is resolved by #1707.
