### ISSUE TITLE
[BUG] Automatic downloader for sktime.datasets.load_UCR_UEA_dataset does not work for custom extract_path

### ISSUE THREAD

**Issue by mingu6** [alan-turing-institute/sktime#1466]
Even given a custom extract_path, UCR_UEA datasets are downloaded to the default sktime package directory. The bug is easily fixed by adding the custom extract_path to the _download_and_extract function call.

Line 175 in sktime/sktime/datasets/_data_io.py in function load_UCR_UEA_dataset:

```python
try:
     _download_and_extract(
                url,
      )
```

should be instead

```python
try:
     _download_and_extract(
                url,
                extract_path=extract_path
      )
```

Expected behaviour:

Dataset gets downloaded to the correct path after bug fix.

**Comment by yairbeer** [comment]
Hi, can I do it as a first contribution?

**Comment by fkiraly** [comment]
yes, looks like a straightforward fix!
Appreciate a PR, @yairbeer!

@TonyBagnall, FYI
