### ISSUE TITLE
[ENH] implement get_fitted_params for tuning forecasters

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1496]
Tuning forecasters like `ForecastingGridSearchCV` should implement a `get_fitted_params` method.
Note that here, by applying a tuning method, the hyperparameters that are tuned become "normal" (fitted) parameters.

The `get_fitted_params` of tuning should return two things in its dictionary:

* the hyper-parameters that are tuned, with their tuned values
* either: the "best estimator" in its fitted state; or, better, parameters of the "best estimator" with a nesting structure like for `sklearn` `get_params`  (this might be slightly fiddly.

For implementation, it's fine to start with one of the two.

See also discussion in #1486, FYI @boukepostma and @asksteph.

FYI @aiwalter.

**Comment by ZiyaoWei** [comment]
Sounds like a pretty interesting small project, can I claim the ticket?

**Comment by fkiraly** [comment]
all yours, @ZiyaoWei !

**Comment by fkiraly** [comment]
small note of caution: `get_fitted_params` is not subject to the "plumbing" layer, i.e., you still have to write boilerplate.

The boilerplate is simple:

```python
if not self.is_fitted:
    raise NotFittedError
```

**Comment by ZiyaoWei** [comment]
So I finally got a bit of time to look into this and it seems `get_fitted_params()` has a implementation in `BaseGridSearch` which just returns the underlying best params - if we change the implementation should we worry about compatibility with existing usages?

**Comment by fkiraly** [comment]
>  if we change the implementation should we worry about compatibility with existing usages?

not if it returns everything in the expected `dict` format.

>Also the only tuning forecasters I see are the ones in _tune.py (`ForecastingGridSearchCV` and `ForecastingRandomizedSearchCV`) - do we have more?

These are the only ones I know.
