### ISSUE TITLE
ShapeletTransformClassifier: TypeError: object of type 'numpy.float64' has no len()

### ISSUE THREAD

**Issue by xaviervasques** [alan-turing-institute/sktime#150]
Hi, 
I am trying to classify data coming from EEG. The data looks like this : 

`# Letter   Cz/theta   Cz/alpha   Cz/betaL   Cz/betaH   Cz/gamma   Fz/theta   Fz/alpha  ...   F8/betaL   F8/betaH   F8/gamma   Fp2/theta   Fp2/alpha   Fp2/betaL   Fp2/betaH   Fp2/gamma
0         0.0      0.304      0.215      0.223      2.709      0.310      0.817      1.239  ...      2.737      6.337      4.653       1.755       1.203       0.615      10.735       3.322
1         0.0      0.365      0.207      0.182      2.641      0.332      0.558      1.118  ...      2.638      5.258      4.675       1.158       1.311       0.992       7.299       3.871
2         0.0      0.389      0.302      0.227      2.679      0.527      0.731      0.794  ...      2.752      4.930      4.665       1.185       1.086       2.369       4.568       4.456
3         0.0      0.460      0.464      0.396      2.694      0.893      1.653      0.532  ...      2.695      4.707      4.938       2.575       0.969       3.684       3.040       4.813
4         0.0      0.499      0.514      0.629      2.705      1.104      2.927      0.707  ...      2.255      4.432      5.269       4.750       1.216       4.327       2.690       4.821`

The "Letter" variable is my target variable (0 or 1)

When loading the data and using sktime to classify:
`y_train = frame['# Letter'].values`
`X_train = frame.loc[:, df.columns != '# Letter']`
`clf = ShapeletTransformClassifier(time_contract_in_mins=5)`
`clf.fit(X_train, y_train)`

I have the following error: 

> Traceback (most recent call last):
  File "lda_v2.py", line 76, in <module>
    lda()
  File "lda_v2.py", line 72, in lda
    clf.fit(X_train, y_train)
  File "/Users/xav/Desktop/EPOC_Flex/juju/lib/python3.7/site-packages/sktime/classifiers/shapelet_based/stc.py", line 76, in fit
    self.classifier.fit(X, y)
  File "/Users/xav/Desktop/EPOC_Flex/juju/lib/python3.7/site-packages/sklearn/pipeline.py", line 352, in fit
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/Users/xav/Desktop/EPOC_Flex/juju/lib/python3.7/site-packages/sklearn/pipeline.py", line 317, in _fit
    **fit_params_steps[name])
  File "/Users/xav/Desktop/EPOC_Flex/juju/lib/python3.7/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/Users/xav/Desktop/EPOC_Flex/juju/lib/python3.7/site-packages/sklearn/pipeline.py", line 716, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/Users/xav/Desktop/EPOC_Flex/juju/lib/python3.7/site-packages/sktime/transformers/shapelets.py", line 470, in fit_transform
    self.fit(X, y)
  File "/Users/xav/Desktop/EPOC_Flex/juju/lib/python3.7/site-packages/sktime/transformers/shapelets.py", line 105, in fit
    X_lens = np.array([len(X.iloc[r,0]) for r in range(len(X))]) # note, assumes all dimensions of a case are the same length. A shapelet would not be well defined if indices do not match!
  File "/Users/xav/Desktop/EPOC_Flex/juju/lib/python3.7/site-packages/sktime/transformers/shapelets.py", line 105, in <listcomp>
    X_lens = np.array([len(X.iloc[r,0]) for r in range(len(X))]) # note, assumes all dimensions of a case are the same length. A shapelet would not be well defined if indices do not match!
TypeError: object of type 'numpy.float64' has no len()

Do you have any idea on what is happening ?

> Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)]
NumPy 1.17.2
SciPy 1.3.1
sktime 0.3.0

**Comment by mloning** [comment]
Thanks for raising the issue! Any chance of providing reproducible code? It's likely to be the format of the input data `X_train` which has to be a nested pandas dataframe.   

You can try to run the example below to rule out any other issues and to inspect the format of X. 

```python
from sktime.classifiers.shapelet_based import ShapeletTransformClassifier
from sktime.datasets import load_gunpoint

X, y = load_gunpoint(return_X_y=True)  # load toy data
clf = ShapeletTransformClassifier(time_contract_in_mins=0.1)
clf.fit(X, y)
clf.score(X, y)
```

**Comment by xaviervasques** [comment]
Hello Markus, thank you very much for your reply and for solving the issue :) 
X_train = detabularise(X_train)  worked
Thank you!
