### ISSUE TITLE
[BUG] Call to ShapeletTransformClassifier that fails to generate shapelets produces unhelpful error message

### ISSUE THREAD

**Issue by BlaiseRitchie** [alan-turing-institute/sktime#151]
**Describe the bug**
If ShapletTransformClassifier is unable to generate any shapelets, a ValueError is produced in validation rather than a message saying no shapelets were generated.

**To Reproduce**
I'm unable to share any of the datasets that resulted in this error and unfortunately wasn't able to reproduce with a trivial example, but the error happened on the call to fit() in the following code:
```
    clf = ShapeletTransformClassifier(time_contract_in_mins=0.5)
    clf.fit(XDataTrain, YDataTrain)
```

**Expected behavior**
"Fit not called yet or no shapelets were generated" exception

**Additional context**
https://github.com/alan-turing-institute/sktime/blob/master/sktime/transformers/shapelets.py#L427
Line 427 should be "if shapelets is None or len(shapelets) == 0"

**Versions**
<details>
```
$ python3
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Windows-10-10.0.17763-SP0
>>> import sys; print("Python", sys.version)
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.17.1
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.1
>>> import sktime; print("sktime", sktime.__version__)
sktime 0.3.0
```
</details>

**Comment by jasonlines** [comment]
Hi @BlaiseRitchie,

Thanks for bringing this to our attention - I agree, it would be good to catch this case and have a more informative error message in the case where fit is called but no shapelets are found. 

I believe this probably happened in your case as we have a constant information gain rejection threshold for candidates. We reject candidate shapelets if they do not exceed the threshold, so if there are no shapelets in a dataset with an info gain higher than the threshold, the transform will finish fit with 0 accepted shapelets. Hopefully this should be rare (and I have never come across it!) but it could happen and thanks for catching the edge case. I'll work on a fix today and update when it has been pushed

**Comment by jasonlines** [comment]
Hi @BlaiseRitchie, I've implemented some enhanced warnings and exceptions in the cases where no shapelets are found. I pushed these additions to the dev branch (#152), and these should be live now. There changes will then move along to master in our next code release. Thanks again for pointing this out - I'll close this issue now to avoid confusion about the status of the fix, but please reopen it/start a new one if the issue persists or presents in another form.

Thanks,

Jason
