### ISSUE TITLE
[BUG] `ForecastingHorizon.to_absolute` conversion for `W-XXX` frequencies

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1523]
`ForecastingHorizon.to_absolute` can produce the wrong day of the week in `to_absolute` conversions.

This seems to occur only for the `W-XXX` frequency, leading to the error in #1405.

Minimally reproducing code:

```python
train = pd.Series(1, index=pd.date_range("2021-10-06", freq="W-WED", periods=3))
fh = ForecastingHorizon([1, 2, 3])
fh.to_absolute(train.index[-1])
```

results in `ForecastingHorizon(['2021-10-31', '2021-11-07', '2021-11-14'], dtype='datetime64[ns]', freq='W-SUN', is_relative=False)`.

Expected result is `ForecastingHorizon(['2021-10-27', '2021-11-03', '2021-11-10'], dtype='datetime64[ns]', freq='W-WED', is_relative=False)`.

Further unintuitive behaviour happens if the `fh` has length 2 or 1, in that case the resulting frequency is `None` but should be `'W-WED'` too... I think?

We should:

- [x] fix this
- [x] introduce tests for this specific frequency

**Comment by fkiraly** [comment]
FYI @asksteph, @aiwalter, @mloning, @xiaobenbenecho.

**Comment by eenticott-shell** [comment]
I will have a look at fixing this

**Comment by eenticott-shell** [comment]
I have found why the bug occurs. Within `to_absolute` the internal function `_get_freq` is used to obtain the frequency which is then given to the conversion. The `_get_freq` function is:

`def _get_freq(x):
    """Get unit for conversion of time deltas to integer."""
    if hasattr(x, "freqstr"):
        if x.freqstr is None:
            return None
        elif "-" in x.freqstr:
           return x.freqstr.split("-")[0]
        else:
            return x.freqstr
    else:
        return None`

So in the case of this bug we have `freqstr = "W-WED"` but the `_get_freq` function only returns "W" which then defaults back to "W-SUN" hence the error. This could be easily fixed by removing the case distinction for "-" in the `freqstr` however I imagine it is there for a reason, @fkiraly @mloning do you know why this case distinction is needed?

**Comment by fkiraly** [comment]
I don't quite know, on superficial glance it seems problematic to do this.
All the function does is "if it is an anchored frequency, cut off the bit after the dash, otherwise do nothing"?

I suspect it would cause a problem in general with the so-called "anchored frequencies" here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases

Does anyone know why we are doing this? @mloning or @aiwalter perhaps?

**Comment by fkiraly** [comment]
@eenticott-shell, quick question: is the issue also addressed in the case where `fh` has length 2 or 1?

**Comment by eenticott-shell** [comment]
No, that seemed to stem from a different problem so I think we should handle it in a separate bugfix, happy to investigate it.
