### ISSUE TITLE
[BUG] TypeError for ComposableTimeSeriesForestClassifier

### ISSUE THREAD

**Issue by jiayilee0** [alan-turing-institute/sktime#1536]
I was trying to follow the tutorial for "Univariate time series classification with sktime" but ran into an error with the time series forest classifier `ComposableTimeSeriesForestClassifier`. Copied the code exactly, everything was fine for a single time series tree. 

Code: 
```
tsf = ComposableTimeSeriesForestClassifier(
    estimator=time_series_tree,
    n_estimators=100,
    criterion="entropy",
    bootstrap=True,
    oob_score=True,
    random_state=1,
    n_jobs=-1,
)
```

Error: 
```
TypeError                                 Traceback (most recent call last)
<ipython-input-25-a9421957ffb2> in <module>()
      7     oob_score=True,
      8     random_state=1,
----> 9     n_jobs=-1,
     10 )

TypeError: Can't instantiate abstract class ComposableTimeSeriesForestClassifier with abstract methods _set_oob_score_and_attributes
```

(Google Colab, no GPU/TPU)

**Comment by Jackxiini** [comment]
The problem still exists

**Comment by OliverMatthews** [comment]
> The problem still exists

Hey @Jackxiini

Please could you give us a bit more information so we can look into it?

Specifically:
- What version of sktime are you using?
- Please can you give us some example code snippets that you're using so we can reproduce the issue.
- What python version are you using?

**Comment by fkiraly** [comment]
@tonybagnall, sounds like it didn´t get resolved? Reopening until we´ve either confirmed it´s resolved or validated the reappearance of the bug.

**Comment by TonyBagnall** [comment]
this example is no longer in the notebooks, but I just tested this and it works fine.

from classification.compose import ComposableTimeSeriesForestClassifier
from datasets import load_gunpoint
from sktime.transformations.panel.summarize import RandomIntervalFeatureExtractor
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

import numpy as np
steps = [
    (
        "extract",
        RandomIntervalFeatureExtractor(n_intervals="sqrt", features=[np.mean, np.std])
    ),
    ("clf", DecisionTreeClassifier())
]

time_series_tree = Pipeline(steps)

trainX, trainY = load_gunpoint(split="train")
testX, testY = load_gunpoint(split="test")

tsf = ComposableTimeSeriesForestClassifier(
    estimator=time_series_tree,
    n_estimators=100,
    bootstrap=True,
    oob_score=True,
    random_state=1,
    n_jobs=-1,
)
tsf.fit(trainX, trainY)
if tsf.oob_score:
    print(tsf.oob_score_)
print(tsf.score(testX,testY))

so I'm going to close this issue.
