### ISSUE TITLE
Tweaks to TimeSeriesForest

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#154]
I'm just proofing the two toolkits paper, can I suggest these changes to code related to TimeSeriesForestClassifier
1. FunctionTransformer(func=time_series_slope), validate=False)
set validate to false be default
2. For RISE, we do this
('acf',RowwiseTransformer(FunctionTransformer(func=acf_coefs,
                                               validate=False))),
  ('ps',RowwiseTransformer(FunctionTransformer(func=powerspectrum,
                                               validate=False)))

provide the functions acf_coefs and powerspectrum. 

note both of these throw exceptions with zero variance intervals, so RISE implemented with TimeSeriesForestClassifier will only complete on half the datasets. Not sure how to handle that

**Comment by mloning** [comment]
I think we explicitly set `validate=False` to silence the warning about future changes (maybe they updated that now). 

Regarding the zero-variance errors, we could catch that exception and simply return whatever is appropriate in that case. How do you solve this in your hard-coded version? Ideally, we would have proper transformers for your favourite transforms, Jeremy started on this, but they're buggy as far as I remember.

**Comment by mloning** [comment]
See #224
