### ISSUE TITLE
Proximity Forest Training Time

### ISSUE THREAD

**Issue by crixus5678** [alan-turing-institute/sktime#155]
Just wondering is it normal for proximity forest to have a long training time? I tried to applied proximity forest (n_trees=1) on a set of training data with 732 records each of length 355 and the run time timed using python time.time was 5682.006188869476.

**Comment by fkiraly** [comment]
@goastler , @jasonlines would probably know?
Also, is n_trees = 1 really a forest?

**Comment by crixus5678** [comment]
I set n_trees= 1 to test what's the training time of proximity forest when the tree is 1 (which in this case a proximity tree). I assume that the training time is going to increase with respect to n_trees so I want to have a rough estimate of the training time if I set n_trees=100.

**Comment by TonyBagnall** [comment]
Assuming thats in seconds, thats about an hour and a half? Not unexpected. Proximity forest's selling point is that it is faster and more accurate than the elastic ensemble. However, even when cython, it is pretty slow in python. I'm just updating the arxiv paper with comparisons, and am currently running both the java and python versions. I'll post a link here when it is revised.

**Comment by crixus5678** [comment]
@TonyBagnall thanks for the reply in regards to this.

**Comment by TonyBagnall** [comment]
no problem, this is all still in development, progress is slower than we would like but we will get there, turns out writing complex software implementing other peoples algorithms is hard  :)

**Comment by TonyBagnall** [comment]
fyi, this is the train time for tsml (java) vs sktime (python) 

![image](https://user-images.githubusercontent.com/9594042/66037723-2e40ab80-e508-11e9-9064-92240a66a798.png)

I'm sure there is more we can optimize to speed up the python, work in progress.

**Comment by fkiraly** [comment]
so, just to confirm, blue = sktime and orange = tsml?

**Comment by TonyBagnall** [comment]
err, no, sorry, blue = tsml. Orange (not red, I'm colour blind!) is sktime. Python much slower than java on anything distance based it seems

**Comment by fkiraly** [comment]
sorry, I don't hear what you are sayingn, lalalala.

Also, is the person who made the graph perhaps a tiny little bit biased?

**Comment by TonyBagnall** [comment]
I'm shocked and appalled at your insinuation, this is the noble pursuit of *science* :)
And tbh, making this graph is purely automated, I'm just running other people's code. Don't shoot the messenger, python is slow unless purely reliant on numpy it seems. Still, give the punters what they want :) This is the TSF graph
![image](https://user-images.githubusercontent.com/9594042/66044269-1291d100-e519-11e9-9dd9-c4388668ef63.png)

the pure numpy hard coded version is equivalent to java in time, the pipelined one less so ...

**Comment by fkiraly** [comment]
>I'm shocked and appalled at your insinuation, this is the noble pursuit of science :)

I thought this is how it worked in this post-truth age?
I'm supposed to ignore evidence and make arguments exclusively ad hominem.

**Comment by fkiraly** [comment]
Anyway, back to being serious, I think the 2nd graph makes a case for "post-processing" or "pipeline compilation", tbd.

**Comment by fkiraly** [comment]
and my curiosity is satisfied, so closing this issue.

**Comment by fkiraly** [comment]
oops, I thought @crixus5678 has already closed this and I re-opened.
Please confirm @crixus5678 if the answer is what you were looking for.

**Comment by isma3ilsamir** [comment]
It seems that this was discussed before, but PF seems always to use **only 2 CPUs** during the training and predicting processes. No matter what value is passed to the `n_jobs` parameter. it is always the same performance on my side.

Am I missing something here ??
