### ISSUE TITLE
[BUG] Numba needs NumPy 1.20 or less, but `sktime` installation does not ensure this on all operating systems

### ISSUE THREAD

**Issue by srinuti** [alan-turing-institute/sktime#1563]
**Describe the bug**

**To Reproduce**

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-63-9c74fc495c79> in <module>
----> 1 all_estimators("forecaster", as_dataframe=True)

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\site-packages\sktime\registry\_lookup.py in all_estimators(estimator_types, filter_tags, exclude_estimators, return_names, as_dataframe)
    140 
    141             try:
--> 142                 module = import_module(module_name)
    143                 classes = inspect.getmembers(module, inspect.isclass)
    144 

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\importlib\_bootstrap_external.py in exec_module(self, module)

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\site-packages\sktime\annotation\clasp.py in <module>
     25 import pandas as pd
     26 
---> 27 from sktime.transformations.series.clasp import ClaSPTransformer
     28 from sktime.utils.validation.series import check_series
     29 

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\site-packages\sktime\transformations\series\clasp.py in <module>
     22 # import numpy.fft as fft
     23 import pandas as pd
---> 24 from numba import njit
     25 
     26 from sktime.transformations.base import _SeriesToSeriesTransformer

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\site-packages\numba\__init__.py in <module>
    196 
    197 _ensure_llvm()
--> 198 _ensure_critical_deps()
    199 
    200 # we know llvmlite is working as the above tests passed, import it now as SVML

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\site-packages\numba\__init__.py in _ensure_critical_deps()
    136         raise ImportError("Numba needs NumPy 1.17 or greater")
    137     elif numpy_version > (1, 20):
--> 138         raise ImportError("Numba needs NumPy 1.20 or less")
    139 
    140     try:

ImportError: Numba needs NumPy 1.20 or less

_______________________________
I had pip installed sktime

Package                  Version
------------------------ -----------
-                        ywidgets
-dm                      4.42.1
-loudpickle              1.1.1
-pywidgets               7.5.1
-qdm                     4.42.1
-umpy                    1.18.1
absl-py                  0.9.0
appdirs                  1.4.4
asn1crypto               1.3.0
astor                    0.8.0
atomicwrites             1.4.0
attrs                    19.3.0
backcall                 0.1.0
beautifulsoup4           4.9.1
bleach                   3.1.1
blinker                  1.4
blis                     0.7.4
bokeh                    2.1.1
cachetools               3.1.1
catalogue                1.0.0
certifi                  2020.12.5
cffi                     1.14.0
cfgv                     3.2.0
chardet                  3.0.4
Click                    7.0
click-plugins            1.1.1
cligj                    0.5.0
cloudpickle              1.3.0
cmdstanpy                0.9.68
colorama                 0.4.3
colorcet                 2.0.6
convertdate              2.3.2
cryptography             2.8
cycler                   0.10.0
cymem                    2.0.5
Cython                   0.29.17
dabl                     0.1.8
decorator                4.4.2
defusedxml               0.6.0
descartes                1.1.0
dill                     0.3.1.1
distlib                  0.3.1
easyAI                   1.0.0.4
en-core-web-sm           2.3.1
entrypoints              0.3
ephem                    3.7.7.1
filelock                 3.0.12
Fiona                    1.8.4
future                   0.18.2
gast                     0.2.2
GDAL                     2.3.3
geographiclib            1.50
geopandas                0.6.1
geopy                    2.0.0
google-auth              1.11.2
google-auth-oauthlib     0.4.1
google-pasta             0.1.8
googleapis-common-protos 1.51.0
googletrans              3.0.0
grpcio                   1.27.2
gym                      0.17.2
h11                      0.9.0
h2                       3.2.0
h5py                     2.10.0
hijri-converter          2.1.1
holidays                 0.11.1
holoviews                1.14.5
hpack                    3.0.0
hstspreload              2020.12.22
httpcore                 0.9.1
httpx                    0.13.3
hvplot                   0.7.3
hyperframe               5.2.0
identify                 2.2.2
idna                     2.8
imbalanced-learn         0.7.0
imblearn                 0.0
importlib-metadata       1.5.0
iniconfig                1.1.1
ipykernel                5.1.4
ipympl                   0.6.3
ipython                  7.13.0
ipython-genutils         0.2.0
ipywidgets               7.6.3
jedi                     0.16.0
Jinja2                   2.11.1
joblib                   0.13.2
jsonschema               3.0.2
jupyter                  1.0.0
jupyter-client           6.0.0
jupyter-console          6.1.0
jupyter-core             4.6.3
jupyterlab-widgets       1.0.0
Keras                    2.3.1
Keras-Applications       1.0.8
Keras-Preprocessing      1.1.0
keras-tuner              1.0.1
kiwisolver               1.1.0
korean-lunar-calendar    0.2.1
langdetect               1.0.7
libpysal                 4.3.0
llvmlite                 0.37.0
loguru                   0.5.3
LunarCalendar            0.0.9
lxml                     4.5.2
Markdown                 3.1.1
MarkupSafe               1.1.1
matplotlib               3.1.3
mistune                  0.8.4
mkl-fft                  1.0.15
mkl-random               1.1.0
mkl-service              2.3.0
momepy                   0.2.1
mpmath                   1.1.0
munch                    2.5.0
murmurhash               1.0.5
n2w                      0.1.3
nbconvert                5.6.1
nbformat                 5.0.4
networkx                 2.4
nltk                     3.5
nodeenv                  1.5.0
notebook                 6.0.3
numba                    0.54.1
numpy                    1.21.3
oauthlib                 3.1.0
opt-einsum               3.1.0
packaging                20.4
pandas                   1.2.3
pandocfilters            1.4.2
panel                    0.12.1
param                    1.11.1
parso                    0.6.2
patsy                    0.5.2
pickleshare              0.7.5
Pillow                   7.1.2
pip                      20.2
plac                     1.1.0
plotly                   4.9.0
plotly-geo               1.0.0
pluggy                   0.13.1
pmdarima                 1.8.0
pre-commit               2.11.1
preshed                  3.0.2
prometheus-client        0.7.1
promise                  2.2.1
prompt-toolkit           3.0.4
prophet                  1.0.1
protobuf                 3.11.4
psutil                   5.7.0
py                       1.10.0
pyasn1                   0.4.8
pyasn1-modules           0.2.7
pycparser                2.19
pyct                     0.4.8
PyExecJS                 1.5.1
pyglet                   1.5.0
Pygments                 2.6.1
PyJWT                    1.7.1
PyMeeus                  0.5.11
pyOpenSSL                19.1.0
pyparsing                2.4.6
pyproj                   1.9.6
pyreadline               2.1
pyrsistent               0.15.7
pyshopee                 1.3.9
PySocks                  1.7.1
pystan                   2.19.1.1
pytest                   6.2.2
python-dateutil          2.8.1
pytz                     2019.3
pyviz-comms              2.1.0
pywin32                  227
pywinpty                 0.5.7
PyYAML                   5.3
pyzmq                    19.0.0
qtconsole                4.7.1
QtPy                     1.9.0
regex                    2020.11.13
requests                 2.23.0
requests-oauthlib        1.3.0
retrying                 1.3.3
rfc3986                  1.4.0
rsa                      4.0
Rtree                    0.9.4
scikit-learn             1.0.1
scikit-plot              0.3.7
scipy                    1.4.1
seaborn                  0.10.0
Send2Trash               1.5.0
setuptools               56.0.0
setuptools-git           1.2
Shapely                  1.6.4.post1
six                      1.14.0
sktime                   0.8.1
sniffio                  1.2.0
soupsieve                2.0.1
spacy                    2.3.5
spacy-langdetect         0.1.2
srsly                    1.0.5
statsmodels              0.13.0
sympy                    1.6.2
tabulate                 0.8.7
tensorboard              2.1.0
tensorflow               2.1.0
tensorflow-datasets      1.2.0
tensorflow-estimator     2.1.0
tensorflow-hub           0.7.0
tensorflow-metadata      0.14.0
tensorflow-probability   0.8.0rc0
termcolor                1.1.0
terminado                0.8.3
terminaltables           3.1.0
testpath                 0.4.4
thinc                    7.4.5
threadpoolctl            2.1.0
toml                     0.10.2
torch                    1.3.1
tornado                  6.0.4
tox                      3.23.0
tqdm                     4.62.1
traitlets                4.3.3
translate                3.5.0
translate-api            4.7.15
typing-extensions        3.7.4.2
ujson                    4.0.2
urllib3                  1.25.8
virtualenv               20.4.3
wasabi                   0.8.2
wcwidth                  0.1.8
webencodings             0.5.1
Werkzeug                 0.16.1
wheel                    0.34.2
widgetsnbextension       3.5.1
win-inet-pton            1.1.0
win32-setctime           1.0.3
wincertstore             0.2
wordcloud                1.8.1
wrapt                    1.11.2
xarray                   0.15.1
xgboost                  1.2.1
xlrd                     1.2.0
zipcodes                 1.1.2
zipp                     3.1.0
WARNING: You are using pip version 20.2; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\programdata\anaconda3\envs\tensorflow_env\python.exe -m pip install --upgrade pip' command.
______________________

**Comment by TonyBagnall** [comment]
hi, you are correct, we need to fix this. I will have a go 
![image](https://user-images.githubusercontent.com/9594042/141643930-d36b8126-1715-4a03-a180-d621a08bca3d.png)

**Comment by TonyBagnall** [comment]
as far as I can tell, there are two main problems with the windows build. 
numba/numpy conflict
fbprophet cant pip install

the latter is fixed with a conda install. The first is made more complex by cython. If you do a full install [all_extras] then downgrade numpy to 1.19, the compiled cython will not work. Installing numpy version first seems to fix the cython, but bizarrely the tests (e.g. series_and_features.tests.test_all_panel_estimators) think we have numpy version 1.21 installed 
![image](https://user-images.githubusercontent.com/9594042/142412907-cdd9a925-faa8-4062-b0ab-6f1f7d903d94.png)

I suspect this might be fixed by simply pinning numpy, and Franz has spelt out the five places (!) this needs to happen, so I will give it a go

**Comment by TonyBagnall** [comment]
putting this here so I can find it again more easily! https://github.com/alan-turing-institute/sktime/issues/1281

**Comment by srinuti** [comment]
Would it be possible to summarize the bug fix please. I tried to follow the
tread unable to understand what exactly needs to be done on my end to make
it work.

With regards
Srinivas

**Comment by fkiraly** [comment]
I think the solution for @TonyBagnall, follow the instructions here:
https://github.com/alan-turing-institute/sktime/issues/1372
(assuming this is on windows)

@TonyBagnall, is that right?

**Comment by srinuti** [comment]
Yes, that is correct. It is windows.

Thanks for addressing this bug shall try and update

**Comment by TonyBagnall** [comment]
Hi, the bug was that numba currently doesn't work with numpy 1.21, so we pinned numpy to 1.19.3. If you want a standard install,, you should simply install numpy 1.19. however, if you want soft dependencies, it's all complicated by fbprophet and cython. We will put some more detailed install instructions up
