### ISSUE TITLE
[DOC] Add toggle button to code examples to remove ">>>", "..." and output 

### ISSUE THREAD

**Issue by RNKuhns** [alan-turing-institute/sktime#1565]
#### Describe the issue linked to the documentation

The way code examples must be formatted in code-blocks is not conducive to copying the examples into a code editor to try out. Scikit-learn has a toggle button on their code examples to remove the ">>>", "...", output and other items that are needed in the code-block, but make it difficult to copy the code directly.  We should implement something similar.

#### Suggest a potential alternative/fix

We need to add javascript to every page that lets users hide the items described above so that the example code is easier to copy. We can easily adapt Scikit-learn's javascript blurb that does this. Then we need to make sure it is included on every page using a layout.html template.

**Comment by TonyBagnall** [comment]
assume we can close this @RNKuhns ?
