### ISSUE TITLE
[DOC] Transformers missing from API Reference

### ISSUE THREAD

**Issue by RNKuhns** [alan-turing-institute/sktime#1569]
#### Describe the issue linked to the documentation

There have been transformers that have recently been improved but have not been added the API Reference. 

For example, STLTransformer, CLaSPTransformer, etc.

#### Suggest a potential alternative/fix

These need to be added to the documentation. 

In the future we'll have to try and be good about following our [reviewer guide](https://www.sktime.org/en/stable/reviewer_guide.html) and waiting to merge until things are added to docs. Otherwise, it is hard for users to know what functionality exists.

**Comment by fkiraly** [comment]
@RNKuhns, what does "have not been added the API Reference" mean here?
I don't think that's a requirement in the reviewer guide currently.

This is what's currently there:

![image](https://user-images.githubusercontent.com/7985502/139558307-cf594709-442f-428c-a61b-e087095a80d1.png)

**Comment by RNKuhns** [comment]
@fkiraly we might not have been explicit enough, but I believe that is part of make sure online docs render correctly. It is also one of the check boxes when you make our PRs. 

It just makes it hard for users to understand sktime’s features unless we make sure we routinely add things to our website.
