### ISSUE TITLE
[DOC] Add Examples to classifier docstrings that currently lack examples

### ISSUE THREAD

**Issue by RNKuhns** [alan-turing-institute/sktime#1570]
#### Describe the issue linked to the documentation

Some of the classifiers don't include and examples section in their docstring. We should update the docstrings to include the examples section. 

- [x] ColumnEnsembleClassifier
- [x] ElasticEnsemble #1584
- [x] ProximityForest #1584
- [x] ProximityTree #1584
- [x] ProximityStump #1584
- [x] TimeseriesForest #1583
- [x] RandomIntervalSpectralForest #1583
- [x] SupervisedTimeseriesForest #1583
- [x] ShapeletTransformClassifier (example imports from non-public module and probably shouldn't)

#### Suggest a potential alternative/fix

Add an examples section to each of these classifiers. Ideally this would be possible by adapting the examples section of other classifiers, but I'm not 100% sure whether the same dataset will be good at illustrating all of them or not since this is not my area of expertise.

**Comment by RNKuhns** [comment]
@TonyBagnall and @MatthewMiddlehurst classification isn't my area of expertise, so I don't know if the same dataset would be good for each classifier.

The current classifier examples all appear to either use dataset from `load_unit_test` or `load_italy_power_demand`. Could you comment as to which dataset would seem like a good option for each classifier?

**Comment by MatthewMiddlehurst** [comment]
We use load_unit_test for speed as they are all run in the testing process. We will get to them all eventually in the refactor.

**Comment by TonyBagnall** [comment]
As Matt says, unit test is there to reduce testing speed and is probably best for examples. Good first issue maybe?

**Comment by TonyBagnall** [comment]
But also the ones you list in particular are not stable and scheduled for revision or deprecation

**Comment by MatthewMiddlehurst** [comment]
For STC you can replace RotationForest with a RandomForest if it is an issue. Can people using the public release not import anything from contrib?

**Comment by RNKuhns** [comment]
@TonyBagnall and @MatthewMiddlehurst I just wanted to collect the ones that needed the examples added so we had a record. Agree this is probably a good first issue.

@MatthewMiddlehurst I’m not sure on the contrib part. But the import with the leading “_” usually denotes from a non-public sub module.

**Comment by TonyBagnall** [comment]
Maybe we should refactor contrib as _contrib?

**Comment by MatthewMiddlehurst** [comment]
Do we want it to be private? 

There is no structure or init files in contrib i'm pretty sure, its the sktime wild west. I don't really think rotation forest should even be there tbh, but its not a time series classifier so it has no other home.

**Comment by TonyBagnall** [comment]
maybe the rotation forest should go in the STC classifier itself? We do that for other specific classifiers, and I dont think the rotation forest implementation is ready to go into scikit-learn...

**Comment by TonyBagnall** [comment]
all these now have examples, rotation forest is now public
