### ISSUE TITLE
[DOC] Extension guidelines should contain a "documentation" section

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1578]
Since in a number of cases, contributors were unaware that documentation must be updated in a certain way when estimators are added (e.g., #1571), I think we need to update the documentation so this is more clear.

Currently, extenders (probably) use the extension template to go through the todos, so I propose we add a section at the end which summarizes the documentation steps "if you add the estimator to `sktime`". This way, it's all in one place (and the place that people already know).

FYI @RNKuhns.
It seems you know what precisely the steps are? Would be really great if you could turn your knowledge in a paragraph or bullet point checklist. Happy to help, but I'm not sure whether I know the steps.

**Comment by mloning** [comment]
Adding a link to the webpage would be good: https://www.sktime.org/en/stable/developer_guide/add_estimators.html
