### ISSUE TITLE
[ENH] window summary transformer

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1581]
We've agreed that we need to implement the following transformer:

`WindowSummaryTransformer`

parameters:
* `window_type: "sliding" (default) or "expanding"`
* `window_size: int or datetime.timedelta`
* `agg_func: str or function; if str, one of "mean", "max", "min", "median"; if function, must be pd.DataFrame (n rows) -> pd.DataFrame (one row)`
* `lags: list of int`, list of lags that are used.

`fit` is empty.
In `transform(X)`, computes `agg_func` of each window (ending at any index in `X`) and appends the results to a `pd.DataFrame`. The index of the `agg_func` output is identical with the index at which the window ends.

Might also be worthwhile to have a `LagTransformer`, which has only the `lags` parameter?

**Comment by fkiraly** [comment]
@danbartl, I think you were working on this, right?

**Comment by fkiraly** [comment]
Please correct the preamble if the signature you are implementing is different, @danbartl

**Comment by mloning** [comment]
Can we call it `window_length` instead of `window_size` to make it consistent with other classes?

**Comment by fkiraly** [comment]
closing this in favour of #1612, see discussion there.
