### ISSUE TITLE
[BUG] docs/readthedocs.org:sktime — Read the Docs build failed!

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1587]
**Describe the bug**
the readthedocs tests are failing on multiple, unrelated PRs with the file

![image](https://user-images.githubusercontent.com/9594042/140315278-9cb76e53-72e4-4e88-afd1-6b679fddae2e.png)

**To Reproduce**

to reproduce, create a PR into main. Dee, for example

https://github.com/alan-turing-institute/sktime/pull/1584
https://github.com/alan-turing-institute/sktime/pull/1583

**Expected behavior**
the test should pass since nothing has changed in the PRs that could feasibly and independently generate it

**Comment by TonyBagnall** [comment]
I have no clue about this CI stuff. Any ideas @freddyaboulton or @mloning? This may be relevant? Need setuptools 5.5.3? 
https://gitmemory.cn/repo/pyodide/pyodide/issues/1930

https://github.com/pypa/setuptools/issues/2849

**Comment by freddyaboulton** [comment]
@TonyBagnall Can we try re-running the RTD build on those PRs? Looks like setuptools pushed a new release since the last commit on those PRs that should fix the problem.

**Comment by TonyBagnall** [comment]
yep fixed by the external package, thanks @freddyaboulton
