### ISSUE TITLE
[DOC] Improve Doc Strings for Temporal Cross validators

### ISSUE THREAD

**Issue by knsantosh27** [alan-turing-institute/sktime#1590]
#### Describe the issue linked to the documentation
 - Currently, the docstrings do not have examples or see also sections.

 
#### Suggest a potential alternative/fix
-   Add simple examples and see also section linking to other cross-validation functionality.

**Comment by mloning** [comment]
Hi @knsantosh27 and sorry for the late reply. There is some documentation here: https://github.com/alan-turing-institute/sktime/blob/main/examples/window_splitters.ipynb but I agree that updating the docstrings would be helpful.

**Comment by fkiraly** [comment]
I think @khrapovs was working on this - I feel that has notably improved and we can consider this closed.
