### ISSUE TITLE
[BUG] evaluate raises KeyError for AutoETS and CutoffSplitter / SlidingWindowSplitter - issue with BaseForecaster._update_y_X

### ISSUE THREAD

**Issue by ltsaprounis** [alan-turing-institute/sktime#1593]
**Describe the bug**
evaluate function raises an invalid error for the CutoffSplitter and SlidingWindowSplitter. 
ExpandingWindowSplitter works fine.

The error initially appears to be in the _predict method of ets.
But, a few debug prints later I managed to pinpoint the issue in the [_update_y_X](https://github.com/alan-turing-institute/sktime/blob/922cd71d0d82d849025a080be826cf1c3c4777e5/sktime/forecasting/base/_base.py#L804) method of the BaseForecaster class.

If the forecaster was fitted before and is now refitted, forecaster._y is not changed based on the new y_train and this causes a difference in the absolute horizon of y and the prediction output. This explains why we don't get the error in the ExpandingWindowSplitter as in that case forecaster._y[0] is the same for all splits.

**To Reproduce**
```python
import numpy as np
import pandas as pd
from sktime.forecasting.ets import AutoETS
from sktime.forecasting.model_selection import CutoffSplitter
from sktime.forecasting.model_evaluation import evaluate
from sktime.performance_metrics.forecasting import MeanSquaredScaledError

synthetic_data = pd.Series(
    10 + np.random.lognormal(5, 1, 365),
    index = pd.PeriodIndex(pd.date_range(start="2020-01-01", freq="D", periods=365), freq="D"), 
)

custom_cutoffs = np.array([
    len(synthetic_data[synthetic_data.index < date]) 
    for date in 
    [
        "2020-07-01",
        "2020-08-01", 
        "2020-09-01", 
        "2020-10-01", 
        "2020-11-01", 
        "2020-12-01",
    ]
])

# create the CV object
CV = CutoffSplitter(
    # custom cuttoffs
    cutoffs=custom_cutoffs, 
    # 3 step ahead forecast
    fh=np.arange(3)+1,
    # 5 years of training data
    window_length=6*30,
)

evaluate(
    forecaster=AutoETS(),
    y=synthetic_data,
    cv=CV,
    strategy="refit",
    return_data=True,
    scoring=MeanSquaredScaledError(square_root=True),
)

>>>  KeyError: "None of [PeriodIndex(['2020-08-02', '2020-08-03', '2020-08-04'], dtype='period[D]')] are in the [index]"
```

**Expected behavior**
evaluate should run smoothly for all cv strategies.
BaseForecaster._y should be updated based on the latest training data. 
I suggest we remove the combine_first logic from  [_update_y_X](https://github.com/alan-turing-institute/sktime/blob/922cd71d0d82d849025a080be826cf1c3c4777e5/sktime/forecasting/base/_base.py#L804), but I'm not sure if it serves a different purpose elsewhere.

Otherwise a deepcopy(forecaster) in evaluate will solve the problem too.

**Comment by fkiraly** [comment]
Yes, this is indeed a problem. Caused by `fit` called multiple way with side effects.

Clean ways would be:

* use `sklearn` `clone` inside the cv - that's the "standard" way.
* implement a (clone-like) `reset` in the base class, and always call it at the start of `fit`.
