### ISSUE TITLE
[DOC] The documentation of sktime.classification.base.BaseClassifier.fit inaccurately describes the input parameters.

### ISSUE THREAD

**Issue by paulsbrookes** [alan-turing-institute/sktime#1596]
#### Describe the issue linked to the documentation

The documentation of sktime.classification.base.BaseClassifier.fit says that it can accept a 2D np.array for X, but this doesn't work. The input is required to be 3D. Demonstrated by:

```
from sktime.classification.dictionary_based import BOSSEnsemble
import numpy as np

model = BOSSEnsemble()
X = np.random.randn(200, 10)
y = np.random.randn(200)
model.fit(X, y)
```

Produces the error:
```
Traceback (most recent call last):
  File "/home/paul/.config/JetBrains/PyCharmCE2021.2/scratches/scratch.py", line 7, in <module>
    model.fit(X, y)
  File "/home/paul/PycharmProjects/sktime/sktime/classification/base.py", line 86, in fit
    X, y = check_X_y(
  File "/home/paul/PycharmProjects/sktime/sktime/utils/validation/panel.py", line 188, in check_X_y
    X = check_X(
  File "/home/paul/PycharmProjects/sktime/sktime/utils/validation/panel.py", line 74, in check_X
    raise ValueError(
ValueError: If passed as a np.array, X must be a 3-dimensional array, but found shape: (200, 10)
```

#### Suggest a potential alternative/fix

Remove
```
2D np.array (univariate, equal length series) of shape = [n_instances,
        series_length]
            or 
```
from the documentation.

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this, but I'm still not used to the structure of the project. Where can I find the docs you mention? I have looked around for a bit without any success.

**Comment by paulsbrookes** [comment]
Hi. Thanks for looking into it. The documentation is in sktime/sktime/classification/base.py. You need to go to the fit method of the BaseClassifier class. You'll find the following block of documentation there:

        """Fit time series classifier to training data.
        Parameters
        ----------
        X : 2D np.array (univariate, equal length series) of shape = [n_instances,
            series_length]
            or 3D np.array (any number of dimensions, equal length series) of shape =
            [n_instances,n_dimensions,series_length]
            or pd.DataFrame with each column a dimension, each cell a pd.Series (any
            number of dimensions, equal or unequal length series)
        y : 1D np.array of shape =  [n_instances] - the class labels.
        Returns
        -------
        self :
            Reference to self.
        Notes
        -----
        Changes state by creating a fitted model that updates attributes
        ending in "_" and sets is_fitted flag to True.
        """

**Comment by TonyBagnall** [comment]
hi, yes sorry, this was in there from before my last refactor, but I left it in. I am working on a PR to allow 2D input and it will hopefully go in next week.

**Comment by paulsbrookes** [comment]
Thanks! Sounds good.

**Comment by TonyBagnall** [comment]
hi, this is fixed by https://github.com/alan-turing-institute/sktime/pull/1604 let us know if you have any problems
