### ISSUE TITLE
Remove unused `_assertions` method in signatures module

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1598]
See below: `_assertions` in `_signature_method.py` is no longer used or needed, this should be removed from the code base according to @jambo6.

---

(Author here), its not used anywhere, my apologies. I moved the checks into the respective sub-transformers that are called and forgot to delete this one. Safe to remove.

_Originally posted by @jambo6 in https://github.com/alan-turing-institute/sktime/pull/1365#discussion_r735344987_

**Comment by Carlosbogo** [comment]
Hi, I would be glad to help with this.

**Comment by fkiraly** [comment]
Thanks!
