### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lfereman** [alan-turing-institute/sktime#161]
**Describe the bug**
SAX module not working

**To Reproduce**
```python
import numpy as np
import pandas as pd
import sktime
from sktime.datasets import load_gunpoint

X_train, y_train = load_gunpoint(split='TRAIN', return_X_y=True)
X_test, y_test = load_gunpoint(split='TEST', return_X_y=True)
from sktime.transformers.dictionary_based import SAX

print("iloc[0]: {}".format(X_train.iloc[0].to_numpy()))
sax = SAX.SAX(window_size=10, word_length=5, alphabet_size=4)
D_X_train = sax.transform(X_train)
print("sax(iloc[0]): {}".format(D_X_train[0].to_numpy()))
```

**Expected behavior**
Runs with compile/runtime errors

**Additional context**
Error is in line 112 in SAX.py, where you refer to:
shapelets.RandomShapeletTransform.zscore(split, axis=None)  # move to utils or create new method?

which should be:
split = shapelets.ShapeletTransform.zscore(split, axis=None) 

I would suggest you make simple unit tests, where somethine, like the SAX transform module, is run on some fixed array and checked if the output is still valid.

**Versions**
<details>
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)]
NumPy 1.17.2
SciPy 1.3.1
sktime 0.3.0

</details>

**Comment by TonyBagnall** [comment]
hi thanks for that, we will take a look and get back to you.

**Comment by TonyBagnall** [comment]
should be fixed in dev, will go into master on next release, thanks for finding it
