### ISSUE TITLE
[ENH] Design and API for Early Classification

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [alan-turing-institute/sktime#1616]
Early classification revolves around allowing classifiers to take incomplete series (i.e, the first half of a series recorded over a day) and decide whether it can make an accurate prediction or not with the presented partial time series. These algorithms are similar enough to the rest of the classification package that they could just reside in a sub-package for now, such as `classification/early_classification`.

While most of the current classification API is suitable for these algorithms, some issues may arise and will require discussion: 
- How do we deal with an algorithm refusing to make a prediction? Both in the sense of what would we actually return (`None` seems reasonable) and how would we go about testing, as returning this is likely to break some of the standard classifier ones.
- How do we verify input when predicting? Some algorithms can only make decisions at specific series lengths (commonly in 5% intervals), do any additions need to be made for this, or should it be left to the individual algorithm? 
- Some algorithms keep data from previous prediction attempts, i.e. a decision at 15% of the series may use information from the decisions at 5% and 10%. Do we require any additional predict inputs to accommodate this? How do we reset for new data when predicting?
- Do we require an extended base class for any of this? Would having it anyway help with testing, or would it be better as a tag?

Good first implementations would be [TEASER](https://link.springer.com/article/10.1007/s10618-020-00690-z) and a simple probability threshold for making the decision.

**Comment by MatthewMiddlehurst** [comment]
@patrickzib has shown interest in the topic from previous discussions, though anyone feel free to contribute and edit the issue if necessary.

**Comment by MatthewMiddlehurst** [comment]
I have put up a draft PR #1630 containing probability threshold early classifier as a test. I have set it up to follow the current classification API as much as possible. We can completely revamp any part of it as we make decisions, but it may require an extended base class to be implemented.

To make sure the current tests pass and that we can use BaseClassifier, a second function is used to determine whether the predictions/probabilities are safe.

> Interesting question! :) I would rather say, one should keep the classifier state-less

Agreed, currently I have set up the decision method to take and return a tuple of values containing the current state. The second option could get very expensive depending on the algorithm.

**Comment by MatthewMiddlehurst** [comment]
Any objections to closing this issue? Any problems with the early classification base class or early classifiers should be raised as a separate issue, IMO.

**Comment by fkiraly** [comment]
no, I thought we arrived at a consolidated design through discussions on the early classification PR.
Perhaps just link those discussions here, then close?

**Comment by MatthewMiddlehurst** [comment]
That's fair.

Initial discussion regarding early classification is mostly in the TEASER PR: #2162

The early classification base class PR and discussion is here: #2235
