### ISSUE TITLE
[BUG] Use prophet instead of fbprophet in requirements

### ISSUE THREAD

**Issue by freddyaboulton** [alan-turing-institute/sktime#1631]
**Describe the bug**

Posted in :

> I think we need to switch over to the prophet package as opposed to fbprophet. I think the problem is that fbprophet is quite old and they list pystan>=2.14 as a requirement. This causes pystan 3.2.0 to be installed which is actually not compatible with prophet! Prophet only supports pystan 2. prophet has the correct pin of pystan~=2.19.1.1.

You can repro this like follow:
- Download the fbprophet tar ball [here](https://pypi.org/project/fbprophet/#files)
- Open `requirements.txt`

You should see the following:
```
Cython>=0.22
cmdstanpy==0.9.5
pystan>=2.14
numpy>=1.15.4
pandas>=1.0.4
matplotlib>=2.0.0
LunarCalendar>=0.0.9
convertdate>=2.1.2
holidays>=0.10.2
setuptools-git>=1.2
python-dateutil>=2.8.0
tqdm>=4.36.1
```

`pystan>=2.14` will install the latest pystan ([pystan 3](https://pypi.org/project/pystan/)). However, Prophet does not support [pystan 3](https://github.com/facebook/prophet#installation-in-python)!!

I suspect this is making our build more complicated than it needs to be.

**Comment by freddyaboulton** [comment]
Filed this to hopefully remove fbprophet from package repositories:  https://github.com/facebook/prophet/issues/2074

**Comment by baggiponte** [comment]
Hi, I tried out what @freddyaboulton suggested. My `build_tools/requirements.txt` does not look like the one posted above (see down here). To reproduce this, I did the following:

* Created a `conda` environment named `sktime` with Python 3.8 and `pip`
* Followed the steps [here](https://www.sktime.org/en/latest/get_involved/contributing.html#git-and-github-workflow)
* In the `build_tools/requirements.txt` as follows, changed `fbprophet>=0.7.1` to `prophet>=1.0.0`. 
* Ran `pip install -r build_tools/requirements.txt`

The first time it tried to install `prophet` it failed, then installed `numpy` and then `pip` successfully installed `prophet` again. Note: in this way, the `pystan` version installed is `pystan-2.19.1.1`.

```
cython>=0.29.0
deprecated>=1.2.13
dtw_python>=1.1.5
esig==0.9.7
fbprophet>=0.7.1 --> prophet>=1.0.0
hcrystalball>=0.1.9
numba==0.53
numpy==1.19.3
pandas==1.1.5
pmdarima>=1.8.0,!=1.8.1
pyod>=0.8.0
pystan>=2.14,<3.0
pytest
pytest-cov
scikit-learn==0.24.*
scikit-posthocs
statsmodels==0.12.1
stumpy>=1.5.1,<=1.9.2
tbats>=1.1.0
tsfresh>=0.17.0
wheel
```

**Comment by baggiponte** [comment]
Another notice: folks at darts use [these requirements](https://github.com/unit8co/darts/blob/master/requirements/prophet.txt) for prophet:

```
prophet>=1.0.0
pystan>=2.19.1.1,<3.0.0.0
```

Will try them as soon as I can, in theory they should work - as I noted above:

> Note: in this way, the pystan version installed is pystan-2.19.1.1.

Guess I will use these when I prepare the PR.

(A side mention: why is `pandas` frozen at 1.15?)
