### ISSUE TITLE
Will it work for Windows?

### ISSUE THREAD

**Issue by Sandy4321** [alan-turing-institute/sktime#164]
Will it work on Windows?

**Is your feature request related to a problem? Please

 describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods. 

**Describe alternatives you've considered**

**Additional context**

**Comment by TonyBagnall** [comment]
hi, yes it works on windows, I am running it with pycharm on a windows box as I type!

**Comment by Sandy4321** [comment]
great
so will it work for multivariate time series with mixture of categorical and continues values
as I can see from example
https://github.com/alan-turing-institute/sktime/blob/master/examples/multivariate_time_series_classification.ipynb
it works only for continues values?
for example two variables are categorical and 3 variables are continues values?
like this
t1
green, black, yellow
0.3, 12, 0.4, 0.8, 0.1
big , small, small, big, medium
123, 345, 789, 1009, 2002, 30, 56, 78, 
0.1, 0.2, 0.5
t2
yellow, green, black, blue
0.43, 162, 0.64, 01.8, 0.771
small, big, medium,big , small, 
13, 45, 79, 109, 200, 390, 536, 178,333 
10, 0.1, 0.2, 
t3
etc

????
