### ISSUE TITLE
[BUG] evaluate fails with Imputer

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#1643]
**Describe the bug**
Calling `evaluate` with a pipeline and imputer fails.  

**To Reproduce**
```python
import pandas as pd
import numpy as np
from sktime.transformations.series.impute import Imputer
from sktime.forecasting.compose import ForecastingPipeline
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.model_evaluation import evaluate
from sktime.forecasting.model_selection import SlidingWindowSplitter

y = pd.Series(np.random.normal(size=100))
X = pd.DataFrame(np.random.normal(size=(100, 2)))
X.iloc[3, 1] = np.nan

cv = SlidingWindowSplitter(fh=[1, 2, 3])

forecaster = ForecastingPipeline([
    ("impute", Imputer()),
    ("forecast", NaiveForecaster())
])

evaluate(forecaster, cv=cv, y=y, X=X)
```

**Expected behavior**
No error. 

**Versions**
<details>
System:
    python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:37:09)  [Clang 10.0.1 ]
executable: /Users/mloning/.conda/envs/sktime-dev/bin/python
   machine: Darwin-19.6.0-x86_64-i386-64bit

Python dependencies:
          pip: 21.2.4
   setuptools: 49.6.0.post20210108
      sklearn: 0.24.2
       sktime: 0.8.1
  statsmodels: 0.12.1
        numpy: 1.19.3
        scipy: 1.6.0
       Cython: 0.29.21
       pandas: 1.2.3
   matplotlib: 3.3.4
       joblib: 1.0.1
        numba: 0.53.1
     pmdarima: 1.8.2
      tsfresh: 0.17.0
</details>

**Comment by aiwalter** [comment]
I get `ValueError: `fh` must not be empty`. From first look:  Seems its coming from the `PolynomialTrendForecaster` which is used in `Imputer` with `method=drift`. I guess it needs `fh` in `fit()`? So we might have to pass `fh` also in `evaluate`?

**Comment by mloning** [comment]
Yes, I get the same error. 

I think `evaluate` works fine. Note that we pass the `fh` twice both to `fit` and `predict` which is unnecessary, passing it only in `fit` should be fine. 

I'm not sure, but think the issue is in `_impute_with_forecaster` where we construct the `fh` from the index of missing values (line 207), can it not be that for some columns there are no missing values and hence we get an empty `fh`?

**Comment by aiwalter** [comment]
ah yep, we should then probably first check if there is anything to impute at all, if not we even dont need to use the `PolynomialTrendForecaster`. Also it would be faster for `Imputer`

**Comment by aiwalter** [comment]
I guess the issue might also be related to the case that you are using multivariate here. I will try to fix it in next days if I have time :)
