### ISSUE TITLE
[BUG] all_tags returns empty list with estimator type

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#1647]
**Describe the bug**
`all_tags` returns empty list when passing estimator type. I suspect it was just copied over from `all_estimators` and can just be removed for now. Otherwise the docstring needs to be updated too. 

**To Reproduce**
```python
from sktime.registry import all_tags
all_tags(estimator_types="forecaster")
```

**Expected behavior**
Get list of tags applicable for given estimator type.

**Comment by fkiraly** [comment]
fixed in the linked PR
