### ISSUE TITLE
[MND] request: osx-arm64 build in conda-forge

### ISSUE THREAD

**Issue by ivaquero** [alan-turing-institute/sktime#1654]
Hi, I am a user of this wonderful package and I just switched to Mac M1. 

Do you have any plan for osx-arm64 build in conda-forge? I saw all of the dependencies have already got arm64 build.

**Comment by fkiraly** [comment]
@freddyaboulton, @lmmentel, @mloning, FYI

**Comment by lmmentel** [comment]
Thanks for reporting this! As far as I know there is no immediate plans to support M1 since it's hard to find build environments supporting M1 at the moment. There might be ways around but that would require some effort.

The good news is that a there are efforts in sktime for eliminating the compiled code and once the codebase is pure python distribution and support for more platforms should increase - provided that you can install a supported version of python.

As for the timeline I'll let @fkiraly and @mloning comment.

As an intermediate solution and provided you are feeling a bit adventurous you can build/install the sktime from source :wink:

**Comment by fkiraly** [comment]
Yes, i think @lmmentel is right: let's revisit this once the compiled code is gone. I suspect v0.10.0 is when that will be the case, start of 2022. python 3.9 support is also a higher priority.

If until then someone has good pointers on the build environments, much appreciated.

Regarding installing from source, you can have a look at our [installation guide](https://www.sktime.org/en/stable/installation.html). Might also be very useful @ivaquero if you can record the install steps that work for you in this issue, if you are going to try. E.g., what is the same, what is different.

**Comment by ivaquero** [comment]
Thank you so much. Good suggestions, I will try to explore workarounds.

**Comment by patrickzib** [comment]
@ivaquero Did you succeed in building it on ARM64? I did try to build it from source using miniconda for ARM64 with python 3.8, but it failed. Can't recall the exact errors. I did not proceed there and went back to python for intel and using rosetta2.

**Comment by fkiraly** [comment]
Once this https://github.com/alan-turing-institute/sktime/pull/1620 and the C removal are through (SOON!), you may like to try again. As @lmmentel says, the latter may increase support among not officially supported ones.

**Comment by ivaquero** [comment]
> @ivaquero Did you succeed in building it on ARM64? I did try to build it from source using miniconda for ARM64 with python 3.8, but it failed. Can't recall the exact errors. I did not proceed there and went back to python for intel and using rosetta2.

No, but like @fkiraly puts, I will try after next minor version.

**Comment by patrickzib** [comment]
@ivaquero thank you! just curious about your setup: in the mean time : 
(a) you are not installing sktime to stick with python on arm or 
(b) you are using python on intel with rosetta and sktime? 
(c) or did you manage to have both python versions for arm and intel installed?

**Comment by ivaquero** [comment]
> @ivaquero thank you! just curious about your setup. in the mean time : 
> 
> (a) you are not installing sktime to stick with python on arm or 
> 
> (b) you are using python on intel with rosetta and sktime? 
> 
> (c) or did you manage to have both python versions for arm and intel installed?
> 
> 
> 
> As mentioned above, I found no other solution than to fall back to python on intel

I stick on Python on ARM, because all of the other packages were installed on it, especially tensorflow (I believe this could be faster, though I did not do benchmark tests.

**Comment by lmmentel** [comment]
FYI I managed to build wheels for arm64 macos:

- `sktime-0.9.0-cp38-cp38-macosx_11_0_arm64.whl`
- `sktime-0.9.0-cp39-cp39-macosx_11_0_arm64.whl`

If you don't have any other choice you can download the wheel [here](https://github.com/lmmentel/sktime/suites/4871241916/artifacts/139016263) however this is not an official release but vanilla `sktime` build. 

In the following release we should be able to ship wheels for macosx 11 arm64 to pypi, so they would be installable with pip.

**Comment by freddyaboulton** [comment]
Now that the compiled code is gone, we can create a platform agnostic wheel right? @fkiraly @lmmentel

**Comment by lmmentel** [comment]
Conda package is now `noarch` so it should work on M1 https://anaconda.org/conda-forge/sktime. I'll close this one and let you open a new issue if there are installation problems.
