### ISSUE TITLE
[BUG] Prophet wrapper internally changing argument X (exogenous data)

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [alan-turing-institute/sktime#1673]
> **Describe the bug**

When fitting prophet with exogenous data, the wrapper changes the argument `X` resulting in some issues; you can't use the same variable X as argument twice since it'll contain the column name `ds` after the first run, so you need to create copies at each occurence. 
It gets worse when you do a `fit_predict` since the X changes internally (because of `fit`), when `fit_predict` calls `predict`, it raises an error that you can't work around with copies.

**To Reproduce**

```python
from sktime.forecasting.fbprophet import Prophet
import pandas as pd
import numpy as np

y_train = pd.Series(np.arange(1,21), index=pd.date_range(start='1/1/2021', end='20/1/2021'))
X_train = pd.DataFrame(data=np.arange(1,21), columns=['something'], index=pd.date_range(start='1/1/2021', end='20/1/2021'))

arima_forecaster = Prophet()
arima_forecaster.fit_predict(fh=y_train.index, y=y_train, X=X_train)
print(X_train)
```

> **Traceback**
```
ValueError                                Traceback (most recent call last)
<ipython-input-4-30650cb58dc7> in <module>()
      7 
      8 arima_forecaster = Prophet()
----> 9 arima_forecaster.fit_predict(fh=y_train.index, y=y_train, X=X_train)
     10 print(X_train)

3 frames
/usr/local/lib/python3.7/dist-packages/sktime/forecasting/base/adapters/_fbprophet.py in _merge_X(df, X)
    197     X.columns = X.columns.astype(str)
    198     if "ds" in X.columns:
--> 199         raise ValueError("Column name 'ds' is reserved in fbprophet")
    200     X.loc[:, "ds"] = X.index
    201     # df = df.merge(X, how="inner", on="ds", copy=False)

ValueError: Column name 'ds' is reserved in fbprophet
```

> **Expected behavior**

to fit and predict without changing arguments so that it can fit_predict without error

> **Versions**

<details>
System:
    python: 3.7.12 (default, Sep 10 2021, 00:21:48)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic

Python dependencies:
          pip: 21.1.3
   setuptools: 57.4.0
      sklearn: 1.0.1
       sktime: 0.8.1
  statsmodels: 0.10.2
        numpy: 1.19.5
        scipy: 1.4.1
       Cython: 0.29.24
       pandas: 1.1.5
   matplotlib: 3.2.2
       joblib: 1.1.0
        numba: 0.54.1
     pmdarima: None
      tsfresh: None
</details>

**Comment by fkiraly** [comment]
@IlyasMoutawwakil, are you positive that this is a *side effect* on the argument `X`?
That is, is the object `X`, after passing to the prophet estimator, differenf from when passed?

I would be surprised.
Why was this not captured by `test_all_estimators/test_methods_have_no_side_effects`?

**Comment by fkiraly** [comment]
ah, I can answer this myself: `_make_args` creates no `X` for forecasting.

So the test would not detect a side effect in `X`.

**Comment by fkiraly** [comment]
I've turned the lack of test coverage in an issue here:
https://github.com/alan-turing-institute/sktime/issues/1674

**Comment by IlyasMoutawwakil** [comment]
I'm pretty positive, here I created X_train dataframe with no `ds` column and was added to it after the call to `fit`.

https://colab.research.google.com/drive/1TtZJMLKIC2jJUPmWanbBAn9GobtCPJEZ?usp=sharing

**Comment by mloning** [comment]
Yes, I've observed the same before but forgot to raise the issue. Thanks for raising it now @IlyasMoutawwakil!

**Comment by aiwalter** [comment]
so basically we just have to add `X = X.copy()`? Is so, this should probably happen in the base class

**Comment by IlyasMoutawwakil** [comment]
@aiwalter I can't see how `X = X.copy()` would solve it, I guess all of the problem comes from the function `_merge_X` which modifies `X` (by adding `ds` to it) then merges it with `df` at lines 200-202 in _fbprophet.py :
```python
X.loc[:, "ds"] = X.index
# df = df.merge(X, how="inner", on="ds", copy=False)
df = df.merge(X, how="inner", on="ds")
return df, X.drop(columns="ds")
```
a simple solution would be not adding `ds` to `X` and in the merging line `df =  merge(X.rename({'index': 'ds'}, ...)` that's if we're avoiding creating a local variable at all costs.

**Comment by fkiraly** [comment]
we also need to check whether the case that `X` *already* has a column named `ds` is covered properly.

**Comment by fkiraly** [comment]
> so basically we just have to add X = X.copy()? 

I think that would work, first thing in `_fit` and `_predict`.
Seems a simple fix, hence good first issue.

**Comment by fkiraly** [comment]
@kejsitake offered to work on this, thanks!

**Comment by kejsitake** [comment]
> we also need to check whether the case that X already has a column named ds is covered properly.

Hi! I am working on this bug and wanted to check if this is referring to the tests or if we should throw an error in the base class if the X already contains a column named ds.

**Comment by fkiraly** [comment]
I think neither - it is the prophet class that needs to be fixed.
None of the forecasters should behave differently with a column `ds` or without.
None of the forecasters should change argument `X` being passed to them.

So there are two things to fix:
* high-priority, the side effect of the prophet forecaster on `X` - the argument should not be modified
* lower-priority, writing a test that would catch this (this is issue #1674)
