### ISSUE TITLE
Estimator Test Parameters Refactor

### ISSUE THREAD

**Issue by Aparna-Sakshi** [alan-turing-institute/sktime#1678]
### Aim
To start to move default parameters out of `tests/_config` and into the concrete estimators, by specifying the parameters inside the `get_test_params` method.

This would declutter the logic, and make extending sktime much easier - since it reduces the "points of extension" by one. Default parameters would no longer have to be entered in _config but become part of the list of things to implement, in the extension template.

### Related Issue
#1098 

### Step
[link for step](https://github.com/sktime/enhancement-proposals/blob/main/steps/12_estimator_test_instances/step.md)
This issue is associated with point 3 of the **suggested refactor sequence** given in the above step.

### Contributing Guidelines
If you would like to work on this: please post here and which estimator you are taking on, to avoid duplication of work.
A core dev will then add your name to the estimator under refactoring and/or link the PR.

A general recipe for refactoring is as follows:
- pick up an estimator class from the below checklist of estimators.
- look for parameters of the estimator in `ESTIMATOR_TEST_PARAMS` (in the tests._config file)
- add `get_test_params` method to the corresponding estimator class which returns a dictionary of the above parameters 
- refer to [extension template](https://github.com/alan-turing-institute/sktime/tree/main/extension_templates) to add get_test_params to the corresponding estimator class
- For example, in case of `ColumnEnsembleForecaster` , dictionary of parameters which is `{"forecasters": FORECASTER} `, should be returned from `get_test_params` method. 

Checklist of estimators:

- [x] ColumnEnsembleForecaster
- [x] OnlineEnsembleForecaster
- [x] FeatureUnion
- [x] DirectTabularRegressionForecaster
- [x] MultioutputTabularRegressionForecaster
- [x] RecursiveTabularRegressionForecaster
- [x] DirRecTabularRegressionForecaster
- [x] DirectTimeSeriesRegressionForecaster
- [x] RecursiveTimeSeriesRegressionForecaster
- [x] MultioutputTimeSeriesRegressionForecaster
- [x] DirRecTimeSeriesRegressionForecaster
- [x] TransformedTargetForecaster
- [x] ForecastingPipeline
- [x] EnsembleForecaster
- [x] StackingForecaster
- [x] AutoEnsembleForecaster
- [x] Detrender
- [x] ForecastingGridSearchCV
- [x] ForecastingRandomizedSearchCV
- [x] TabularToSeriesAdaptor
- [x] ColumnEnsembleClassifier
- [x] FittedParamExtractor
- [x] SeriesToPrimitivesRowTransformer
- [x] SeriesToSeriesRowTransformer
- [x] ColumnTransformer
- [x] AutoARIMA
- [x] MultiplexForecaster
- [x] ShapeletTransformClassifier
- [x] ContractedShapeletTransform
- [x] ShapeletTransform
- [x] SignatureTransformer
- [x] SignatureClassifier
- [x] Catch22Classifier
- [x] MatrixProfileClassifier
- [x] TSFreshClassifier
- [x] ROCKETClassifier
- [x] Arsenal
- [x] HIVECOTEV1
- [x] TSFreshFeatureExtractor
- [x] TSFreshRelevantFeatureExtractor
- [x] TSInterpolator
- [x] RandomIntervalSpectralForest
- [x] SFA
- [x] ContractableBOSS
- [x] TemporalDictionaryEnsemble
- [x] TimeSeriesForestClassifier
- [x] ComposableTimeSeriesForestClassifier
- [x] ComposableTimeSeriesForestRegressor
- [x] SupervisedTimeSeriesForest
- [x] CanonicalIntervalForest
- [x] DrCIF
- [x] HCrystalBallForecaster
- [x] BATS
- [x] TBATS
- [x] Prophet
- [x] UnobservedComponents
- [x] PartialAutoCorrelationTransformer
- [x] AutoCorrelationTransformer
- [x] Imputer
- [x] HampelFilter
- [x] OptionalPassthrough
- [x] FeatureSelection
- [x] ColumnwiseTransformer
- [x] AggrDist
- [x] PyODAnnotator
- [x] ClaSPSegmentation

**Comment by Aparna-Sakshi** [comment]
@fkiraly Let me know if I have to make any changes to the above issue.

**Comment by fkiraly** [comment]
thanks, great work!
Can you kindly update this and merge with #1098 (which is sort of a duplicate).

I.e., move useful things from #1098 such as explanations here, and then we can close #1098.

**Comment by fkiraly** [comment]
most forecasters dealt with here:
https://github.com/alan-turing-institute/sktime/pull/1902
(checked above, since don´t anticipate much problems)

**Comment by shubhamkarande13** [comment]
Hi @fkiraly and @Lovkush-A!

Can I work on this issue?
I could start with refactoring `FeatureUnion` and then move on towards the forecasters.

**Comment by Lovkush-A** [comment]
@fkiraly Bit of context: shubham and i have had a small back and forth in slack, resulting in a call on the weekend in which i helped shubham understand this issue. I recommended starting with just one estimator to make sure he (and I) has not missed any details, and then can continue to do remainder of work in batches.

**Comment by shubhamkarande13** [comment]
@fkiraly I will start working on `FeatureUnion` as discussed on Slack. 👍🏼

**Comment by lielleravid** [comment]
Hey @fkiraly and @Lovkush-A
I would like to start working on refactoring the TimeSeriesForestClassifier :)

**Comment by mariamjabara** [comment]
Hi, I would like to start working on refactoring the FittedParamExtractor :)

**Comment by kcc-lion** [comment]
Hey @fkiraly,
I would like to do test params refactoring for the ColumnTransformer.

**Comment by fkiraly** [comment]
all remaining estimators now have open PR. Removing "good first issue" and will close once all is merged.
