### ISSUE TITLE
[ENH] Forecasters: prediction interval, probabilistic forecasting interface refactor

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1687]
We're currently working on a major refactor of the forecasting core interfaces to allow probabilistic and interval predictions.
The design is here:
https://github.com/sktime/enhancement-proposals/blob/main/steps/13_proba_forecasting/step.md

Major work items:

Design:
- [x] STEP (design) #984

Interface/framework refactor:
- [x] framework: `predict_interval` and `predict_quantiles`
- [x] framework: `predict_var`
- [x] framework: `predict_proba` 

Refactoring or adding individual methods:
- [x] `predict_interval` and `predict_quantiles`
    - [x] `ARIMA`,  `AutoARIMA` (inherit from same intermediate adaptor class) #1874
    - [x] `AutoETS` #1874 
    - [x] BATS/TBATS - https://github.com/alan-turing-institute/sktime/pull/1842 by @k1m190r
    - [x] `ThetaForecaster` - https://github.com/alan-turing-institute/sktime/pull/1579
    - [x] `Prophet`
- [x] `predict_var`
    - [ ] `ARIMA`,  `AutoARIMA` (inherit from same intermediate adaptor class)
    - [ ] `AutoETS`
    - [ ] BATS/TBATS
    - [ ] `ThetaForecaster`
    - [ ] `Prophet`
- [x] `predict_proba` 
    - [ ] `ARIMA`,  `AutoARIMA` (inherit from same intermediate adaptor class)
    - [ ] `AutoETS`
    - [ ] BATS/TBATS
    - [ ] `ThetaForecaster`
    - [ ] `Prophet`
 
Capstone activities:
- [x] refactor capstone
    - [x] `predict_interval` and `predict_quantiles`
    - [x] `predict_var`
    - [x] `predict_proba` 
- [x] deprecation complete

**Comment by kejsitake** [comment]
According to my initial checks the forecastors that should have probabilistic capabilities and still need to be refactored are:

- [ ] ARIMA
- [ ] AutoARIMA
- [ ] AutoETS
- [ ] BATS
- [ ] TBATS
- [ ] Theta - I am working on refactoring predict_quantiles and predict_intervals here https://github.com/alan-turing-institute/sktime/pull/1579

**Comment by kejsitake** [comment]
Hi! I am working on the other forecasters, starting with ARIMA. I am not very sure about the `predict_in_sample` and `predict_fixed_cutoff` functions, which currently return pred_int. Given that we are trying to separate the quantile/interval functionality from the predict functions, do we want to have a separate one for quantiles i.e. `predict_in_sample_quantiles` and `predict_fixed_cutoff_quantiles` or do we want to introduce a new variable in predict_quantiles that determines if we want in_sample predictions or not?

**Comment by fkiraly** [comment]
@kejsitake, I just tried to prepare the refactor capstone (for deprecation).
It would look like we forgot `Prophet`!

**Comment by fkiraly** [comment]
From our discussion on slack: @kejsitake has tentatively taken `Prophet` on for refactoring.

**Comment by fkiraly** [comment]
All done:
* framework functionality and default for `predict_proba` and `predict_var` was added in https://github.com/alan-turing-institute/sktime/pull/2100
* defaults were added in https://github.com/alan-turing-institute/sktime/pull/1879
* deprecation of `return_pred_int` is done in preparation for 0.11.0, #2271
