### ISSUE TITLE
[ENH] NaiveForecaster to be able to forecast by copy&paste from previous season(s)/values

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#1688]
**Is your feature request related to a problem? Please describe.**
There is a simple naive forecasting possible by means of just copying values from the most recent season(s). Example for shampoo data can look as follows:
```python
y = load_shampoo_sales()
y_train, y_test = temporal_train_test_split(y, test_size=12)
y_pred = y_train[-12:]
y_pred.index = y_test.index
plot_series(y_train, y_pred, y_test, labels=["y_train", "y_pred", "y_test"])
```
![image](https://user-images.githubusercontent.com/29627036/144651953-c62969b9-f498-4ea9-a4f1-fe2aaa989b8e.png)

Together with a `Detrender`, this might be a powerful naive forecast.

**Describe the solution you'd like**
It would be important to take the first n points of the last season(s) for a forecast of n points. So it will not be just copying the last n points and take them as predictions. In above pic, if we would forecast only 4 steps, then we would take `y_pred = y_train[-12:-8]
` instead `y_pred = y_train[-4:]`. Maybe we can also do both approaches an have a param for it to distinguish between them.

**Comment by mloning** [comment]
I may not fully understand what you have in mind, but last seasonal forecasts are already possible: 

```python
from sktime.forecasting.naive import NaiveForecaster
from sktime.datasets import load_shampoo_sales
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.base import ForecastingHorizon
from sktime.utils.plotting import plot_series

y = load_shampoo_sales()
y_train, y_test = temporal_train_test_split(y, test_size=12)
fh = ForecastingHorizon(y_test.index, is_relative=False)

forecaster = NaiveForecaster(strategy="last", sp=12)
forecaster.fit(y_train, fh=fh)
y_pred = forecaster.predict()

plot_series(y_train, y_test, y_pred)
```

![image](https://user-images.githubusercontent.com/21020482/144658718-38745bcf-7c4e-495e-89e3-8584b7f49663.png)

**Comment by aiwalter** [comment]
ah nice, thx for clarification @mloning !
I was not aware that `last` in combination with `sp` is already doing this. Should have looked better into it probably. I think just taking the last 4 points to forecast the next 4 points will then work when I set `sp=4`, right. So even if there is basically no seasonality known or identified, I would just set `sp=4`, right?

**Comment by aiwalter** [comment]
let me close it then :) happy that this is already working
