### ISSUE TITLE
Documentation needs to be fixed 

### ISSUE THREAD

**Issue by Kludex** [alan-turing-institute/sktime#169]
Single comment line on `sktime.utils.validation.forecasting` needs to be fixed. Check the image below.

Instead of `<<<<<<< HEAD:sktime/utils/validation/forecasting.py` we should see `Returns`.
 
![image](https://user-images.githubusercontent.com/7353520/66719148-2c0d0580-edc2-11e9-9a10-8632c1d896e4.png)

**Comment by mloning** [comment]
Fixed by #170
