### ISSUE TITLE
[BUG] CanonicalIntervalForest breaks with CIT tree

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#1690]
**Describe the bug**
When running the below code snippet, I get: 

> `AttributeError: '_TreeNode' object has no attribute '_predict_proba_cif'`

**To Reproduce**
```python
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

from sktime.classification.compose import ColumnEnsembleClassifier
from sktime.classification.interval_based import CanonicalIntervalForest
from sktime.datasets import load_basic_motions
from sktime.transformations.panel.compose import ColumnConcatenator

X, y = load_basic_motions(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

steps = [
    ("concatenate", ColumnConcatenator()),
    ("classify", CanonicalIntervalForest(n_estimators=100, base_estimator="CIT")),
]
clf = Pipeline(steps)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)```
```

**Additional context**
There's a [question on TSF on StackOverflow](https://stackoverflow.com/questions/70212188/how-to-know-from-which-interval-of-the-input-the-features-used-in-sktimes-times) in which I wanted to show CIF as an alternative but got the above error.

**Comment by TonyBagnall** [comment]
I'm not sure why you would want to do that though, CIF can handle multivariate data afaik

**Comment by TonyBagnall** [comment]
also, the ColumnEnsembleClassifier does not conform to the new model and so it might be that breaking it

**Comment by MatthewMiddlehurst** [comment]
Thanks, Markus. I also noticed this in a branch I have speeding up the classifier, but can make a separate one to fix this. Must have been introduced during the refactor.

We used to test both classifiers, but I think we removed the CIT one when we banished it to contrib as it was extremely slow. When I make my speed-up PR this should no longer be an issue.

**Comment by mloning** [comment]
@TonyBagnall It's just the example from the StackOverflow answer, I just replaced the estimator.
