### ISSUE TITLE
[BUG] transformer multi-column pd.DataFrame output conversion fails

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#1697]
**Describe the bug**
It seem like series-to-series transformers cannot return multiple columns when passing a pd.Series as input. 

**To Reproduce**
```python
from sktime.transformations.base import BaseTransformer
import numpy as np
import pandas as pd

class MyTransformer(BaseTransformer):
    _tags = {
        "scitype:transform-input": "Series",
        "scitype:transform-output": "Series",
        "scitype:transform-labels": "None",
        "scitype:instancewise": True,
        "univariate-only": False,
        "handles-missing-data": True,
        "X_inner_mtype": "pd.DataFrame",
        "y_inner_mtype": "None",
        "X-y-must-have-same-index": True,
        "enforce_index_type": None,
        "fit-in-transform": False,
        "transform-returns-same-time-index": True,
        "skip-inverse-transform": True,
    }

    def _fit(self, X, y=None):
        return self
    
    def _transform(self, X, y=None):
        return pd.concat([X, X], axis=1)
    
transformer = MyTransformer()
transformer.fit_transform(pd.DataFrame(np.random.normal(size=(10,)))) # works
transformer.fit_transform(pd.Series(np.random.normal(size=(10,))))  # fails
```
> ValueError: input must be univariate pd.DataFrame, with one column

**Additional context**
This is relevant for "featurizers" as in #1693.

**Version**
main at commit 8ca23bd85e60d

**Comment by fkiraly** [comment]
yes, I noticed that too when thinking about #1677.

I was wondering what the behaviour should be in that case. `pd.DataFrame` by default? Seems easiest.

**Comment by fkiraly** [comment]
@mloning, also wondering how to properly test this.
I have been thinking about a more comprehensive suite of transformers tests than we currently have. We need to cover cases like this, and then check inputs/outputs. A tag that indicates whether the number of variables might change (e.g., grow), or what it is, might help.
