### ISSUE TITLE
[ENH] Make BaseClassifier abstract with ABC

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1708]
**Is your feature request related to a problem? Please describe.**

both _fit and _predict should be properly abstract using ABC, rather than just raising an error. 

This cannot be done until all classifiers conform to _fit/fit model. This is linked here

- #1609
- #1608
- #1607
- #1606

this is complicated by the fact that it seems TimeSeriesForestClassifier is used in annotation, benchmarking, forecasting, series_as_features, transformations and utils.

**Comment by fkiraly** [comment]
indeed - I think there is a more general question about use of abc throughout sktime.
I'm in favour, although as you correctly identify, various refactors need to be completed first.

May I change this to "use abc for sktime base classes" in general?

**Comment by TonyBagnall** [comment]
Yes please do, ABC is already used in series as features and clustering, so we may as well encourage its usage everywhere I think

**Comment by lmmentel** [comment]
It seems, that all the blocking issues are solve. I can take  a look at this, but would need some more information to understand the  requirements. Any help would be appreciated @TonyBagnall @fkiraly :slightly_smiling_face:

**Comment by fkiraly** [comment]
well - I there is a more serious design issue in the background.

We need to work out how we would be using `abc`, which classes inherit from it.
I would be very reluctant to do this only for classifiers, since we must avoid pattern divergence between the modules, in my opinion.

I've opened an issue here: https://github.com/alan-turing-institute/sktime/issues/1923

**Comment by TonyBagnall** [comment]
I'll close this for now since there is not agreement on if its a good idea or not, please don't reopen unless you want it done
