### ISSUE TITLE
DatasetHDD from DataFrame Pandas

### ISSUE THREAD

**Issue by Kludex** [alan-turing-institute/sktime#171]
**Problem**
I was working with the [Orchestrator module](https://alan-turing-institute.github.io/sktime/autogen/sktime.experiments.orchestrator.html) and I've noticed that the method `run()` needs list of datasets that has the `load()` method implemented. As you can see in the snippet below:

```    
def run(self, predict_on_runtime=True, save_strategies=True):
        """
        Method for running the orchestrator
        
        Parameters
        ----------
        predict_on_runtime : bool, optional (default=True)
            If True makes predictions after the estimator is trained
        save_strategies : bool, optional (default=True)
            If True saves the trained strategies on the disk
        """

        for task, data in zip(self._tasks, self._datasets):
            dts_loaded = data.load()
```
But on the documentation we assume that is a list of `DataFrame` pandas. Which doesn't have the `load()` method ([DataFrame documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)). What is being used is a `DatasetHDD` list.

![image](https://user-images.githubusercontent.com/7353520/66721744-07be2280-eddc-11e9-95f8-71ee3d07736e.png)
Minor issue: typo on `skitme`->`sktime`.

**Solution**
**1. Easiest Solution**
Change the documentation. 
`datasets (pandas dataframe) – datasets in pandas skitme format` -> `datasets (list of DatasetHDD) – datasets in DatasetHDD format`

**2. Accept a DataFrame pandas as parameter to create a DatasetHDD**

**3. Create a method that converts DataFrame pandas to DatasetHDD**

**4. Create a .ts file from DataFrame pandas**
I haven't found this option on the code base. I mean, even if this exists, it should be easily to find on the documentation, we should have an update on the [loading data tutorial](https://alan-turing-institute.github.io/sktime/examples/loading_data.html) if that's the case. If we don't have a `create_tsfile_from_dataframe()`, this can solve the problem creating the tsfile and using it as parameter to the `DatasetHDD`. 

**5. DatasetRAM should be analogous to DatasetHDD**
The `load()` method on both classes are different. `DatasetHDD` splits the dataset, though the `DatasetRAM` doesn't. Maybe we could create a `Dataset` class and make that the parent class for both `DatasetRAM` and `DatasetHDD`.

What do you guys think? If I said something that is not right, please, let me know.

**Comment by mloning** [comment]
Thanks for raising the issue! We've been working on updating the benchmarking module, please take a look at the [`dev`](https://github.com/alan-turing-institute/sktime/tree/dev/sktime/benchmarking) branch. We're planning on pushing these updates to the master branch and making a new release some time soon. 

The `run` method should definitively accept datasets rather than pandas data frames. I'm sure the documentation isn't great on `dev` either. If you're interested in contributing, take a look at issue #141 where we've collected a number of to-dos and open design questions.

**Comment by Kludex** [comment]
Oh, thank you! I'll start using the `dev` branch. 
I'm interested. I'll check.

**Comment by mloning** [comment]
Let's the continue discussion in #141!
