### ISSUE TITLE
[ENH] design - what should the output be of series transformers applied to multivariate series?

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1719]
Consider the situation where we apply a transformer of univariate series to primitives or series.

When applied to multivariate series, i.e., to each variable individually, what should the output be?

Some options:
* should raise error
* a panel, e.g., multi-index level introduced by variable, rows
* a panel, e.g., multi-index level introduced by variable, columns

There other aspect of this question is whether vectorization over variables should occur automatically or not.
For instance:

* should be left to individual transformers
* should happen automatically through the base class

This arises from #1663, which is a series-to-primitives transformer which was noted by @MatthewMiddlehurst to have counterintuitive behaviour when faced with multivariate series (the behaviour was implemented by @RNKuhns ).

**Comment by MatthewMiddlehurst** [comment]
I don't remember implementing anything to do with the transformer refactor or suggesting any changes to how to deal with multivariate Panel data for Series transformers during the process. If you could point me to where I am involved in this process other than the recent comment, that would be great.

The only thing I can think of is the original SummaryTransformer PR (#1329), where I proposed that additional dimensions be added on as columns? I still agree with this (for my usage at least, maybe there is a better general format).

Currently, when I try to use the SummaryTransformer as the transformer in a pipeline (part of #1063), the multivariate panel data with 40 rows and 6 dimensions is transformed into 240 rows. I struggle to think of a case where I would want this using panel data. Would be best to either add a 3rd dimension to the output, or just add them on as additional columns.

From main:
```
from sktime.datasets import load_basic_motions
from sktime.transformations.series.summarize import SummaryTransformer

if __name__ == "__main__":
    X_train, y_train = load_basic_motions(split="train", return_X_y=True)
    print(X_train.shape)
>>> (40, 6)
    st = SummaryTransformer()
    print(st.fit_transform(X_train).shape)
>>> (240, 9)
```

I don't believe I am doing anything strange here. The input is a pandas DataFrame, but the output is the same with a numpy 3d array also. SummaryTransformer only takes Series datatypes I believe, so this is all happening in the base class automated transformations?

**Comment by fkiraly** [comment]
> I don't remember implementing anything to do with the transformer refactor or suggesting any changes to how to deal with multivariate Panel data for Series transformers during the process. If you could point me to where I am involved in this process other than the recent comment, that would be great.

Sorry, I got confused. @RNKuhns implemented the summary transformer, but you were last to review, and I remembered the discussion with you on that, which in memory got distorted into you implementing it.

**Comment by fkiraly** [comment]
Regarding the discussion: I think we are not consistent in what we think 2D numpy data means.
By default, it is implemented as a multivariate series, i.e., 1 instance, 40 time points, 6 variables.
You seem to refer to it as panel data, i.e., 6 instances, 40 time points, 1 variable.

Obviously, both cannot be correct at the same time.
The automated type recognition thinks it is a multivariate series, and I think in general that makes most sense to assume if you are seeing a 2D numpy array and no further information.

What happens in the transform is that the rows corresponds to a produce of the variable index and the time index.

**Comment by MatthewMiddlehurst** [comment]
All good.

I'm a bit confused. Are we are talking about the output type here? I'm assuming the process is a bit like this: The base class splits up the input Panel data, feeds it into the Series transformer one series at the time, which then outputs a 2d numpy array (or 1d if univariate) for each series. If that's the case, it is all fine and is the expected output.

When it comes to putting those 2d arrays back together for the primitive output, we could probably format it a bit better.

If we are talking input from the above example, the shape is 40 instances, 6 dimensions, 100 time points. The DataFrame format does not give the amount of time points using .shape annoyingly. The output shape is instances*dimensions, with 9 columns for the default summary stats.

**Comment by fkiraly** [comment]
>I'm a bit confused. Are we are talking about the output type here?

Well, format primarily. The output probably has to be `pd.DataFrame`, which is fundamentally a 2D container.

>I'm assuming the process is a bit like this

Yes - each univariate series produces a 1D array/container of length 9. This is stored in a one-row `pd.DataFrame` by convention.

If there are multiple series, you have as many of these as there were series. So, in the example, when you have 40 instances of univariate series, you (should) get a 2D arrays of shape (40, 9).

The question is what should happen if you have multiple variables (in the example 6). Then you can compute the summaries per variable and per instance.

I can think of two natural ways:
* multi-index over columns, this gives a (40, 54) in the example, with a column multi-index of two levels (feature and variable)
* multi-index over rows, this gives a (240, 9) in the example, with a row multi-index of two levels (instance and variable)

Note that since (or as long as) the output container is `pd.DataFrame`, the resulting structure must be 2D - but we can have multi-indices.

**Comment by MatthewMiddlehurst** [comment]
If the output type is primitives, I think it is more natural for it to multi-index over columns.

When the output from the transformer is a series, however, neither are great really. If I had to choose, probably multi-index over rows, as things could get strange if the series are unequal length and you start just appending them onto each other.

Do we want to avoid nested DataFrames for the above case? 

Would be good to hear what others think.

**Comment by fkiraly** [comment]
So, @MatthewMiddlehurst, you think it should be *column* multiindex, given the merged PR #1869 of yours?

**Comment by MatthewMiddlehurst** [comment]
For cases where the output is not a series, yes.

**Comment by fkiraly** [comment]
ok, agreed & decided then!

Turned this into todo items here: https://github.com/alan-turing-institute/sktime/issues/2717
