### ISSUE TITLE
[BUG] Forecasting horizon in EnsembleForecaster fit and predict

### ISSUE THREAD

**Issue by prockenschaub** [alan-turing-institute/sktime#172]
**Describe the bug**
Closely related to #126, but the fix in `BaseForecaster` has not carried over to `EnsembleForecaster` as it overrides the fit and predict methods.

**To Reproduce**
```python
import pandas as pd
from sktime.forecasters import EnsembleForecaster
from sktime.forecasters import ExpSmoothingForecaster
from sktime.datasets import load_shampoo_sales

shampoo = load_shampoo_sales()
train = pd.Series([shampoo.iloc[0].iloc[:30]])

estimators = [
    ('ses', ExpSmoothingForecaster()),
    ('holt', ExpSmoothingForecaster(trend='additive'))
]
m = EnsembleForecaster(estimators=estimators)

# Error in fit
m.fit(train)

# Error in predict
m.fit(train, fh = 1)
m.predict(train)
```

**Expected behavior**
Have default forecasting horizon in line with `BaseForecaster`

**Versions**
<details>

Windows-10-10.0.17763-SP0
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
NumPy 1.17.2
SciPy 1.3.1
sktime 0.3.0

</details>

**Comment by mloning** [comment]
Fixed by #177
