### ISSUE TITLE
[BUG] series-to-series transformer no longer work with `ForecastingPipeline`

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1731]
I think the transformers refactor introduced a bug:
in series-to-series transformers, the order of arguments was not changed, but the names were.
So args calls are fine since downwards compatible, but kwargs calls may break.

One reference in the `ForecastingPipeline` was kwargs, which makes pipelines with any transformers that are not yet refactored break.

PR #1730 fixes the issue, by replacing the kwargs reference with an args reference.

I've also searched the repository, there are no other kwargs references to the sub-set of transformers that had `Z` previously as the first argument.

**Comment by fkiraly** [comment]
(slightly unhappy that I discovered this only a few hours after the release - but perhaps we can send a patch version on its way once this is confirmed/fixed)

**Comment by aiwalter** [comment]
I think its not a bug since you fixed it in `fit_transform` before already?

**Comment by fkiraly** [comment]
yes, and the tests don't complain. So this is probably just an imagined bug.

I've added more test cases in https://github.com/alan-turing-institute/sktime/pull/1732, let's see what that says.

**Comment by fkiraly** [comment]
This is not actually a bug, it was imagined upon code inspection. See discussion in #1732.
