### ISSUE TITLE
[BUG] mismatch in classification datasets

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1735]
some of ts files the classification datasets in datasets module have old style headers. These need updating, a list made of which ones are shipped and a test function written to check the format

**Comment by fkiraly** [comment]
can you kindly be a bit more explicit what closed this?

**Comment by TonyBagnall** [comment]
this has been fixed

**Comment by fkiraly** [comment]
downstream, in timeseriesclassification.com, I presume?
