### ISSUE TITLE
[ENH] address FutureWarning: Timestamp.freq is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1750]
It would be great if someone could address the repeated
`FutureWarning: Timestamp.freq is deprecated and will be removed in a future version`
that is caused by various places all over the codebase.

The most prominent source seems to be `utils/datetime`

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is there a new functionality that replaces that of `Timestamp.freq`?

**Comment by fkiraly** [comment]
I don't quite know - but perhaps you can find out?
I think the full message (printed when running the test suite) has suggestions what to do, but I don't have it in front of me right now.

I'd suggest, just run the test suite and check the full deprecation message.
There are also others that may be easy to fix, like the `np.float` deprecation.

**Comment by fkiraly** [comment]
(it's yours now)

**Comment by khrapovs** [comment]
Reading the pandas PR where `freq` was deprecated I now understand better why it was done. The bad news is that there is no trivial alternative to get this `freq` thing. Since a single timstamp does not have a well defined inherent frequency in it, perhaps it would be better to work exclusively with `pd.Period` objects, where frequency is totally native.

**Comment by fkiraly** [comment]
hm, could we make a converesion internally in the `ForecastingHorizon`?

**Comment by fkiraly** [comment]
unassigning @Carlosbogo, since he abandoned it.

Assigning @khrapovs who said he would take it on in duplicate #2617.

**Comment by fkiraly** [comment]
@khrapovs, thanks a lot for your hard and excellent work on the `freq` issue! This is truly a very fiddly and unpleasant problem.

I have been somewhat confused, I have to admit, as you may see from some replies, and have now tried to make an effort to understand things better.

Let me first try to summarize what I've understood is at the root of the problem, so you can check my understanding:

* `pandas` is going to deprecate `Timestamp.freq`. No such deprecation will happen in `Period` or `pd.Index` children that have a `freq` attribute.
* `BaseForecaster.cutoff` and `ForecastingHorizon` rely on `Timestamp.freq`. A key location is when `cutoff` is being passed, especially in `to_absolute`, to infer the shifts.

Is this correct?

If so, I might have a solution: changing the `cutoff` to `Index`, which still carries `freq`.
In a first step, we can change the private `_cutoff`, in a second step, we can deprecate `cutoff` being an index element and change it to a length-1 index as well.

The idea is, `pd.Index` descendants will still carry `freq`, even if elements are `Timestamp`. The rest should hence still work, right?
We may like to be careful with sub-setting though, since `pd.index` loses `freq` if subsetting to something that is too short, i.e., length 1 or 2.

**Comment by khrapovs** [comment]
> Is this correct?

Yes. This is more or less what I was trying to say in my enhancement proposal and in this PR description. Sorry, if it was not very clear.

> If so, I might have a solution: changing the `cutoff` to `Index`, which still carries `freq`. In a first step, we can change the private `_cutoff`, in a second step, we can deprecate `cutoff` being an index element and change it to a length-1 index as well.

As a user I am not sure I like this proposal. In exchange of passing a simple string like "D" or "10T" as a `freq` argument in a very corner case of `pd.Timestamp` (in all other cases default `freq=None` is perfectly fine), you are offering me to be very careful not to pass `y.index[-1]` directly as `cutoff` argument, but go through an additional step of converting it to an index and making sure along the way that it still has the frequency embedded. Sorry, the second option looks quite complicated. Did I get it wrong?

**Comment by fkiraly** [comment]
Here is the proposal as part of the STEP:
https://github.com/sktime/enhancement-proposals/pull/24

> Sorry, the second option looks quite complicated. Did I get it wrong?

Maybe - I think `ForecastingHorizon` should still be extended to allow `freq` pass.

But, I would like to:
* keep current usage where that arg is not required in many cases
* change internal/private usage so the interfaces do not proliferate arguments, I think that is best achieved with an `pd.Index` typed version of the various utilities.

**Comment by fkiraly** [comment]
> Sorry, if it was not very clear.

No, it was clear - I just didn't understand it properly first time round.

**Comment by khrapovs** [comment]
> Here is the proposal as part of the STEP: [sktime/enhancement-proposals#24](https://github.com/sktime/enhancement-proposals/pull/24)

@fkiraly May I kindly remind you your own words: https://github.com/alan-turing-institute/sktime/pull/2694#issuecomment-1146769665. I have spent quite some time on this PR...

**Comment by fkiraly** [comment]
> @fkiraly May I kindly remind you your own words: https://github.com/alan-turing-institute/sktime/pull/2694#issuecomment-1146769665. I have spent quite some time on this PR...

Still my preference! I just don't want anything to happen to our public interfaces, or anything major to `BaseForecaster` logic. Hence my modified suggestion. We can probably mix the two approaces.

**Comment by fkiraly** [comment]
I'm removing the "good first issue" label, since (as we have learnt) the deprecation is so horriffically intertwined with `sktime` core interfaces relying on that `freq` attribute that it requires experienced core devs.
