### ISSUE TITLE
[BUG] Invalid FutureWarning for load_from_tsfile_to_dataframe? 

### ISSUE THREAD

**Issue by ltsaprounis** [alan-turing-institute/sktime#1762]
**Describe the bug**

`sktime.utils.data_io.load_from_tsfile_to_dataframe` throws a `FutureWarning` that it has been moved to `sktime.datasets._data_io` and will be deprecated in version 0.10. However it looks like it's not moved there and instead it's imported and is a dependency for a few other functions.

**To Reproduce**

```python
from sktime.utils.data_io import load_from_tsfile_to_dataframe
df = load_from_tsfile_to_dataframe("dummy_path")
```

**Comment by ltsaprounis** [comment]
Looks like @TonyBagnall is one step ahead with #1757

**Comment by TonyBagnall** [comment]
yep it is a work in progress :) I just misworded the warning, my bad. Coming soon I hope, had a couple of complications/threw up some other issues
