### ISSUE TITLE
[ENH] Centralise correctness testing for classification

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1765]
all the classifiers run correctness sanity tests using predict and predict_proba for the UnitTest problem as a check against changes introducing logical errors to the algorithms. This is currently done with replicated code in each sub package. It would be good to centralise this in a single place and remove duplicate code. Several stages to this

1. Regenerating correct outputs. Sometimes algorithms will change in an approved way, and output may change. Code to generate new correct output is currently commented out. Stage 1 of this issue will be to strip out commented code and dump it in contrib for noew
2. What tests to perform? We can review existing and decide on how best to test any classifier
3. How to do a generic test and where to put it and the correct results? this will basically integrate (1) and (2) above

**Comment by fkiraly** [comment]
Addressed by the new classification testing framework in https://github.com/alan-turing-institute/sktime/pull/2257, "correctness" moved to issue https://github.com/alan-turing-institute/sktime/issues/2255.
