### ISSUE TITLE
[ENH] `_set_fh` with side effects should be replaced by `_check_fh` with return

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1776]
[let's first have an API discussion before implementing/changing anything]

Currently, our input check interfaces are not consistent in forecasting.

We have `X, y = _check_X_y(X, y)`, `X = _check_X(X)`, `alpha = check_alpha(alpha)`, but for the forecasting horizon we have `_set_fh(fh)` (this returns nothing) and then the user needs to retrieve a potentially changed `fh` from `self.fh` to which `_set_fh` writes.

This is inconsistent and counterintuitive in my opinion, I think the bug addressed in #1775 shows this - @SveaMeyer13 and @kejsitake didn't know and also didn't guess that the above was how `_set_fh` had to be used.
I don't think this is at all their fault, the problem is the inconsistency in the input check and conversion, where `_set_fh` breaks what is otherwise an obvious pattern.

So I think this should be changed to `fh = _check_fh(fh)`, notationally, without changing any logic.
More explicitly, the line `fh = _check_fh(fh)` should replace the line `_set_fh(fh)` and then repeated subsequent uses of `self.fh` in places where `fh` seems more natural.
(it would also not affect users, only developers, since the logic doesn't change)

Any thoughts? @aiwalter, @mloning, @SveaMeyer13, @kejsitake, @eenticott-shell?

**Comment by kejsitake** [comment]
I agree that this is counterintuitive and _check_fh makes more sense.
