### ISSUE TITLE
[ENH] classification/clustering data loading restructuring

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#1778]
I'm rejigging that data input output for classifiers and will do it in several stages
1. Done
2. Add a new data loader that returns 2D numpy for equal length univariate, 3D numpy for  equal length multivariate, DataFrame for any unequal length problems
https://github.com/alan-turing-institute/sktime/issues/1718
3. Add writers that can write 2d/3d numpy and pandas
https://github.com/alan-turing-institute/sktime/issues/1753
https://github.com/alan-turing-institute/sktime/issues/1756
4. Done
5. Adjust the web downloader to put in a different download location, then gitignore that
6. Adjust all the single problem loaders to use the new loader, fix any resulting notebook issues where pandas are expected, move all the single loaders into a separate file. Possibly also split input/output into different files 
7. Provide a general purpose loader than can handle .ts, .csv, .arff and .txt
8. Update the notebook to demonstrate new usage
  

Done
1. Clone functions currently in utils/data_io.py into datasets/_data_io.py 
https://github.com/alan-turing-institute/sktime/pull/1777
4. Add univariate unequal length dataset (AsbestosObstacles) [actually just used PLAID which is already there], sort out multivariate unequal length to remove nan padding, sort out other data formatting.

**Comment by fkiraly** [comment]
Added a descriptive title.

Re. point 2 and 3, some random thoughts. This could be most easily achieved by:
* having logic that loads to a very general format, e.g., `pd-multiindex`
* having an `mtype` argument in the loader, which determines the output format
* using `convert` at the end of the loader, from the very general format, instead of writing seven or so loaders or pieces of logic

**Comment by TonyBagnall** [comment]
@fkiraly so for the .ts format, the idea is to read the data type from the file header, removing the need to explicitly check or convert. We are starting to look at larger problems (EEG are often 10-100 GB), so we need to minimize unnecessary checking. If the file does not match the header (e.g. unequal length data registered as equal in header) it will throw an exception. For other formats, the idea is to load into dataframe as we always have done, then use check and convert it get it into the best format.
