### ISSUE TITLE
[ENH] Dimension or channel selection in Multivariate Time Series Classification

### ISSUE THREAD

**Issue by haskarb** [alan-turing-institute/sktime#1782]
**Is your feature request related to a problem? Please describe.**
Not all the dimensions are useful in MTSC. The problem is to identify the useful dimensions, and perform classification with them, rather than using all the dimensions.   

**Describe the solution you'd like**
A solution was proposed in the [paper](https://www.researchgate.net/publication/354445008_Fast_Channel_Selection_for_Scalable_Multivariate_Time_Series_Classification) based on distance class-centroid distance.

**Comment by TonyBagnall** [comment]
hi @haskarb, I agree and we would love a contribution that provides this functionality

**Comment by haskarb** [comment]
Thanks, Tony, Will work on making a contribution in the next few days.

**Comment by TonyBagnall** [comment]
This functionality is now available in transformations, https://github.com/alan-turing-institute/sktime/pull/3248/files
