### ISSUE TITLE
StatsModels and Numpy to have a >= version instead of == version

### ISSUE THREAD

**Issue by AlexPars** [alan-turing-institute/sktime#1787]
Would it be possible to use StatsModels >= 0.12.1 and Numpy >= 1.19.3 instead of StatsModels == 0.12.1 and Numpy == 1.19.3?

Currently the file main/setup.py uses the same version for StatsModels  and Numpy  in min and max requirements

**Comment by lmmentel** [comment]
FYI there is currently a refactor of how dependencies are specified in #1620 and the deps will go into `pyproject.toml` file. 

Is there any specific reason the later requirements would be favorable? (bugfixes, performance improvements etc)?

**Comment by AlexPars** [comment]
thank you for the initiative to use pyproject.toml 

My inquiry is rather about ability to use sktime in conjunction with other Python packages

I am using poetry to manage dependencies of multiple packages, and I am not able to install sktime if I want to use other packages which rely on StatsModels > 0.12.1 and on Numpy > 1.19.3

**Comment by lmmentel** [comment]
That makes sense, thanks for clarifying. Could you reveal what version of python are you using and what other packages are you trying to use that have conflicting dependencies?

**Comment by AlexPars** [comment]
Python 3.9.9.

 I have a collection of about 50 python packages, and I am getting some inconsistencies with a few of them (according to poetry output)

**Comment by AlexPars** [comment]
One clarification: I have a collection of about 50 explicit Python packages for this particular project on time series (analysis, forecasting, classification, clustering and network analysis)

I would like to compare various algorithms implemented in Python and R packages. I consider sktime to be one of the great time series packages in Python

**Comment by TonyBagnall** [comment]
hi, I cant comment on statsmodels, but the problem with numpy >1.19.3 is that it does not work with pandas 1.15. Why used pandas 1.15, given it is seven years old? Because it is the only version that works python 3.6, and our CI tests with 3.6 to 3.9. So until we ditch 3.6 (I think we should but apparently a lot of people still use it). I forget the exact details, numba was involved somewhere to!

**Comment by TonyBagnall** [comment]
https://github.com/alan-turing-institute/sktime/issues/1642
https://github.com/alan-turing-institute/sktime/issues/1645

**Comment by AlexPars** [comment]
Thank you for clarifications. Indeed, it is challenging to have it working under Python 3.6-3.9. While there are approaches to deal with these challenges (such that package dependencies would be specified separately for each major Python version: 3.7, 3.8, 3.9), this would introduce additional workload for sktime team  (definitely not a desired outcome from my perspective)

regarding Python 3.6, a good argument for ditching it that its official lifespan (in terms of support) is only until December 2021 (this month, likely on Dec 23)
https://www.python.org/dev/peps/pep-0494/
https://azure.microsoft.com/en-us/updates/community-support-for-python-36-is-ending-on-23-december-2021/

**Comment by TonyBagnall** [comment]
Thanks for the info, I'm personally hopeless at all the CI stuff, not my domain, I don't have the patience. But I'll definitely raise it again with core Devs in the new year.

**Comment by fkiraly** [comment]
Yes, I think we were discussing to cease support for 3.6 in 0.11.0 - that's the earliest version number since we need a full version cycle (0.10.0) to have people read the deprecation message. Which means, around spring 2022 we can also remove pins or bounds that come from 3.6.

**Comment by baggiponte** [comment]
Hi, back on the `pandas` issue.

* Does this mean we cannot relax the requirement to `pandas>=1.1.5`?
* When you install packages with `pip install -r requirements.txt` it goes in the order they appear: if we specified `pandas` before other packages, could we relax the constraints?

**Comment by fkiraly** [comment]
@baggiponte, I thought once we drop python 3.6 support, all should be fine?
