### ISSUE TITLE
[BUG] Conversion of univariate series to Sktime format for shapelet  discovery

### ISSUE THREAD

**Issue by aron-alarik** [alan-turing-institute/sktime#1791]
**Describe the bug**

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

Hi I am trying to use shapelet transforms with SkTime, I have a univariate series in a pandas format as in the screen shot, trying to convert it to Sktime format as per the documentation, keep getting errors, tried adding default columns such as caseID etc but got an error : duplicate entries, any help on how to convert this to SkTime format. Stuck on this for several days now. 
![Screenshot 2021-12-22 025042](https://user-images.githubusercontent.com/86116123/147039091-af6a0b95-6934-4249-98b8-cfad4a434b8f.png)
![Screenshot 2021-12-22 025126](https://user-images.githubusercontent.com/86116123/147039095-78580bbe-1862-47ec-a326-fa2bea74254b.png)
Thanks!

**Comment by TonyBagnall** [comment]
hi, this looks like a problem with from_long_to_nested rather than shapelets?

**Comment by aron-alarik** [comment]
> hi, this looks like a problem with from_long_to_nested rather than shapelets?

Yes that is correct, this is the same issue while converting data for  some of the other transformers, little guidance or help on the input data format will help open up this entire awesome library for us. Also what is the kind of input you are expecting for shapelets? a pre-discovered set of data with time and location or will a single time series sensor data will do? Thanks !

**Comment by MatthewMiddlehurst** [comment]
Shapelets require multiple series and class labels. I'm not really sure about the long format or do I know anyone else who is, but the easiest format is probably a 3d numpy array of shape (n_series, n_dimensions, series_length) if your series are equal length. Since your series is univariate, n_dimensions would just be 1. The labels can just be a 1d numpy array.

**Comment by aron-alarik** [comment]
thanks ! let me try with this configuration

**Comment by MatthewMiddlehurst** [comment]
I don't think this needs to be an open issue any more? I will give it a bit to see if there is any response/concerns still.
