### ISSUE TITLE
[MNT] conda-forge release 0.9.0

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1797]
0.9.0 hasn't been released on `conda-forge`, this still needs to be done.

@freddyaboulton, did you handle the last release on `conda-forge`, or was that @mloning?

**Comment by freddyaboulton** [comment]
@fkiraly it was @mloning ! Only @mloning and @dhirschfeld are maintainers on the conda package.

**Comment by dhirschfeld** [comment]
I bumped the deps and kicked the CI over in https://github.com/conda-forge/sktime-feedstock/pull/21. We'll see how that goes. Any review appreciated...

**Comment by fkiraly** [comment]
Thanks! Looks like all good?

**Comment by dhirschfeld** [comment]
> Thanks! Looks like all good?

Yep, sorry - forgot to actually hit merge!

**Comment by fkiraly** [comment]
@dhirschfeld, thanks a lot again! Are you on our slack? Might make sense to catch up there next time to coordinate the `pypi` and `conda-forge` releases.

**Comment by dhirschfeld** [comment]
Hi @fkiraly :wave:
I'm not on the `sktime` slack - I'm just a `mamba` user who wanted to play around with `sktime` 😄.

The packaging of the `conda` package is *probably* best done by a core team member but I'm happy to help out as I'm able to... though my time is a bit scarce at the moment.

**Comment by fkiraly** [comment]
>I'm just a `mamba` user who wanted to play around with `sktime`

I hope your playing has been enjoyable and productive...

>The packaging of the `conda` package is probably best done by a core team member 

ok, let's do it this way then: we look at what you did, try to generalize from that, and ask you for help if we get stuck?

**Comment by freddyaboulton** [comment]
@dhirschfeld can you make me (and maybe @lmmentel ) maintainers on the conda package?

**Comment by dhirschfeld** [comment]
> *can you make me (and maybe @lmmentel ) maintainers on the conda package?*

Done! https://github.com/conda-forge/sktime-feedstock/issues/22
