### ISSUE TITLE
[DOC] reference to `pip install -e .[all_extras]` in installation instructions

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1832]
The developer instructions should  make explicit reference to the command `pip install -e .[all_extras]`, for the option "with all extras" of the devlopment version install (similar to the stable version).

The file to edit is `docs/source/installation`.

**Comment by lmmentel** [comment]
I made some updates to the instructions in https://github.com/alan-turing-institute/sktime/pull/1620/files#diff-e285c1b9901cd202e89d9f37e3249a6fee524a65428895e1a45fd062cc0f9aca

**Comment by fkiraly** [comment]
ah, thanks!

So we just need to merge it once the deed is done?

**Comment by lmmentel** [comment]
Should be, but it should pass the review first.
