### ISSUE TITLE
[DOC] update core developers

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1837]
The core developer list `docs/source/about/team` should be updated:

* Ryan Kuhns @RNKuhns has left and is inactive
* Patrick Schäfer @patrickzib has joined core developers

Core developers should also be ordered alphabetically by first name, then last name.

**Comment by sumit-158** [comment]
Can I work on this?

**Comment by patrickzib** [comment]
Sure :) And thank you!
