### ISSUE TITLE
[ENH] rename `fit-in-predict` and `fit-in-transform` to `fit-is-empty`

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1843]
I think we should rename `fit-in-predict` and `fit-in-transform` to `fit-is-empty`.

This has two advantages:
* one tag instead of multiple; no future need to introduce new tags for other estimators such as aligners where there is no `predict` or `transform`, or annotators
* the `fit-is-empty` tag is much clearer and unambiguous in my opinion. Because, what does `fit-in-predict` mean? It could mean, for instance, that `predict` also `fit`-s if `fit` was not called before, it's a statement about `predict`, and not clearly a statement about `fit`.

**Comment by fkiraly** [comment]
Any opinions, @aiwalter, @GuzalBulatova, @TonyBagnall?

**Comment by GuzalBulatova** [comment]
I don't have strong opinion regarding this, to me it does make more sense.
`fit-is-empty` could mean though that this estimator doesn't perform/require fit at all, is it always the case?

**Comment by fkiraly** [comment]
>fit-is-empty could mean though that this estimator doesn't perform/require fit at all, is it always the case?

Currently we require `fit` to be run before `transform` even if `fit` is empty, @mloning was adamant on that.
I understand how it makes sense, since it results in consistent run conditions and behaviour.

The function to call when you want to transform the data in one go is `fit_transform`, that's more python zen with "one and only one way to do things".
