### ISSUE TITLE
[ENH] Add option to set smoothing parameters for ExponentialSmoothing class based models

### ISSUE THREAD

**Issue by ishannangia001** [alan-turing-institute/sktime#1845]
`smoothing_level`, `smoothing_trend`, and `smoothing_seasonal` should be added as parameters to `ExponentialSmoothing` which wraps `statsmodels` exponential smoothing.

In `statsmodels`, these parameters are passed to `fit`, but in `sktime`, they should be passed to `__init__` together with the other hyper-parameters.

Adding other parameters which are arguments to `fit` in `statsmodels` to `__init__` in `sktime` should also be considered.

---

**PROBLEM** 
I have been using the ExponentialSmoothing class recently. Can't seem to find a way to input/set the smoothing_level, smoothing_trend and the smoothing_seasonal parameters. This functionality is provided by statsmodels and imo should be offered by sktime too.  

**Solution**
Add a way to input smoothing_level, smoothing_trend, and smoothing_seasonal parameters for the ExponentialSmoothing models.

**Comment by fkiraly** [comment]
Hm, could you kindly paste a reference to the parameters you mentioned?

I just looked in statsmodels, and here is the list of parameters I could find.
The list does not include `smoothing_level`, `smoothing_trend`, or `smoothing_seasonal`.

```
        endog,
        trend=None,
        damped_trend=False,
        seasonal=None,
        seasonal_periods=None,
        initialization_method=None,  # Future: 'estimated',
        initial_level=None,
        initial_trend=None,
        initial_seasonal=None,
        use_boxcox=None,
        bounds=None,
        dates=None,
        freq=None,
        missing="none",
```

**Comment by ishannangia001** [comment]
They have been mentioned in their tutorial notebook: https://github.com/statsmodels/statsmodels/blob/main/examples/python/exponential_smoothing.py

These three parameters are called while fitting the model and not while initialising it. The below image shows a snippet from the code in the above link.

![image](https://user-images.githubusercontent.com/96042791/148554304-640caa45-3e79-4378-a978-1759f5b6d098.png)

**Comment by fkiraly** [comment]
Ohhhh, it's passed to `fit` and not to the constructor! Thanks!

**Comment by fkiraly** [comment]
We overlooked these, since they were being passed to `fit`. Bit of a questionable design decision on the side of `statsmodels` to pass some parameters in the constructor, and some in `fit`...

Aaaanyway, I've marked this a good first issue, since it should be only a few lines of code to add/change.

**Comment by ishannangia001** [comment]
Agreed. Though I would imagine that the intuition might have been to keep iteratively testing out fits with different smoothing parameters for the same type of models as that might help in deciding the final smoothing parameters through cross-validation, etc.

Great. Thanks a lot ! Will certainly do.

**Comment by fkiraly** [comment]
>Though I would imagine that the intuition might have been to keep iteratively testing out fits with different smoothing parameters for the same type of models as that might help in deciding the final smoothing parameters through cross-validation, etc.

Sure - you can do this using a layer of tuning on top of the model, with `ForecastingGridSearchCV` from `sktime` ... as long as the ETS model exposes the parameters.

**Comment by fkiraly** [comment]
Done here now #1849 - I just went and added all parameters from `fit`.
Would be great if you could check if this is what you want (check out the PR branch and try).

Do you know what else would be great, @ishannangia001?

If you had the time to go through the various `statsmodels` interfaces and check whether we are missing any parameters. A list would already be useful; or, PRs per individual estimator that adds those parameters, given that you have proven that you know how to make a valid pull request :-) (see here #1848). You can take #1849 as a blueprint for changing estimators and get the "code" contribution badge!

**Comment by fkiraly** [comment]
I opened an issue here to collect and address missing `statsmodels` parameters: https://github.com/alan-turing-institute/sktime/issues/1850

**Comment by fkiraly** [comment]
Perhaps, someone should also fix the apostrophe catastrophe in `statsmodels`' docstring.

E.g., someone should go and say "apologie's, its that you're docstrings' apostrophes' misplaced"

**Comment by ishannangia001** [comment]
> 

Can definitely try this out. Will keep working on different statsmodel estimators as and when I get time.

**Comment by fkiraly** [comment]
@ishannangia001, FYI, 0.10.0 is now released which has the smoothing parameters. Enjoy!

**Comment by ishannangia001** [comment]
Thanks so much for this quick update ! Helps tons @fkiraly
