### ISSUE TITLE
[ENH] `statsmodels` interfaces may be missing parameters - investigate and/or add them

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1850]
In issue #1845, an instance of a `statsmodels` interfacing estimator was discovered which was missing crucial parameters.

The reason was that in `statsmodels`, model parameteres are spread out across constructor (`__init__`), `fit`, and potentially other functions.

Due to this, it would be important to look at other `statsmodels` interfaces to check whether we are missing useful parameters from non-constructor methods.

If we are, a notice here would already be useful. Further, these should be added to the constructor (not `fit` etc) of the corresponding `sktime` interface. A "blueprint" PR to carry out this addition of parameters is #1849 (for Holt-Winters smoothing).

**Comment by biologioholic** [comment]
I would like to handle this issue

**Comment by aiwalter** [comment]
@biologioholic its yours

**Comment by biologioholic** [comment]
> 

Thanks

**Comment by fkiraly** [comment]
@biologioholic, great!
Btw, if you're looking into statsmodels, you could also look at interfacing DynamicFactor, if you want, issue here:
https://github.com/alan-turing-institute/sktime/issues/2059

**Comment by fkiraly** [comment]
Ah, just noticed that somebody has already picked that up.

**Comment by fkiraly** [comment]
@biologioholic, sorry to as, I might be confused.
Where exactly is your draft PR? I haven't seen one.

**Comment by biologioholic** [comment]
> @biologioholic, sorry for this, I might be confused. Where exactly is your draft PR? I haven't seen one. Could you kindly post a link?

Sorry for the confusion. I have closed that draft since it only has ETS. This PR includes other model as well. 

https://github.com/biologioholic/sktime/pull/3#issue-1177143455

**Comment by fkiraly** [comment]
Investigated by @biologioholic - with #2304, all currently interfaced statsmodels models have the full parameter set.

Details from #2304, citing @biologioholic there:

There is no more parameters missing for statsmodel interface.  I realize it's been a lengthy first PR. Really appreciate the patience and input of everyone involved (Next time I'll make a draft PR first 😄). Below is a summary of what happened:

Five statsmodel-based files were reviewed/worked on. These are:

1. var.py - added `freq`, `dates` and `ic` parameters. Added default values for other parameters already in place.
2. trend.py - no change, no missing parameters.
3. theta.py - no change, no missing parameters.
4. structural.py - ~~added `approximate_diffuse_variance`~~ This parameter belongs to method `initialize_default` - this is supposed to be a private method and not part of fit or constructor. Thus, no missing parameters.
5. ets.py - ~~added `method`, `skip_hessian`, `approx_centered`, `approxe_complex_step`, `return_raw`~~ - These parameters are part of the super class and not exposed to users. Thus, these are not included. No missing parameters.

In the end, only VAR was missing parameters.
