### ISSUE TITLE
[ENH] Forecasters | Add new tag for support of multiple seasonal periods.

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#1862]
**Describe the solution you'd like**
Would like to add a tag to the forecasters to indicate whether the forecaster can support multiple seasonal periods or not.
Default Value = `False`; set to `True` for forecasters like TBATS.

```python
_tags = {"capability:multiple_sp": False} # does forecaster handle multiple seasonal periods?
```

**Describe alternatives you've considered**
Managing it outside `sktime` in `pycaret`, but that does not seem like a nice solution since tags are already available in `sktime`.

I will be happy to add this to `sktime` if it sounds ok.

**Comment by fkiraly** [comment]
Hm, which forecasters would have `True` for this tag?

Currently, seasonality parameters are not a unified interface element, different forecasters will have different parameters that will indicate seasonal periods. One could, in addition, also consider making them a unified interface element (e.g., have consistent parameter names) if there are more than a small number of cases with that capability.

**Comment by ngupta23** [comment]
Hi @fkiraly TBATS will support multiple seasonal periods.

**Comment by fkiraly** [comment]
Yes, I know that TBATS supports this - but a tag is of limited usefulness if there is only one single example, no?

**Comment by ngupta23** [comment]
That probably makes sense if there is only 1 model, but in general, if we encounter more such features that can be tracked (with more than 1 example), would sktime be a viable place to add these tags or should it be tracked outside sktime?

**Comment by fkiraly** [comment]
>That probably makes sense if there is only 1 model, but in general, if we encounter more such features that can be tracked (with more than 1 example), would sktime be a viable place to add these tags or should it be tracked outside sktime?

That's both possible, you can always add your own tags if you want them wihtout having to change the framework. E.g., import an estimator and call the `set_tag` function with the tag of your choice and the value of your choice (for dynamic tags, or use the `_tag` attribute to static ones).

`sktime` itself is, in-principle, also a good place.
We want to avoid having tags proliferate though, the more there are, the less useful the ones that are there are, and the more tags a developer may have to set if they extend `sktime` (although you could set "defaults").

What would be really useful would be a list of suggested tags, with examples and reasons why you think it might be useful for the user. 
So whenever you come up with a tag that could be useful, feel free to post them here.

About the "multiple seasonal period" one, I'm really neutral. I've just been trying to understand what the user benefit is. So if the case is good enough, or enough users would find it useful, I'm willing to be convinced. You'll also need to convince the other core devs who'd be reviewing it. And if the reviewers are not convinced (for whatever reason), as said, you can always add the tags in your own package by using `sktime` onboard functionality.

**Comment by ngupta23** [comment]
Sounds good. I will wait to find a more convincing case. For now, this is good to know.
