### ISSUE TITLE
[BUG] Four classifiers failing `fit` when not enough time points (10)

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1866]
Multiple time series classifiers seem to be failing when the number of time points is too small.

I've verified this with `DrCIF` and `SupervisedTimeSeriesForest` on win py3.9, other estimators that may be affected are: `HIVECOTEV2`, `MUSE`.

The following code runs:
```python
from sktime.utils._testing.panel import _make_classification_y, _make_panel_X

T = 20

y = _make_classification_y(n_instances=10, random_state=42)
X = _make_panel_X(n_instances=10, n_timepoints=T, random_state=42, y=y)

my_cls = DrCIF().fit(X, y)
```

The following code does not run:
```python
from sktime.utils._testing.panel import _make_classification_y, _make_panel_X

T = 10

y = _make_classification_y(n_instances=10, random_state=42)
X = _make_panel_X(n_instances=10, n_timepoints=T, random_state=42, y=y)

my_cls = DrCIF.create_test_instance().fit(X, y)
```

The error message raised is non-informative.

I'd expect the code to run, in both cases, or at least raise an informative error message in the second case.

**Comment by TonyBagnall** [comment]
more likely the series length, since we fit on 10x24 for unit tests. Should through an informative error though I agree.

**Comment by TonyBagnall** [comment]
where are the methods _make_panel_X and _make_Y?

**Comment by TonyBagnall** [comment]
(sorry, misread, hence deleted a comment)

**Comment by TonyBagnall** [comment]
to recreate

**Comment by TonyBagnall** [comment]
![image](https://user-images.githubusercontent.com/9594042/149024594-8464d458-5f83-4b6f-86e0-26b27c62efda.png)
len_range = 5, min_intervals = 4, so random fails. It may just need an edge case check,  
                    len_range = min(
                        transform_length - intervals[j][0],
                        self._max_interval[r],
                    )

**Comment by fkiraly** [comment]
>where are the methods _make_panel_X and _make_Y?

Ah, sorry, forgot the imports. Added them at the top.

**Comment by fkiraly** [comment]
& `MUSE` seems to have stochastic failures even for larger sizes?
See this run
https://github.com/alan-turing-institute/sktime/runs/4783434797?check_suite_focus=true

Locally, the test was not failing.

**Comment by TonyBagnall** [comment]
not sure about MUSE, will try fix our two first then take a look at the other two.

**Comment by TonyBagnall** [comment]
train_X = np.random.rand(10, 10)
#val = np.random.randint(low=0, high=1)
#print(val)
train_y = np.random.randint(low=0, high=2, size = 10)
cls = MUSE()
cls.fit(train_X, train_y)

gives an intermittent error

![image](https://user-images.githubusercontent.com/9594042/149148860-dc628a73-f52a-4560-b12b-d999a3e6d731.png)

looks to be a problem with the data not being consistent with logistic regression (assuming this is what linear_models\_logistic.py is). I'll take a look

**Comment by TonyBagnall** [comment]
so its getting to here in _muse and all_words is empty. 
![image](https://user-images.githubusercontent.com/9594042/149149613-098f9b4e-a189-46ae-9d84-42297e5579a2.png)

**Comment by TonyBagnall** [comment]
basically feature selection finds no relevant words, which causes the sklearn classifier to (iunderstandably) crash. Discussed with Matt and we will add a special case for when all_words is empty and just keep all the words, any thoughts @patrickzib ?

**Comment by TonyBagnall** [comment]
and @MatthewMiddlehurst has also found the problem with DrCIF and by implication HC2, PR to follow.

**Comment by fkiraly** [comment]
one way would be fallback behaviour. For instances, if whatever features fail to extract, predict the majority class on the training set instead of running against a wall.
