### ISSUE TITLE
Compile manylinux wheels

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#188]
Currently, we only get wheels for specific linux versions which are not accepted by PyPI. We need to set up our CI to build wheels following the [manylinux](https://github.com/pypa/manylinux) convention. Also see this [blog post](https://opensource.com/article/19/2/manylinux-python-wheels).

**Comment by goastler** [comment]
Okay so as I understand it we need a wheel per linux distro. The manylinux idea uses an old CentOS6 linux install to build a wheel which is compatible with most linux distros today as they all inherit off of CentOS6 (afaik, may be wrong!). Either way, CentOS6 is generic enough.

I'm currently trying to mirror [this demo](https://github.com/pypa/python-manylinux-demo) in sktime, but the build install script is rather odd. I'm not sure whether the OSX entry in travis is going to play well with this, we'll need to heavily adjust the demo I think.

**Comment by mloning** [comment]
Closed by #241
