### ISSUE TITLE
[ENH] weighted version of scipy based distance class

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1887]
Also related to #1884.

I think it would be a good idea to extend `ScipyDist` with an optional parameter `weights` (1D iterable of float) which multiples the i-th column of `X`, `X2` with the i-the element in `weights` before applying the distance. If weights are passed, there should be a check in `_transform` for `weights` having length equal to number of columns of `X`, `X2.

Note: this should be done manually in `sktime`, since weighting is deprecated in `scipy`.

**Comment by stepinski** [comment]
Hi, I wanted to get involved in the project. Can you assin me to this issue?

**Comment by lmmentel** [comment]
All yours @stepinski :tada:
