### ISSUE TITLE
[ENH] data type conventions - should time index be unique?

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1893]
Should all data type conventions adopt the strict requirement that time indices be unique?

For instance, should the `pd.DataFrame` format specification ensure that the `DataFrame.index` has no duplicates?
Currently, the checks allow it, but if there are duplicates, there are errors in various places, for instance in the conversions.

The "safe" fix seems to be to add checks to require the assumption for which our codebase is robust; the "soft" fix is to add tests which check correctness on fixtures where there are repeated indices for compliance.

An example "bug" (bug depending on this assumption) is in the `AA_datatypes` notebook as of current `main`. Since `load_arrow_head` has a (potential) bug that loads a data frame with repeated indices, the subsequent call to `convert_to` results in a data frame that is still nested and does not comply with the `df-multiindex` specification.

**Comment by fkiraly** [comment]
Looking back at this: we probably want instance indices to be unique, affecting specific mtypes such as `nested_univ`. One can have repeated observations attributed to a give time point, so we may not like to enforce uniquenss for the time stamp.

As in the "soft" fix, we may like to test for robustness of methods, by introducing fixtures with repeated time indices.

**Comment by khrapovs** [comment]
I would be strongly against enforcing uniqueness of index values. I do not know how common my use case is, but I have already spent quite a lot of effort on generalising sktime's splitter behaviour to deal with either repeated or missing observations, or both. For reference:
- https://github.com/sktime/enhancement-proposals/blob/main/steps/18_cv_with_irregulrar_ts_data/step.md
- https://github.com/alan-turing-institute/sktime/issues/1737

**Comment by fkiraly** [comment]
> I would be strongly against enforcing uniqueness of index values

Is that only for *time* index, or also for *instance* index?

I would be weakly against doing this for time index, but I would be in favour to enforce unique instance index.

The problem at hand is mainly from the `nested_univ` type, where a non-unique instance index makes the representation ambiguous, even if the "abstract data type" still can have repeated index.
In the pandas multiindex or a simple series, I do not mind duplicate time index, and a duplicate instance index will not even be possible (since rows with the same instane index are automatically considered as part of the same instance by pandas).

I'd be happy taking the decision that we allow repeated time indices.

What we then should do:
* we need to write tests to ensure the estimators work with repeated time indices. I suppose adding a fixture would do, or - to avoid additional runtime - changing one of the many fixtures to an example that has a repeated time index? Needs to be done in forecasting, transformers, classifiers.
* think about simple transformers or tags, e.g., transformers that remove duplication etc.

**Comment by fkiraly** [comment]
From slack discussion with @khrapovs, agreement:

* we should allow duplicate time indices. That can happen in a number of relevant use cases.
* instance indices should not be duplicate, since it is the "name of" a series, and like in math this should not be overloaded.

There is no contradiction, since time index is, conceptually, not "name of" but "place of", and multiple things can be in the same place.

As a consequence, we need to test.
Closing this given decision, test issue is here: https://github.com/alan-turing-institute/sktime/issues/3032
