### ISSUE TITLE
[ENH] predictive intervals and quantiles for naive forecaster

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1905]
- [ ] Describe naive predictive intervals (what is the method?)
- [ ] implement for `NaiveForecaster`

Related to the variance forecaster of @IlyasMoutawwakil

**Comment by fkiraly** [comment]
Question, what should this be?

I see a number of options:
* detrend in-sample, compute the variance of in-sample residuals. Use this as a predictive variance with normal assumption, get intervals/quantiles from that.
* use rolling residuals, like in @IlyasMoutawwakil´s variance forecaster, then do the same
* use any of the residuals and get empirical quantiles, use the empirical cdf of residuals as a probabilistic prediction

... any other options?

**Comment by ltsaprounis** [comment]
The naive methods' forecast variance can be expressed analytically under the 2 assumptions below:
- forecast values are normally distributed
- residuals are uncorrelated

https://otexts.com/fpp3/prediction-intervals.html#benchmark-methods

**Comment by fkiraly** [comment]
yes, sure, but *which residuals* would be part of the question above?

**Comment by SveaMeyer13** [comment]
Can't we use the expression used in #775 and adapt it to the current interface?

**Comment by fkiraly** [comment]
hm, maybe? Looking through it I'm not sure which method/algorithm this proposes to implement.
There's not just one one could use, similar to how there are multiple naive strategies for the point prediction.

Do you have a pointer to the method or algorithm description? Maybe I'm just not seeing it among all the discussion.

**Comment by topher-lo** [comment]
Hi @fkiraly, I created a PR with `_predict_var` and `_predict_quantile` translated from the R naive forecast code (which implements the FPP3 textbook's algorithm in Chapter 5.5 for naive prediction intervals). To answer your question:

> Question, what should this be?
> 
> I see a number of options:
> 
> * detrend in-sample, compute the variance of in-sample residuals. Use this as a predictive variance with normal assumption, get intervals/quantiles from that.
> * use rolling residuals, like in @IlyasMoutawwakil´s variance forecaster, then do the same
> * use any of the residuals and get empirical quantiles, use the empirical cdf of residuals as a probabilistic prediction
> 
> ... any other options? (probably there´s also a few different ways this could look like if we try to write down in formalism)

We take the first option: i.e. we first compute the in-sample AKA past residuals, we then compute the residuals standard error, and finally compute the forecast standard error using the following formulas from FPP3:

<img width="677" alt="Screenshot 2022-09-17 001240" src="https://user-images.githubusercontent.com/46541035/190846334-d868c80a-0d3b-4a38-9b64-d9a601159806.png">
