### ISSUE TITLE
[BUG] old CI/CD checks still showing in the GitHub CI summary

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1918]
Items from this:
- [x] readthedocs does not complete properly. fixed in #1920 
- [x] the old checks removed in #1620 should no longer display in the GitHub PR checks interface.

---
After the CI refactor #1620, the old checks are still being displayed in the GitHub PR checks interface, here (example):

![image](https://user-images.githubusercontent.com/7985502/150696962-769249f3-c48c-4009-bee0-c284795b54c6.png)
 
Rreadthedocs do not display as completed.

The new GitHub actions based tests display and run as they should.

What is really strange is that for a new PR, the display, at the start, seems to jump between the old set and the new set of tests.

This is not affected by whether the PR branched off post or pre #1620, see also https://github.com/alan-turing-institute/sktime/pull/1917

The expected behaviour is that only the new checks are shown.

**Comment by lmmentel** [comment]
Related discussion on SO https://stackoverflow.com/questions/57927115/anyone-know-a-way-to-delete-a-workflow-from-github-actions

**Comment by lmmentel** [comment]
The config file for appveyor has been removed in #1620 so it seems that the integration needs to be terminated from the appveyor, which is currently configured using an account that belongs to @mloning.

**Comment by lmmentel** [comment]
Also this https://github.community/t/removed-workflow-showing-up-as-check-for-pr/16393 I don't have the access so someone else needs to own this.

**Comment by fkiraly** [comment]
>Also this https://github.community/t/removed-workflow-showing-up-as-check-for-pr/16393 I don't have the access so someone else needs to own this.

Yes, this was it, @lmmentel!
It was coming from the branch protection rules.

This leads to required tests being *displayed* even if they are not *executed*.

I changed the required tests to the new ones, that should take care of the issue for all future PR (also of the appveyor one, I think).

**Comment by fkiraly** [comment]
ok, this apparently fixes GitHub actions, but not appveyor.

**Comment by fkiraly** [comment]
as @mloning said on slack, he probably just needs to delete (or uncouple) the appveyor project

**Comment by fkiraly** [comment]
... and it's gone, I guess @mloning did it?

**Comment by mloning** [comment]
I now deleted the appveyor project, hope that fixes it.

**Comment by fkiraly** [comment]
> I now deleted the appveyor project, hope that fixes it.

Excellent, it does! Thanks!

**Comment by lmmentel** [comment]
Thanks @mloning!
