### ISSUE TITLE
[ENH] refactor `all` submodules to use `all_estimators` instead of manual update

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1928]
Some modules have an `all` submodule that allows for easy import of all estimators in the module - in theory.

In practice, extenders would need to update the package with imports every time an estimator is added, which is clunky, has not been documented, and hence also not done in the past.

An easy solution which would remove the need to manually update would be to use `registry.all_estimators` to create the list of estimators in the module automatically, and similar lookup functionality, where it exists, for other objects.

Shouldn't be too hard (... I may be mistaken, of course ...), hence good first issue.

**Comment by nilesh05apr** [comment]
@fkiraly  i would like to work on this issue.

**Comment by fkiraly** [comment]
Excellent, @nilesh05apr, welcome and go ahead!

One note, there was an issue with `all_estimators` in the recent version which has been fixed - it would raise errors if not all soft dependencies were installed.

So, I would suggest you also test your work with two environments - one which only has core dependencies, and one which has all soft dependencies.

**Comment by fkiraly** [comment]
resolved by this PR https://github.com/alan-turing-institute/sktime/pull/2845
