### ISSUE TITLE
[ENH] add .tsf loader in sktime

### ISSUE THREAD

**Issue by ltsaprounis** [alan-turing-institute/sktime#1933]
Monash Time Series Forecasting Repository has introduced a new file format for storing time series data for forecasting problems called .tsf, inspired by sktime's .ts format. The repository has a lot of nice/popular benchmark datasets, including Australian tourism datasets and 3/5 of the M competitions.

A .tsf reader is available from the Monash repository team here:
https://github.com/rakshitha123/TSForecasting/blob/master/utils/data_loader.py

We should make this available in sktime!

**Comment by fkiraly** [comment]
pinging @rakshitha123 so I can add her as the owner of this issue
