### ISSUE TITLE
[ENH] verbose CI/CD test for mac and unix

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1947]
In our current GitHub actions CI/CD, the windows tests are verbose, i.e., logs per test are printed out, which is very useful for diagnosing on remote.

This is not the case for mac and unix (only "dots" are printed and percentages) - it would be great if it were.

Not sure what would have to be changed, but perhaps a good first issue for someone with CI/CD and/or GitHub actions experience.

**Comment by fkiraly** [comment]
This may have been posted in error, following #1941, and the very recent CI/CD refactor.
It does seem that the mac tests at least are verbose at runtime.

I need to check whether tests are verbose or not, once #1941 is resolved.

**Comment by fkiraly** [comment]
ok, the tests are already verbose. However, they just output "dots" and not what tests they are at on mac and unix.

**Comment by Saransh-cpp** [comment]
@fkiraly, I think I might've found a fix for this. Can I take this up too? (I am still working on #2039 but this one will be a quick fix)
