### ISSUE TITLE
Save results function in Shapelet Transform

### ISSUE THREAD

**Issue by i3evelyn** [alan-turing-institute/sktime#195]
**Describe the bug**

In the shapelet transform code: https://github.com/alan-turing-institute/sktime/blob/master/sktime/transformers/shapelets.py.
Two functions report errors: write_shapelets_to_csv, write_transformed_data_to_arff
**To Reproduce**

```python
[Past your code here.]
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by mloning** [comment]
Thanks for raising the issue! These function were mainly used for development as far as I know. 

@i3evelyn If you're interested to contribute, a PR would be highly appreciated!

@jasonlines @dguijo can we remove them or could you make them more usable?
