### ISSUE TITLE
[ENH] `clustering._base` could be called `clustering.base`

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1979]
Imports `from sktime.clustering.base` have ceased to work in 0.10.0 since `sktime.clustering.base._base` was moved to `sktime.clustering` without renaming `_base` to `base`.

This should not have happened without deprecation - it happened without any warning.
It is also inconsistent with all the other modules, where `sktime.modulename.base` has the base classes.

Hence, one of the two following things should happen:
* add a `sktime.clustering.base` which aliases `_base`
* rename `sktime.clustering._base` to `sktime.clustering.base`

FYI @TonyBagnall, @chrisholder. Also see #1978

**Comment by fkiraly** [comment]
(is this correct?, i.e., is this a bug?)

**Comment by TonyBagnall** [comment]
I don't think it's a bug, it's a design choice Chris made. I think it makes sense, as we use init everywhere else

**Comment by fkiraly** [comment]
well, it's currently the only module whre the `BaseSthSth` is not in `module.base`.
It's not consistent with classification, for instance, which has a very similar base class and module design.

**Comment by TonyBagnall** [comment]
I changed classification to _base but it was part of a PR you blocked. Clustering is, by your definition, "experimental" [ref ABC discussions], so we I think this is fine unless you have anyone who has actually objected to it. If there are users wqho object, we could look at changing it, otherwise, it seems to me a good change to make our design more consistent.

**Comment by fkiraly** [comment]
>I changed classification to _base but it was part of a PR you blocked. 

Ah - in-principle, I would not mind, but we need to deprecate if we change public module names.

**Comment by fkiraly** [comment]
> Clustering is, by your definition, "experimental" 

Valid point - on the README the status is given as experimental.

Let's have the discussion on what the base modules should be called.

**Comment by chrisholder** [comment]
This has been refactored and is in main now
