### ISSUE TITLE
Applicable methods for times series classification and transformation for time series like `japanese_vowels`

### ISSUE THREAD

**Issue by roumail** [alan-turing-institute/sktime#1984]
Hello,

First of all, I wanted to thank the maintainers for this great library. I just came to learn of it and have been absolutely blown away by the documentation and algorithms that are now accessible to people who aren't intimately familiar with this field..

I have been diving through your documentation for a use case of mine where I have a data structure matching japanese_vowels dataset, i.e, multivariate time series unequal time series. After the initial learning curve getting your data into the expected format, I'm now in a trial and error phase to find the methods that are applicable for my usecase. 

I saw that most examples for multivariate time series used the motions data, so I've kind of just been trying to run those examples replacing them with the japanese vowels. Obviously, this is a time consuming process. I wonder if you had any suggestions  as to how to proceed. Are there plans to add some sort of tagging for method documentation so we know which methods (classifiers/transformers) are suitable for a given data type? 

Secondly, I understand that unequal time series is probably a more difficult usecase so I was wondering if I might not just try and pad the different time series using forward fills to get the more common equal time series use case. That might increase the options I have available for my use case. Since this is all quite new to me, I was thinking of using different transformations (PAA/SAX/Catch22, Matrix profile etc) and then find a way to featurize these for a couple of different pipeline setups: sklearn type as well as the sktime multivariate pipelines from the examples.

Thank you!

**Comment by roumail** [comment]
Apologies but I have a follow up question as well regarding the unequal time series example. Imagine a dataset with n instances, t timepoints and d dimensions. Do we need to have equal time points per dimension or equal timepoints ACROSS dimensions?

Assuming n=50, t = 20, d = 5, we'd have data of shape `(50, 5, 20)` for the former case. However, for the latter, our `t` would depend on the dimension we're talking about.

So when we talk about equal length time series in the multivariate case, do we need the former or will the latter suffice ? Hope the example was clear...

**Comment by TonyBagnall** [comment]
Hi and welcome! I'll respond in more detail next week, but really happy that you have found sktime :)

**Comment by fkiraly** [comment]
Let me answer what I can:

> Secondly, I understand that unequal time series is probably a more difficult usecase so I was wondering if I might not just try and pad the different time series using forward fills to get the more common equal time series use case. That might increase the options I have available for my use case. Since this is all quite new to me, I was thinking of using different transformations (PAA/SAX/Catch22, Matrix profile etc) and then find a way to featurize these for a couple of different pipeline setups: sklearn type as well as the sktime multivariate pipelines from the examples.

Pipelines like this are definitely a priority focus. To which extent they are already possible with the various components we have in 0.10.0, @TonyBagnall can answer.

I suspect you my already be able to do this by pipelining the `PaddingTransformer` or `TruncationTranformer` with a multivariate classifier.

> Apologies but I have a follow up question as well regarding the unequal time series example. Imagine a dataset with n instances, t timepoints and d dimensions. Do we need to have equal time points per dimension or equal timepoints ACROSS dimensions?

The `sktime` interface does *not* enforce equal time points per dimension or across dimensions - as long as you use a data format such as `pd-multiindex` that doesn't. The `numpy3D` format does.
See this tutorial for data formats: https://github.com/alan-turing-institute/sktime/blob/main/examples/AA_datatypes_and_datasets.ipynb

However, individual time series classifiers may enforce equal time index (and in fact most do, I think), since the logic/mathematics assumes that. The corresponding classifier tag is `"capability:unequal_length"` for unequal length time series. There is no tag for "time index must be equal across series", I just notice - do you know why, @TonyBagnall?

You can search classifiers via the `registry.all_estimators`, or in the estimator web overview here:
https://www.sktime.org/en/stable/estimator_overview.html

**Comment by roumail** [comment]
Thanks @fkiraly for pointing me towards PaddingTransformer. It seems I had missed it in the documentation and I might have gone ahead and implemented this myself :D This is probably a separate topic on it's own but with Padding transformer I see that we don't have the option of doing a "forward-fill". 

Thanks for pointing me to the other resources - I'll give them a look and keep trying!

**Comment by roumail** [comment]
Raised bug for issues I faced when trying to use `ColumnWiseTransformer` https://github.com/alan-turing-institute/sktime/issues/2040

Please let me know if this is something that could be something I can help with. I saw that we didn't have tests for ColumnWiseTransformer or maybe I can add documentation.. It would be my first open source contribution so might have some questions :)

**Comment by roumail** [comment]
Sorry but can you please share an example of how to pass "capability:unqual_length" as the argument for filter_tags? The docstring for the argument `filter_tags` to `all_estimators` isn't super clear to me. I've tried messing around with `from sktime.registry._tags import ESTIMATOR_TAG_REGISTER` but it's not super obvious..

The link [above](https://www.sktime.org/en/stable/estimator_overview.html) doesn't have the ability to filter using the tags

**Comment by fkiraly** [comment]
>The link [above](https://www.sktime.org/en/stable/estimator_overview.html) doesn't have the ability to filter using the tags

Yes, known issue with the estimator overview, we want to improve that:
https://github.com/alan-turing-institute/sktime/issues/1930

> Sorry but can you please share an example of how to pass "capability:unqual_length" as the argument for filter_tags?

```python
from sktime.registry import all_estimators

all_estimators(estimator_types="classifier", filter_tags={"capability:unequal_length": True}, as_dataframe=True)
```

should print the table you want.
... and, apparently, it prints an empty table! That would mean none of the "component" estimators can deal with unequal length. I.e., the only way would when using `sktime` onboard components would be to pipeline it with sth like the `PaddingTransformer`.

**Comment by MatthewMiddlehurst** [comment]
Yes, none of the classifiers currently can handle unequal length data. I think the answer by Franz above is sufficient. 

Will leave this up for a while longer if anyone has anything to add.
