### ISSUE TITLE
[ENH] MAPE/sMAPE `symmetric` flag default should be switched

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1986]
Current parameter defaults of MAPE, MdAPE metric classes etc heavily frustrates user expectations, since the default parameter settings actually produce sMAPE and sMdAPE etc (as pe common definition) and not MAPE, MdAPE (as per common definition).

This should be switched around, so default invocation of MAPE metric classes indeed give MAPE (as commonly defined).

The switch is easy - just flip the default to `symmetric=False` - but we will need to add a deprecation message since this is part of a widely used public interface.

See the [documentation on deprecation policy](https://www.sktime.org/en/stable/developer_guide/deprecation.html), we're probably looking at deprecation in 0.11.0, and removal in 0.12.0.

I.e., adding a "will be deprecated" warning now, then a "will be removed" warning in 0.11.0, then removing in 0.12.0.

Good first issue for someone to get involved with `sktime`.

---

from discussions, @k7e7n7t:

https://github.com/alan-turing-institute/sktime/discussions/1508

> I ran mean_absolute_percentage_error in cell 41 of 01-forecasting.ipynb and got 0.145427686270316.
> I then ran MeanAbsolutePercentageError class with the default symmetric = False (which make it asymmetric just like MAPE I assume) but I get  0.13189432350948402 which I would expect from sMAPE, but not with the flag set to False.  If I set symmetric = True it does match.  This seems backwards to me.  What am I missing?

**Comment by ltsaprounis** [comment]
I don't think it's a real bug. The issue is that default is `symmetric=True`. Have a look at the docs:
https://www.sktime.org/en/stable/api_reference/auto_generated/sktime.performance_metrics.forecasting.MedianAbsolutePercentageError.html

This is not very intuitive. Users expect that MAPE is MAPE and not sMAPE... 
e.g. Have a look at the forecasting metrics code here: 
https://github.com/ltsaprounis/dsf-ts-forecasting/blob/main/notebooks/02-forecasting-metrics.ipynb

MAPE and sMAPE have the expected behaviour when you manually specify `symmetric`. 

I think this needs to change, but we'll have back-compatibility issues if/when we change it. I would also prefer a separate sMAPE class to avoid things like that in the future. 

Tested it on the code in main: 
```python
from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError
import numpy as np

y_forecast = np.array([10, 10, 10])
y_actual_1 = np.array([8, 8, 8])
y_actual_2 = np.array([12, 12, 12])


mape = MeanAbsolutePercentageError(symmetric=False)
print("This should be MAPE:")
print(f"forecast 1: {mape(y_actual_1, y_forecast): 0.2f}")
print(f"forecast 2: {mape(y_actual_2, y_forecast): 0.2f}")

print("\nThis should be sMAPE:")
smape = MeanAbsolutePercentageError(symmetric=True)
print(f"forecast 1: {smape(y_actual_1, y_forecast): 0.2f}")
print(f"forecast 2: {smape(y_actual_2, y_forecast): 0.2f}")

print("\nsimple NUMPY implementation:")

def calc_mape(actual, fcast): 
    return np.mean(np.abs(actual-fcast)/actual)

def calc_smape(actual, fcast): 
    return 2 * np.mean(np.abs((actual-fcast)/(actual+fcast)))

print("\nThis should be MAPE:")
print(f"forecast 1: {calc_mape(y_actual_1, y_forecast): 0.2f}")
print(f"forecast 2: {calc_mape(y_actual_2, y_forecast): 0.2f}")

print("\nThis should be sMAPE:")
print(f"forecast 1: {calc_smape(y_actual_1, y_forecast): 0.2f}")
print(f"forecast 2: {calc_smape(y_actual_2, y_forecast): 0.2f}")
```

**Comment by fkiraly** [comment]
ah, yes! Makes sense, @ltsaprounis.
It's not a bug since the implementation agrees with the specification.

But it is a quite heavy frustration of user expectations that, if you write `MeanAbsolutePercentageError()`, you do *not actually get the MAPE* as commonly defined.

I think we need to change the default to `True`, and that needs deprecation since it is part of the public interface.

I'll change this issue to a ticket to do this, if we are all agreed.

FYI @k7e7n7t.

**Comment by mtorabirad** [comment]
A minor point but shouldn't we call symmetricMAPE adjustedMAPE. After all, sMAPE is not really symmetric and the original developer of the Metric, Armstrong, never called it symmetricMAPE. https://www.youtube.com/watch?v=_uaJWg5eNpE&ab_channel=MLBoost
