### ISSUE TITLE
[BUG] scipy 1.8.0 breaks BoxCoxtransformer due to reliance on private interface (needs fixing/removal)

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#1994]
`scipy 1.8.0` is just 2 minutes old and already breaks our CI/CD.

The issue seems to be with the import of `_boxcox_conf_interval` in `BoxCoxtransformer` which has changed.

Generally, it is a bad habit to interface private methods, we should not do this.

Also, it does not seem that the output of `_boxcox_conf_interval` is really used in the transformer? The easy way to address this is probably simply to remove the third optional argument of `_boxcox`.

**Comment by fkiraly** [comment]
seems very straightforward - good first issue.
(will unlabel in case someone picks this up)

**Comment by ltsaprounis** [comment]
I find this video really relevant: 
[James Powell: Because You Can Run, You Can't Hide: Some Musings on API Design | PyData London 2019](https://www.youtube.com/watch?v=S0AdB36WuAU)

**Comment by fkiraly** [comment]
@varuniyer, are you still working on this? If yes, you could take care of the other private method dependency. I've opened an issue here: https://github.com/alan-turing-institute/sktime/issues/2469

**Comment by fkiraly** [comment]
ok, the two dependencies both actually cause the breakage. Did you understand how to resolve the issue and not lose the `bounds` argument, @varuniyer? Or is that why you abandoned this?
