### ISSUE TITLE
fit_predict for Forecasters

### ISSUE THREAD

**Issue by big-o** [alan-turing-institute/sktime#200]
**Is your feature request related to a problem? Please describe.**
I'm sure there will be many situations where users just want to get a quick forecast on a time series. Implementing a `fit_predict` method would make the forecaster interface simpler for this common use case.

**Describe the solution you'd like**
Add a `fit_predict` method to BaseForecaster, which takes in all the arguments of `fit` and `predict`, fits the forecaster and returns the prediction for the provided horizon. I'm not aware of any clashing arguments for `fit` and `predict` in any of the existing forecasters, and implementing this method earlier on will force authors to avoid such clashes in the future.

**Comment by mloning** [comment]
Thanks for the suggestions. This seems like a nice convenience method, but I worry that this may also introduce some additional problems, for example how would you handle exogenous variables which are passed separately to `fit` and `predict` (i.e. `exog_train` and `exog_test`)?

**Comment by big-o** [comment]
I guess in that case you would just call `fit` and `predict` separately as before, providing a different `X` for each call. `fit_predict` would just be available to you in the case where you want to reuse the same `X`.

Alternatively you could rename `X` to something different for each method, like `exog_train` and `exog_test`. This would allow you to specify both in `fit_predict` and it would also be a more decscriptive name than just "`X`".

Being forced to use different parameter names in `fit` and `predict` would definitely be a new limitation, but if you want to use different values in each call, then this might indicate that the two values serve different roles (as in your description), which in turn suggests that different parameter names would be more descriptive of the interface.

**Comment by fkiraly** [comment]
Hm, this relates to discussions regarding re-work of the interface we were having last week and are going to have this week (Friday Nov 22 afternoon) at UCL. @big-o , would you mind indicating on Slack whether you are available?

General discussion points involve:
- `fit`, `predict`, and potential `update` method signature
- potential fused methods and their generics such as `fit_predict`, or `update_predict`
- treatment of exogenous variables and multi-variate series
- treatment of specification where to predict, including forecast horizon
- treatment of specification which variables to predict and predict from
- pro/con use of task object and `fit_task` or `predict_task` high-level methods, and/or mixins

The plan is to end up with a concrete interface

**Comment by fkiraly** [comment]
Issue #18 has an older design of mine - I no longer agree with all parts of it (especially treatment of tasks, should probably be by mixin rather than two-layer architecture), but as far as I know it's the only full design we have up.
So homework = read, and/or write your own.

**Comment by fkiraly** [comment]
oh, and
- handling of forecast return type, incl prediction intervals
(relates to recent PR)

**Comment by big-o** [comment]
> Hm, this relates to discussions regarding re-work of the interface we were having last week and are going to have this week (Friday Nov 22 afternoon) at UCL. @big-o , would you mind indicating on Slack whether you are available?
> 
> General discussion points involve:
> 
> * `fit`, `predict`, and potential `update` method signature
> * potential fused methods and their generics such as `fit_predict`, or `update_predict`
> * treatment of exogenous variables and multi-variate series
> * treatment of specification where to predict, including forecast horizon
> * treatment of specification which variables to predict and predict from
> * pro/con use of task object and `fit_task` or `predict_task` high-level methods, and/or mixins
> 
> The plan is to end up with a concrete interface that we are all happy to adhere to and which is interoperable with the remainder of sktime and sklearn ecosystem.

Sorry I won't be able to join your meeting - I'll just share a few of my thoughts here instead. So far I've only worked with the forecasters and the `Deseasonaliser` transformer so my knowledge of the project is limited; I also won't claim to be fully aware of all the possible use cases. I'm coming at this from more of a layman's perspective and thinking about what I believe will be the most common uses of sktime forecasters for people like me. There's probably lots I've misunderstood here - feel free to correct me on anything!

I think the rough idea of the current implementation is pretty good and easy to use for someone coming from previous experience of `sklearn`. There are a few things I think need addressing though:

#### Method signatures

I've just added a few thoughts on this to #199.

#### Defining forecast horizons

I've written something about this in #201.

#### Data containers

I realise this is a hot topic that's already being looked at, but I'll add my thoughts here as I believe it affects the forecasters. @mloning recently wrote a branch that changed forecasters to work with a normal `Series` instead of the "nested dataframes" used elsewhere. In my opinion this is a huge improvement. The nested frames were fiddly and unnecessarily complex, especially for new users. Unfortunately it doesn't escape the fact that you still need to convert things to/from nested frames if you want your forecaster to interact with any other parts of the library. I hit on this issue when writing the code for #198 - I had to deseasonalise/reseasonalise my series within the forecaster. To do that I have to perform some messy transforms on the data containers. Fortunately this is hidden from the users, but what if the user wants to build a pipeline like `[Transform, Forecast]`?  I think they will have the same issue.

One idea I discussed with @mloning was to move to using `xarray` instead, which supports N-D dataframes and therefore covers off multiple time series. The issues with `xarray`, as I understand, are:

1) It won't support multiple unequal-length time series.
2) It won't support multiple series with unaligned time indices.

We can address both issues with padding, but what value do we use to pad with? If we use the obvious choice, NaN, then we lose the ability to distinguish between missing data in the inputs and our padding. This to me isn't a problem with the data container; it's a lower-level problem caused by the fact that numpy defines two kinds of missing data, [NA (Unknown Yet Existing) and IGNORE (Doesn't Exist)](https://numpy.org/neps/nep-0012-missing-data.html#glossary-of-terms), yet it provides no way of dealing with both types at once.

I initially thought we could create a new type of padding object that behaves in a similar way to NaN but is distinguishable from it, or use sparse matrices that can contain NaN values, but I can't think of a good way to implement either of these approaches. Instead, I thought we could let the user provide a padding mask instead. This mask could be optional, that way the use case of having aligned, equal length time series can be achieved with a simple `xarray` (or even a flat `dataframe` for univariate series). For unaligned/unequal series, a helper function could be provided that converts a list of `pandas.Series` into an `(xarray, padmask)` tuple. The padmask can then be used internally to distinguish the NA NaNs (missing) from the IGNORE NaNs (padding). Hopefully this won't make it too difficult to implement algorithms, but I'll leave that for others with more knowledge to comment on.

In the case of forecasters and transformers, this would mean having an new optional `padmask` parameter in `fit()`. I don't think it would be needed in predict as the padmask should be the same for transformers (we don't transform non-existent data) and irrelevant for forecasters.

I appreciate that this would be a huge change, but I believe it would pay off in the long term to move away from the nested format if possible and now is the time to make sweeping changes while the project is still young.

#### Documentation

Not strictly a forecasting issue, but again I think it affects their usability so is worth mentioning. At the moment I feel the docs jump straight into the deep end and skip over a lot of the introductory stuff. sklearn's documentation is a learning resource in itself; it typically introduces the background theory for the task, demonstrates how to implement it with examples and provides detailed API information generated from the docstrings. I feel like the sktime docs assume the user already knows the subject well and just wants the technical detail.

Also I'm not so sure about the format. Notebooks are great for getting one or two points across, but any more than that and they quickly become unwieldy. I think a website provides a much better way to organise and present larger amounts of information. For that reason I would drop the notebooks and prioritise writing sphinx docs which include explanations of the subject matter as well as the implementations.

#### Fitted params

At the moment the ARIMAForecaster wraps up a statsmodels SARIMAX object which does all of the heavy lifting. No problem there, but the forecaster doesn't effectively hide this from the user. If you want to inspect the fitted parameters, you have to inspect the internally stored SARIMAX object. You need knowledge of how the forecaster works (and hope that it hasn't been changed) to be able to use it. The fact that this object is called `_fitted_estimator` indicates that it shouldn't be exposed to users. The new ThetaForecaster on the other hand is implemented directly in sktime, so there is no fitted estimator object (`self` _is_ the estimator).

It's fine to wrap up other libraries with an sktime interface, but if we do that then anything the user might care about should be extracted from the wrapped API and stored as a parameter in the standard format, e.g. to get the smoothing level for an `ExpSmoothingForecaster`, it should be `m.smoothing_level_` rather than `m._fitted_estimator.params['smoothing_level']`.

**Comment by fkiraly** [comment]
>Data containers

Can of worms we've been keeping kicking down the road if you forgive me combining two metaphors here. I'll contribute to discussion in the relevant issue #15 .

> Documentation

Agreed with what you say, could be more beginner friendly - though even if Sphinx, someone needs to invest time to make it...
for now we thought getting feature complete on the TSC/TSR and forecasting fronts would be a priority, as to showcase the reduction/composition arc-hitecture, but certainly documentation is something to revisit.

> fitted params

Agreed that there should be a consistent inspection interface for fitted parameters.
Though this is something that vanilla sklearn doesn't seem to do well either.

In my best of worlds, I'd like the entire sklearn ecosystem to have a `get_fitted_params` (and perhaps even `set_fitted_params`) interface that mirrors that of `get_params`, including nesting/deep access.

**Comment by fkiraly** [comment]
Sorry, this went a little off-topic because of me - thanks for your interesting contributions, @big-o, but if you don't mind helping to correct this mistake of mine, I'd suggest let's discuss the different points in their respective issues.

**Comment by fkiraly** [comment]
Just in case you didn't see @mloning 's updated architecture document:
https://github.com/alan-turing-institute/sktime/wiki/Forecasting-API-proposal
& there will be a meeting 3pm on Fri (see slack).

**Comment by mloning** [comment]
See #218 and corresponding [API design document](https://github.com/alan-turing-institute/sktime/wiki/Forecasting-API-proposal)
