### ISSUE TITLE
Simplify forecast horizon parameter by allowing an integer value

### ISSUE THREAD

**Issue by big-o** [alan-turing-institute/sktime#201]
**Is your feature request related to a problem? Please describe.**
Building forecast horizons might not be obvious to new users - I know if confused me a little at first. I imagine many users will simply want to specify the number of point predictions in the horizon and let the forecaster interpret that as it sees fit.

**Describe the solution you'd like**
Add something like the following to `sktime.utils.validation.forecasting.validate_fh`:

```python
if isinstance(fh, np.integer):
    fh = np.arange(fh) + 1
```

Then if I specify `fh = 20`, I would get back 20 point predictions that immediately follow the last observation in my training data. I don't believe this would break anything in the existing API.

**Comment by mloning** [comment]
In your example, how would I specify the fh if I only wanted to forecast the 20th step ahead (and not the 1st to the 19th)?

**Comment by big-o** [comment]
> In your example, how would I specify the fh if I only wanted to forecast the 20th step ahead (and not the 1st to the 19th)?

As before (if I understand the existing interface correctly): `fh = np.array([21])`. `fh = 20` would just be a convenient shorthand for the existing common use case of `fh = np.array([20]) + 1`. I would have thought that the latter scenario would be much more common than the former which is why I'm suggesting the shorthand interface for it.

**Comment by fkiraly** [comment]
The suggestion is sensible but would cause a clash of signature conventions, as @mloning points out.
I think this can be nicely resolved in a task specification interface, e.g., by allowing for specifying "range" or "offset", see #18. Relates to general interface discussion we are going to have Nov 22, see my post in #200.

**Comment by fkiraly** [comment]
The more specific technical question here is:
what are workable alternatives to resolve the interface clash, except the obvious one to restrict the interface and no longer allow for multiple forecasts at multiple time points?
I.e., even if you were to make a single time point in the future an interface default, what are the (user friendly) ways to also allow many?

**Comment by big-o** [comment]
As promised I'll expand on my thoughts here ahead of your discussion later this week.

Coming at this from the non-expert user's perspective, I would imagine that the most common uses for forecasters would be:

* Make future predictions up to a certain point that may be defined in a number of ways:
  * A fixed number of points ahead
  * Up to a certain timestamp
  * Something more complex, like a certain number of seasonal periods ahead. The periods may be known _a priori_ or inferred through seasonal decomposition.
* Making in-sample predictions as a way of estimating residuals.

I think wanting to know a prediction at a single point in time would be more unusual (with the exception of point `T + 1`). This is because if I'm going to make a prediction, I probably want to see how we get there (i.e. what is the trend) as well as the absolute value.

For that reason, I'll stick by my original suggestion of making an integer `i` shorthand for building a forecast horizon of `i` points out from `T`. It will make the common tasks simple, while still allowing the rarer tasks to be possible. Perhaps you could even use negative numbers for nowcasting (e.g. `fh=-len(y)` to start at the beginning of the training data).

Wishing to calculate a specific point or points that are offset from the end of the training data are, in my mind, less common tasks (note that this is just intuition, I have nothing to base this on). In this case under my proposal you would need to build the horizon directly yourself, i.e. `fh=np.array([4,5,6])` or `np.array([20])`. So this task doesn't become any simpler, but the more common tasks do.

When you start adding in support for datetime indices this might be slightly more complex, but not by much (I think). In this case, the integer shorthand may need an extra parameter alongside it, such as `freq` or `end` - so basically, the minimum arguments needed for a call to [`pandas.date_range()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html). If the forecaster cached the frequency and final timestamp from the training data, then this information could be used to set defaults for these extra parameters, simplifying things further to the point where you're back to a single integer in most cases.

Alternatively, the integer shorthand could live in a different parameter; let's call it `horizon_periods` for consistency with `pandas.date_range`. `validate_fh` would then need to check both `fh` and `horizon_periods` to ensure there are no conflicting options. As full datetime indexing is introduced, you could extend these signatures to include `horizon_frequency`, `horizon_start` and `horizon_end`.

I don't believe any of these suggestions would restrict the interface. You can still make multiple forecasts or single forecasts. The only difference is that you would have an extra way of specifying multiple forecasts available to you, alongside the existing approach.

**Comment by fkiraly** [comment]
Hm, makes sense, especially from a useability perspective.

Any thoughts/opinions on
- specifying the information as different arguments to `fit`/`predict`, or
- bundled through a `ForecastTask` or similar, with named keyword arguments that can be used to specify the one or the other, e.g., `ForecastTask(upto = 2020)` or `ForecastTask(range = [2018,2021])` or similar?

The aspects I'd be interested in is (i) useability/clarity, and (ii) architecture/interface

**Comment by fkiraly** [comment]
Another sub-point: sometimes you want to specify a time stamp, sometimes how many time stamps ahead you want to predict. But the latter is only well-specified if you have a regular grid of time stamps at which data was observed, which isn't an inspectable property.

How do we avoid ambiguitiy or interface clash between specifying time stampe and specifying "how many steps"?
(if not using a task object or structured specification parameter set)

**Comment by big-o** [comment]
> Hm, makes sense, especially from a useability perspective.
> 
> Any thoughts/opinions on
> 
> * specifying the information as different arguments to `fit`/`predict`, versus
> * bundled through a `ForecastTask` or similar, with named keyword arguments that can be used to specify the one or the other, e.g., `ForecastTask(upto = 2020)` or `ForecastTask(range = [2018,2021])` or similar?
> 
> The aspects I'd be interested in is (i) useability/clarity, and (ii) architecture/interface.
> There's also ways to have both of the above, btw.

It seems nice, and analogous to the pd.date_range function. The only downside I can see is that it would require polluting your namespace with an extra import to use it. This is a pretty minor point though, and it could even be circumvented by allowing methods like `predict` to accept the arguments that can construct a `ForecastTask` inside the method, e.g. `m.predict(upto=2020)` or `m.predict(steps=5)`. Alternatively you could encapsulate these arguments: `m.predict(horizon=dict(periods=10, freq='D'))` but this could seem fiddly to some.

If I was being really picky, I would suggest naming it `ForecastHorizon` or even just `Forecast` though, as "task" is quite an abstract term that has more relevance to the architects of the project than the users.

As for the later point on ambiguity, your task solution would certainly be one very clear way of addressing this; probably the clearest of all the proposed ones. Perhaps another approach would be inferring it from the types (`int`/`datetime`), but I think I prefer the task-based approach, especially if it had the option of just specifying the parameters instead of constructing the object in the current namespace.

**Comment by fkiraly** [comment]
Thanks for your feedback. Just to give credit, I think the "task" architecture element in data science first appears in the mlr toolbox (so it's "mine" only in the sense that it is adapted).

**Comment by fkiraly** [comment]
Just in case you didn't see @mloning 's updated architecture document:
https://github.com/alan-turing-institute/sktime/wiki/Forecasting-API-proposal
& there will be a meeting 3pm on Fri (see slack).

**Comment by mloning** [comment]
See #218 and corresponding [API design document](https://github.com/alan-turing-institute/sktime/wiki/Forecasting-API-proposal)
