### ISSUE TITLE
[BUG] forecasting API docs page is broken

### ISSUE THREAD

**Issue by popcornn1** [alan-turing-institute/sktime#2013]
**Describe the bug**

Hello, 
In your API documentation (https://www.sktime.org/en/v0.10.0/api_reference/forecasting.html) there is no references for prophet, ARIMA and BATS/TBATS

![unknown](https://user-images.githubusercontent.com/89520785/152760511-00c6d7db-9114-4efb-9225-921ad5d45e89.png)

</details>

**Comment by fkiraly** [comment]
#2070 and #2168 are two different approaches to this problem.
Looks like either works?
FYI @aiwalter, @popcornn1.
