### ISSUE TITLE
[BUG] report `pandas` anchor difference bug to `pandas` and follow up

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2038]
This fix https://github.com/alan-turing-institute/sktime/pull/1981
uncovered what looks like an underlying bug in `pandas`.

We ought to report it with a minimally reproducing example.

@eenticott-shell, @khrapovs, did one of you already report it?
Just checking, and whether you want to.

**Comment by khrapovs** [comment]
@fkiraly @eenticott-shell here you go: https://github.com/pandas-dev/pandas/issues/45999

**Comment by khrapovs** [comment]
This bug seem to be fixed: https://github.com/pandas-dev/pandas/pull/46006

**Comment by fkiraly** [comment]
alright, let's see what happens.

**Comment by fkiraly** [comment]
Fixed, issue should have been closed after the fix.
