### ISSUE TITLE
[BUG] ColumnWiseTransformer fails with `PaddingTransformer` and `Imputer` transformer on multivariate time series

### ISSUE THREAD

**Issue by roumail** [alan-turing-institute/sktime#2040]
**Describe the bug**

ColumnWiseTransformer isn't playing well, either in a pipeline where I apply `PaddingTransformer` and `Imputer` sequentially, nor when I try to apply one of these transformers directly to the japanese vowels dataset.

**To Reproduce**

```python
from sktime.datasets import (
    load_japanese_vowels,
    #     load_basic_motions
)
from sklearn.pipeline import Pipeline

from sktime.transformations.panel.padder import PaddingTransformer
from sktime.transformations.series.impute import Imputer
from sktime.transformations.series.compose import ColumnwiseTransformer

# load data .. 
vowel_X, vowel_y = load_japanese_vowels()

# helper to confirm padding transformer worked as expected
def summarize_data(df):
    return df.apply(lambda dim: dim.apply(lambda series: len(series)))

# Unequal time series as expected. 
summarize_data(vowel_X)


# Apply each of these transformers (padding and imputing), sequentially to each column using `ColumnWiseTransformer` but it gives me the error `get_tags` not found:

padding_pipeline = Pipeline(
    steps=[
        ("equalise", PaddingTransformer(fill_value=np.nan)),
        ("forward_fill", Imputer(method="ffill")),
        ("passthrough", "passthrough"),
    ]
)
transformer = ColumnwiseTransformer(transformer=padding_pipeline)
ex = padding_pipeline.fit_transform(vowel_X)

# Note that applying this pipeline across the entire dataset without ColumnWiseTransformer works
# However this gives me the same length time series across the entire dataset, which is not what I'm looking for

ex = padding_pipeline.fit_transform(vowel_X)
summarize_data(ex)

# Using columnwisetransformer with any of these transformers gives me a recursion error
equalize = ColumnwiseTransformer(PaddingTransformer(fill_value=np.nan))
out1 = equalize.fit_transform(vowel_X)

ffill = ColumnwiseTransformer(Imputer(method="ffill"))
ffill.fit_transform(vowel_X)
```

**Expected behavior**

A time series that is padded and imputed separately for each column of the multivariate time series

**Versions**

```
Python implementation: CPython
Python version       : 3.8.12
IPython version      : 7.29.0

Compiler    : GCC 7.5.0
OS          : Linux
Release     : 3.10.0-1160.45.1.el7.x86_64
Machine     : x86_64
Processor   : x86_64
CPU cores   : 20
Architecture: 64bit

seaborn   : 0.11.2
stumpy    : 1.9.2
pandas    : 1.3.5
matplotlib: 3.5.1
pyts      : 0.12.0
numpy     : 1.21.2
sktime    : 0.10.0
```

**Comment by aiwalter** [comment]
`PaddingTransformer` is a `panel `tranformer, therefore it seems not to work. `ColumnwiseTransformer` needs a `series `transformer. You can recognize them by means of the import path.

**Comment by fkiraly** [comment]
@aiwalter, with the new transformer interface, all transformers should accept both series and panel.

I suspect what is going on is that `Pipeline` is a scikit-learn transformer and does not have `sktime` methods.
We probably want to create our own transformer pipeline to ensure it is interface compliant? (which currently does not exist)

**Comment by roumail** [comment]
Okay, given that PaddingTransformer is a panel transformer, I removed the sklearn Pipeline and now the usecase works

```python
from sktime.datasets import (
    load_japanese_vowels,
    #     load_basic_motions
)

import numpy as np
from sktime import show_versions
from sktime.transformations.panel.padder import PaddingTransformer
from sktime.transformations.series.impute import Imputer
from sktime.transformations.series.compose import ColumnwiseTransformer

# load data ..
vowel_X, vowel_y = load_japanese_vowels()
equalize = PaddingTransformer(fill_value=np.nan)
equalized = equalize.fit_transform(vowel_X)
fwd_impute = ColumnwiseTransformer(transformer=Imputer(method="ffill"))
df_final = fwd_impute.fit_transform(equalized)
df_final
```
I guess the mistake from my side was a lack of understanding for the PanelTransformer. It works columnwise by default whereas I was expecting it to work on series and therefore tried wrapping it in a pipeline of columnwise Transformers

**Comment by roumail** [comment]
I'm happy to close the issue since it was incorrect usage of the methods..

**Comment by fkiraly** [comment]
yes - the original issue was "not a bug", as it seems.

Though, still, it has highlighted an issue with compatibility of pipelines - which is a different one, but it's given me food for thought. E.g., what if you want to pipeline transformers, and *then* use the resulting transformer in another `sktime` estimator? That may crash for estimators that try to address `sktime` specific interface points that are not available in `sklearn`.

Perhaps a `sklearn`-to-`sktime` "lifter"?

Another issue is user sided documentation - we should finish the transformer tutorial #1705 ...
