### ISSUE TITLE
[ENH] Address deprecated references in datatypes module

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#2049]
I get this future warnings, mildly annoying and probably easy to fix? @fkiraly 

![image](https://user-images.githubusercontent.com/9594042/153705329-cccdd0ee-cdf8-48fc-9495-b5fe300294b9.png)

**Comment by gchhablani** [comment]
Hi @fkiraly,
Can I pick this up?

**Comment by fkiraly** [comment]
Closing in favour of https://github.com/alan-turing-institute/sktime/issues/2332 which has a clearer title and description.
