### ISSUE TITLE
[ENH] GitHub Actions: cancel old but running workflows of a PR when pushing again

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#2062]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
E.g. use this:
https://github.com/marketplace/actions/cancel-workflow-action

**Comment by RishiKumarRay** [comment]
@aiwalter can you describe this issue?

**Comment by RishiKumarRay** [comment]
@aiwalter 
- name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
can i raise a PR for this? adding the above action

**Comment by aiwalter** [comment]
@RishiKumarRay yes would be appreciated

**Comment by RishiKumarRay** [comment]
@aiwalter please review #2063
