### ISSUE TITLE
[BUG] `SFA` transformer does not comply with transformer interface since it returns unsupported format, list of dict

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2064]
Discovered in refactoring the transformers to the new interface. Updated after discussion below.

It would appear that the `SFA` does not comply with any `sktime` transformer interface, because `transform` returns a list of dictionaries.

Based on discussion with @MatthewMiddlehurst, @patrickzib (below and on slack), the list of dict can be read as a table, with list index = row index and key = col index, so it is formally/scientifically a transformer.

The non-compliance comes through `sktime` currently not supporting list of dict as a table format.
Two options would exist in-principle: always convert to a compliant output format (i.e., modify SFA), or introduce list of dict as a compliant format (i.e., modify the datatypes module).

We've reached the conclusion that we should do the second, i.e., that it should be added, since conversions to `pd.DataFrame` etc greately reduce performance of composites, namely classifiers that use the SFA transformer.

**Comment by MatthewMiddlehurst** [comment]
The SFA transformer was one of the first things I contributed to the package, it has been in the package in this state for years at this point.

I brought this up in the refactor PR, but it was not addressed.

**Comment by fkiraly** [comment]
ah, which PR is that?

**Comment by fkiraly** [comment]
also, can you esplain why all the tests were passing? The `SFA` transformer is non-compliant, was not excepted from tests, and also did not raise any test breaks - I don't quite understand that.

**Comment by fkiraly** [comment]
ok, so do I understand that this is really old legacy code then, before transformers had a consolidated interface?
If it is useful to have dict returns from transformers, should that be another return type?

**Comment by MatthewMiddlehurst** [comment]
https://github.com/alan-turing-institute/sktime/pull/1365

We provide an option to return a dataframe instead, which is used for tests. This is not the ideal output datatype, however. The output is very sparse, so dictionaries are ideal.

**Comment by MatthewMiddlehurst** [comment]
There are 200 comments in that PR so it was probably just washed away in the tide of feedback, but having a return types for dictionaries or a similar structure would be nice.

**Comment by MatthewMiddlehurst** [comment]
The issue with the transformer's output is that there are possibly hundreds of thousands of potential attributes depending on the parameters, of which only a few will have non-0 values for each series. 

You could return a dataframe containing only that attributes which appear for all cases, which the previously mentioned option does, but then it becomes very difficult to compare two sets of data separately transformed.

**Comment by patrickzib** [comment]
> The issue with the transformer's output is that there are possibly hundreds of thousands of potential attributes depending on the parameters, of which only a few will have non-0 values for each series.
> 
> You could return a dataframe containing only that attributes which appear for all cases, which the previously mentioned option does, but then it becomes very difficult to compare two sets of data separately transformed.

And as far as I remember, the code became very slow when constantly converting between dicts and DataFrames. A dict as an input to a DataFrame will essentially create a single column for each entry in the dict. Given that the Bag of Patterns representatio has potentially thousands of words this was way too slow.

**Comment by fkiraly** [comment]
ok, @MatthewMiddlehurst, @patrickzib, I updated the issue description at the top with the result of our discussions, have a look whether that captures it correctly.

**Comment by MatthewMiddlehurst** [comment]
Good description of the issue and surrounding discussions.

**Comment by fkiraly** [comment]
We´ve added the `list_of_dict` mtype for `Table` to the registry, h ence SFA is now interface compliant (via interface extension)
