### ISSUE TITLE
Black formatting

### ISSUE THREAD

**Issue by big-o** [alan-turing-institute/sktime#208]
**Is your feature request related to a problem? Please describe.**
Make code formatting consistent by using [`black`](https://black.readthedocs.io/en/stable/).

**Describe the solution you'd like**
There are several formatting standards across the sktime codebase. This means we can't use automatic code formatters without making more changes than intended. `black` is a popular formatter that is used by an increasing number of projects including `pandas`. It enforces a strict subset of PEP8 standards easily and automatically.

As well as being a simple command-line tool, it can be integrated into several IDEs giving developers lots of flexibility. It can also be made into a git web hook or a unit test that will force contributors to make their code black-compliant to pass the regression tests ([here's an example](https://github.com/big-o/cherrypicker/blob/master/tests/test_black.py) from a side project of mine).

**Comment by mloning** [comment]
I'm generally in favour of the idea of enforcing consistent coding styles. I'm not sure if we want to do it at this stage because it adds an additional hurdle for contributors, old and new alike. 

If we want to enforce it at a later stage, how easy is it to automatically reformat existing Python code to comply with black style? I know that you can just run `black <file>` but does that generally work without problems?

**Comment by big-o** [comment]
Yes, it's incredibly easy. You can just run `black <file>` or `black <directory>` (to reformat everything at once. If you've integrated it into your IDE, you can reformat the files you have open with a single command/click.

Black is technically beta software but in practice it's extremely stable. (The beta status is only because they may make minor changes to the formatting style in the future). By default it compares the AST before and after formatting to make sure the code isn't effected.

The following notable open-source projects trust Black with enforcing a consistent code style: pytest, tox, Pyramid, Django Channels, Hypothesis, attrs, SQLAlchemy, Poetry, PyPA applications (Warehouse, Pipenv, virtualenv), pandas, Pillow, every Datadog Agent Integration, Home Assistant.

**Comment by mloning** [comment]
Opted for flake8 for now, changed in #246, but happy to change it to black if someone wants to implement it :)
