### ISSUE TITLE
[ENH] Create mock estimators for use in testing

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2091]
"good first issue" for those with good experience in testing.

A useful type of class to have for testing would be mock estimators.

What should such a mock class do?
* behave like an estimator of a specific kind, e.g., forecaster, or classifier - returns correct outputs for given inputs. Bonus if it can cover many independent tag settings, although for the start we may be happy with just a few (e.g., multiple mocks that cover specific tag combinations)
* write an internal log of all calls to it, especially arguments passed and outputs requested, using private scitype defining methods like `_fit` and `_predict`

The logs can then be retrieved in tests to see what pieces of code interacting with the mock are doing.

Two use cases for this:
* testing the base classes, by checking how the base class interacts with methods of the child class, like `_fit` and `_predict`
* testing compositors, by checking how the composite interacts with components, a special case is #2089

---

- [ ] @ltsaprounis agreed to create a forecaster mock

**Comment by ltsaprounis** [comment]
Not really a mock but, a while back I implemented a `ConstantValueForecaster` where the predictions are all a single number that is a parameter of the forecaster. Did it to illustrate the values that optimise different metrics here:
https://github.com/ltsaprounis/dsf-ts-forecasting/blob/main/notebooks/02-forecasting-metrics.ipynb

Can easily add it here if you think it's valuable. Code is here: 
https://github.com/ltsaprounis/dsf-ts-forecasting/blob/main/dsf_utils/models/_constant_value_forecaster.py

**Comment by fkiraly** [comment]
yes, @ltsaprounis!
The easiest way to create a mock class is probably to take a very simple estimator and add the logging/reporting functionality.

**Comment by fkiraly** [comment]
done via https://github.com/alan-turing-institute/sktime/pull/2197
