### ISSUE TITLE
ROCKET transformer RAM consumption

### ISSUE THREAD

**Issue by RafaAyGar** [alan-turing-institute/sktime#2133]
### **Problem Description**
- ROCKET transformer _apply_kernels function create a dataframe of shape (n_data_instances x n_kernels*2). Leaving the number of kernels as default (=10000) and working with a dataset of 15000 instances, it results in a 300 million cells dataframe which takes around 1.8 GB of RAM. In the same way, for a data of 44k instances it goes over 8 GB of RAM consumption. If we extrapolate this 2 last results for a dataframe of 1 million instances it can consume over 120 GB.

### **Solution**
- The datatype of the dataframe cells is set to float64, we changed it to float32 halving the RAM consumption exposed above.

### **Checking Experiments**
- We tested both versions of ROCKET transformer (with float 64 and float 32) over the same data to check that model output is not changed, obtaining the exact same results but with the RAM consumption half reduced.
- Used datasets (not stratified or resampled):
- - DistalPhalanxOutlineAgeGroup
- - DistalPhalanxTW
- - EthanolLevel
- - MiddlePhalanxOutlineAgeGroup
- - MiddlePhalanxTW
- - ProximalPhalanxOutlineAgeGroup
- - ProximalPhalanxTW
-  Each dataset was tested with 2 Rockets classifiers, one with the random state set to 0, and the other to 1.
- RAM consumption were measured with memory_profiler python module, checking the increment produced on the fit_predict function of the classifiers (that is where ROCKET transformer is executed)

### **Results obtained**
- ROCKET transformer version with float 64:
- - Execution RAM: 79.2 MB
- - **Mean Accuracy Measure of Datasets for the 2 RocketClassifier runs:**
- - - DistalPhalanxOutlineAgeGroup: 0.758993
- - - DistalPhalanxTW: 0.705036
- - - EthanolLevel: 0.594000
- - - MiddlePhalanxOutlineAgeGroup: 0.558442
- - - MiddlePhalanxTW: 0.538961
- - - ProximalPhalanxOutlineAgeGroup: 0.858537
- - - ProximalPhalanxTW: 0.797561
- ROCKET transformer version with float 32:
- - Execution RAM: 47.3 MB 
- - **Mean Accuracy Measure of Datasets for the 2 RocketClassifier runs:**
- - - DistalPhalanxOutlineAgeGroup: 0.758993
- - - DistalPhalanxTW: 0.705036
- - - EthanolLevel: 0.594000
- - - MiddlePhalanxOutlineAgeGroup: 0.558442
- - - MiddlePhalanxTW: 0.538961
- - - ProximalPhalanxOutlineAgeGroup: 0.858537
- - - ProximalPhalanxTW: 0.797561

## Participants:
- RafaAyGar
- @dguijo

**Comment by RafaAyGar** [comment]
@dguijo

**Comment by TonyBagnall** [comment]
Hi, and welcome. This looks useful, I see no downsides, we would welcome the associated pull request

**Comment by RafaAyGar** [comment]
> Hi, and welcome. This looks useful, I see no downsides, we would welcome the associated pull request

Great!
