### ISSUE TITLE
[ENH] Default alpha values

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#2134]
**Is your feature request related to a problem? Please describe.**
DEFAULT_ALPHA = 0.05 today, but defaults in `predict_quantiles` are [0.05, 0.95] which is equivalent to alpha = 0.10. 

https://github.com/alan-turing-institute/sktime/blob/87bdf36dbc0990f29942eb6f7fa56a8e6c5fa7b7/sktime/forecasting/base/_base.py#L375

**Describe the solution you'd like**
Defaults in `predict_quantiles` should be 0.025 and 0.975 to make it consistent with DEFAULT_ALPHA and backward compatible after `return_pred_int` is deprecated in 0.11.0.

**Comment by fkiraly** [comment]
Hmmm - I admit this may be confusing now.
I´m not sure there is an inconsistency and I thought we did the refactor in a downwards compatible way.

There are a number of quantities in play here, for predictive quantiles and intervals:
* the `coverage` of a symmetric predictive interval
* the lower quantile point of a symmetric predictive interval, `alpha_low`, corresponding to the "lower" end value (the quantile at `alpha_low`)
* * the higher quantile point of a symmetric predictive interval, `alpha_high`, corrdsponding to the "upper" end value (the quantile at `alpha_high`)
* the significance level `p` arising from a symmetric predictive interval if containedness is the null

For the same interval, assuming symmetry, the relations are as follows:
* `coverage = 1-p`
* `coverage = alpha_high - alpha_low`
* `alpha_high = 1 - alpha_low` (symmetry)

The "old" `DEFAULT_ALPHA`, to the best of my understanding, was (somewhat confusingly) implemented as `alpha_low` in most of the cases. Unfortunately, this was nowhere properly documented, only now we have proper docstrings that explain what `alpha` and `coverage` are, mathematically.

The "old" `DEFAULT_ALPHA` of `0.05` (`alpha_low` above) corresponds to a `coverage` of 0.9, and quantile points `alpha_low = 0.05`, `alpha_high = 0.95`.

That would be downwards compatible choices of defaults?

**Comment by ngupta23** [comment]
@fkiraly - What might be helpful is to get the equivalent of what Hyndman uses [here](https://otexts.com/fpp3/prediction-intervals.html).

> The hilo() function converts the forecast distributions into intervals. By default, 80% and 95% prediction intervals are returned, although other options are possible via the `level` argument.

## Level
What does `level` correspond to in sktime terminology?

Is `level` in Hyndman's language = `coverage` in sktime language?

## Hilo
What would be equivalent of `hilo 80` and `hilo 95` using `predict_interval` and `predict_quantiles` in sktime?

Would `hilo 80` be equivalent to `predict_interval(coverage=0.9)` and `predict_quantiles(alpha=[0.1, 0.9])`?
Would `hilo 95` be equivalent to `predict_interval(coverage=0.95)` and `predict_quantiles(alpha=[0.025, 0.975])`?



![image](https://user-images.githubusercontent.com/33585645/155537464-32970f58-afc0-4b81-a056-41d0c53cf787.png)

**Comment by fkiraly** [comment]
Yes, I think this is all correct.
Once we have `predict_proba` implemented, you can also just call the quantiles methods on the distribution, but using `predict_interval` is more direct.

**Comment by ngupta23** [comment]
Thanks for clarifying. I will close this for now.
