### ISSUE TITLE
Using data in NumPy arrays

### ISSUE THREAD

**Issue by madarax64** [alan-turing-institute/sktime#217]
Hello,
I'd like to use data in NumPy arrays with the ContractedShapeletTransform. Somehow, there seems to be a hard dependency on Pandas, and to be honest I couldn't really understand from the documentation how to massage my data to be in the form Sktime expects. Could you perhaps provide a short code snippet showing how this could be done? I think this would be a good idea because NumPy arrays are flexible and many times we're not working with .ts or .tsv files - all we have are arrays of numbers.

Thanks!

**Comment by mloning** [comment]
Thanks for raising the issue! 
* I'd suggest you take a look at the [shapelet classification example notebook](https://github.com/alan-turing-institute/sktime/blob/master/examples/shapelet_transform.ipynb) and inspect the `train_x` data container to better understand the expected input data format in sktime,
* For univariate panel data stored in a 2d numpy array with column representing time points, the [`detabularise`](https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/data_container.py) method could help you to get to the required input format,
* To find out more about why we chose this data representation, take a look at this [wiki entry](https://github.com/alan-turing-institute/sktime/wiki/Data-representation-in-sktime),
* We're also currently revising our data container in [this companion repo](https://github.com/sktime/data-container) in case you're interested in contributing. 

I hope this helps, if not, it'd be helpful if you could provide more details on how exactly you're storing your data in a numpy array.

**Comment by madarax64** [comment]
Hello @mloning,
Thanks for your response. I looked at the notebook and figured something out, so I wrote a small helper function (more on that in a moment) to solve my problem.

Specifically, consider if we have a numpy array declared as a = np.array([1,2,3,4]), representing some time series sampled at regular (arbitrary) intervals. So this instance as a shape of (4,). Usually, we have a number of such series, say 100, so the resulting collection would have a shape of (100,4); 100 representing the number of instances, 4 representing the (temporal) length of each instance. This is a pretty common way to find or use custom data for time series analysis. So in a nutshell, I'm looking for a simple and direct way to use data in such a structure/form with sktime. 

On the other hand, I hacked together a small helper function to help solve my problem. Would you like me to share it or perhaps create a pull request?

Regards

**Comment by mloning** [comment]
I'm happy to take a look at your helper function! 

With the `detabularise` function mentioned above you should also be able to do this, something along these lines should work for you I believe:
```python
import numpy as np
import pandas as pd
from sktime.utils.data_container import detabularise

a = np.random.random(size=(100, 4))
b = pd.DataFrame(a)
c = detabularise(b)
```

* One issue is however that this currently only works on univariate data but not multivariate data, so extending the detabularise function to handle this would be great.  
* Improving the documentation would also be very helpful I believe.

**Comment by mloning** [comment]
I'm closing this now as I think it's been resolved. @madarax64 please get in touch if you're interested in contributing!

**Comment by madarax64** [comment]
@mloning Sure! Sorry, I actually thought I'd closed this. Thanks for the info, and I'll be looking at the data container repo to see if I can give a hand there. Thanks again!
