### ISSUE TITLE
[ENH] Add interface to nixtla AutoARIMA

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#2181]
**Is your feature request related to a problem? Please describe.**
AutoARIMA from statsmodels is quite slow. 

**Describe the solution you'd like**
A faster alternate was recently released by [Nixtla](https://github.com/Nixtla/statsforecast). Add this as an extension to `sktime`

**Describe alternatives you've considered**
None

**Additional context**
Currently it has a copyleft license. This needs to be resolved in order to be added. See [discussion here].(https://www.linkedin.com/feed/update/urn:li:activity:6902012650709204992?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6902012650709204992%2C6902192208720617472%29)

![image](https://user-images.githubusercontent.com/33585645/157331210-88311192-21e2-4a9a-80cd-7503e7c86306.png)

**Comment by ngupta23** [comment]
Tracking the license issue here: https://github.com/Nixtla/statsforecast/issues/62

**Comment by aiwalter** [comment]
thx for oopneing this issue @ngupta23

**Comment by markvrma** [comment]
I would like to work on this.

**Comment by fkiraly** [comment]
I believe @fede (one of the developers) is already working on this - but perhaps he'd like some assistance?
@fede, how is it going?

**Comment by FedericoGarza** [comment]
Hi @fkiraly @markvrma! I've opened a PR: #2251. If you have comments on the PR @markvrma, they are welcome. :)

**Comment by fkiraly** [comment]
Merged, hence done.
