### ISSUE TITLE
[BUG] rename `same_cuttoff` to `same_cutoff` in `_make_hierachical`

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2192]
Not a bug, strictly speaking, but a naming consistency problem.

`same_cuttoff` should be renamed to `same_cutoff` in `_make_hierachical`, to be consistently named with `cutoff` in `BaseForecaster`.

This should be done before 0.11.0, where it can be done without deprecation.

**Comment by cdahlin** [comment]
Hi @fkiraly, I'm on this.
