### ISSUE TITLE
[BUG] odd failure in `fh._coerce_to_period` that occurs only on windows, in context of hierarchical forecast

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2194]
When making hierarchical forecasts on default output of `_make_hierarchical`, `fh.coerce_to_period` fails, on a windows run:
https://github.com/alan-turing-institute/sktime/runs/5503723513

This is quite strange, and I cannot reproduce the behaviour locally on my windows machine (python 3.8 or 3.9).

It looks like `freq` is not correctly preserved in subsetting from a hierarchical multi-index ... but only under specific conditions on a windows system???

Expected behaviour: the test does not fail, just like on linux/max and as on my local system.

**Comment by fkiraly** [comment]
any good ideas from those who have recently looked at `fh` or `freq`?
@khrapovs, @eenticott-shell, @k1m190r?
I'd give this bug high priority due to the hierarchical functionality attached to it.

**Comment by fkiraly** [comment]
suspicion: `get_cutoff(_make_hierarchical())`, for some reason, results in a time stamp without the `freq` attribute. Why, and why specifically on windows? On my local system, the `freq` attribute is not lost.

**Comment by ltsaprounis** [comment]
Might be a data types issue, I'll look into it!
