### ISSUE TITLE
Improved error messaging in transformers (and likely other places)

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#2202]
https://github.com/alan-turing-institute/sktime/blob/87bdf36dbc0990f29942eb6f7fa56a8e6c5fa7b7/sktime/transformations/base.py#L313

This is the current error message that I get. I suspect that the list concatenation is not happening as intended. It would be nice to improve the error message by handling the list of allowed values appropriately.

```python
ValueError: ["X must be a pandas.Series, found <class 'NoneType'>", "X must be a pandas.DataFrame, found <class 'NoneType'>", "X must be a numpy.ndarray, found <class 'NoneType'>", "X must be a pd.DataFrame, found <class 'NoneType'>", "X must be a numpy.ndarray, found <class 'NoneType'>", "X must be a pd.DataFrame, found <class 'NoneType'>", "X must be list of pd.DataFrame, found <class 'NoneType'>"]
```

May need to be modified here: 

https://github.com/alan-turing-institute/sktime/blob/87bdf36dbc0990f29942eb6f7fa56a8e6c5fa7b7/sktime/datatypes/_check.py#L170

**Comment by fkiraly** [comment]
hm, what are you trying to do, can you post code?

**Comment by ngupta23** [comment]
Honestly, I don't recall now. I think X was None and it gave that message. I think it is just a print issue. It is not concatenating the allowed types correctly.

**Comment by fkiraly** [comment]
ah, I see. No, it was not a print issue, the wrong error message was returned - for some reason, I had it return an internal error message instead of the correct one (like in forecasting). The correct message should be
```
            msg = (
                "X must be in an sktime compatible format, "
                "of scitype Series, Panel or Hierarchical, "
                "for instance a pandas.DataFrame with sktime compatible time indices, "
                "or with MultiIndex and lowest level a sktime compatible time index. "
                "See the forecasting tutorial examples/01_forecasting.ipynb, or"
                " the data format tutorial examples/AA_datatypes_and_datasets.ipynb"
            )
```

Do you think this is clear?

**Comment by ngupta23** [comment]
Thanks @fkiraly . That should be fine. It would be nice to also print what type of X was passed also. It will help with debugging. Thanks!

**Comment by fkiraly** [comment]
>It would be nice to also print what type of X was passed also. It will help with debugging. 

Well, that might be impossible - the user can pass whatever `X` they like - or they can pass a `pd.DataFrame` which does not comply with the specification.

How about extending the error message:
```
            msg = (
                "X must be in an sktime compatible format, "
                "of scitype Series, Panel or Hierarchical, "
                "for instance a pandas.DataFrame with sktime compatible time indices, "
                "or with MultiIndex and lowest level a sktime compatible time index. "
                "See the data format tutorial examples/AA_datatypes_and_datasets.ipynb"
                "If you think X is already in an sktime supported input format, "
                "run sktime.datatypes.check_raise(X, mtype) to diagnose the error, "
                "where mtype string of the type specification you want to pass X as."
            )
```

Do you think this is clear?

**Comment by ngupta23** [comment]
Sounds good. Do you need to make it a fstring? Also, is there anything missing after the last line?

**Comment by fkiraly** [comment]
Implemented here now:
https://github.com/alan-turing-institute/sktime/pull/2314

The error message is longer, it also lists the possible mtype strings that can be used in `check_raise`.

0.11.0 has the first, shorter version from this issue.

**Comment by fkiraly** [comment]
> Sounds good. Do you need to make it a fstring? Also, is there anything missing after the last line?

Yes, of course. It was just meant as a sketch, with the implied understanding that "Franz will fill in the rest".
