### ISSUE TITLE
[BUG] Benchmark of HC2 and HC1 do not match paper results

### ISSUE THREAD

**Issue by baraline** [alan-turing-institute/sktime#2213]
Hi, 

I'm currently running experiments and benchmarking the performance of multiple algorithms used in the SoTA of TSC. During those experiments, i'm consistently getting the results that HC2 is slower than HC1 (using default parameters for both), which contradict the results given in the paper presenting HC2. That is, trying on multiple datasets, with and without using n_jobs>1.

Is this an expected behavior due to some work in progress or something wrong on my side ?

Example results on the Crop dataset with varying number of samples:

|n_samples|RDST              |Rocket            |DrCIF             |HC1              |HC2               |STC              |RDST_std            |Rocket_std          |DrCIF_std         |HC1_std           |STC_std            |HC2_std           |
|------|------------------|------------------|------------------|-----------------|------------------|-----------------|--------------------|--------------------|------------------|------------------|-------------------|------------------|
|225   |0.8935474371537566|0.4801460364833474|18.577583170495927|7848.464765178971|8959.079658895731 |86.56675709038973|0.04171504359692335 |0.010750255547463894|0.3076158696785569|4.683004071004689 |0.43590452894568443|25.00064292922616 |
|450   |1.6947628241032362|0.8065409753471613|24.938918606378138|8360.594130783342|10547.514885107055|243.3796755867079|0.02757885307073593 |0.055771343410015106|0.2900445992127061|18.76490328181535 |1.9626950984820724 |43.63670677691698 |
|675   |2.320853997953236 |0.9106023721396923|44.63115615211427 |8971.236895166337|12217.335100212134|430.5591306462884|0.028325325809419155|0.008519411087036133|1.7223147563636303|35.296641977503896|0.5699807498604059 |29.104480856098235|

The code used to produce my benchmark can be found here :
https://github.com/baraline/convst/blob/main/PaperScripts/benchmark.py

The system i'm running the experiments on :
DELL PowerEdge R730 on Debian 9 with 2 XEON E5-2630 Corei7 (92 cores) and 64GB of RAM

Sktime version : 0.10.1

**Comment by fkiraly** [comment]
For completeness, could you kindly point to the paper, and in there the reference results and reported runtimes, which are discrepant with what you find?

**Comment by fkiraly** [comment]
FTI @TonyBagnall, @chrisholder, @MatthewMiddlehurst

**Comment by MatthewMiddlehurst** [comment]
A massive time sink in HC1 is obtaining the train estimate for STC which is contracted by default. This implementation uses OOB instead of 10-fold CV to get that estimate, which is significantly faster. 

I could return it to the 10-fold CV used originally, but at that point we are intentionally making it worse so it looks slower in comparison to HC2. IMO, note the change in the documentation and leave it.

**Comment by baraline** [comment]
Thanks for the answers : 

@fkiraly  Concerning paper, i'm talking about this one https://arxiv.org/pdf/2104.07551.pdf

@MatthewMiddlehurst So if I understand correctly, the difference we notice in sktime is due to the fact that HC1 is using a OOB rather than a 10-fold CV for the estimate, while when reported in the paper, both used a 10-fold CV ?

A change to the documentation would indeed clear things out, no point in making it worse !

**Comment by MatthewMiddlehurst** [comment]
Most likely, yeah. HC2 replaced all cross-validation with OOB estimates, in the paper we compare against HC1 with 10-fold CV (as that is what was used at the time and in its publication). In sktime both use OOB for both currently because it's a lot quicker.

**Comment by baraline** [comment]
Ok thanks, so the difference we notice in sktime is due to the individual components being "slower" (e.g ROCKET compared to ARSENAL) as both CAWPE with OOB ? 

Sorry if i'm a bit picky but i'm trying to avoid any miss-information being reported in a paper

**Comment by MatthewMiddlehurst** [comment]
The HC2 components individually are slower than those in HC1, but the swap to OOB compensates for that. With HC1 STC using OOB, HC1 is faster than HC2.

**Comment by TonyBagnall** [comment]
hi @baraline, no worries about being picky, we are happy you are looking at HC2! @MatthewMiddlehurst has covered it, introduction of OOB for train estimates for HC2 was one of the redesign features. HC1 was a tidying up of the original HC. STC is a weird one, because time is actually a parameter (how long to randomly sample shapelets) and it is set very arbitrarily at the moment. We are sort of looking at alternatives to set the search time in a more data and model dependent way, but have nothing complete yet.  

We will update the documentation for HC1, dont hesitate to ask if you have any other queries or have found other things that could be clarified

**Comment by baraline** [comment]
Thanks for your detailed answers, to summarize :

- In the paper, HC2 use OOB while HC1 use 10fold-CV, hence why HC2 is faster than HC1 in the paper benchmark
- Currently in sktime, both use OOB, which cause HC1 to be faster  because some of his individual components are faster than those in HC2. This is under the condition that the same time contract is used for STC for both, and that no time contracts are imposed on the other components (as it is the case for the default value if I read the implementation correctly)

If this is correct, I think we can close this issue ! Thanks for the clarifications !
