### ISSUE TITLE
[ENH] ForecastingHorizon support in deep_equals

### ISSUE THREAD

**Issue by ltsaprounis** [alan-turing-institute/sktime#2215]
**Is your feature request related to a problem? Please describe.**
Currently `sktime.utils._testing.deep_equals.deep_equals` doesn't support the `ForecastingHorizon` type.

**Example**
```python
from sktime.utils._testing.deep_equals import deep_equals
from sktime.forecasting.base import ForecastingHorizon
fh_1 = ForecastingHorizon(values=[1,2,3], is_relative=True)
fh_2 = ForecastingHorizon(values=[1,2,3], is_relative=True)
deep_equals(fh_1, fh_2)
# Output: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
# Expected Output: True
```

**Describe the solution you'd like**
We need to add an additional `if` block for `ForecastingHorizon` equality, similar to `numpy.ndarray`, `pandas.Series` etc. 
e.g. https://github.com/alan-turing-institute/sktime/blob/6cc0d41e778f9ed61a5cd8b24a21be680e23dd6f/sktime/utils/_testing/deep_equals.py#L108

**Describe alternatives you've considered**
One alternative fix would be changing `__eq__` in `ForecastingHorizon`. 
This feels a bit more risky.

**Additional context**
Discovered this while writing the tests for #2197.
Related to #2214.

**Comment by fkiraly** [comment]
hm... why the `ForecastingHorizon`'s own `__eq__` result in "truth valus is ambiguous" do you understand that?

**Comment by ltsaprounis** [comment]
It behaves like numpy arrays, pandas Series, Dataframes etc. In most cases this is a feature not a bug. Unfortunately, I don't know enough about the `ForecastingHorizon` to say what the case is here.

**Comment by fkiraly** [comment]
Hm, how about just adding another case, at the end, pseudocode:
``` 
    elif it´s a ForecastingHorizon, then:
    return deep_equals(fh1.values, fh2.values) and fh1.is_relative == fh2.is_relative
    plus deal with the informative return message
```
