### ISSUE TITLE
Refactoring transformers/spectral_based 

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#224]
During an informal code review, I noticed that [transformers/spectral_based.py](https://github.com/alan-turing-institute/sktime/blob/7c95c3d244f53306453c96e3606a27207559331e/sktime/transformers/spectral_based.py) use a custom mechanism to do the same as applying the compositor RowWiseTransformer from sktime.transformers.compose to single-series-transformers would do.

Should this be re-factored?

I believe @jsellier wrote the original version in an early stag of the project where RowWiseTransformer may not yet have existed.

**Comment by mloning** [comment]
Close this in favour of #483
