### ISSUE TITLE
[BUG] StratifiedGroupKFold import breaks pytest discovery

### ISSUE THREAD

**Issue by GuzalBulatova** [alan-turing-institute/sktime#2240]
**Describe the bug**

Pytest discovery fails at `sktime/classification/tests/test_sklearn_compatability.py` when importing 'StratifiedGroupKFold' from 'sklearn.model_selection'

**To Reproduce**

pytest discovery
```python
conda run python /Users/user/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/get_output_via_markers.py /Users/user/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir /Users/user/dev/sktime -s --cache-clear
```

**Expected behavior**

Expected not to get 
```python
sktime/classification/tests/test_sklearn_compatability.py:17: in <module>
    from sklearn.model_selection import (
E   ImportError: cannot import name 'StratifiedGroupKFold' from 'sklearn.model_selection'
```

**Additional context**

`StratifiedGroupKFold` is introduced in the latest stable version of sklearn (1.0.2). Sktime requires version 0.24.0 or higher, but if I install 1.0.2 then other tests (testing sklearn version) fail.
Temporary solution: comment out the import and use of `StratifiedGroupKFold` in `sktime/classification/tests/test_sklearn_compatability.py`

**Versions**
main commit 88c08e92c058b9c83322646744ec0241e2dcaaf5
<details>

System:
    python: 3.8.10 (default, May 19 2021, 11:01:55)  [Clang 10.0.0 ]
executable: /Users/user/opt/anaconda3/envs/sktime-dev/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
          pip: 21.1.3
   setuptools: 52.0.0.post20210125
      sklearn: 0.24.2
       sktime: 0.10.1
  statsmodels: 0.12.2
        numpy: 1.21.2
        scipy: 1.7.1
       pandas: 1.3.4
   matplotlib: 3.4.2
       joblib: 1.1.0
        numba: 0.52.0
     pmdarima: 1.8.2
      tsfresh: 0.18.0

</details>

**Comment by fkiraly** [comment]
@TonyBagnall, the `sktime/classification/tests/test_sklearn_compatability.py` was introduce by you recently, I think?

This prevents test discovery with older versions.

@lmmentel, one thought form this: should we also CI test for tests passing on the combination of oldest versions?

**Comment by TonyBagnall** [comment]
what is the desirable outcome, increase our requirements for sklearn to 1.0 or reduce the code tests to that which is compatible with 0.24 to 1.02? Either fine with me, but we should check nothing else breaks with 1.02, they have a history of random interface changes. FYI, @MatthewMiddlehurst introduced this, not me.

**Comment by fkiraly** [comment]
I would prefer the second - there's always a trade-off between new features and downwards compatibility. In this case, I think the downwards compatibility far outweighs the feature (since it's used only in testing, and the specific cv object does not seem to add much in case coverage).
