### ISSUE TITLE
[ENH] Bagging Forecaster

### ISSUE THREAD

**Issue by ltsaprounis** [alan-turing-institute/sktime#2247]
We can now use the new bootstrapping transformers (`MovingBlockBootstrap`, `STLBootstrapTransformer`) and the new vectorize feature  to implement a `BaggingForecaster` as described in:

1. Bergmeir, C., Hyndman, R. J., & Benítez, J. M. (2016). Bagging exponential smoothing methods using STL decomposition and Box-Cox transformation. International Journal of Forecasting, 32(2), 303-312
2. Hyndman, R.J., & Athanasopoulos, G. (2021) Forecasting: principles and practice, 3rd edition, OTexts: Melbourne, Australia. OTexts.com/fpp3, Chapter 12.5. Accessed on February 13th 2022.

The point prediction should be the mean of the bootstrapped time series predictions and the distributional forecast should be a different [`tfp.distributions.Empirical`](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Empirical) for each time step! 

link to the online version of [2]: https://otexts.com/fpp3/bootstrap.html

**Comment by ltsaprounis** [comment]
FYI - https://github.com/tensorflow/probability/pull/1550
The next release of tensorflow probability will have quantiles implemented for the Empirical distribution so we can then also implement `predict_proba`

**Comment by fkiraly** [comment]
Finally!

I wonder, who is this @ltsaprounis on tensorflow probability who has heroically fixed this long-standing issue?
