### ISSUE TITLE
Implement DirRec strategy for regression forecasting  

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#226]
Implement additional strategy for reducing forecasting to (time series) regression. 

* Existing code is in `sktime.forecasting.reduce.py`
* For a good introduction and description of `DirRec` strategy, see [Bontempi G., Ben Taieb S., Le Borgne YA. (2013) Machine Learning Strategies for Time Series Forecasting](https://www.researchgate.net/publication/236941795_Machine_Learning_Strategies_for_Time_Series_Forecasting)

**Comment by luiszugasti** [comment]
@mloning I'm looking into this. Is it alright?

**Comment by mloning** [comment]
Yes @luiszugasti implementing this would be great!

**Comment by mloning** [comment]
Closed by #779
