### ISSUE TITLE
[ENH] Implement leakage-free imputation methods

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2270]
The `Imputer` transformer has a lot of methods, but only few that are free of information leakage on a test set in the forecasting setting.

The simplest methods are implemented in #2269, but it would be nice to have more:

- [ ] `random_fit` - like `random`, but uses min and max from `fit`
- [ ] `random_empirical` - uses uniform sampling from the series seen in `transform` (this is leakage prone but should be there for completeness)
- [ ] `random_empirical_fit` - uses uniform sampling from the series seen in `fit`
- [ ] `forecaster_fit` - fits forecaster to data in `fit`, and uses `predict` to forecast indices with nan seen in `transform`

Implementation should branch off #2269 if not merged.

**Comment by divo12** [comment]
I wish to contribute on it

**Comment by aiwalter** [comment]
I think we should rather implement this methods it `fit` as I described in the comments of #2269

**Comment by fkiraly** [comment]
resolved by https://github.com/alan-turing-institute/sktime/pull/2382
