### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#228]
## Overview
| Project | Coordinators |
|---|---|
| [Documentation](#Documentation) | @lynnssi, @mloning, @fkiraly | 
| [Time Series Classification](#Time-Series-Classification) | @TonyBagnall, @mloning |
| [Time Series Regression](#Time-Series-Regression) | @TonyBagnall, @mloning |
| [Time Series Clustering](#Time-Series-Clustering) | @TonyBagnall, @fkiraly, @mloning |
| [Forecasting](#Forecasting) | @mloning, @fkiraly |
| [Supervised/Panel Forecasting](#Supervised/Panel-Forecasting) | @mloning, @fkiraly |
| [Time Series Annotation](#Time-Series-Annotation) | @mloning, @fkiraly |
| [Data container](#Data-Container) | @prockenschaub, @mloning, @fkiraly |
| [Development operations](#Development-operations) | @mloning |

## Documentation
| Project | Links | Description | 
|---|---|---|
| User guide | #377 | Develop user guide | 
| Website | | Improve website | 
| Extension guidelines | | Write guidelines for extending sktime | 
| Contributing guide | | Improve guide for contributing to sktime | 
| Reviewer guide | | Add a reviewer guide to our contributing guide, see e.g. this [blog post](https://rgommers.github.io/2019/06/the-cost-of-an-open-source-contribution/), [Turing Way chapter](https://the-turing-way.netlify.app/reproducible-research/reviewing.html), [Software Construction on MIT OpenCourseWare](https://ocw.mit.edu/ans7870/6/6.005/s16/classes/04-code-review/index.html), [eScienceCentre guide](https://guide.esciencecenter.nl/#/best_practices/code_review) | 
| Glossary | #363 | Add glossary of common terms | 
| Docstrings | | Improve docstrings |
| Blog posts | | Write blog posts |

## Time Series Classification
| Project | Links | Description | 
|---|---|---|
| Multivariate data | | Extend algorithms to handle multivariate data | 
| Parallelization | #381 | Parallelize algorithms using joblib or numba | @mloning |
| Unequal length data | #230 | Extend algorithms to handle unequal length data |
| New algorithms | #259 | Add new algorithms |
| Data simulators | #353 | Add data simulators for unit testing and algorithm explanation/interpretability | 

## Time Series Regression
| Project | Links | Description |
|---|---|---|
| Refactor time series classifiers | #212 | Refactor time series classifiers into time series regressor | 

## Time Series Clustering
| Project | Links | Description |
|---|---|---|
| 2nd degree transformer framework | #52, #105 | Design and implement 2nd degree transformer framework | 
| New algorithms | | Add new clustering algorithms based on scikit-learn's implementation and sktime's time series distances | 
| New distances | | Add new time series distances |

## Forecasting 
| Project | Links | Description | 
|---|---|---|
| Multivariate data | | Extend algorithms to handle multivariate/exogenous data, add new composition tools for multivariate time series data | 
| New algorithms | #220 | Add new algorithms | 
| Prediction intervals | | Extend algorithms to compute prediction intervals |
| Fitted parameter interface | | Extend algorithms to support fitted parameter interface | 
| Interface algorithms | | Interface algorithms from existing packages |
| Data simulators | #353 | Add data simulators for unit testing and algorithm explanation/interpretability | 

## Supervised/Panel Forecasting
| Project | Links | Description | 
|---|---|---|
| API design | #66 | Design supervised forecasting API based on pysf | 

## Time Series Annotation
| Project | Links | Description | 
|---|---|---|
| API design | #260 | Design time series annotation API | 

## Data Container
| Project | Links | Description | 
|---|---|---|
| API design | #15 | Design data container interface | 
| Implementation | | Implement data container interface | 

## Development operations 
| Project | Links | Description | 
|---|---|---|
| CI | #196 | Improve continuous integration and development operations |

**Comment by TonyBagnall** [comment]
could you put me down for time series clustering too? Will be doing a bit of that next year with students

**Comment by Raghibshams456** [comment]
@mloning I am hugely interested in this project..was looking for this type project pas few days...I want to contribute in this project in gsoc 2021 as well as after gsoc also..please guide me...
thanx a lot..

**Comment by mloning** [comment]
@Raghibshams456 thanks for reaching out! Please take a look at the GSoC page [here](https://github.com/alan-turing-institute/sktime/wiki/GSoC-2021).

**Comment by mloning** [comment]
Closed in favour of new roadmap planning: https://github.com/sktime/community-org/blob/main/meetups/previous_meetings/20211203-roadmap-planning.md
