### ISSUE TITLE
[DOC] typo in `testing_framework.rst`

### ISSUE THREAD

**Issue by fkiraly-shell** [alan-turing-institute/sktime#2283]
Typo or formatting issue in `testing_framework.rst`, should be easy to fix:

![image](https://user-images.githubusercontent.com/61805342/159671305-25ea136e-a82d-4ee7-9575-a20cd095752d.png)

(this should be a bullet point list, starting at "an `args` parameter")

**Comment by 0saurabh0** [comment]
hi @fkiraly-shell  can i work on this issue?

**Comment by fkiraly** [comment]
sure, thanks!

**Comment by 0saurabh0** [comment]
hey @fkiraly-shell  
only second line has to be modified (adding the bullet ) right??

**Comment by fkiraly** [comment]
Thanks!
