### ISSUE TITLE
[ENH] `WindowSummarizer` inputs for `lag_config`

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#2290]
**Is your feature request related to a problem? Please describe.**
I am sorry, I am not able to find where this was discussed earlier, but I finally got to test this out in 0.10.1. I have some observations and feedback. Please feel free to chime in.

```python
import pandas as pd
from sktime.transformations.series.window_summarizer import WindowSummarizer
from sktime.datasets import load_airline

y = load_airline()
kwargs = {
    "lag_config": {
        "lag": ["lag", [[1, 0], [5, 0]]],
        "mean": ["mean", [[3, 0], [3, -1], [12, 0]]],
        "std": ["std", [[4, 0]]],
    }
}
transformer = WindowSummarizer(**kwargs)
y_transformed = transformer.fit_transform(y)
pd.concat([y, y_transformed], axis=1)[:20]
```

![image](https://user-images.githubusercontent.com/33585645/159787854-6855a567-adbb-45f2-9ea9-5aed51d7bb1a.png)

### Observation 1:

It seems that the window starting is not referenced to the current data point but rather the 1 period prior. So if I want to get the mean of last 3 values (including current value), I need to specify [3, -1]. This seems quite odd. I would have thought [3, 0] would have made more sense, i.e. window size of 3 starting at the current value (0).

If I wanted the window size of 3 starting at prior value, I would specify [3, 1] in that case which again is more intuitive to me.

So in this case, the interpretation would be `[window_length, starting_at (w.r.t **current** data point)]` vs. the way it is implemented which is `[window_length, starting_at (w.r.t **prior** data point)]`.

### Observation 2:

For "lag" feature, the `window length` currently does not have any significance, i.e. `[1, 0]` gives the same results as `[5, 0]`. So instead of `[window_length, starting_at]`, maybe this should be interpreted as `[lag, starting_at]`. With this,

`[1, 0]` would mean the 1st observation prior to current (lag 1 in the true sense of it)
`[5, 0]` would mean the 5th observation prior to the current (lag 5 in the true sense of it)
`[1, 2]` = `[3, 0]` would mean the 1st observation prior to the 2nd observation prior to the current observation (lag 3 in the true sense of it).

I feel this nomenclature is more intuitive, but that is just my opinion. Feel free to chime in if this would be feasible and easier to understand.

**Comment by fkiraly** [comment]
> This seems quite odd. I would have thought [3, 0] would have made more sense, i.e. window size of 3 starting at the current value (0).

Yes, agreed!!

I have had long discussions with @danbartl about this, and he was adamant about that *you* suggested the convention that leads to the "-1". This is quite funny 😆 since your comment confirms it must has been some kind of miscommunication. 

Anyway, we have jointly agreed that we will change it to "0 lag means output = input time series", and that the current situation has the status of a bug because there is such a strong user expectation.
Unfortunately, @danbartl is off sick, so the fix might not make it into 0.11.0.

**Comment by fkiraly** [comment]
(the work is being carried out in this PR https://github.com/alan-turing-institute/sktime/pull/2154)

**Comment by ngupta23** [comment]
Thanks @fkiraly . Yes, it might have been miscommunicated/misinterpreted. But I am glad that the change is happening now. 

Just so we avoid miscommunication again, could you clarify what you mean by the following. I am not sure I follow that.

> "0 lag means output = input time series"

**Comment by ngupta23** [comment]
@fkiraly Also, would this change apply to "Observation 2" as well (for lags) or only for functions like "mean", "median", etc.?

**Comment by fkiraly** [comment]
@ngupta23, regarding observation 1: this is one of those things where you get more confused the more you look at it...
If you had the time, I would much appreciate if you could look into the docstring of the PR
https://github.com/alan-turing-institute/sktime/pull/2154/files
and check whether the indexing is now "right" in your opinion. And/or play around with it.

Re observation 2, indeed, we've discussed that it should be easier to pass lags, without the `window_length` number. I'm not sure whether that's already included in #2154 though.

**Comment by ngupta23** [comment]
@fkiraly I think it is still not consistent with what is proposed in this issue

https://github.com/alan-turing-institute/sktime/pull/2154/files#r835367534

**Comment by fkiraly** [comment]
@danbartl, appreciate your eyes on this once you are back...

**Comment by fkiraly** [comment]
Fixed by https://github.com/alan-turing-institute/sktime/pull/2316
