### ISSUE TITLE
[BUG] `update` of forecasting pipelines does not transform model

### ISSUE THREAD

**Issue by atsangarides** [alan-turing-institute/sktime#2291]
Update by @fkiraly: the root cause of the below is, probably, forecasting pipelines not performing transform in the `update` method. Changed the title to reflect this.

---

**Describe the bug**

`update_predict_single` no longer refits the model in v0.10.1

**To Reproduce**

```python
forecast_horizon=24
cov=0.95
preds, conf_ints = model.update_predict_single(
    y=y_new, X=None, 
    fh=np.arange(1, forecast_horizon+1),
    update_params=True,
    return_pred_int=True, alpha=1-cov
)
```

**Expected behavior**

The model should be refitted when setting `update_params` to True. It seems like the property class `_y` attribute gets updated with the new observations, but the model is not refitted, and predictions returned are just longer forecasts of the originally trained model.

**Additional context**

**Versions**
<details>

System:
    python: 3.8.11 (default, Jan 25 2022, 23:19:55)  [Clang 13.0.0 (clang-1300.0.29.3)]
executable: /Users/tsangis/Projects/uk-ds-day-ahead-prices-forecast/venv/bin/python
   machine: macOS-12.0.1-x86_64-i386-64bit

Python dependencies:
          pip: 22.0.3
   setuptools: 58.0.4
      sklearn: 1.0.2
       sktime: 0.10.1
  statsmodels: 0.13.1
        numpy: 1.21.1
        scipy: 1.7.3
       pandas: 1.4.1
   matplotlib: 3.5.1
       joblib: 1.1.0
        numba: 0.55.1
     pmdarima: 1.8.4
      tsfresh: None

</details>

**Comment by fkiraly** [comment]
>`update_predict_single` no longer refits the model in v0.10.1

Thanks for reporting, @atsangarides!

I briefly looked into the base class, and it does seem that `update_predict_single` calls `update` by default, which calls the inner `_update`. The latter has as default "refitting on the entire data seen so far".

So from a framework perspective, it seems that refitting/updating is hardcoded and also done as a default (if all works as intended).

What could be the case, is that individual models override this incorrectly and don't update despite the interface looking like it would.

So, could you kindly paste some reproducible code, and let us know whether you think it's a particular model, or whether it's a general problem? If you think it's a general problem, can you explain why you think it is?

**Comment by fkiraly** [comment]
Hmmmm - on first glance, there is a lot of composition here, and in a pipeline the "update" is called sequentially. So it would in theory suffice if it is broken in one of the estimators only, or in the compositors (e.g., the pipeline) for it to break overall.

@aiwalter, do you have any obvious idea? Given that it´s using a number of estimators I think you might be familiar with?

**Comment by fkiraly** [comment]
also, quick question, @atsangarides, how do you know it does not refit?

**Comment by atsangarides** [comment]
thanks for looking into this @fkiraly !
I use `prefect` for scheduling daily updates. I did a backfill using bumped sktime `0.10.1` and these are the results (see below). 
I manually tested the code above to investigate, `predict_update_single` is way too fast. `._y` does get appended with new observations, but there is no refit.
![image](https://user-images.githubusercontent.com/42976901/159992134-d2a0e12e-9ff4-4f0d-a9fc-2e5ca2bf7fda.png)

**Comment by fkiraly** [comment]
Ouch - I hope this didn't incur any trading losses 😅 
(I just compulsively had to look up the "IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE" part of our BSD license 😁)

I think I found the error - the `_update` of the `TransformedTargetForecaster` calls `update` of the transformers, but not `transform`! It should be calling, in sequence of the pipeline, `trafo1.update`, `trafo1.transform`, `trafo2.update`, `trafo2.transform`, and passing results of `transform` on to the next `update` and `transform`. But instead, it updates everything on the untransformed data.

**Comment by fkiraly** [comment]
yes, I think it's coming from `TransformedTargetForecaster` and not from the framework. @aiwalter, would much appreciate your (author's) eyes on this, too!

**Comment by fkiraly** [comment]
Btw, I think it's also broken in the `ForecastingPipeline`. Just to confirm whether it's not me getting confused here: the `update` of `trafoN` needs to be called on the output of `transform` of `trafo[N-1]`, and not on the input, does that sound correct?

**Comment by fkiraly** [comment]
attempted fix here: https://github.com/alan-turing-institute/sktime/pull/2296

**Comment by fkiraly** [comment]
> It's just weird that the behaviour of the transformer (/steps) changed over the bump and I couldn't find it.

Are you saying, it changed in one of the versions?

You're right - if the `_update` wouldn't be there in the pipelines, it would just revert to default behaviour and just continue updating by fitting to the entire data (without calling any implemented `update` functionality of the steps).

**Comment by fkiraly** [comment]
> It would not explain why the updating runs in no time, but it would explain why the output is garbage.

I'm noticing, my sentence above give an explanation to the "no time" aspect - calling `update` is usually much faster than a complete refit, so it fits the explanation.

**Comment by fkiraly** [comment]
So, here's a question: tests are not catching this currently, because, even though `update` returns garbage, it returns garbage in the expected data format, which the test think is fine. The tests have no means to pick up a garbage estimator, because the garbage could be intentional and hence "correct". Any good ideas about the testing problem here?

**Comment by atsangarides** [comment]
Oh. Will hold off from changing my pipeline flows then! Was changing to separate fit/predict steps!
Don't know if my suggestion is of any value re tests.. Internally we tend to test transformations.. i.e. using some static/hardcoded data do we get the transformed values we expect. A dead simple series of transformations you can apply and test input<>output data?

**Comment by atsangarides** [comment]
> > It's just weird that the behaviour of the transformer (/steps) changed over the bump and I couldn't find it.
> 
> Are you saying, it changed in one of the recent versions?
> 
> You're right about how that would behave, assuming `_update` was added sometime recently. If the `_update` wouldn't be there in the pipelines, it would just revert to default behaviour specified in the base class framework (`BaseForecaster`), and just continue updating by fitting to the entire data (without calling any implemented `update` functionality of the steps).
> 
> That's computationally more wasteful than calling `update`, but ... at least it's correct ...
> 
> Anyway, I guess we're lucky that we found this 1 day before the new release. If this is indeed the fix, it should be included in the new, much improved 😄 0.11.0 version.

It was working as expected on `0.9.0`

**Comment by fkiraly** [comment]
>A dead simple series of transformations you can apply and test input<>output data?

Yes, we do that in parts of the code base already, most prominently in time series classification.
FYI @MatthewMiddlehurst (we had been discussing this recently).
Perhaps we should also do this in forecasting.

Although it would primarily detect whether the logic of the pipeline has *changed*, not whether it produces *garbage*, so it's not quite the same? Perhaps sth tied to performance monitoring?

**Comment by fkiraly** [comment]
I changed the title of this issue to reflect the root cause bug.

Sadly, this was already reported by @mloning in #1381 and it was completely ignored by all other core devs...
I guess there is a lesson there.

**Comment by ngupta23** [comment]
I wonder if this is related to this one: https://github.com/alan-turing-institute/sktime/issues/2203

**Comment by fkiraly** [comment]
@atsangarides, we've just released 0.11.0, which should contain the fix for your problem.

Based on our discussion, I've also started working on a wrapper that allows you to control how often you refit (instead of update):
https://github.com/alan-turing-institute/sktime/pull/2305

Note that, currently, transformers have an empty update by default and update only if a given transformer implements update.

**Comment by atsangarides** [comment]
@fkiraly Thank you so much! will give it a shot now! You responsiveness is amazing. 
We need to start contributing to sktime... We have some methods wrapping the `evaluate` method for backtesting (what `update_predict` with a CV was supposed to be doing) with pred intervals, plotly visuaisations for easier inspection of longer time series, etc, that I think would benefit other people

**Comment by atsangarides** [comment]
Just checked with `0.11.0`. Observations:

1. Lost the ability to return prediction intervals using the `TransformedTargetForecaster`. Same as #2317 
2. My filter acts on a window, so updating (`update_predict_single(y=y_new_only)`) with say last day's observations (24, which is shorter than the window=168) raises the error below (this goes away if I use `update_predict_single(y=y_old_with_new)
> ValueError: The `window_length` and the forecasting horizon are incompatible with the length of `y`. Found `window_length`=168, `max(fh)`=1, but len(y)=24. It is required that the window length plus maximum forecast horizon is smaller than the length of the time series `y` itself.
