### ISSUE TITLE
[BUG]  ColumnEnsembleClassifier throws `ValueError: The data has unequal length series` when using an estimator that supports unequal lengths

### ISSUE THREAD

**Issue by jyviko** [alan-turing-institute/sktime#2312]
**Issue**
`ColumnEnsembleClassifier` complains when adding estimators that have unequal lengths. For example I am using a `TimeSeriesForestClassifier` classifier with unequal lengths and I am getting:
`ValueError: The data has unequal length series, this classifier cannot handle unequal length series`

**To Reproduce**

```python
import pandas as pd
import numpy as np
#sktime
from sktime.classification.compose import ColumnEnsembleClassifier
from sktime.classification.interval_based import TimeSeriesForestClassifier
a = pd.Series(np.arange(100,200))
b = pd.Series(np.arange(200,500))
c = pd.Series(np.arange(500,550))


X = pd.DataFrame({'x': [a,b,c], 'y': [2*a,3*b,4*c]})
y = np.array([1,2,3])

clf = ColumnEnsembleClassifier(
    estimators=[
        ("TDE0", TimeSeriesForestClassifier(), [0]),
        ("TDE1", TimeSeriesForestClassifier(), [1]),
    ],
    verbose=True,
)
clf.fit(X,y)
```
The above throws:
```
ValueError: The data has unequal length series, this classifier cannot handle unequal length series
```
**Additional context**
When adding: 
``` python
clf.set_tags(**{"capability:unequal_length": True})
```
before clf.fit we get:
``` python
ValueError: all input arrays must have the same shape
```

**Versions**
<details>

System:
    python: 3.9.10 (main, Jan 15 2022, 11:48:04)  [Clang 13.0.0 (clang-1300.0.29.3)]
executable: /Users/kourtis/Sources/shotgun/venv/bin/python
   machine: macOS-12.2.1-x86_64-i386-64bit

Python dependencies:
          pip: 22.0.4
   setuptools: 59.2.0
      sklearn: 1.0.1
       sktime: 0.10.1
  statsmodels: 0.13.1
        numpy: 1.21.5
        scipy: 1.7.2
       pandas: 1.1.5
   matplotlib: 3.5.0
       joblib: 1.1.0
        numba: 0.55.1
     pmdarima: None
      tsfresh: 0.18.0

</details>

**Comment by fkiraly** [comment]
Yes, this is a bug, and I can confirm this.

The behaviour should be as follows:
if `ColumnEnsembleClassifier` is constructed with classifiers, all of which can deal with unequal length data, the tags should indicate the composite also can.
The default should probably also be "can handle", so the compositor is found when searching for classifiers which can handle unequal length data.

**Comment by k1m190r** [comment]
I'm looking at it

**Comment by fkiraly** [comment]
@jyviko, what you report is not a bug, but intended behaviour, indeed, because TSF does not support unequal length data.

However, this should work instead, but it actually doesn't:

```python
import pandas as pd
import numpy as np
#sktime
from sktime.classification.compose import ColumnEnsembleClassifier
from sktime.classification.interval_based import TimeSeriesForestClassifier
from sktime.transformations.panel.padder import PaddingTransformer

a = pd.Series(np.arange(100,200))
b = pd.Series(np.arange(200,500))
c = pd.Series(np.arange(500,550))


X = pd.DataFrame({'x': [a,b,c], 'y': [2*a,3*b,4*c]})
y = np.array([1,2,3])

pad = PaddingTransformer()
tsf = TimeSeriesForestClassifier()

clf = ColumnEnsembleClassifier(
    estimators=[
        ("TDE0", pad * tsf, [0]),
        ("TDE1", pad * tsf, [1]),
    ],
    verbose=True,
)
clf.fit(X, y)
```

The reason it does not work is bugs with `ColumnEnsembleClassifier` which I just fixed here.
Indeed, `ColumnEnsembleClassifier` could not handle unequal length data!

**Comment by jyviko** [comment]
@fkiraly thank you for the update and effort. I am glad you were able to resolve this although I misreported the issue. I will test this the soonest: )
