### ISSUE TITLE
[ENH] AutoETS: heavy random fluctuations in interval predictions - investigate random seed and correctness

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#2315]
Update by @fkiraly: the below is not a bug, but a consequence of what seems like quite serious random variation in the prediction intervals and quantiles produced by `AutoETS`.

It may be useful to investigate whether:
* a random seed can be set in `AutoETS` to allow deterministic comparisons
* whether the prediction intervals should be something different (e.g., variation predicted added to variation in re-sampling the prediction)
* whether this fluctuation implies anything about the correctness of `AutoETS`

---

**Describe the bug**

Followup from ##2275: AutoETS behavior still seems inconsistent in the 0.11.0 release (ARIMA and Theta has to be fixed now).

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.forecasting.ets import AutoETS
y = load_airline()

forecaster = AutoETS(auto=True, n_jobs=-1, sp=12)
forecaster.fit(y, fh=[1,2,3])

# return_pred_int and alpha are disabled in sktime 0.11.0
# forecaster.predict(return_pred_int=True, alpha=0.05)
forecaster.predict()

forecaster.predict_quantiles(alpha=[0.025, 0.05, 0.1, 0.5, 0.9, 0.95, 0.975])

forecaster.predict_interval(coverage=[0.8, 0.9, 0.95])
```

![image](https://user-images.githubusercontent.com/33585645/160263672-3deed4ef-41cb-423a-9218-cab02994230b.png)

**Expected behavior**
Would have expected the point forecast to match 50% quantile and coverage = 80% to match quantiles [0.1, 0.9] and so on. This seems to be the case in ARIMA and ThetaForecaster but not in AutoETS.

**Versions**
<details>

System:
    python: 3.7.13 (default, Mar 16 2022, 17:37:17)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic

Python dependencies:
          pip: 21.1.3
   setuptools: 57.4.0
      sklearn: 1.0.2
       sktime: 0.11.0
  statsmodels: 0.13.2
        numpy: 1.21.5
        scipy: 1.4.1
       pandas: 1.3.5
   matplotlib: 3.2.2
       joblib: 1.1.0
        numba: 0.55.1
     pmdarima: 1.8.5
      tsfresh: None

</details>

**Comment by fkiraly** [comment]
As per discussion in https://github.com/alan-turing-institute/sktime/pull/2320, this is most likely not a bug, but a side effect of how `AutoETS` internally generates prediction intervals, which apparently comes with heavy random variation.

There is currently no way to set a random seed, so I will change this issue into investigating this.

**Comment by ngupta23** [comment]
Closing in favor of #2388 which lays out a potential solution.

**Comment by fkiraly** [comment]
agreed
