### ISSUE TITLE
[BUG] ForecastingPipeline does not implement `predict_quantiles` or `predict_interval`

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#2317]
**Describe the bug**
When using a `ForecastingPipeline`, the checks for prediction interval need to be based on the final forecaster in the pipeline but currently this does not seem to be the case.

**To Reproduce**
```python
from sktime.datasets import load_longley
from sktime.forecasting.theta import ThetaForecaster
from sktime.forecasting.compose import ForecastingPipeline
from sktime.transformations.series.impute import Imputer
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.model_selection import temporal_train_test_split

y, X = load_longley()
y_train, _, X_train, X_test = temporal_train_test_split(y, X)
fh = ForecastingHorizon(X_test.index, is_relative=False)

# This works ----
forecaster = ThetaForecaster()
forecaster.fit(y_train, X_train, fh=fh)
forecaster.predict_quantiles(X=X_test, alpha=[0.05, 0.5, 0.95])

# But this does not ----
pipe = ForecastingPipeline(steps=[
    ("imputer", Imputer()),
    ("forecaster", ThetaForecaster())])
pipe.fit(y_train, X_train, fh=fh)
pipe.predict_quantiles(X=X_test, alpha=[0.05, 0.5, 0.95])
```

```python
RuntimeError: ForecastingPipeline does not implement probabilistic forecasting, but "capability:pred_int" flag has been set to True incorrectly. This is likely a bug, please report, and/or set the flag to False.
```

**Expected behavior**
Would have expected the `ForecastingPipeline` to look at the underlying `ThetaForcester` for capability and run to completion i.e. produce the same results as `forecaster.predict_quantiles(X=X_test, alpha=[0.05, 0.5, 0.95])`. 

**Versions**
<details>
System:
    python: 3.7.13 (default, Mar 16 2022, 17:37:17)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic

Python dependencies:
          pip: 21.1.3
   setuptools: 57.4.0
      sklearn: 1.0.2
       sktime: 0.11.0
  statsmodels: 0.13.2
        numpy: 1.21.5
        scipy: 1.4.1
       pandas: 1.3.5
   matplotlib: 3.2.2
       joblib: 1.1.0
        numba: 0.55.1
     pmdarima: None
      tsfresh: None
</details>

**Comment by fkiraly** [comment]
Special case of https://github.com/alan-turing-institute/sktime/issues/2313

**Comment by fkiraly** [comment]
Actually, this is a special case of
https://github.com/alan-turing-institute/sktime/issues/2088

and not a bug - the reason is "currently not implemented".

**Comment by ngupta23** [comment]
So @fkiraly , will this work eventually or are you suggesting setting the tag for prediction interval to False in `ForecastingPipeline`?
What would be the end state for this?

**Comment by fkiraly** [comment]
The end state would be that `predict_interval` etc works.

The problem is not the tag setting, the problem is that the logic is not implemented.

Help would be appreciated!
For the `ForecastingPipeline`, the logic should be easy - the inner `predict` in the outer `predict` should be replaced by `predict_interval` for the outer `predict_interval` etc, and arguments patched through.

For `TransformedTargetForecaster`, you'd additionally need to inverse transform the lower/upper etc.

**Comment by fkiraly** [comment]
> It is breaking the pipeline we have in pycaret since we can not do prediction intervals anymore.

Is it? Did it work before?

**Comment by ngupta23** [comment]
> Is it? Did it work before?

`return_pred_int` in `predict` (version 0.10.1) worked with the `ForecastingPipeline`. But with the 0.11.0 release, I have to switch to using `predict_intervals` (due to deprecation of `return_pred_int`) and that does not work anymore.

**Comment by ngupta23** [comment]
> For the ForecastingPipeline, the logic should be easy - the inner predict in the outer predict should be replaced by predict_interval for the outer predict_interval etc, and arguments patched through.

@fkiraly What if I add 2 methods here called `_predict_interval` and `predict_quantiles` and replace the return statement with `forecaster.predict_interval` and `forecaster.predict_quantiles` respectively. Is this what you are recommending?

https://github.com/alan-turing-institute/sktime/blob/f06b9b0a43db13e9e0217cc3c7de8f3807d3c722/sktime/forecasting/compose/_pipeline.py#L250

**Comment by fkiraly** [comment]
let me give it a shot

**Comment by fkiraly** [comment]
Here:
https://github.com/alan-turing-institute/sktime/pull/2318

**Comment by ngupta23** [comment]
Wow, @fkiraly that was quick. Could you please apply these changes to TransformedTargetForecaster as well? Thank you do much!

**Comment by fkiraly** [comment]
>  Could you please apply these changes to TransformedTargetForecaster as well? Thank you do much!

That is not as easy, since we need to back-transform the proba outputs. It will also be "correct" only for `_predict_interval` and `predict_quantiles`.

**Comment by fkiraly** [comment]
> Wow, @fkiraly that was quick

And no guarantees that it works at the first attempt.

**Comment by ngupta23** [comment]
> That is not as easy, since we need to back-transform the proba outputs. It will also be "correct" only for _predict_interval and predict_quantiles.

I am only using predict_interval and predict_quantiles for now so that would work if it is available.

**Comment by ngupta23** [comment]
@fkiraly Since #2318 is implemented, can we close this or do you think anything else is pending on this issue? Thanks!
