### ISSUE TITLE
Conflict between the default and documentation value of TimeSeriesForestClassifier.

### ISSUE THREAD

**Issue by ninfueng** [alan-turing-institute/sktime#232]
**Describe the bug**
At the documentation of TimeSeriesForestClassifier, `n_estimators = 100`.
https://github.com/alan-turing-institute/sktime/blob/4dabe1afee0ad180f31c5f585f904f515ab4d0b1/sktime/classifiers/compose/ensemble.py#L48

However, at the constructor, the default value is `n_estimators = 500`.
https://github.com/alan-turing-institute/sktime/blob/4dabe1afee0ad180f31c5f585f904f515ab4d0b1/sktime/classifiers/compose/ensemble.py#L185

**Expected behavior**
All of `n_estimators` should be either all 100 or 500.

**Comment by mloning** [comment]
Hi, thanks for raising the issue, would appreciate a PR!

**Comment by ninfueng** [comment]
@mloning Which one should I change to 100 or 500?

**Comment by mloning** [comment]
I'd change it to 200.

**Comment by ninfueng** [comment]
Just for note, some others values also have the conflicted values as well.

max_features = None (Default), "auto" (Document)
min_impurity_split = None (Default), 1e-7 (Document)
bootstrap = False (Default), True (Document)

Please tell me, the preferred values then, I will try to pull request again.

**Comment by mloning** [comment]
These hyper-parameters go into scikit-learn's decision tree classifier, so I'd use the defaults that they have.

**Comment by ninfueng** [comment]
From sklearn documentation, [DecisionTreeClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html). Their default values are as below:
```
max_features = None
min_impurity_split = None
```
However, `bootstrap` is not appeared in the documentation.
Maybe we should use sktime default value,  `bootstrap = False`, since both previous sktime default values (`max_features` and `min_impurity_split`) are the same as sklearn default values. What do you think about this?

**Comment by mloning** [comment]
The bootstrap argument comes from here: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html, but happy to keep `bootstrap=False`

**Comment by ninfueng** [comment]
I added one more committing into Pull Request #233. I think I will end this issue now if you say so.

**Comment by mloning** [comment]
Thanks for the PR! Let me know if you're interested in contributing towards sktime more generally, we have a few interesting open issues to work on :-)
