### ISSUE TITLE
[ENH] add non-duplicate (multi)index to sktime data specification and input checks

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2331]
We should enforce non-duplicate row and column indices as part of the data specification.

This will need to be ensured in the `_check` functions in the `datatypes` module, and the specifications in the `AA_datatypes_` notebook need to be updated accordingly.

---

Following a suggestion by/discussion with @grzegorzrut in https://github.com/alan-turing-institute/sktime/pull/2325.

We probably want to enforce that there are no duplicate (loc) indices in any `pandas` data containers (rows and columns).
We already enforce that indices are ordered monotonically increasing, but the checks/conversions do not enforce, or guarantee, non-duplicate (loc) indices.

As a matter of fact, probably much of our code would break if passed containers with duplicate indices - and it is currently also not tested.

A design question for the start, for discussion.

For implementation, a check for it would need to be added to the `_check` modules in `datatypes`.

**Comment by fkiraly** [comment]
Ok, I now think it should be - any diverging opinions?

**Comment by GrzegorzRut** [comment]
I believe that there's a [flag](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Flags.allows_duplicate_labels.html) that could help with that.

As a side note, duplicated indices might cause problems in [pandas](https://stackoverflow.com/questions/35084071/concat-dataframe-reindexing-only-valid-with-uniquely-valued-index-objects?noredirect=1&lq=1). I'm working on the extension of the `WindowSummarizer` to time windows/lags and can't get rid of these errors for some reason - will write about it in the nearest future.
