### ISSUE TITLE
[ENH] @lru_cache in ForecastingHorizon is an error for `flake8-bugbear`

### ISSUE THREAD

**Issue by khrapovs** [alan-turing-institute/sktime#2338]
**Is your feature request related to a problem? Please describe.**

Starting from version 22.3.20 of `flake8-bugbear` (https://github.com/PyCQA/flake8-bugbear/releases/tag/22.3.20) `@lru_cache` decorator in `sktime.forecasting.base._fh.ForecastingHorizon.to_relative` and `sktime.forecasting.base._fh.ForecastingHorizon.to_absolute` raises a pre-commit error. Adding `# noqa: B019` silences the warning, but I do not think this is a very sustainable solution.

**Describe the solution you'd like**

Is `@lru_cache` strictly necessary? Is the speed gain so dramatic that it overweights the dangers suggested by flake8? I do not have much experience with caching, so I have no good solution to propose.

**Comment by fkiraly** [comment]
@khrapovs, why does it raise the error?
I thought the B019 specification does this for *class methods*, which makes sense to me since since all objects share it, but this is an *object method* (not a class method), so it doesn't should like it *should* be raised?

**Comment by fkiraly** [comment]
Is that a bug in `flake8-bugbear` then? Since implemented functionality does not seem to comply with the specified functionality.

**Comment by fkiraly** [comment]
Well, it's called *bug*bear, so might be plausible?

**Comment by khrapovs** [comment]
I have asked the question about class methods in https://github.com/PyCQA/flake8-bugbear/pull/218. Let's see what they answer.

**Comment by fkiraly** [comment]
maybe better in an open issue, since closed PR are less well tracked?

**Comment by khrapovs** [comment]
Opened the issue: https://github.com/PyCQA/flake8-bugbear/issues/250

**Comment by khrapovs** [comment]
So, the question was answered. There is no error, no bug. It is only our (or rather my) lack of understanding how caching works in combination with classes and their methods. I see two ways to proceed:

1. At least temporary add `# noqa: B019` comment next to `@lru_cache`. This would allow to make changes in `sktime.forecasting.base._fh` module.
2. Address a deeper issue with caching. Again, is it really necessary? Personally, I can not say.

**Comment by fkiraly** [comment]
The "simple" solution would be to move this to loose functions `to_absolute(fh, cutoff)` and `to_relative(fh, cutoff)` which are then referenced from within the class, no?

**Comment by khrapovs** [comment]
@fkiraly Something like that https://github.com/alan-turing-institute/sktime/pull/2364?
