### ISSUE TITLE
TSF fit process error

### ISSUE THREAD

**Issue by MrNobodyCali** [alan-turing-institute/sktime#234]
When I run the example file `univariate_time_series_classification.ipynb`, I meet a typeError at the code `tsf.fit(X_train, y_train)`. The error is:
> TypeError: _generate_sample_indices() missing 1 required positional argument: 'n_samples_bootstrap'

I have no idea how this happens because I didn't change any codes.

**Comment by mloning** [comment]
Thanks for raising the issues! Check out issue #160, that seems to be very similar. There it was the scikit-learn version which caused the problem. We've fixed that issue, but it hasn't been released yet! So see if you can get it working by downgrade scikit-learn to 0.21.3.

**Comment by MrNobodyCali** [comment]
Thank you for your reply! I set the `bootstrap=False, oob_score=False` to avoid the problem temporarily.
Thanks again!
