### ISSUE TITLE
do you have ability to process categorical data or mixture of categorical and continuous data 

### ISSUE THREAD

**Issue by Sandy4321** [alan-turing-institute/sktime#235]
do you have ability to process categorical data or mixture of categorical and continuous data

**Comment by mloning** [comment]
Could you give a bit more details, i.e. which learning task are you trying to solve, classification, regression or forecasting? 

A few of our methods should work with categorical data, but haven't tested it thoroughly, we'd also be interested in categorical datasets if you can share them.

**Comment by Sandy4321** [comment]
1
it is about classification
2
we'd also be interested in categorical datasets if you can share them.
it was second part of my question to ask you what data can be, but
maybe this
https://www.kaggle.com/c/grupo-bimbo-inventory-demand/data
or try 
search
https://www.kaggle.com/tags/time-series
![image](https://user-images.githubusercontent.com/11426119/77554016-eafa4080-6e8b-11ea-93ca-d03cb2d4ef0d.png)

**Comment by mloning** [comment]
Could you describe what your data looks like?

**Comment by Sandy4321** [comment]
did you find multivariate ts data?
try this 

https://pyts.readthedocs.io/en/stable/generated/pyts.multivariate.transformation.MultivariateTransformer.html

**Comment by Sandy4321** [comment]
when data is mixer of continues and categorical variables for each time sample?
for example data samples are
time t1: red , 0.4 , big , low, 234
time t2: green, 0.8, big, high, 12
time t3: green, 0.1, small, low, 34
etc

you do have example for multivariate ts data classification
then you do understand what multivariate ts data is?
https://github.com/alan-turing-institute/sktime/blob/master/examples/03_classification_multivariate.ipynb
