### ISSUE TITLE
[ENH] Add `tbats` packages to sktime conda recipe

### ISSUE THREAD

**Issue by RISHIKESHAVAN** [alan-turing-institute/sktime#2350]
**Is your feature request related to a problem? Please describe.**
Currently, installing `sktime-all-extras` via `conda` requires the packages - `catch-22`, `pmdarima` and `tbats` to be installed via `pip` as well. Ref: https://www.sktime.org/en/stable/installation.html#installing-sktime-from-conda

However, `pmdarima` and `tbats` are now available on `conda`.  

**Describe the solution you'd like**
Therefore we can proceed to add their dependencies to the sktime conda recipe and reduce the cross dependency on pip.
Additionally, the sktime installation docs also need to be updated as per the changes.

EDIT: `pmdarima` was already part of conda install. So removed it from title.

**Comment by fkiraly** [comment]
as a side note, when this is done, we should make a parallel PR to the `sktime` docs where the reference is updated accordingly. It will remain but only point to `catch-22`.

**Comment by RISHIKESHAVAN** [comment]
@fkiraly As suggested, I have raised PR with the changes in documentation and also updated the issue description. The PR can be merged after the changes in [conda-forge](https://github.com/conda-forge/sktime-feedstock/pull/33) is merged.
