### ISSUE TITLE
[ENH] list tag values in `all_estimators` return table

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2387]
`all_estimators` currently returns tuples/columns (classname, class), but it would be useful to users, e.g., for listing, or for display in the sktime docs, if additional columns return values of certain tags.

I would propose to add an additional `return_tags` argument which can be a str or list ot str of tag names (see `all_tags` for valid tags). Default None which retrieves no tags in addition.

The utility would then return the value of those tags in a tuple (classname, class, tagvalue1, tagvalue2, etc), with tagvalue being empty (None) value if the estimator does not have the tag.

**Comment by miraep8** [comment]
Hey!  I agree this would be a useful change!  I am planning to take a crack at implementing this over the next few days! :)
