### ISSUE TITLE
[BUG] `ThetaForecaster` doesn't work inside `ColumnEnsembleForecaster`

### ISSUE THREAD

**Issue by eenticott-shell** [alan-turing-institute/sktime#2435]
**Describe the bug**
`ThetaForecaster` doesn't work with `ColumnEnsembleForecaster`, the forecasting horizon is not picked up correctly in the underlying forecasters inside the `ColumnEnsembleForecaster`.

**To Reproduce**
```python
import numpy as np

from sktime.forecasting.compose import ColumnEnsembleForecaster
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.theta import ThetaForecaster
from sktime.utils._testing.series import _make_series

y = _make_series(n_columns=3)
y_train, y_test = temporal_train_test_split(y)
fh = np.arange(len(y_test)) + 1
f = ColumnEnsembleForecaster(ThetaForecaster(sp=12))
f.fit(y_train)
f.predict(fh=fh)
```

**Expected behavior**
It should produce an array of predictions for each of the columns. It seems that when computing the drift in the underlying theta forecasters it cannot find the forecasting horizon.

**Versions**
System:
    python: 3.8.12

Python dependencies:
          pip: 21.2.2
   setuptools: 58.0.4
      sklearn: 1.0.2
       sktime: 0.11.0
  statsmodels: 0.13.2
        numpy: 1.21.5
        scipy: 1.7.3
       pandas: 1.4.1
   matplotlib: 3.5.1
       joblib: 1.1.0
        numba: 0.55.1
     pmdarima: 1.8.4
      tsfresh: 0.19.0

**Comment by fkiraly** [comment]
Yes, I have seen the bug before, and I remember that I had fixed it.

The argument of `_by_columns` should be the outer methods, not the inner methods.

It is weird why this is not on main. Perhaps it is in some PR that got stalled because no one reviewed and I forgot it?

**Comment by fkiraly** [comment]
fixed: https://github.com/alan-turing-institute/sktime/pull/2436
thanks for reporting

I hope I can put it in today's hotfix

**Comment by fkiraly** [comment]
@eenticott-shell, could you kindly add the above example as a test specific to `ColumnEnsembleForecaster`, while I work on other things?

**Comment by fkiraly** [comment]
PS, @euanenticott-shell, I sent you a message on the sktime slack
