### ISSUE TITLE
[ENH] UnobservedComponents model as probabilistic forecaster

### ISSUE THREAD

**Issue by juanitorduz** [alan-turing-institute/sktime#2441]
Hey 👋 ! Its seems the `UnobservedComponents` model wrapper (see [here](https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/structural.py)) does not support prediction intervals yet right? I would be nice to have them as I do not think is really hard because of the `statsmodels` implementation.

I can work on this one in the upcoming weeks!

**Comment by fkiraly** [comment]
excellent, that would be really nice!

**Comment by fkiraly** [comment]
Hm, I just looked at it, seems non-obvious to me...
So it´s great you´ve already looked at this!

May I ask you, @juanitorduz, which method or attribute you would be planning to read the proba forecasts off?

**Comment by juanitorduz** [comment]
I actually haven't thought in detail 😂... I just saw there are other algorithms like ARIMA that support this and I was thinking that both come from the state space module from 'statsmodels' so I thought "how hard can it be ?" Let me look into the implementation in detail 🙈

**Comment by juanitorduz** [comment]
So the idea us is to use the existing implementation [statsmodels.tsa.statespace.mlemodel.PredictionResults.summary_frame](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.mlemodel.PredictionResults.summary_frame.html#statsmodels.tsa.statespace.mlemodel.PredictionResults.summary_frame).
