### ISSUE TITLE
[DOC] Broken links in Testing framework overview

### ISSUE THREAD

**Issue by RISHIKESHAVAN** [alan-turing-institute/sktime#2442]
#### Describe the issue linked to the documentation
Many of the links in the Testing Framework Overview page are broken and lead to pages that do not exist.

https://www.sktime.org/en/stable/developer_guide/testing_framework.html

#### Suggest a potential alternative/fix

This is most probably caused by issues in how the links are mentioned in the `.rst` files and need to be fixed.

**Comment by Tomiiwa** [comment]
Hi, I want to work on this.

**Comment by lmmentel** [comment]
Go ahead @Tomiiwa !
