### ISSUE TITLE
[BUG] MrSEQLClassifier missing module on windows install

### ISSUE THREAD

**Issue by MJFlynn** [alan-turing-institute/sktime#248]
**Describe the bug**
Traceback (most recent call last):
  File "C:/Repositories/sktime/sktime/contrib/experiments.py", line 61, in <module>
    import sktime.classifiers.shapelet_based.stc as st
  File "C:\Repositories\sktime\sktime\classifiers\shapelet_based\__init__.py", line 2, in <module>
    from sktime.classifiers.shapelet_based.mrseql.mrseql import MrSEQLClassifier
  File "C:\Repositories\sktime\sktime\classifiers\shapelet_based\mrseql\__init__.py", line 1, in <module>
    from sktime.classifiers.shapelet_based.mrseql.mrseql import MrSEQLClassifier
ModuleNotFoundError: No module named 'sktime.classifiers.shapelet_based.mrseql.mrseql'

**To Reproduce**
Fresh install of sktime on windows.
Run contrib.experiments.py

**Versions**
<details>
Windows-10-10.0.15063-SP0
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
NumPy 1.17.5
SciPy 1.4.1
sktime 0.3.1
</details>

**Comment by mloning** [comment]
Hey, 

This is an issue for @lnthach and was discussed on PR #211. It looks like the issue wasn't fixed, but instead the unit test simply doesn't run any more.

**Comment by mloning** [comment]
When you say installed, did you build and install from dev?

**Comment by mloning** [comment]
All tests passed on Windows after adding the init file.

**Comment by lnthach** [comment]
Thanks @mloning. I ran the tests again and it looked fine on my Windows system as well.

**Comment by MJFlynn** [comment]
Sorry for the slow reply! The new commit has solved the issue for me to. 
Many thanks.
