### ISSUE TITLE
[BUG] Tag translation for fit-in-transform and fit_is_empty not working as intended

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#2493]
**Describe the bug**
My trafo still used the old tag `fit-in-transform: False`, but when I did `my_trafo.get_tag("fit_is_empty")` it returned `True`, so seems translation is not working in this direction. The problem is I guess here:
https://github.com/alan-turing-institute/sktime/blob/68c359f7afd070ce4778cc1e2937b3d92913129f/sktime/base/_base.py#L430
It only translates in one way.

The translation is needed in the `BaseTransformer` here:
https://github.com/alan-turing-institute/sktime/blob/68c359f7afd070ce4778cc1e2937b3d92913129f/sktime/transformations/base.py#L277

**Reproduce**
```python

from sktime.transformations.base import BaseTransformer


class Featureizer(BaseTransformer):
    _tags = {
        "fit-in-transform": False,
        "transform-returns-same-time-index": True,
        "skip-inverse-transform": True,
        "univariate-only": False,
        "X_inner_mtype": ["pd.DataFrame"],
        "y_inner_mtype": ["pd.Series"],
        "scitype:y": "univariate",
        # "fit_is_empty": False,
        # "scitype:X": "multivariate",
    }

    def __init__(self, transformer, fh, suffix=None):
        self.transformer = transformer
        self.fh = fh
        self.suffix = suffix
        super(Featureizer, self).__init__()

    def _fit(self, X, y=None):
        pass


    def _transform(self, X, y=None):
        return X

from sktime.datasets import load_longley
from sktime.transformations.series.exponent import ExponentTransformer
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.model_selection import temporal_train_test_split

y, X = load_longley()
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X)
fh = ForecastingHorizon(y_test.index, is_relative=False)

featureizer = Featureizer(ExponentTransformer(), fh=fh)
featureizer.fit(X_train, y_train)
featureizer.transform(X_test, y_test)
featureizer.get_tag("fit_is_empty")
featureizer.get_tag("fit-in-transform")
```

**Comment by fkiraly** [comment]
I looked into this and I think this is expected behaviour.

Why: `BaseTransformer` has a default set of `"fit_is_empty"` being `True`, so all transformers inherit the tag.
If the tag is available, it is *not* overridden by its alias.

I think this is expected behaviour? Since the "right" tag, if found together with the "old" tag, should have precedence.
Or do you think this is unintuitive?

In any case, simply change the tag to the new one and all should be fine.

**Comment by aiwalter** [comment]
yes I chnged to new one and it works fine.

**Comment by fkiraly** [comment]
ok, so we can close then?
