### ISSUE TITLE
Improve integration testing and automatic unit testing

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#25]
to go with the extension guidelines

should check conformity with interface design and extension guidelines

**Comment by mloning** [comment]
* run `check_estimator` on all estimators on `master` branch

**Comment by mloning** [comment]
Should test for 
* raises specific not-fitted error if predict/transform is called before fit (`check_is_fitted`)
* runs `fit`, `predict` and `score` for classifiers/regressors/forecasters
* runs `fit`, `transform` and `inverse_transform` (if available) for transformers
* raises specific only-univariate-data error on multivariate data
* raises error on wrong input types (i.e. not pandas DataFrame for X)

**Comment by mloning** [comment]
See #218 where I ported the `all_estimators` function from sklearn, currently only works with forecasters, more work needed to include all classifiers.

**Comment by mloning** [comment]
Closed by #246
