### ISSUE TITLE
[ENH] DummyClassifier

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2507]
We should implement a `DummyClassifier`, similar to the one in `sklearn`.
Functionality can be equivalent, except that it should inherit from `BaseClassifier` in `sktime`.

Suggestion: impot `sklearn` `DummyClassifier`, loop through all the inputs and loop through `y`, create some 2D `X` for the `sklearn` classifier which will be ignored anyway.

**Comment by ZiyaoWei** [comment]
If no one objects I am interested in working on it to get my feet wet. Seems like a great first issue!

**Comment by fkiraly** [comment]
Great! Have fun!
Here's the developer guide on adding a new estimator:
https://www.sktime.org/en/stable/developer_guide/add_estimators.html
In this case, we are dealing with a time series classifier, so it should inherit from `BaseClassifier`.
