### ISSUE TITLE
Vector Autoregression

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/sktime#252]
Maybe I missed this, will there be options for vector autoregression?

**Comment by mloning** [comment]
In principle, yes. That would be an extension of the forecasting framework, but we haven't started working on it. 

Would you be interested in contributing? We'd be happy to draft an API design proposal and discuss/review implementations.

**Comment by mloning** [comment]
I've added it to the dev roadmap #228

**Comment by azev77** [comment]
Unfortunately I do my work in Julia & MLJ (in the past R) & am not too familiar w/ TS in python. 
I became interested in sktime bc yesterday I saw a [GSoC project](https://summerofcode.withgoogle.com/projects/#5949928943124480) that will port sktime into MLJ.

I hope sktime will include:
- [ ] the usual [ensemble benchmarks](https://robjhyndman.com/hyndsight/benchmark-combination/)
- [ ] FB [prophet](https://github.com/facebook/prophet)
- [ ] LSTM time series models

**Comment by mloning** [comment]
Thanks for the suggestions! For an overview of what we have currently implemented for forecasting, see this issue #220. For deep learning we have a separate companion package: https://github.com/sktime/sktime-dl. Do you have a list of recommended LSTM models?

**Comment by azev77** [comment]
The only LSTMs I tried is [through Keras in R](https://rpubs.com/jwcb1025/int_rate_lstm). 
I see you already made progress on the components of the ensemble. 
Does SKTime compute the weighted ensemble in the same way as Rob: 
https://robjhyndman.com/hyndsight/benchmark-combination/

**Comment by mloning** [comment]
At the moment we compute the simple mean as used in the M4 study, but I've added other ensembling methods to our forecasting wishlist #220

**Comment by aa25desh** [comment]
Hello @azev77 we are hosting MLJTime project [here.](https://github.com/alan-turing-institute/MLJTime.jl) It will be great to have you for the feedback:)

**Comment by mloning** [comment]
I'm closing this now, discussion can move to the MLJTime project! 🙂
