### ISSUE TITLE
[BUG] ThetaForecaster fails to give prediction intevals for pd.DataFrames

### ISSUE THREAD

**Issue by GrzegorzRut** [alan-turing-institute/sktime#2524]
**Describe the bug**
@fkiraly , yesterday you mentioned that pd.Series should not appear in the code. I feel that this is somehow connected.

I noticed that `ThetaForecaster` is unable to generate the prediction intervals when it's inside a `ForecastingPipeline`. It turns out that the problem is not with the pipeline but with the input being forced to be a `pd.DataFrame`.
The error i'm getting is:
```python
ValueError: Unable to coerce to Series, length must be 1: given 36
```

The problem is connected with the addition of `y_pred` with `sem` in  `_predict_quantiles`, in theta.py.
I'd offer a work around but I'm sure a temporal change of data type is not the best solution;-).

Btw, is it expected that `sem` is a pd.Float64Index instance?

Here's a toy example:
```python
pd.DataFrame([1,2])+pd.Float64Index([.1,.2])
```

**To Reproduce**

```python
import pandas as pd
from sktime.forecasting.theta import ThetaForecaster
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.datasets import load_airline
y = load_airline()
y_train, y_test = temporal_train_test_split(y)

fp = ThetaForecaster(sp=12)
fp.fit(pd.DataFrame(y_train))
fp.predict_quantiles(fh=y_test.index)
```

**Expected behavior**

```python
import pandas as pd
from sktime.forecasting.theta import ThetaForecaster
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.datasets import load_airline
y = load_airline()
y_train, y_test = temporal_train_test_split(y)

fp = ThetaForecaster(sp=12)
fp.fit(y_train)
fp.predict_quantiles(fh=y_test.index)
```
**Additional context**

**Versions**
<details>

System:
    python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:45) [MSC v.1929 64 bit (AMD64)]
executable: C:\Users\Mi\miniconda3\envs\sktime-dev\python.exe
   machine: Windows-10-10.0.22000-SP0

Python dependencies:
          pip: 22.0.4
   setuptools: 62.1.0
      sklearn: 1.0.2
       sktime: 0.11.2
  statsmodels: 0.13.2
        numpy: 1.22.3
        scipy: 1.8.0
       pandas: 1.4.2
   matplotlib: 3.5.1
       joblib: 1.1.0
        numba: 0.53.0
     pmdarima: 1.8.5
      tsfresh: None

</details>

**Comment by fkiraly** [comment]
Bug confirmed, and fixed here: #2529.

The explanation is, likely a typo, a single missing underscore.

A test that would catch this is passing different input types - we need to discuss in the dev meeting how we trade off the increased compute with increased case coverage.

**Comment by fkiraly** [comment]
> Btw, is it expected that sem is a pd.Float64Index instance?

That shouldn´t matter, should it?

**Comment by GrzegorzRut** [comment]
> > Btw, is it expected that sem is a pd.Float64Index instance?
> 
> That shouldn´t matter, should it?

Nah, was just a bit surprised to see something like this.

**Comment by fkiraly** [comment]
> Nah, was just a bit surprised to see something like this.

I guess float would be cleaner, and may be less risky in case addition for exotic types changes or gets deprecated.
But, in the spirit of "keeping PR scopes confined", I haven't changed it.

Maybe @guzalbulatova can shed light on why it's an index?

**Comment by GuzalBulatova** [comment]
I frankly have no idea, it seems like a bug to me, somewhere defaulting to that class perhaps? There shouldn't be anything in Theta itself to require a Float64Index anywhere really. 🤔

**Comment by fkiraly** [comment]
well, it still computes the right thing seemingly, due to dunder magic...

**Comment by GuzalBulatova** [comment]
Let's see how this would work in new version of Theta, I don't fully understand this current implementation. I'll keep this index issue in mind.

**Comment by fkiraly** [comment]
> Let's see how this would work in new version of Theta, I don't fully understand this current implementation.

I thought that line was coming from you?

**Comment by GuzalBulatova** [comment]
No, the new modular version is to substitute this current one and enable enhanced 'autotheta'. This implementation is by big-o if I'm not mistaken
