### ISSUE TITLE
[ENH] lagging transformer

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2526]
Can it be that we don´t have a simple lagging transform?
It seems to be the case (although the `WindowSummarizer` can be "abused" for this).

We should have a `Lag` transformer that can take an integer or timedelta in construction, and all it does is to lag the series by the given lag value, using `pandas.shift`.

Should be pretty straightforward with the transformer extension template - I would recommend implementing it only for `X_inner_mtype = "pd.DataFrame"`, and relying on automatic vectorization for panel and hierarchical data.

One word of caution is that `pandas.shift` is inconsistent between integer and timedelta use, so it should be made consistent and one or the other behaviour should be steered by something like a `keep_index` parameter (I would give it the default `False`).

**Comment by cgoxo** [comment]
Can I work on this issue? I want to know more about this how to proceed.

**Comment by fkiraly** [comment]
great, thanks, of course!

Here is our detail guide on implementing new estimators, in this case it would be a transformer.
https://www.sktime.org/en/stable/developer_guide/add_estimators.html

**Comment by fkiraly** [comment]
@cgoxo, are you still working on this?

**Comment by cgoxo** [comment]
Sorry Sir, I got busy related to my college activities. Now I am free and can work on this problem.

**Comment by fkiraly** [comment]
FYI @cgoxo, I've started here now: https://github.com/alan-turing-institute/sktime/pull/2783
(in case you were still working on it)

**Comment by cgoxo** [comment]
Really sorry sir. I got busy on my end sem exams.

**Comment by fkiraly** [comment]
no worries, no harm done!
