### ISSUE TITLE
[BUG][DOC] API reference on `sktime.utils` module is wrong, outdated, confusing

### ISSUE THREAD

**Issue by mccrinbc-ss** [alan-turing-institute/sktime#2528]
@fkiraly update after discussion below (Apr 22):

The API reference page on the `sktime.utils` module is incorrect:
https://www.sktime.org/en/stable/api_reference/utils.html

Most of the functions aren't even there anymore.
This needs to be updated, preferably urgently.

What should be in the utilities section:

* `sktime.datatypes` functionality `convert`, `convert_to`, `check_is`, `check_raise` for "data processing"
* plotting, that's still in the `utils` module
* `check_estimator` for manual testing
* maybe some of the synthetic data generators, `_make_series`, `_make_panel`, `_make_hierarchical` (in `utils`) and `get_examples` (in `datatypes`)

Sources for this page are in `docs/source/api_reference/utils`

---

**Describe the bug**
I'm looking to work with sktime, but I can't seem to import any of the functions provided in the _utils_ module. 

**To Reproduce**
I created a brand new venv with sktime version 0.11.2. 
1. python3 venv 
2. pip install sktime

There were no issues the popped up during installation. 

**Environment**
Linux pop-os 5.13.0-7620-generic Ubuntu  x86_64 x86_64 x86_64 GNU/Linux

When I go to import sktime.utils.from_nested_to_2d_array, I receive the following error: 
AttributeError: module 'sktime.utils' has no attribute 'from_nested_to_2d_array'. 

When I look at what attributes the module has, I get the following: 
![image](https://user-images.githubusercontent.com/83707037/164559890-a848e6ac-668d-4d12-9c46-d444da2089bc.png)

I'm looking to test an implementation of ROCKET using the sktime library, but I have been unsuccessful due to these module errors. Am I doing something incorrect?

**Comment by fkiraly** [comment]
@mccrinbc-ss, that function is not in the `utils` module since ages.
Also, `dir(sktime.utils)` should break unless you are in the wrong directory.
To me this sounds like a messed up installation?

I would suggest one of two things:

* please post reproducible, self-contained code for your bug, e.g., when does rocket try to import this? 
* you can join one of the collab sessions tomorrow and we can have a look at your notebook or code

Re `from_nested_to_2d_array`, if you want that functionality use instead:

```python
from sktime.datatypes import convert_to
convert_to(object, to="numpyflat")
```

**Comment by mccrinbc-ss** [comment]
Oh for real! I was trying to follow what is stated in the API reference for where functions are stored but I guess things have changed and the API reference is not up to date? Where can I find the most up-to-date API reference documentation? I see the following: 
![image](https://user-images.githubusercontent.com/83707037/164756177-c357ec2b-c99d-4ff4-8302-6482b47d48e4.png)

I was only attempting to import the function directly, so I never had and direct issues with ROCKET itself. Sorry for the confusion here. 

The import statement you provided above works fine, so I assume that I have a working installation of sktime. These all seem to be very beginner mistakes :-) Thanks for the support!

**Comment by fkiraly** [comment]
Oh dear!! This is all wrong.
How is this still on the stable API page?

I verified and this page is outdated since probably half a year.
https://www.sktime.org/en/stable/api_reference/utils.html

I will change this issue into a docbug.

**Comment by fkiraly** [comment]
> Where can I find the most up-to-date API reference documentation?

Apologies, it does not exist for this piece of functionality - the auto-generated API has not been updated with the move to the `datatypes` module that happend a while ago.

Until this is fixed (hopefully soon), you can use the docstrings. The content on this page should be as said above:

* `sktime.datatypes` functionality `convert`, `convert_to`, `check_is`, `check_raise` for "data processing"
* plotting, that's still in the `utils` module
* `check_estimator` for manual testing
* maybe some of the synthetic data generators, `_make_series`, `_make_panel`, `_make_hierarchical` (in `utils`) and `get_examples` (in `datatypes`)

**Comment by fkiraly** [comment]
For a tutorial on the functionality mentioned, you can consult this:

https://github.com/alan-turing-institute/sktime/blob/main/examples/AA_datatypes_and_datasets.ipynb

**Comment by fkiraly** [comment]
@aiwalter, perchance, is your upgrade of the automated doc generation here
https://github.com/alan-turing-institute/sktime/pull/2498
also going to fix this?

**Comment by fkiraly** [comment]
@mccrinbc-ss, I think I fixed this now: https://github.com/alan-turing-institute/sktime/pull/2703

**Comment by mccrinbc-ss** [comment]
Fantastic! Thanks for resolving this.
