### ISSUE TITLE
[BUG] `FileNotFoundError` - `gfortran` in all CI/CD

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2552]
PRs error out on windows CI with this, since recently:

`FileNotFoundError: Could not find module 'C:\Miniconda\envs\test\lib\site-packages\scipy\.libs\libbanded5x.TNNMG3IXHGJK7NIBT5J6YPEO5XWTOQAJ.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

Unclear what is causing it, likely some package upgraded recently (within the last 12 hours)?

PR for diagnostic runs of CI here: #2550

This needs to be solved before we can make the 0.11.3 release :-(

**Comment by lmmentel** [comment]
I can only see breaking CI runs on windows with conda, seems to be a conda related issue.

**Comment by lmmentel** [comment]
I found this discussion that suggests changing the conda channel for installing scipy https://github.com/pytroll/satpy/issues/1835

**Comment by fkiraly** [comment]
some observations:

* `scipy` coming from `conda-force` seems to have upgraded to 1.8.0 a few days ago - even though the release happened months ago
* this PR https://github.com/alan-turing-institute/sktime/pull/2560 introduces a bound and has `scipy 1.7.3`, but the error still occurs
* switching the `scipy` and `matplotlob` mirror from `conda-force` to `anaconda` here https://github.com/alan-turing-institute/sktime/pull/2561 also ensures `scipy 1.7.3`, and does not seem to suffer from the problem

I do not understand why #2560 does not solve it, but #2561 does.

We should also not close this until we have understood the reason and whether the problem is waiting to happen again once `anaconda` moves up to `1.8.0`.

**Comment by lmmentel** [comment]
How about making the conda deps more transparent and adding an `environment.yaml` with explicit deps, channels and versions?

**Comment by fkiraly** [comment]
good idea - I opened an issue about the general problem this suggestion tries to address here, already:
https://github.com/alan-turing-institute/sktime/issues/2559

**Comment by fkiraly** [comment]
Has been resolved by https://github.com/alan-turing-institute/sktime/pull/2561
