### ISSUE TITLE
[ENH] improvements to changelog generator

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2578]
@lmmentel, THANK YOU for your excellent changelog generator script!

Collecting some improvement suggestions:

* in PR names, single-quotes should be converted to double-quotes, since the rst code environment has double-quotes, and the markdown code environment has single-qupte

**Comment by lmmentel** [comment]
Could you give an example where the quotes should be added?

**Comment by fkiraly** [comment]
it's hard to give an examples directly since quotes are reserved symbols within markdown.

So here is an indirect example: suppose this PR ends up in a change log:
https://github.com/alan-turing-institute/sktime/pull/2597
then we need to change the quotes in its title to double-quotes.

**Comment by lmmentel** [comment]
> Hm, I do not think this was addressed in the PR.

any specifics?

**Comment by fkiraly** [comment]
oh, it was, I am in error. I probably did not update my local `main`.
