### ISSUE TITLE
Implement Sequitur algorithm

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#258]
Sequitur is for processing discrete series, but is commonly used in motif research after a discretisation transform such as SAX. 

Jessica Lin has proposed several ways of using it Nevill-Manning, C., Witten, I.: Identifying hierarchical structure in sequences: a linear time algorithm. Journal of Artificial Intelligence Research 7, 67–82 (1997)

**Comment by fkiraly** [comment]
so every other algorithm is a ... 
...
...
... non-sequitur?

**Comment by mloning** [comment]
I'm actually not sure what this is form, I just cleaned up the repo a bit today and came across a milestone with this in it, so I created an issue, is that from you @TonyBagnall?
