### ISSUE TITLE
[MNT] specify `dtype=float64` in `pd.Series` constructors or most of sktime will break due to `pandas` deprecation

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2614]
Since recently, the following deprecation warning started appearing in many places:

```
FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
```

Due to sensitivity regarding `dtype`, that would mean tests, utilities, or estimators start breaking where construction starts with an empty `pd.Series`.

We need to change instances of the constructor raising the warning.

A list of occurrences can be found in any CI/CD run in more recent PR.

**Comment by khrapovs** [comment]
I took a random recently completed job: https://github.com/alan-turing-institute/sktime/runs/7205042546?check_suite_focus=true. "float64" does not show up in the search. Closed.
