### ISSUE TITLE
[MNT] replace deprecated timestamp.freqstr throughout sktime

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2617]
A very large amount of deprecation messages around `timestamp.freqstr` are raised throughout the CI/CD, especially around the `ForecastingHorizon`:

```
FutureWarning: Timestamp.freqstr is deprecated and will be removed in a future version.
```

We should address this, as the `ForecastingHorizon` is a central object, so it would be catastrophic if it breaks.

At the moment, deprecation seems to be in the future since there is no specified version number yet, but we should prepare and take care of it earlier than later.

**Comment by fkiraly** [comment]
FYI @khrapovs, in case you know how to easily get rid of this.

**Comment by khrapovs** [comment]
I would love to tackle it. I hate warnings. Besides, this is very much related to my #1737.

**Comment by fkiraly** [comment]
I suspected... there are thousands of these!
Unfortunately, I'm not sure what a suitable replace would be in all the cases.

**Comment by khrapovs** [comment]
This is almost duplicate: https://github.com/alan-turing-institute/sktime/issues/1750

**Comment by fkiraly** [comment]
indeed, dupicate of #1750!

Has it already been half a year?

We might want to do sth about this...
