### ISSUE TITLE
[BUG] cross validation does not work with MiniRocket when an integer random_state is used

### ISSUE THREAD

**Issue by k-olsen** [alan-turing-institute/sktime#2625]
**Describe the bug**

An error occurs when a `MiniRocket` model containing a specified `random_state` is used within a function that includes cross validation. If `random_state=None` within `MiniRocket`, no error occurs. 

**To Reproduce**

```python
from sktime.transformations.panel import rocket
from sktime.datasets import load_arrow_head
from sklearn.model_selection import cross_val_score

X, y = load_arrow_head(return_X_y=True)

model = rocket.MiniRocket(
            num_kernels=10000,
            max_dilations_per_kernel=32,
            n_jobs=1,
            random_state=17,)

scores = cross_val_score(model, X, y, cv=5, scoring='f1_macro')
```

Error:
```
File ~/lib/python3.8/site-packages/sklearn/base.py:96, in clone(estimator, safe)
     [95] if param1 is not param2:
---> [96] raise RuntimeError(
     [97] "Cannot clone object %s, as the constructor "
     [98] "either does not set or modifies parameter %s" % (estimator, name)
     [99] )
    [100] return new_object

RuntimeError: Cannot clone object MiniRocket(random_state=17), as the constructor either does not set or modifies parameter random_state
```

**Expected behavior**

Cross validation should not fail if an integer is specified for `random_state`.

**Additional context**

**Versions**
<details>
System:
    python: 3.8.10 (default, Jan 10 2022, 10:11:20)  [Clang 13.0.0 (clang-1300.0.29.3)]
executable: /bin/python
   machine: macOS-12.3.1-arm64-arm-64bit

Python dependencies:
          pip: 22.0.4
   setuptools: 56.0.0
      sklearn: 1.0.2
       sktime: 0.10.0
  statsmodels: 0.13.2
        numpy: 1.21.5
        scipy: 1.7.3
       pandas: 1.4.2
   matplotlib: 3.5.1
       joblib: 1.1.0
        numba: 0.56.0dev0+418.g637a75023
     pmdarima: None
      tsfresh: None

</details>

**Comment by fkiraly** [comment]
This is a known issue which was fixed by PR https://github.com/alan-turing-institute/sktime/pull/2027 and should be in 0.12.0.

Tested your code with the current dev version, no error (python 3.8.12, windows)
