### ISSUE TITLE
[BUG] sktime breaks with new scikit-learn 1.1.X due to private import

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2631]
Someone has been importing private methods again 😠 

This time it's `sklearn` 1.1.0 with `_check_param_grid from sklearn.model_selection._search` being imported in `forecasting/model_selection/_tune`

... breaking much of `sktime`

**Comment by ngupta23** [comment]
From [sklearn github](https://github.com/scikit-learn/scikit-learn)

>scikit-learn 1.0 and later require Python 3.7 or newer. scikit-learn 1.1 and later require Python 3.8 or newer.

@fkiraly Will this be an issue for sktime with python 3.7?

**Comment by fkiraly** [comment]
> @fkiraly Will this be an issue for sktime with python 3.7?

I don't think so, since if you want to install sktime on python 3.7, you end up installing 1.0.2, which still works with sktime, according to the CI/CD.

I.e., you can use future `sktime` versions with the highest 3.7 compatible version of `sklearn` still, you simply are locked in to `sklearn` 1.0.2 or less.

**Comment by ngupta23** [comment]
Sorry, it was a badly phrased question. What I really wanted to ask was whether sktime will support 3.10? Most of the dependencies in pycaret now support this (with the latest release of sklearn) except sktime, so just curious :)
