### ISSUE TITLE
Reading CSV data format

### ISSUE THREAD

**Issue by jmrichardson** [alan-turing-institute/sktime#265]
Hi, sktime looks very interesting.  After reading the docs, it stores data in pandas using a nested format.  I am trying to understand how to load data (for example stock prices) that are in CSV format.  It appears that I have to first convert it to long format, then convert it again to nested format?  Is this correct?  Thanks for any help.

Update: I am hoping there is a way to do a "pandas.read_csv" equivalent in sktime

**Comment by mloning** [comment]
Hi, yes, if you want to do classification or regression, you have to get your data into the nested pandas format. 

If you have univariate time series data, you can also load it into a regular `pd.DataFrame` and then use the `detabularize` function in [`sktime/utils/data_container.py`](https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/data_container.py)

**Comment by fkiraly** [comment]
stock prices doesn't sound like regression/classification though, more like forecasting (depending on the use case, of course). 

In this case, you can directly stick in your time series, and no re-formatting to nested pandas is needed - assuming you construct the right reduction/composite forecaster - see e.g., section 3.3.1 of https://arxiv.org/pdf/2005.08067.pdf or the forecasting example
https://github.com/alan-turing-institute/sktime/blob/dev/examples/forecasting.ipynb
(note: at the moment, you'll need to look on the dev branch for the new interface)

**Comment by fkiraly** [comment]
Also, if you have utility functions lying around for the various data format conversions, these would be quite useful - we appreciate pull requests...

**Comment by Mo-Saif** [comment]
Hi, I created a function that performs the task discussed here. Please feel free to modify it and add it sktime.
```
import pandas as pd
from sktime.utils.data_container import detabularize

def read_univariate_ts(file, window_size, target_distance=1):
    """
    Reads a univariate time-series csv file and converts it to sktime nested format.
    
    Parameters
    ----------
    file : str, path object or file-like object
        pandas compatable path i.e:
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handler (e.g. via builtin ``open`` function) or ``StringIO``.
    window_size : int
        Number of historical values used in each prediction.
    target_distance : int
        The number of steps inthe future you want to predict.
        
    Returns
    -------
    X : pandas DataFrame
        Nested DataFrame with window_size long pandas Series in each row
    y : pandas Series
        The target for each case in X
    """
    
    df = pd.read_csv(file)
    y = df.shift(-target_distance)
    
    lagslist = []
    for i in range(window_size-1, -1, -1):
        lagslist.append(df.shift(i))
        
    X = pd.concat(lagslist, axis =1)
    X = X.iloc[window_size-1:-target_distance]
    X = detabularize(X)
    y = y.iloc[window_size-1:-target_distance].squeeze(axis=1)
    
    return X, y
```

**Comment by mloning** [comment]
@Mo-Saif Thanks! What's the expected file format for the file here? Timepoints in rows?

**Comment by Mo-Saif** [comment]
Yes, one column with timepoints in rows.

**Comment by mloning** [comment]
So if I understand this correctly, you first load a single time series and then turn into a data frame with lagged values using a sliding window approach with a given window length and a target series consisting of the subsequent observation of each window (please let me know if I'm just confused).

If this is what you want to do, it's probably better to separate the loading (`pd.read_csv`) from the data transformation. 

```python
from sktime.forecasting.compose import RecursiveTimeSeriesRegressionForecaster
from sktime.datasets import load_airline
from sktime.regression.compose import TimeSeriesForestRegressor

series = load_airline()  # single pd.Series, could be replaced with a pd.read_csv() call

regressor = TimeSeriesForestRegressor()  # time series regressor

# this is the class to perform the reduction from forecasting to time series regression 
forecaster = RecursiveTimeSeriesRegressionForecaster(regressor=regressor, window_length=10)

forecaster.fit(series)
fcast = forecaster.predict(fh=1)  # single step-ahead forecast

# if you want to see the transformed data set you can run 
X, y = forecaster._transform(series)  # currently hidden method
```

* we have a similar class (`RecursiveRegressionForecaster`) for using sklearn-like tabular regressors
* making the `_transform` method public would be nice, but requires to do some more work on the transformer types and class hierarchy 

I'm happy to guide you through it if you're interested.

**Comment by SaddamHussain84** [comment]
I have also the same issue, my data format looks like this 
**Data description:** First columns user id, from Jan-16 to Dec-16, electricity consumption of different users, inn the end target column showing either customer is healthy or theft.
**Code:**
X_train = pd.read_csv("file.csv")
X_train.head()
![sampledataimage](https://user-images.githubusercontent.com/64782359/97342726-8ee41880-18c1-11eb-9f00-3b72b2db4897.PNG),
**_Conversion into sktime data format:_**
i want to convert it into this file format, please help me
![sktime](https://user-images.githubusercontent.com/64782359/97342779-9e636180-18c1-11eb-9ab6-6c21fe01e443.PNG)
please help, how to do that.

**Comment by mloning** [comment]
There's ongoing work in #478
