### ISSUE TITLE
[ENH] Fourier series components

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2650]
### Discussed in https://github.com/alan-turing-institute/sktime/discussions/2649

<div type='discussions-op-text'>

<sup>Originally posted by **GrzegorzRut** May 16, 2022</sup>
Hi!
I've recently stumbled upon [this](https://robjhyndman.com/hyndsight/longseasonality/) and [this](https://medium.com/intive-developers/forecasting-time-series-with-multiple-seasonalities-using-tbats-in-python-398a00ac0e8a).

As far as I can tell, `sktime` so far does not have functions like [fourier](https://www.rdocumentation.org/packages/forecast/versions/8.16/topics/fourier). We do have the `CosineTransformer` but this can probably be extended to something like the `fourier` function mentioned above. Seems to be really helpful with for long or multiple seasonalities.

Would it be helpful to have something like that? </div>

**Comment by fkiraly** [comment]
Good idea!

Legacy sktime seemed to have a `FourierTransformer`, but I´m not sure where it went. 
Perhaps best to start from scratch...

**Comment by divo12** [comment]
I wish to contribute to this issue

**Comment by fkiraly** [comment]
Excellent, thanks, @divo12!

**Comment by watchcode01** [comment]
i would be glad to contribute to this issue

**Comment by fkiraly** [comment]
Great! What are you planning to implement?

**Comment by bugslayer-332** [comment]
Hi, I am new to open source, and I would love to contribute to this.  Is this issue still open ?

**Comment by bugslayer-332** [comment]
Hi, I am new to open source and would love to contribute to this issue. I am exploring the code base and I am not able to figure out where the CosineTransformer is implemented, any help is appreciated.

**Comment by bugslayer-332** [comment]
@fkiraly can you look into this if possible?

**Comment by fkiraly** [comment]
I think it is in `transformations.series.cos`
