### ISSUE TITLE
[ENH] `make_mock_estimator` should allow passing constructor args for the mocked class

### ISSUE THREAD

**Issue by ltsaprounis** [alan-turing-institute/sktime#2685]
**Describe the bug**

The current implementation of `sktime.utils.estimators.make_mock_estimator` does not allow to pass any arguments to the returned Mock Estimator Class `__init__`. As a result, we can only use it to reproduce the behaviour of the estimator class with it's default arguments.

**To Reproduce**

```python
from sktime.forecasting.naive import NaiveForecaster
from sktime.utils.estimators import make_mock_estimator
from sktime.datasets import load_airline
y = load_airline()
mock_estimator_class = make_mock_estimator(NaiveForecaster)
mock_estimator_instance = mock_estimator_class(strategy=last, sp=1})
```

**Expected behavior**

There should be a way to pass the __init__ arguments of the input estimator class to the mock estimator.

**Comment by fkiraly** [comment]
not a bug, but a missing feature?

**Comment by ltsaprounis** [comment]
> not a bug, but a missing feature?
ok - maybe I was being a bit dramatic calling it a bug

**Comment by fkiraly** [comment]
well, I guess all missing features are bugs in some way 😄
