### ISSUE TITLE
[DOC] Improve Documentation on Imputer method parameter

### ISSUE THREAD

**Issue by robertmcleod2** [alan-turing-institute/sktime#2696]
#### Describe the issue linked to the documentation

[Current Documentation](https://www.sktime.org/en/v0.8.1/api_reference/auto_generated/sktime.transformations.series.impute.Imputer.html)  on the "method" parameter for Imputer is limited, especially with the default method: "drift". It isn't particularly clear what drift does, or the parameters that are used by the sktime.PolynomialTrendForecaster() mentioned.

#### Suggest a potential alternative/fix

A clearer explanation of the "drift" method, to highlight how it differs from "linear", and what parameters are used in the sktime.PolynomialTrendForecaster() for "drift".

**Comment by fkiraly** [comment]
Related PR: https://github.com/alan-turing-institute/sktime/pull/2382 and https://github.com/alan-turing-institute/sktime/pull/2269

I've added some docs in #2269 and have requested @aiwalter to transplant that to #2382, that should solve this issue once actions.
