### ISSUE TITLE
[DOC] Jupyter Notebooks to show cell outputs

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#2746]
#### Describe the issue linked to the documentation
The exmaple notebooks should show the cell outputs. Its much more readable and convenient for users if they can just see the output alreadys and dont need to run it themsels.

#### To do
Execute all notebooks and save outputs.

**Comment by fkiraly** [comment]
hm, good idea - my main worry is the size of the notebook ultimately, and multiple versions cluttering the GitHub repository with large file sizes.

Is there a way to avoid this? E.g., having the binder notebooks execute cells or docs rendering execute cells while the notebooks in the repo are present in their unexecuted forms? More generally, having execution happening between the (empty execution cell) repo notebook and the showcase versions?

**Comment by fkiraly** [comment]
Generally, I agree that the user experience is better with executed cells when inspecting. However, can we have that without compromising repository integrity and the developer experience (i.e., 100s of MB or GB size repo?)

**Comment by lbventura** [comment]
Could it be that some of the example notebooks themselves are too long? For example, _01_forecasting.iypnb_ is very insightful, but split into 3 different large sections. 
By splitting into several notebooks, one could have the executed cells without having too large of a notebook to scroll through - although it has the problem of being a less coherent presentation.

**Comment by lbventura** [comment]
One could bundle the relevant notebooks into a series (parts I, II, III, etc...) that the user can easily shift between.

**Comment by fkiraly** [comment]
> By splitting into several notebooks, one could have the executed cells without having too large of a notebook to scroll through - although it has the problem of being a less coherent presentation.

That would not solve the problem of accumulating repository size due to the images. Every version typically adds a copy of the image.

Splitting the notebooks might make sense, although it might be less clear in terms of user experience that these are intended to be read in sequence. For instance, users currently can start with any of the numbered notebooks.
