### ISSUE TITLE
[BUG] no matches found: [all_extras,dev]

### ISSUE THREAD

**Issue by AurumnPegasus** [alan-turing-institute/sktime#2770]
**Describe the bug**

When trying to install dev dependencies / all dependencies I get:
```
zsh: no matches found: [all_extras,dev]
```

**To Reproduce**

System Specifications:
```
Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish
```

In Bash/Zsh enter:
```bash
pip install -e .[all_extras,dev]
```

**Expected behavior**

Command should be accepted and start installation of required packages. 

**Additional context**

This mostly seems to be a Ubuntu issue since it generally does not recognise special characters in the terminal. With a bit of digging around a simple solution to it is to instead use
```
pip install -e ."[all_extras,dev]"
```
We should update the installation guide with the solution.

**Versions**
<details>

```
>>> show_versions()

System:
    python: 3.9.7 (default, Sep 10 2021, 14:59:43)  [GCC 11.2.0]
executable: /home/shivansh/Desktop/Intern/GSoC/sktime/sktime-dev/bin/python3
   machine: Linux-5.17.5-76051705-generic-x86_64-with-glibc2.34

Python dependencies:
          pip: 20.3.4
   setuptools: 44.1.1
      sklearn: 1.1.1
       sktime: 0.11.4
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.8.1
       pandas: 1.4.2
   matplotlib: 3.5.2
       joblib: 1.1.0
        numba: 0.55.2
     pmdarima: 1.8.5
      tsfresh: 0.19.0

```

</details>

**Comment by fkiraly** [comment]
fixed via https://github.com/alan-turing-institute/sktime/pull/2786
