### ISSUE TITLE
[ENH] [Annotation Workstream] Implement HMM annotation estimator

### ISSUE THREAD

**Issue by miraep8** [alan-turing-institute/sktime#2799]
I am opening this up as an issue for the new annotation/segmentation workstream. 

My plan is to implement a Hidden Markov Model (HMM) estimator for annotation of time series data. You can read more about the algorithm [here](https://en.wikipedia.org/wiki/Hidden_Markov_model), but for a brief overview:

- You want to model a series of variables over time $X$, where $x_t$ represents the variable state at time $t$. 
- Unfortunately, you cannot measure or observe $X$ directly, it is a *hidden* variable, but fortunately you can observe a series of related variables $Y$, where $y_t$ represents your observation of $Y$ at time $t$. 
- You assume both that $y_t$ depends on $x_t$ (and only on $x_t$), and that $x_{t+1}$ depends on $x_t$ but only on $x_t$ (this assumption that each state is only influenced by the state immediately before it is known as a *Markov* assumption).
- One can use the [Baum-Welch algorithm](https://en.wikipedia.org/wiki/Baum%E2%80%93Welch_algorithm) (a special case of EM) to help find the unknown parameters that define the probabilistic relationship that relates $x_t$ and both $y_t$ and $x_{t+1}$.
- If you have defined the distributions that relate $x_t$ to $y_t$ (known as the emission distribution) and $x_t$ to $x_{t+1}$ (known as the transmission distribution) then you can calculate the most likely sequence of $X$ given the observed sequence $Y$ using a variety of algorithms (for example the [Viterbi algorithm](https://en.wikipedia.org/wiki/Viterbi_algorithm#Example))

This is an attractive algorithm for a variety of reasons - its been around for a long time (helped with the lunar landing if I am not mistaken), its a tool that people from a variety of different fields are familiar with, and has good statistical/algorithmic tools to work with it!   

To start with we will work with something that assigns non-overlapping single dimensional labels to univariate time series data (we will expand later, but getting this simple case to work would be nice). This will be a batch, not online approach, and will be an unsupervised algorithm. 

There are two paths forward:

1. one is to integrate [hmmlearn](https://github.com/hmmlearn/hmmlearn).  Its a pretty nice package, has a decent number of users, and what it does it does well.  But, its currently under limited maintenance mode (which *could* present issues in the future?) doesn't necessarily seem to be totally optimized for speed, which could be important for large data sets, and the multivariate case. And there doesn't seem to be a clear path forward for integrating it with other HMM-like algorithms (e.g. MEMM or CRF) other than integrating new libraries.  Could be nice to have it all under one roof. 
2. The path I plan to try out first is to write our own HMM estimator for at least the simple case.  Can we actually make it faster than the vanilla version in `hmmlearn`?  How easy will it be to build on this basic version? 

Will reference PRs/make comments below to update progress. 

@fkiraly @lmmentel

**Comment by fkiraly** [comment]
My recommendation would be to start interfacing `hmmlearn` and see what we can do.

What is the typology of the algorithms above?
As far as I see, vanilla HMM in its simplest form, is:

* when no part of $X$ has been ever observed:
  * the `transform` part of a transformer (unsupervised), when obtaining $X$ from $Y$
  * using Baum-Welch is `fit` of the same transformer
* if $X$ has not been observed, predicting $y_{t+1}$ from $y_t$ is forecasting
* if $X$ has been observed, predicting $y_{t+1}$ from $y_t$ is forecasting with an exogeneous variable observed in $X$
* if $X$ has been observed in `fit`, then inferring $X$ on another series or another part of the series is supervised annotation

**Comment by fkiraly** [comment]
I guess: if $X$ is discrete, we can interpret the labelling as segmentation (into contiguous value segments)

**Comment by fkiraly** [comment]
and, we can use exogeneous data differently - we can use it as part of $Y$, or as part of $X$

**Comment by miraep8** [comment]
So, in my experience, I think the general interpretation for a typical HMM is that $X$ is usually not observed at all, and I think it is quite common for $X$ to be discrete and to be interpreted as a label. 

Usually in an HMM, you are less interested in predicting $y_{t+1}$ from $y_t$.  This is usually because you already have all the $Y$.  What is the interesting data analysis question here is connecting the observed $Y$ to some $X$ "label" or "hidden state" that you would like to assign to the raw data ($Y$). 

Which is just to say I think the first point you raise is closest to the typical use case of an HMM.  One can think of it as a transformation I suppose!  But one can also call it annotation.  I feel the difference is probably mostly semantics, but I think given the typical use case it might make sense for HMM to live in an annotations folder rather than transformations.

**Comment by miraep8** [comment]
And - why start with interfacing `hmmlearn`? 🙃 I was planning on starting with my own implementation as I mentioned above!  I think there are good reasons for doing this, among them the fact I think interfacing `hmmlearn` is always a good fall back strategy, but I think if we start with it we have little motivation to try any alternatives.  And if we try the alternatives we can test against the working version in `hmmlearn` now!  If its not better, we can stick with what they already have. :)

**Comment by fkiraly** [comment]
> What is the interesting data analysis question here is connecting the observed $Y$ to some $X$ "label" or "hidden state" that you would like to assign to the raw data ($Y$). 

I don't agree that this is the *only* interesting question for which one can use HMM. Supervised use is less common, but I think it's quite important in cases where you have some training segmentation labels, in a stream or in a panel setting.
It's just less often presented in random blog posts and online videos (which seemingly almost always talk about the unsupervised annotation/segmentation application).

> I feel the difference is probably mostly semantics, but I think given the typical use case it might make sense for HMM to live in an annotations folder rather than transformations. 

I think I agree.
The more general question here is, "aren't annotators just a kind of transformers?", design-wise and interface-wise.

>And - why start with interfacing `hmmlearn`? 🙃 I was planning on starting with my own implementation as I mentioned above!

Just a very naive cost-benefit calculation.

`hmmlearn` is an existing solution with a good maintainer base and probably optimized, clean implementations of sub-algorithms.
For achieving any goal related to methodological functionality that already is in `hmmlearn`, it seems interfacing has a lower implementation cost and a lower continuously incurred maintenance cost.

I didn't put "enjoyment from implementing an algorithm" on the benefit side, just to say that explicitly 😄 
You could also put "not invented here" on the other side of the balance... https://en.wikipedia.org/wiki/Not_invented_here

**Comment by fkiraly** [comment]
> Alright, I can begin with a naive port.

I think in the end you should make the call, not me.
You should take into account what people are saying, but in the end you ought to weight the options yourself - it´s your GSoC project!

I don´t think there is a strongly compelling argument for either option here, there are pros/cons.

**Comment by miraep8** [comment]
This has now been implemented, though I am in the process of further improving the HMM ecosystem in #3099 Progress on improvement can be tracked there, so closing this issue.
