### ISSUE TITLE
Implement ShapeDTW for TSC

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#284]
**Is your feature request related to a problem? Please describe.**
A recently proposed distance based approach to TSC is called ShapeDTW

https://www.sciencedirect.com/science/article/pii/S0031320317303710

**Describe the solution you'd like**
ShapeDTW is basically a composition of a transformer and DTW. The transformer convert a univariate series into a multivariate one, and the form of DTW employed is DTW_D. This requires
1) implement transformer
2) implement multivariate dependent DTW
this should then slot into the existing structure, we can just wrap the published classifier as a pipeline 
**Additional context**
Vincent Nicholson is doing this as part of his MSc project.

**Comment by Multivin12** [comment]
Yes I'm looking to deploy this algorithm as part of my MSC project

**Comment by mloning** [comment]
Welcome @Multivin12 and thanks for contributing to sktime!

A few tips for contributing:
* you should probably inherit from [`BaseSeriesAsFeaturesTransformer`](https://github.com/alan-turing-institute/sktime/blob/master/sktime/transformers/series_as_features/base.py#L9), the [`RandomIntervalSegmenter`](https://github.com/alan-turing-institute/sktime/blob/57944d5b03b31c7f0d5b8746b1df6642bbe42b6d/sktime/transformers/series_as_features/segment.py#L124) may serve you as a template/starting point
* input and output data type should be a nested pandas data frame, for a quick intro check out our [classification tutorial notebook](https://github.com/alan-turing-institute/sktime/blob/master/examples/02_classification_univariate.ipynb)
* the advanced [installation instructions] will also be useful for running tests, we use pytest, you can simply run `pytest` or `make tests` in the root dir 
* please make sure you comply with a PEP8 style, you can `pip install flake8` and run `flake8 sktime/` in the root dir to see if everything works

**Comment by goastler** [comment]
@Multivin12 if you end up going down the transformer route to convert univariate to multivariate as @jasonlines mentioned you can cache the result in the transformer. Use the index of the panda dataframe row as a key and maintain a map (dict) of row# -> transformed instance. 

I built a cached transformer once upon a time for Proximity Forest so you can try that / use it as a starting point for your shape DTW work: https://github.com/alan-turing-institute/sktime/blob/57944d5b03b31c7f0d5b8746b1df6642bbe42b6d/sktime/classification/distance_based/_proximity_forest.py#L49

Note that it would more elegant for the KNNs to accept multivariate data, but if this is a no go then this should do

**Comment by TonyBagnall** [comment]
hi vincent, I think in the first instance implement shapeDTW as a fixed composition of the shape transform and KNeighborsTimeSeriesClassifier, assuming it can be adapted to work with multivariate. This may be what you are suggesting already! Key thing is to avoid doing the transform in the distance function, as that is unnecessary

**Comment by Multivin12** [comment]
Oh okay thank you all for your help! @TonyBagnall  so just so I understand would that mean writing ShapeDTW as its own class that comprises of the Shape transform and kNeighboursTimeSeriesClassifier? I was thinking that if I wrote shape_dtw as a metric then it would be doing the transform inside the distance function (or doing something hacky inside KNeighboursTimeSeriesClassifier but I want to avoid that).

**Comment by mloning** [comment]
Closed by #287
