### ISSUE TITLE
[BUG] Differencer in TransformedTargetForecaster

### ISSUE THREAD

**Issue by ohbtorres** [alan-turing-institute/sktime#2879]
**Describe the bug**
Using Differencer class in TransformedTargetForecaster causes the following error:
_ValueError: Must supply freq for datetime value_

**To Reproduce**
Trying to use the Differencer class inside the TransformedTargetForecaster, and finish with any forecaster. After that, try to _fit_ the pipeline

```python
pipe = TransformedTargetForecaster(steps=[("diff",Differencer(lags=1)),
                                          ("forecaster", NaiveForecaster())]) 
pipe.fit(time_series)
```

**Expected behavior**
The following error
_ValueError: Must supply freq for datetime value_

**Versions**
0.12.0

`from sktime import show_versions; show_versions()`

System:
    python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)  [GCC 9.3.0]
executable: /opt/conda/envs/previsao_demanda/bin/python
   machine: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.10

Python dependencies:
          pip: 22.0.4
   setuptools: 49.6.0.post20210108
      sklearn: 1.0.2
       sktime: 0.12.0
  statsmodels: 0.13.0
        numpy: 1.21.0
        scipy: 1.7.3
       pandas: 1.2.5
   matplotlib: 3.5.1
       joblib: 0.17.0
        numba: 0.55.1
     pmdarima: 1.8.5
      tsfresh: 0.19.0

**Comment by khrapovs** [comment]
Could you, please, paste a complete code snippet that generates the error? Including imports, `time_series`, etc. Thanks!

**Comment by fkiraly** [comment]
Possible duplicate or homologue of this bug: https://github.com/alan-turing-institute/sktime/issues/2806

**Comment by ohbtorres** [comment]
@fkiraly, that's the same issue

**Comment by fkiraly** [comment]
indeed, confirmed that. Closing this in favour of #2806.
