### ISSUE TITLE
NaiveForecaster docstring does not contain definition for "sp" parameter

### ISSUE THREAD

**Issue by MatteoFelici** [alan-turing-institute/sktime#288]
I noticed that the docstring for the `NaiveForecaster` class does not explain what the `sp` parameter is. I suggest to add it.

**Comment by mloning** [comment]
Thanks for raising the issue! We're refactoring the NaiveForecaster at the moment in #253, but if you like you can open a PR to add it :)

**Comment by mloning** [comment]
Closed by #335
