### ISSUE TITLE
[ENH] Upgrade to Prophet 1.1

### ISSUE THREAD

**Issue by tcuongd** [alan-turing-institute/sktime#2886]
Hello! We recently released v1.1 of Prophet: https://github.com/facebook/prophet/releases/tag/v1.1 which removes the pystan==2.19.1.1 dependency and has binary distributions (python 3.7-3.10) uploaded to PyPI. I think specifying prophet >= 1.1 will make the optional Prophet install a lot smoother.

**Comment by aiwalter** [comment]
@tcuongd thx for update! :)
