### ISSUE TITLE
[BUG] ConformalIntervals wrapped ARIMA/AutoARIMA breaks with default parameters

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2889]
### Discussed in https://github.com/alan-turing-institute/sktime/discussions/2869

<div type='discussions-op-text'>

<sup>Originally posted by **linaamic** June 26, 2022</sup>
Hi everyone, I am currently trying out the ConformalIntervals feature from sktime.forecasting. However, I can't get it to work for both ARIMA and AutoARIMA. Is there an inherent difference between ARIMA forecasters and others? Do I have to call or wrap them differently or is ConformalPrediction not possible with ARIMA?
With other forecasters I have no issues.

This is the error I get:
File "...\site-packages\statsmodels\tsa\statespace\sarimax.py", line 843, in _conditional_sum_squares
    Y = endog[r:]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

Code:
```python
from sktime.datasets import load_airline
from sktime.forecasting.arima import AutoARIMA, ARIMA
from sktime.forecasting.conformal import ConformalIntervals

y = load_airline()
trial_forecaster = AutoARIMA()
conformal_forecaster = ConformalIntervals(trial_forecaster, method="conformal")
conformal_forecaster.fit(y, fh=[1,2,3])
```

Any help is much appreciated! </div>

**Comment by fkiraly** [comment]
FYI @bethrice44

**Comment by bethrice44** [comment]
Have looked into this and it appears to just be too short `initial_window` since auto-arima does some slicing of the data and it  requires more than one data point. The exact number of data points it requires is [defined by r from sarimax](https://github.com/statsmodels/statsmodels/blob/2eac8066b068a88f00a29f8ff728b04e58248375/statsmodels/tsa/statespace/sarimax.py#L820), i.e. it will be `r+1`:

```
    def _conditional_sum_squares(endog, k_ar, polynomial_ar, k_ma,
                                 polynomial_ma, k_trend=0, trend_data=None,
                                 warning_description=None):
        k = 2 * k_ma
        r = max(k + k_ma, k_ar)
    
        ....
    
        Y = endog[r:]
```

I'm not sure if there is an easy way to pre-calculate this for the model. Thoughts @fkiraly?

**Comment by fkiraly** [comment]
Possible solutions I can think of:
* making the default initial window of `ConformalInterval` longer. That does not cover all possible cases (since `r` can be arbitrarily high), but perhaps most cases appearing in actual use
* adding a note or caveat at somewhere in the algorithm description, and/or next to the `initial_window` parameter
?

**Comment by bethrice44** [comment]
Yes. One option is we don't pass `initial_window` at all and we take (say) 5% of the data points as the initial window, as long as it is >= some value. Another option is just adding to the `initial_window` docstring, but I would assume an  `initial_window` of just 1 will always be a poor model and maybe over-estimate the overall interval? I think I need to test this and also check the literature.

**Comment by fkiraly** [comment]
Hmm, I see - your suggestion is to allow `float` for `initial_window`, interpreting this as a fraction, and then leave a fraction as the default?

Makes sense!

Another thing I noticed when I was thinking about the impacts of runtime, `sample_frac` might also be confusing for a user to control, since it is a fraction of a total that the user will not have a grasp of, rather than a parameter that links to absolute runtime. Would a parameter `n_samples` or similar be better to control the runtime here?

**Comment by bethrice44** [comment]
Yes thats right on `initial_window` although may run in to problems if that dataframe passed to the function is small (i.e. we pass 0.05 as `initial_window` fraction and the data only has 10 items say...), so could do something like `max(initial_window*len(y), 1)`, but that wouldn't solve the priblem above if `len(y)` is too small.

On the second point, happy to update it to `n_samples` and I guess default to `n_samples=len(y_index)`

**Comment by fkiraly** [comment]
> On the second point, happy to update it to n_samples and I guess default to n_samples=len(y_index)

Perhaps - I would not remove arguments, but we can make it like in `train_test_split` that accepts multiple types (integers, floats, etc) which are interpreted differently.

We also need to be cautious about deprecations, i.e., all calls to the estimator need to behave the same until version 0.15.0, possibly raising deprecation messages if we want to change the behaviour. But, optimally, we can figure something out so we do not even need to deprecate? Would have to sit down and think about this carefully, but probably you already have a good idea what/how to change?

**Comment by fkiraly** [comment]
This might be another instance of "too small training set": https://github.com/alan-turing-institute/sktime/issues/3194
