### ISSUE TITLE
[MNT] Relax restriction on `cmdstanpy` version or completely remove it from `all_extras` dependencies

### ISSUE THREAD

**Issue by khrapovs** [alan-turing-institute/sktime#2898]
**Is your feature request related to a problem? Please describe.**

`prophet==1.1` is not compatible with `cmdstanpy==1.0.2`. To avoid this problem, the restriction was introduced in this PR: https://github.com/alan-turing-institute/sktime/pull/2887.

**Describe the solution you'd like**

Restriction has to be lifted once the problem is resolved either in `prophet` or in `cmdstanpy`. Ideally, `cmdstanpy` should be removed from `all_extras` as it is a direct dependency of `prophet`.

**Comment by fkiraly** [comment]
... and not one of `sktime`.

**Comment by khrapovs** [comment]
@WardBrian Thanks for reaching out so quick! I think this would be a representative example: https://github.com/alan-turing-institute/sktime/runs/7106816665?check_suite_focus=true

**Comment by aiwalter** [comment]
Hi @WardBrian , thx that you look into it. Here is one of the logs from yesterday: https://pipelines.actions.githubusercontent.com/serviceHosts/4020a5b7-5870-47fe-a430-bbf53b49363a/_apis/pipelines/1/runs/23899/signedlogcontent/18?urlExpires=2022-06-29T12%3A57%3A13.8971983Z&urlSigningMethod=HMACV1&urlSignature=NE3ZS%2FBXgpq2Bp89yaSrhUIKArvq%2FxorOwPVO4Selfo%3D

You have to scroll to the end, there is some `RecursionError` happening: 
```
2022-06-28T20:51:43.0028705Z /opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/cmdstanpy/stanfit/mle.py:56: in __getattr__
2022-06-28T20:51:43.0029163Z     return self.stan_variable(attr)
2022-06-28T20:51:43.0029486Z E   RecursionError: maximum recursion depth exceeded
2022-06-28T20:51:43.0029851Z         attr       = '_metadata'
2022-06-28T20:51:43.0030404Z         self       = <[RecursionError('maximum recursion depth exceeded') raised in repr()] CmdStanMLE object at 0x7f2c21a4f760>
2022-06-28T20:51:43.0030810Z !!! Recursion detected (same locals & position)
```

**Comment by WardBrian** [comment]
It seems like the change to support `.` for variable access made CmdStanPy objects un-pickleable. This should be fixable, but my more general question is if this is necessary behavior for cmdstanpy objects (and things which hold references to them, like Prophet objects)

**Comment by tcuongd** [comment]
Yeah you can reproduce this by trying to copy a fitted Prophet model (which has the CmdStanMLE saved in `m.stan_fit`.

```python
# cmdstanpy==1.0.1

from prophet import Prophet
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/facebook/prophet/main/examples/example_wp_log_peyton_manning.csv')
m_fitted = Prophet().fit(df)
import copy
m_fitted_copy = copy.deepcopy(m_fitted)
```

```python
# cmdstanpy==1.0.2

from prophet import Prophet
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/facebook/prophet/main/examples/example_wp_log_peyton_manning.csv')
m_fitted = Prophet().fit(df)
import copy
m_fitted_copy = copy.deepcopy(m_fitted)

~/.local/share/virtualenvs/cp37-Uo1qYR6O/lib/python3.7/site-packages/cmdstanpy/stanfit/mle.py in __getattr__(self, attr)
     54         """Synonymous with ``fit.stan_variable(attr)"""
     55         try:
---> 56             return self.stan_variable(attr)
     57         except ValueError as e:
     58             # pylint: disable=raise-missing-from

RecursionError: maximum recursion depth exceeded
```

In the Prophet docs we already advise against pickling stan backend objects: https://facebook.github.io/prophet/docs/additional_topics.html#saving-models but I guess `copy` is a common action that people don't associate with pickling and expect to just "work".

**Comment by aiwalter** [comment]
yes its required that its `pickle`-able. In deployment of ML models, its common that `pickle` is used to dump models e.g. by means of `mlflow`. We also have tests to assure our models work well with `pickle`.

**Comment by aiwalter** [comment]
@fkiraly do we actually have a dedicated test for `deepcopy()`? Might be handy to have it

**Comment by WardBrian** [comment]
Would someone be able to run the sktime tests with the current `develop` branch of cmdstanpy? I'd like to confirm all downstream issues here are resolved before releasing the 1.0.3 patch

**Comment by aiwalter** [comment]
@WardBrian 
I have tested on `develop` of `cmdstanpy` and `main` of `sktime` with adjustment of removing the `cmdstanpy` requirement: It has passed! To test I used `pytest -k "Prophet"` which is testing all tests that run on `Prophet` class.

However I get a weird logging error after tests have passed:
```
=============================== 211 passed, 3 skipped, 30349 deselected, 18 warnings in 311.75s (0:05:11) ================================ 
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\miniconda3\envs\cmdstanpy37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
Call stack:
  File "C:\Users\miniconda3\envs\cmdstanpy37\lib\site-packages\cmdstanpy\__init__.py", line 31, in _cleanup_tmpdir
    logging.getLogger('cmdstanpy').info('deleting tmpfiles dir: %s', _TMPDIR)
Message: 'deleting tmpfiles dir: %s'
Arguments: ('C:\\Users\\\AppData\\Local\\Temp\\tmpwnauoazq',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\miniconda3\envs\cmdstanpy37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
Call stack:
  File "C:\Users\miniconda3\envs\cmdstanpy37\lib\site-packages\cmdstanpy\__init__.py", line 31, in _cleanup_tmpdir
    logging.getLogger('cmdstanpy').info('deleting tmpfiles dir: %s', _TMPDIR)
Message: 'deleting tmpfiles dir: %s'
Arguments: ('C:\\Users\\\AppData\\Local\\Temp\\tmpwnauoazq',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\miniconda3\envs\cmdstanpy37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
Call stack:
  File "C:\Users\miniconda3\envs\cmdstanpy37\lib\site-packages\cmdstanpy\__init__.py", line 33, in _cleanup_tmpdir
    logging.getLogger('cmdstanpy').info('done')
Message: 'done'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\miniconda3\envs\cmdstanpy37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
Call stack:
  File "C:\Users\miniconda3\envs\cmdstanpy37\lib\site-packages\cmdstanpy\__init__.py", line 33, in _cleanup_tmpdir
    logging.getLogger('cmdstanpy').info('done')
Message: 'done'
Arguments: ()
2022-06-29 21:41:27,622 - prophet - INFO - Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.        
2022-06-29 21:41:27,632 - prophet - INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
```

**Comment by WardBrian** [comment]
Yeah, that’s an unrelated but annoying bug in Pytest: https://github.com/pytest-dev/pytest/issues/5502

At CmdStanPy we could work around it by either not logging that we’ve cleaned up temp files, or doing this logging with print statements, both of which have drawbacks
