### ISSUE TITLE
Replace gun-point data set in tutorials

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#294]
Thanks to @marielledado for suggesting this. 

* You can find the example notebooks here: https://github.com/alan-turing-institute/sktime/tree/master/examples
* We could replace the gunpoint data set with the arrow head data set used in the [code breakfast tutorial](https://github.com/sktime/sktime-tutorial-pydata-amsterdam-2020) and use the images from there to explain the data set a little bit, 
* We use the gunpoint data set in the following notebooks: 
02_classification, 03_classification, feature_extraction_with_tsfresh, rocket, mrseql, shapelet_transform

**Comment by marielledado** [comment]
Thanks @mloning ! 

I'll start working on 02_classification.

Basically I plan to "preserve" the code from the tutorial notebooks and only take relevant code snippets & explanatory test from the code breakfast notebooks.

**Comment by marielledado** [comment]
03_classification doesn't seem to use the gunpoint dataset. Now working on feature_extraction_with_tsfresh.

**Comment by mloning** [comment]
Oh yes, my bad, that's on multivariate data only!

**Comment by marielledado** [comment]
@mloning Would it be okay to also replace references to GunPoint in the loading_data notebook? This would involve adding new arff and tsv files, which I found for the ArrowHead dataset.

A related question would be, would there be any use for the GunPoint dataset after making all these replacements? If it's essentially obsolete then may be it an be removed from the library altogether?

**Comment by mloning** [comment]
@marielledado Yes, feel free to replace it there as well. 

The only notebook where we use the gun point data set is to explain shapelets based on the published paper and diagram. My impression is that removing it there takes away of the intuition what the algorithm does. Any ideas?

**Comment by marielledado** [comment]
@mloning I did some digging around and found [a paper that used shapelets on a reptile skull dataset](https://pdfs.semanticscholar.org/c505/10c8ccf2a24e98db1ca3b1d34e41a759d286.pdf). The figures are pretty illustrative, but I couldn't find a dataset for it unfortunately. I suppose it would be good for the sample dataset and the illustrations to be the same in the tutorial.

I suppose we could leave the gunpoint in the shapelet notebook for now, then maybe I can email the authors to ask if they can provide the reptile skull dataset?

**Comment by mloning** [comment]
@marielledado Nice work! Perhaps you can find it in [timeseriesclassification.com](http://www.timeseriesclassification.com/dataset.php)? One of the authors is associated with the people who maintain the website and data set repo.

**Comment by marielledado** [comment]
@mloning Nice, I'll give the leaf data set a go.

**Comment by mloning** [comment]
#300 gives some hints on how to add a new data set

**Comment by mloning** [comment]
Closed by #295
