### ISSUE TITLE
[ENH] clean up the `_contrib` folder, aim to remove

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#2942]
There apparently is a `_contrib` folder in `sktime` with ... stuff ... in it.
Tbh it is unclear to me when it was decided that we should have it, what the scope of it is, or how it got populated with a collection of seemingly random content.

I think we need to deal with it, stop putting more random stuff in it, and eventually get rid of it.

* decide what should stay in `sktime` and what should go.
* if stays, move content in appropriate folders, e.g., classifiers in `classification`, docs into documentation, and so on. Ensure content is clean, well-documented, and interface compliant.
* content could also move to different repositories.

FYI @TonyBagnall, what is all this?

**Comment by fkiraly** [comment]
some discussion by @TonyBagnall in the duplicate issue https://github.com/alan-turing-institute/sktime/issues/2947

**Comment by fkiraly** [comment]
added a list of things we should do imo.

FYI @MatthewMiddlehurst, @chrisholder

**Comment by TonyBagnall** [comment]
so I was just going to delete it once we had extracted the sklearn classifiers then you can put anything anyone wants back in later. All of this is experimental or redundant code and what you suggest involves a significant amount of work for very little benefit. But if anyone wants to do as you describe thats great.
