### ISSUE TITLE
[ENH] remove the _contrib package from sktime main, port useful code elsewhere

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#2947]
@fkiraly's original post in #2942 (added by @fkiraly):

There apparently is a `_contrib` folder in `sktime` with ... stuff ... in it.
Tbh it is unclear to me when it was decided that we should have it, what the scope of it is, or how it got populated with a collection of seemingly random content.

I think we need to deal with it, stop putting more random stuff in it, and eventually get rid of it.

* decide what should stay in `sktime` and what should go.
* if stays, move content in appropriate folders, e.g., classifiers in `classification`, docs into documentation, and so on. Ensure content is clean, well-documented, and interface compliant.
* content could also move to different repositories.

FYI @TonyBagnall, what is all this?

---

@TonyBagnall's re-post, here, 4h later:

**Is your feature request related to a problem? Please describe.**
from the beginning, contrib and _contrib have been areas where working code could be stored, particularly by the UEA group. This was a convenient solution proposed by the developers at the time. However, sktime is now at a stage where it looks odd having this code there. 

**Describe the solution you'd like**
Remove _contrib, ship any useful code to subpackages

There are a few issues to resolve before we do this, so please dont just delete it. The main of these are

1. Where to put the rotation forest and the continue interval tree classifiers. These are standard vector classifiers, not time series classifiers, used  within time series classifiers. I think we should just locate them within the file containing the time series classifier of interest.

2. clustering_experiments and classification_experiments are central to how we run experiments. These are moving to an sktime-estimator-evaluation sub package (still private at the moment). 

3. Also need to review other content, and see what is salvagable

My goal is to have this done by the time the grant starts.

**Comment by TonyBagnall** [comment]
oh, just saw this @fkiraly https://github.com/alan-turing-institute/sktime/issues/2942, can we use this issue instead?

**Comment by fkiraly** [comment]
> oh, just saw this @fkiraly https://github.com/alan-turing-institute/sktime/issues/2942, can we use this issue instead? 

Sure. Closing this as duplicate of #2942.

**Comment by TonyBagnall** [comment]
reopened to respond to comments. 
_"clustering_experiments and classification_experiments are central to how we run experiments. These are moving to an sktime-estimator-evaluation sub package (still private at the moment).
Instead of doing that, please make sure you align with the benchmarking workstream. You have committed to write benchmarking code for classifiers in 2019 https://github.com/alan-turing-institute/sktime/issues/12, which you haven't done."_

I may have misunderstood, are you trying to dictate how we run experiments or dictate my workstream? Do you also want to preapprove any papers we write? No, I haven't worked on the benchmarking module, nor has anyone else afaik. Sadly, there are many things I wanted to do but haven't. 

_"As [per the CC decision on May 31](https://github.com/sktime/community-org/blob/main/community_council/previous_meetings/20220531-meeting.md), you are not going to split sktime into multiple packages, or work on benchmarking in separation from community led workstreams, since this does not have express approval by the sktime community. Please acknowledge that."_

this is an open source package right? I am not splitting anything, this was on your express command to get rid of contrib. Are you really saying you want to have approval of how I use sktime? I'll take sktime out of the name of any associated packages if you want, but I dont think you have the right to dictate what github packages I create and what open source code I import into them! 

"Please work with the rest of the community, sktime is not just your own research group, and benchmarking time series classifiers is not just your turf"

I think that such rude and confrontational posts are undesirable, please desist

**Comment by MatthewMiddlehurst** [comment]
I am unsure if you have actually read the files you are making this fuss about. `classification_experiments.py` is essentially two versions of this:

```
if __name__ == "__main__":
        print(" Local Run")
        data_dir = "../datasets/data/"
        results_dir = "./temp/"
        cls_name = "FreshPRINCE"
        classifier = FreshPRINCE()
        dataset = "UnitTest"
        resample = 0
        tf = False
        predefined_resample = False

        load_and_run_classification_experiment(
            overwrite=True,
            problem_path=data_dir,
            results_path=results_dir,
            cls_name=cls_name,
            classifier=classifier,
            dataset=dataset,
            resample_id=resample,
            build_train=tf,
            predefined_resample=predefined_resample,
        )
```

This is literally just calling a function from the benchmarking package. We keep them in contrib to avoid having an unnecessary main method in the benchmarking module. What is it you want to keep.

**Comment by MatthewMiddlehurst** [comment]
This is an easy candidate for removal since we are looking to ditch `_contrib`.

**Comment by TonyBagnall** [comment]
so I was simply trying to get rid of contrib but keep stuff useful to us somewhere else. We can leave contrib as is if you want, but you asked for its removal.  I have literally no idea what your issue is with the code changes, your concerns seems to go beyond this issue

**Comment by fkiraly** [comment]
> I am unsure if you have actually read the files you are making this fuss about. classification_experiments.py is essentially two versions of this:

I have been relying on @TonyBagnall's statement to infer that there is some private package of yours that does benchmarking, where benchmarking functionality will move, `_contrib` or not. This statement: 

> clustering_experiments and classification_experiments are central to how we run experiments. These are moving to an sktime-estimator-evaluation sub package (still private at the moment).

I would read this to imply, there is a benchmarking package, only visible to the UEA research group ("private"). You want to move development there. You are actively working on benchmarking, and you are not sharing code.
I also know that you are also not engaging with all the other people working on benchmarking. Why?

If, as you say, there are just 10 additional lines besides benchmarking, why would Tony be talking about an `sktime-estimator-evaluation` package? Would that "package" just be the 10 additional lines? That does not seem plausible.

**Comment by MatthewMiddlehurst** [comment]
I can't speak for Tony, but he most likely meant we use the files to run all of our sktime experiments, which is the truth.

The new repository is simply a solution to having to remove these files and keep everyone in the group on the same page when running experiments. We are also taking the opportunity to use it as a hub to store results and similar items.

**Comment by MatthewMiddlehurst** [comment]
There may be some confusion around the name, but there is no concentrated effort to conceal useful benchmarking code away from other community members.

**Comment by fkiraly** [comment]
> I am unaware of any concentrated effort to develop the benchmarking package beyond what we have contributed, but nice to hear if there is now.

Repeated topic in the daily standups of the summer programme, and also here: https://github.com/alan-turing-institute/sktime/projects/31
The easiest way to hear about it is join at least one of the standups or meetings.

> but there is no concentrated effort to conceal useful benchmarking code away from other community members.

Excellent! Do I understand this as a commitment to make the `sktime-estimator-evaluation` package public?

**Comment by MatthewMiddlehurst** [comment]
It has been renamed, just `estimator-evaluation` now. 

We probably will make it public as a way to share results, not that we have any obligation to do so. Though, I'm not sure why anyone would want our code to run sktime classifiers on the UEA HPC. I also have a link to a public repository with bash submissions scripts for the UEA HPC and a guide to submitting HPC jobs using sktime if anyone is interested in that.

**Comment by aiwalter** [comment]
@TonyBagnall @MatthewMiddlehurst i am supportive to remove `_contrib`. Can you make a PR?

**Comment by TonyBagnall** [comment]
@aiwalter this is the first stage, would appreciate a review.  https://github.com/alan-turing-institute/sktime/pull/2951 Franz has asked me on slack to not approve any PRs. I dont think that fair, but will do it for now. Once this is in I will create a PR to get rid of it completely

**Comment by fkiraly** [comment]
> I dont think that fair, but will do it for now. Once this is in I will create a PR to get rid of it completely

Just to clarify, I am also in favour of getting rid of `_contrib`. You just have to read what I wrote in #2942 for a confirmation of that.

**Comment by TonyBagnall** [comment]
closed as duplicate https://github.com/alan-turing-institute/sktime/issues/2942
