### ISSUE TITLE
Error with TimeSeriesKMeans class import

### ISSUE THREAD

**Issue by foe12** [alan-turing-institute/sktime#2950]
### Discussed in https://github.com/alan-turing-institute/sktime/discussions/2949

<div type='discussions-op-text'>

<sup>Originally posted by **foe12** July  7, 2022</sup>
Please, help me to understand why I cant to import class TimeSeriesKMeans?  All my efforts to import TimeSeriesKMeans are handling to infinity. 
For clarity, I have jupyter notebook with 1 row: 
`from sktime.clustering.k_means import TimeSeriesKMeans`
sktime version is 0.11.2
OS windows

When I interrupt kernel I see errors:
[err_log.txt](https://github.com/alan-turing-institute/sktime/files/9062183/err_log.txt)

Hope for your help to understand what's wrong. Thank you in advance!

</div>

**Comment by TonyBagnall** [comment]
hi, seems like a permission error, can you import other modules, e.g.

from sktime.classification.dummy import DummyClassifier


PermissionError                           Traceback (most recent call last)
File C:\Program Files\Python39\lib\tempfile.py:255, in _mkstemp_inner(dir, pre, suf, flags, output_type)
    254 try:
--> 255     fd = _os.open(file, flags, 0o600)
    256 except FileExistsError:

PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Python39\\lib\\site-packages\\sktime\\distances\\__pycache__\\tmpmax6l57o'

**Comment by foe12** [comment]
> from sktime.classification.dummy import DummyClassifier



> 

Yes, I can import DummyClassifier and other classes. I faced with this issue only at TimeSeriesKMeans import

**Comment by foe12** [comment]
I start check other classes and have problem with import:
`from sktime.forecasting.naive import NaiveForecaster` and other classes from forecasting. 
Problem the same: 
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Python39\\lib\\site-packages\\sktime\\utils\\numba\\__pycache__\\tmpk9oih7d8'

**Comment by foe12** [comment]
I solve the problem by adding permission to write at C:\Program Files\Python39\ to my os user. Thanks!
