### ISSUE TITLE
[BUG] Cannot install `sktime-all-extras` in codespaces

### ISSUE THREAD

**Issue by soma2000-lang** [alan-turing-institute/sktime#2961]
I am trying to install sktime using the command
conda install -c conda-forge sktime-all-extras
I am using GitHub codespaces.I tried various ways to solve this issue but nothing seemed to work.
![image](https://user-images.githubusercontent.com/56045049/178091179-646270e0-fffd-44b7-99f9-5e880ebb2322.png)

**Comment by fkiraly** [comment]
Hm, it seems to want python 3.10, according to the log?

@lmmentel, is this perhaps related to your investigation of #2921?

**Comment by soma2000-lang** [comment]
![image](https://user-images.githubusercontent.com/56045049/178114584-afafb813-6663-4622-acc4-6b7e52267ec6.png)

**Comment by soma2000-lang** [comment]
These are all the commands that I tried executing after all the errors I _faced. even tried to change the python version and from thr select interpreter command in the command palette._

**Comment by soma2000-lang** [comment]
After that I tried to edit the .bashrc  by doing something like this
![image](https://user-images.githubusercontent.com/56045049/178115087-7e44866d-1e1d-4577-890c-c5f7086b7d15.png)
And lastly I tried https://github.com/conda/conda/issues/9367#issuecomment-555156949

**Comment by pertetotale** [comment]
sktime is **not** available **for py 3.10, yet**  
so searchin, installin fails

Note: the error description is not clear, the first argument should be omitted cos it suggests platfrom specific logic

**Comment by pertetotale** [comment]
cherry picking good data triomphs over brute force
water spring Lupa in Italy: only 30 days of lag
computes in a minute or 2 on GPU
http://vanoproy.be/python/Multivariate_Timeseries_Forecast_with_Lead_and_Lag_Timesteps_Using_LSTM.html

**Comment by fkiraly** [comment]
> sktime is not available for py 3.10, yet

ah, it's a py 3.10 thing. Will release py 3.10 compatible version 0.13.0 today.

**Comment by pertetotale** [comment]
thx, I got envs for several 3.7-8-9-10 timeseries and there is also some QGIS/geospatial conformism wanted, 
so that's good news

**Comment by fkiraly** [comment]
Yes, looks like it works now because we are on 3.10 since 0.13.0!

Closing issue.

**Comment by fkiraly** [comment]
@soma2000-lang, kindly confirm whether it works for 0.13.0 for you, I think it should - if not, please reopen

**Comment by soma2000-lang** [comment]
@fkiraly yes it works.
