### ISSUE TITLE
Function to convert 3d numpy array to nested pandas dataframe

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#298]
**Describe the solution you'd like**
* The inverse function of [`nested_to_3d_numpy()`](https://github.com/alan-turing-institute/sktime/blob/b72d2ac3a127430a4c3fc0bbebe74f34fbae5150/sktime/utils/data_container.py#L272)
* Takes in a nested `pd.DataFrame` and returns a 3d `np.array` with the first dimension being instances, the second columns/variables and the third time points.

**Comment by vedazeren** [comment]
take

**Comment by mloning** [comment]
Thanks! Writing a unit test for both functions would also be great! :)

**Comment by mloning** [comment]
Closed by #304
