### ISSUE TITLE
[DOC] Website - How to Contribute: Slack Invite Link Expired

### ISSUE THREAD

**Issue by tobiasweede** [alan-turing-institute/sktime#3014]
I was looking for the time of the Friday meetings.
The discord link is working, but at what time the meetings take place?

On sktime.org (https://www.sktime.org/en/stable/get_involved/contributing.html?highlight=Friday#how-to-contribute) you state "(see schedule on [Slack](https://join.slack.com/t/sktime-group/shared_invite/zt-62i7aejn-vXc3nOWF26S_P3VXFPWisQ))"

Don't know if the website has its own bug tracker.
However, the link has expired. 
Please use a new/static link and maybe duplicate the schedule to, e.g., the discord announcement channel?

**Comment by tobiasweede** [comment]
fixed by **#3017**

**Comment by fkiraly** [comment]
There are more, there is at least one in the `mentoring.rst` doc that had also expired, as @arvind has pointed out. We should to a full respository search and ensure that all links are updated. @arvind has offered to look into this, thanks!

**Comment by arvind** [comment]
Wrong Arvind I believe? :)

**Comment by fkiraly** [comment]
oh, very sorry, @arvind. I then presume that your discord name is not identical to your GitHub ID. Apologies for the spam.

**Comment by aiwalter** [comment]
@Arvind644 you can just copy the link from README, I created that and it has now no expiration date :)

**Comment by Arvind644** [comment]
@aiwalter just send a PR

**Comment by aiwalter** [comment]
Can you link it?

**Comment by topher-lo** [comment]
Hello there, it appears that this Slack link (https://sktime-group.slack.com/join/shared_invite/zt-62i7aejn-vXc3nOWF26S_P3VXFPWisQ#/shared-invite/error) on the README is also expired:
<img width="539" alt="Screenshot 2022-09-20 100325" src="https://user-images.githubusercontent.com/46541035/191151191-0682eeb2-aa32-488c-a55d-89272327d991.png">

**Comment by fkiraly** [comment]
is it expired again?
Let's fix it. Why did we not close this issue back then?

**Comment by topher-lo** [comment]
Looks like this PR was reverted for some reason: https://github.com/alan-turing-institute/sktime/pull/3017/files

**Comment by fkiraly** [comment]
how odd - can you kindly open a PR that replaces the expired link with the permanent one? That would be great!
Otherwise a core dev will do it later.
