### ISSUE TITLE
[ENH] Remove HIVE-COTE2 classifier

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#3034]
`sktime` currently contains a time series classifier called HIVE-COTE2.

The classifier seems quite questionable:

* it is an ensemble of a seemingly arbitrary choice of other classifiers
* the ensemble weights appear to be chosen without a good reason

I find it a very plausible assumption that "creator overfitting" or "parameter cherry-picking" has happened here. That is, tinkering around with the set of component classifiers, and the mixture weights, until it had - by randomness! - achieved good performance on the UCI dataset collection. Even when restricting the number of classifiers to choose from to 10 or so, and the weight combinations to as few as 5, we still face a combinatorial explosion which could plausibly explain supposed outperformance as random.

I think we should just remove this estimator from `sktime`.

Other problematic aspects:
* the ensemble method is not available as a compositor in `sktime`, and neither weight choice nor choice of components are explorable parameters. Therefore, the authors do not give others an easy way to construct similar estimators, or explore how much impact there could be of the above kind of cherry-picking.
* the authors of the paper claim the results are easily reproducible, but despite there being a benchmarking module in `sktime`, and the estimator being available in `sktime`, there is no code available for simply re-running the experiment. That is odd.
* in the reference paper, a lot of tests are performed (implicitly in the critical difference diagrams), but - probably - no multiple testing correction is carried out. This approach favours type I errors, i.e., mistakenly finding outperformance by the new estimator where it is not real.
* the experiment in the paper does not compare to naive baselines, or simple baselines such as much simpler pipelines as [feature extractor][supervised classifier], e.g., binner & random forest. For fairness, similar size combinatorial spaces should be explored of this combination.

Paper reference HIVE-COTE2: https://arxiv.org/abs/2104.07551

Paper with a discussion on why comparison to simpler baselines is important: https://arxiv.org/abs/1812.07519

**Comment by MatthewMiddlehurst** [comment]
> it is an ensemble of a seemingly arbitrary choice of other classifiers

Read the paper.

> the ensemble weights appear to be chosen without a good reason

Inherited from the previous HIVE-COTE, it is an exponent of the train accuracy estimate for each ensemble member. Changing or tuning it has very little impact on the classifier.

> the authors of the paper claim the results are easily reproducible

We ran the experiments in Java and the code to reproduce it is there, TSC literature does not revolve around sktime.

> ensemble method is not available as a compositor in sktime, and neither weight choice nor choice of components are explorable parameters

Separate issues, is this really a reason for removal?

> the experiment in the paper does not compare to naive baselines, or simple baselines such as much simpler pipelines

Neither do most of the implemented TSC classifiers, because they have been shown to perform poorly many times already.

**Comment by MatthewMiddlehurst** [comment]
Of course, I may be biased. @patrickzib and @angus924 are unaffiliated with the paper, and have both contributed their TSC algorithms to sktime before. Any thoughts? If there are fundamental issues, I genuinely would like to know and solve them.

Also, while an arxiv link is used, the paper is peer reviewed and published FYI. I cannot find anything for the second link. https://link.springer.com/article/10.1007/s10994-021-06057-9

**Comment by patrickzib** [comment]
@fkiraly: seriously, I do not quite understand the purpose of this move. This has the potential to seriously damage the community and potential contributors. Hive Cote is one of the baselines and most cited classifiers in the time series community.

**Comment by fkiraly** [comment]
>Hive Cote is one of the baselines and most cited classifiers in the time series community.

Discussion is about Hive-cote2, which has 22 citations, of which a handful are self-citations. Hardly one of the most cited classifiers.

>  I do not quite understand the purpose of this move. This has the potential to seriously damage the community and potential contributors.

Shipping computationally costly estimators that aren't good is what has the potential to damage trust in us. 

sktime is not an outlet for making unfounded claims like in the classification tutorial of "hive-cote 2 being *the* state-of-art".

sktime, in my vision at least and I would think in the vision of many others, is a neutral place where every contribution is equally respected, and not a place to be dominated a small number of TSC researchers for them to promote their specific interests and specifically branded algorithms while trashing others without being backed by evidence.

> Inherited from the previous HIVE-COTE, it is an exponent of the train accuracy estimate for each ensemble member. Changing or tuning it has very little impact on the classifier.

"choice has very little impact" seems to be a claim without proof.

If this is so, then why the strange fourth power?

Also, what you say indirectly confirms my suspicion that you played around with it, and the amount of "playing around" with the exponent and mixture weights is not reported.

> We ran the experiments in Java and the code to reproduce it is there, TSC literature does not revolve around sktime.

This is sktime.

And, this discussion does revolve around sktime, we are making the argument for or against this being in sktime.

You - the author - claim the "experiments are easily reproducible". So where are they?
Why are there not a few lines in sktime for this, if the estimator is here and you are contributing to it?

Or is it at least somewhere in java that everyone can look at?

You are, after all, contributing to a package that wants to make reproducible science easier for everyone.

> Read the paper.

It might come as a surprise to you, but I have done that. 
Jokes aside, please do not move to this insulting tone.

I have made what I think are valid scientific arguments, kindly react to those instead of dismissing them and claiming I have not read the paper.

If I had not read the paper, why would I cite it, and how could I make specific comments about passages from it?

>> the experiment in the paper does not compare to naive baselines, or simple baselines such as much simpler pipelines

> Neither do most of the implemented TSC classifiers, because they have been shown to perform poorly many times already.

That seems like an unvalidated and implausible claim. You are claiming that most of TSC literature does not compare to baselines?

Even in the unlikely case this were true, it would be an [argument from popularity](https://en.wikipedia.org/wiki/Argumentum_ad_populum) rather than a scientific one.

More generally, I don't think "baselines perform poorly, therefore do not need to compare to them" is a valid argument at all.

Baselines are *meant to perform poorly*, because they are the point of comparison that your algorithms need to outperform.

Conversely, to me it looks like that you cannot even make a solid argument that you are outperforming the most important baselines.

**Comment by MatthewMiddlehurst** [comment]
> Discussion is about Hive-cote2, which has 22 citations, of which a handful are self-citations. Hardly one of the most cited classifiers.

There is one citation from a paper by me and Tony. I was not aware number of citations was a prerequisite for inclusion, we should survey the package immediately.

> Shipping computationally costly estimators that aren't good is what has the potential to damage trust in us.
> 
> sktime is not an outlet for making unfounded claims like in the classification tutorial of "hive-cote 2 being the state-of-art".
> 
> sktime, in my vision at least and I would think in the vision of many others, is a neutral place where every contribution is equally respected, and not a place to be dominated a small number of TSC researchers for them to promote their specific interests and specifically branded algorithms while trashing others without being backed by evidence.

We show it is good in the paper. It is not even the slowest algorithm in sktime currently, let alone in other literature and algorithms we want implemented in the issue tracker. 

If your issues is around the wording in some examples, why not create an issue about that.

> "choice has very little impact" seems to be a claim without proof.
> 
> If this is so, then why the strange fourth power?
> 
> Also, what you say indirectly confirms my suspicion that you played around with it, and the amount of "playing around" with the exponent and mixture weights is not reported.

The exponent is justified in the original HIVE-COTE paper, we want to limit the impact of poor performing representations. It is inherited from the CAWPE ensemble, which is not even a time series classifier. We didn't report it in HC2 because we didn't test it. Those are unreported results from after the original HIVE-COTE paper, which I wasn't even around for.

> This is sktime.
> 
> And, this discussion does revolve around sktime, we are making the argument for or against this being in sktime.
> 
> You - the author - claim the "experiments are easily reproducible". So where are they?
> Why are there not a few lines in sktime for this, if the estimator is here and you are contributing to it?
> 
> Or is it at least somewhere in java that everyone can look at?
> 
> You are, after all, contributing to a package that wants to make reproducible science easier for everyone.

Funnily enough, you won't get the same results as the paper if you run the sktime version! There aren't a few lines for running it because why would there be when we have generic benchmarking tools where you can run any algorithm with our results style? Also, I do infract provide an example using the sktime benchmarking methods to run HC2, which would allow people to reproduce our results as best as you can in another language.

> It might come as a surprise to you, but I have done that.
> Jokes aside, please do not move to this insulting tone.
> 
> I have made what I think are valid scientific arguments, kindly react to those instead of dismissing them and claiming I have not read the paper.
> 
> If I had not read the paper, why would I cite it, and how could I make specific comments about passages from it?

It does come as a surprise, especially given the "So where are they?" about providing results above and the "arbitrary choice of other classifiers" comment.

> That seems like an unvalidated and implausible claim. You are claiming that most of TSC literature does not compare to baselines?
> 
> Even in the unlikely case this were true, it would be an [argument from popularity](https://en.wikipedia.org/wiki/Argumentum_ad_populum) rather than a scientific one.
> 
> More generally, I don't think "baselines perform poorly, therefore do not need to compare to them" is a valid argument at all.
> 
> Baselines are meant to perform poorly, because they are the point of comparison that your algorithms need to outperform.
> 
> Conversely, to me it looks like that you cannot even make a solid argument that you are outperforming the most important baselines.

While it is interesting so see how far the field has moved forward by comparing to these again and again, It is a waste of time and space to compare to 1-NN DTW and Random Forest every single paper. But it is fair if you feel this is not the case. People I have talked to and the peer reviewers for the paper did not, however. You are the first person to bring this up.

You are welcome to use my implementation, benchmarking code and running example to try to beat HC2 using the benchmarks if you want. I am going to assume you are not actually claiming Random Forest or simple summary stats would perform better.

**Comment by MatthewMiddlehurst** [comment]
Either way, if you really think this is necessary, I assume the next step is to hold a vote?

**Comment by fkiraly** [comment]
We could also try to democratitze the composition pattern:
https://github.com/alan-turing-institute/sktime/pull/3036
how many HIVE-COTE do you think a user can build with this before breakfast?

Took me about an hour to write.

Should also make it easy for anyone to study the impact of playing around with weights and the estimators inside.

**Comment by MatthewMiddlehurst** [comment]
If the issue created was about creating a composable weighted ensemble/HIVE-COTE I would have been all for it. If we can reproduce the results from the current code using that, it is a better solution, and one I wanted to work towards any way to cut down the repetition of HC1 and HC2.

That was not the issue created.

**Comment by fkiraly** [comment]
>There is one citation from a paper by me and Tony. I was not aware number of citations was a prerequisite for inclusion, we should survey the package immediately.

That was not the point. Someone was claiming that it is one of the "most cited classifiers in the community", as a positive argument for inclusion, and I refuted that claim.

Turning this refutation of "it is most cited" into a claim of a citation threshold sounds like a [basic logic error](https://en.wikipedia.org/wiki/Denying_the_antecedent) to me.

>We didn't report it in HC2 because we didn't test it. Those are unreported results from after the original HIVE-COTE paper, which I wasn't even around for.

"someone else did it and didn't report it" doesn't sound like a valid argument.

> Funnily enough, you won't get the same exact results as the paper if you run the sktime version! 

Hm, that's what I'm worried about. How *do* I get the same exact results with the `sktime` estimator, or at least similar ones?

>There aren't a few lines for running it because why would there be when we have generic benchmarking tools where you can run any algorithm with our results style? 

That's upside-down logic.
If it would cost only a few lines to write, so ... why didn't you write those lines?

> It does come as a surprise, especially given the "So where are they?" about providing results above and the "arbitrary choice of other classifiers" comment.

"so where are they" -> the paper does not link to code that reproduces the experiment. The links that you provide above only tell people in general how to run the algorithm on data, not how to reproduce the precise paper results. Also, this contradicts your earlier statement "Funnily enough, you won't get the same exact results as the paper if you run the sktime version!", since all we are talking about is the sktime estimator.

"arbitrary choice of other classifiers" -> from the paper, section 3 has the relevant sentence "HIVE-COTE 2.0 replaces three of the four classifiers that make up HIVE-COTE 1.0". No reason that I can discern is given, why those. Except perhaps that the components all lead to self-citations, but that is not made explicit.

**Comment by MatthewMiddlehurst** [comment]
Is the paper only considered reproducible if you can recreate the results perfectly in sktime? As I said earlier: `We ran the experiments in Java and the code to reproduce it is there, TSC literature does not revolve around sktime`. If all sktime estimators must be able to fully reproduce the exact results from their paper regardless of language, I think we have another issue to create and a lot of work to do. I respect the readers enough to believe they can write a for loop through the UCR datasets if they want to double-check our results for us, which we also provide on the same website.

Also, an FYI, we do compare the sktime version to the tsml one here https://timeseriesclassification.com/HC2_supplement.php. I by default set the STC contract to 2 hours instead of 1 to preserve accuracy, but there is probably room for improvement there and in DrCIF.

> "arbitrary choice of other classifiers" -> from the paper, section 3 has the relevant sentence "HIVE-COTE 2.0 replaces three of the four classifiers that make up HIVE-COTE 1.0". No reason that I can discern is given, why those. Except perhaps that the components all lead to self-citations, but that is not made explicit.

Dictionary Based: cBOSS -> TDE: higher accuracy
Interval Based: TSF&RISE -> DRCIF: Higher accuracy taking features from both classifiers.
Shapelet Based: STC remains the most accuracy shapelet approach at the time (I believe this has been improved on since)
Distance Based: Shown in HC1 to add little to accuracy while having a massive cost time-wise
Kernel Based: New addition, due to the very impressive performance of ROCKET. Altered due to the requirement for probabilities in the ensemble weighting scheme.
Weighting scheme: We tested multiple alternative schemes, and found the original CAWPE scheme to perform best.

We do explain these choices. Are we going to set up a vote for this?

**Comment by fkiraly** [comment]
>You are welcome to use my implementation, benchmarking code and running example to try to beat HC2 using the benchmarks if you want. I am going to assume you are not actually claiming Random Forest or simple summary stats would perform better.

In science, the [burden of proof](https://en.wikipedia.org/wiki/Burden_of_proof_(philosophy)) is with the one making the claim - the saying is "what is stated without evidence, can be dismissed without evidence". Also see the discussion on [burden of proof in the context of evidential standards vs pseudoscience](https://en.wikipedia.org/wiki/Pseudoscience#Improper_collection_of_evidence).

So, for this specific discussion: I don't need to beat HC2 or even write any benchmark code.

Au contraire: you need to beat reasonable baselines and present your evidence properly.

**Comment by MatthewMiddlehurst** [comment]
Good thing this is not a paper

**Comment by MatthewMiddlehurst** [comment]
What's the next move for this?

**Comment by fkiraly** [comment]
>We do explain these choices. Are we going to set up a vote for this?

Or, a benchmarking experiment, maybe?

**Comment by fkiraly** [comment]
>    Dictionary Based: cBOSS -> TDE: higher accuracy
>    Interval Based: TSF&RISE -> DRCIF: Higher accuracy taking features from both classifiers.
>    Shapelet Based: STC remains the most accuracy shapelet approach at the time (I believe this has been improved on since)
>    Distance Based: Shown in HC1 to add little to accuracy while having a massive cost time-wise
>    Kernel Based: New addition, due to the very impressive performance of ROCKET. Altered due to the requirement for probabilities in the ensemble weighting scheme.
>    Weighting scheme: We tested multiple alternative schemes, and found the original CAWPE scheme to perform best.

So, to summarize: you took six parts of the earlier algorithm, and replaced them by parts you found to perform better. That is, you made *at least six changes*, based on performance improvement observed, right?

Now, here's my prize question: *on which data did you observe that improved performance, subject to which evaluation mode*? On which you then based the decision to replace the components/parameters by other components/parameters?

Possibly on the UCI dataset collection? Possibly subject to the same fixed splits and evaluation worfklow that you are now evaluating the six-fold "improved" algorithm on?

Wouldn't that mean that you tuned the algorithm manually, on the test set that you are now using to evaluate it?

**Comment by MatthewMiddlehurst** [comment]
We didn't make six changes. We made three. Two of which were designed to replace the components they replaced in the HC2 ensemble. 112 datasets over 30 folds is quite a lot to overfit on, but the possibility exists, I agree. Which is why we also tested it on the 26 UEA multivariate algorithms, which none of the component classifiers had been tested on prior, except for STC which performed rather poorly and was not altered at all.

**Comment by fkiraly** [comment]
>What's the next move for this?

How about a compromise: we don't remove HIVE-COTE2, but we no longer present it as "the state-of-art" in the classification notebook?

**Comment by patrickzib** [comment]
Seriously, guys, I do not get the point here. 

> sktime, in my vision at least and I would think in the vision of many others, is a neutral place where every contribution is equally respected, and not a place to be dominated a small number of TSC researchers for them to promote their specific interests and specifically branded algorithms while trashing others without being backed by evidence.

I really do not get this. You talk about respecting ideas from others but do just the oposite and decise what is good for others. Let the users decide what to use. If runtime is the criterion we should remove all deep learning based methods inclusing Prophet please. You may still like a certain approach or not.

Also sktime is a place that requires contributions from others without being payed for! Of course these add contributions based on their own interest.  And if you want to attract researchers you have to accept this.

**Comment by patrickzib** [comment]
And to further add: the significance of a contribution should be answered by peer review and not by us.

**Comment by TonyBagnall** [comment]
I've not read all this, life is too short on a sunday in a heat wave, but I wish it would stop. I will say this for now
1. If you link to a paper describing HC2, please link to the published version, not the arxiv one
https://link.springer.com/article/10.1007/s10994-021-06057-9
2. The "questionable" classifier has been published in one of the top machine learning journals after peer review, by reviewers whose opinion I respect more than yours.
3. This is an unpleasant attack on the work of @MatthewMiddlehurst, a PhD student, and is IMO in clear breach of the code of conduct. I will report it as such, lets see if there is anyone left on the code of conduct committee to consider it

thanks you @patrickzib for chipping in, but I think Kiraly is beyond reason, this is just one part of an inept and laughable attack on me and my group. Its very sad. If anyone in my research group is reading this, I would advise you not to engage Kiraly directly via this issue, but to take any complaints you have to the code of conduct committee or the community council (although not to Franz obviously)

**Comment by TonyBagnall** [comment]
I've read it now and find it contains what I consider hugely inappropriate comments from kiraly to a PhD student. Frankly, I think it is disgraceful behaviour. No doubt kiraly will reopen, but I'm closing it

**Comment by fkiraly** [comment]
> This is an unpleasant attack on the work of @MatthewMiddlehurst, a PhD student, and is IMO in clear breach of the code of conduct.
>this is just one part of an inept and laughable attack on me and my group.

How exactly is a discussion on the merits of a classifier in `sktime` an "attack" on you and your group?

What is an attack is you calling this "laughable" and "sad", that is highly insulting.

> I've read it now and find it contains what I consider hugely inappropriate comments from kiraly to a PhD student. Frankly, I think it is disgraceful behaviour. No doubt kiraly will reopen, but I'm closing it

Again, this is ad hominem and personally insulting.

What again is "inappropriate"?

> And to further add: the significance of a contribution should be answered by peer review and not by us or someones personal preference.

@patrickzib, do you not consider me a peer?

Do I not have the right ot ask reasonable scientific questions?

What you are basically saying that only a certain circle (that you define) have the right to review algorithms, and those people determine what is in `sktime`, and not the `sktime` community.

**Comment by fkiraly** [comment]
> And if you want to attract researchers you have to accept this.

The point as I had made it at the top: `sktime` is a neutral place and not an advertising outlet for a narrow selection of researchers. I find it inappropriate that HIVE-COTE2 is being peddled as "the state-of-art" in TSC, on `sktime`.

To attract researchers, you have to be open to collaboration outside your immediate friends.

**Comment by patrickzib** [comment]
To be honest, I feel like you are mixing personal affairs with a fair review process. Right now you behave like a bouncer revoking access to sktime. And I believe that has a huge impact on potential contributors.

From my side, I believe Matthew did his part by passing a peer review in a journal. Also Tonys group is out of question for delivering great reproducible research. This is sufficient evidence. You brought up no new evidence but rather argument against him forcing additional evidence by him. 

If you want to have a certain standard for contributions (certain number of cotations, reproducibility, …) you should declare a document wirh conditions to be met for being included in sktime. But right now you do it in an ad hoc way with only one classifier chosen at random.

**Comment by aiwalter** [comment]
I would also kindly ask @fkiraly to close this issue. Its not going into a positive direction for the community. Regarding the "state-of-art" statement, I think its actually reasonable to remove that as it seems to be a subjective opinion here of the author and we want to let the user decide what is state of the art and what not.

**Comment by MatthewMiddlehurst** [comment]
Thank you for your comments. It is disappointing it has come to this.

> sktime contains the state of the art in time series classifiers in the package classification. These are grouped based on their representation. An accurate and relatively fast classifier is called [ROCKET](https://arxiv.org/abs/1910.13051)

> A state-of-art algorithm for time series classification is version 2 of the [HIVE-COTE algorithm](https://link.springer.com/article/10.1007/s10994-021-06057-9). HC2 is slow on small problems like these examples. However, it can be configured with an approximate maximum run time as follows (may take a bit longer than a minute to run this cell).

I assume these are the offending statements from the classification notebook? I did not write it, but it doesn't seem like HIVE-COTE is the only classifier to be referred to as the state-of-the-art currently? It would be fair to include ROCKET and InceptionTime in there as well, though ROCKET already has as many examples as HC2 in the notebook and InceptionTime is in the process of being ported over. If wording is still an issue, "A state-of-art" > "An accurate"?

I feel it is good to give current recommendations rather than just using 1-NN DTW or whatever the fastest classifier at the time is.

**Comment by MatthewMiddlehurst** [comment]
The attitude regarding including algorithms in sktime appears to have changed (https://github.com/alan-turing-institute/sktime/pull/3155). Will close this issue if there are no replies.

**Comment by fkiraly** [comment]
yes, correct, we've decided that (almost) everything can live in sktime as long as it is accompanied by sufficient quality scientific reference and as long as it is interface compliant. HIVE-COTE2 passes that bar imo, and probably only few people would object to that.
