### ISSUE TITLE
[BUG] address imminent removal of deprecated `sklearn` `_pprint`

### ISSUE THREAD

**Issue by celestinoxp** [alan-turing-institute/sktime#3037]
**Describe the bug**

next release 1.2.0 of scikit-learn will move pprint function and sktime will produce an error.

check this commit: https://github.com/scikit-learn/scikit-learn/commit/c63e38add5d0baa345cc363460dc0d0e18c87903

**To Reproduce**

install scikit-learn 1.2.0dev

```python
pip install --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple scikit-learn
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
Thanks for the pointer! Should be a quick fix, since we can replace by `BaseObject` repr in all cases where the warning is raised.

**Comment by fkiraly** [comment]
>I think only needs to delete line 23 "from sklearn.base import _pprint" in file "_split.py" from sktime\forecasting\model_selection\

Yes, that's one of the two instances and the easier one:
https://github.com/alan-turing-institute/sktime/pull/3048

The other instance occurs in `benchmarking.tasks` and seems less straightforward to address, since `BaseTask` does not inherit `BaseObject`.

**Comment by fkiraly** [comment]
@celestinoxp, looks like we got it now. Thanks for reporting!

**Comment by fkiraly** [comment]
PS: the second PR is not merged yet, so you would have to install from the branch to test it.
