### ISSUE TITLE
[BUG] TBATS model fails when forecast horizon is greater than number of training data points

### ISSUE THREAD

**Issue by hancelpv** [alan-turing-institute/sktime#3062]
TBATS model from sktime 0.7.0 fails with the following error if the forecast horizon is greater than number of training data points. Attaching error screenshot and reproducible code here.

![image](https://user-images.githubusercontent.com/34185789/180009313-7dde92ef-450b-4fde-b0cf-e0fa44cd7f65.png)

```
# Imports
import numpy as np
import pandas as pd

# Logger
import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# create some monthly time series data with random values
length_of_time_series = 24
seasonal_periods = 12
ts_array = np.random.randint(0, 100, length_of_time_series)

# convert numpy array to series
train = pd.Series(ts_array).astype('float64')

from sktime.forecasting.tbats import TBATS

tbats_model = TBATS(
    use_box_cox=False,
    use_trend=True,
    use_damped_trend=False,
    sp=seasonal_periods,
    use_arma_errors=False,
)

tbats_model.fit(train)

# works fine - when num points to forecast is less than or equal to train datapoints
num_points_to_forecast = 12
fcst_horizon = np.arange(1, num_points_to_forecast + 1)
pred = tbats_model.predict(fh=fcst_horizon)
logger.info("-- Predictions --")
logger.info(pred)

# throws ValueError - when num points to forecast is greater than train datapoints
num_points_to_forecast = 25
fcst_horizon = np.arange(1, num_points_to_forecast + 1)
try:
    pred = tbats_model.predict(fh=fcst_horizon)
except Exception as e:
    logger.exception(e)
```

Kindly suggest workarounds if any, thanks in advance!

**Comment by fkiraly** [comment]
sktime is version 0.13.0, can you confirm whether this problem still exists?

**Comment by hancelpv** [comment]
Hi @fkiraly , thanks for your quick response. Let me check on 0.13 and get back to you.

However, a numba issue is blocking me from upgrading sktime to 0.11.x series or above. Attaching the issue here : 
https://github.com/numba/numba/issues/4908

Let me know if you have any other workarounds. I tried using TBATS estimator  from the TBATS library itself, but the fitting seems to be really slow compared to sktime.

**Comment by fkiraly** [comment]
hm, unsure - re the numba issue, can you kindly open a separate issue where you describe precisely what you are trying to do (i.e., sequence of console commands for install) and the error message you are getting? Also, operating system and python version.

**Comment by aiwalter** [comment]
Version shouldnt matter as we didnt tough this model since longer, I guess its an problem of the underlying algo/implementation in `tbats` package. I think would be best to open an issue on their repo adn linke it here.
https://github.com/intive-DataScience/tbats

Regarding speed, I think its not possible that `sktime` model is faster than `tbats`, pls make sure you have same params, they might have different names: https://github.com/alan-turing-institute/sktime/blob/5f31ac0224666ae0c2deb4d34383350a57579636/sktime/forecasting/base/adapters/_tbats.py#L71-L80

**Comment by fkiraly** [comment]
>Version shouldnt matter as we didnt tough this model since longer

Hm, I think you are right, @aiwalter.

**Comment by hancelpv** [comment]
@fkiraly I confirm that the issue doesn't exist with sktime==0.13. Is there any way to know the exact release in which this issue was fixed (without having to try out with every release version) ? I will try to upgrade, but need to see how the numba issue can be mitigated.

Also, @aiwalter the underlying tbats library doesn't give an error when tried with the same data. It looks like a problem with the sktime adapter itself, but no action required since it seems to be fixed with 0.13 version. Thanks for confirming that time required for fitting will be same with both sktime and native tbats functions, I will try it with a timer and validate.

**Comment by hancelpv** [comment]
Attaching reproducible code with TBATS library alone.

```
# Imports
import numpy as np
import pandas as pd

# Logger
import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# create some monthly time series data with random values
length_of_time_series = 24
seasonal_periods = 12
ts_array = np.random.randint(0, 100, length_of_time_series)

# convert numpy array to series
train = pd.Series(ts_array).astype('float64')

from tbats import TBATS

tbats_model = TBATS(
    seasonal_periods=[seasonal_periods],
    use_box_cox=False,
    use_trend=True,
    use_damped_trend=False,
    use_arma_errors=False,
    n_jobs=1
)

fitted_model = tbats_model.fit(train)

# works fine - when num points to forecast is less than or equal to train datapoints
num_points_to_forecast = 12
logger.info("num_points_to_forecast : {}".format(num_points_to_forecast))
pred = fitted_model.forecast(steps=num_points_to_forecast)
logger.info("-- Predictions --")
logger.info(pred)

# works fine here as well
num_points_to_forecast = 25
logger.info("num_points_to_forecast : {}".format(num_points_to_forecast))
try:
    pred = fitted_model.forecast(steps=num_points_to_forecast)
    logger.info(pred)
except Exception as e:
    logger.exception(e)
```

**Comment by hancelpv** [comment]
@fkiraly @aiwalter I had one more follow up question. I could see that TBATS was taking about 14 seconds for fitting a model to a time series of length 24 datapoints, this is consistent with both the source TBATS and the sktime wrapper around TBATS. 14 seconds to fit a model for one time series seems a bit too long (compared to the R implementation). Let me know if there's anything we can do to improve the runtime. Thanks a lot!

![image](https://user-images.githubusercontent.com/34185789/180609534-cf057477-a490-4014-a533-e2fcccc04be5.png)

```
# Imports
import numpy as np
import pandas as pd

# Logger
import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
import time

def main():

    # create some monthly time series data with random values
    length_of_time_series = 24
    seasonal_periods = 12
    ts_array = np.random.randint(0, 100, length_of_time_series)

    # convert numpy array to series
    train = pd.Series(ts_array).astype('float64')

    from tbats import TBATS
    import os
    tbats_model = TBATS(
        seasonal_periods=[seasonal_periods],
        use_box_cox=False,
        use_trend=True,
        use_damped_trend=False,
        use_arma_errors=False,
        n_jobs=os.cpu_count()
    )
    # get the start time
    st = time.time()

    fitted_model = tbats_model.fit(train)

    # get the end time
    et = time.time()

    # get the execution time
    elapsed_time = et - st
    print('TBATS Fitting time :', elapsed_time, 'seconds')

    from sktime.forecasting.tbats import TBATS

    tbats_model = TBATS(
        sp=[seasonal_periods],
        use_box_cox=False,
        use_trend=True,
        use_damped_trend=False,
        use_arma_errors=False,
        n_jobs=os.cpu_count()
    )
    # get the start time
    st = time.time()

    fitted_model = tbats_model.fit(train)

    # get the end time
    et = time.time()

    # get the execution time
    elapsed_time = et - st
    print('Sktime Wrapper TBATS Fitting time :', elapsed_time, 'seconds')

if __name__ == '__main__':
    main()

```
