### ISSUE TITLE
[ENH] Implement update method for TBATS

### ISSUE THREAD

**Issue by jelc53** [alan-turing-institute/sktime#3063]
**Is your feature request related to a problem? Please describe.**
Want to perform walk-forward predictions using TBATS model. without refitting parameters every time. This is crucial for validation, especially since TBATS model is slow to train. 

**Describe the solution you'd like**
Implement update method for TBATS... same as interface used for other time series forecasters in sktime.

**Comment by fkiraly** [comment]
Hm, I think the `tbats` package that we interface does not have an updating capability, therefore the `sktime` `update` defaults to refitting.
I've opened an issue on `tbats` here: https://github.com/intive-DataScience/tbats/issues/35

If you want to control how often you refit, you can use the wrappers in the `forecasting.stream` module that will be added with 0.13.1 (you can try them out on the dev version), feedback appreciated. Note that this will still refit, but you can say sth like "I want to refit only every month".

**Comment by jelc53** [comment]
Thank you @fkiraly. I definitely have what I need now to use this functionality! Might be worth implementing a similar ‘update’ wrapper method to that used for other sktime models. Especially given the ‘refit_model.py’ logic is short and self-contained. Let me know if you’d like me to create a PR for this. Regardless really appreciate the follow up.

**Comment by fkiraly** [comment]
>Especially given the ‘refit_model.py’ logic is short and self-contained.

Which `refit_model.py` are you referring to?

> Let me know if you’d like me to create a PR for this? Regardless really appreciate the follow up.

Sure, would be appreciated! What precisely would you like to implement?

**Comment by fkiraly** [comment]
Oh, in the TBATS repository, I get it.

Yes, would appreciate a PR! If you need access to the pooled data, the `self._y` attribute stores the updated `y`.

**Comment by jelc53** [comment]
Perfect, can do. I tried creating a branch with my update and pushing it to the repo (from which I’d create a PR for your review) but it looks like I’d need to be granted some access permissions. Can you help or do I need to do a bunch of required onboarding?

Julian Cooper 

Mobile +61 411 190 693
***@***.***

**Comment by fkiraly** [comment]
>Perfect, can do. I tried creating a branch with my update and pushing it to the repo (from which I’d create a PR for your review) but it looks like I’d need to be granted some access permissions. Can you help or do I need to do a bunch of required onboarding?

Only core devs can push directly to this repo, you need to fork and make a PR from your fork.
(this is the typical open source contribution workflow, so once you've seen it you know it)
Instructions here: https://www.sktime.org/en/stable/developer_guide/git_workflow.html

**Comment by fkiraly** [comment]
need any help, @jelc53?

**Comment by jelc53** [comment]
Thanks @fkiraly, makes sense. This is my first time contributing to a public repo. Ill have a read through the link and give it a go later today!
