### ISSUE TITLE
[BUG] High memory consumption in `get_cutoff` when using a `DataFrame` with `MultiIndex`

### ISSUE THREAD

**Issue by shchur** [alan-turing-institute/sktime#3069]
**Describe the bug**
The method `get_cutoff` when applied to a `DataFrame` dataset with hierarchical index performs a lot of redundant computations. This results in OOM errors and crashes when training on very large datasets. For example, I cannot train `AutoETS` model on the `electricity` dataset from the Monash repository on a machine with 300GB of RAM.

The problem lies in the following line of code in [`sktime.datatypes._utilities.py`](https://github.com/alan-turing-institute/sktime/blob/5767dbaac759ed6ac43a8977f4c46beb93d0f18c/sktime/datatypes/_utilities.py#L299) 
```python
series_idx = [obj.loc[x].index.get_level_values(-1) for x in idx.droplevel(-1)]
```
Suppose our dataset consists of 300 time series each of length 20000, stacked into a `DataFrame` with `MultiIndex` (level 0 = time series ID, level 1 = timestamp). The above line of code will try to create an array with 20000 * 20000 entries, even though we actually only need an array with 300 * 20000 entries.

**To Reproduce**
```python
from sktime.datatypes import get_cutoff
from sktime.utils._testing.hierarchical import _make_hierarchical

df = _make_hierarchical((300,), max_timepoints=20000, min_timepoints=20000)
get_cutoff(df)  # program gets stuck and eventually crashes with in an OOM error
```

**Expected behavior**
The code shouldn't result in an OOM error.

**Additional context**
An easy solution to this problem is to replace L299 in [`sktime.datatypes._utilities.py`](https://github.com/alan-turing-institute/sktime/blob/5767dbaac759ed6ac43a8977f4c46beb93d0f18c/sktime/datatypes/_utilities.py#L299) 
```python
series_idx = [obj.loc[x].index.get_level_values(-1) for x in idx.droplevel(-1)]
```
with
```python
series_idx = [obj.loc[x].index.get_level_values(-1) for x in idx.droplevel(-1).unique()]
```

**Versions**
```
Python dependencies:
          pip: 22.1.2
   setuptools: 63.2.0
      sklearn: 1.1.1
       sktime: 0.13.0
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.3
   matplotlib: None
       joblib: 1.1.0
        numba: 0.55.2
     pmdarima: None
      tsfresh: None
```

**Comment by fkiraly** [comment]
hm, thanks!
Do you want to make a PR?

**Comment by shchur** [comment]
Yes, I'm on it

**Comment by fkiraly** [comment]
feel free to add yourself to authors and/or .all-contributorsrc

**Comment by fkiraly** [comment]
question: perhaps, might it be even more efficient to recurse or use groupby?

**Comment by shchur** [comment]
Unfortunately, I'm not 100% sure if I completely understand the surrounding logic to come up with a more efficient and elegant solution.
