### ISSUE TITLE
[BUG] CI test logs are too verbose

### ISSUE THREAD

**Issue by lmmentel** [alan-turing-institute/sktime#3073]
**Describe the bug**

The CI test configuration is too verbose and the logs often breaks browser display and often fail to load. It is not useful to have such verbosity when tests are passing and for failing tests pytest provides verbose diagnostic information.

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

Less vebose output from tests.
**Additional context**

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
What could we do to make them less verbose?

**Comment by lmmentel** [comment]
I think there is a flag for pytest that we can adjust
