### ISSUE TITLE
[BUG] Imputer and log transformer do not work together (inverse transform not applied)

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#3084]
**Describe the bug**

- When the `TransformerPipeline` consists of an Imputer followed by a log transformer, predictions do not apply inverse log transform (seems to be a bug)
- When the `TransformerPipeline` consists of only a log transformer, predictions seem to be correct (inverse transform is applied correctly).

**To Reproduce**

```python


from sktime.datasets import load_airline
from sktime.transformations.series.boxcox import LogTransformer
from sktime.transformations.series.impute import Imputer
from sktime.transformations.compose import TransformerPipeline
from sktime.forecasting.compose import ForecastingPipeline, TransformedTargetForecaster
from sktime.forecasting.naive import NaiveForecaster

preprocess = TransformerPipeline(
    [("imputer", Imputer()), ("transform", LogTransformer())]
)

pipeline = ForecastingPipeline(
    [
        (
            "forecaster",
            TransformedTargetForecaster(
                [
                    ("preprocess", preprocess),
                    ("model", NaiveForecaster()),
                ]
            ),
        )
    ]
)

y = load_airline()

# Fit Pipeline
pipeline.fit(y)

# Peedict
preds = pipeline.predict([1, 2, 3])

print(preds)
```

![image](https://user-images.githubusercontent.com/33585645/180647274-eb6791ca-8d4d-4647-aecc-866624218e9e.png)

**Expected behavior**
Predictions should be around the same magnitude as the data but it looks like the inverse transform is not applied for the `LogTransformer` when `Imputer` is also present in the `TransformerPipeline`

**Additional context**
**May be important. The above code works as expected if the `Imputer` is removed from the `TransformerPipeline`**, i.e. change this line

```python
preprocess = TransformerPipeline(
    [("transform", LogTransformer())]
)
```

**Versions**
<details>

System:
    python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_13p0\python.exe
   machine: Windows-10-10.0.19044-SP0

Python dependencies:
          pip: 22.1.2
   setuptools: 61.2.0
      sklearn: 1.1.1
       sktime: 0.13.0
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.3
   matplotlib: 3.5.2
       joblib: 1.1.0
        numba: 0.55.2
     pmdarima: 1.8.5
      tsfresh: None

</details>

**Comment by fkiraly** [comment]
I have identified the reason for the bug:

* the "skip inverse" rule for transformer pipeline skipped the inverse of the pipeline iff *at least one* component skipped inverse. But this was wrong, the pipeline inverse should be skipped iff *all* components are skipping inverse.
* `Imputer` skipped the inverse, and since it was in a pipeline with another transformer that did not skipped inverse, according to the old (wrong) rule, the entire sequence of inverses was skipped.

**Comment by fkiraly** [comment]
Fix here: https://github.com/alan-turing-institute/sktime/pull/3085

**Comment by ngupta23** [comment]
Thanks @fkiraly. That was super quick!
