### ISSUE TITLE
[BUG] ARIMA.fit with numpy arrays not working correctly

### ISSUE THREAD

**Issue by benHeid** [alan-turing-institute/sktime#3159]
**Describe the bug**
If I execute ARIMA().fit with numpy arrays, it will fails with a strange error message. It says that the indexes of the input Time Series does not fit to the exogenous variables Time Series. And prints the input time series values as missing index values for the exogenous variables time series.

**To Reproduce**

```python
rand = np.random.random(1000)
rand_x = np.random.random(1000)
ar = ARIMA()
assert rand.shape == rand_x.shape
ar.fit(rand, X=rand_x)
```

**Expected behavior**
ARIMA should be fitted without an error.

**Additional context**
I suppose the problem is line 269ff in series.py. The supposed index are the values of y. I would expect that the index is something like `np.arange(0, len(y)`. I can implement this fix, but I assume that this would have effects on lots of other transformers too.

```python
        if isinstance(y, np.ndarray):
            y_index = pd.Index(y)
        else:
            y_index = y.index
```

**Versions**
<details>

   machine: Windows-10-10.0.18362-SP0
Python dependencies:
          pip: 22.0.3
   setuptools: 60.8.2
      sklearn: 1.0.2
       sktime: 0.13.0
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.7.3
       pandas: 1.4.1
   matplotlib: 3.5.1
       joblib: 1.1.0
        numba: 0.55.1
     pmdarima: 1.8.5
      tsfresh: None

</details>

**Comment by fkiraly** [comment]
Yes, you are right! Line 270 should be `y_index = pd.Index(range(len(y)))`.
Strange that this went undetected for so long - we don't have numpy scenarios.

Would appreciate a PR, I'm also investigating further, there seem to be more problems with that function
