### ISSUE TITLE
[BUG] `day_of_year` is not generated in `DateTimeFeatures` transformation

### ISSUE THREAD

**Issue by e-alizadeh** [alan-turing-institute/sktime#3188]
**Describe the bug**
Passing `day_of_year` to `manual_selection` argument of `DateTimeFeatures` transformation shows the day of month (duplicating the column even if `day_of_month` exists) instead of day of the year.

**To Reproduce**
```python
import pandas as pd 
from sktime.transformations.series.date import DateTimeFeatures

ts = pd.DataFrame(index=pd.DatetimeIndex(["2020-02-09", "2020-02-10","2020-02-11", "2020-02-12"], freq ="D"))
tr = DateTimeFeatures(ts_freq="D", manual_selection=["day_of_year", "day_of_month", "day_of_week"])

print(tr.fit_transform(ts))
```
Above script gives the following result:
![Screen Shot 2022-08-05 at 9 23 15 AM](https://user-images.githubusercontent.com/84460342/183086502-0b2e06fb-24ac-4dbb-9010-e6f702b84438.png)

**Expected behavior**
We are expecting a new column `day_of_year` to be 40 for `2020-02-09` date. 

Another thing that I'm not sure, shouldn't the day of month column name be `day_of_month` instead of just `day`?

**Versions**
<details>
System:
    python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:06:49)  [Clang 12.0.1 ]
executable: /Users/<removed>/opt/anaconda3/envs/<removed>/bin/python
   machine: macOS-10.16-x86_64-i386-64bit
Python dependencies:
          pip: 22.2
   setuptools: 63.2.0
      sklearn: 1.1.1
       sktime: 0.13.0
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.3.5
   matplotlib: 3.5.2
       joblib: 1.1.0
        numba: 0.56.0
     pmdarima: 1.8.5
      tsfresh: 0.17.0
</details>

**Comment by fkiraly** [comment]
FZI @danbartl

**Comment by danbartl** [comment]
Fixed here

https://github.com/alan-turing-institute/sktime/pull/3222
