### ISSUE TITLE
[BUG] Dtype of `week_of_year` is different than other generated features in `DateTimeFeatures` transformation

### ISSUE THREAD

**Issue by e-alizadeh** [alan-turing-institute/sktime#3189]
**Describe the bug**
Passing `week_of_year` to manual_selection argument of DateTimeFeatures transformation will generate a `UInt32` column data type that's different than `int64` used when generating other features. 
I believe the generated features here should be consistent in terms of data types.

**To Reproduce**

```python
import pandas as pd 
from sktime.transformations.series.date import DateTimeFeatures
ts = pd.DataFrame(index=pd.DatetimeIndex(["2020-02-09", "2020-02-10","2020-02-11", "2020-02-12"], freq ="D"))
tr = DateTimeFeatures(ts_freq="D", manual_selection=["day_of_month", "day_of_week", "week_of_year"])
ts_transformed = tr.fit_transform(ts)
print(ts_transformed.dtypes)
```
![Screen Shot 2022-08-05 at 12 08 01 PM](https://user-images.githubusercontent.com/30320825/183117415-3eb98231-1e9b-41bb-b6e4-baba53329097.png)

**Expected behavior**
Similar integer data types (e.g all int64)

**Additional context**
You may also want to consider an int32 for memory purposes!

**Versions**
<details>
System:
    python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:06:49)  [Clang 12.0.1 ]
executable: /Users/<removed>/opt/anaconda3/envs/<removed>/bin/python
   machine: macOS-10.16-x86_64-i386-64bit
Python dependencies:
          pip: 22.2
   setuptools: 63.2.0
      sklearn: 1.1.1
       sktime: 0.13.0
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.3.5
   matplotlib: 3.5.2
       joblib: 1.1.0
        numba: 0.56.0
     pmdarima: 1.8.5
      tsfresh: 0.17.0

</details>

**Comment by fkiraly** [comment]
FYI @danbartl

**Comment by danbartl** [comment]
Fixed here

https://github.com/alan-turing-institute/sktime/pull/3222
