### ISSUE TITLE
[DOC] Improve shapelet transform notebook

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#320]
#### Describe the issue linked to the documentation
The current data set isn't very useful to show the inner workings of the shapelet transform. 

#### Suggest a potential alternative/fix
We need to find a new data set that can help illustrate the inner workings of shapelet and is easy to understand.

**Comment by mloning** [comment]
Suggestions are welcome @ABostrom @jasonlines!

**Comment by TonyBagnall** [comment]
TSML ones here, could be improved on, as Aaron said, this design started maybe 15 years ago and was bolted on repeatedly  https://github.com/uea-machine-learning/tsml/tree/master/src/main/java/statistics/simulators

**Comment by TonyBagnall** [comment]
this is a year old, I will shortly roll it into a Shapelets ongoing issue to mirror distance based one

**Comment by TonyBagnall** [comment]
the old shapelet transform has been deprecated, so the workbook this issue relates to has been removed. Work on improving classification notebooks is ongoing, but I am closing this very old issue.
