### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'pmdarima'

### ISSUE THREAD

**Issue by Abhilash-Kar0** [alan-turing-institute/sktime#322]
**Describe the bug**

In sktime.forecaster AutoARIMA,---   from pmdarima.arima import AutoARIMA as _AutoARIMA , pmdarima not installed. Please add a check in installation requirements. 
**To Reproduce**

install sktime through pip and import AutoARIMA from sktime.forecasting.arima 

```python
[Past your code here.]
```

**Expected behavior**

**Additional context**

**Versions**
<details>

Linux-4.9.0-12-amd64-x86_64-with-debian-buster-sid
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) 
[GCC 7.3.0]
NumPy 1.18.1
SciPy 1.4.1
Pandas 1.0.3
sktime 0.4.0
</details>

MY first issue please ignore any shortcomings

**Comment by mloning** [comment]
Please run `pip install pmdarima`. 

pmdarima is a soft dependency, so you don't need it to install sktime and you won't need it to use most of our functionality, but you need it for the AutoARIMA forecaster.

**Comment by mloning** [comment]
Please re-open if this doesn't help!

**Comment by ABIGAILDEBBY** [comment]
I still have an error after following all the steps here. I am doing this in Jupyter notebook. Kindly help/

**Comment by mloning** [comment]
@ABIGAILDEBBY Make sure you install the extra dependencies in the same environment from which you launch Jupyter notebook, let me know if that helps!

**Comment by aiexplorations** [comment]
Thanks for the install tip for `pmdarima`. Is there a chance that this dependency will be automatically fixed as part of the sktime install (pip/conda) in future releases?

**Comment by mloning** [comment]
Hi @aiexplorations, we treat `pmdarima` and a few other packages as soft dependencies for now, any issues installing them?

**Comment by steveross1975** [comment]
Hi, I have installed pmdarima via a Notebook cell, still get the error.
`!pip install pmdarima --user`
The package is installed because the output is a bunch of "Requirement already satisfied", but when I try to import pmdarima a few lines below,I get this error.

```
import pmdarima as pm
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-05191c3ae93f> in <module>
----> 1 import pmdarima as pm

ModuleNotFoundError: No module named 'pmdarima'

```

How can I solve this issue, thanks.

**Comment by mloning** [comment]
If it works on the command line but not in the notebook, it's likely that the notebook runs from a different environment. Using conda environments usually solved these issues for me.

**Comment by steveross1975** [comment]
Yes, you're right, looks like I was running a misconfigured Conda env.
In the end I've managed to install it and run a model.

**Comment by iSantPy** [comment]
I installed pmdarima in the current venv using python -m pip install pmdarima. When I type python -m pip list I got: 

![image](https://github.com/sktime/sktime/assets/87784833/c7d96525-3991-4574-8a31-26e10cfbb48c)

so, there it is! but when I open a JupyterLab with the venv activate and run the program it says:

![image](https://github.com/sktime/sktime/assets/87784833/bf61ff37-6cd3-4100-bf8c-e03d8d9c6620)

what am I doing wrong?
