### ISSUE TITLE
[BUG] make_forecasting_scorer attribute error

### ISSUE THREAD

**Issue by ilkersigirci** [alan-turing-institute/sktime#3221]
**Describe the bug**

When trying to create a custom forecasting scorer with `make_forecasting_scorer`, it fails with `AttributeError: '_DynamicForecastingErrorMetric' object has no attribute 'lower_is_better'`.

**To Reproduce**

```python
from sktime.performance_metrics.forecasting import make_forecasting_scorer
import numpy as np
from sktime.datasets import load_airline

y = load_airline()

def custom_mape(y_true , y_pred) -> float:

    eps = np.finfo(np.float64).eps

    result = np.mean(np.abs(y_true - y_pred) / np.maximum(np.abs(y_true), eps))

    return float(result)


fc_scorer = make_forecasting_scorer(
    func=custom_mape,
    name="custom_mape",
    greater_is_better=False,
)

fc_scorer(y,y)
```

**Expected behavior**

Creating custom_score should be done without any error.

**Additional context**

This was working as expected in earlier version IIRC. I think this is happens after `metric refactor` implementations.

**Versions**
<details>

System:
    python: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

Python dependencies:
          pip: 21.1.3
   setuptools: 57.4.0
      sklearn: 1.0.2
       sktime: 0.13.0
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.7.3
       pandas: 1.3.5
   matplotlib: 3.2.2
       joblib: 1.1.0
        numba: 0.56.0
     pmdarima: 1.8.5
      tsfresh: None
</details>

**Comment by fkiraly** [comment]
Thanks for reporting!

This was unfortunately not caught since the dynamic metric class started with an underscore and was not collected by tests, so slipped under the test screen of the refactor.

Fixed here now: https://github.com/alan-turing-institute/sktime/pull/3225
