### ISSUE TITLE
[DOC] Documentation not available 29 - 30/06/20 --> server down(?)

### ISSUE THREAD

**Issue by djwight** [alan-turing-institute/sktime#323]
Hey guys,
I am having a problem accessing the online documentation at **sktime.org** --> the server is not found since yesterday afternoon.

Is the site down? And if so, do you know when it will be live again?

Checked with github's status and the server issue from yesterday is apparently fixed (see image).

Sorry if this is the wrong thread for this issue, I didn't want to pollute the bug issues with this Q.

Thanks!

![Screenshot from 2020-06-30 10-41-55](https://user-images.githubusercontent.com/51029384/86104659-a00d4c00-babe-11ea-8da1-41f8de4114b4.png)

![Screenshot from 2020-06-30 10-47-53](https://user-images.githubusercontent.com/51029384/86105230-5e30d580-babf-11ea-9faa-db3628450bb0.png)

**Comment by mloning** [comment]
Hi @djwight, yes we're currently trying to deploy in to a custom domain which isn't working as expected at the moment, should be up soon again.

**Comment by djwight** [comment]
Hey @mloning,
Awesome, thanks for letting me know that.
