### ISSUE TITLE
Conda-Forge recipe request

### ISSUE THREAD

**Issue by owen-synergy** [alan-turing-institute/sktime#326]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to install sktime with conda

**Describe the solution you'd like**
I'd like a conda-forge feedstock to be created with a conda recipe to install sktime.

**Describe alternatives you've considered**
I know sktime can probably be pip installed into a conda environment... but it isn't ideal if you intend to update that environment continuously... pip and conda dependencies don't always play nice when updating.

**Additional context**
Conda-forge has instructions for adding a [recipe](https://conda-forge.org/#add_recipe). I will try to assist if any developers are interested - I'm not clear on whether sktime can be deployed as a no specific architecture package or whether it needs special build steps for each platform.

**Comment by mloning** [comment]
Hi @owen-synergy, adding a conda-forge recipe would be great! It's already on our list of CI/distribution issues #241. 

I've not done this before and only looked into it briefly, I'm not sure what specific architecture or special build steps would be. Most of our building process and deployment to PyPI is written in [`sktime/build_tools/`](https://github.com/alan-turing-institute/sktime/tree/master/build_tools).

**Comment by ketulgupta1995** [comment]
Hi @owen-synergy  I would like to add it but i haven't done it before, it would be great if you could help?

**Comment by mloning** [comment]
There's some info here: https://conda-forge.org/#contribute

**Comment by ketulgupta1995** [comment]
I followed the link as @mloning mentioned. 

One problem is that `scikit-posthocs
pmdarima` packages are not available in conda-forge which are required for sktime.  [https://conda-forge.org/docs/maintainer/knowledge_base.html#core-dependency-tree-packages-cdts](url)
[https://github.com/conda-forge/staged-recipes/issues/7462](url)
[https://github.com/facebookresearch/nevergrad/issues/272#issuecomment-530989489](url)

Still I have created a recipe [https://github.com/ketulgupta1995/staged-recipes/blob/master/recipes/sktime/meta.yaml](url) .

But it fails and it is not related to `scikit-posthocs
pmdarima` , can anyone help with this?

`["  ERROR (sktime,lib/python3.7/site-packages/sktime/classification/shapelet_based/mrseql/mrseql.cpython-37m-x86_64-linux-gnu.so): .. but ['libstdcxx-ng'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  ERROR (sktime,lib/python3.7/site-packages/sktime/classification/shapelet_based/mrseql/mrseql.cpython-37m-x86_64-linux-gnu.so): .. but ['libgcc-ng'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)"]
`
Also the `libgcc-ng` is present in packages being installed.
I have attached the logs.
[logs.txt](https://github.com/alan-turing-institute/sktime/files/4954266/logs.txt)

**Comment by mloning** [comment]
Seems like the error comes from the cpp code. Perhaps you can find a solution in the [advanced installation instructions](https://sktime.org/installation.html#development-version).

**Comment by mloning** [comment]
@dhirschfeld can you ping me here once https://github.com/conda-forge/staged-recipes/pull/13568#pullrequestreview-564010418 is merged and sktime is available via conda-forge? I want to add the badge to the readme!

**Comment by dhirschfeld** [comment]
https://github.com/conda-forge/sktime-feedstock

Not sure how far you'll get without all the deps, but it's a start. Still need to try relaxing the numpy pin & improve the CI. Will try and find some time shortly...

**Comment by mloning** [comment]
Also added the badge now to the README (see commit [cc5d9](https://github.com/alan-turing-institute/sktime/commit/cc5d9d440824efa6c0ac41757b6e02ca115b81fd)) and we're all set!
