### ISSUE TITLE
Implement Automatic Exponential Smoothing

### ISSUE THREAD

**Issue by HYang1996** [alan-turing-institute/sktime#327]
**Is your feature request related to a problem? Please describe.**

Add the Automatic Exponential Smoothing feature to BaseSktimeForecaster.

**Describe the solution you'd like**

Translate [the fable version on R](https://github.com/tidyverts/fable/blob/master/R/ets.R) to Python and add to sktime.

**Describe alternatives you've considered**

There might be existing Python packages that implement this feature.

**Additional context**

R documentation of the [ETS function](https://www.rdocumentation.org/packages/fable/versions/0.0.0.9100/topics/ETS).

**Comment by mloning** [comment]
Hi @HYang1996, as said, adding this would be great. I'd approach it as follows: 
* do a bit more online research if it already exists, google searches, perhaps open an issue on statsmodels or even better, ask in their Googlemail list
* read about ETS in https://otexts.com/fpp3/expsmooth.html
* get the R version to run on the airline data set (or any other data set, but we've got the airline data set in sktime too) in RStudio or so
* start translating the version from fable into Python, inherit from BaseSktimeForecaster https://github.com/alan-turing-institute/sktime/blob/67c56be8b1e838f2628df829946f795b7dba9aed/sktime/forecasting/base/_sktime.py#L21
* Check results against results obtained in R, perhaps even for certain methods/steps

**Comment by btrtts** [comment]
take

**Comment by mloning** [comment]
Sorry didn't mean to un-assign you
