### ISSUE TITLE
[ENH] offset for `LogTransformer`

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#3286]
It should be possible to specify an offset and scale for `LogTransformer`.

Based on the suggestion of @ilkersigirci here:
https://github.com/alan-turing-institute/sktime/discussions/3275

My approach would be adding `offset` and a `scale` parameter (with defaults 0, 1).

**Comment by bugslayer-332** [comment]
@fkiraly I would like to work on this issue. From what I have understood till now, np.log(data) gives an error for very small values of the data. And after reading your discussion, I got clarity on why offset should be used and how to fix that in code, but the [scale] parameter is what I am not able to understand. Any input from your side would be appreciated.

**Comment by fkiraly** [comment]
> I got clarity on why offset should be used and how to fix that in code, but the [scale] parameter is what I am not able to understand. Any input from your side would be appreciated.

the ideas is as follows: the data is being transformed as `scale * (data + offset)`

**Comment by bugslayer-332** [comment]
Thanks, I will work on this.

**Comment by bugslayer-332** [comment]
PR #3354, tests have been passed with suggested changes. Any suggestions are welcome.

**Comment by bugslayer-332** [comment]
PR https://github.com/alan-turing-institute/sktime/pull/3354, tests have been passed with suggested changes.

**Comment by ltsaprounis** [comment]
You can achieve this by not specifying an upper bound to the [ScaledLogitTransformer](https://www.sktime.org/en/latest/api_reference/auto_generated/sktime.transformations.series.scaledlogit.ScaledLogitTransformer.html)

Not saying that we shouldn't add this to the LogTransformer, I think we should.
