### ISSUE TITLE
[BUG] AutoETS.fit generates an unneeded UserWarning when auto=True and additive_only=True

### ISSUE THREAD

**Issue by adamcataldo** [alan-turing-institute/sktime#3311]
**Describe the bug**

When:

1. AutoETS is constructed with auto=True and additive_only=True, and
2. AutoETS.fit is called with a series with negative values
A UserWarnings gets generated.

_UserWarning: Warning: time series is not strictly positive,multiplicative components are ommitted_

**To Reproduce**

```python
import warnings

import numpy as np
import pandas as pd
from sktime.forecasting.ets import AutoETS

with warnings.catch_warnings() as w:
    warnings.simplefilter("error")
    forecaster = AutoETS(auto=True, additive_only=True)
    x = pd.Series(np.arange(-15.0, 15.0, 1.0))
    forecaster.fit(x)
```

**Expected behavior**

This warning should not be generated. Because additive_only is set equal to True, omitting multiplicative components is the expected behavior, not exceptional behavior.

**Additional context**

The following can serve as a workaround until this bug is fixed:

```python
import warnings

import numpy as np
import pandas as pd
from sktime.forecasting.ets import AutoETS

forecaster = AutoETS(auto=True, additive_only=True)
x = pd.Series(np.arange(-15.0, 15.0, 1.0))
with warnings.catch_warnings() as w:
    warnings.simplefilter("ignore")
    forecaster.fit(x)
```

The problem with this workaround is that other warning also get suppressed, so users miss the opportunity to catch other potential issues.

**Versions**
<details>

System:
    python: 3.8.9 (default, Apr 13 2022, 08:48:07)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
executable: /Library/Developer/CommandLineTools/usr/bin/python3
   machine: macOS-12.5.1-x86_64-i386-64bit
Python dependencies:
          pip: 22.2.2
   setuptools: 63.1.0
      sklearn: 1.1.2
       sktime: 0.13.1
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.3
   matplotlib: 3.5.2
       joblib: 1.1.0
        numba: 0.56.0
     pmdarima: 2.0.0
      tsfresh: None

</details>

**Comment by fkiraly** [comment]
agreed, thanks! Good first issue since it seems like a simple thing. Contributions appreciated!

**Comment by chillerobscuro** [comment]
I've been looking to contribute and this seems like an easy first issue, I'll put in a PR for this shortly.
