### ISSUE TITLE
[DOC] Docstring lists wrong default for `SlidingWindowSplitter` parameter `start_with_window`

### ISSUE THREAD

**Issue by JasonSanchez** [alan-turing-institute/sktime#3315]
Default for this argument is actually True.

https://github.com/alan-turing-institute/sktime/blob/824804c785fb97e20c29045ee058181ceeb9418b/sktime/forecasting/model_selection/_split.py#L1107

**Comment by fkiraly** [comment]
Thanks for reporting - should be a really easy fix (good first issue)

**Comment by bugslayer-332** [comment]
Hi, I am a beginner in Open Source, and I would love to start contributing to sktime with this issue. I have looked at the code base and figured out that this error is in the documentation of the SlidingWindowSplitter function. Am i right?

**Comment by fkiraly** [comment]
> Hi, I am a beginner in Open Source, and I would love to start contributing to sktime with this issue. I have looked at the code base and figured out that this error is in the documentation of the SlidingWindowSplitter function. Am i right?

Yes, happy bugslaying!

**Comment by bugslayer-332** [comment]
@fkiraly I have submitted a PR https://github.com/alan-turing-institute/sktime/pull/3340 can you please review and provide you valuable feedback. Any mistake from my side,please inform..
