### ISSUE TITLE
[ENH] Add STRAY anomaly detection

### ISSUE THREAD

**Issue by KatieBuc** [alan-turing-institute/sktime#3337]
Add STRAY (Search TRace AnomalY) anomaly detection [1]. 

"The HDoutliers [2] algorithm is a powerful unsupervised algorithm for detecting anomalies in high-dimensional data, with a strong theoretical foundation. However, it suffers from some limitations that significantly hinder its performance level, under certain circumstances. In this article, we propose an algorithm that addresses these limitations. We define an anomaly as an observation where its k-nearest neighbor distance with the maximum gap is significantly different from what we would expect if the distribution of k-nearest neighbors with the maximum gap is in the maximum domain of attraction of the Gumbel distribution. An approach based on extreme value theory is used for the anomalous threshold calculation. Using various synthetic and real datasets, we demonstrate the wide applicability and usefulness of our algorithm, which we call the stray algorithm. "

This task involves re-writing [this R code](https://github.com/pridiltal/stray/tree/master/R), as an estimator in the annotation module.

References: 
1. Talagala, Priyanga Dilini, Rob J. Hyndman, and Kate Smith-Miles. "Anomaly detection in high-dimensional data." Journal of Computational and Graphical Statistics 30.2 (2021): 360-374.
2. Wilkinson, Leland. "Visualizing big data outliers through distributed aggregation." IEEE transactions on visualization and computer graphics 24.1 (2017): 256-266.

**Comment by lmmentel** [comment]
closed by #3338
