### ISSUE TITLE
[BUG] `Differencer` returns original data instead of inverting when all in-sample

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#3345]
From @ilkersigirci in #3277.

Unexpected behaviour when `Differencer` is asked to inverse transform in-sample and used inside a target transformation forecasting pipeline - because `Differencer` just retrieves the data seen in `fit`.

---
Assume that I want to log&diff y and X and use ARIMA model as forecaster. When I tried to get in_sample prediction of the pipeline, I got exactly original y data instead of arima's in_sample prediction. Note that this is not the case when using just the model not the pipeline with the transformer. I think this happens because Differencer returns its stored data for the same indices. 

I believe this is a general bug for any forecasting pipeline that uses Differencer and forecaster whose able to do in_sample prediction together.

```python
import numpy as np
from sktime.forecasting.compose import (
    ForecastingPipeline,
    TransformedTargetForecaster,
)
from sktime.transformations.compose import TransformerPipeline
from sktime.transformations.series.compose import OptionalPassthrough
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.transformations.series.difference import Differencer
from sktime.transformations.series.boxcox import LogTransformer
from sktime.forecasting.base import ForecastingHorizon
from sktime.datasets import load_airline

y = load_airline()
X = pd.DataFrame({"lag1": y.shift(1).fillna(method="bfill"),
                  "lag2": y.shift(2).fillna(method="bfill")}, 
                 index=y.index)

y_train, y_test, X_train, X_test = temporal_train_test_split(y=y,X=X, test_size=30)
fh_out = np.arange(1, len(y_test)+1)
fh_ins = ForecastingHorizon(y_train.index, is_relative=False)

pipe = ForecastingPipeline(
    steps=[
        (
            "transformersX",
            TransformerPipeline(
                steps=[
                    ("logX", OptionalPassthrough(LogTransformer())),
                    ("differencerX", Differencer(na_handling="fill_zero")),
                ]
            ),
        ),
        (
            "forecaster",
            TransformedTargetForecaster(
                steps=[
                    (
                        "transformers",
                        TransformerPipeline(
                            steps=[
                                ("log", OptionalPassthrough(LogTransformer())),
                                ("differencer", Differencer(na_handling="fill_zero")),
                            ]
                        ),
                    ),
                    ("arima", ARIMA()),
                ]
            ),
        ),
    ]
)

pipe.fit(y=y_train, X=X_train)
pipe_ins = pipe.predict(fh=fh_ins, X=X_train)
pipe_forecast = pipe.predict(fh=fh_out, X=X_test)

arima_model = ARIMA()
arima_model.fit(y=y_train, X=X_train)
model_ins = arima_model.predict(fh=fh_ins, X=X_train)
model_forecast = arima_model.predict(fh=fh_out, X=X_test)


# Returns True - not expected
np.allclose(y_train.to_numpy(), pipe_ins.to_numpy())

# Returns False - not expected
np.allclose(pipe_ins.to_numpy(), model_ins.to_numpy())

# Returns False - expected
np.allclose(y_train.to_numpy(), model_ins.to_numpy())
```

_Originally posted by @ilkersigirci in https://github.com/alan-turing-institute/sktime/discussions/3277#discussioncomment-3469781_

**Comment by fkiraly** [comment]
Thanks for the explanation, @ilkersigirci.

I looked in the `Differencer`, and there was a strange shortcut that had the described effect precisely under the condition that you outlined. Puzzled why it was there, but it's gone now: https://github.com/alan-turing-institute/sktime/pull/3346

**Comment by fkiraly** [comment]
added your code as a test, simplified a bit, though.

Your original pipeline can be written shorter:
```python
    logdiff = -LogTransformer() * Differencer()
    pipe = logdiff ** (logdiff * NaiveForecaster())
```

question: do we need the `OptionalPassthrough`? That will just remove the `LogTransformer`, since the default is `passthrough=True`. So your pipeline is even simpler, it is
```python
    pipe = Differencer() ** (Differencer() * NaiveForecaster())
```
or do I misunderstand?

**Comment by fkiraly** [comment]
and the exogeneous data we don´t need either, so for testing this would be sufficient? `Differencer() * NaiveForecaster()`

**Comment by ilkersigirci** [comment]
For miminal testing purposes, you are absolutely right. I just wrote the code since my current use-case is like that. The reason because I don't use dunder methods is to be able to explicitly name the transformers in order to use their names in grid search.

**Comment by fkiraly** [comment]
> The reason because I don't use dunder methods is to be able to explicitly name the transformers in order to use their names in grid search.

Hm, I see - are the names they get from the dunders so much worse? i.e., if you use `pipe.get_params()`?
Would be interested to hear why that is not so good and why you prefer the "explicit" way?

**Comment by ilkersigirci** [comment]
> > The reason because I don't use dunder methods is to be able to explicitly name the transformers in order to use their names in grid search.
> 
> Hm, I see - are the names they get from the dunders so much worse? i.e., if you use `pipe.get_params()`?
> Would be interested to hear why that is not so good and why you prefer the "explicit" way?

The names I got from the pipeline are not the problem, actually. I just like the explicit way. Moreover, if I try to use dunder methods with the same transformer with different params, I can't discriminate their names, so explicit way seems to working better for me :)

**Comment by fkiraly** [comment]
> Moreover, if I try to use dunder methods with the same transformer with different params, I can't discriminate their names, so explicit way seems to working better for me :)

It creates unique names, e.g., `Transformer1`, `Transformer2`, in that case? But, fair enough.

**Comment by fkiraly** [comment]
@ilkersigirci, I think I solved the `Differencer` issue:
https://github.com/alan-turing-institute/sktime/pull/3346

I would appreciate your eyes on it since it does not exactly satisfy your test case, only if you exclude the first index.
