### ISSUE TITLE
[ENH] Let evaluate() function accept and return trained model

### ISSUE THREAD

**Issue by chillerobscuro** [alan-turing-institute/sktime#3353]
**Is your feature request related to a problem? Please describe.**
The `evaluate` function is very helpful for cross validation with sliding time windows. However as far as I can tell it requires that you internally train the model, as even if you use the "update" strategy, the first window trains the model. 

**Describe the solution you'd like**
It should let you pass in an already trained model. If this was the case, then it should also be possible to only pass in a "test set", because no training needs to be done internally, and it could just produce a forecast on every window within the test set. Right now it is kind of awkward to figure out what your "initial window" of the `ExpandingWindowSplitter` needs to be, it seems preferable to just define a forecast horizon and step size and run on the entirety of the test set, if your model is already trained. This is much more amenable to typical train/test workflows most people use outside the `evaluate` workflow.

Finally, there should be an option to return the model that was trained within the evaluator.

**Describe alternatives you've considered**
Not sure of existing alternatives, I will happily implement these fixes in a PR if I get feedback that they would make sense and be an improvement.

**Comment by fkiraly** [comment]
Thanks! @alex-hh and @dbcerigo are currently reworking the benchmarking interface here, using the `kotsu` package: https://github.com/alan-turing-institute/sktime/pull/2977

so if you are adventurous, trying this out and feedback would be appreciated!

For `evaluate`, this https://github.com/alan-turing-institute/sktime/pull/2903 could do the job to pass an already fitted estimator.

Returning might be useful, but what would you return if you go with the `refit` strategy? Which state, which estimator do you want returned? All states? Or only the last one?

**Comment by chillerobscuro** [comment]
Hmm looks like between those two pieces of work, my main requests might be covered. I see the benchmarkingv2 notebook and look forward to a bit more example documentation, as it does look useful. 

I think it'd make sense to return the final estimator (the "most fitted" one) but do think it's low priority, especially if you can pass it in prefit. So I'll hold off on putting any PRs for this.
