### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'sktiem'

### ISSUE THREAD

**Issue by xtibau** [alan-turing-institute/sktime#339]
After creating a new environment with anaconda, and running `pip install sktime` I got the following error (I've also tried to install it as a developer).

Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sktime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tiba_xa/Documents/Personal/UB/firearms/codi/sktime.py", line 2, in <module>
    from sktime.datasets import load_airline
ModuleNotFoundError: No module named 'sktime.datasets'; 'sktime' is not a package

**Versions**
>>> import platform; print(platform.platform())
Linux-5.3.0-51-generic-x86_64-with-glibc2.10
>>> import sys; print("Python", sys.version)
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.19.0
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.5.1
>>> import scipy; print("Pandas", pandas.__version__)
Pandas 1.0.5
>>> import sktime; print("sktime", sktime.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tiba_xa/Documents/Personal/UB/firearms/codi/sktime.py", line 2, in <module>
    from sktime.datasets import load_airline
ModuleNotFoundError: No module named 'sktime.datasets'; 'sktime' is not a package

**Comment by xtibau** [comment]
Seems that if I installed manually with `python setup.py develop` works.

**Comment by xtibau** [comment]
It was because I had a file with the same name in the main folder. Sorry

**Comment by mloning** [comment]
@xtibau no problem, happy to help if something else is broken! :)
