### ISSUE TITLE
[BUG] sporadic bug in `test_all_annotators.py::test_output_type[HMM]`

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#3394]
There seems to be a sporadic bug with `test_all_annotators.py::test_output_type[HMM]`:

```
         if np.any(np.isinf(trans_prob[:, -1])):
>           raise ValueError("Change parameters, the distribution doesn't work")
E           ValueError: Change parameters, the distribution doesn't work
```

see here: https://github.com/alan-turing-institute/sktime/runs/8257610342?check_suite_focus=true

FYI @miraep8, @lmmentel

**Comment by miraep8** [comment]
Thank you for raising issue!
