### ISSUE TITLE
[BUG] make_reduction causes misleading Exception on NaN values: `ValueError: Input X contains NaN.`

### ISSUE THREAD

**Issue by tobb10001** [alan-turing-institute/sktime#3402]
**Describe the bug**

When using an sklearn model, that does not support NaN values with `make_reduction` and a `y` series with NaN values, the resulting exception is misleading:
`ValueError: Input X contains NaN.`

**To Reproduce**

```python
import numpy as np

from sklearn.linear_model import LinearRegression

from sktime.datasets import load_longley
from sktime.forecasting.compose import make_reduction

y, X = load_longley()

assert not X.isna().any().any() # X doesn't contain NaN

y_w_nan = y.copy()
X_w_nan = X.copy()

y_w_nan.iloc[0] = np.nan
X_w_nan.iloc[0] = np.nan

model = make_reduction(LinearRegression())

model.fit(y, X)
# works normal

#model.fit(y, X_w_nan)
# throws `ValueError: Input X contains NaN.`, as one would expect.

model.fit(y_w_nan, X)
# also throws `ValueError: Input X contains NaN.`, although X doesn't contain NaN.
```

**Expected behavior**

An exception, that tells the user that the y array contains NaNs.

**Additional context**

This problem does not appear in sklearn:
```py
import numpy as np

from sklearn.linear_model import LinearRegression

from sktime.datasets import load_longley

y, X = load_longley()

assert not X.isna().any().any() # X doesn't contain NaN

y_w_nan = y.copy()
X_w_nan = X.copy()

y_w_nan.iloc[0] = np.nan
X_w_nan.iloc[0] = np.nan

linreg = LinearRegression()

linreg.fit(X, y) # works normal

#linreg.fit(X_w_nan, y)
# throws `ValueError: Input X contains NaN.`
#linreg.fit(X, y_w_nan)
# throws `ValueError: Input y contains NaN.`
```
@aiwalter When we discussed this, we missed that `LinearRegressioin.fit()` takes arguments in `X, y` order, instead of the `y, X` order used in `sktime`.  <https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression.fit>

This problem also appears with other sklearn models. I've tried Ridge and SGDRegressor.

My stacktrace:
<details>

```plainTraceback (most recent call last):
  File "/home/.../t.py", line 27, in <module>
    model.fit(y_w_nan, X)
  File "/home/.../sktime/forecasting/base/_base.py", line 303, in fit
    self._fit(y=y_inner, X=X_inner, fh=fh)
  File "/home/.../sktime/forecasting/compose/_reduce.py", line 513, in _fit
    self.estimator_.fit(Xt, yt)
  File "/home/.../venv/lib/python3.10/site-packages/sklearn/linear_model/_base.py", line 684, in fit
    X, y = self._validate_data(
  File "/home/.../venv/lib/python3.10/site-packages/sklearn/base.py", line 596, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/.../venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1074, in check_X_y
    X = check_array(
  File "/home/.../venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 899, in check_array
    _assert_all_finite(
  File "/home/.../venv/lib/python3.10/site-packages/sklearn/utils/validation.py", line 146, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

```

</details>

**Versions**
<details>

```plain
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sktime import show_versions; show_versions()

System:
    python: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
executable: /home/.../venv/bin/python3
   machine: Linux-5.19.0-76051900-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 22.2.2
   setuptools: 59.8.0
      sklearn: 1.1.2
       sktime: 0.13.2
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.4
   matplotlib: None
       joblib: 1.1.0
        numba: 0.56.2
     pmdarima: None
      tsfresh: None
```
</details>

**Comment by aiwalter** [comment]
@tobb10001 I was looking into it and think that actually there is no bug. Reason is that `make_reduction` is doing the tabularization of the time series and therefore some past values of `y` go into `X`. You will see that doing following will therefore also raise the same exception.
```pyhton
model.fit(y_w_nan, fh=[1,2,3])
```
The `X` is internally created to the lags:
```
array([[   nan, 61122., 60171., 61187., 63221., 63639., 64989., 63761.,
        66019., 67857.],
       [61122., 60171., 61187., 63221., 63639., 64989., 63761., 66019.,
        67857., 68169.],
       [60171., 61187., 63221., 63639., 64989., 63761., 66019., 67857.,
        68169., 66513.],
       [61187., 63221., 63639., 64989., 63761., 66019., 67857., 68169.,
        66513., 68655.],
       [63221., 63639., 64989., 63761., 66019., 67857., 68169., 66513.,
        68655., 69564.],
       [63639., 64989., 63761., 66019., 67857., 68169., 66513., 68655.,
        69564., 69331.]])
```

I can understand that the exception might be a little confusing. We could write a custom exception around this, but actually I am not a big fan of wrapping exceptions. Or what do you have in mind? @tobb10001 :)

**Comment by aiwalter** [comment]
@fkiraly I am wondering if the order of the `X` values per row should not be inverted? I think for tree-based models it doesnt matter but for liner models I think it matters? So first row would start with `67857.` and end with `nan`?
The `y` is originally:
```
Period
1947        NaN
1948    61122.0
1949    60171.0
1950    61187.0
1951    63221.0
1952    63639.0
1953    64989.0
1954    63761.0
1955    66019.0
1956    67857.0
1957    68169.0
1958    66513.0
1959    68655.0
1960    69564.0
1961    69331.0
1962    70551.0
Freq: A-DEC, Name: TOTEMP, dtype: float64
```

**Comment by tobb10001** [comment]
@aiwalter I've got a few things in mind, but none of which seems convincing...

I think the cleanes would be to to somehow check if the passed estimator can handle NaNs and if it doesn't, check `y` and `X` in sktime, before passing it to the estimator. However, I'm afraid that this is impossible.
The only thing I've found is a [small list of estimators that _are_ capable of handling NaNs](https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values) in sklearn, but I don't think this can be used to build a stable mechanism.

Another approach would be to catch the exception, check if it says `Input X contains NaN.` and emit a warning or something But I don't like this approach as well, because (a) one would probably not read the warning anyways, if there is an exception right besides it and (b) reading a string intended for humans will probably never be stable (maybe another regressor says `NaN found in X input`...).
(b) also applies for wrapping / reraising the exception as well, so I wouldn't consider this an option as well...

Maybe a note in the documentation to also check your `y` if you see this exception might be the best option. Although admitted, that I think I didn't even look there when I encountered this yesterday...

**Comment by fkiraly** [comment]
> I think the cleanes would be to to somehow check if the passed estimator can handle NaNs and if it doesn't, check y and X in sktime, before passing it to the estimator. However, I'm afraid that this is impossible.

I think that's incorrect.

That is, it is possible to check whether the wrapped estimator can handle nan, via the `sklearn` tag `allow_nan`.

We could copy that tag to the `sktime` estimator for the same purpose, which would then raise an informative error message, in theory (at the input checks).

**Comment by fkiraly** [comment]
This should work:
https://github.com/alan-turing-institute/sktime/pull/3405

I also noticed the input checks of forecasters did not check missing values in data against the tag - the PR #3405 also adds an informative error message.

**Comment by fkiraly** [comment]
seems to work, but there might be some interaction with `WindowSummarizer` - @danbartl, any idea what might be happening? It seems the reducer in the pipeline is receiving NAs from `WindowSummarizer` - is that expected?

**Comment by danbartl** [comment]
@fkiraly sorry do not get your comment, what do you mean by "seems the reducer in the pipeline is receiving NAs from WindowSummarizer"? I do not see WindowSummarizer in the example

**Comment by fkiraly** [comment]
In the PR that adds the NA error message, PR #3405, one of the regression tests that involves it fails, because `WindowSummarizer` produces NA for some reason where it is unexpected. I think?
