### ISSUE TITLE
[ENH] Forecasting composition to infer sp param from data

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#3417]
**Is your feature request related to a problem? Please describe.**
The `sp` param of forecasters could be automatically infered from data e.g. by means of FFT.

**Describe the solution you'd like**
Having a composition e.g. `AutoSP()` that will set `sp` param of given forecaster. Optionally we could predict multiple seasonalities as a `List[int]`. 

**Additional context**
FFT implementation, see #3406

**Comment by fkiraly** [comment]
This exists, it lives in `param_est` (experimental module). Currently it is using acf/pacf, but fourier spectrum is another obvious option (not implemented, see #3406).

**Comment by aiwalter** [comment]
oh was not aware that there is a module for it 👀 . But how can we use those param estimators in combination with e.g. a forecaster as I was aiming for with the `AutoSP`? We might need a composition anyway?

**Comment by fkiraly** [comment]
also exists 😁 , look at `PluginParamsForecaster`

**Comment by fkiraly** [comment]
that was nice and quick 😀
