### ISSUE TITLE
Integrate tbats package

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#342]
**Is your feature request related to a problem? Please describe.**
Integrate tbats package: https://pypi.org/project/tbats/

**Describe the solution you'd like**
Adding tbats as a soft dependency and wrapping it or copying code.

**Comment by mloning** [comment]
@aiwalter in case you're interested!

**Comment by aiwalter** [comment]
@mloning  I am working on this. Can this be a regular dependency or should it also be a soft dependency?

**Comment by mloning** [comment]
I generally prefer soft dependencies, unless it's used in several places in the code base.

**Comment by mloning** [comment]
Closed by #527
