### ISSUE TITLE
[ENH] Modelling seasonality with fourier terms

### ISSUE THREAD

**Issue by eenticott-shell** [alan-turing-institute/sktime#3454]
**Is your feature request related to a problem? Please describe.**
Seasonality can be modelled by using a matrix of fourier terms as exogenous data. The process is described here: https://robjhyndman.com/hyndsight/longseasonality/ this can be useful to include multiple seasonality in ARIMA models, where sarima is very slow to fit.

**Describe the solution you'd like**
A function that takes as input a `DateTimeIndex`, the fourier order desired and which seasonalities to include and outputs a matrix of fourier terms that can model seasonality effects when included as exogenous data.

If this feature already exists please let me know, I couldn't find anything upon a quick search.

**Comment by fkiraly** [comment]
that is this, no?
https://github.com/alan-turing-institute/sktime/pull/3374
should be in the next release

That's `sktime`, the time from issue to solution is negative :-)

**Comment by fkiraly** [comment]
@ltsaprounis, did we perhaps forget to add this to the API docs?

**Comment by fkiraly** [comment]
oh, no, it's there, but it's not on stable, only on latest docs

**Comment by eenticott-shell** [comment]
Good to know! Thanks @fkiraly, this is the feature I was looking for so I will close the issue.
