### ISSUE TITLE
When the index of the data is a timestamp, it leads to "TypeError: Addition/subtraction of integers and integer-arrays with Timestamp is no longer supported.  Instead of adding/subtracting `n`, use `n * obj.freq`"

### ISSUE THREAD

**Issue by shruthibalaji2307** [alan-turing-institute/sktime#346]
**Describe the bug**
When I use a Series which has TimeStamp as the index, I get the following error in various steps:

**TypeError**: _Addition/subtraction of integers and integer-arrays with Timestamp is no longer supported.  Instead of adding/subtracting `n`, use `n * obj.freq`_

This error occurs when I try a plot (plot_ys) and when I try to predict (y_pred = forecaster.predict(fh)).

For fixing the plot, I modified the file "sktime/utils/plotting/forecasting.py" in the line:

_-continuous_index = np.arange(y.index.min(), y.index.max() + 1)
+continuous_index = np.arange(1, len(y) + 1)

>> After the above change, I got a plot with the timestamp as the index.

![image](https://user-images.githubusercontent.com/48148271/87846860-b9046280-c8f0-11ea-9c48-56096e428773.png)

Similarly, for predict, the following file needs fixing : sktime/forecasting/base/_fh.py in line:

-values = self + cutoff 
+values = (self * cutoff.freq) + cutoff

Because, here direct addition is not possible due to the TimeStamp index. 

**To Reproduce**
https://gist.github.com/shruthibalaji2307/e10dcae314773e75f6a03d4c43246f71

**Input Data**
[nation_level_daily.zip](https://github.com/alan-turing-institute/sktime/files/4941236/nation_level_daily.zip)

**Expected behavior**
I expected plot_ys to plot my data without cribbing about the TimeStamp index. It only works when I use a simple numerical index.

**Versions**
Linux-5.4.0-40-generic-x86_64-with-glibc2.29
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
NumPy 1.19.0
SciPy 1.5.1
Pandas 1.0.5
sktime 0.4.1

**Code Changes required**
1) "sktime/utils/plotting/forecasting.py" :

_-continuous_index = np.arange(y.index.min(), y.index.max() + 1)
+continuous_index = np.arange(1, len(y) + 1)

2) sktime/forecasting/base/_fh.py in line:

-values = self + cutoff 
+values = (self * cutoff.freq) + cutoff

3) Wherever addition/subtraction is done on the index of the data.
</details>

**Comment by mloning** [comment]
Dear @shruthibalaji2307 thanks for the detailed bug description. We currently don't support date time indices. I believe adding support for them will require some substantial work. Would you be interested in working on that?

**Comment by shruthibalaji2307** [comment]
Hello @mloning , I would be very interested. Sktime is a huge step towards easing time series analysis in Python and it would be great if we could support datetime indices as a part of it. Shall I go ahead and create a feature request and assign it to myself?

Also, please let me know if you have specific requirements in mind. I will pick it up right away.

**Comment by bingblackbean** [comment]
I am not sure if this bug will be fixed soon in coming version. By now I change the code to allow it support timestampindex in the series. Meanwhile, I also check if the timestamps are continuous.
`        # scatter if only a few points are available
        if isinstance(y.index, pd.DatetimeIndex):
            y = y.asfreq(pd.infer_freq(y.index))
            is_continuous = np.var((y.index - y.index.shift(1)).seconds)==0
        else:
            continuous_index = np.arange(y.index.min(), y.index.max() + 1)
            is_continuous  = np.array_equal(y.index.values, continuous_index)

        if len(y) < 3 or not is_continuous:
            ax.scatter(y.index.values, y.values, label=label)
        # otherwise use line plot
        else:
            ax.plot(y.index.values, y.values, label=label)`

**Comment by mloning** [comment]
Hi all, and thanks @bingblackbean for sharing your solution here! 

We added much more comprehensive date-time support in PR #392. It hasn't made it's way into a release yet, but should work when you install the development verision. 

You can find my solution for the plotting function [here](https://github.com/alan-turing-institute/sktime/blob/f13c9e189ef35796bcc2f3dc4ce00c8e5504932c/sktime/utils/plotting/__init__.py#L16) (might have also renamed it!)

I'll close this issue for now, please open a new one if anything else doesn't work!
