### ISSUE TITLE
Supporting datetime indices

### ISSUE THREAD

**Issue by shruthibalaji2307** [alan-turing-institute/sktime#347]
**Is your feature request related to a problem? Please describe.**
When we load a pandas series as input data, Python datetime indices are not supported by sktime, only simple numerical indices are supported.  

**Describe the solution you'd like**
The datetime index provides much more clarity while plotting and analyzing the data. Sktime must support series that have a datetime index and add appropriate computations in the datetime context.

**Describe alternatives you've considered**
I have tried using the numerical index, but it does not clearly indicate the unit of the time, whether it represents seconds, minutes, days, weeks, or months.

**Additional context**
More details about this are posted in this Bug : https://github.com/alan-turing-institute/sktime/issues/346

**Comment by mloning** [comment]
Thanks for creating the issue and volunteering to work on this! 

I think you already identified the main parts of the code where changes would have to be implemented: the handling of observation (oh) and forecasting horizons (fh). 

Adding support for date time indices will also require a lot more extensive unit testing. Some package that we interface may not support date time indexing (e.g. [pmdarima](https://github.com/alkaline-ml/pmdarima) as far as I remember).

**Comment by shruthibalaji2307** [comment]
As far as I've seen, the arima class of the pmdarima package wraps the statsmodel's ARIMA. And it appears that statsmodels supports date time indexing. Source : https://alkaline-ml.com/pmdarima/1.0.0/_modules/pmdarima/arima/arima.html

I will do elaborate Unit testing anyway after making appropriate code changes. Can you please assign this to me?

**Comment by fkiraly** [comment]
@mloning, would it perhaps also be a good time to think about the API and use of indices? Currently, the API is integer index (`iloc`) based, and time indices are ignored both in application of algorithms, and in the horizon interface, if I'm not mistaken. Shall we think about specs?

**Comment by fkiraly** [comment]
Alright @mloning, @shruthibalaji2307, I made a proposal on how support for datetime indices could look here, please have a look at [this wiki page](https://github.com/alan-turing-institute/sktime/wiki/Design-proposal:-forecasting-API-re-work-including-support-for-datetime-indices).

There are two versions, and the "luxurious" version relies on a bit o a re-work of input/output checks that allow for multiple input/output types, I've also added a [design for that](https://github.com/alan-turing-institute/sktime/wiki/Design-proposal%3A-multi-type-input-output) to the wiki.

Comments and criticism very much appreciated. 
I'd prefer the luxurious version, but it might be a bit of work to implement.

**Comment by shruthibalaji2307** [comment]
Hello @fkiraly , I took a look at your design document. As I was going through the sktime repository, I was also inclining toward something along the lines of the luxurious implementation you have mentioned.

However, I was wondering how the input types like dataframes (univariate/multivariate) will be passed on to the [statsmodel](https://www.statsmodels.org/stable/index.html)/[pmdarima](http://alkaline-ml.com/pmdarima/) forecasters during fit and predict. I know that [pmdarima](http://alkaline-ml.com/pmdarima/) accepts a pandas series with a datetime index as input. But how will dataframes be handled?

**Comment by fkiraly** [comment]
>However, I was wondering how the input types like dataframes (univariate/multivariate) will be passed on to the statsmodel/pmdarima forecasters during fit and predict. I know that pmdarima accepts a pandas series with a datetime index as input. But how will dataframes be handled?

Well, if a given model can't handle it, it will throw an error, e.g., a `ValueError` "this model cannot handle multivariate series :-(" or similar. Perhaps we want to have some estimator tags on what inputs an implemented methods can handle, similar to the experimental `sklearn` [estimator tags](https://scikit-learn.org/stable/developers/develop.html#estimator-tags).

**Comment by mloning** [comment]
Closed by #392
