### ISSUE TITLE
[DOC] Enhance documentation on data formats and conversions from one format to another 

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#348]
#### Suggest a potential solution
* Improve [data loading tutorial notebook](https://github.com/alan-turing-institute/sktime/blob/master/examples/loading_data.ipynb)
* Improve docstrings on [conversion functions](https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/data_processing.py)

**Comment by ayan-biswas0412** [comment]
@mloning can I work on this ? Can you give me some more info such that I can start my work , this project is very interesting and I am loving it.
Previous [PR](https://github.com/alan-turing-institute/sktime/pull/667) is passing all the tests now so I can move to a new work , Can you assign me in this

**Comment by mloning** [comment]
Hi @ayan-biswas0412 yes sure: 

There are different ways to represent panel data: 
* 3d numpy arrays with shape (n_instances, n_variables, n_timepoints)
* nested pandas 
* long format

You can find different conversion functions to move between these formats here: https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/data_processing.py

In the tutorial, we need to explain each format and illustrate how to convert data between them. Does that help?

**Comment by ayan-biswas0412** [comment]
> Hi @ayan-biswas0412 yes sure:
> 
> There are different ways to represent panel data:
> 
> * 3d numpy arrays with shape (n_instances, n_variables, n_timepoints)
> * nested pandas
> * long format
> 
> You can find different conversion functions to move between these formats here: https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/data_processing.py
> 
> In the tutorial, we need to explain each format and illustrate how to convert data between them. Does that help?

Thank you for your guidance I will look into it definitely

**Comment by pomt98** [comment]
Hi there! Any updates on this?
If not, I would love to get started on this for the time being!

**Comment by ayan-biswas0412** [comment]
> Hi there! Any updates on this?
> If not, I would love to get started on this for the time being!

I am not working on this you can take this if permitted by admin

**Comment by mloning** [comment]
Yes sure @pomt98 please take a look if you're interested!

**Comment by abhishek-parashar** [comment]
hey, any update on this one? If anybody is not working on it. I would love to take it.

**Comment by mloning** [comment]
Hi @abhishek-parashar looks like no-one is working on this at the moment.

**Comment by abhishek-parashar** [comment]
Hey @mloning can I take this I will be reverting back with pr in one to two days.

**Comment by nihal-rao** [comment]
Hi @abhishek-parashar are you working on this? If not I would like to take this up.

**Comment by fkiraly** [comment]
This is covered in the `AA_datatypes_and_datasets` notebook added in #1232.
