### ISSUE TITLE
Feature request: Leveraging good forecasting methods implemented in R packages

### ISSUE THREAD

**Issue by AlexPars** [alan-turing-institute/sktime#351]
It would be useful to incorporate in sktime some of the forecasting methods implemented in R packages, and in particular the packages done by Prof. Hyndman and his team: fable, forecast, feasts, seer, hts, thief (see https://robjhyndman.com/software/).
This way one can have access in Python to those methods, through the excellent API that was designed for sktime.

I know that a few of the methods  in those R packages were already implemented in sktime. For the remaining ones, a possible approach would be not to reimplement them, but rather to call these packages within sktime, given that R packages can be utilized within Python code (and viceversa).

**Comment by mloning** [comment]
Yes, that sounds like good suggestion!
