### ISSUE TITLE
Feature request: additional forecasting metrics

### ISSUE THREAD

**Issue by AlexPars** [alan-turing-institute/sktime#352]
It would be quite useful to incorporate additional forecasting metrics described in [Botchkarev (2019](https://www.informingscience.org/Publications/4184)) and [Gasthaus et al. (2019)](http://proceedings.mlr.press/v89/gasthaus19a.html)

**Comment by mloning** [comment]
Thanks for the suggestion! Would appreciate a PR.

**Comment by AlexPars** [comment]
I will try to do a Pull Request next weekend or the weekend after.

Also, what would be your perspective on incorporating into sktime a framework like [this one](https://cran.r-project.org/web/packages/ForecastTB/vignettes/Introduction_to_ForecastTB.html) for comparing forecasting performance among forecasting methods?

**Comment by mloning** [comment]
We're very supportive of comparative benchmarking frameworks! We've implemented a [framework for time series classification](https://github.com/alan-turing-institute/sktime/blob/master/examples/04_benchmarking.ipynb) already, based on the API design in [mlaut](https://github.com/alan-turing-institute/mlaut), and we're planning on extending that to forecasting and other learning tasks. I'm happy to collaborate on this.

**Comment by mloning** [comment]
Closing in favour of https://github.com/alan-turing-institute/sktime/issues/671
