### ISSUE TITLE
[DOC] automated generation of estimators table

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#354]
#### Describe the issue linked to the documentation

Following an idea by @lynssi, we could think about generating the estimators.md automatically following some parsing convention and automated document compilation.

This would be extremely useful i.m.o., as such an auto-generated table would automatically give a look-up of any papers/documents describing algorithms, perhaps tutorials too, and who is currently the maintainer.

It would also be important since the current version is not too well-curated, since it requires much manual intervention.

#### Suggest a potential alternative/fix

I´m not sure how this would practically work though.
It would require an html or md page to be generated, based on pre-defined tags and hierarchies.

**Comment by mloning** [comment]
I think an ideal solution would be to integrate this into the [sphinx](https://www.sphinx-doc.org/en/master/)-generated API reference on our website, so that all documentation is in one place: literature references, author/maintainer details and docstrings.

**Comment by fkiraly** [comment]
But sphinx does not generate a "single table" overview like in estimators.md. Or at least, I would not see how your solution of (ab-)using sphinx would do this, @mloning?

Further, the taxonomy that sphinx applies is that of code hierarchy, not a semantic hierarchy which is more useful to the user?

Though if it were true, i.e., you could use sphinx to generate multiple pieces of overview documentation, e.g., tables according to different tags and hierarchies, that would be the optimal solution ... probably?

**Comment by mloning** [comment]
Our code hierarchy is already aligned with a user-oriented semantic hierarchy for most parts, and we should work towards improving that further in the future with new additions to sktime (more comprehensive typing of transformers, etc). 

My suggestion is to create an API reference similar to the [scikit-learn's API reference](https://scikit-learn.org/stable/modules/classes.html), but with a third column for author/maintainer.

**Comment by fkiraly** [comment]
>Our code hierarchy is already aligned with a user-oriented semantic hierarchy for most parts, and we should work towards improving that further in the future with new additions to sktime (more comprehensive typing of transformers, etc).

Agreed.

>My suggestion is to create an API reference similar to the scikit-learn's API reference, but with a third column for author/maintainer.

Three-quarters-agreed - I wouldn´t want utility functions in there, but I would like a 4th column with literature refs.

But mainly agreed. I just don´t know how to generate such a page automatically...

**Comment by lynnssi** [comment]
> > My suggestion is to create an API reference similar to the scikit-learn's API reference, but with a third column for author/maintainer.
> 
> Three-quarters-agreed - I wouldn´t want utility functions in there, but I would like a 4th column with literature refs.
> 
> But mainly agreed. I just don´t know how to generate such a page automatically...

Checked scikit-learn. It looks like their [API reference](https://github.com/scikit-learn/scikit-learn/blob/master/doc/modules/classes.rst) is not generated automatically, but manually (see [this issue](https://github.com/scikit-learn/scikit-learn/issues/9718)  as an example).

One package that might provide a solution is [pdoc](https://pdoc3.github.io/pdoc/). It generates a set of html files based off the docstrings in the code. It is configurable and should be able to make use of the __author__ variable in each file. I installed it and had it generate html files for the package. Here are some screenshots of what it looks like. It would take some work to configure it properly and combine the html files into a single API reference, but easier than starting from scratch.

![image](https://user-images.githubusercontent.com/17050655/88078472-86ee3d00-cb4a-11ea-9563-e02011458979.png)
![image](https://user-images.githubusercontent.com/17050655/88078134-13e4c680-cb4a-11ea-8c3a-e231a5426968.png) (
![image](https://user-images.githubusercontent.com/17050655/88078353-5efed980-cb4a-11ea-87a9-ea1f1c90a50a.png))

I looked at some other packages, but I don't know if any exactly generate the API Reference page.

**Comment by fkiraly** [comment]
@lynnssi, thanks for looking into this!

We already have an API reference [here](https://sktime.org/api_reference.html) which is great, though we (or at leasts I) don´t know how you could get multiple columns - e.g., to add maintainer or paper link.

**Comment by mloning** [comment]
Closed in favour of #704
