### ISSUE TITLE
[DOC] documentation to summarize the classification algorithms and their categories 

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#355]
#### Describe the issue linked to the documentation

Entry into the world of TSC requires external reading
 
#### Suggest a potential alternative/fix

A description of the categories of algorithms, summary of the TSC algorithms available  and links to the relevant papers would be really helpful

**Comment by lynnssi** [comment]
I would be happy to do the external reading and write this description + references. Where should this description be committed?

**Comment by mloning** [comment]
This seems to be a larger documentation project. Perhaps we can start with a shared [hackmd](https://hackmd.io) document for easy collaboration. When it's finished we can add it to our website and selected parts to the tutorial notebooks? Having another blog post about it may also be useful. What do you think @TonyBagnall?

**Comment by fkiraly** [comment]
agreed, let´s try to use this to align on what precisely is the "desired goal" of the documentation project(s). Might be worthwhile discussing also in the context of #354.

E.g., what kind of documentation - besides API reference of course - would be most useful to users and community members?

Also, what is the "end state" of documentation and curation, and associated roles, e.g., a dedicated community role for documentation?

**Comment by TonyBagnall** [comment]
The contribution is really helpful, thanks. I'm not too sure about wider docs, I think Markus and Franz have a better take on it

**Comment by lynnssi** [comment]
@mloning I'd be happy to write a blog post (or two) on this topic. I think there would be a lot of interest. 

> E.g., what kind of documentation - besides API reference of course - would be most useful to users and community members?

I think documentation summarizing the types of classification algorithms and detailed documentation explaining how each of the algorithms work would be really useful. Aside from papers, resources on the topic are scarce. I have often referred to the scikit-learn User Guides (e.g. [Clustering User Guide](https://scikit-learn.org/stable/modules/clustering.html)) in my work and I think it would be beneficial to have something similar for sktime.

**Comment by fkiraly** [comment]
>I think documentation summarizing the types of classification algorithms and detailed documentation explaining how each of the algorithms work would be really useful.

Agreed - I would find the same useful for *all the components* (transformers of various kinds, reducers, compositors). I have a somewhat encyclopaedic vision of a register of components, with different tags and taxonomies:
* scientific type (e.g., ts classifier, forecaster, transformer of specific type such as series-to-series)
* algorithm type (e.g., neural network, distance-based, etc)
* version/implementation, owner/maintainer and such

I thought the explanation of how individual algorithms work should be accompanied by a tagged register of all of them, and an explanation of the different kinds of algorithm there are (forecaster, classifier, etc) - like in a library.
Couldn't convince the British Library to do this, but I still think it would be enormously useful (not just for time series algorithms).

What are your ideas around what kind of documentation would be useful, @lynnssi?

We were also going to discuss somtime soon on a more strategic level where our documentation should move to, and what to prioritize. Would you be interested to participate in such a discussion?

**Comment by lynnssi** [comment]
> What are your ideas around what kind of documentation would be useful, @lynnssi?
Possible types of documentation:
- High-level documentation: types of classification algorithms, reduction, etc
- How each algorithm works 
- Examples and tutorials -- especially showing how everything works together
 
> We were also going to discuss somtime soon on a more strategic level where our documentation should move to, and what to prioritize. Would you be interested to participate in such a discussion?
I would be interested in this discussion.

**Comment by mloning** [comment]
Here's a good graph for explaining dictionary-based algorithms: https://pyts.readthedocs.io/en/stable/auto_examples/approximation/plot_sax.html

**Comment by fkiraly** [comment]
>I would be interested in this discussion.

sometime early/mid august probably? Please leave Markus with an email message and we´ll coordinate (need to have a quick internal connect).
Anyone else interested in this issue or contributing to docs, please do the same.

**Comment by mloning** [comment]
Hi @lynnssi, we think it's probably best to create a new user guide in which we give an overview of sktime and explain the different modules and algorithms. I've created an issue here for more details: #361. What do you think?
