### ISSUE TITLE
Interface to DICOM data

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#356]
**Is your feature request related to a problem? Please describe.**

DICOM for data is standard for storing images in hospitals. However, it can also be used to store "waveform" data such as ECG. Analysing this data with sktime requires expertise in converting and formatting. It would be great to embed tools to transform DICOM time series into ts format.

**Describe the solution you'd like**

there are existing DICOM interfaces in python. These should be explored and hopefully facilitate the translation. 

1) This should involve code to form a single file including time series for a single patient record, where meta information is stored in the .ts file header.  
2) post processing code to form different problem types such as clustering, classification and anomaly detection. 

there is a lot of leg work to make this happen and we will need to define some more meta info in the .ts format. 

The whole issue of data extraction/formatting might be better in a sister package at sktime.org?

**Comment by zbenmo** [comment]
I'm new here, yet happy to jump in. This seems like a useful feature(s) / tool(s) / tutorial. Happy for additional advice from sktime maintainers and for where to obtain DICOM that relate to ECG for example. Believe I can find something in Kaggle  or elsewhere.
