### ISSUE TITLE
[DOC] Add NoLiTSA to related software

### ISSUE THREAD

**Issue by woj-i** [alan-turing-institute/sktime#358]
#### Describe the issue linked to the documentation

I found useful library NoLiTSA for time-series analytics, that is not on the list of related software of sktime.

#### Suggest a potential alternative/fix

Please add https://github.com/manu-mannattil/nolitsa to the list of related software.

**Comment by mloning** [comment]
Thanks for the addition! I'll add it to the list. Could you provide a short summary of what it does?

Perhaps we should move the list from the wiki into our docs so that people can update it directly with PRs.
