### ISSUE TITLE
Design/implement multivariate ensembles and composites

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#36]
I thought it worth spelling out the structure of how people can use and implement classification algorithms in sktime. The balance is between modularity and efficiency. This is summarising what we have, but I think it worth it as a we try to widen the development base. 

Modular approach:
I propose two classifiers as pipelines
TimeSeriesEnsemble (or time_series_ensemble? need to resolve naming conventions. Another ticket!). This pipeline is a set of transforms and an estimator/classifier as the last element. The logic is that the transforms are applied independently to each member of the ensemble, and the final estimator is the base classifier for the ensemble. The transformers are *not* applied sequentially. They are applied independently to the data and the results are concatenated. They must be Randomizable, so that a different transform is applied for each ensemble member. The transformers and the base classifier should be seedable for reproducability.

**Comment by TonyBagnall** [comment]
Non configurable approach. 
Estimator passed a pandas, and internally sorts out what to do. The assumption is that each column is a dimension of a multiviariate time series, with dimension 1 in column 1. It is up to the classifier to decide if it can handle multivariate/missing/unequal length, through some standard Capabilites mechanism perhaps (thats how Weka does it) all of which will be encoded when we extend pandas. For the univariate equal length case we start with, simply extract the first dimension.

Instantiations: within the HIVE-COTE directory, bespoke implementations of TSF, RISE, BOSS, EE, ST and HIVE-COTE.

**Comment by mloning** [comment]
For implementation, see https://scikit-learn.org/stable/modules/ensemble.html

**Comment by mloning** [comment]
* ConcatenatorTransformer which concatenates multivariate time series data into long univariate time series data 
* ColumnEnsemble (possibly with options for stacking, CAWPE style voting, etc), similar to ColumnTransformer
* bespoke methods in specific estimators to handle multivariate data

**Comment by mloning** [comment]
Column-wise ensemble implemented through #99

**Comment by TonyBagnall** [comment]
its probably just me, but I find column-wise ensemble a confusing name that requires a deep understanding of the data structure model. I would call it DimensionWise or something. Still, lets close this.

**Comment by mloning** [comment]
I agree, it's not the most intuitive, but I prefer the column terminology over the dimension one because (i) given our data container, we actually refer to columns, whereas dimensions could refer to something else as well, e.g. the `shape` of an array, and (ii) because it's similar as a compositor to sklearn's `ColumnTransformer`. So `ColumnEnsembleClassifier` and `ColumnConcatenator` sounds about right to me.
