### ISSUE TITLE
[DOC] Add glossary for common terms 

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#363]
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/glossary.html

### Initial terms
| Term | Description |
| ------- | ------ |
| `n_instances` | number of instances, represented by rows in data container, instances represent i.i.d. samples |
| `n_columns` | number of columns in data container, where columns represent different kind of measurements, cells in columns may contain time series or primitives, data in columns is type homogeneous |
| `n_timepoints` | number of time points in a time series or sequence at which observations were made |

**Comment by RNKuhns** [comment]
@mloning I think we can consider this closed based on updated documentation having a glossary.
