### ISSUE TITLE
Rocket Transform across multiple cores

### ISSUE THREAD

**Issue by jmrichardson** [alan-turing-institute/sktime#367]
**Is your feature request related to a problem? Please describe.**
Is there a plan to make Rocket.transform parallelized?  Hoping to distribute the load across multiple cores if possible.

**Describe the solution you'd like**
specify n_jobs when calling rocket.transform(X, n_jobs=x)

**Comment by mloning** [comment]
@angus924 any thoughts on this?

**Comment by angus924** [comment]
Hi @jmrichardson and @mloning, this should already be happening automatically, it's always been part of the implementation (provided it's working properly).  Is this not working for you, i.e., can you can you see that only one or some subset of cores is being used?

**Comment by mloning** [comment]
Perhaps we could expose that choice to the user using the familiar `n_jobs` argument from scikit-learn and internally numba's [`set_num_threads`](https://numba.pydata.org/numba-doc/latest/user/threading-layer.html#numba.set_num_threads)?

**Comment by angus924** [comment]
That's a possibility.  This is new to me, I'd have to play around with it a bit.  In the meantime, if I understand correclty, it should already be possible (as a kind of workaround) to do this by simply calling, e.g., `set_num_threads(2)` anywhere in your code before you run the transform.
