### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#37]
I will by default use camel case for classifier names etc. This is just my habit. Can we formalise some naming conventions to help me please? Probably best to copy sklearn?

**Comment by jasonlines** [comment]
I believe the convention in python is that camel case would be the way to go for classifier names :) File names and modules should be formatted like python identifiers, however. e.g.: 

a_module_name/a_file_name.py
class MyClassifierName(): ...
