### ISSUE TITLE
Parallelize algorithms

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#381]
**Is your feature request related to a problem? Please describe.**
- [ ] [Time series forest](https://github.com/alan-turing-institute/sktime/blob/master/sktime/classification/interval_based/_tsf.py)

**Describe the solution you'd like**
* Replace loops with joblib parallelized computations or numba.

**Comment by kkoziara** [comment]
Hey, I can take this task.

**Comment by mloning** [comment]
Hi @kkoziara that would be awesome! Thanks! 

Please take a look at our [contributing guidelines](https://github.com/alan-turing-institute/sktime/blob/master/CONTRIBUTING.md). Let me know if you have any more questions!
