### ISSUE TITLE
[DOC] Mismatch between 0.4.1 docs and release

### ISSUE THREAD

**Issue by thorbjornwolf** [alan-turing-institute/sktime#386]
Thank you for spending some of your valuable time on open source 🤗 

#### Describe the issue linked to the documentation

The documentation for NaiveForecaster includes "drift" and says 0.4.1 in the upper left corner. [Link, but not a permalink](https://sktime.org/modules/auto_generated/sktime.forecasting.naive.NaiveForecaster.html#sktime.forecasting.naive.NaiveForecaster). The package version 0.4.1 does not support "drift", but fails with `ValueError: Unknown strategy: drift; expected one of ('last', 'mean', 'seasonal_last')`.

I don't see a way to access the docs for older versions.

#### My hypothesis
I believe that
1. docs are autobuilt and deployed from master on new changes
    - See bullet 4 in #360: "PRs into dev do not trigger doc builds, so changes to tutorial notebooks are not included in CI checks;"
2. master is often ahead of the latest release
3. package version in master is only updated at release time
     - see [the latest bump](https://github.com/alan-turing-institute/sktime/commit/98ae0a1d9a3afcdcc0602a46f94a8e5aff292d28#diff-892e5b4461cd224a9f593fed8830d659)
4. Consequently, the hosted docs are ahead of the latest release, while retaining the version number of the latest release. Some confusion may arise 😁 

So when #383 enriched master with all the good stuff from dev, updated docs were built and deployed under the current version, and no package release was made.

#### Suggest a potential alternative/fix

I sure don't know what would be the best(tm) way of handling this, but here's a few ideas for starters:

1. Only build docs when also cutting a release (but this goes against the wish to have updated tutorial notebooks)
2. Separate tutorial notebooks from the API docs so they can be built independently
3. Differentiate among doc versions, so one could view either 0.4.1 or master/cutting edge.

Thank you for your attention. Cheers!

**Comment by mloning** [comment]
Thanks for raising the issue! We actually thought about a few things that could go wrong when we changed the workflow over to master, but this one didn't cross our minds! 😄 

Differentiating between doc version seems like a good suggestion. I've seen this in other repos, but wouldn't know where to start. Would you be interested in setting that up?

**Comment by mloning** [comment]
https://readthedocs.org seems like the way to go. @thorbjornwolf if you're interested in setting up readthedocs that would be highly appreciated!

**Comment by thorbjornwolf** [comment]
Hi @mloning! I'm afraid I won't find the time anytime soon. It _does_ sound like a very good exercise in a generally applicable open-source skill, though. I wonder if there exist cross-project opensourcers who have experience with this 🤔

**Comment by mloning** [comment]
Fixed by #395
