### ISSUE TITLE
[BUG] ThetaForecaster-Deseasonalizer returns numpy.array

### ISSUE THREAD

**Issue by arainboldt** [alan-turing-institute/sktime#396]
**Describe the bug**

**To Reproduce**

```python
from sktime.forecasting.compose import ReducedRegressionForecaster
from sktime.forecasting.theta import ThetaForecaster
import pandas as pd
import numpy as np
y = pd.Series("34 34 39 46 47 50 53 58 61 58 57 59 64 67 72 74".split(' ',-1)).astype(float)
model = ReducedRegressionForecaster(regressor=ThetaForecaster(smoothing_level=.2,sp=1), window_length=3, strategy="recursive")
model.fit(y)
model.predict(pd.Series(list(np.arange(3) + y.index[-1])))

```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by mloning** [comment]
Thanks @arainboldt for posting the bug report! 

I'm not sure what you want to achieve. If you want to use the `ThetaForecaster` for forecasting, you could simply run:

```python 
from sktime.forecasting.theta import ThetaForecaster
import pandas as pd
import numpy as np
y = pd.Series("34 34 39 46 47 50 53 58 61 58 57 59 64 67 72 74".split(' ',-1)).astype(float)
model = ThetaForecaster(smoothing_level=.2,sp=1)
model.fit(y)
model.predict(np.arange(3) + y.index[-1])
```

Your code suggests that you want to reduce the forecasting problem to a tabular regression problem. In that case, you could replace the `ThetaForecaster` with any scikit-learn regressor. For example:

```python
from sktime.forecasting.compose import ReducedRegressionForecaster
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
import numpy as np
y = pd.Series("34 34 39 46 47 50 53 58 61 58 57 59 64 67 72 74".split(' ',-1)).astype(float)
model = ReducedRegressionForecaster(regressor=RandomForestRegressor(), window_length=3)
model.fit(y)
model.predict(np.arange(3) + y.index[-1])
```

In either case, the error is not very helpful! We should check the passed regressor to make sure it's a tabular regressor.

**Comment by arainboldt** [comment]
@mloning thanks for the quick follow up and the recommendation. I was reading through the docs and came across the terms tabular regression along with direct reduction and recursive reduction. I'm not familiar with these terms. Where can I read more about them?

**Comment by mloning** [comment]
Take a look at this paper: Bontempi, Gianluca & Ben Taieb, Souhaib & Le Borgne, Yann-Aël. (2013). "Machine Learning Strategies for Time Series Forecasting."

We're also in the process of writing a user guide to explain these terms (#377), let me know if you're interested in contributing.

**Comment by arainboldt** [comment]
@mloning awesome! thanks for the references!
