### ISSUE TITLE
[BUG] build_tools.requirements.txt contains incompatible packages

### ISSUE THREAD

**Issue by SilvestrePerret** [alan-turing-institute/sktime#406]
**Describe the bug**

During the installation of build_tools, `pip` returns a warning/error message :
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

pmdarima 1.7.1 requires Cython<0.29.18,>=0.29, but you'll have cython 0.29.21 which is incompatible.
pmdarima 1.7.1 requires statsmodels<0.12,>=0.11, but you'll have statsmodels 0.12.0 which is incompatible.
```

**To Reproduce**

- clone the repository
- set up an virtual environment and open a shell in it
- `$ pip install --upgrade pip`
- `$ pip install -r build_tools/requirements.txt`

**Expected behavior**

Expect no error message.

**Additional context**

<details>First time trying to contribute here. Hope I didn't miss something obvious</details>

**Comment by mloning** [comment]
Thanks @SilvestrePerret for raising the issue. 

This is due to a bug that was introduced in statsmodels 0.12.1 (see https://github.com/statsmodels/statsmodels/issues/7019). But we had started developing based on the new version already. It has been fixed already. We're just waiting for a new release.

**Comment by mloning** [comment]
statsmodels 0.12.1 is now release, so hopefully we can resolve this now https://github.com/statsmodels/statsmodels/releases/tag/v0.12.1

**Comment by mloning** [comment]
There now also a new pmdarima release: https://github.com/alkaline-ml/pmdarima/releases/tag/v1.8.0 so we should be able to update our requirements.

**Comment by mloning** [comment]
This should now be fixed in the new release https://github.com/alan-turing-institute/sktime/releases/tag/v0.5.0
