### ISSUE TITLE
Instances about each algorithms

### ISSUE THREAD

**Issue by maisuiqianxun** [alan-turing-institute/sktime#417]
Would you mind providing a sample instance about each developed algorithm in the API reference? To a freshman, it is hard to use some algorithms without a simple example, such as "ColumnEnsembleClassifier" in "sktime.classification.compose". By the way, sktime is a wonderful python API and can I devote to developing this repository with you?

**Comment by mloning** [comment]
Hi @maisuiqianxun, thanks for reaching out! Check out our [example notebooks](https://github.com/alan-turing-institute/sktime/tree/master/examples). For the ColumnEnsembleClassifier go to the multivariate time series classification notebook. There's also a blog post of about the different kind of classification algorithms [here](https://towardsdatascience.com/a-brief-introduction-to-time-series-classification-algorithms-7b4284d31b97). 

Please let us know if that's helpful or where the docs could still be improved!

**Comment by maisuiqianxun** [comment]
Hello @mloning, thank you for your help, I find the example of the algorithm ColumnEmsembleClassifier in the multivariate time series classification notebook, which is helpful to my understanding of the corresponding algorithms. 

Thank you very much!

**Comment by mloning** [comment]
Great, glad I could help.
