### ISSUE TITLE
[DOC]add new software in Wiki

### ISSUE THREAD

**Issue by bingblackbean** [alan-turing-institute/sktime#419]
#### Describe the issue linked to the documentation
I cannot find the LoudML in the Related Software in wiki page.https://github.com/alan-turing-institute/sktime/wiki/related-software

Loud ML is an open source time series inference engine built on top of TensorFlow. It's useful to forecast data, detect outliers, and automate your process using future knowledge. here is link： https://github.com/regel/loudml
#### Suggest a potential alternative/fix
could you add it into the list?

**Comment by mloning** [comment]
Hi @bingblackbean, thanks, wasn't aware of LoudML! 

How about we move the list of related software from the wiki to the website? That should make it more visible and easier to edit by others (people could simply open a PR).
