### ISSUE TITLE
ModuleNotFoundError: No module named 'sktime.forecasting.all

### ISSUE THREAD

**Issue by yunusrf** [alan-turing-institute/sktime#427]
**Describe the bug**

Running the latest example code, 01_forecasting.ipynb,  from jupitor notebook through Binder  gives the error : 01_forecasting.ipynb

**To Reproduce**

Run the Binder from sktime gitbub repository and select the notebook example - 01_forecasting.ipynb
```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
v0.4.2
<details>
v0.4.2

</details>

**Comment by mloning** [comment]
Yes, sorry about that, this is related to #416

**Comment by shrinandj** [comment]
Complete newbie here. But I tried to download the two files in #416 locally and then tried the following steps. No luck. 

- Restarted `jupyter notebook`
- Opened `01_forecasting.ipynb` in a new browser window
- Still got the same problems of `ModuleNotFoundError: No module named 'sktime.forecasting.all'`

<img width="1426" alt="Screen Shot 2020-10-12 at 1 19 01 PM" src="https://user-images.githubusercontent.com/3084759/95787009-836fdb00-0c8d-11eb-885c-ec025b737b1f.png">

**Comment by mloning** [comment]
It's because the master is ahead of the latest release. So what you can do is checkout the latest release and then open the notebooks. 

On master, run:
```
git checkout v0.4.2
```

Or use this binder link: https://mybinder.org/v2/gh/alan-turing-institute/sktime/v0.4.2?filepath=examples

**Comment by yunusrf** [comment]
Thank you for the quick response. Installing from the development version seems to be working.

**Comment by mloning** [comment]
Hopefully fixed by #416
