### ISSUE TITLE
[DOC] Add example of vector forecasting

### ISSUE THREAD

**Issue by Lucius888** [alan-turing-institute/sktime#433]

**Comment by mloning** [comment]
Just to be clear, by multivariate forecasting you mean forecasting with exogenous variables (which some of our forecasters support)? Or vector forecasting (which we don't support yet)?

**Comment by Lucius888** [comment]
I am sorry . 
it‘s vector forecasting,thanks

**Comment by mloning** [comment]
As said, that's not implemented yet, but please see #432 for further discussion on design/implementation.

**Comment by ShahNewazKhan** [comment]
@mloning are there any examples of forecasting with exogenous variables?

thanks in advance!

**Comment by ShahNewazKhan** [comment]
looks like it might be stuck in this PR? https://github.com/alan-turing-institute/sktime/pull/376/files

**Comment by mloning** [comment]
Hi @ShahNewazKhan, it depends on the forecasting algorithm you want to use. Some are not defined with exogenous variables (e.g. exponential smoothing), others support it already (e.g. AutoARIMA), and for some we still need to implement it (e.g. reduction to regression). 

Here's an example with AutoARIMA: 

```python
from sktime.forecasting.all import * 

y, X = load_longley()
y_train, y_test, X_train, X_test = temporal_train_test_split(y, X)
fh = ForecastingHorizon(y_test.index, is_relative=False)

forecaster = AutoARIMA(suppress_warnings=True)
forecaster.fit(y_train, X_train)
y_pred = forecaster.predict(fh, X=X_test)
plot_series(y_train, y_test, y_pred, labels=["y_train", "y_test", "y_pred"])
```
![image](https://user-images.githubusercontent.com/21020482/101983954-246f1800-3c76-11eb-8a73-28fb6bff525d.png)

**Comment by mloning** [comment]
Let me know if you want to contribute to the open PR - it'd be great to extend this functionality. What's the use case you're working on?

**Comment by ShahNewazKhan** [comment]
> Let me know if you want to contribute to the open PR - it'd be great to extend this functionality. What's the use case you're working on?

@mloning my use case is reduction on a multivariate dateset for regression, I am definitely interested in contributing. Are you referring to this  https://github.com/alan-turing-institute/sktime/pull/390 PR?

**Comment by mloning** [comment]
Yes exactly! The reduction module needs some refactoring too to make everything a bit simpler and needs to be extended to handle exogenous data. Your help is very welcome!

**Comment by ShahNewazKhan** [comment]
@mloning I can most definitely help, can you point me towards what needs to be refactored and done?

**Comment by mloning** [comment]
@ShahNewazKhan I'll post more details here: #345
