### ISSUE TITLE
[DOC] classifiers missing bibtex reference

### ISSUE THREAD

**Issue by whackteachers** [alan-turing-institute/sktime#447]
#### Describe the issue linked to the documentation

The following classifier miss the bibtex reference to the paper for the algorithm:

- ColumnEnsembleClassifier in classification/compose/_column_ensemble.py

- TimeSeriesForestClassifier in classification/compose/_ensemble.py

- TemporalDictionaryEnsemble in classification/dictionary_based/_tde.py

- ProximityTree in classification/distance_based/_proximity_forest.py

- ShapeDTW in classification/distance_based/_shape_dtw.py

-  KNeighborsTimeSeriesClassifier in classification/distance_based/_time_series_neighbors.py 

#### Suggest a potential alternative/fix
add back the bibtex reference

**Comment by mloning** [comment]
Do we want to add them in the BibTeX format or simply some other standard format? 

Either way, we should add them under the References heading in the numpy docstring format.

**Comment by TonyBagnall** [comment]
hi, 
ColumnEnsembleClassifier in classification/compose/_column_ensemble.py
KNeighborsTimeSeriesClassifier in classification/distance_based/_time_series_neighbors.py

thanks for this, please add bibtext for now, and maybe link under references?

TimeSeriesForestClassifier in classification/compose/_ensemble.py
https://www.sciencedirect.com/science/article/pii/S0020025513001473

TemporalDictionaryEnsemble in classification/dictionary_based/_tde.py
@inproceedings{middlehurst20temporal,
  title={The Temporal Dictionary Ensemble {(TDE)} Classifier for Time Series Classification},
  author={Middlehurst, Matthew and Large, James and Cawley, Gavin and Bagnall, Anthony},
  booktitle={The European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases},
  year={2020}
}

ProximityTree in classification/distance_based/_proximity_forest.py
same as proximity forest, just copy from there
ShapeDTW in classification/distance_based/_shape_dtw.py
https://www.sciencedirect.com/science/article/abs/pii/S0031320317303710?via%3Dihub

**Comment by whackteachers** [comment]
> hi,
> ColumnEnsembleClassifier in classification/compose/_column_ensemble.py
> KNeighborsTimeSeriesClassifier in classification/distance_based/_time_series_neighbors.py
> 
> thanks for this, please add bibtext for now, and maybe link under references?
> 
> TimeSeriesForestClassifier in classification/compose/_ensemble.py
> https://www.sciencedirect.com/science/article/pii/S0020025513001473
> 
> TemporalDictionaryEnsemble in classification/dictionary_based/_tde.py
> @inproceedings{middlehurst20temporal,
> title={The Temporal Dictionary Ensemble {(TDE)} Classifier for Time Series Classification},
> author={Middlehurst, Matthew and Large, James and Cawley, Gavin and Bagnall, Anthony},
> booktitle={The European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases},
> year={2020}
> }
> 
> ProximityTree in classification/distance_based/_proximity_forest.py
> same as proximity forest, just copy from there
> ShapeDTW in classification/distance_based/_shape_dtw.py
> https://www.sciencedirect.com/science/article/abs/pii/S0031320317303710?via%3Dihub

so wt about ColumnEnsembleClassifier and KNeighborsTimeSeriesClassifier?

**Comment by TonyBagnall** [comment]
hi jason,  ColumnEnsembleClassifier and KNeighborsTimeSeriesClassifier are generic classifiers, they do not need a reference
