### ISSUE TITLE
Implement stumpy series-to-series transformer

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#450]
**Describe the solution you'd like**
Interface and wrap `stumpy.stump` in series-to-series transformer, alternatively as panel-to-panel transformer 

**Additional context**
See https://github.com/TDAmeritrade/stumpy/issues/249 for preliminary discussions

**Comment by utsavcoding** [comment]
@mloning As a part of MLH fellowship, I would like to take up this issue.
