### ISSUE TITLE
pandas dataframe conversion into sktime dataframe[BUG]

### ISSUE THREAD

**Issue by SaddamHussain84** [alan-turing-institute/sktime#451]
**Describe the bug**

I have attached the data format, it is CSV file , first column is id column and then from jan-16 to Dec-16, it is monthly electricity consumption of Con_1 to Con-11(11 different consumers) in the end their is target which describe  either customer is healthy or theft.
df = pd.read_csv("data_file.csv")
df.head()
![sampledataimage](https://user-images.githubusercontent.com/64782359/97338031-f0a18400-18bb-11eb-8edb-3a7140417bff.PNG)
I want to represent my data into this file format, can you help me.
I am trying to resolve this from past seven days please help me
![sktime](https://user-images.githubusercontent.com/64782359/97339420-87227500-18bd-11eb-8dd6-39c86aca0c28.PNG)

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by mloning** [comment]
Hi @SaddamHussain84, see if this works: 
```python
from sktime.utils.data_container import from_2d_array_to_nested
df = pd.read_csv("data_file.csv")
nested = from_2d_array_to_nested(df)
```
If you have equal length data, you can also use 3d numpy arrays with shape (n_instances, n_variables, n_timepoints). 

Let me know if this works!

**Comment by SaddamHussain84** [comment]
It worked, thanks God, why you have not mentioned in your tutorial sections. Since, most of the data for training machine learning models, is in this way, I have been troubled for days.
Thanks for solving my problem, i really appreciate your effort. Keep doing great work
