### ISSUE TITLE
Make sure all classifiers are seeded by random_state

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#459]
for reproducibility, all classifiers should be seeded by random_state. In our experiments, the random_state is set to the resampleID. This is not correctly set in all the considered classifiers. The current list to check is

all_classifiers = [
    "BOSSEnsemble", "TemporalDictionaryEnsemble", "MUSE", "WEASEL",
    "ProximityForest", "ElasticEnsemble", "KNeighborsTimeSeriesClassifier",
#"ShapeDTW",
    "RandomIntervalSpectralForest",
    "TimeSeriesForest",
    "ShapeletTransformClassifier", "MrSEQLClassifier", "RocketClassifier"
]

**Comment by dicicch** [comment]
I'd be happy to take a look at this. Does seeding always happen in the `fit` method, as it does in the `BOSSEnsemble`?

**Comment by dicicch** [comment]
Maybe an appropriate (if a little too generic) way forward for this would be to perform the following check for each of the estimators mentioned in the original issue:
* construct the estimator we're checking, `est`
* use `sktime.utils._testing.estimator_checks.check_estimator` to verify that `est` passes `check_fit_idempotent` when `random_state` is set.

This would at least tell us which estimators are immediately incorrect by showing that prediction results are not the same between runs even when `random_state` is set.

**Comment by mloning** [comment]
* We found that all algorithms are seeded with random state and that there is a test for this: `check_fit_idempotent`
* We found that in ensembles, all ensemble members may be seeded with the same seed and hence may not exhibit any variation. 

@dicicch any chance that you can push the code you worked on during the sprint to make sure that the different ensemble members aren't seeded by exactly the same seed?
