### ISSUE TITLE
[DOC] Developer guide (extension guidelines and scitype templates)

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#464]
From my comments in #420:

I think we very much need to write up template designs, type conventions, extension conventions. This information is typically not suitably covered by an auto-generated API reference, as it is distributed across classes - the generic template, and the conventions implemented in the concrete desendants. Sth like in sklearn dev guidelines could work, but I'd actually prefer to also have "formal" template definitions collected in one place. While the typing makes things clearer, it also makes the necessity to document the interface cleanly greater.

Opinions, @mloning, @TonyBagnall?

I'm not sure what the "final form" should be here, but I feel this needs to be manually written and curated, with any modification to template patterns and conventions.
Could live on the wiki, linked from user docs, or directly in the official docs.

Happy to contribute to this, but let's discuss first where it should live.

**Comment by mloning** [comment]
Hi @utsavcoding, this may be interesting to you too

**Comment by mloning** [comment]
Hi @fkiraly, I agree, we need better extension guidelines. I think we should write a "developer guide" in addition to the planned "user guide" and the scitype template should be part of that.

It should live in the docs. The wiki isn't very good for suggesting and reviewing changes collaboratively. I'm trying to slowly move away from the wiki for most things. 

We should merge in the user guide (#377) first though, even with only some basic information and place holders, that way other people can see it and may be interested in contributing. Having a work-in-progress warning at the top of the page should be fine. Similarly, I'm happy to merge in a basic structure of the developer guide. I believe some sections from CONTRIBUTING.md should eventually also be moved into the developer guide.

**Comment by fkiraly** [comment]
@mloning, writing on the extension guidelines.

Quick question on forecasting extension pattern.
Can you confirm the following:

To implement a new forecaster, one should inherit from `_SktimeForecaster` and precisely one of the two `[...]ForecastingHorizonMixin`-s.

The extender needs to implement:
* `fit`, writing to `self`
* `_predict` (not `predict`!), reading from `self`
* `update` (if the model can be run in update mode)
* `update_predict` (if the model can be run in update mode)

Optional implements:
* `compute_pred_int` for prediction intervals
* `_update_predict_single` for single-step update/predict
* `get_fitted_params` for fitted parameter inspection

noting that some of these methods are implemented in `_SktimeForecaster` and will hence not raise `NotImplementedError`?

**Comment by fkiraly** [comment]
@mloning, @big-o, can you please confirm?

Also pinging @aiwalter who went through the extension workflow recently (is the above what you did in #503?).

**Comment by big-o** [comment]
I would say it's better to implement `_compute_pred_err()` instead for prediction intervals. `compute_pred_int()` is just a wrapper for the private method that does some input validation and generic output formatting.

**Comment by aiwalter** [comment]
@fkiraly I have another issue that would be great to add in the developer guide here: https://www.sktime.org/en/latest/contributing.html#id18

When adding a new softdependency, the file `check_soft_dependencies.py` for the azure build has to be updatet accordingly.

**Comment by fkiraly** [comment]
@mloning, forgot to ping the draft here:
https://github.com/alan-turing-institute/sktime/wiki/Scitype-interface-specification:-forecaster

You gave me feedback earlier and said that conceptual model & specs should be preceded by a quick overview.
I've added that now - have a look. Is that useful?

**Comment by fkiraly** [comment]
@aiwalter, @big-o, feel free to look as well - I haven't added much detail about `_SktimeForecaster` yet because of #510.

On a side note: what I think is often find very helpful is a template class in the "code template" sense - i.e., an example class where all that is missing is the core logic, and comment blocks tell you what to fill in. Do we have sth like that?

**Comment by mloning** [comment]
Thanks @fkiraly, in terms of exposition, I'd would have a very concise description at the top, perhaps even a code skeleton, and then discuss key points in more detail below. 

For example:
```python
class MyForecaster(BaseForecaster, <forecasting-horizon-mixin>):

    def __init__(self, <hyper-parameters>):
        ...

    def fit(self, y, X=None, fh=None):
        ...
```

**Comment by fkiraly** [comment]
@mloning, would the following help:
* create the "fill-in code template" as suggested - I can take a look at this if you suggest the best current python file to "convert". the `NaiveForecaster`?
* use the code template to create the preamble.

Regarding concise description: I added the checklist which I thought would satisfy that requirement. Do you not think this is suitable as such? If not, why is this not good?

**Comment by mloning** [comment]
Yes, the `NaiveForecaster` should be fine but bear in mind that it inherits from the `BaseWindowForecaster`, so best to make the inherited functionality explicit if relevant for the code skeleton. 

Yes, the check list is suitable for the concise description!

**Comment by fkiraly** [comment]
>Yes, the check list is suitable for the concise description!

Hm, so why did you say it was missing - did you not see it?

I can add a template code block if you want. E.g., example template and checklist.

**Comment by mloning** [comment]
I didn't mean to say it was missing, my comment mainly referred to the structure rather than content. Do you want to create a PR to include this on the website? I can set up the structure for the developer guide, similar to the user guide.

**Comment by fkiraly** [comment]
sure, can make a PR once there is a location where to.

Also, please note that some parts are still missing, e.g., on input check conventions. I can give it a try, but I don't know what these actually are.
