### ISSUE TITLE
Add AutoAR

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#465]
**Is your feature request related to a problem? Please describe.**
Simple auto-regressive forecaster with automatic estimation of number of lags.

**Describe the solution you'd like**
There is a open PR #411 which implements the basic structure but requires some more work to finish it.

**Comment by 3c0n0mist** [comment]
I would like to take up this issue.

**Comment by mloning** [comment]
Great, @3c0n0mist, let me know if you need any help!

**Comment by Afzal-Ind** [comment]
Hi @mloning , I would like to work on this. Thanks.

**Comment by Aditya-Sihmar** [comment]
Hi @afzal442, are you still working on this issue?

**Comment by afzal442** [comment]
Yep @Aditya-Sihmar, I am. If you want, you can collaborate here. So in the meantime, go with my PR, try to debug the code there.

**Comment by fkiraly** [comment]
> So in the meantime, go with my PR, try to debug the code there.

Welcome, @aditya-sihmar!

So, @afzal442... given that @aditya-sihmar might be offering help here, would you perhaps kindly explain what precisely needs fixing or debugging?
I haven't looked at this PR, and Markus is offline for thesis writing for a while, so would really appreciate you being as concrete as you can.

**Comment by afzal442** [comment]
Thanks, @fkiraly. 

Hi @Aditya-Sihmar, I have mentioned in my PR where I have debugged the respective algorithm somewhat. So find me there where I would explain you briefly.

**Comment by Aditya-Sihmar** [comment]
Thanks, @fkiraly

@afzal442 Sorry for the late reply. I would love to collaborate with you. I will look into your PR and try to debug your code.

**Comment by fkiraly** [comment]
This is a sub-case of `AutoARIMA`, hence covered by `AutoARIMA` currently in sktime.
