### ISSUE TITLE
[BUG] API broken on 0.4.3 - plot_ys is missing

### ISSUE THREAD

**Issue by itpmngt** [alan-turing-institute/sktime#466]
**Describe the bug**
file `forecasting.py` in `sktime.utils.plotting` is missing - it breaks the API and all online tutorials (including PyData 2020)) are broken

it happened between version 0.4.2 and 0.4.3

(assuming that was unintentional - otherwise, the advice is DO NOT break the API within minor versions, and never without pre-warnings of deprecating features, etcetera, etcetera...)

attempted to submit a PR but not-allowed

Best,

Joe Rosa

**Comment by mloning** [comment]
Hi @itpmngt, thanks for raising the issue and sorry about that! Note that sktime is at an early stage of development, many features aren't stable yet, so breaking changes will occur, we'll try to handle/communicate them better in the future! 

I've now pinned the version for the PyData tutorial [here](https://github.com/sktime/sktime-tutorial-pydata-amsterdam-2020/commit/440580ae9e52e5f612cac608eca20422aa87afef), so that should work again. 

What do you mean by "attempted to submit a PR but not-allowed"?

**Comment by itpmngt** [comment]
Hi @mloning - 

> What do you mean by "attempted to submit a PR but not-allowed"?

Cloned, created a branch and tried to push to create a PR - some repos are open for submitting PRs

> I've now pinned the version for the PyData tutorial here, so that should work again.

There are lots of stuff - other people tutorials and papers - your papers as well as - with that change you're breaking everything given a bad feeling and the thought on some people's minds that maybe this is not serious - highly recommend to revert that, this could jeopardise all the good work the 'sktime' team have been putting together

DO NOT break the API, and never, never in a minor version - 0.4.2 and 0.4.3. Your code is already live, people start to use, and this is not a small project - don't break the trust 

Disclaimer: just taking the time to expose (and give importance to this detail) because I think you are building something very interesting...

Best,

Joe Rosa

**Comment by mloning** [comment]
For creating a PR, please fork the repo as described in our [contributing guidelines](https://github.com/alan-turing-institute/sktime/blob/master/CONTRIBUTING.md).

Thanks for your feedback!

**Comment by Bruno-Hanzen** [comment]
I installed sktime with 
`pip install sktime`
The directory structure seems to be very different from the one in github.
For example, in the Plateaufinder example, I find:
`from sktime.transformers.panel.summarize import PlateauFinder`
On my machine, I have to use:
`from sktime.transformers.series_as_features.summarize import PlateauFinder`
This is quite inconvenient. Is the documentation aligned with the development version, or with the released version?
Should we consider the 0.4.3 structure as obsolete?

**Comment by mloning** [comment]
Hi @Bruno-Hanzen, we're developing on master, meaning that you have two options: 

1. run the notebooks using the latest "development" version from master by installing sktime via `pip install -e .` (see the [advanced installation instructions for more details](https://www.sktime.org/en/latest/installation.html))
2. running the latest stable release version by installing sktime via `pip install sktime` and running the notebooks locally via `git checkout v0.4.3`

I hope this helps. The [next version](https://github.com/alan-turing-institute/sktime/blob/master/CHANGELOG.rst) will be `v0.5.0` and will introduce a few breaking changes. 

I'll close this issue now but feel free to open a new issue or [chat on gitter](https://gitter.im/sktime/community)!
