### ISSUE TITLE
load data functionality

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#47]
currently loading data is performed in utils.load_data and works for .ts format. It would be good to bring back the methods to load from arff and from long format and add them as methods here

**Comment by TonyBagnall** [comment]
I think we need to unify the mechanism for loading problems from file. AFAIK there are currently two ways. 
on dev: utils.load_data has three methods

**Comment by mloning** [comment]
I agree, I think there should be two main entry points to our nested version of a pandas dataframe:
- file loading from .ts (also arff? and long table csv?) 
- from in-memory pandas dataframe in long table format with three columns [time, variable, value] (not sure what `from_long_to_nested` currently expects)

We should also have file saving functions to persist the data format once users managed to put data in the nested pandas dataframe.

**Comment by TonyBagnall** [comment]
digging a bit, I think its all there basically, but needs a tweak or two. Jason has added loading from arff and converting from long to pandas. I think it needs
1) file load from long and
2) the ability to define the schema of the long table. 
the latter because forecasting and classification necessarily have different formats: you need extra columns for case, class value, and dimension.

**Comment by TonyBagnall** [comment]
we might also want to be able to load from UCR/matlab-esq format, which is pretty commonly used. Does openML have a standard data format?

**Comment by jasonlines** [comment]
RE -  1: I think I answered this in person, but specifically I think this is what you mean: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html. Basically loads a file into a dataframe. So if you have have your data in a file (.csv, .txt, etc) then you can just load into the long format with pandas already

**Comment by jasonlines** [comment]
RE 2: yeah i agree it's a bit tricky for classification and other use cases. The example already expects columns for case id and dimension id (which could both have a single value for the simple 1d forecasting case). Class value is trickier; the way I handled it previously was to have an optional arg in the method for the dimension "name" of the class value, and could then handle that as appropriate if it was present, but that was a little messy. I just stuck to loading the data in the current code and assume the class values are loaded separately (not necessarily the best or final solution though)

**Comment by mloning** [comment]
@jasonlines @TonyBagnall Is this still relevant or has it be solved?

**Comment by mloning** [comment]
Closed as the other methods have been added [here](https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/load_data.py) I believe, please re-open if that's not the case.
