### ISSUE TITLE
[DOC] Broken documentation on `RandomIntervalSpectralForest`

### ISSUE THREAD

**Issue by AaronX121** [alan-turing-institute/sktime#470]
#### Describe the issue linked to the documentation

Hi, thank you for contributing to this nice repo. 

I find that the documentation page on `RandomIntervalSpectralForest` is broken (https://www.sktime.org/en/latest/modules/auto_generated/sktime.classification.frequency_based.RandomIntervalSpectralForest.html). This is what it looks like:

![screen](https://user-images.githubusercontent.com/22359569/98362893-fab84500-2068-11eb-8ebf-9bba6a9ca1b5.png)

**Comment by mloning** [comment]
@AaronX121 Thanks for raising this! Would appreciate a PR :)

**Comment by AaronX121** [comment]
Got it, I am happy to take this, and open a PR latter.

**Comment by mloning** [comment]
Thanks @AaronX121, really appreciated!
