### ISSUE TITLE
load_from_arff_to_dataframe fails when importing 'ECG200' dataset [BUG]

### ISSUE THREAD

**Issue by isma3ilsamir** [alan-turing-institute/sktime#474]
**Describe the bug**
I downloaded the 'ECG200' dataset files on my local machine and was trying to import it using 'load_data'
It works fine if I use 'load_from_tsfile_to_dataframe' utility but fails when I use 'load_from_arff_to_dataframe'

This is how the dataset is downloaded
c:\myfolder\ECG200
- c:\myfolder\ECG200\ECG200_TEST.arff
- c:\myfolder\ECG200\ECG200_TEST.ts
- c:\myfolder\ECG200\ECG200_TEST.txt
- c:\myfolder\ECG200\ECG200_TRAIN.arff
- c:\myfolder\ECG200\ECG200_TRAIN.ts
- c:\myfolder\ECG200\ECG200_TRAIN.txt
- c:\myfolder\ECG200\ECG200.txt

**To Reproduce**
```python
from sktime.utils.load_data import load_from_arff_to_dataframe as load_arff
from sktime.utils.load_data import load_from_tsfile_to_dataframe as load_tsf

X_train, y_train= load_tsf('c:\\myfolder\\ECG200\\ECG200_TRAIN.ts')
X_train, y_train= load_arff('c:\\myfolder\\ECG200\\ECG200_TRAIN.arff')
```

Error:
```python
~\.virtualenvs\Code-OH4xsw-D\lib\site-packages\sktime\utils\load_data.py in load_from_arff_to_dataframe(full_file_path_and_name, has_class_labels, return_separate_X_and_y, replace_missing_vals_with)
    698 
    699     with open(full_file_path_and_name, 'r') as f:
--> 700         for line in f:
    701 
    702             if line.strip():

~\.virtualenvs\Code-OH4xsw-D\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 159: character maps to <undefined>
```

**Expected behavior**
Training data is returned

**Additional context**

**Versions**
<details>
System:
    python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
          pip: 20.2.3
   setuptools: 50.3.0
      sklearn: 0.23.2
        numpy: 1.19.2
        scipy: 1.5.3
       Cython: 0.29.21
       pandas: 1.1.3
   matplotlib: 3.3.2
       joblib: 0.17.0
        numba: 0.51.2
     pmdarima: 1.7.1
      tsfresh: 0.17.0
</details>

**Comment by mloning** [comment]
Thanks @isma3ilsamir for raising the issue! 

@AidenRushbrooke did you take a look at the function recently? Any idea what may be wrong here?

**Comment by AidenRushbrooke** [comment]
I briefly looked though the function but made no changes. There were a few issues with code guidelines when running the pre-checks, so it might be to do with changes to python since the code was written, but I cannot say for certain.
