### ISSUE TITLE
Implement series-to-series transformers

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#483]
**Describe the solution you'd like**
Here's a simple example of a series-to-series log transformer transformer:

All of these transforms are series-to-series transforms. For an overview of different kinds of transformations, see this [document](https://github.com/sktime/enhancement-proposals/blob/master/steps/03_transformer_api/transform_types.ipynb).

```python
import numpy as np
import pandas as pd

from sktime.transformers.base import _SeriesToSeriesTransformer
from sktime.utils.validation.series import 

class LogTransformer(_SeriesToSeriesTransformer):

    _tags = {"transform-returns-same-time-index": True}

    def transform(self, Z, X=None):
        self.check_is_fitted()
        Z = check_series(Z)
        return np.log(Z)

    def inverse_transform(self, Z, X=None):
        self.check_is_fitted()
        Z = check_series(Z)
        return np.exp(Z)
```

**List of transformations we'd like to include in sktime**
| Transform  | Package/Function |
| ------------- | ------------- |
| FFT/DFT  | https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.fft.html  |
| Autocorrelation function (ACF)  | https://www.statsmodels.org/0.9.0/generated/statsmodels.tsa.stattools.acf.html  |
| Partial autocorrelation function (autoregressive coefficients) (PACF) | https://www.statsmodels.org/0.9.0/generated/statsmodels.tsa.stattools.pacf.html  |
| Auto Regressive Moving Average (ARMA)  | https://www.statsmodels.org/0.9.0/generated/statsmodels.tsa.arima_model.ARMA.html  |
| Power Spectrum  | https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.periodogram.html  |
| Cepstrum  | https://github.com/python-acoustics/python-acoustics/blob/master/acoustics/cepstrum.py  |
| Cosine  | https://docs.scipy.org/doc/numpy/reference/generated/numpy.cos.html  |

**Related issues**
see #6, #224 and #297

**Comment by mloning** [comment]
Hi @Afzal-Ind, could you tell me which part isn't clear? You can message me here or on Gitter.

**Comment by Afzal-Ind** [comment]
> Could you tell me which part isn't clear?

Thanks. I am not clear about series-to-series log transformer is how it works basically.

**Comment by mloning** [comment]
@Afzal-Ind There is an example in the linked [document](https://github.com/sktime/enhancement-proposals/blob/master/steps/03_transformer_api/transform_types.ipynb).

**Comment by Afzal-Ind** [comment]
> Does that make it clearer?

Thanks again. It may take some time but I will keep up with this.
