### ISSUE TITLE
[BUG] ImportError: DLL load failed while importing mrseql: The specified module could not be found

### ISSUE THREAD

**Issue by adelphi207831197** [alan-turing-institute/sktime#498]
**Describe the bug**

Hello.
I installed SKTime version 0.4.3 on my local Anaconda environment.
When I try to follow 03_classification_multivariate (version 0.4.3) example there is an error from the line:
"from sktime.classification.shapelet_based import MrSEQLClassifier"
Thank you.

**To Reproduce**

Following the example from 
sktime.org/en/v0.4.3/examples/03_classification_multivariate.html
```python

from sktime.classification.shapelet_based import MrSEQLClassifier

Traceback (most recent call last):
  File "ex_multiivariateTSClassification1.py", line 22, in <module>
    from sktime.classification.shapelet_based import MrSEQLClassifier
  File "C:\Users\mee\AppData\Local\Continuum\anaconda3\envs\Python38-TimeSeries\lib\site-packages\sktime\classification\shapelet_based\__init__.py", line 6, in <module>
    from sktime.classification.shapelet_based.mrseql.mrseql import \
ImportError: DLL load failed while importing mrseql: The specified module could not be found.

```

**Expected behavior**

**Additional context**

**Versions**
<details>

System:
    python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\mee\AppData\Local\Continuum\anaconda3\envs\Python38-TimeSeries\python.exe
   machine: Windows-8.1-6.3.9600-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 49.6.0
      sklearn: 0.23.2
        numpy: 1.19.4
        scipy: 1.5.3
       Cython: 0.29.17
       pandas: 1.1.4
   matplotlib: 3.3.2
       joblib: 0.17.0
        numba: 0.51.2
     pmdarima: 1.7.1
      tsfresh: 0.17.0
</details>

**Comment by mloning** [comment]
Hi @adelphi207831197 - thanks for raising the issue! 

Someone had a similar issue on [Gitter](https://gitter.im/sktime/community) and managed to fix it by installing Visual Studio 2019. 

See if that works, otherwise we have to look into it in more detail!
