### ISSUE TITLE
MAPE loss function implementation

### ISSUE THREAD

**Issue by tch** [alan-turing-institute/sktime#499]
**Is your feature request related to a problem? Please describe.**
A need for MAPE loss function to be able to compare forecasting results.

**Describe the solution you'd like**
MAPE loss function compatible with sktime

**Describe alternatives you've considered**
None

**Additional context**
NA

**Comment by tch** [comment]
Implemented in PR #500. Please have a look. Thx

**Comment by mloning** [comment]
Thanks @tch for raising the issue and opening the PR!
