### ISSUE TITLE
[DOC] Tidy up and unify the referencing style

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#507]
We need a unified way of linking to publications in the source code. I will sort this out, but please comment here if you have thoughts on what the standard approach should be. I want
cite
link
bibtex
to make peoples life easier. I might also link the the tsml version, and vice versa?

**Comment by mloning** [comment]
Our general formatting follows the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).

**Comment by TonyBagnall** [comment]
![image](https://user-images.githubusercontent.com/9594042/100377027-6fe3be00-3008-11eb-85e8-aafe5211cda4.png)

at the top of the file? I will do this but will add the bibtex too, and a link

**Comment by mloning** [comment]
Usually it's place in the docstring for the class below the class definition. Check out how scikit-learn does it, here's the notes section from random forest: https://github.com/scikit-learn/scikit-learn/blob/0fb307bf39bbdacd6ed713c00724f8f871d60370/sklearn/ensemble/_forest.py#L1116

**Comment by TonyBagnall** [comment]
seems a weird place to put it, but we are meant to follow scikit learn I suppose

**Comment by TonyBagnall** [comment]
done
