### ISSUE TITLE
ModuleNotFoundError: No module named 'sktime.transformers.series'

### ISSUE THREAD

**Issue by robomotic** [alan-turing-institute/sktime#508]
**Describe the bug**

I am running the 01_forecasting.ipynb notebook.

**To Reproduce**

```python
from sktime.transformers.series.detrend import Deseasonalizer, Detrender
```

**Expected behavior**

Import should succeed 

**Additional context**

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-79c87a42ec01> in <module>
     22 from sktime.forecasting.trend import PolynomialTrendForecaster
     23 from sktime.performance_metrics.forecasting import sMAPE, smape_loss
---> 24 from sktime.transformers.series.detrend import Deseasonalizer, Detrender
     25 from sktime.utils.plotting import plot_series
     26 

ModuleNotFoundError: No module named 'sktime.transformers.series'
```
**Versions**

Name: sktime
Version: 0.4.3

Source: python3-defaults
Version: 3.8.2-0ubuntu2
System:
    python: 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05)  [GCC 7.5.0]
executable: /opt/conda/bin/python
   machine: Linux-5.4.0-54-generic-x86_64-with-glibc2.10

Python dependencies:
          pip: 20.2.4
   setuptools: 49.6.0.post20201009
      sklearn: 0.23.2
        numpy: 1.19.4
        scipy: 1.5.4
       Cython: 0.29.21
       pandas: 1.1.4
   matplotlib: 3.3.3
       joblib: 0.17.0
        numba: 0.49.1
     pmdarima: 1.7.1
      tsfresh: 0.17.0

**Comment by mloning** [comment]
Hi @robomotic, it looks like a similar problem to this one: https://github.com/alan-turing-institute/sktime/issues/481

Let me know if the suggested solution there works for you.

**Comment by summa-code** [comment]
It did not work for me, i have the same issue. I checked out v0.4.3 example for the latest '''pip install sktime'''

**Comment by mloning** [comment]
@summa-code could you provide a bit more details on what system and versions you're running on and whether you use conda?

**Comment by summa-code** [comment]
Never mind, i forgot to use -b. But again should the examples be in sync with master branch ? That way it is easy for folks who want to do a quick learning on this framework. Looks great so far.

**Comment by mloning** [comment]
The examples are in sync with the master branch. The latest release lags behind the master branch, that's why you have to check out the latest stable version locally when you have pip-installed sktime.

**Comment by robomotic** [comment]
I understand now, I basically build docker images every time but I use this commandline:
RUN pip install --upgrade "sktime$OPTIONS"
What flag I should use, I am not sure about the -b mentioned is it conda related?

**Comment by robomotic** [comment]
I am now building it from source as described in the docs but I am getting this warning:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

pmdarima 1.7.1 requires statsmodels<0.12,>=0.11, but you'll have statsmodels 0.12.1 which is incompatible.
```

What combination of pmdarima and statmodel do I have to install to avoid the warning?

**Comment by mloning** [comment]
Yes, this is related to a statsmodels bug that was introduced in their previous version and only fixed in their last version. We're still waiting for pmdarima to make a new release, see #512
