### ISSUE TITLE
ModuleNotFoundError: No module named 'sktime.transformers.series'

### ISSUE THREAD

**Issue by satya-pattnaik** [alan-turing-institute/sktime#514]
**Describe the bug**

I am following the example notebooks provided in the Repo. While importing sktime Detrender, I need to import it as "from sktime.transformers.series.detrend import Detrender". However I get an error "ModuleNotFoundError: No module named 'sktime.transformers.series'". 

**To Reproduce**

```python
from sktime.transformers.series.detrend import Deseasonalizer, Detrender
```

**Expected behavior**
I was expecting the import to work totally fine. But it seems there is no module "series" inside "transformers"

**Versions**
<details>
sktime-0.4.3

System:
    python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20)  [GCC 7.3.0]
executable: /opt/conda/bin/python3.7
   machine: Linux-5.4.49+-x86_64-with-debian-buster-sid

Python dependencies:
          pip: 20.2.4
   setuptools: 46.1.3.post20200325
      sklearn: 0.23.2
        numpy: 1.18.5
        scipy: 1.4.1
       Cython: 0.29.21
       pandas: 1.1.4
   matplotlib: 3.2.1
       joblib: 0.14.1
        numba: 0.48.0
     pmdarima: None
      tsfresh: 0.17.0
</details>

**Comment by mloning** [comment]
Hi @satya-pattnaik - thanks for raising the issue! Please take a look at this issue to see if that resolve the error #481.

**Comment by satya-pattnaik** [comment]
Thanks, @mloning . With the help of IDE I figured out the following:
`from sktime.transformers.single_series.detrend import Deseasonalizer, Detrender`

This works!
