### ISSUE TITLE
[DOC] SlidingWindowSplitter start_with_window default value not consistent

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#516]
#### Describe the issue linked to the documentation

https://github.com/alan-turing-institute/sktime/blob/139b9291fb634cce367f714a6132212b0172e199/sktime/forecasting/model_selection/_split.py#L174

It looks like the default value of start_with_window=False, but documentation states that it is True. Not sure which one was intended.

https://github.com/alan-turing-institute/sktime/blob/139b9291fb634cce367f714a6132212b0172e199/sktime/forecasting/model_selection/_split.py#L183

#### Suggest a potential alternative/fix
Change either the documentation or the default argument to match the other one

**Comment by mloning** [comment]
Hi @ngupta23 - thanks for raising the issue! 

I'd appreciate a PR that changes the docs.

**Comment by ngupta23** [comment]
Ok, no problem. What default would you like it to be: True or False?

**Comment by mloning** [comment]
I'd say we keep the code and adjust the docs, so default should be `False`.
