### ISSUE TITLE
[DOC] ForecastingGridSearchCV clarity needed 

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#521]
#### Describe the issue linked to the documentation

When using ForecastingGridSearchCV with SlidingWindowSplitter and Initial Window, need some clarity on what happens during initial split training and what happens in the temporal cross validation step.

The documentation states:

> Performs grid-search cross-validation to find optimal model parameters. The forecaster is fit on the initial window and then temporal cross-validation is used to find the optimal parameter

For the example below, what is the sequence of event?

```python
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

# tuning the 'n_estimator' hyperparameter of RandomForestRegressor from scikit-learn
regressor_param_grid = {"n_estimators": [100, 200, 300]}
forecaster_param_grid = {"window_length": [5,10,15,20,25]}

# create a tunnable regressor with GridSearchCV
regressor = GridSearchCV(RandomForestRegressor(), param_grid=regressor_param_grid)
forecaster = ReducedRegressionForecaster(regressor, window_length=15, strategy="recursive")

cv = SlidingWindowSplitter(initial_window=int(len(y_train) * 0.5))
gscv = ForecastingGridSearchCV(forecaster, cv=cv, param_grid=forecaster_param_grid)

gscv.fit(y_train)
y_pred = gscv.predict(fh)
```

### Initial Window

> forecaster is fit on the initial window

What is its purpose? Is it to get the remaining parameters of the regressor (which are not specified in the `regressor_param_grid` such as `max_depth`, `min_samples_split`, etc)?

### Temporal Cross Validation

> then temporal cross-validation is used to find the optimal parameter

* Is temporal cross validation performed with the non-specified hyperparameters (`max_depth`, `min_samples_split`, etc) that are found above in the initial window?
* Do these non-specified hyperparameters (`max_depth`, `min_samples_split`, etc) remain fixed to the value found in the initial window at each of the fold evaluations or is the model retrained at each fold to compute these non-specified hyperparameters again? If it is the latter, what is the purpose of the initial window in that case?

Thank you for any additional clarity you can shed on this.

**Comment by mloning** [comment]
Hi @ngupta23, I think this is how it works:

1. for each set of hyper parameters, the model is fitted on the `intial_window`
2. predictions are generated for each window on the cross-validation windows 
3. predictions are evaluated using the scoring function and aggregated
4. the best set of hyper parameters is chosen that optimises the score

This code is still experimental, both the window splitters and grid-search routine. I'm open to discuss improvements.

**Comment by ngupta23** [comment]
Hi @mloning , Thanks for the clarification. I have been diving deeper into the repo to understand this better. Its still early, but if I understand this correctly, I think one potential pitfall would be the part of the validation window might overlap with the training since `initial_window` is decoupled from `window_length` in the `SlidingWindowSplitter`. 

Let's take a simple example (similar to what you have in your forecasting notebook). If the training data has 108 observations, `initial_window` is 50% of that as in your examples folder (54 observations), `window_length` is the default of 10, `fh` and `step_length` are set to default of 1, then

* The training happens on indices 0 to 53.
* But validation starts from using data from the beginning.
  - So first temporal fold will use data from index 0 to 9 to make the next prediction (index 10). But indices 0 to 9 have already been used for training, so the same should not be used for validation as it will lead to a biased score.
  - Similarly, the next fold will use data from index 1 to 10 to predict index 11. Again, index 1 to 10 have been used in training so should not be used for validation. 
  - This process repeats until you make a prediction for index 64 using data from index 54 to 63. That is the first truly unbiased fold.

**Would it be better to have the temporal validation start from after the training index?**

**Comment by mloning** [comment]
Yes that's what is intended and how it is used inside [`ForecastingGridSearchCV`](https://github.com/alan-turing-institute/sktime/blob/4422a66a2749eaea41d3fbda723bc8c64f334787/sktime/forecasting/model_selection/_tune.py#L73) as far as I can see: the training and validation are split first, then we use temporal CV on the validation data. 

I understand that having this initial window though overlapping with the validation windows is confusing. Any idea how to improve this?

**Comment by mloning** [comment]
More info here: https://github.com/sktime/enhancement-proposals/blob/master/steps/01_forecasting_api/model-evaluation-tuning.md
