### ISSUE TITLE
FutureWarning: the 'damped'' keyword is deprecated, use 'damped_trend' instead

### ISSUE THREAD

**Issue by londumas** [alan-turing-institute/sktime#523]
Running the README example "Quickstart/Forecasting", I get the following warning:
```
<me>/.local/lib/python3.8/site-packages/sktime/forecasting/exp_smoothing.py:101: FutureWarning: the 'damped'' keyword is deprecated, use 'damped_trend' instead
  self._forecaster = _ExponentialSmoothing(
```

https://github.com/alan-turing-institute/sktime/blob/139b9291fb634cce367f714a6132212b0172e199/sktime/forecasting/exp_smoothing.py#L104

**Comment by mloning** [comment]
Hi @londumas - thanks for raising the issue. Yes, it's a future warning, meaning that we have to make changes when we want to support newer statsmodels version which is what we want to do for the next release! 

I'd really appreciate a PR to make the required changes! 

This is also related to #512.

**Comment by mloning** [comment]
This should now be fixed in the new release https://github.com/alan-turing-institute/sktime/releases/tag/v0.5.0
