### ISSUE TITLE
ModuleNotFoundError: No module named 'sktime.transformers.series'

### ISSUE THREAD

**Issue by Conet1502** [alan-turing-institute/sktime#526]
**Describe the bug**
I created a new Anaconda environment to test SKTime.
I ran the 'pip install sktime' to install SKTime.
When I try to follow the "Forecasting  with sktime"(https://github.com/alan-turing-institute/sktime/blob/master/examples/01_forecasting.ipynb)  Time series forest example I get this error:

What other dependencies am I supposed to install? Is the example notebook not up to date?
**To Reproduce**
ModuleNotFoundError: No module named 'sktime.transformers.series'

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by mloning** [comment]
Hi @Conet1502 - thanks for raising the issue. This is related to https://github.com/alan-turing-institute/sktime/issues/481
