### ISSUE TITLE
ModuleNotFoundError: No module named 'sktime.transformers.panel'

### ISSUE THREAD

**Issue by orko19** [alan-turing-institute/sktime#528]
I get the error:
`ModuleNotFoundError: No module named 'sktime.transformers.panel'
`
For 
`from sktime.transformers.panel.reduce import Tabularizer
`
(taken from: `https://www.sktime.org/en/latest/examples/02_classification_univariate.html?highlight=tabulizer`)
I use version `0.43`

Why can't I import it?
Thanks

**Comment by mloning** [comment]
Hi @orko19 - thanks for raising the issue. This is related to https://github.com/alan-turing-institute/sktime/issues/481

**Comment by orko19** [comment]
@mloning Thanks for the ref. I didn't understand what is the version I should use and how do it in google colab?
You wrote to use v0.4.3 but it is the one I used, can you please clarify?

**Comment by mloning** [comment]
I'm not sure what your setup is in Google Colab. As said in #418 you have two options:

* When you `pip install sktime` you install the latest stable release, so to run the example notebooks locally you need to make sure to checkout the latest stable release version of the notebooks (rather than using the most up-to-date changes on master), run: `git checkout v0.4.3`
* Alternatively, you can install the latest development version from master using `pip install -e .` from the root directory of the cloned sktime repo.

Which one are trying to work with? 

Sorry for the confusion with this - we're trying to push a new release some time soon to fix this.

**Comment by orko19** [comment]
@mloning I am working with google colab so I can't run `git checkout v0.4.3`
That is the reason I also can't run `pip install -e .` from the root directory of the cloned sktime repo - since I didn't clone any repo, but just install with pip.
Can you please provide a way to install `v0.4.3` from colab?

**Comment by mloning** [comment]
I'm not sure how your Colab is set up. How do you install sktime? How do you run the examples?

**Comment by orko19** [comment]
@mloning I install using
`!pip install sktime
` which installed version 0.4.3 and then simply import
`from sktime.transformers.panel.reduce import Tabularizer
`

**Comment by mloning** [comment]
Okay for version 0.4.3 you can see the code structure here: https://github.com/alan-turing-institute/sktime/tree/v0.4.3 so you can adjust the import statements. 

Hope this helps!

**Comment by orko19** [comment]
@mloning Thanks, but I suppose it's not the best solution since I might encounter additional issues later - there is no way to just install v0.4.3 in google colab? I can share with you any needed configuration (it's pretty much the default, I changed nothing)

Also, I am reading ur original reply again and there is something I can't understand - if I installed the latest stable from master, and the notebook are also from the latest stable from master, why aren't they match?

**Comment by mloning** [comment]
You install v0.4.3 which is not master but the latest stable release - master contains newer changes and we will make a new release hopefully some time soon.

**Comment by orko19** [comment]
@mloning Oh OK. and all the notebooks are aligned with master? Do you have a v0.4.3 of them?

**Comment by mloning** [comment]
Yes, exactly. To get the v0.4.3 you need to run `git checkout v0.4.3` or go here: https://github.com/alan-turing-institute/sktime/tree/v0.4.3

**Comment by orko19** [comment]
@mloning Thanks, and any time estimation as when master will be deployed as a new stable release?

**Comment by mloning** [comment]
Hopefully within the next 2 weeks

**Comment by jowallner** [comment]
Hi,

I have the same problem regarding Google colab and the issue: ModuleNotFoundError: No module named 'sktime.transformers'.
I tried 
```
!git clone https://github.com/alan-turing-institute/sktime.git
!cd v0.4.3 && git checkout incoming
```
but this just gives me: "cd: v0.4.3: No such file or directory".
@orko19 how did you resolve this?

Thank you!

**Comment by mloning** [comment]
Could you try to import `sktime.transformations`?
