### ISSUE TITLE
[BUG] Import error: ColumnConcatenator

### ISSUE THREAD

**Issue by Pratyush1991** [alan-turing-institute/sktime#530]
**Describe the bug**

Unable to import the ColumnConcatenator while trying to implement the multivariate classification example. The error shows as "no module named sktime.transformers.panel"

**To Reproduce**
![image](https://user-images.githubusercontent.com/28738918/101628890-17261380-3a53-11eb-8a19-eb27220914ee.png)

```python
from sktime.transformers.panel.compose import ColumnConcatenator
```

**Expected behavior**

Successful import of  the module

**Additional context**

**Versions**
<details>

System:
    python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
executable: C:\ProgramData\Anaconda3\python.exe
   machine: Windows-10-10.0.20270-SP0

Python dependencies:
          pip: 20.1.1
   setuptools: 49.6.0.post20201009
      sklearn: 0.23.1
        numpy: 1.19.4
        scipy: 1.5.3
       Cython: None
       pandas: 1.1.3
   matplotlib: 3.2.2
       joblib: 0.17.0
        numba: 0.51.2
     pmdarima: None
      tsfresh: 0.17.0

</details>

**Comment by mloning** [comment]
Hi @Pratyush1991 - thanks for raising the issue. This is related to https://github.com/alan-turing-institute/sktime/issues/481
