### ISSUE TITLE
Add utility functions to convert between additional data structures and nested DataFrame

### ISSUE THREAD

**Issue by RNKuhns** [alan-turing-institute/sktime#532]
I know that potentially changing the time series input container for sktime is on the future enhancement docket, but in the meantime it would be useful to have additional utility functions to convert between other common representations of time series data and the nested DataFrame format used by sktime. 

I've got a couple functions worked up to handle conversion from a MultiIndexed Pandas DataFrame, a 3d Numpy array (cases, feature dim, time dim) and what I believe to be  a quicker version of sktime.utils.load_data.from_long_to_nested. 

I'm new to contributing to open source projects, so please advise on the best way to contribute these.  Should I fork the repo, add and submit a pull request?

**Comment by mloning** [comment]
Hi @RNKuhns - yes that would be great! Take a look at our [contributing guidelines](https://github.com/alan-turing-institute/sktime/blob/d3ac2b45d89946363899370c3b43cf52a103e501/CONTRIBUTING.md) - I'm happy to help if anything is unclear!

**Comment by RNKuhns** [comment]
@mloning Thanks, I've been taking a look through the guidelines and I am in the process of forking the repository now.

**Comment by RNKuhns** [comment]
This was closed by #553.
