### ISSUE TITLE
[DOC]Deseasonalizer Clarity Needed

### ISSUE THREAD

**Issue by satya-pattnaik** [alan-turing-institute/sktime#539]
#### Describe the issue linked to the documentation
The Deseasonalizer does not remove the trend, if I am not wrong?

> A transformer that removes a seasonal and trend components from time series.

#### An alternative/fix

> A transformer that removes the seasonal component from time series.

**Comment by mloning** [comment]
Hi @satya-pattnaik - yes that's right, good catch! I'd appreciate a PR!
