### ISSUE TITLE
[BUG] AutoArima fit with X_train generates a ValueError: "Multiple values provided for both X and exogenous"

### ISSUE THREAD

**Issue by PierreOreistein** [alan-turing-institute/sktime#540]
### Description:
I am trying to use the model **AutoARIMA** from _sktime.forecasting.arima_ with exogenous variables.
In particular, I am trying to pass a Dataframe to the argument _X_train_ in the method _fit_ of the model **AutoARIMA**. When I do so, I obtain a _ValueError_. Below an example

```python
MODEL_Auto_ARIMA = AutoARIMA(
)

y_df = pd.DataFrame(
    np.random.randint(0, 10, 31),
    columns=["y"],
    index=pd.period_range(
        start="2020-01-01",
        periods=31,
        freq="D"
))

X_df = pd.DataFrame(
    np.random.randint(0, 10, len(y_df)),
    columns=["X"],
    index=y_df.index
)

MODEL_Auto_ARIMA.fit(
    y_train=y_df["y"],
    X_train=X_df
)
```

When I run the above code, I obtain the following error:

```python
ValueError                                Traceback (most recent call last)
<ipython-input-3-4a75cca05732> in <module>
     16 MODEL_Auto_ARIMA.fit(
     17     y_train=y_df["y"],
---> 18     X_train=X_df
     19 )

~/miniconda3/envs/RATP37/lib/python3.7/site-packages/sktime/forecasting/arima.py in fit(self, y_train, fh, X_train, **fit_args)
    363         self._set_y_X(y_train, X_train)
    364         self._set_fh(fh)
--> 365         self._forecaster.fit(y_train, exogenous=X_train, **fit_args)
    366         self._is_fitted = True
    367         return self

~/miniconda3/envs/RATP37/lib/python3.7/site-packages/pmdarima/arima/auto.py in fit(self, y, X, **fit_args)
    218             with_intercept=self.with_intercept,
    219             sarimax_kwargs=sarimax_kwargs,
--> 220             **fit_args)
    221 
    222         return self

~/miniconda3/envs/RATP37/lib/python3.7/site-packages/pmdarima/arima/auto.py in auto_arima(y, X, start_p, d, start_q, max_p, max_d, max_q, start_P, D, start_Q, max_P, max_D, max_Q, max_order, m, seasonal, stationary, information_criterion, alpha, test, seasonal_test, stepwise, n_jobs, start_params, trend, method, maxiter, offset_test_args, seasonal_test_args, suppress_warnings, error_action, trace, random, random_state, n_fits, return_valid_fits, out_of_sample_size, scoring, scoring_args, with_intercept, sarimax_kwargs, **fit_args)
    390 
    391     # Temporary shim until we remove `exogenous` support completely
--> 392     X, fit_args = pm_compat.get_X(X, **fit_args)
    393 
    394     # pop out the deprecated kwargs

~/miniconda3/envs/RATP37/lib/python3.7/site-packages/pmdarima/compat/pmdarima.py in get_X(X, **kwargs)
     12     exog = kwargs.pop("exogenous", None)
     13     if X is not None and exog is not None:
---> 14         raise ValueError("Multiple values provided for both X and exogenous")
     15 
     16     if exog is not None:

ValueError: Multiple values provided for both X and exogenous
```

### Additional Context
I am using python 3.7 on a conda virtual environment on WSL2.

### Versions
<details>
System:
    python: 3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0]
executable: /home/poreistein/miniconda3/envs/RATP37/bin/python3.7
   machine: Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid

Python dependencies:
          pip: 20.3.1
   setuptools: 51.0.0.post20201207
      sklearn: 0.23.2
        numpy: 1.19.4
        scipy: 1.5.3
       Cython: 0.29.17
       pandas: 1.1.0
   matplotlib: 3.3.3
       joblib: 0.17.0
        numba: 0.49.1
     pmdarima: 1.8.0
      tsfresh: 0.17.0
</details>

Feel free if you have any questions for the reproductability

**Comment by mloning** [comment]
Hi @PierreOreistein - thanks for raising the issue! 

Looks like this is due to the newer version of pmdarima. We're currently working on a new release where we will update our dependencies (#538). That should solve this error.

**Comment by PierreOreistein** [comment]
Hi @mloning ,

Thanks for the answer. Can't wait to see the new release!

By the way, sktime is a great piece of code! Thanks for your hard work on it

**Comment by mloning** [comment]
Thanks @PierreOreistein!

**Comment by Pranav-India** [comment]
Hi @PierreOreistein @mloning   I have a confusion I thought arima is a pure time series method and its prediction of anything using arima depends only on the past values of that parameter. But here in sktime AutoARIMA you are also feeding x_train along with y_train I wanted to understand, what effect does these x_train has on the y_hat(prediction of y)? does AutoARIMA considers other features while making the forecast for y?

**Comment by fkiraly** [comment]
@Pranav-India, it's a direct interface (with different signature) to `pmdarima`'s `AutoARIMA`. The exogeneous variables are used as regressors, see the [`pmdarima` reference](https://alkaline-ml.com/pmdarima/modules/generated/pmdarima.arima.auto_arima.html).

**Comment by Pranav-India** [comment]
Hi @fkiraly  Thank you for the response , I read the page you have mentioned it cleared my understanding. What I did is I tried AutoArima predictions with both the models 

` 
import pmdarima as pm
from pmdarima import model_selection
import numpy as np
from matplotlib import pyplot as plt

arima = pm.auto_arima(y_tr,X=x_tr, start_p=1, start_q=1,
                      test='adf',       # use adftest to find optimal 'd'
                      max_p=3, max_q=3, # maximum p and q
                      m=1,              # frequency of series
                      d=None,           # let model determine 'd'
                      seasonal=True,   # No Seasonality
                      start_P=0, 
                      D=1, 
                      trace=True,
                      error_action='ignore',  
                      suppress_warnings=True, 
                      stepwise=True)
`

![pdarima](https://user-images.githubusercontent.com/55158029/129142957-617dd4dd-0e62-4f49-b0b6-a10bad1decb6.png)


`fh_train = ForecastingHorizon(y_tr.index, is_relative=False)
fh = ForecastingHorizon(y_te.index, is_relative=False)
        
forecaster = AutoARIMA()
forecaster.fit(y_tr,x_tr)
y_pred_train = forecaster.predict(fh_train , X=x_tr)
y_pred = forecaster.predict(fh , X=x_te)
df = pd.DataFrame(y_tr.append(y_pred,ignore_index = True))`
![sktimeautoarima](https://user-images.githubusercontent.com/55158029/129142947-0727de03-8b12-4f8a-8b2d-e333921a6ac7.png)



I checked the summary of both models it is exactly the same all the values are exactly same also I have made sure that the input and output data is also exactly same still I am getting pretty different results. Does sktime make some more changes to the output of pmdarima's autoarima ? 

I went through [https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/arima.py#L357-L576](this) git page of sktime AutoArima but could not understand what improvement sktime makes on output of pmdarima. Can you please point to the correct direction so I can find the complete implementation? 


Thank you

**Comment by fkiraly** [comment]
>I went through this git page of sktime AutoArima but could not understand what improvement sktime makes on output of pmdarima. Can you please point to the correct direction so I can find the complete implementation?

`sktime`'s autoARIMA is simply interfacing `pmdarima`'s, i.e., the algorithm is exactly the same.

What `sktime` adds is the `scikit-learn` like interface (which `pmdarima` doesn't have), for instance you can use AutoARIMA with the same interface as all the other methods, or use it in pipelines etc.

The file you link to is the right one, but the lines are not correct - you need to look at the `AutoARIMA` class.

>I checked the summary of both models it is exactly the same all the values are exactly same also I have made sure that the input and output data is also exactly same still I am getting pretty different results.

There is some stochasticity in the forecasts and fitting of `AutoARIMA`, so that might be an explanation. If you re-run, your results might be different each time, for the same method.
It would be good if you could check whether this stochastic fluctuations are the reason - if not, there may be a bug in the interface which we'd be thankful to hear about (in case you can confirmed it).

**Comment by fkiraly** [comment]
(if you think the deviation is a bug, and you don't know where it comes from: would appreciate some reproducible code that creates the figures)

**Comment by Pranav-India** [comment]
@fkiraly  Sure I rerun the code the results are still same I will let you know if I find something

**Comment by Pranav-India** [comment]
Hi @fkiraly I wanted to know this in "ThetaForecaster" , does sktime ignores X = x_tr i.e. exogenous variables? or it is using them for regression?
