### ISSUE TITLE
[BUG] Data leakage when running evaluate function with exogenous data

### ISSUE THREAD

**Issue by admo1** [alan-turing-institute/sktime#5438]
**Describe the bug**
A data leakage issue occurs when executing the evaluate function with exogenous data.

**To Reproduce**
```python
from sktime.datasets import load_airline
from sktime.forecasting.arima import AutoARIMA
from sktime.split import ExpandingWindowSplitter
from sktime.forecasting.model_evaluation import evaluate

y = load_airline()

forecaster = AutoARIMA()

splitter = ExpandingWindowSplitter(step_length=12)

results = evaluate(forecaster=forecaster, y=y, X=y, cv=splitter)

print(results.iloc[:, 0].mean())
```

**Expected behavior**
At present, the code yields a mean cross-validation score close to 0 on the holdout cross-validation dataset, which is not logically possible.

**Additional context**
I'm currently utilizing the same input dataset for both y and X. It's worth noting that even if the target we aim to predict exists within X, the function should not incorporate future data to inform its predictions.

**Versions**
<details>

System:
    python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
executable: /local_disk0/.ephemeral_nfs/envs/pythonEnv-eb143bb3-eb1e-4c9d-b489-38c2d68dce24/bin/python
   machine: Linux-5.15.0-1042-azure-x86_64-with-glibc2.35

Python dependencies:
          pip: 22.2.2
       sktime: 0.24.0
      sklearn: 1.1.1
       skbase: 0.6.0
        numpy: 1.21.5
        scipy: 1.9.1
       pandas: 1.4.4
   matplotlib: 3.5.2
       joblib: 1.2.0
        numba: None
  statsmodels: 0.13.2
     pmdarima: 2.0.3
statsforecast: None
      tsfresh: None
      tslearn: 0.5.3.2
        torch: None
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment]
Hm, @admo1, not sure if its a bug, let me explain:

The default of `evaluate` is to provide *all `X` in `predict`*, i.e., all variables in `X` are future-known. If you do not want that, you need to specify `cv_X` explicitly, it should be equal to `cv`.

I also note there is currently no splitter object that just censors some variables, I'll make a note to create one.

**Comment by fkiraly** [comment]
> But it seems a bit unintuitive and is also not very clear in the documentation.

Ok, so that's an improvement action for the docs as well.

**Comment by fkiraly** [comment]
I opened issues arising:

* splitters for future-unknown data https://github.com/sktime/sktime/issues/5467
* doc improvement https://github.com/sktime/sktime/issues/5468
