### ISSUE TITLE
[DOC] Intermediate step missing in "Code quality checks" section of CONTRIBUTING.md

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#557]
#### Describe the issue linked to the documentation

In [this section](https://github.com/alan-turing-institute/sktime/blob/master/CONTRIBUTING.md#code-quality-checks), there is a missing intermediate section since pre-commit needs to be installed.

#### Suggest a potential alternative/fix

Add the following intermediate section

> 1B. Install pre-commit
> ```terminal
> pip install pre-commit
> ```
>

**Comment by mloning** [comment]
Thanks @ngupta23 - now fixed!
