### ISSUE TITLE
[BUG] load_data.py is no longer found in the main source tree after recent change

### ISSUE THREAD

**Issue by geoHeil** [alan-turing-institute/sktime#558]
After https://github.com/alan-turing-institute/sktime/pull/496/files (even though it is not deleting but enhancing the file) the load_data.py file is no longer found in the main source tree: https://github.com/alan-turing-institute/sktime/tree/master/sktime/utils

am I overlooking something? Wass it removed by accident? If yes, why doesn`t the merge request show a delete?

**Comment by mloning** [comment]
Hi @geoHeil - we consolidated our utils module a bit, the data loading functionality now lives in `utilts/data_io.py` (see https://github.com/alan-turing-institute/sktime/pull/538)

**Comment by mloning** [comment]
Please

**Comment by geoHeil** [comment]
thx
