### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'sktime.forecasting.fbprophet'

### ISSUE THREAD

**Issue by mikelty** [alan-turing-institute/sktime#580]
I'm trying to run the first notebook(https://github.com/alan-turing-institute/sktime/blob/master/examples/01_forecasting.ipynb). 
I tried running this on my local ubuntu 18.04 machine and google colab. On google colab, it yields an error at cell 91 of the origiinal notebook (btw it doesn't open on colab either so i have to copy / paste everything.) Here's what I did and what the error is:
`pip install sktime pmdarima sklearn `
```
from warnings import simplefilter

import numpy as np
import pandas as pd

from sktime.datasets import load_airline
from sktime.forecasting.arima import AutoARIMA
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import (
    EnsembleForecaster,
    ReducedRegressionForecaster,
    TransformedTargetForecaster,
)
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
from sktime.forecasting.model_selection import (
    ForecastingGridSearchCV,
    SlidingWindowSplitter,
    temporal_train_test_split,
)
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.theta import ThetaForecaster
from sktime.forecasting.trend import PolynomialTrendForecaster
from sktime.performance_metrics.forecasting import sMAPE, smape_loss
from sktime.transformations.series.detrend import Deseasonalizer, Detrender
from sktime.utils.plotting import plot_series

simplefilter("ignore", FutureWarning)
%matplotlib inline
`from sktime.forecasting.fbprophet import Prophet`
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-25-dbe222e3db2a> in <module>()
----> 1 from sktime.forecasting.fbprophet import Prophet
      2 
      3 forecaster = Prophet(
      4     seasonality_mode="multiplicative",
      5     n_changepoints=int(len(y_train) / 12),

ModuleNotFoundError: No module named 'sktime.forecasting.fbprophet'
```
I try to look into this but it seems fbprophet subpackage does not exist:
`from sktime import forecasting 
l=vars(forecasting).keys()
list(l)
['__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__path__',
 '__file__',
 '__cached__',
 '__builtins__',
 'base',
 'model_selection',
 'arima',
 'compose',
 'exp_smoothing',
 'naive',
 'theta',
 'trend',
 'ets']`
Could this be a build issue in the latest version? I cloned the package a couple hours ago and found fbprophet.py inside sktime/forecasting.

**Comment by mikelty** [comment]
I also tried
`pip install --upgrade sktime[all_extras] pmdarima sklearn`
and then
`from sktime.forecasting.fbprophet import Prophet`
but got the same error.

**Comment by aiwalter** [comment]
@mikelty pls see here:
https://github.com/alan-turing-institute/sktime/pull/515#issuecomment-750742290
