### ISSUE TITLE
[DOC] Guideline to add new adapters

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#586]
#### Describe the issue linked to the documentation

I was wondering if there is documentation on how `sktime` could be linked to other time series libraries. From the code, it seems that the preferred method is to [use adapters](https://github.com/alan-turing-institute/sktime/tree/v0.5.1/sktime/forecasting/base/adapters), but I could not make out what the requirements are for the adpater. Something similar to [this](https://scikit-learn.org/stable/developers/develop.html) would be helpful which will help guide what needs to be added to the adapter.

It looks like at least the `fit` method needs to be implemented, but [some adapters](https://github.com/alan-turing-institute/sktime/blob/v0.5.1/sktime/forecasting/base/adapters/_pmdarima.py) implement the `_predict` method while [others](https://github.com/alan-turing-institute/sktime/blob/v0.5.1/sktime/forecasting/base/adapters/_fbprophet.py) implement the `predict` method. I would greatly appreciate it if someone provide an overview of the requirements for these adapters?

One application could be to integrate some of the deep learning algorithms found in `darts` such as [this one](https://github.com/unit8co/darts/blob/master/darts/models/nbeats.py), but I am sure there could be others that could be added as well.

Thanks!

**Comment by mloning** [comment]
I agree, please see #464 for previous discussions. Any help is welcome!

**Comment by ngupta23** [comment]
Thank you @mloning. Sorry for missing it. It did not show up when I searched for `adapter` so I filed this new issue. I will have a look at #464  in detail.
