### ISSUE TITLE
Pandas-style lag plotting for sktime

### ISSUE THREAD

**Issue by aiexplorations** [alan-turing-institute/sktime#588]
**Is your feature request related to a problem? Please describe.**
When preparing AR and ARIMA class models, it is helpful to be able to visually inspect segments of (univariate) time series through lag plots. Currently this feature doesn't exist within sktime but exists in other packages such as pandas

**Describe the solution you'd like**
A lag plotting function should be made available within sktime with compatibility with native representation of univariate time series (pandas Series object or columns of a pandas DataFrame). Output will be a (resizeable) lag plot. 

**Describe alternatives you've considered**
1. Pandas api contains a lag plot function
2. Stable R libraries have a lag plotting function

**Additional context**
References on lag plots: 
* [Lag plot in R - Rob Hyndman's book](https://otexts.com/fpp2/lag-plots.html)
* [Pandas lag plotting from Pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.plotting.lag_plot.html)
* [Lag plot described on NIST](https://www.itl.nist.gov/div898/handbook/eda/section3/lagplot.htm)

**Comment by aiexplorations** [comment]
Turns out `statsmodels` doesn't have implementations of lag plots but `pandas` does. Have changed title to reflect this.

**Comment by mloning** [comment]
Hi @aiexplorations - thanks for creating the issue here and the links to the R resources - much appreciated!

**Comment by hassan-jvd90** [comment]
@mloning , I am a newcomer to sktime and I would also like to contribute to the project. Since, this is open, can I take this up?

**Comment by mloning** [comment]
Hi @hassan-jvd90, great, yes your contribution would be very welcome! We'd aim to reuse as much functionality from pandas/statsmodels as possible.

**Comment by hassan-jvd90** [comment]
Thanks a lot @mloning , I have created a PR for this. Please, let me know what you think.

**Comment by mloning** [comment]
Closed by #1330
