### ISSUE TITLE
Identical shapelets

### ISSUE THREAD

**Issue by Bruno-Hanzen** [alan-turing-institute/sktime#590]
When fitting shapelets to a set of time series, I get twice the same shapelet (for the same ts, at different places).
In the ts, there are zones of constant values. 2 of them are 11 positions long, so after normalization, this gives 2 shapelets with 11 "0" in "data", but different "start_pos".

I suggest testing identity or similarity of a new shapelet (data part) with the previously discovered ones. This would save time in the "fit" and "transform" execution.

**Comment by TonyBagnall** [comment]
hi, yes this is possible, although we do have a threshold to exclude shapelets with identical info gain. STC could do with some work, its on my list after sorting out distance functions

**Comment by Bruno-Hanzen** [comment]
Hi, I can confirm that the shapelets were identical, but info gain was different (0.18 and 0.14), if I remember correctly.

**Comment by TonyBagnall** [comment]
hmmm, curious, we will look into it, thanks for pointing it out
