### ISSUE TITLE
Random Grid Search for Forecasting

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#597]
**Is your feature request related to a problem? Please describe.**
I am wondering if there is a Random Grid Search equivalent of [`ForecastingGridSearchCV`](https://www.sktime.org/en/latest/api_reference/modules/auto_generated/sktime.forecasting.model_selection.ForecastingGridSearchCV.html#forecastinggridsearchcv) similar to how we have [`RandomizedSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html) equivalent of [`GridSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) in scikit-learn?

**Describe the solution you'd like**
Would like to have a random grid search equivalent of the fixed grid search option (similar to what is present in scikit-learn).

**Describe alternatives you've considered**
None so far

**Comment by pabworks** [comment]
I'd like to have a go at this, please!

**Comment by mloning** [comment]
@pabworks great - would really appreciate a PR, let us know if you need any help!

**Comment by pabworks** [comment]
@mloning I think we can mark this as Closed now - apologies, I used the wrong keyword on the PR (🤦‍♂️) so this did not close automatically

**Comment by mloning** [comment]
No worries @pabworks - closed by #634
