### ISSUE TITLE
will it work for multivariate time series prediction   both regression and classification 

### ISSUE THREAD

**Issue by Sandy4321** [alan-turing-institute/sktime#604]
great code thanks
may you clarify : 
will it work for multivariate time series prediction   both regression and classification 
1 
  where all values are continues values 
2
or  even will it work for multivariate time series where values are mixture of continues  and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

    color        weight     gender  height  age  
1    black       56              m          160    34
2    white       77              f            170    54
3    yellow      87             m          167     43
4    white       55             m            198    72
5   white       88              f            176     32

**Comment by TonyBagnall** [comment]
hi, the classification and regression tools currently only work with continuous variables. Sequence classification (i.e. categorical variables such as colour) is a whole different thing. Some classifiers work for multivariate, some dont, I'm just tidying up the capabilities to make this clearer. If you have a real valued multivariate classification problem, for now I recommend The ROCKETClassifier, it came out best in our recent bake off https://link.springer.com/article/10.1007/s10618-020-00727-3

**Comment by Sandy4321** [comment]
great thanks
only link from paper is broken
https://github.com/alan-turing-institute/sktime/blob/master/sktime/transformers/series_as_features/rocket.py

**Comment by mloning** [comment]
@Sandy4321 there's a notebook here on ROCKET: https://github.com/alan-turing-institute/sktime/blob/master/examples/rocket.ipynb

**Comment by TonyBagnall** [comment]
ah good spot, its been refactored, perhaps we can set up a redirect.
