### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'sktime.classification.frequency_based'

### ISSUE THREAD

**Issue by Hephaest** [alan-turing-institute/sktime#605]
**Describe the bug**

ModuleNotFoundError: No module named 'sktime.classification.frequency_based'

**To Reproduce**

```python
from sktime.classification.frequency_based import RandomIntervalSpectralForest

rise = RandomIntervalSpectralForest(n_estimators=10)
rise.fit(X_train, y_train)
rise.score(X_test, y_test)
```

**Expected behavior**

Generate the result: `0.8301886792452831`

**Additional context**

the code from `examples/02_classification_univariate.ipynb`

**Versions**
<details>

System:
    python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
executable: c:\users\hephaest\appdata\local\programs\python\python38\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.3.3
   setuptools: 49.2.1
      sklearn: 0.23.2
       sktime: 0.5.1
  statsmodels: 0.12.1
        numpy: 1.19.3
        scipy: 1.4.1
       Cython: 0.29.21
       pandas: 1.1.2
   matplotlib: 3.3.2
       joblib: 0.17.0
        numba: 0.52.0
     pmdarima: None
      tsfresh: 0.17.0
</details>

**Comment by mloning** [comment]
Sorry we moved the algorithm to `sktime.classification.interval_based` - checkout the latest notebooks on master to find the corrected versions. 

FYI @TonyBagnall

**Comment by Hephaest** [comment]
> Sorry we moved the algorithm to `sktime.classification.interval_based` - checkout the latest notebooks on master to find the corrected versions.
> 
> FYI @TonyBagnall

Dear @mloning,
That's why we need the community. I pull a request #606. Please merge it, thanks.

**Comment by TonyBagnall** [comment]
good spot, thanks for that, I see pycharm refactoring doesnt check notebooks! We will merge it in once its gone through the tests.
