### ISSUE TITLE
[BUG] TypeError from KNeighborsTimeSeriesClassifier

### ISSUE THREAD

**Issue by Hephaest** [alan-turing-institute/sktime#608]
**Describe the bug**

```Python

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-25-a54f834dd466> in <module>
      2 
      3 knn = KNeighborsTimeSeriesClassifier(n_neighbors=1, metric="dtw")
----> 4 knn.fit(X_train, y_train)
      5 knn.score(X_test, y_test)
      6 

~\Desktop\sktime\sktime\classification\distance_based\_time_series_neighbors.py in fit(self, X, y)
    250             check_array.__code__ = _check_array_ts.__code__
    251 
--> 252         fx = self._fit(X, self._y)
    253 
    254         if hasattr(check_array, "__wrapped__"):

TypeError: _fit() takes 2 positional arguments but 3 were given
```
**To Reproduce**

```python

from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier

knn = KNeighborsTimeSeriesClassifier(n_neighbors=1, metric="dtw")
knn.fit(X_train, y_train)
knn.score(X_test, y_test)
```

**Expected behavior**

Generate the result: `0.55`

**Additional context**

This problem occurs because that `NeighborsBase._fit()` only accept 1 positional argument (only X).

**Versions**
<details>

System:
    python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
executable: c:\users\hephaest\appdata\local\programs\python\python38\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.3.3
   setuptools: 49.2.1
      sklearn: 0.23.2
       sktime: 0.5.1
  statsmodels: 0.12.1
        numpy: 1.19.3
        scipy: 1.4.1
       Cython: 0.29.21
       pandas: 1.1.2
   matplotlib: 3.3.2
       joblib: 0.17.0
        numba: 0.52.0
     pmdarima: None
      tsfresh: 0.17.0
</details>

**Comment by TonyBagnall** [comment]
so I've had a look. scikit learn changed how KNN works in 0.24. _fit(X) was replaced by _fit(X, y=None), with a test for a _tag whether 'requires_y' is true. we can recreate previous behaviour by turning off the tag requires_y, 
  def _more_tags(self):
        return {'requires_y': False}

However, y might well be required for the GridSearchCV, and the absence of the y values may explain why for example MSM gives the same values for different parameter combinations. I'm not sure yet, so I will delay pushing a solution to master until I have debugged it further
