### ISSUE TITLE
Refit with ForecastingGridSearchCV when using a Grid Search based forecasters may not use "best hyperparameters"

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#620]
**Describe the bug**
When using a Grid Search based forecaster (such as `AutoARIMA`, or `ReducedRegressionForecaster` with `GridSearchCV` from scikit-learn) in `ForecastingGridSearchCV`, the best hyperparameters that are found in the `initial_window` may not be used when the final refit is done. 

The outer Grid Search (that in `ForecastingGridSearchCV`) works fine and picks the right hyperparameters for the final fit, but the inner Grid Search is a problem. This is due to the fact that the final refit is simply calling the fit function on the full data which leads to the entire "inner" grid search to be rerun. This may lead to a different set of best hyperparameters being selected than those that were selected during the fit in the `initial_window`. 

**Since the final hyperparameters can be different from the ones used in the sliding cross validation, this has the potential to make the cross validation results incorrect (i.e. cross validation results will not correspond to the final model hyperparameters that are refit).**

**To Reproduce**

```python
y = load_airline()
fh = np.arange(1, 13)  

y_train, y_test = temporal_train_test_split(y, test_size=len(fh))

cv = SlidingWindowSplitter(
    initial_window=int(len(y_train) * 0.5),
    start_with_window=True,
)

# ARIMA
forecaster_param_grid = {"sp": [12, 24]}
forecaster = AutoARIMA(suppress_warnings=True)

gscv_arima = ForecastingGridSearchCV(
    forecaster, cv=cv, param_grid=forecaster_param_grid, verbose=True
)
gscv_arima.fit(y_train)
```

**During the Grid Search, the hyperparameter values with sp=12 indicate that only 2 lags are selected along with a seasonal lag. Note, I have left out the parameters for sp=24 since that is not selected as the final best_forecaster.**

```python
# Initial Window Fit
forecaster._get_fitted_param_names()
['intercept', 'ar.L1', 'ar.L2', 'ar.S.L12', 'sigma2']
forecaster._get_fitted_params()
array([ 7.99081197,  0.56606485,  0.1956277 , -0.47478481, 68.31476303])
```

**Best Estimator**
```python
self.best_forecaster_
AutoARIMA(sp=12, suppress_warnings=True)
```

**Final Refit: This seems to indicate that there 3 lags should be used. This means that the hyperparameters selected by the final fit are not the same as those selected by the fit in the "initial_window". Note, that the actual parameter values will be different and that is OK, but the hyperparameters (param_names below) should be the same for the initial window and final refit.**

```python
self.best_forecaster_._get_fitted_param_names()
['intercept', 'ar.L1', 'ar.L2', 'ar.L3', 'sigma2']
self.best_forecaster_._get_fitted_params()
array([  5.53410033,   0.70489183,   0.25742152,  -0.14344774, 101.09688613])
```

**Expected behavior**
The param names should be the same as those selected in the initial window. 

**Additional context**
The same issue can potentially be observed when `ReducedRegressionForecaster` with `GridSearchCV` from scikit-learn is used in `ForecastingGridSearchCV`.

An example is shown below (note that in this case, it ends up picking the same hyperparameter in the final refit as in the `initial_window`, but since the `GridSearchCV` object is fit again in the end without any regard to the hyperparameters selected in the `initial_window`, it could have picked different hyperparameters.

```python
regressor_param_grid = {"n_estimators": [200, 300]}
forecaster_param_grid = {"window_length": [12, 15]}
tscv = TimeSeriesSplit()

# create a tunnable regressor with GridSearchCV
regressor = GridSearchCV(
    RandomForestRegressor(),
    param_grid=regressor_param_grid,
    cv = tscv,
    scoring='neg_mean_squared_error',  
    verbose=1
)
forecaster = ReducedRegressionForecaster(
    regressor, strategy="recursive"
)

gscv = ForecastingGridSearchCV(
    forecaster, cv=cv, param_grid=forecaster_param_grid, verbose=1
)
gscv.fit(y_train)
```

### Possible Solution
Implement a refit method in the forecasters. 
- For the Grid Search Based forecasters, this will pluck the "best hyperparameters" based on the "inner" grid search and use those for the final fit by setting those explicitly in the underlying forecaster (`ARIMA` for `AutoARIMA`, `RandomForestRegressor` for `ReducedRegressionForecaster`, etc.) instead of performing the "inner" grid search again.
- For non Grid Search based forecasters, this can simply alias the fit method.

**Versions**
<details>

```python
System:
    python: 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Nikhil\.conda\envs\sktime_dev\python.exe
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
          pip: 20.3.3
   setuptools: 51.0.0.post20201207
      sklearn: 0.24.0
       sktime: 0.5.1
  statsmodels: 0.12.1
        numpy: 1.19.4
        scipy: 1.5.4
       Cython: 0.29.17
       pandas: 1.1.5
   matplotlib: 3.3.3
       joblib: 1.0.0
        numba: 0.52.0
     pmdarima: 1.8.0
      tsfresh: 0.17.0
```
</details>

**Comment by fkiraly** [comment]
@ngupta23, short comments on first read:
* the issue you describe is not a bug, since you're not describing a discrepancy between expected/contracted functionality and actual functionality. You're actually commenting on what higher-order algorithm `ForecastingGridSearchCV` should implement in your opinion, and a discrepancy between that and the status quo.
* I agree we may want to carefully think about, and then document expected/contracted behaviour. There is lack of proper documentation of intended "should" here.
* I'm not sure I agree with your "should" state here. This would lead to two different algorithms being implemented, depending on the specific implementation of the wrapped estimator, not just on the type. I think dispatch-on-concrete, as opposed to dispatch-on-type, should be avoided.

**Comment by ngupta23** [comment]
Hi @fkiraly 

Definitely, more documentation on this would be nice since it was definitely not what I was expecting and would not have figured that out unless I was looking deeper into the code. 

And I agree that if that if this was intentionally done this way, then this is not a bug.

That being said, is there a way to do what I am asking in sktime right now or is it planned?

Thanks!

**Comment by fkiraly** [comment]
>That being said, is there a way to do what I am asking in sktime right now or is it planned?

That depends entirely on what you mean by "what I am asking", but I guess not.
Though I might also contest whether what you are asking is the behaviour we'd ultimately want.

Generally, I think one takeaway of this is that we may want to think carefully about how to document our higher order algorithms, since the devil is in the detail, and the expected/actual may differ if it is not properly written up somewhere.
Any opinions, @mloning?

**Comment by mloning** [comment]
@ngupta23 Having looked into this a bit more, I agree that this it not a bug and indeed what I would expect to happen - similar to what I'd expect to happen if I'd put a `GridSearchCV` into a `GridSearchCV` object in scikit-learn. 

If you do not want to run nested CV, you can just use temporal CV and optmise over the entire parameter grid: 
```python
from sktime.forecasting.all import *
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

y = load_airline()
fh = np.arange(1, 13)  

y_train, y_test = temporal_train_test_split(y, test_size=len(fh))

param_grid = {"regressor__n_estimators": [200, 300], "window_length": [12, 15]}

cv = SlidingWindowSplitter(
    initial_window=int(len(y_train) * 0.5),
    start_with_window=True,
)
regressor = RandomForestRegressor()
forecaster = ReducedRegressionForecaster(regressor, strategy="recursive")
gscv = ForecastingGridSearchCV(forecaster, cv=cv, param_grid=param_grid, verbose=1)
gscv.fit(y_train)
gscv.best_params_
```

I agree that we need to better document this. I'm also not sure what works better empirically, or what is being used more often in practice.

**Comment by ngupta23** [comment]
@fkiraly Thanks for the feedback on this topic. 
@mloning , Thanks for the alternate code. Let me try this out and get back in case there are any further questions. If this works as expected, it might be good to document this in the forecasting example notebook.

**Comment by ngupta23** [comment]
Hi @mloning , Thank you for the alternate code for `ReducedRegressionForecaster`. I verified that this alternate (without using `GridSearchCV` in the regressor) works great when using `scikit-learn` based regressors.

However the issue still exists with AutoARIMA since it is essentially an intelligent Grid Search. Do you have an alternate that works for `AutoARIMA` as well?

**Comment by mloning** [comment]
@ngupta23 if you do not want to use AutoARIMA, why not use simply ARIMA with a pre-defined grid for hyper-parameters?

**Comment by ngupta23** [comment]
I was afraid of that :). There are just too many hyperparameter combinations to try with the base ARIMA from `statsmodels`. Let me try it out anyway to see what can be done. Thanks again for your guidance on this.
