### ISSUE TITLE
[BUG] Hourly data series fails to pass np.isnan checks

### ISSUE THREAD

**Issue by abendinelli** [alan-turing-institute/sktime#623]
When following the tutorial and attempting to use an hourly data series, the ForecastingHorizon is passing a numpy.ndarray with type "object" instead of "float64". This causes the last window checks to fail because np.isnan() does not work on "object" type ndarrays.

My code:

```
df = pd.DataFrame(rows, columns=cols)

df['dtime'] = pd.to_datetime(df['DATE_DAY'].astype('str') + ' ' + df['HOUR'].astype('str') + ':00:00')
df = df.set_index('dtime')

zoom = df["2020-05-01":"2020-11-01"]['SESSION_MINUTES']
zoom.index = zoom.index.to_period('H')
zoom_series = pd.Series(zoom)

from sktime.forecasting.model_selection import temporal_train_test_split
y_train, y_test = temporal_train_test_split(zoom_series, test_size=720)
plot_series(y_train, y_test, labels=["y_train", "y_test"])

fh = ForecastingHorizon(y_test.index, is_relative=False)

from sklearn.neighbors import KNeighborsRegressor

regressor = KNeighborsRegressor(n_neighbors=1)
forecaster = ReducedRegressionForecaster(
    regressor=regressor, window_length=12, strategy="recursive"
)
forecaster.fit(y_train)
y_pred = forecaster.predict(fh)
plot_series(y_test, y_pred, labels=["y_test", "y_pred"])
```

The fix I had to implement in sktime/forecasting/compose/_reduce.py on line 330:

```
    def _predict_last_window(
        self, fh, X=None, return_pred_int=False, alpha=DEFAULT_ALPHA
    ):
        """Predict"""
        # compute prediction
        # prepare recursive predictions
        fh_max = fh.to_relative(self.cutoff)[-1]
        y_pred = np.zeros(fh_max)

        # get last window from observation horizon
        last_window, _ = self._get_last_window()
        last_window = last_window.astype('float64')      # This is the fix
        if not self._is_predictable(last_window):
            return self._predict_nan(fh)

        # recursively predict iterating over forecasting horizon
        for i in range(fh_max):
            X_last = self._format_windows(
                [last_window]
            )  # convert data into required input format
            y_pred[i] = self.regressor_.predict(
                X_last
            )  # make forecast using fitted regressor

            # update last window with previous prediction
            last_window = np.append(last_window, y_pred[i])[-self.window_length_ :]

        fh_idx = fh.to_indexer(self.cutoff)
        return y_pred[fh_idx]
```

There are other places where the np.isnan() check is failing due to the "object" type of the array. 

System:
    python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.3.3
   setuptools: 49.2.1
      sklearn: 0.24.0
       sktime: 0.5.2
  statsmodels: 0.12.1
        numpy: 1.19.3
        scipy: 1.5.4
       Cython: 0.29.17
       pandas: 1.1.5
   matplotlib: 3.3.3
       joblib: 0.17.0
        numba: 0.52.0
     pmdarima: 1.8.0
      tsfresh: None

**Comment by mloning** [comment]
Thanks @abendinelli for raising the issue. 

What's the data type of `zoom_series `? If it's not a float type, could you coerce it to float? 

This is something we should catch in our input checks.

**Comment by mloning** [comment]
I cannot reproduce without more details, please feel free to reopen and post a minimal, reproducible example!
