### ISSUE TITLE
Overlap of training and test window in SlidingWindowSplitter

### ISSUE THREAD

**Issue by koralturkk** [alan-turing-institute/sktime#626]
https://github.com/alan-turing-institute/sktime/blob/36f3cb1b96421bb08e041d16949d3d8a9be6f7d8/sktime/forecasting/model_selection/_split.py#L217

Hi, 

The last element of training window and first element of test window overlaps here. As a fix, simply -1 can be removed. Bests,

```
from sktime.datasets import load_airline
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.model_selection import (
    ForecastingGridSearchCV,
    SlidingWindowSplitter,
    temporal_train_test_split,
)

y = load_airline()
y_train, y_test = temporal_train_test_split(y, test_size=36)

fh = ForecastingHorizon(y_test.index, is_relative=False)
cv = SlidingWindowSplitter(step_length= 3, fh = list(range(3)), window_length= 20)

windows = cv._split_windows(y_train)
for i in list(windows)[:10]:
    print(i)
```

(array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1]), array([-1,  0,  1]))
(array([-17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2]), array([2, 3, 4]))
(array([-14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,
        -1,   0,   1,   2,   3,   4,   5]), array([5, 6, 7]))
(array([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,
         2,   3,   4,   5,   6,   7,   8]), array([ 8,  9, 10]))
(array([-8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11]), array([11, 12, 13]))
(array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14]), array([14, 15, 16]))
(array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17]), array([17, 18, 19]))
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20]), array([20, 21, 22]))
(array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23]), array([23, 24, 25]))
(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26]), array([26, 27, 28]))

**Comment by mloning** [comment]
Closed in favour of #628
