### ISSUE TITLE
Forecasting via Reduction to MultiOutput Regression

### ISSUE THREAD

**Issue by Lovkush-A** [alan-turing-institute/sktime#629]
Issue to track and discuss the implementation of the forecasting via reduction to multioutput regression.

**Describe the solution you'd like**
I intend to work on this. Presumably it is enough look at similar forecasters, and adjust them appropriately.

**Additional context**
Recommended good first issue in conversation between me and @mloning.

**Comment by mloning** [comment]
Thanks @Lovkush-A, just saw that there was an issue already (#403) - sorry about that!
