### ISSUE TITLE
[ENH] New classifier - Similarity Forest

### ISSUE THREAD

**Issue by ppias** [alan-turing-institute/sktime#631]
Together with prof. T. Górecki and prof. T. Łuczak we are currently working on adjusting Similarity Forest (proposed by S. Sathe and C.C. Aggrawal [reference](http://saketsathe.net/downloads/simforest.pdf) ) to time series data. It seems to be very fast (~ O(n log(n)/O(log(n) for training/inference) and at the same time more accurate than e.g. TSF. We are going to develop this method and would like to make it widely available. Sktime seems to be a perfect place for that.

**Comment by mloning** [comment]
Hi @ppias - thanks again for reaching out and for creating the issue here! Sounds like a great idea to me! Any thoughts, @TonyBagnall!

**Comment by TonyBagnall** [comment]
hi, that would be great, we would welcome the contribution

**Comment by Lovkush-A** [comment]
@ppias After seeing this PR, I read the paper Similarity Forests and decided to write a [short summary of it](https://lovkush-a.github.io/blog/data%20science/2021/04/17/trees_variants.html). @ppia: have I understood it correctly?  I would be interested to know what changes you are making in order to adapt it to time series. Is the main thing coming up with suitable similarity metrics, or are there other details?

**Comment by TonyBagnall** [comment]
hi @ppias are you still hoping to do this or should I close the issue? We would still welcome the contribution, but I am doing some housekeeping and closing issues that are no longer relevant

**Comment by ppias** [comment]
Hi @TonyBagnall, sorry for the poor communication. It turned out that the performance is not that good as expected, so now I will be working on some improvements. Will try to give some update in ~3months.

**Comment by TonyBagnall** [comment]
hi @ppias no problem, happy to leave this open if it might pan out into something, thanks for working on it.

**Comment by ppias** [comment]
Hi @TonyBagnall. Sorry to inform we aborted the idea. The algorithm was not that efficient as we expected. Even after several improvements it was barely better then 1NN or simple random forest.

Sorry it took so long - issue may be closed now. Anyway, maybe will contribute to Your great library in the future in some other way.

**Comment by fkiraly** [comment]
alright, thanks for letting us know.
