### ISSUE TITLE
Converting data to nested dataframe.

### ISSUE THREAD

**Issue by Leonardbcm** [alan-turing-institute/sktime#641]
Hi everyone,

Im am trying to use sktime for time series forecasting. I have a stream of multivariate data with a daily granularity and the objective is to produce a forecast everyday for the next one.
My data is formated the following way : each column represent a feqature of the multivariate time serie, and each row is a timestamp.
I want to convert it into a nested dataframe. I can do this manually by copying data and replacing each cell by the correponding serie but I was wondering if such function would exist in sktime. 

**Describe the solution you'd like**
I would like to have a function that converts a DataFrame containing a multivariate time serie into a nested dataframe, usable by sktime's algorithms. A function where you could chose the time series length would be perfect.

**Describe alternatives you've considered**
I have tried converting my data into other formats which have their converting functions but the code required is as long as for converting into a nested dataframe.

**Additional context**
Here is a sample from my data so that you can understand their format.
![image](https://user-images.githubusercontent.com/48202779/106453246-48d2be00-6489-11eb-840c-df7a875dbb88.png)

Thanks for your help!

**Comment by mloning** [comment]
Hi @Leonardbcm thanks for raising the issue. A few question to better understand what you're trying to do: 

* Are you trying to forecast all series simultaneously, or only a single series using the information from the other series as exogenous variables?
* In the sample data, what do the `day_1`, `day_2` columns represent? Are they some lagged values for some variable?

For forecasting, you probably don't need to worry about the nested format. We currently do not support multivariate forecasting directly if that's what you want to do, but there are ongoing development efforts to add it https://github.com/sktime/enhancement-proposals/pull/4.

**Comment by Leonardbcm** [comment]
Hi and thanks for your answers. I will clarify my problem.

> Are you trying to forecast all series simultaneously, or only a single series using the information from the other series as exogenous variables?

I am trying to forecast only one of the series using all other series AND the one I want to forecast. Let's say I want to forecast the serie 'FR_consumption_mean', I can use the information from 'day_1', 'day_2', etc... from the same and previous rows and the preivous values of 'FR_consumption_mean'.

> In the sample data, what do the day_1, day_2 columns represent? Are they some lagged values for some variable?

Yes, more precisly they consist in the day of the month circularly encoded. I know this is irrelevant if I use a Time Series model. Let's just consider them as regular series for the sake of the example.

> We currently do not support multivariate forecasting directly if that's what you want to do

Yes I am aiming at performing multivariate time series forecasting. Indeed, I was trying to convert my data into the nested dataframe format to be able to use the proposed models for forecasting.

I hope I have made this clearer, let me know if it is not.
Thanks again for your time!

**Comment by mloning** [comment]
When you want to forecast only a single series but use multiple other related series, we'd call this univariate forecasting with exogenous variable, terminology is ambiguous here. Multivariate forecasting we'd call the problem of forecasting multiple series simultaneously. 

We do support univariate forecasting with exogenous variables, at least some methods do. Check out `AutoARIMA` for example. Multivariate forecasting is under development but nothing has been implemented so far.

**Comment by Leonardbcm** [comment]
Ok thanks a lot for your answer. I will keep an eye on the repo to check for further developpement.
