### ISSUE TITLE
Rename master branch to main 

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#644]
I suggest to rename our current `master` branch to the new GitHub standard name `main`.  

More details on why and what has to be done here: https://github.com/alan-turing-institute/the-turing-way/issues/1210

**Comment by 96RadhikaJadhav** [comment]
@mloning In which files we need to rename it can you please mention?

**Comment by mloning** [comment]
Hi @96RadhikaJadhav - take a look at the linked issue from The Turing Way, they provide all the details. In terms of in file references to `master`, I'd do a search over the entire repository to find out where we refer "master". Does that help?

**Comment by ayan-biswas0412** [comment]
@mloning Can I do it ? Can I Make a PR after necessary changes ??

**Comment by mloning** [comment]
Hi @ayan-biswas0412, let's check: @96RadhikaJadhav are you still working on this? If not, @ayan-biswas0412 can do it!

**Comment by ayan-biswas0412** [comment]
@mloning I have a question just for my knowledge enhancement , what I have to do with the script which is given in your mentioned link, that python script https://gist.github.com/sgibson91/44a1c3a6bbf34257dbdbb621a98dab0d , Can you please solve my doubt

**Comment by 96RadhikaJadhav** [comment]
@mloning  For now, I'm bit busy with other issues. It may take some time for me to grab this one. Meanwhile, @ayan-biswas0412  you can work on it if you want. 
Thank You.

**Comment by ayan-biswas0412** [comment]
> @mloning For now, I'm bit busy with other issues. It may take some time for me to grab this one. Meanwhile, @ayan-biswas0412 you can work on it if you want.
> Thank You.

great I can do it but @mloning for changing the base branch I think I have to get the repository access as contributor

**Comment by fkiraly** [comment]
@ayan-biswas0412, I think we can simply use the "rename" option that is also mentioned in the link - the readme asserts that this will also rename all references incl PR targets.
https://github.com/github/renaming#renaming-existing-branches

@mloning, that´s a one-click-thing in the admin config, can you confirm that it looks to you as well that we don´t need any help for this (since it´s a one-button-action)?

**Comment by fkiraly** [comment]
... anything about the CI set-up that will break, maybe?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412, I think we can simply use the "rename" option that is also mentioned in the link - the readme asserts that this will also rename all references incl PR targets.
> https://github.com/github/renaming#renaming-existing-branches
> 
> @mloning, that´s a one-click-thing in the admin config, can you confirm that it looks to you as well that we don´t need any help for this (since it´s a one-button-action)?
> 
> (I´m not doing anything since I might be missing something obvious here)

I also feel same like you that it is a one click action in the admin config

**Comment by mloning** [comment]
As Sarah summarised in the linked issue: Things that the new feature won't do:

- [ ] Rewrite our CI files to the correct branch
- [ ] Update any docs

So as suggested above, I'd do a search over the entire repository to find out where we refer "master" and replace that with "main". 

I'm happy to make the changes in the repo settings that require admin access.

**Comment by ayan-biswas0412** [comment]
> As Sarah summarised in the linked issue: Things that the new feature won't do:
> 
> * [ ]  Rewrite our CI files to the correct branch
> * [ ]  Update any docs
> 
> So as suggested above, I'd do a search over the entire repository to find out where we refer "master" and replace that with "main".
> 
> I'm happy to make the changes in the repo settings that require admin access.

I can do the changes in the entire repo and change the master to main , please can I do that ? I will be highly obliged

**Comment by mloning** [comment]
@ayan-biswas0412 Sure, I'd start with the docs (including docs like CONTIRBUTING.md) and open a PR to see if everything passes. Changing the CI files will likely break the CI on the PR, so let's start with the docs.

**Comment by ayan-biswas0412** [comment]
@mloning can you review by PR #667

**Comment by mloning** [comment]
From: https://docs.github.com/en/github/administering-a-repository/renaming-a-branch

After you rename a branch in a repository on GitHub, any collaborator with a local clone of the repository will need to update the clone. From the local clone of the repository on a computer, run the following commands to update the name of the default branch:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by ayan-biswas0412** [comment]
@mloning do I need to do anything more in my PR ? or it is fine now

**Comment by mloning** [comment]
PR looks good, thanks again @ayan-biswas0412, we just need to find a good time to make the change.

**Comment by mloning** [comment]
FYI we needed to update readthedocs and codecov settings too.
