### ISSUE TITLE
[BUG] Variable length time series throw an error in DTW in elastic.py

### ISSUE THREAD

**Issue by goastler** [alan-turing-institute/sktime#645]
**Describe the bug**
In elastic.py, the vanilla python implementation of DTW apparently doesn't handle variable length time series properly. I believe it assumes the cost matrix is square, which it will not be for time series of different lengths. https://github.com/alan-turing-institute/sktime/blob/74c14cbdf01f5acb55294f69738e03facf09c80f/sktime/distances/elastic.py#L54

**Expected behavior**
The cost matrix is sized corresponding to each of the input time series allowing for variable length time series.

**Comment by TonyBagnall** [comment]
rolled into #596
