### ISSUE TITLE
Distance measure unit testing

### ISSUE THREAD

**Issue by goastler** [alan-turing-institute/sktime#646]
**Is your feature request related to a problem? Please describe.**
Distance measures are currently not tested, both python or cython implementations. This leads to bugs like #645 and #596 

**Describe the solution you'd like**
For every distance measure, a corresponding unit test should be made to check known inputs against known outputs. This will a) test whether the distance measures are working properly and b) run checks in travis ensuring any new development does not silently break / alter the distance measure code / behaviour.

**Describe alternatives you've considered**
No alternatives afaik.

**Additional context**
This will help with any classifier which uses distance measures, as if the distance measure pass all tests but your classifier does not you know the problem lies in your classifier rather than the distance measures. Likewise, the reverse is true if a problem lies in a distance measure instead of your classifier.

**Comment by TonyBagnall** [comment]
rolled into #596
