### ISSUE TITLE
[DOC] Update example notebook for forecasting for tuning and model evaluation

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#650]
#### Describe the issue linked to the documentation
After implementing #647, #648 and #649 we need to update the forecasting tutorial to better describe the user journey and different available options.

**Comment by mloning** [comment]
We should cover the following use cases:

## 1. Single fixed cut-off forecasting
* single prediction

## 2. Moving cut-off forecasting
* most common deployment case
* updating
* online learning
* requires more dynamic update-and-predict routines

## 3. In-sample prediction


## 4. Evaluating forecasts
* Sliding window evaluation
* dynamic update-and-predict routine

## 5. Composite forecasters
### 5.1. Reduction 
Most machine learning approaches to forecasting involve some form of reduction. Typically, we do this by the following procedure: For training, to get the required tabular feature matrix, the training time series is split into multiple windows of a fixed length and stacked on top of each other to form the two-dimensional feature matrix of lagged values. To get the target variable, for each window, the subsequent observation after the window are used. Given the result feature matrix and training vector, the regressor can be fitted to the data. For predictions, the fitted regressor uses the last available window of the training series to predict the first step ahead and is then applied recursively to predict multiple steps ahead using previously predicted values. This is sometimes called lagged variable regression or auto-regression.

* multiple tunable hyper-parameters, including how you reduce forecasting to regression:
* recursive strategy, most popular one
* direct strategy: needs fh in fit
* use compositor class to (i) expose tunable hyper-parameters and (ii) adapt regressors to forecasting setting/API, so that they can be used with other model selection/evaluation functionality

### 5.2. Detrending
* detrending by returning residuals from forecasted values
* requires in-sample predictions, single interface point for obtaining predictions

### 5.3. Pipelining
* transformed target pipelines
* detrending with some simple forecaster
* predicting residuals with more complicated model

### 5.4. Ensembling
* aggregating multiple forecasts

## 6. Model selection 
* inlcuding tuning over models for different steps in forecasting horizon, selecting a separate model for each step ahead, need fh in fit
* requires update-and-predict routine

**Comment by fkiraly** [comment]
done, right?
