### ISSUE TITLE
Implement Multiplexer

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#651]
**Is your feature request related to a problem? Please describe.**
Arising from the call on Feb 2 on forecasting model selection & evaluation.

The multiplexer is a component that allows easy tuning for selection over a list of estimators with potentially distinct parameters

**Describe the solution you'd like**
The high-behaviour is as follows.

The multiplexer takes a named list (dict) of components at initialization, `components`.
It also has a single `select` parameter that should be identical to one of the components´ names.

The behaviour of the estimator is identical to the component `components[select]`, the other components are ignored.

Why is this useful:
this is arising from a suggestion by @aiwalter that model selection should be possible over inhomogenous (not the same) estimators.

Better than the "naive" solution to write a custom grid search and random search is the solution to wrap a multiplexer in a tuner - this way, model selection can be done using any evaluation strategy, e.g., grid search, random search, Bayesian optimization, etc.

**Usage and implementation sketch**

```python
class Multiplexer
    def __init__(self, components, select=None):
        self.components = components
        self.select = select
        
    def fit(self, ...):
        self.components[select].fit(...)

    def predict(self, ...):
        self.components[select].predict(...)
        
    def update(self, ...):
        self.components[select].update(...)
```

To get model selection, one would then write the following:

```python
mpx = Multiplexer({"ARIMA": ARIMA(sth), "ExpS": ExpSmoothing(sth)])
grid = {"select": ["ARIMA", "ExpSmoothing"]}
gscv = ForecastingGridSearchCV(mpx, grid, ...)
```
A technical challenge might be to check whether this works well with nested `get_params`/`set_params`.
Easy solution might just be to "unpack" the list in the constructor.

**Comment by aiwalter** [comment]
thx @fkiraly  for writing this idea down here! I might work on it, but currently I have other topics with a higher priority which I would like to add to `sktime` before :)

**Comment by koralturkk** [comment]
Hey everyone, I can take on doing this one? @mloning 

@fkiraly I am not sure if I could fully understand the need to provide a select parameter to pick an estimator among other estimators we provided in components and ignore others. Could you please elaborate further on that? 

I believe the responsibility of multiplexer should be to run a search for the best model over given model components, however providing a functionality to take the subset of those models that have given in components by a select parameter might not be needed, if I have understood it correctly.

**Comment by mloning** [comment]
yes sure @koralturkk
