### ISSUE TITLE
[BUG] Derivative based distance measures error out

### ISSUE THREAD

**Issue by goastler** [alan-turing-institute/sktime#654]
**Describe the bug**
WDDTW and DDTW both error out due to improper usage of numpy's diff operation. Note this only affects the python implementations of these distances - the cython versions do not have this error.

**To Reproduce**
Run either WDDTW or DDTW with two numpy multidimensional time series arrays (i.e. two 3d arrays).

`derivative_dtw_distance(np.array([[1,2,3],[4,5,6]]), np.array([[7,8,9],[10,11,12]]))`

**Expected behavior**
No error.

**Additional context**
The diff usage (iirc) is incorrect for computing the derivative anyway. We should change this to compute the derivative properly.

**Comment by TonyBagnall** [comment]
hi, I've rolled this into #596
