### ISSUE TITLE
[BUG] ERP in cython produces an error

### ISSUE THREAD

**Issue by goastler** [alan-turing-institute/sktime#655]
**Describe the bug**
ERP produces an error on the cython version, complaining about the `ll` variable. Likely a problem with multiple dimensions.

**To Reproduce**
erp_distance(np.array([[1, 2, 3], [4, 5, 6]]), np.array([[7, 8, 9], [10, 11, 12]]))

(make sure to import the cython version! The python version is fine!)

**Expected behavior**
No error.

**Comment by xuyxu** [comment]
Hi @goastler, I cannot reproduce your problem using the cython distince metirc.

``` python
import numpy as np
from sktime.distances.elastic_cython import erp_distance


if __name__ == "__main__":

    a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
    b = np.array([[7, 8, 9], [10, 11, 12]], dtype=np.float64)
                 
    print(erp_distance(a, b))
```

The running result is:
``` bash
>>> 6.0
```

**Comment by mloning** [comment]
Closed now since cython distances have become deprecated.
