### ISSUE TITLE
Design & implementation of supervised forecasting API

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#66]
* For classical forecasting API, see #18, #218 and corresponding [API design document](https://github.com/alan-turing-institute/sktime/wiki/Forecasting-API-proposal)
* For exemplar supervised forecasting API, see [pysf](https://github.com/alan-turing-institute/pysf)

**Comment by mloning** [comment]
For enhancement proposal, see https://github.com/sktime/enhancement-proposals/tree/master/steps/04_supervised_forecasting_api

**Comment by fkiraly** [comment]
@ahmedgc FYI

**Comment by fkiraly** [comment]
I can't find the thesis anymore, but I'm attaching the working version of a paper.
[supervisedforecast.pdf](https://github.com/alan-turing-institute/sktime/files/5435003/supervisedforecast.pdf)

**Comment by mloning** [comment]
@DanieleBaranzini I saw your comment on the [YouTube video](https://www.youtube.com/watch?v=wqQKFu41FIw&lc=UgxK6NUyo6N1J9hAl3h4AaABAg.9FX3dxddUas9JeT2TyNScg), we haven't implemented anything yet, would you be interested in contributing?

**Comment by mloning** [comment]
Discussion moved here: https://github.com/sktime/enhancement-proposals/tree/master/steps/04_supervised_forecasting_api
