### ISSUE TITLE
[BUG] Proximity Forest always using 2 processors

### ISSUE THREAD

**Issue by isma3ilsamir** [alan-turing-institute/sktime#663]
I know PF performance was discussed before in #155 , but PF seems to be very slow and always uses only 2 Processors during the training and predicting processes.

No matter what value is passed to the n_jobs parameter. it is always the same performance on my side.

Am I missing something here ??

**Comment by TonyBagnall** [comment]
I'll tag @goastler in this

**Comment by TonyBagnall** [comment]
hi, I've rolled this into #596 so will close this and update there when its sorted
