### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by MuslimBeibytuly** [alan-turing-institute/sktime#664]
**Is your feature request related to a problem? Please describe.**
It would be great if this package supported python3.9 since it's production-ready 

**Describe the solution you'd like**
Adding it to github action to upload pypi

**Comment by mloning** [comment]
Hi @MuslimBeibytuly - yes adding support for 3.9 would be great! 

It depends if all our dependencies already provide support for 3.9. The other question is if the manylinux containers already support 3.9.

**Comment by xuyxu** [comment]
> Hi @MuslimBeibytuly - yes adding support for 3.9 would be great!
> 
> It depends if all our dependencies already provide support for 3.9. The other question is if the manylinux containers already support 3.9.
 
BTW, I am wondering when will we discard the support on python 3.6. It has hindered us from using Numpy 1.20.X, which contains many improvements and new features.

**Comment by mloning** [comment]
@xuyxu good question, the next release will still support 3.6, we can consider removing it for the following release after that.

**Comment by discdiver** [comment]
I think it's worth adding to the install instructions that 3.9 is not supported and changing the relevant badge. Right now, the badge just says that 3.6+ is supported.

**Comment by xuyxu** [comment]
> I think it's worth adding to the install instructions that 3.9 is not supported and changing the relevant badge. Right now, the badge just says that 3.6+ is supported.

Replace `https://img.shields.io/badge/python-3.6+-blue?logo=python` in [README.rst](https://raw.githubusercontent.com/alan-turing-institute/sktime/main/README.rst) with `https://img.shields.io/pypi/pyversions/sktime`

**Comment by mloning** [comment]
Thanks @discdiver and @xuyxu - will update the README. 

For our current CI setup, we would need miniconda with Python 3.9 on appveyor which isn't there yet (https://www.appveyor.com/docs/windows-images-software/#python), but may be worth switching Windows builds to GitHub Actions or some other CI provider:

**Comment by fkiraly** [comment]
@freddyaboulton FYI

**Comment by fkiraly** [comment]
Done in https://github.com/alan-turing-institute/sktime/pull/1255
