### ISSUE TITLE
[BUG] fbprophet installation error on Windows

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#666]
I reinstalled on a windows machine and had trouble with fbprophet when installing the soft dependencies

![image](https://user-images.githubusercontent.com/9594042/107203282-23970000-69f3-11eb-9661-33479c7a9423.png)

**Comment by aiwalter** [comment]
@TonyBagnall installing `fbprophet` on windows is a bit tricky, I decided to use miniconda to get it running. Can you try the following in sequence:

```
pip uninstall -y pystan fbprophet
conda install libpython m2w64-toolchain -c msys2
pip install pystan
pip install fbprophet
```
So generally, this issue is not directly related to `sktime`.

**Comment by kanand77** [comment]
@aiwalter I'm currently running on a Mac machine. 

We tested Pystan: it seems Pystan 2.19 is installed correctly. Doesn't look like I should be getting any issues as I followed all the previous build steps and it works till I run pytest sktime/ 

This is the error I'm getting: 
<img width="1363" alt="Screen Shot 2021-02-23 at 2 00 38 PM" src="https://user-images.githubusercontent.com/64884188/108913920-84236100-75df-11eb-9fc2-870eea70f492.png">

Stored in a gist: https://gist.github.com/kanand77/b3e33f4ac62aa15480d2b1a33775deac

**Comment by luiszugasti** [comment]
@aiwalter I wish I somehow could replicate your conda environment (could you potentially publish it as a docker environment?)

I tried your suggestion as you mentioned. Remarkably, I get an error from installing soft dependencies suggesting that fbprophet does not install. However importing it and printing in a python prompt for the same environment prints 0.7.1.

P.S. Thanks and sorry for my late reply. Working on WSL has so far removed my need for working on windows but once @kanand77 and I resolve #212 I'd love to hop on debugging why this happens (or just get a docker image of your install published! :) )

**Comment by aiwalter** [comment]
@luiszugasti I have two other options you might try:

1) Above solution but with this instead:
`pip install pystan --no-cache`

2) Installation via conda:
```
conda install -c conda-forge pystan
conda install -c conda-forge fbprophet
````
Btw I am using Python 3.7.

**Comment by aiwalter** [comment]
@koralturkk maybe you can support here regarding above problem on Mac or at least write how you did installation of `fbprophet`?

**Comment by kanand77** [comment]
> conda install -c conda-forge pystan
> conda install -c conda-forge fbprophet

@aiwalter this above code snippet worked for me. I was able to get pytest sktime running successfully after installing pystan and fbprophet w the above method. Thank you!
