### ISSUE TITLE
TSF importance curve normalization (remove bias)

### ISSUE THREAD

**Issue by aabanda** [alan-turing-institute/sktime#669]
**Is your feature request related to a problem? Please describe.**
The TimeSeriesForestCLassifier computes the importance curve for each of the extracted features in each time index. However, as the authors point out "different time indices are associated with different numbers of intervals", and, in particular, "the indices in the middle have more intervals than the indices on the edges of the time series". The importance curves are, hence, biased towards the time points having more interval features. 

**Describe the solution you'd like**
I propose to normalize the importance curve at each point by dividing the importance by the number of intervals that the point is part of.  The authors mention that the number of intervals each time t in part of is  t(L-t+1), where L is the length of the time series. However, I think that it's better to use the empirical number of intervals each point is part of, given that this information can be easily obtained.   For this, firstly, the empirical number of random intervals each point is included in is calculated and then the importance curves are divided by this value. 

This can easily be done by adding the fis_count lines in the feature_importances_ function (line 290) in sktime/sktime/series_as_features/base/estimators/_ensemble.py. The new function would be:

```python
def feature_importances_(self):
"""Compute feature importances for time series forest"""
# assumes particular structure of clf,
# with each tree consisting of a particular pipeline,
# as in modular tsf

if not isinstance(
  self.estimators_[0].steps[0][1], RandomIntervalFeatureExtractor
):
  raise NotImplementedError(
      "RandomIntervalFeatureExtractor must"
      " be used as the transformer,"
      " which must be the first step"
      " in the base estimator."
  )

# get series length, assuming same length series
tree = self.estimators_[0]
transformer = tree.steps[0][1]
time_index = transformer._time_index
n_timepoints = len(time_index)

# get feature names, features are the same for all trees
feature_names = [feature.__name__ for feature in transformer.features]
n_features = len(feature_names)

# get intervals from transformer,
# the number of intervals is the same for all trees

intervals = transformer.intervals_
n_intervals = len(intervals)

# get number of estimators
n_estimators = len(self.estimators_)

# preallocate array for feature importances
fis = np.zeros((n_timepoints, n_features))
<b>fis_count = np.zeros((n_timepoints, n_features))<b>

for i in range(n_estimators):
  # select tree
  tree = self.estimators_[i]
  transformer = tree.steps[0][1]
  classifier = tree.steps[-1][1]

  # get intervals from transformer
  intervals = transformer.intervals_

  # get feature importances from classifier
  fi = classifier.feature_importances_

  for k in range(n_features):
      for j in range(n_intervals):
          # get start and end point from interval
          start, end = intervals[j]

          # get time index for interval
          interval_time_points = np.arange(start, end)

          # get index for feature importances,
          # assuming particular order of features

          column_index = (k * n_intervals) + j

          fis_count[interval_time_points, k] += 1

          # add feature importance for all time points of interval
          fis[interval_time_points, k] += fi[column_index]

# normalise by number of estimators and number of intervals
fis = fis / n_estimators / n_intervals
fis_count =  fis_count / n_estimators / n_intervals

# format output
fis = pd.DataFrame(fis, columns=feature_names, index=time_index)
fis_count = pd.DataFrame(fis_count, columns=feature_names, index=time_index)
fis_norm = fis/fis_count

return fis_norm
```

An example of the empirical number (normalized by n_estimators and n_intervals) of intervals each point is included in for an instance of the CBF dataset is shown above: 

![intervasl](https://user-images.githubusercontent.com/46486474/107494752-73aac980-6b8f-11eb-9913-d9aec32a4500.png)

Finally, an example of the importance curve for the mean feature before and after the normalization for an instance of the CBF dataset is shown above: 

![importance_mean](https://user-images.githubusercontent.com/46486474/107494904-a5239500-6b8f-11eb-97f9-a8ec5c2d4747.png)

**Comment by fkiraly** [comment]
@aabanda, this sounds like an interesting and good idea.

However, what I'm wondering: is this not original research rather than just a simple improvement to an existing algorithm? In which case it might be appropriate to primarily write it up as a research paper, "correcting interval sampling bias in time series forest classifier importance curves" or sth like that?

Since if you just fix it in the code:
* the implementation might no longer be 1:1 congruent with the algorithm described in the paper (of which the class is supposed to be an "implementation mirror" i.m.o.)
* your (potentially great) idea would go unnoticed, unpublished, unreviewed

@TonyBagnall, what is your opinion?

**Comment by TonyBagnall** [comment]
hi amaia, this issue came up with our other interval classifiers, @MatthewMiddlehurst may remember the context? I think the feature importance stuff is his. I think having this as an option would be good, but perhaps discuss on slack first? I'm not on top of this code myself

**Comment by aabanda** [comment]
@fkiraly @TonyBagnall I agree, let's discuss it on slack

**Comment by Dbhasin1** [comment]
Is this issue available for taking up? I understand why curve normalization could be helpful to remove the unwanted bias. It will be my first time contributing, so some pointers before starting would be much appreciated!

**Comment by MatthewMiddlehurst** [comment]
I have something currently ready for this, just not made a PR as it accompanies a bunch of other stuff. 

Feel free to resolve this yourself, I would recommend adding it as an option to normalise or not rather than just replacing what is currently there.

**Comment by aabanda** [comment]
I agree with @MatthewMiddlehurst , feel free @Dbhasin1

**Comment by Dbhasin1** [comment]
Thanks, @MatthewMiddlehurst @aabanda
To ensure I am going in the right direction, the following are the points that need to be taken care of: 
• Add a bool parameter in the BaseTimeSeriesForest class in 
 sktime/sktime/series_as_features/base/estimators/_ensemble.py
• Initialise the fis_count dataframe and fill it with the number of empirical intervals for each point 
• If the bool parameter's True, return the fis_norm dataframe (as shown in the code snippet attached by @aabanda), else return the fis dataframe. 
Do let me know if I missed something.

**Comment by Aexousia** [comment]
Hello, I added an option for normalizing the importance curve if the user needs that given the objective and dataset that they might be working on based on what @aabanda, @TonyBagnall, and @MatthewMiddlehurst  suggested.
I also think that we could include more types of normalization as options if we are at it. Sometimes when the range of the time series dataset might be very large, the users might need normalization based on the maximal value among all the empirical counts. Additionally, we can also normalize based on the average or median. These choices could be provided in a separate variable 'normalise_type' that will take in the input once users set 'normalise_option' as 'True'. The default value could be empirical count as suggested by @aabanda but we could also add other options.
Please let me know what you think!

**Comment by MatthewMiddlehurst** [comment]
Included in the above PR.
