### ISSUE TITLE
[DOC] alpha value in forecasting notebook

### ISSUE THREAD

**Issue by aurelije** [alan-turing-institute/sktime#673]
#### Describe the issue linked to the documentation

Hello,
In https://github.com/alan-turing-institute/sktime/blob/master/examples/01_forecasting.ipynb on "In [43]:"  line 6 it is written:
`alpha=0.2,`
but from graph and previous input alpha is 0.05

#### Suggest a potential alternative/fix

Just set alpha to 0.05

**Comment by mustafaaydn** [comment]
Hi, that `alpha=0.2` is actually a plotting parameter for [`matplotlib.axes.Axes.fill_between`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.fill_between.html) that controls the transparency of the shaded area and is therefore different than the `alpha` used in the prediction interval terminology.

**Comment by mloning** [comment]
Yes, that's right @mustafaaydn, thanks for helping out. 

I'll close this for now, @aurelije, let me know if you want this to be reopened.
