### ISSUE TITLE
[BUG] Cannot make docs on Windows 10

### ISSUE THREAD

**Issue by luiszugasti** [alan-turing-institute/sktime#675]
**Describe the bug**
When attempting to build the documentation for `sktime`, `make` complains that it cannot find the ./symlink_examples.sh file.
Hence, Sphynx cannot create the docs on Windows 10.

**To Reproduce**
1. Navigate to the root directory of the project and instantiate a conda environment (`conda activate sktime`).
2. Enter in the command line: `make docs`.
3. View the [error](https://gist.github.com/luiszugasti/dfe5dab78c637255465bb22dd68f6b5f)

**Expected behavior**
Creation of the docs. I will add that this works fine in WSL2.

**Additional context**
Checked the contents of the "docs" folder and the `symlink_examples.sh` document is there. (This is from a fresh clone of the repository)
Unfortunately, I am unsure how Sphinx begins its search through the files.

**Versions**
<details>
System:
    python: 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 22:54:47) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Luis\anaconda3\envs\sktime\python.exe
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 49.6.0.post20210108
      sklearn: 0.23.2
       sktime: 0.5.3
  statsmodels: 0.12.2
        numpy: 1.20.1
        scipy: 1.6.0
       Cython: 0.29.17
       pandas: 1.1.5
   matplotlib: 3.3.4
       joblib: 1.0.1
        numba: 0.52.0
     pmdarima: 1.8.0
      tsfresh: 0.17.0
</details>

**Comment by mloning** [comment]
Thanks @luiszugasti for raising the issue! I don't have access to a Window machine, so I'd really appreciate it if you want to debug this! This might help: https://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified

**Comment by luiszugasti** [comment]
That SO answer is a little related, I find, because in that user's case, the command their system runs is "pscp". To be more specific, the make command is `pscp blob.txt username@hostname:/folder/`.

In my case, it's `bash C:\Users\Luis\Projects\sktime\docs\symlink_examples.sh`, where the command is "bash". But bash is Windows Subsystem!

I will have to look more into this.

**Comment by mloning** [comment]
I will close this for now, but feel free to reopen if you have more details on this.
