### ISSUE TITLE
[BUG] sktime Installation fails on Windows 10 due to OpenMP error

### ISSUE THREAD

**Issue by luiszugasti** [alan-turing-institute/sktime#677]
**Describe the bug**
When following the steps from https://www.sktime.org/en/latest/installation.html#windows, the installer complains that the folder /openmp is not accessible and quits.

Currently, I have 

**To Reproduce**

1. Follow steps one thru six of the attached documentation link.
2. Before running pip install --verbose, run `conda install fbprophet`. If  I don't do this, I get weird errors related to sklearn not being installed, although it is
3. Face the issue.

**Expected behavior**
Installation of sktime and allowing to run the tests. This works fine using WSL2 on the same machine.

**Additional context**
Disabling usage of openmp with the SKTIME_NO_OPENMP flag does allow the installation to take place, but when running tests, a whole slew of issues arise with numpy during test case collection.

**Versions**
<details>
System:
    python: 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 22:54:47) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Luis\anaconda3\envs\sktime2\python.exe
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 49.6.0.post20210108
      sklearn: 0.23.2
       sktime: 0.5.3
  statsmodels: 0.12.2
        numpy: 1.20.1
        scipy: 1.6.0
       Cython: 0.29.17
       pandas: 1.1.5
   matplotlib: 3.3.4
       joblib: 1.0.1
        numba: 0.52.0
     pmdarima: 1.8.0
      tsfresh: 0.17.0
</details>

**Comment by luiszugasti** [comment]
Here is the output from running `pip install --verbose --no-build-isolation --editable .` without disabling OpenMP, and after line 165, shows output of running the same command with OpenMP disabled.

**Comment by mloning** [comment]
The problem may be that fbprophet installs a different compiler. Try this: 
```
python setup.py build_ext --compiler=msvc
python setup.py bdist_wheel bdist_wininst
pip install --pre --no-index --no-deps --find-links dist/ sktime
```

**Comment by luiszugasti** [comment]
Thank you @mloning .

I tried the first command `python setup.py build_ext --compiler=msvc`
and this is the output: https://gist.github.com/luiszugasti/97344068b0420f8eca822f50b35b4569
It looks like there are some options missing from the compiler I set up thru Visual Code 2019 (as per the development installation instructions). Some of the warnings are set as errors.
I am not sure why this is, as I am running an AMD x86 CPU. 

I also tried to use mingw as a compiler but that failed, by an even larger margin.

I tried to push on with `python setup.py bdist_wheel bdist_wininst`:
https://gist.github.com/luiszugasti/68b84065dd8b3f5c76a368a7b4e6b7f7

Just a reminder, this is not a big blocker for me because I have this running perfectly fine on WSL2, and by usage of my own fork I can just push and pull from that working environment.

I am interested, however, if I could get this to work with a brand new install of Windows. Might use my computer as a guinea pig :)

**Comment by aiwalter** [comment]
@luiszugasti pls check #666 of how to install `fbprophet` on Windows, at least that is one way that works :)

**Comment by afzal442** [comment]
>This works fine using WSL2 on the same machine.

Hi @luiszugasti, as you told you are fine with the installation using WSL2, it will be great if you bring your steps here on how to install dev version of sktime on windows using WSL2. Do you find this command `pip install -e .` working fine here? Thanks.

**Comment by luiszugasti** [comment]
@afzal442 so what I did was I tried to re-install on WSL2 because I remember the process was pretty easy. To make a long story short **it turned out to be a little bit confusing**.

I want to test this out further to see if there's some form of regression between different python versions starting from python 3.5.

Here are the steps (along with a few observations I encountered). My requirements.txt can be found [here](https://gist.github.com/luiszugasti/22e355ce8f4bc8924a4212c8b00cbbe9).

Here goes:
0. Create an environment in python3.8 `mkvirtualenv "name_of_your_package" -p=python3.8`
1. install pre-commit with `pip install pre-commit`
2. checked out master (as per steps 1-4 of the [instructions](https://www.sktime.org/en/latest/installation.html#development-version))
3. `pip install cython` -> cython-0.29.22 (as per the reqs in the setup.py script)
4. I already have the compilers for linux. So, I install numpy, scipy and cython.
5. Go ahead to running `pip install --editable .`
6. Go ahead and install the build tools `pip install -r build_tools/requirements.txt`. It uninstalls cython, numpy, pandas, and scipy from the previous step, which is silly
7. Install docs too. `pip install -r docs/requirements.txt`
8. Run tests. If when running the tests you get an error from a Cython module complaining about size 88 being provided when 80 was expected, do the following:
    - take requirements.txt from my gist, install them with `pip install -r requirements.txt`
    - Then instal the editable environment again. This will remove any stale packages (I think).

All tests will then run fine and docs will be able to be built.

**Comment by mloning** [comment]
For more details go to https://github.com/alan-turing-institute/sktime/issues/666
