### ISSUE TITLE
How to handle missing values

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#69]
* transformers for distribution of missing values (see #6)
* adapting existing algorithms to internally handle missing values if possible
* add details about missing values in meta-data

**Comment by fkiraly** [comment]
just to add from discussion:

there could be two chains of transformers to do this, depending on whether missingness is 
(a) explicit (at time t, measured value NA) or (b) not (simply not measured, irregularly sampled)

(a) [by series] 1. apply binning (missing Y/N, "is na" logical), series-to-primitive 2. table/histogram, series-to-primitive (or series-to-bag)
(b) [by series] 1. get time points (series-to-sequence, "forget values), 2. first differences, 3. histogram/binning (or 5-num summary), series-to-primitive

**Comment by TonyBagnall** [comment]
I'm implementing a transformer to simply interpolate missing in the simplest case

**Comment by fkiraly** [comment]
I noticed this may be dangerous: while ok in the TSC/TSR case, in forecasters it may leak information "from the future". Perhaps let's add a boolean trait "temporal": if it's true, it doesn't leak information from the future.

**Comment by aiwalter** [comment]
solved by #637 . I think it can be closed then.

**Comment by mloning** [comment]
Thanks @aiwalter
