### ISSUE TITLE
TSC/TSR: implement pipeline building functionality with transformers on y

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#7]
xpandas provides functionality for fusing series-to-tabular transformers with tabular supervised learning methods.

This should be interfaced, or replicated in the more general interface.

In this interface, it should be possible to chain series-to-series transformers (e.g., truncation) with series-to-tabular transformers to obtain a series-to-tabular transformer, or series-to-series with series-to-tabular with a tabular SL method to obtain a TSC/TSR method.

Conditional on a consolidated interface design as in https://github.com/kiraly-group/sktime/issues/5 and https://github.com/kiraly-group/sktime/issues/6.

If easy interfacing is not possible, it may also require separate pipeline design, in this case please raise issue of pipeline API design.

**Comment by mloning** [comment]
Separate design/implementation of transformers on y into separate issues #44.
