### ISSUE TITLE
Sktime and MLJ Workshop @ The Alan Turing Institute

### ISSUE THREAD

**Issue by ysimillides** [alan-turing-institute/sktime#70]
This might interest you 

https://github.com/alan-turing-institute/MLJ.jl/wiki/2019-MLJ---sktime-tutorial-and-development-sprint

Applications are closing shortly

**Comment by fkiraly** [comment]
Dear all,

apologies as there seems to have been some org and communication blockage.
If you've applied and received no message (acceptance or rejection) on or before May 31, please let me know asap, fkiraly at turing.ac.uk 

Also please let me know if you've sent anything to julia at turing.ac.uk, and forward

Thanks, and apologies for any inconvenience
Franz

**Comment by mloning** [comment]
For more details, please see the relevant [wiki page](https://github.com/alan-turing-institute/sktime/wiki/2019-sktime-MLJ-tutorial-development-sprint).
