### ISSUE TITLE
Outlier detection

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#702]
**Is your feature request related to a problem? Please describe.**
I would like to detect outliers in time series data.

**Describe the solution you'd like**
I have seen the [Time Series Annotation](https://github.com/sktime/enhancement-proposals/blob/master/steps/06_time_series_annotation/step.md) enhancement proposal, however we actually could just have classes which inherit from `_SeriesToSeriesTransformer` and fill outliers with `np.nan` values. Then the outlier correction could happen by means of the `Imputer` I recently added.

I would like to add different outlier detection classes (maybe with a common parent class), which could be placed in `sktime.transformations.series.outlier`.

**Describe alternatives you've considered**
Implementing the annotation module from scratch, because for probabilistic outlier detection we would need to return an additional column (so a `pd.DataFrame`) with the probabilities for each time point. This could however be solved with above solution in having a `threshold` argument which takes a probability value to decide if a point is an outlier or not.

**Comment by fkiraly** [comment]
@aiwalter, this proposal is a bit of a hack - since it creates an implicit data container convention that is also ambiguous: sometimes `np.nan` are just NAs, sometimes they are outliers, and there's no way to distinguish.

However, if you only want outlier detection: why not start with a lean interface instead of covering all of annotation?

I think ensuring that it is multivariate from the start would be a good idea.

Apart from that, you can indeed make it similar to the transformer class. Though I would suggest not to replace values with `np.nan`, but instead return a series of events (the anomalies) or segments (anomalous periods) that is annotating the original series.

**Comment by fkiraly** [comment]
PS: packages that already have a related interface are `pyod` (tabular outlier detection), `ADTK` (anomaly detection in a temporal setting), `ruptures` (changepoint detection in a temporal setting).

You may want to consider:
* what the new interface would add above these
* whether to interface or use these directly
(make sure though that no copyleft/copyright dependencies are introduced)

**Comment by mloning** [comment]
I agree with the above points, to make outlier detectors usable in a forecasting pipeline, I'd suggest something like the following:

```python
detector = MyDetector(...)
transformation = ConditionalTransformer(Imputer, condition=detector, ...)
forecaster = MyForecaster(...)
pipeline = make_pipeline(transformer, forecaster)
pipeline.fit(...)
```
where `MyDetector` has a basic annotation interface with fit and predict and `ConditionalTransformer` is a series-to-series transformer. `Imputer` would take as input a list of values to be replaced, e.g. np.nan values by default, or a list of anomalies from the detector.

**Comment by fkiraly** [comment]
(agreed with @mloning - though I guess it should either be `Imputer()` or `imputer` following an `imputer = MyFancyImputer()`?)

**Comment by mloning** [comment]
Yes that's right, I've edited the comment above.

One thing that isn't clear to me is how to best "pass the list of outliers" from the detector to the imputer since the imputer only takes in a single series, there seems to be a missing step where the outliers are removed (converted to nan).

**Comment by fkiraly** [comment]
Hm, the "obvious" way would be a graphical composition formalism like in `ADTK` or `mlr` or `MLJ`.

A simpler way would be `RemoverTrafo(forecaster, remove=myoutlierdetector)`?

**Comment by aiwalter** [comment]
I would propose to start simple and I implement in a first step a transformer (e.g. a `HampelFilter`). I actually planned to wrap `adtk` or at least a part of it, however it seems the MPL-2.0 License is not compatible.

**Comment by fkiraly** [comment]
>however it seems the MPL-2.0 License is not compatible.

Correct! This is the major downside of `adtk`...
