### ISSUE TITLE
removing tqdm as a hard dependency

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#703]
We should remove `tqdm` as a hard dependency since it is partially copyleft, see here: https://github.com/tqdm/tqdm/blob/master/LICENCE

Why: packages with copyleft or copyright contents *or dependencies* cannot be used in some organisations (public research, corporate, public sector etc) due to license issues or regulation.

Depending on `tqdm` would change `sktime`'s status from permissive open source (incl hard dependencies) to copyleft.
This dependency may put `sktime` on license blacklists and break solutions using `sktime` in deployment.

The relevance of `tqdm` is really minimal and cosmetic, so it would be a minimal change in terms of functionality; it would however be a major change or problem (of not removed) in terms of license status.

**Comment by fkiraly** [comment]
@mloning, @TonyBagnall, please review/comment

**Comment by fkiraly** [comment]
apologies for not picking this up earlier. I believed it was MIT, but it is only *partially* MIT.

**Comment by TonyBagnall** [comment]
I'm all for reducing dependencies. I am not familiar with the package but it seems purely cosmetic and no great loss. I dont know where it is used though

**Comment by fkiraly** [comment]
I think it appears in the evaluation code by @aiwalter?

**Comment by aiwalter** [comment]
Ok I can remove it. Thx @fkiraly

**Comment by aiwalter** [comment]
solved with recent commit in #690
