### ISSUE TITLE
[DOC] User paths in tutorial notebooks (tool suggestion)

### ISSUE THREAD

**Issue by bdice** [alan-turing-institute/sktime#711]
#### Describe the issue linked to the documentation

I noticed there are some user paths in the tutorial notebooks. Example: https://www.sktime.org/en/latest/examples/feature_extraction_with_tsfresh.html

```python
/Users/mloning/Documents/Research/software/sktime/sktime/sktime/transformations/panel/tsfresh.py:164: UserWarning: tsfresh requires a unique index, but found non-unique. To avoid this warning, please make sure the index of X contains only unique values.
  "tsfresh requires a unique index, but found "
Feature Extraction: 100%|██████████| 5/5 [00:11<00:00,  2.32s/it]
```

#### Suggest a potential alternative/fix

I recently created a (very beta) tool that strips user paths from Jupyter notebook output cells. It can be used with a pre-commit hook. https://github.com/bdice/nb-strip-paths

Here is an example of the behavior:
```
# When executing from a repository "my_awesome_code", this text in a Jupyter cell output...
/home/bdice/my_awesome_code/some_directory/file.txt
# becomes...
some_directory/file.txt
```

Here is an example pre-commit hook configuration:
https://github.com/glotzerlab/signac-examples/blob/5478bb68517789fdd5b2831059059f062e46153a/.pre-commit-config.yaml#L51-L54

I don't have time to contribute a PR at the moment but I hope this is useful.

**Comment by aiwalter** [comment]
@bdice good idea! @mloning can I add it to the `pre-commit` yaml file?
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by mloning** [comment]
@bdice Thanks for reaching out, sounds like a great idea! What does "very beta" mean? How many other repos are using this already?

Happy to try it out if you want to implement it @aiwalter, but may have to remove it again if we run into bugs.

**Comment by bdice** [comment]
@mloning @aiwalter Good questions -- it's less than a month old. I made `nb-strip-paths` for [example notebooks](https://github.com/glotzerlab/signac-examples) for the [signac data management framework](https://signac.io/) but I think there are quite a few projects in the SciPy ecosystem with embedded notebooks that might find it handy. I'm using the hook with projects developed by my research lab but there aren't any other users yet.

`nb-strip-paths` is meant to be a very small package with a singular purpose, and I think it is stable enough to use in your pre-commit hooks (especially since pre-commit hooks are usually pinned to a tag).

To strip the user paths, you may need to re-render the notebooks locally so that the path to the repository matches _your_ path. For example, paths containing `/Users/mloning/.../sktime/abc` would not be stripped to `sktime/abc` if the current repository path is `/home/aiwalter/.../sktime/abc`. This is why it's helpful to have as a pre-commit hook, because it ensures that the user making a commit will strip their own paths from the outputs.

Thanks for the consideration, I'd be happy to hear your feedback!

**Comment by aiwalter** [comment]
@bdice I tried your package in  a separate test repo and produced two test cases which were however not detected. I created some error messages in a notebook and got two paths like...

1. `C:\Users\MYUSERID\bla\bla\bla\lib\site-packages\sktime\forecasting\compose\__init__.py`
2. `~\AppData\Local\bla\bla\bla\lib\site-packages\pandas\io\common.py`

In both cases I would ideally expect to strip the path, however after a commit nothing has been modified. Did I do sth wrong?
`nb-strip-paths...........................................................Passed`

**Comment by bdice** [comment]
@aiwalter Currently the only paths that are stripped are paths to the *repository* containing the notebooks. The user site packages directory is not stripped (since it is not a subdirectory of the repository containing the notebooks). I would be happy to add support for the two cases you’re mentioning — can you tell me what behavior you would expect in each case?

**Comment by aiwalter** [comment]
@bdice 
Is there actually in general a way to strip ANY occurrence of my USERID in a notebook (and even other files)? In cells as well as error messages?

Regarding my two examples, I would like to propose the following solutions. We could add additional argument to `nb-strip-paths` in order to...
1. strip any path but only keep the file name only? (most secure)
2. Strip any path before `site-packages` e.g.? (less secure)
3. Just strip any USERID occurances in a notebook

For me its actually very important not to expose my USERID as I am using my company PC :) So I would prefer solution 1 for `sktime`. Or 2 in combination with 3. What do you think?
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by bdice** [comment]
@aiwalter @mloning Sorry for the slow response, I didn't see your reply until now! I like your suggestions and have some follow-up questions before I work on the implementation.

> strip any path but only keep the file name only? (most secure)

This sounds prone to false positives but could be useful with some clarification. For example, strings like `2021/01/01` or `his/hers` or `alpha/beta/gamma` could be relative paths to a file. Similarly, regular expressions printed like `/abc/g` could appear to be absolute paths. This would also need to be a fairly high-priority rule (applied before the other rules that are more specific). Thus, I think you would want to detect _only_ absolute paths for potential stripping/truncation. You could also use something like `os.path.exists` to verify if it's really a path on the current system before stripping/truncating. What do you think of that?

> Strip any path before site-packages e.g.? (less secure)

I like this proposed rule! This is a narrower scope and thus easier to apply without worrying about false positives. Any path-like string that includes `site-packages` as a substring could have its prefix (the part before `site-packages`) replaced with an ellipsis. This would look like `.../site-packages/more/stuff.py`. That seems very safe and unlikely to cause problems for readers.

For consistency, we could also have an option to change the paths to be UNIX-like with forward slashes. That would make it more likely that the output of a notebook executed on Windows, Linux, or Mac would be the same.

> Just strip any USERID occurances in a notebook

In this case, would you expect that the output of the cell below would be _empty_ after stripping the username? Or would you suggest a replacement such as the literal string `$USER`?

```python
import getpass
print(getpass.getuser())
```

**Comment by aiwalter** [comment]
@bdice sry as well, I was off a few days. 
 

> 1. file-name-only (1 above)
> 2. strip-site-packages-prefix (2 above)
> 3. strip-repo-root-prefix (the current behavior)
> 4. strip-username (3 above)

This sounds very cool and would be nice to have all those four options as argument each and a short description, if possible. 

> In this case, would you expect that the output of the cell below would be empty after stripping the username? Or would you suggest a replacement such as the literal string $USER?

I would prefer replacement with `USER`

> You could also use something like os.path.exists to verify if it's really a path on the current system before stripping/truncating. What do you think of that?

That would be very smart and cool to have!

Let me know once you have this implemented, so I can test it again and then add it to `sktime` :)
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by bdice** [comment]
@aiwalter Cool! I appreciate your input. I’ll follow up when I have a chance to add these features.
