### ISSUE TITLE
provide pypi wheels for MacOS < 10.15

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#724]
**Is your feature request related to a problem? Please describe.**
MacOS wheels should be provided for actively maintained versiosn of MacOS <10.15, see
https://github.com/alan-turing-institute/sktime/discussions/723

**Describe the solution you'd like**
According to @hoesler who raised this:
"Well, I don't think that I am really able to contribute to your build and publishing process without access to the CI/CD environment. I might be wrong, but I think all you need to do is to set the mac os x runner to an earlier OS version."

**Comment by fkiraly** [comment]
@mloning FYI

**Comment by TonyBagnall** [comment]
hey @fkiraly and @mloning can we close this?

**Comment by fkiraly** [comment]
Not done, #748 is not merged - @hoseler4dh is either still working on this or has disengaged.

**Comment by mloning** [comment]
Closed for now due to inactivity. I'm happy to revisit the idea if this is still relevant.
