### ISSUE TITLE
[BUG] `pip3 install sktime` failed on MacOS Big Sur (Version 11.2.3) for Python 3.9

### ISSUE THREAD

**Issue by wangchen615** [alan-turing-institute/sktime#728]
**Describe the bug**

**To Reproduce**

```python
pip3 install sktime
```

**Expected behavior**

pip3 install sktime
Collecting sktime
  Using cached sktime-0.4.3.tar.gz (9.7 MB)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.9/site-packages (from sktime) (1.20.1)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.9/site-packages (from sktime) (1.2.0)
Requirement already satisfied: scikit-learn>=0.23.0 in /usr/local/lib/python3.9/site-packages (from sktime) (0.24.1)
Requirement already satisfied: statsmodels>=0.12.0 in /usr/local/lib/python3.9/site-packages (from sktime) (0.12.2)
Requirement already satisfied: wheel in /usr/local/lib/python3.9/site-packages (from sktime) (0.35.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/site-packages (from pandas>=1.0.0->sktime) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/site-packages (from pandas>=1.0.0->sktime) (2.8.1)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.9/site-packages (from scikit-learn>=0.23.0->sktime) (1.6.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/site-packages (from scikit-learn>=0.23.0->sktime) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.9/site-packages (from scikit-learn>=0.23.0->sktime) (1.0.1)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.9/site-packages (from statsmodels>=0.12.0->sktime) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas>=1.0.0->sktime) (1.15.0)
Building wheels for collected packages: sktime
  Building wheel for sktime (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py'"'"'; __file__='"'"'/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-wheel-igjscozh
       cwd: /private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/
  Complete output (45 lines):
  C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers

  compile options: '-c'
  extra options: '-fopenmp'
  clang: test_openmp.c
  clang: error: unsupported option '-fopenmp'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py", line 319, in <module>
      setup_package()
    File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py", line 315, in setup_package
      setup(**metadata)
    File "/usr/local/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py", line 210, in configuration
      config.add_subpackage("sktime")
    File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 1019, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 985, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 927, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "sktime/setup.py", line 28, in configuration
      maybe_cythonize_extensions(top_path, config)
    File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/sktime/_build_utils/__init__.py", line 42, in maybe_cythonize_extensions
      with_openmp = check_openmp_support()
    File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/sktime/_build_utils/openmp_helpers.py", line 145, in check_openmp_support
      raise CompileError(err_message)
  distutils.errors.CompileError:
                      ***
  It seems that sktime cannot be built with OpenMP support.

  - If your compiler supports OpenMP but the build still fails, please
    submit a bug report at:
    'https://github.com/alan-turing-institute/sktime/issues'

  - If you want to build sktime without OpenMP support, you can set
    the environment variable SKTIME_NO_OPENMP and rerun the build
    command. Note however that some estimators will run in sequential
    mode and their `n_jobs` parameter will have no effect anymore.

  - See sktime advanced installation instructions for more info:
    'https://https://www.sktime.org/en/latest/installation.html'
                      ***

  ----------------------------------------
  ERROR: Failed building wheel for sktime
  Running setup.py clean for sktime
Failed to build sktime
Installing collected packages: sktime
    Running setup.py install for sktime ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py'"'"'; __file__='"'"'/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-record-a5ji17kj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/sktime
         cwd: /private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/
    Complete output (45 lines):
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers

    compile options: '-c'
    extra options: '-fopenmp'
    clang: test_openmp.c
    clang: error: unsupported option '-fopenmp'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py", line 319, in <module>
        setup_package()
      File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py", line 315, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py", line 210, in configuration
        config.add_subpackage("sktime")
      File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 1019, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 985, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 927, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sktime/setup.py", line 28, in configuration
        maybe_cythonize_extensions(top_path, config)
      File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/sktime/_build_utils/__init__.py", line 42, in maybe_cythonize_extensions
        with_openmp = check_openmp_support()
      File "/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/sktime/_build_utils/openmp_helpers.py", line 145, in check_openmp_support
        raise CompileError(err_message)
    distutils.errors.CompileError:
                        ***
    It seems that sktime cannot be built with OpenMP support.

    - If your compiler supports OpenMP but the build still fails, please
      submit a bug report at:
      'https://github.com/alan-turing-institute/sktime/issues'

    - If you want to build sktime without OpenMP support, you can set
      the environment variable SKTIME_NO_OPENMP and rerun the build
      command. Note however that some estimators will run in sequential
      mode and their `n_jobs` parameter will have no effect anymore.

    - See sktime advanced installation instructions for more info:
      'https://https://www.sktime.org/en/latest/installation.html'
                        ***

    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py'"'"'; __file__='"'"'/private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-install-cms3wkh3/sktime/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2m/6d5jtcp5149cwbbxnm70m24m0000gn/T/pip-record-a5ji17kj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/sktime Check the logs for full command output.

**Additional context**

**Versions**
<details>

</details>

**Comment by mloning** [comment]
Hi @wangchen615 3.9, thanks for reporting the installation issue here! 

Unfortunately 3.9 is not officially supported yet, meaning we don't provide precompiled wheels for it, same for Big Sur. Any chance to use 3.8 and the previous macOS?

**Comment by freddyaboulton** [comment]
@mloning We're planning on using sktime in [evalml](https://github.com/alteryx/evalml) and are curious about the timeline of 3.9 support! Is this something you could use help with?

Thanks!

**Comment by mloning** [comment]
Hi @freddyaboulton, yes help would be much appreciated! It also depends on our dependencies, I'm not sure if they all support 3.9 yet. Adjusting the CI scripts described [here](https://github.com/alan-turing-institute/sktime/blob/79ac80ab65adb30fdf233e98433646c1989da2fc/CONTRIBUTING.md) in a PR would be a start to see if anything breaks in 3.9.

**Comment by wangchen615** [comment]
> Hi @wangchen615 3.9, thanks for reporting the installation issue here!
> 
> Unfortunately 3.9 is not officially supported yet, meaning we don't provide precompiled wheels for it, same for Big Sur. Any chance to use 3.8 and the previous macOS?

@mloning I see. Ok, yeah, my other code was using 3.9 now. It would be nice if you could support it in the future.

**Comment by mloning** [comment]
Closed in favour of https://github.com/alan-turing-institute/sktime/issues/664

**Comment by gogozhang** [comment]
Try gcc-11. I have installed on Big Sur for Python 3.9 successfully.
