### ISSUE TITLE
2021 Summer internships (GSoC & Outreachy)

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#731]
You can find out more about sktime's summer internships below: 

* Google Summer of Code: https://github.com/alan-turing-institute/sktime/wiki/GSoC-2021
* Outreachy: https://github.com/alan-turing-institute/sktime/wiki/Outreachy-2021

Please let us know if anything remains unclear.

**Comment by mloning** [comment]
A few tips on how to get started: 

1. Watch the [PyData online tutorial](https://www.youtube.com/watch?v=wqQKFu41FIw&t=14s) as an introduction, but note that some parts of the code base have evolved since then. 
1. Work through the [tutorials](https://github.com/alan-turing-institute/sktime/tree/main/examples). The tutorials should be self-explanatory. Is there anything that isn't clearly explained? Make notes on the parts that we could improve and post them in a discussion thread or issue on GitHub.
1. Read the [contributing guide](https://github.com/alan-turing-institute/sktime/blob/main/CONTRIBUTING.md). Again, make notes on the parts that we could improve.
1. Take a look at the online documentation at [sktime.org](http://sktime.org), especially the [API reference](https://www.sktime.org/en/latest/api_reference.html). If you find incomplete or missing docstrings, please open a pull request to fix them.

**Comment by mertbozkir** [comment]
@mloning I didn't know sktime and I didn't make a proposal for here. 

But if I haven't GSoC internship, I would contribute here, even I am not chosen. I loved this environment and framework.💖

**Comment by fkiraly** [comment]
unfortunately, application deadlines have passed now but ... well ... there's always next year :-)

**Comment by fkiraly** [comment]
And this: https://www.sktime.org/en/latest/mentoring.html

**Comment by mertbozkir** [comment]
@fkiraly I know that have passed. I can contribute if anybody won't chooses me in GSoC.  I can contribute from here github. without mentor.

Woaww if there is a mentorship program. It makes me excited.  

What is the mentorship program deadline?  😍

**Comment by mloning** [comment]
Hi @mertbozkir, we accept people on a rolling basis depending on mentor availability! There will also be an onboarding event in mid May - we'll announce details soon.

**Comment by TonyBagnall** [comment]
@mloning can I close this, since the program has started

**Comment by fkiraly** [comment]
yes, and applications have since closed. I´ve renamed the issue for better reference, this can obviously be closed.
