### ISSUE TITLE
Tuning implicite hyperparameter of tranformers inside TransformedTargetForecaster

### ISSUE THREAD

**Issue by aiwalter** [alan-turing-institute/sktime#747]
**Is your feature request related to a problem? Please describe.**
I have locally created a class `TuningTransformer` inspired by this `TabularToSeriesAdaptor` in order to tune the implicite hyperparameter of using a tranformers or not inside `TransformedTargetForecaster` in order to tune this all together in a `ForecastingGridSearchCV`. Therefore, the class `TuningTransformer` has an arg `use: bool` to turn on and off the use of a tranformer.

**Describe the solution you'd like**
All together looks as follows:
```python
TuningTransformer(BoxCoxTransformer(method="pearsonr"))
```
Or more complicated with `TabularToSeriesAdaptor`:
```python
TuningTransformer(TabularToSeriesAdaptor(MinMaxScaler()))
```
So in the end I will put each tranformer inside a `TuningTransformer` and all together with GS looks like this:
```python
pipe = TransformedTargetForecaster(steps=[
    ("deseasonalise", TuningTransformer(transformer=Deseasonalizer())),
    ("minmax", TuningTransformer(transformer=TabularToSeriesAdaptor(MinMaxScaler()))),
    ("power", TuningTransformer(transformer=TabularToSeriesAdaptor(PowerTransformer()))),
    ("model", TBATS()),
    ]
)

cv = SlidingWindowSplitter(initial_window=int(len(y_train) * 0.5), window_length=24, start_with_window=True, step_length=24)
param_grid = {
    "deseasonalise__transformer__model" : ["multiplicative", "additive"],
    "deseasonalise__transformer__sp" : [12],
    "deseasonalise__use" : [True, False],

    "power__transformer__transformer__method" : ["yeo-johnson", "box-cox"],
    "power__transformer__transformer__standardize" : [True, False],
    "power__use" : [True, False],

    "minmax__transformer__transformer__copy": [(0,1), (0,2)],
    "minmax__use" : [True, False],

    'model__sp': [12],
}
gscv = ForecastingGridSearchCV(forecaster=pipe, param_grid=param_grid, cv=cv, n_jobs=-1)
gscv.fit(y)

```
It can look a bit confusing to have grid arguments like `minmax__transformer__transformer__copy`, however this is all consistent with existing stuff in `sktime` and `sklearn`. And it is very handy for tuning :)

**Additional context**
I might contribute this to `sktime` in case it is appreciated, otherwise I dont mind to keep it in our private repo. I am open to adjust my implementations in case there are other ideas how to solve the implicit hyperparameter tuning in this case. Maybe the class can have a better name..
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by fkiraly** [comment]
Quick question, @aiwalter, what does this do?
Does it simply default to the identity transform if `sthsth_use=False`?

Seems like a really good idea to me!

The name though seems sub-optimal, because you would expect a `TuningTransformer` to tune (which it doesn't).
How about `Optional`, or `OptionalTunable` or similar?

PS: beware overfitting by overtuning...

**Comment by mloning** [comment]
@aiwalter isn't this already possible with scikit-learn pipelines? 

From https://scikit-learn.org/stable/modules/compose.html:
> Individual steps may also be replaced as parameters, and non-final steps may be ignored by setting them to 'passthrough':

Not sure if our pipeline currently handles this, but if we want to add this, we should add handle it like scikit-learn I think. 

FYI there is also a [BoxCoxTransformer](https://github.com/alan-turing-institute/sktime/blob/bcce82cbabff00878d5347225d5679c8d30cf239/sktime/transformations/series/boxcox.py#L175) in sktime which allows you to set bounds on lambda, similar to [forecast library in R](https://www.rdocumentation.org/packages/forecast/versions/8.14/topics/BoxCox.lambda).

**Comment by aiwalter** [comment]
@mloning that sounds like what I actually want to do, however I could not find how to use `passthrough` exactly and in the `TransformedTargetForecaster` for example, did you get that? Unfortunately there is very rare doc about it.

@fkiraly So `TuningTransformer` seems to do what `passthrough` from `sklearn` is meant for. If I get `TransformedTargetForecaster` running with `passthrough`, we probably wont need to have this transformer.
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by fkiraly** [comment]
>@fkiraly So TuningTransformer seems to do what passthrough from sklearn is meant for. If I get TransformedTargetForecaster running with passthrough, we probably wont need to have this transformer.

I think your proposal is preferrable, in terms of functionality, usability and design:
* I don't think the `passthrough` formalism works the way your functionality is intended.
This is because in `sklearn`'s interface, you have to replace the *estimator* with the string `passthrough`, so it appears as a component in the list, not as a directly indexable hyper-parameter that you can use in grid search, as far as I understand? At least, it seems to be substantially more complicated to set up the desired grid.
(assuming I understand correctly how it's used in `sklearn`
* the `sklearn` design attached the "optionality" parameter to the pipeline, while you are attaching it to the component. The latter is more general, since it allows for the parameter in any compositor/reducer, rather than just in the pipeline. Implementing "passthrough" in every compositor/reducer is most definitely the more cumbersome and duplicative choice, compared to having a single wrapper.

**Comment by fkiraly** [comment]
PS: I think I now know what you should call the component: `OptionalPassthrough`?

**Comment by aiwalter** [comment]
@fkiraly @mloning ok, so let me open a PR in the next days/weeks. I basically already have all the code locally :) Any ideas where to place such a class? Maybe in `sktime.transformations.series.adapt` or we make a new file `sktime.transformations.series.tune`?

> PS: I think I now know what you should call the component: `OptionalPassthrough`?

Yeah could be sth like this
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by mloning** [comment]
Perhaps we should make a new file `sktime.transformations.series.compose.py`?

**Comment by fkiraly** [comment]
stupid question: is this actually not an instance of the multiplexer, with a "canonical alternative" being the identity transformer?

Might be worth having the `OptionalPassthrough` as a shorthand, but that would imply that it should perhaps be wherever the multiplexer is, and it should perhaps even be a contraction of the multiplexer?

**Comment by aiwalter** [comment]
@fkiraly not sure if I understood this. I think generally `MultiplexForecaster` is about finding the best forecaster whereas OptionalPassthrough will be used to find the best combination of multiple transformers together with a forecaster inside a `TransformedTargetForecaster`. 

Maybe it helps to show what I am doing in model tuning all together. I am using the following steps and components:

1. different multiple forecasters (number = `n_forecasters`)
2. multiple transformers (number = `n_transformers`)
3. For 1 and 2 I create a `TransformedTargetForecaster` for each forecaster in `n_forecasters` together with all n_transformers. In future I will use `OptionalPassthrough` for each transformer. So in the end I will get `n_transformedtargetforecasters`
4. Then I create a `ForecastingGridSearchCV` for each element in `n_transformedtargetforecasters `and append it to a list of grid searches called `n_gridsearches`
5. Then I take the list `n_gridsearches` and give it to `MultiplexForecaster`
6. This multiplexer is now finally given to another `ForecastingGridSearchCV` and I train it to get the overall best hyperparameters and implicite hyperparameters.

Its a bit a nested approach, but works well so far. So this also describes a bit the relationship of `MultiplexForecaster` and the new class `OptionalPassthrough` hopefully. 
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by fkiraly** [comment]
>@fkiraly not sure if I understood this. I think generally MultiplexForecaster is about finding the best forecaster whereas OptionalPassthrough will be used to find the best combination of multiple transformers together with a forecaster inside a TransformedTargetForecaster.

Ok, let me explain:
`OptionalPassthrough(foo)` is the following instance of a hypothetical `MultiplexSeriesTransformer`:
`MultiplexSeriesTransformer(['foo' = foo(), 'id' = IdentitySeriesTransformer())`, with the `selected_transformer` in `MultiplexSeriesTransformer` corresponding to `passthrough` of `OptionalPassthrough` (`'foo'` vs `'id'` corresponds to `True` vs `False`)

**Comment by aiwalter** [comment]
@fkiraly 

> OptionalPassthrough(foo()) is the following instance of a hypothetical MultiplexSeriesTransformer:
MultiplexSeriesTransformer(['foo' = foo(), 'id' = IdentitySeriesTransformer()]), with the hyper-parameter selected_transformer in MultiplexSeriesTransformer corresponding to the hyper-parameter passthrough of OptionalPassthrough ('foo' vs 'id' corresponds to True vs False)

but `selected_transformer` would just allow to select one transformer out of n tranformers, right? So equivalent to `MultiplexForecaster` is selecting one forecaster out of n?
Because, that is not the behavior I have in mind as I would like to find all possible combinations of mulitple hyperparameters of transformers (including implicit hyperparameter of using it or not)

I would say lets start simple with a `OptionalPassthrough` transformer, as I am not yet sure what the benefit of a higher level `MultiplexSeriesTransformer` class would be?

**Comment by fkiraly** [comment]
@aiwalter, I think we're not entirely on one page here.

All I'm saying ist hat your `OptionalPassthrough` *can be expressed as an instance* of a transformer-multiplexer. Not that you should implement the multiplexer instead.
That it can be expressed as an instance indicates it should live in the same "category" of composers, design-wise and scitype-wise.

Also, to get the equivalent behaviour inside a pipeline, you would have to use multiple transformer-multiplexers on the inside, not just one on the outside.

@mloning, not sure whether I'm making sense?

**Comment by mloning** [comment]
@fkiraly I understand your point! Makes sense to me conceptually. Regarding implementation, it's probably a good idea to have an `OptionalPassthrough` transformer.

**Comment by fkiraly** [comment]
>Regarding implementation, it's probably a good idea to have an `OptionalPassthrough` transformer.

Agreed, seem y point above:

>Might be worth having the `OptionalPassthrough` as a shorthand, but that would imply that it should perhaps be wherever the multiplexer is, and it should perhaps even be a contraction of the multiplexer?

**Comment by aiwalter** [comment]
done by #762
