### ISSUE TITLE
[BUG] import MUSE error

### ISSUE THREAD

**Issue by jachane99** [alan-turing-institute/sktime#755]
**Describe the bug**
Import issue for MUSE package

**To Reproduce**
`from sktime.classification.dictionary_based import MUSE`

**Expected behavior**

This import shouldn't cause any issue

**Additional context**

   from sktime.classification.dictionary_based import MUSE
ImportError: cannot import name 'MUSE' from 'sktime.classification.dictionary_based' (C:\UserPath\site-packages\sktime\classification\dictionary_based\__init__.py)

**Versions**
sktime version sktime==0.4.2

<details>

**Comment by mloning** [comment]
Looks like MUSE was added in `0.4.3`, please update your sktime version.
