### ISSUE TITLE
[BUG] Installation fails:  Soft dependencies and Jupyter Notebook

### ISSUE THREAD

**Issue by ngallo1** [alan-turing-institute/sktime#758]
I installed sktime and tried to run the 'Forecasting' code segment from the Welcome page (https://www.sktime.org/en/latest/).
When I put the code in a `test.py` file and run it from the terminal (`python test.py`) it outputs the correct value.  However, when I run the same code from a Jupyter notebook I get a "ModuleNotFoundError: No module named 'pmdarima'. 'pmdarima' is a soft dependency and not included in the sktime installation. Please run: `pip install pmdarima`. To install all soft dependencies, run: `pip install sktime[all_extras]"

I ran both `pip install pmdarima`  and `conda install -c conda-forge pmdarima`  (I had to use conda install to install sktime initially).  Neither worked.  I keep getting the same error.  I restarted my computer and tried again.  That didn't work either.
(I am using Windows 10 if that matters.)
_________________________________________________________________________

• Code I ran:
```
from sktime.forecasting.all import *

y = load_airline()
y_train, y_test = temporal_train_test_split(y)
fh = ForecastingHorizon(y_test.index, is_relative=False)
forecaster = ThetaForecaster(sp=12)  # monthly seasonal periodicity
forecaster.fit(y_train)
y_pred = forecaster.predict(fh)
smape_loss(y_test, y_pred)
```

• Error message from Jupyter notebook:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\anaconda3\lib\site-packages\sktime\utils\validation\_dependencies.py in _check_soft_dependencies(*packages)
     22         try:
---> 23             import_module(package)
     24         except ModuleNotFoundError as e:

~\anaconda3\lib\importlib\__init__.py in import_module(name, package)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 

~\anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'pmdarima'

The above exception was the direct cause of the following exception:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-cd3271f835dd> in <module>
----> 1 from sktime.forecasting.all import *
      2 
      3 y = load_airline()
      4 y_train, y_test = temporal_train_test_split(y)
      5 fh = ForecastingHorizon(y_test.index, is_relative=False)

~\anaconda3\lib\site-packages\sktime\forecasting\all\__init__.py in <module>
     44 from sktime.datasets import load_lynx
     45 from sktime.datasets import load_shampoo_sales
---> 46 from sktime.forecasting.arima import AutoARIMA
     47 from sktime.forecasting.base import ForecastingHorizon
     48 from sktime.forecasting.compose import EnsembleForecaster

~\anaconda3\lib\site-packages\sktime\forecasting\arima.py in <module>
      9 from sktime.utils.validation._dependencies import _check_soft_dependencies
     10 
---> 11 _check_soft_dependencies("pmdarima")
     12 
     13 

~\anaconda3\lib\site-packages\sktime\utils\validation\_dependencies.py in _check_soft_dependencies(*packages)
     29                 f"sktime[all_extras]`"
     30             )
---> 31             raise ModuleNotFoundError(msg) from e

ModuleNotFoundError: No module named 'pmdarima'. 'pmdarima' is a soft dependency and not included in the sktime installation. Please run: `pip install pmdarima`. To install all soft dependencies, run: `pip install sktime[all_extras]`

**Comment by mloning** [comment]
@ngallo1 thanks for reporting the issue. Can you check you run the Jupyter notebook from the same environment where you installed `pmdarima`?

**Comment by mloning** [comment]
I've updated the README to avoid the installation of soft dependencies.
