### ISSUE TITLE
Implement Guerrero method for Box-Cox lambda estimation 

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#778]
**Is your feature request related to a problem? Please describe.**
Add Guerrero method for lambda estimation to [BoxCoxTransformer](https://github.com/alan-turing-institute/sktime/blob/main/sktime/transformations/series/boxcox.py).

**Describe the solution you'd like**
You can find an example here: https://otexts.com/fpp3/transformations.html
R code from forecast is available here: https://github.com/robjhyndman/forecast/blob/master/R/guerrero.R

**Comment by yashlamba** [comment]
I would like to work on this!

**Comment by mloning** [comment]
Hi @yashlamba, I think @GuzalBulatova already wanted to work on this. 

I posted some more ideas on how to identify useful issues here: https://github.com/alan-turing-institute/sktime/issues/778
