### ISSUE TITLE
Implement STL forecaster

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#782]
**Is your feature request related to a problem? Please describe.**
STL forecasting seems a common composite forecaster, so it will be useful to provide a class for it. 

There is a [STLForecaster](https://www.statsmodels.org/v0.12.0/generated/statsmodels.tsa.forecasting.stl.STLForecast.html#statsmodels.tsa.forecasting.stl.STLForecast) in statsmodels.

**Describe the solution you'd like**
It should be a composite forecaster consisting of a TransformedTargetPipeline which accepts any other forecaster and applies the forecaster to deseasonalized and detrended data.  

```python
forecaster = STLForecaster(MyForecaster(...), ...)
```

This should be equivalent to this pipeline:
```python
forecaster = TransformedTargetForecaster(
    [
        ("deseasonalise", Deseasonalizer(...)),
        ("detrend", Detrender(forecaster=PolynomialTrendForecaster(degree=1))),
        ("forecast", MyForecaster(...)),
    ]
)
```

**Comment by fkiraly** [comment]
Interesting!

There is an obvious "easy" way to do this - but...

I was wondering, is it possible in python to create a contraction operation that is class-level, i.e., a factory operation that uses class inspection and manipulation? Sth that allows

```python
class STLForecaster = EstimatorContract(forecaster, 
        fixed_params = {'detrend__degree' : 1},
        mapped_params = {'foo' : 'bar'}
    )
```

**Comment by smriti111** [comment]
Can I work on this issue, if it hasn't been taken up by anyone.

**Comment by mloning** [comment]
@smriti111 yes no-one is working on this as far as I'm aware. Creating a draft PR as soon as possible is usually a good idea to let others know you've started working on this and to get early feedback.

**Comment by smriti111** [comment]
Sure am working on it, will update soon

**Comment by thayeylolu** [comment]
Hello @smriti111 . Have you started working on this ?

**Comment by thayeylolu** [comment]
Hello @mloning . @smriti111 has not responded and I would like to go ahead with a draft

**Comment by mloning** [comment]
Great @thayeylolu - feel free to go ahead!

**Comment by thayeylolu** [comment]
I am on it

**Comment by thayeylolu** [comment]
> **Is your feature request related to a problem? Please describe.**
> STL forecasting seems a common composite forecaster, so it will be useful to provide a class for it.
> 
> There is a [STLForecaster](https://www.statsmodels.org/v0.12.0/generated/statsmodels.tsa.forecasting.stl.STLForecast.html#statsmodels.tsa.forecasting.stl.STLForecast) in statsmodels.
> 
> **Describe the solution you'd like**
> It should be a composite forecaster consisting of a TransformedTargetPipeline which accepts any other forecaster and applies the forecaster to deseasonalized and detrended data.
> 
> ```python
> forecaster = STLForecaster(MyForecaster(...), ...)
> ```
> 
> This should be equivalent to this pipeline:
> 
> ```python
> forecaster = TransformedTargetForecaster(
>     [
>         ("deseasonalise", Deseasonalizer(...)),
>         ("detrend", Detrender(forecaster=PolynomialTrendForecaster(degree=1))),
>         ("forecast", MyForecaster(...)),
>     ]
> )
> ```

I think my first version of the implementation is a bit different from this. 
```python
 forecaster = STLForecaster(MyForecaster(...), steps)
 ```
where steps is 
```python
forecaster = TransformedTargetForecaster(
   [
    ("deseasonalise", Deseasonalizer(...)),
    ("detrend", Detrender(forecaster=PolynomialTrendForecaster(degree=1)))]
```

without the forecaster

**Comment by thayeylolu** [comment]
Hello @fkiraly . Here is what

```python 
STLForecaster =(forecaster = {'estimator' : 'forecast'}, fixed_params = {'detrend_degree' : 1, 'seasonal periodicity':1}
    )
```

**Comment by fkiraly** [comment]
Great!

I would just make a minor modification: remove the dictionary brackets from this, they just seem to complicate the interface?
There's also the "equal" sign but I think that's just an unintended type.

That is, I would suggest
```python
STLForecaster(forecaster, detrend_degree=1, sp=1)
```
to be a shorthand for 

```python
TransformedTargetForecaster(
    [
        ("deseasonalise", Deseasonalizer(sp=1)),
        ("detrend", Detrender(forecaster=PolynomialTrendForecaster(degree=1))),
        ("forecast", forecaster),
    ]
)
```

**Comment by thayeylolu** [comment]
I have made the modification. Thank you @fkiraly

**Comment by thayeylolu** [comment]
I created a separate test file containing specific tests in the `test_all_forecasters.py` that failed for the STLForecaster. I decided to check these check if these failed for the `TransformedTargetForecaster` but they all passed. The test still fails for the `STLForecaster`. This is the specific error message  I get `` .

**Comment by fkiraly** [comment]
which test is failing?

**Comment by thayeylolu** [comment]
Hello @fkiraly  `test_update_predict_predicted_index_update_params( Forecaster, fh, window_length, step_length, update_params)` this test. Its is the last test in `test_all_forecasters.py`

**Comment by fkiraly** [comment]
can you kindly update your PR from dev and make sure your code (that produces the error) is identical with the code in the PR?

**Comment by thayeylolu** [comment]
Ah! Yes @fkiraly . https://github.com/alan-turing-institute/sktime/pull/933

**Comment by thayeylolu** [comment]
I have updated my PR.

**Comment by thayeylolu** [comment]
Hello @mloning.
-  @fkiraly and I investigated why the test (`test_update_predict_predicted_index_update_params`- this is present in `sktime.forecasting.tests.test_all_forecasters.py`) failed for the STLForecaster.
- The stlforecaster has/uses/calls a step (which is the parameter of the `TransformedTargetForecaster` ) in it's constructor
- We created an instance of the Transformed target forecaster. (**See below - exhibit A**) and ran the test on the instance. This test failed and raised the following error (**See below- exhibit B**).
- We believe that there is a bug in the TransformedTargetForecaster. We would appreciate it if you help us understand why. We also noticed that you are the author of the `_pipeline.py` where the `TransformedTargetforecaster` is created.

**Exhibit A**
```
python

ttf = TransformedTargetForecaster(
    [
        ("deseasonalize", Deseasonalizer(model="multiplicative", sp=12)),
        ("detrend", Detrender(forecaster=PolynomialTrendForecaster(degree=1))),
("forecaster", NaiveForecaster())
    ]
)

ttf.fit(y_train, fh=fh)
```


**Exhibit B**

`ValueError: `index` must contain at least some values, but found empty index: DatetimeIndex([], dtype='datetime64[ns]', freq='D'). `

<img width="947" alt="image" src="https://user-images.githubusercontent.com/13348874/122019343-9528f580-cdbb-11eb-8961-db784ea9d0b9.png">

**Comment by fkiraly** [comment]
Indeed - as a supplementary note, we ran a modified version of `test_update_predict_predicted_index_update_params` on the instantiated `ttf`, which takes an object, not a class (i.e., where the "instantiation step" in the test is removed)

**Comment by aiwalter** [comment]
@RNKuhns when I use the new `STLTransformer`, I get only residuals of 0. I did 
```python
stl = STLTransformer(sp=12, trend=13, seasonal=13)
y_hat = stl.fit_transform(y)
resid = y - stl.seasonal_ - y_hat
```
Or did I miss sth in params to get another residual values?

**Comment by aiwalter** [comment]
also not so sure about the example given in the docstring of `STLTransformer` of how to build an "STLForecaster": 
```python
    stlforecaster = TransformedTargetForecaster([
        ("deseasonalize", STLTransformer(sp=12),
        ("forecast", PolynomialTrendForecaster(degree=1))]
    )
    stlforecaster.fit(y)
```
this is quite different to what you propose @RNKuhns I think. But for me your proposal makes more sense.
