### ISSUE TITLE
[BUG] cannot import name 'MultiplexForecaster' from 'sktime.forecasting.compose'

### ISSUE THREAD

**Issue by krinkere** [alan-turing-institute/sktime#786]
**Describe the bug**
While trying to run example notebook that uses MultiplexForecaster given an error message that it is not present in forecasting/compose/__init__.py

**To Reproduce**
Install via pip (pip install sktime) or conda (conda install -c conda-forge sktime)
Run imports from example notebooks
https://github.com/alan-turing-institute/sktime/blob/main/examples/01_forecasting.ipynb

Given error
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8864e845d085> in <module>
      7 from sktime.forecasting.arima import ARIMA, AutoARIMA
      8 from sktime.forecasting.base import ForecastingHorizon
----> 9 from sktime.forecasting.compose import (
     10     EnsembleForecaster,
     11     MultiplexForecaster,

ImportError: cannot import name 'MultiplexForecaster' from 'sktime.forecasting.compose' (/lib/python3.7/site-packages/sktime/forecasting/compose/__init__.py)

Contents of the file
```python
#!/usr/bin/env python3 -u
# -*- coding: utf-8 -*-
# copyright: sktime developers, BSD-3-Clause License (see LICENSE file)

__author__ = ["Markus Löning"]

__all__ = [
    "EnsembleForecaster",
    "TransformedTargetForecaster",
    "DirectRegressionForecaster",
    "DirectTimeSeriesRegressionForecaster",
    "RecursiveRegressionForecaster",
    "RecursiveTimeSeriesRegressionForecaster",
    "ReducedForecaster",
    "StackingForecaster",
]

from sktime.forecasting.compose._ensemble import EnsembleForecaster
from sktime.forecasting.compose._pipeline import TransformedTargetForecaster
from sktime.forecasting.compose._reduce import DirectRegressionForecaster
from sktime.forecasting.compose._reduce import DirectTimeSeriesRegressionForecaster
from sktime.forecasting.compose._reduce import RecursiveRegressionForecaster
from sktime.forecasting.compose._reduce import RecursiveTimeSeriesRegressionForecaster
from sktime.forecasting.compose._reduce import ReducedForecaster
from sktime.forecasting.compose._stack import StackingForecaster
```

**Versions**
<details>

System:
    python: 3.7.10 (default, Feb 26 2021, 18:47:35)  [GCC 7.3.0]
executable: /bin/python
   machine: Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-redhat-7.9-Maipo

Python dependencies:
          pip: 21.0.1
   setuptools: 52.0.0.post20210125
      sklearn: 0.24.1
       sktime: 0.5.3
  statsmodels: 0.12.2
        numpy: 1.20.2
        scipy: 1.6.2
       Cython: 0.29.17
       pandas: 1.2.3
   matplotlib: None
       joblib: 1.0.1
        numba: 0.52.0
     pmdarima: 1.8.0
      tsfresh: None

</details>

**Comment by aiwalter** [comment]
Hi @krinkere ,

this example is from the main branch, which is ahead of PyPI version of sktime. `MultiplexForecaster` is a new class which is not yet on PyPI.
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md
