### ISSUE TITLE
Add support for fractions for window length parameters

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#795]
**Is your feature request related to a problem? Please describe.**
Currently, window length parameters (e.g. `window_length` or `initial_window` in `SlidingWindowSplitter`) have to be integers and denote the absolute number of time points, similar to how scikit-learn handles fractions in their cross-validation functionality. 

**Describe the solution you'd like**
Add support for floats denoting the number of time points relative to the passed data. For example passing `window_length=0.5` would mean half of the data `y` passed to `split` in the `SlidingWindowSplitter`.

The parameters `window_length` and `initial_window` are used in several locations in the code base.

**Comment by thayeylolu** [comment]
I would like o ask if `window_length` and `initial_window` mean the same thing.

**Comment by mloning** [comment]
@thayeylolu If you search for these names in the entire code base, you will see that they are used in different classes. The docstrings should give you more details on their meaning. 

For the temporal cross-validation splitters, you can see what these parameters mean in this notebook: https://github.com/alan-turing-institute/sktime/blob/main/examples/window_splitters.ipynb

**Comment by thayeylolu** [comment]
Thank you @mloning for sharing. I would look at the example notebook to understand them better.

**Comment by Ifeanyi30** [comment]
Hi @mloning, so if the window_length=0.5 returns half of the y data, then the range of the float window_length would have to range from 0.0 to 1.0

**Comment by mloning** [comment]
@Ifeanyi30 yes that's correct, anything above 1 would have to be an integer denoting the absolute number of time points in the window, e.g. `window_length=10` means 10 timepoints regardless of the length of `y`

**Comment by Ifeanyi30** [comment]
I would like to work on this

**Comment by mloning** [comment]
@thayeylolu are you already working on this?

**Comment by thayeylolu** [comment]
@Ifeanyi30 Thank you for showing interest in this. @mloning  I have started working on it

**Comment by mloning** [comment]
@thayeylolu great! Opening a draft PR is usually a good first step to indicate that you're working on it and to receive early feedback. @Ifeanyi30 perhaps you'd be interested in reviewing once the PR is up?

**Comment by Ifeanyi30** [comment]
I would love to

**Comment by mloning** [comment]
Closed by #827
