### ISSUE TITLE
Implement PyOD transformer adapter

### ISSUE THREAD

**Issue by satya-pattnaik** [alan-turing-institute/sktime#798]
**Is your feature request related to a problem? Please describe.**
A sktime Series Transformer which wraps a ADTK Pipeline for outlier detection. 

**Describe the solution you'd like**
This [notebook](https://github.com/satya-pattnaik/sktime-mentorship-program/blob/main/anomaly_detection/sktime_adtk.ipynb) has an initial approach

**Additional context**
https://arundo-adtk.readthedocs-hosted.com/en/stable/

**Comment by fkiraly** [comment]
Unfortunately, ADTK is not permissive open source, so we can't make it a dependency.
I'm also not sure how well it is supported still.

Though, if you want outlier detection, I suggest `pyod`:
https://github.com/yzhao062/pyod

So, we could wrap the `pyod` interface (for i.i.d./tabular data) for use with temporal scenarios via reduction?

**Comment by satya-pattnaik** [comment]
This looks to be a good one, it has got some techniques specific for time series - https://github.com/SeldonIO/alibi-detect

**Comment by fkiraly** [comment]
yes, indeed! Thanks for making us aware of this. @mloning FYI, also good to have on the related work page?

They do not seem to have a pipeline structure though - so it might be a good idea to construct:
* a seldon interface, with a cleaner API design for scitype handling (e.g., time series input or tabular input? annotators and detectors)
* some functionality similar to sklearn `Pipeline` or ADTK `PipeNet`; on that note, I believe @viktorkaz wanted to build something similar to that

**Comment by mloning** [comment]
@satya-pattnaik looks interesting, please add to `docs/source/related_software.rst`

**Comment by ViktorKaz** [comment]
For the last several weeks I've been working on a design of a pipeline which can also be used for outlier detection. You can find the preliminary code [here](https://github.com/ViktorKaz/sktime/tree/pipeline/sktime/pipeline). This is related to Issue https://github.com/alan-turing-institute/sktime/issues/763.

**Comment by fkiraly** [comment]
so... how do we proceed with this?
There are multiple non-exclusive options I can see:
* interface to `pyod`
* interface to `alibi-detect`
* extend @ViktorKaz's pipeline design to cover generic temporal on-line anomaly detection

**Comment by satya-pattnaik** [comment]
I am already on it. I am developing the interface to PyOD, I had a call with @mloning  to get the design sketch(which I will update as an enhancement proposal ).

**Comment by RNKuhns** [comment]
@satya-pattnaik and @mloning this was completed, right?

**Comment by satya-pattnaik** [comment]
Yes @RNKuhns .

**Comment by mloning** [comment]
Closed by #1021
