### ISSUE TITLE
Import make_reduction error

### ISSUE THREAD

**Issue by JonDickens1607** [alan-turing-institute/sktime#803]
ImportError: cannot import name 'make_reduction' from 'sktime.forecasting.compose' (C:\ProgramData\Anaconda3\lib\site-packages\sktime\forecasting\compose\__init__.py)

**Comment by aiwalter** [comment]
same as #804 
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md
