### ISSUE TITLE
Model Evaluation Module Error

### ISSUE THREAD

**Issue by JonDickens1607** [alan-turing-institute/sktime#804]
from sktime.forecasting.model_evaluation import evaluate

No module named 'sktime.forecasting.model_evaluation'

**Comment by aiwalter** [comment]
@JonDickens1607 there is an issue template, pls use next time. This is a new function from master branch and not yet in PyPI.
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md
