### ISSUE TITLE
[BUG] binder notebook environment build breaks over scikit-posthocs unable to load pyqt5 in setup.py

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#807]
**Describe the bug**

When running the sktime binder, the environment setup breaks over scikit-posthocs unable to load pyqt5 in setup.py.
This is reproducible using multiple browsers and computers (all running Windows).

Have not investigated what causes the issue, but it´s possibly an incomplete requirements file somewhere in the dependency graph.

See printout here.

![image](https://user-images.githubusercontent.com/7985502/114570341-a8a9ca00-9c6d-11eb-88bc-c417a2e6e027.png)

![image](https://user-images.githubusercontent.com/7985502/114570453-beb78a80-9c6d-11eb-96f4-c0c057da1ea3.png)

**To Reproduce**

1. Go to sktime binder
2. watch the "starting prompt"

**Expected behavior**

no error occurs, binder loads as expected

**Comment by mloning** [comment]
Binder is still broken #662 - partly due to complications with fbprophet/pystan I believe

**Comment by fkiraly** [comment]
the error I getting seems like a different one though, @mloning?
