### ISSUE TITLE
[BUG] problematic language statistics shown in the homepage

### ISSUE THREAD

**Issue by xuyxu** [alan-turing-institute/sktime#809]
Hi, I have noticed that `.ts` files in the folder `datasets` are tracked by Github Linguist, which is not the case in the past.

As a result, the language statistics shown in the homepage are somehow mis-leading. Maybe we should add `jquery.js -linguist-vendored` as a new line in `.gitattributes`, according to this [markdown file](https://github.com/github/linguist/blob/master/docs/overrides.md#vendored-code).

**Comment by mloning** [comment]
Thanks @xuyxu - would appreciate a PR. 

We should probably also except the docs folder, so the new `.gitattributes` files should look like this if I understand the documentation correctly:
```
docs/* linguist-documentation
sktime/datasets/data/* linguist-vendored
jquery.js -linguist-vendored
```

**Comment by xuyxu** [comment]
Sure, will work on this soon ;-)
