### ISSUE TITLE
MiniRocket as an Option for ROCKETClassifier

### ISSUE THREAD

**Issue by angus924** [alan-turing-institute/sktime#813]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
I thought I'd ask first, before submitting a PR—@MatthewMiddlehurst because it's your code, @kachayev and @RavenRudi because you are working on related PRs—would it be helpful to add [MiniRocket](https://github.com/alan-turing-institute/sktime/blob/main/sktime/transformations/panel/rocket/_minirocket.py) as an option for ROCKETClassifier?

If so, I'd suggest making MiniRocket the default, because it's so much faster than Rocket, but this is only a suggestion.

**Describe alternatives you've considered**
Alternatively, of course, we could have a separate MINIROCKETClassifier.  This would essentially just duplicate all the ROCKETClassifier code, but perhaps it would be clearer to do it this way.

**Additional context**
NA

**Comment by kachayev** [comment]
I think it would make sense to have optional `transformation` parameter for `ROCKETClassifier` class that could be set to one of the following: `Rocket`, `MiniRocket` or `MiniRocketMultivariate`. Though I would keep  `Rocket` default for backwards compatibility.

**Comment by RavenRudi** [comment]
Hi,

I agree with @kachayev. That is probably the best option. What I did in my PR, is refactoring duplicate code of the `ROCKETClassifier` and `ROCKETRegressor` into `series_as_features/base/estimators/shapelet_based/_rocket_estimator.py`. That's were the `transformation` parameter could be added.

**Comment by MatthewMiddlehurst** [comment]
Having it as a parameter would be best. No opinion on the best default value.

**Comment by mloning** [comment]
I think it would be nice to develop a more unified interface for using Rocket/MiniRocket at the level of the RocketClassifier/RocketRegressor. Adding a `transformation` or `method` argument seems fine, with possible values being "minirocket" or "rocket". I would not add `MiniRocketMultivariate". I prefer multivariate data being handled automatically when given in fit/predict without requiring users to set hyper-parameters. If multivariate data is not supported, we should raise an error.

**Comment by angus924** [comment]
Thanks very much everyone.

**Comment by TonyBagnall** [comment]
hi, just bumping this, does this still need doing? If so, I may find someone to do so, but dont want to duplicate what others have done.

**Comment by MatthewMiddlehurst** [comment]
Related to #1095.

**Comment by TonyBagnall** [comment]
closing this issue, direct it to #1095
