### ISSUE TITLE
[BUG] Custom scorer gives you an error when fitting a ForecastingGridSearchCV object 

### ISSUE THREAD

**Issue by angelmoti24** [alan-turing-institute/sktime#826]
**Describe the bug**

When running a ForecastingGridSearchCV with exogenous variables with a scoring created with MetricFunctionWrapper, gives you an error.

**To Reproduce**

```python
from sktime.performance_metrics.forecasting import mase_loss,sMAPE
from sktime.performance_metrics.forecasting._classes import MetricFunctionWrapper
metric = MetricFunctionWrapper(sMAPE)
cv = SlidingWindowSplitter(initial_window=int(len(yt) * 0.5))
gscv = ForecastingGridSearchCV(forecaster, cv=cv, param_grid=regressor_param_grid,scoring=metric)
gscv.fit(y=yt,X=xt)
```

**Expected behavior**

The forecaster should be scored with the custom metric but instead it gives you an error.
**Additional context**
The error that gives you is the following:
TypeError: __init__() takes 1 positional argument but 3 were given

**Versions**
0.6.0

System:
    python: 3.8.2 (default, Dec 21 2020, 15:06:04)  [Clang 12.0.0 (clang-1200.0.32.29)]
executable: /Library/Developer/CommandLineTools/usr/bin/python3
   machine: macOS-11.2.3-x86_64-i386-64bit

Python dependencies:
          pip: 21.0.1
   setuptools: 41.2.0
      sklearn: 0.24.1
       sktime: 0.6.0
  statsmodels: 0.12.2
        numpy: 1.19.5
        scipy: 1.6.1
       Cython: 0.29.17
       pandas: 1.2.3
   matplotlib: 3.3.4
       joblib: 1.0.1
        numba: 0.53.0
     pmdarima: 1.8.0
      tsfresh: None

**Comment by mloning** [comment]
Hi @angelmoti24 - `MetricFunctionWrapper` takes a function, not a class. This works for me:
```python
from sktime.performance_metrics.forecasting import smape_loss
from sktime.performance_metrics.forecasting._classes import MetricFunctionWrapper
from sktime.forecasting.model_selection import SlidingWindowSplitter, ForecastingGridSearchCV
from sktime.datasets import load_longley
from sktime.forecasting.naive import NaiveForecaster

y, X = load_longley()
param_grid = {"strategy": ["last", "mean"]}
forecaster = NaiveForecaster()
scoring = MetricFunctionWrapper(smape_loss)
cv = SlidingWindowSplitter(initial_window=10, window_length=3)
gscv = ForecastingGridSearchCV(forecaster, cv=cv, param_grid=param_grid, scoring=scoring)
gscv.fit(y=y, X=X)
```

**Comment by angelmoti24** [comment]
you are right, thank you!!

**Comment by mloning** [comment]
@angelmoti24 it's also part of the private API, perhaps we should highlight the `make_forecasting_scorer` function
