### ISSUE TITLE
Add a small multivariate dataset to the baked-in dataset loading set

### ISSUE THREAD

**Issue by James-Large** [alan-turing-institute/sktime#83]
**Is your feature request related to a problem? Please describe.**
Similar to gunpoint, italypowerdemand, and a couple others, could a method to load in a basic/small multivariate TSC dataset be added to sktime.datasets.base and .data for the purposes of quick testing without additional downloads, as requested by a couple of people, @ABostrom 

I notice that BasicMotions is in .data, but only the train split as an arff, and without the simplified/wrapped load_basic_motions() method in .base

**Describe the solution you'd like**
To upload/add the .ts versions of e.g. BasicMotions (or a smaller dataset, if one exists) and add the wrapped load method

Simple fix, but easier for someone on a clean or the master fork

**Comment by TonyBagnall** [comment]
good idea. To extend this, we should have

**Comment by mloning** [comment]
Added a the multivariate BasicMotions dataset already on `dev` as requested, see d302c26044785e4495b1d800c77da68920e8fca3.
