### ISSUE TITLE
-inf AIC/BIC in AutoETS

### ISSUE THREAD

**Issue by ltsaprounis** [alan-turing-institute/sktime#847]
**Is your feature request related to a problem? Please describe.**
Some ETS models from the [statsmodels.tsa.exponential_smoothing.ets.ETSModel](https://www.statsmodels.org/stable/generated/statsmodels.tsa.exponential_smoothing.ets.ETSModel.html) can yield an infinite likelihood. As a result, information criteria like AIC, AICc and BIC will be negative infinity. The AutoETS implementation is picking the model that minimises the chosen information criterion, therefore, in the above case it would choose the infinite likelihood model. For the time series I was playing with this results in many obscure forecasts with a mean MAPE (across splits) of 168%.

**Describe the solution you'd like**
Simply ignoring models with -inf Information Criteria is an effective solution to the problem.
For my time-series, applying this fix causes a reduction in mean MAPE (across splits) from 168% to 13%

**pre vs post -inf IC fix**
![image](https://user-images.githubusercontent.com/64217214/116484582-4661e380-a881-11eb-80e2-e9505772682c.png)  ![image](https://user-images.githubusercontent.com/64217214/116484595-4bbf2e00-a881-11eb-9959-2dd9f78c722a.png)

**Comment by mloning** [comment]
Thanks @ltsaprounis 

FYI @HYang1996
