### ISSUE TITLE
[DOC] Exponential Smoothing not an issue just advice.

### ISSUE THREAD

**Issue by mertbozkir** [alan-turing-institute/sktime#852]
Hello folks, 
I wanted to use the Exponential Smoothing sktime class. But when I opened sktime documentation, I realize there is a wrong syntax. I look twice, three times, etc. Then I tried to find an example on the internet I understand what is the problem.

 Here is [Exponential Smoothing Documentation](https://www.sktime.org/en/stable/api_reference/modules/auto_generated/sktime.forecasting.exp_smoothing.ExponentialSmoothing.html?highlight=Exponential%20Smoothing)

![image](https://user-images.githubusercontent.com/63906053/116784106-0413ee80-aa9b-11eb-89f2-84ca8a8e8f11.png)

**When you look at this image you can assume there is a blank between Exponential and Smoothing word.**

It's not an issue but if you change this example section, people can understand easily.

**Comment by mertbozkir** [comment]
I also want to help those who know Exponential Smooth(Somebody advice me of this model)
**I am just a newbie in this field**
I have a dataset as a form of pd.DataFrame, you can see below here.

### I have some questions.
* Which models would fit my short-time series?
* Where to learn model? 
* If Exp Smooth fits my problem, how can I solve it with Exp Smooth? (Which parameters I should focus on?)
* Any advice, I would be grateful :)


## TRAIN
![image](https://user-images.githubusercontent.com/63906053/116784261-f27f1680-aa9b-11eb-87d2-6da609213371.png)


## TEST
![image](https://user-images.githubusercontent.com/63906053/116784265-f743ca80-aa9b-11eb-960e-ef04d63a2cf4.png)

**Comment by mloning** [comment]
Thanks @mertbozkir for raising the issue. I don't see the blank space when I go here: https://www.sktime.org/en/stable/api_reference/modules/auto_generated/sktime.forecasting.exp_smoothing.ExponentialSmoothing.html#sktime.forecasting.exp_smoothing.ExponentialSmoothing

**Comment by mertbozkir** [comment]
**It's my pleasure** 🦸‍♂️, 
Do you have an answer to my questions?

**Comment by mloning** [comment]
For an intro to forecasting, take a look at this book: https://otexts.com/fpp3/
