### ISSUE TITLE
MASE for evaluate function

### ISSUE THREAD

**Issue by RavenRudi** [alan-turing-institute/sktime#857]
**Is your feature request related to a problem? Please describe.**
The `sktime.forecasting.model_evaluation.evaluate` function does not work with the MASE.

**Describe the solution you'd like**
Provide the MASE() object as the `scoring` parameter. 

**Additional context**
The current problem is that `evaluate` only accepts metrics that calculate a score from `y_test` and `y_pred`. The MASE however also needs `y_train`. As `y_train` is available within `evaluate` this shouldn't take too much time.

**Comment by fkiraly** [comment]
@RNKuhns, did we miss something?
I was under the impression that this would already work, given earlier suggestion to allow metrics that don't use `y_train` to still accept it as an ignored argument.

Or, is it coming from the internals of `evaluate`, which would be code of @aiwalter?

**Comment by mloning** [comment]
Thanks @RavenRudi for raising the issue! 

We've already discussed a solution to it here: #712 - so hopefully that will be on `main` soon, there are a few other changes related to the performance metrics on `main` already.

**Comment by fkiraly** [comment]
ah, was under the false impression this was already addressed!

**Comment by mloning** [comment]
This is now fixed by #858
