### ISSUE TITLE
[BUG] TimeSeriesForestClassifier.predict_proba() returns 1-dim array upon single instance input

### ISSUE THREAD

**Issue by LoadingByte** [alan-turing-institute/sktime#86]
**Describe the bug**

When you feed a single instance into `TimeSeriesForestClassifier.predict_proba()`, i.e., a DataFrame with the following structure:

&nbsp; | dim_0
-|-
**0** | x1, x2, x3, x4, ...

...a 1-dimensional array is returned, i.e., an array with the following structure:

`[p1, p2, p3, ...]`

Every other sklearn classifier that I'm aware of, as well as the elastic ensemble classifier from sktime, would return a 2-dimensional array in this case, thus matching the array structure of multi-instance predictions:

`[[p1, p2, p3, ...]]`

Therefore, TimeSeriesForestClassifier presents unexpected behavior, which also contradicts the documentation of `predict_proba()`:

>Returns
>p : array of shape = [n_samples, n_classes] [...]

The unexpected behavior is most likely caused by a seemingly deliberate conversion statement at the end of `predict_proba()`:

```python
if len(all_proba) == 1:
    return all_proba[0]
else:
    return all_proba
```

Note that this unexpected behavior presumably also confuses `TimeSeriesForestClassifier.predict()` when inputting single instances, since that leads to an exception hinting at `predict()` tripping over the unusual 1-dimensional return format:

```
---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
<ipython-input-56-a8b067ca3dcd> in <module>
----> 1 clf.predict(X_test.iloc[0:1, :])

~/.conda/envs/py3/lib/python3.7/site-packages/sklearn/utils/metaestimators.py in <lambda>(*args, **kwargs)
    114 
    115         # lambda, but not partial, allows help() to work with update_wrapper
--> 116         out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
    117         # update the docstring of the returned function
    118         update_wrapper(out, self.fn)

~/.conda/envs/py3/lib/python3.7/site-packages/sklearn/pipeline.py in predict(self, X, **predict_params)
    420         for _, name, transform in self._iter(with_final=False):
    421             Xt = transform.transform(Xt)
--> 422         return self.steps[-1][-1].predict(Xt, **predict_params)
    423 
    424     @if_delegate_has_method(delegate='_final_estimator')

~/.conda/envs/py3/lib/python3.7/site-packages/sklearn/ensemble/forest.py in predict(self, X)
    546 
    547         if self.n_outputs_ == 1:
--> 548             return self.classes_.take(np.argmax(proba, axis=1), axis=0)
    549 
    550         else:

~/.conda/envs/py3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in argmax(a, axis, out)
   1101 
   1102     """
-> 1103     return _wrapfunc(a, 'argmax', axis=axis, out=out)
   1104 
   1105 

~/.conda/envs/py3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     54 def _wrapfunc(obj, method, *args, **kwds):
     55     try:
---> 56         return getattr(obj, method)(*args, **kwds)
     57 
     58     # An AttributeError occurs if the object does not have

AxisError: axis 1 is out of bounds for array of dimension 1
```

**To Reproduce**

```python
from sktime.utils.load_data import load_from_ucr_tsv_to_dataframe
from sktime.classifiers.ensemble import TimeSeriesForestClassifier

X_train, y_train = load_from_ucr_tsv_to_dataframe("GunPoint_TRAIN.tsv")

clf = TimeSeriesForestClassifier()
clf.fit(X_train, y_train)

print(clf.predict_proba(X_train.iloc[[0], :]))  # leads to unusual return format
print(clf.predict(X_train.iloc[[0], :]))        # leads to exception
```

**Expected behavior**

`TimeSeriesForestClassifier.predict_proba()` should **always** return a 2-dimensional array, even on single-instance inputs, just as the documentation states. Moreover, `TimeSeriesForestClassifier.predict()` should not fail on single-instance inputs, which can likely be resolved by fixing the `predict_proba()` bug.

**Versions**

<details>
Linux-4.19.49-1-MANJARO-x86_64-with-arch-Manjaro-Linux
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
NumPy 1.16.4
SciPy 1.2.1
sktime 0.2.0
</details>

**Comment by TonyBagnall** [comment]
hi, thanks for this, I've assigned Markus as it is his code

**Comment by mloning** [comment]
Yes, that looks like a bug indeed - thanks for raising the issue! I will look into this.

**Comment by LoadingByte** [comment]
@mloning Thanks for the invitation! I'm quite short on time at the moment, but if I come across something I'd share or write code that could fit the project, I'll let you know.
