### ISSUE TITLE
[BUG] Unable to install pmdarima via Conda

### ISSUE THREAD

**Issue by ParthivNaresh** [alan-turing-institute/sktime#860]
**Describe the bug**
As `pmdarima` is a soft dependency, and is necessary for `AutoARIMA`, I am currently trying to install `pmdarima` via the conda route alongside `sktime`. Unfortunately, I'm unable to install `pmdarima` AND `sktime` via conda channels for a feedstock as it results in package conflicts.

**To Reproduce**
`conda install pmdarima`
`conda install sktime`

Essentially trying to install both `pmdarima` and `sktime` via conda results in conflicts.

**Expected behavior**
There shouldn't be any conflicts or the appropriate packages should be installed/upgraded/downgraded.

**Versions**
`numpy >= 1.19.1`
`pandas >= 1.1.0`
`scikit-learn >= 0.23.1`

System:
python: 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:19)  [Clang 9.0.0 (tags/RELEASE_900/final)]
executable: /Users/parthiv.naresh/miniconda3/envs/main/bin/python
machine: macOS-10.15.7-x86_64-i386-64bit

Python dependencies:
pip: 21.1.1
setuptools: 49.6.0.post20210108
sklearn: 0.24.2
sktime: 0.6.0
statsmodels: 0.12.2
numpy: 1.19.5
scipy: 1.6.3
Cython: 0.29.17
pandas: 1.2.4
matplotlib: 3.4.1
joblib: 1.0.1
numba: 0.52.0
pmdarima: 1.8.0
tsfresh: None

**Comment by mloning** [comment]
@ParthivNaresh wasn't aware of this, but I can reproduce the package conflict. Would you like to look into it and see which requirements we have to adjust to avoid the conflict?

**Comment by ParthivNaresh** [comment]
@mloning From what I understand, `pmdarima` requires `statsmodels` to be `>=0.11,<0.12`, while `sktime` requires `statsmodels` to be `>=0.12.1`. I haven't been able to find any combination of requirements so far that can fix it. Even installing `sktime` and `pmdarima` (in either order) without pinning versions results in this error. As far as I can see, there's no way to install them both via conda due to conflicting dependencies.

**Comment by mloning** [comment]
Okay that's not great - does it work with pip? I have them both in my environment but don't remember how I installed them. 

From [here](https://github.com/alkaline-ml/pmdarima/blob/master/requirements.txt) it seems as if only `statsmodels` `0.12.0` is excluded.

**Comment by ParthivNaresh** [comment]
The feedstock is [built differently](https://github.com/conda-forge/pmdarima-feedstock/blob/master/recipe/meta.yaml).

It does works with pip, however that prevents it from being included in the feedstock recipe.

**Comment by mloning** [comment]
@ParthivNaresh Ah I see, in that case, it's perhaps easiest to raise an issue with pmdarima to update their feedstock or am I missing something?

**Comment by mloning** [comment]
Thanks @ParthivNaresh for raising the issue here https://github.com/alkaline-ml/pmdarima/issues/429

**Comment by mloning** [comment]
@ParthivNaresh I believe the issue has been resolved in alkaline-ml/pmdarima#429, I'll close this one here now, but please let me know if the issue persists. Thanks for pushing this!
