### ISSUE TITLE
[BUG] ImportError: cannot import name 'MeanAbsolutePercentageError'

### ISSUE THREAD

**Issue by jiryang** [alan-turing-institute/sktime#862]
Hi, 

Following your forecasting tutorial (https://github.com/alan-turing-institute/sktime/blob/main/examples/01_forecasting.ipynb) gives me the import error. Could you please help?

Python: 3.6.9
sktime: 0.6.0

**Comment by mloning** [comment]
The tutorial notebook is based on the `main` branch, which is ahead of the latest release. Please check out the corresponding files for the latest stable release here: https://github.com/alan-turing-institute/sktime/tree/v0.6.0

**Comment by jlfischer** [comment]
This is actually still a problem. 

![image](https://user-images.githubusercontent.com/6618220/165137457-92d64c36-a704-4afd-bf11-74c16e96f348.png)

**Comment by fkiraly** [comment]
@jlfischer, could you kindly post your sktime version and operating system?

For me, the import works fine, i.e., 
`from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError`

**Comment by jlfischer** [comment]
sktime: 0.5.0
python: 3.6.8
OS: Linux (Linux-3.10.0-1160.53.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo)

**Comment by aiwalter** [comment]
@jlfischer we now have 0.11.2 version. Pls try to update 😃
