### ISSUE TITLE
The 2021 sktime summer programme

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#863]
We invite sktime community members, new joiners, and interested data scientists to participate in the 2021 summer programme, held virtually.

The summer programme consists of events and activities which can be joined separately:

| Event | Date | Short description
|---|---|---|
| [sktime onboarding days](https://github.com/sktime/community-council/blob/main/events/sktime-onboarding-days.md) | May 19-21 |  3 days of workshops, tutorials and a sprint for new joiners and people interested in contributing |
| [sktime dev days](https://github.com/sktime/community-council/blob/main/events/sktime-dev-days.md) | June 21-25 | 5 days of workshops, tutorials and a sprint | 
| [Meet-ups](https://github.com/sktime/community-council/blob/main/events/meet-ups.md) | May 20, June 22, August 20 (tbc) | Social activities, informal discussions   | 
| [Internships & mentoring](https://github.com/sktime/mentoring#readme) | May-Aug | Internship and mentoring activities within the sktime community | 
| [SciPy 2021](https://www.scipy2021.scipy.org) sprint | July 18 | sktime sprint at the SciPy 2021 conference | 
| [sktime doc sprint](https://github.com/sktime/community-council/blob/main/events/doc-sprint.md) | Aug 16-19 | 4-day documentation sprint | 
| [Summer project presentation](https://github.com/sktime/community-council/blob/main/events/project-presentation.md) | Aug 20 | Presentation and celebration of community projects and intern projects |

**Comment by thePworeo** [comment]
Hello,
in context of my semester thesis i try to use sktime for time series classification. Unfortunately i have missed the onboarding days. Would it be possible to get the documents used for tutorials and similar?

**Comment by fkiraly** [comment]
sure, material from past workshops is here: https://github.com/sktime/sktime-workshop

For the introduction, I´d recommend to watch our youtube video: https://www.youtube.com/watch?v=wqQKFu41FIw

**Comment by thePworeo** [comment]
> sure, material from past workshops is here: https://github.com/sktime/sktime-workshop
> 
> For the introduction, I´d recommend to watch our youtube video: https://www.youtube.com/watch?v=wqQKFu41FIw

Thank you very much, I am sorry to answer that late.
Unfortunately the link to the workshop materials does not work, github raises an 404 error.
I already watched the youtube video, but I was looking for some deeper information. I am especially interested in time series classification since i am currently working on my semester thesis about condition monitoring of machine tools through analysing different kinds of data.
It would be very kind of you could offer me further information. I already did some experimental work with sktime and really liked using it. But with the tutorials and documentation given it is pretty hard work.

Best regards

**Comment by fkiraly** [comment]
>Unfortunately the link to the workshop materials does not work, github raises an 404 error

Oh, very sorry - I must have cut off the last letter when I copy-pasted. Please try again.

>But with the tutorials and documentation given it is pretty hard work.

We'd appreciate any feedback on how to improve tutorials and documentation - what would you like to see, what makes it hard?

We know that it's grown a bit organically and is currently not as nice as it could be. Improving documentation and tutorials will be one of the larger topics at the summer dev days.

In case you would like to contribute yourself to improving these - having users like yourself in mind - you would be more than welcome!

**Comment by thePworeo** [comment]
Ah perfect, now the link works!
I'll work through the tutorials and workshops the next days. I will be happy to give you feedback after that as well!
My main problem are the documentation and little number of examples, but i also admit not to be a professional concerning machine learning algorithms.
Probably I will spend at least the next 3-4 weeks working with sktime and I will be happy to share my experiences and suggestions for improvement.
Probably I'll come around with some more questions anyway.
