### ISSUE TITLE
[BUG] cannot import name 'mean_absolute_percentage_error' from 'sktime.performance_metrics.forecasting'

### ISSUE THREAD

**Issue by blenderben2** [alan-turing-institute/sktime#865]
**Describe the bug**

> cannot import name 'mean_absolute_percentage_error' from 'sktime.performance_metrics.forecasting' (/home/doe/miniconda3/envs/sktime_env/lib/python3.7/site-packages/sktime/performance_metrics/forecasting/__init__.py)

**To Reproduce**
```
from sktime.performance_metrics.forecasting import mean_absolute_percentage_error
```

**Expected behavior**

**Additional context**

**Versions**
sktime: 0.6.0

</details>

**Comment by mloning** [comment]
Hi @blenderben2 - thanks for opening the issue. Please see #862
