### ISSUE TITLE
ExponentialSmoothing results in error for a series with w-sun freq

### ISSUE THREAD

**Issue by eyalshafran** [alan-turing-institute/sktime#866]
I'm using sktime 0.6.0

If I use the following code:

```
forecaster = ExponentialSmoothing()
date = pd.date_range(start='01/07/2018',end='05/09/2021',freq='W')
value = np.random.normal(size=175)
ts = pd.Series(value, index=date)
forecaster.fit(ts)
forecaster.predict(fh=np.arange(1,10))
```

I get the error below. If I replace the forecaster with something else (e.g. NaiveForecaster) I do not get an error.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
pandas/_libs/tslibs/timedeltas.pyx in pandas._libs.tslibs.timedeltas.parse_timedelta_unit()

KeyError: 'w-sun'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/opt/anaconda3/lib/python3.8/site-packages/sktime/utils/datetime.py in _coerce_duration_to_int(duration, freq)
     43             if isinstance(duration, pd.TimedeltaIndex):
---> 44                 return (duration / pd.Timedelta(1, freq)).astype(np.int)
     45         except ValueError:

pandas/_libs/tslibs/timedeltas.pyx in pandas._libs.tslibs.timedeltas.Timedelta.__new__()

pandas/_libs/tslibs/timedeltas.pyx in pandas._libs.tslibs.timedeltas.parse_timedelta_unit()

ValueError: invalid unit abbreviation: W-SUN

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-594-c72ddc4c380b> in <module>
      4 ts = pd.Series(value,index=date)
      5 forecaster.fit(ts)
----> 6 forecaster.predict(fh=np.arange(1,10))

/opt/anaconda3/lib/python3.8/site-packages/sktime/forecasting/base/_sktime.py in predict(self, fh, X, return_pred_int, alpha)
    226         self.check_is_fitted()
    227         self._set_fh(fh)
--> 228         return self._predict(self.fh, X, return_pred_int=return_pred_int, alpha=alpha)
    229 
    230     def compute_pred_int(self, y_pred, alpha=DEFAULT_ALPHA):

/opt/anaconda3/lib/python3.8/site-packages/sktime/forecasting/base/adapters/_statsmodels.py in _predict(self, fh, X, return_pred_int, alpha)
     78         # statsmodels requires zero-based indexing starting at the
     79         # beginning of the training series when passing integers
---> 80         start, end = fh.to_absolute_int(self._y.index[0], self.cutoff)[[0, -1]]
     81         y_pred = self._fitted_forecaster.predict(start, end)
     82 

/opt/anaconda3/lib/python3.8/site-packages/sktime/forecasting/base/_fh.py in to_absolute_int(self, start, cutoff)
    322 
    323         if isinstance(absolute, (pd.PeriodIndex, pd.DatetimeIndex)):
--> 324             integers = _coerce_duration_to_int(integers, freq=_get_freq(cutoff))
    325 
    326         return self._new(integers, is_relative=False)

/opt/anaconda3/lib/python3.8/site-packages/sktime/utils/datetime.py in _coerce_duration_to_int(duration, freq)
     44                 return (duration / pd.Timedelta(1, freq)).astype(np.int)
     45         except ValueError:
---> 46             raise ValueError(
     47                 "Index type not supported. Please consider using pd.PeriodIndex."
     48             )

ValueError: Index type not supported. Please consider using pd.PeriodIndex.

**Comment by mloning** [comment]
Thanks, this is also related to #868 I believe. 

But have you tried using a `pd.PeriodIndex` as suggested in the error message? This works for me:
```python
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
import pandas as pd
import numpy as np

forecaster = ExponentialSmoothing()
date = pd.period_range(start='01/07/2018',end='05/09/2021',freq='W')
value = np.random.normal(size=175)
ts = pd.Series(value, index=date)
forecaster.fit(ts)
forecaster.predict(fh=np.arange(1,10))
```

**Comment by fkiraly** [comment]
Indeed!
