### ISSUE TITLE
[BUG] can't import performance metrics

### ISSUE THREAD

**Issue by eyalshafran** [alan-turing-institute/sktime#869]
sktime 0.6.0

for example:
`from sktime.performance_metrics.forecasting import MeanAbsolutePercentageError`

gives the following error:

ImportError: cannot import name 'MeanAbsolutePercentageError' from 'sktime.performance_metrics.forecasting' (/opt/anaconda3/lib/python3.8/site-packages/sktime/performance_metrics/forecasting/__init__.py)

**Comment by RNKuhns** [comment]
@eyalshafran you can access the performance metrics in `sktime.forecasting.all`. 

But you raise a good point about the performance_metrics not being available for import from the `performance_metrics.forecasting` sub-module. 

I'll talk with @mloning about where we want to make these available in the API.

**Comment by mloning** [comment]
I think this is related to https://github.com/alan-turing-institute/sktime/issues/865 - please make sure your version align (the new metrics are on `main` but not in the latest release yet).
