### ISSUE TITLE
fit method argument does not accept numpy.ndarray

### ISSUE THREAD

**Issue by thayeylolu** [alan-turing-institute/sktime#880]
**Is your feature request related to a problem? Please describe.**
fit method argument of ARIMA throws error if argument is a numpy array.

**Describe the solution you'd like**
Allowing automatic casting of numpy.ndarray argument to pd.Series argument in fit method

**Describe alternatives you've considered**
converting the numpy array to a series `forecaster.fit(pd.Series(y))`

**Additional context**
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/13348874/118844122-9d783880-b8c2-11eb-8b17-8778b3c465b6.png">
Docstring
```python
    """Validate input data.

    Parameters
    ----------
    Z : pd.Series, pd.DataFrame, np.ndarray
        Univariate or multivariate time series. NumPy ndarray only allowed
        if `allow_numpy` = True.
    enforce_univariate : bool, default = False
        If True, multivariate Z will raise an error.
    allow_empty : bool, default = False
    allow_numpy : bool, default = True
    enforce_index_type : type, default = None
        type of time index

    Returns
    -------
    Z : pd.Series when univariate
         pd.DataFrame when multivariate
        Validated time series

    Raises
    ------
    ValueError, TypeError
        If Z is an invalid input
    """
```

**Comment by mloning** [comment]
This is now working.
