### ISSUE TITLE
 The function 'plot_series' should accept series with different index types 

### ISSUE THREAD

**Issue by Dbhasin1** [alan-turing-institute/sktime#882]
**Is your feature request related to a problem? Please describe.**
The plot_series function throws an error when multiple series with different index types are passed as parameters.

**Describe the solution you'd like**
The function should include implicit type casting of the series' indexes  

**Describe alternatives you've considered**
Manually converting the datatype of the series' indexes before passing them to the plot_series function using pandas 

**Additional context**
<img width="1009" alt="Screenshot 2021-05-20 at 4 48 00 PM" src="https://user-images.githubusercontent.com/56479884/118969810-25c21080-b98b-11eb-96b1-010d9a9d5a05.png">

**Comment by mloning** [comment]
```python
def _check_indices(x, y):
    # compare and check index x and y
```
