### ISSUE TITLE
[DOC] Fix docstrings for doc sprint 

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#884]
#### Describe the issue linked to the documentation
#863 

#### Easy files to fix
* https://github.com/alan-turing-institute/sktime/blob/77c2547b7f05e2975962eca749d4c9f4f2b8468e/sktime/utils/_maint/_show_versions.py
* https://github.com/alan-turing-institute/sktime/blob/main/sktime/transformations/series/boxcox.py
* https://github.com/alan-turing-institute/sktime/blob/main/sktime/transformations/series/acf.py

**Comment by GuzalBulatova** [comment]
Working on fixing `transformations/series/boxcox.py` 🤖
