### ISSUE TITLE
np.int is a deprecated 

### ISSUE THREAD

**Issue by vherrera96** [alan-turing-institute/sktime#893]
https://github.com/alan-turing-institute/sktime/blob/c611e6a3587d7b3a44cb7deefd4b6baa4897fc9b/sktime/forecasting/base/_fh.py#L92
Throws

> DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.

Should `np.int` be removed, replaced with `int` or should the warning just be ignored.

**Comment by mloning** [comment]
Hi @vherrera96, given that it's an integer index, I think we can remove it. If that breaks anything, we should replace it with `int`.

**Comment by vherrera96** [comment]
> Hi @vherrera96, given that it's an integer index, I think we can remove it. If that breaks anything, we should replace it with `int`. Would you like to open a PR for this? That would also give you the chance to clean up the docstrings.

Of course, @mloning! I will take care of it. Could you assign this issue to me?

**Comment by fkiraly** [comment]
Ultimately, this was done in various PR:
https://github.com/alan-turing-institute/sktime/pull/1997
https://github.com/alan-turing-institute/sktime/pull/1734
