### ISSUE TITLE
np.float is a deprecated

### ISSUE THREAD

**Issue by vherrera96** [alan-turing-institute/sktime#894]
https://github.com/alan-turing-institute/sktime/blob/c611e6a3587d7b3a44cb7deefd4b6baa4897fc9b/sktime/transformations/base.py#L21
Throws
> DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.

Should `np.float` be removed, replaced with `np.float64` or should the warning just be ignored.

**Comment by mloning** [comment]
Hi @vherrera96, same here as in #893: I think we can remove it. If that breaks anything, we should replace it with `np.float64`.

**Comment by vherrera96** [comment]
@mloning could you assign me this issue too, please.

**Comment by fkiraly** [comment]
Ultimately, this was done in various PR:
https://github.com/alan-turing-institute/sktime/pull/1997
https://github.com/alan-turing-institute/sktime/pull/1734
