### ISSUE TITLE
TSC/TSR: Implement/interface favourite UEA algorithms

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#9]
Not necessarily in sktime unified interface.
Priority is scalable/efficient and robust implementation which can be interfaced.

Care needs to be taken with writing code in a way such that it includes:
- a fitting method, to data, which returns a stored models
- a prediction method, which takes a model and returns predictions given the feature
- a method interface which explicitly exposes hyper-parameters (e.g., per declaration or as a return dictionary)

**Comment by TonyBagnall** [comment]
so update on implementations/functionality of specific algorithms
in sktime.classifiers: boss, rise, tsf, ee, proximity_forest
in sktime.contrib (to be ported):  bop, rotation forest another elastic_ensemble?.
in forks, awaiting assimilation: 9 kernel methods  
in https://github.com/uea-machine-learning/sktime-dl: 8 deep learning classifiers.

have I missed any? Could someone list the configurable classifiers? Straight pipeline, ensemble pipeline and dimension ensemble iirc?

**Comment by TonyBagnall** [comment]
so I can finally say this is done. I have run locally versions of TSF, RISE, BOSS, EE, ST and PF in sktime. Discussion of benchmarking can move to the bakeoff issue
