### ISSUE TITLE
[DOC]Sphinx build error while running make docs command

### ISSUE THREAD

**Issue by afzal442** [alan-turing-institute/sktime#901]
#### Describe the issue linked to the documentation

To build the website locally as described in the contributing [guide](https://github.com/alan-turing-institute/sktime/blob/main/CONTRIBUTING.md#documentation), make docs command throws an error as below.
```sphinx
Sphinx error:
Builder name docs not registered or available through entry point
make: *** [Makefile:29: docs] Error 2
```

#### Suggest a potential alternative/fix

To enable it to be run first change the directory to docs as `cd docs` in the command terminal, then we can run `make html` instead of `make docs`. Also add the below information to be more explicit in the documentation.

When building sktime’s documentation, the most common options for **`make`** are:

- html: build any HTML output that hasn’t been built yet or needs to be rebuilt to include changes to the documentation source files.
- clean: remove all previously built documentation output. All output files are generated from scratch on the next build.
- serve: start a minimal web server and open a web browser to display the docs. Starting a server is necessary because large portions of the documentation require JavaScript files in the background.

For example, to clean the docs build directory, run the following command:

`make clean`

**Comment by afzal442** [comment]
@mloning could you tell me if it works fine on your system (Mac) when you run the command `make docs`? Thanks

**Comment by mloning** [comment]
Yes `make docs` should work on UNIX systems, it works on my machine.

**Comment by afzal442** [comment]
Thanks @mloning but do you get the rendered HTML files on your local machine? Plz have a look at the screenshot shared below after running the command.

![c2](https://user-images.githubusercontent.com/11625672/122062457-0e046d80-ce0d-11eb-8327-a90fc663ca0f.JPG)

Let me know if you get expected page as below

![c3](https://user-images.githubusercontent.com/11625672/122062885-6f2c4100-ce0d-11eb-8693-518dbd36349d.JPG)

**Comment by mloning** [comment]
Yes I get the expected pages

**Comment by afzal442** [comment]
Thanks @mloning, nice to know about this. I really wondered where I am missing. Could you plz bring the steps here once you run the commands? I mean which file/folder to explore.

**Comment by mloning** [comment]
The main page is in `sktime/docs/_build/html/index.html`

**Comment by fkiraly** [comment]
fixed at some point, we are using readthedocs now
