### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by prasadovhal** [alan-turing-institute/sktime#903]
** TypeError: predict() got an unexpected keyword argument 'X'**

**To Reproduce**

```python
<Paste your code here>
```
from sktime.datasets import load_airline
from sktime.forecasting.arima import AutoARIMA
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.performance_metrics.forecasting import mean_absolute_percentage_error

y = load_airline()
y_train, y_test = temporal_train_test_split(y, test_size=36)

forecaster = AutoARIMA(sp=12, suppress_warnings=True)
forecaster.fit(y_train)
y_pred = forecaster.predict(fh)
mean_absolute_percentage_error(y_pred, y_test)

**Expected behavior**
 I followed tutorials given in documentation and followed exact steps mentioned, documentation shows code running fine but I got error mentioned above

**Additional context**

**Versions**
<details>

</details>

**Comment by aiwalter** [comment]
Pls make sure to paste the code into the right place. Seems you did not define `fh`?
