### ISSUE TITLE
Not able to install sktime

### ISSUE THREAD

**Issue by ksaurabh21** [alan-turing-institute/sktime#904]
Unable to install sktime. I am getting the attached error:
![image (5)](https://user-images.githubusercontent.com/7358203/119648878-98c20000-be3f-11eb-9d15-dba262f7324c.png)

**Comment by aiwalter** [comment]
Pls use the issue template and provide required information.

**Comment by mloning** [comment]
@ksaurabh21 seems like we don't provide a wheel for your platform, which operating system are you on?

**Comment by ksaurabh21** [comment]
Here are the os details:

NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o
enterprise_linux:7.9
server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

**Comment by mloning** [comment]
You could try to use a more recent Python and/or sktime version. Otherwise see if the advanced installation instructions help you to compile sktime on your platform: https://www.sktime.org/en/latest/installation.html

**Comment by TonyBagnall** [comment]
hi @ksaurabh21 can we close this issue?

**Comment by ksaurabh21** [comment]
Yes, please do.
