### ISSUE TITLE
series_as_features.base.estimators.interval_based

### ISSUE THREAD

**Issue by TonyBagnall** [alan-turing-institute/sktime#908]
I'm not sure why this exists and is in this location, may be some legacy code. It should be integrated into classification I think

![image](https://user-images.githubusercontent.com/9594042/119882184-08aab600-bf26-11eb-903b-b01464a6c512.png)

**Comment by mloning** [comment]
This is where code lives shared between classifiers and regressors. Happy to move this somewhere else but classification doesn't seem like the right place if it's shared by regressors.

**Comment by TonyBagnall** [comment]
I think it should be in classification or utilities and avoid cloning, especially whilst regression is in development but I'll take a closer look
