### ISSUE TITLE
Can sktime deal with multiple time series forecasting？

### ISSUE THREAD

**Issue by wangbingnan136** [alan-turing-institute/sktime#909]
I have read all the tutorials of sktime,but I did not find any tutorial or API about multiple time series forecasting?Can anyone help?

**Comment by mloning** [comment]
Hi @wangbingnan136, what do you mean by multiple time series forecasting? Predicting multiple series (multivariate forecasting) or predicting a single series from multiple series (forecasting with exogenous data)? 

sktime currently forecasting with exogenous data. For multivariate forecasting, there are ongoing development efforts (https://github.com/sktime/enhancement-proposals/pull/4).

**Comment by wangbingnan136** [comment]
Hello,sir,thanks for your reply! For example,the kaggle web traffic competition,I need to use many traffic data from different web pages,and I need to build only one model on thousands of different time series data of different pages to learning the potential pattern among all the pages,and the I can use one model to forecast different pages.This is the explanation of multiple time series forecasting.

**Comment by mloning** [comment]
Okay, I would call this cross-learning or panel forecasting, it's currently not supported but on the roadmap.

**Comment by wangbingnan136** [comment]
Thanks for your reply!
