### ISSUE TITLE
Installation fails because of missing include for limits.h

### ISSUE THREAD

**Issue by tombh** [alan-turing-institute/sktime#913]
**Describe the bug**
When installing with `pip install sktime`, I get:
```
   sktime/classification/shapelet_based/mrseql/SNode.cpp:89:39: error: ‘numeric_limits’ is not a member of ‘std’
       89 |             totalWildcardLimit = std::numeric_limits<int>::max();
          |                                       ^~~~~~~~~~~~~~
    sktime/classification/shapelet_based/mrseql/SNode.cpp:89:54: error: expected primary-expression before ‘int’
       89 |             totalWildcardLimit = std::numeric_limits<int>::max();
          |                                                      ^~~

```

**To Reproduce**
I have a standard, up to date, Arch Linux system

**Additional context**
This fixes the problem:
`CPLUS_INCLUDE_PATH=/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include-fixed/limits.h pip install sktime`

**Versions**
python: 3.9.5
gcc: 11.1.0

**Comment by tombh** [comment]
This commit also fixes it: https://github.com/tombh/sktime/commit/53df0b9ed9d1fd800539165c414cc5611bcc56b3

**Comment by mloning** [comment]
Thanks @tombh, would you like to open a PR? @lnthach what do you think?

**Comment by tombh** [comment]
Submitted 🤓
