### ISSUE TITLE
Issues for the 2021 summer dev sprint

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#920]
This issue collects some good issues to work on during the 2021 summer dev sprint (#863).
Will consolidate things in the first post, but please free to discuss and suggest in reply posts.

* Refactor Theta and implement AutoTheta (https://github.com/alan-turing-institute/sktime/discussions/854)
* Implement annotation module (#838)

**Comment by TonyBagnall** [comment]
1. Redesign and unify the unit tests for classification

**Comment by fkiraly** [comment]
this is issues, high-level brainstorming is here:
https://github.com/alan-turing-institute/sktime/discussions/919

good idea, btw - perhaps also an interface refactor with input/output checks?

**Comment by TonyBagnall** [comment]
closing since dev days have finished
