### ISSUE TITLE
Implement ThetaLines transformer

### ISSUE THREAD

**Issue by GuzalBulatova** [alan-turing-institute/sktime#922]
**References re-design of Theta Forecaster #854**

**Describe the solution you'd like**
Implement `ThetaLines` series to series transformer to decompose original data (univariate series) into theta lines for Theta forecaster .

**Related issues:**
Poor Theta model predictions #421
Implementation of AutoTheta Forecaster #738

**Existing implementations:**
- in sktime `sktime/forecasting/theta.py` (theta parameter is assumed)

other implementations in R:
- Theta https://rdrr.io/cran/forecast/man/thetaf.html
- AutoTheta https://github.com/vangspiliot/AutoTheta/blob/master/code
- M4 AutoTheta https://github.com/Mcompetitions/M4-methods/tree/master/260 - KaterinaKou
- 4Theta https://github.com/Mcompetitions/M4-methods/blob/master/4Theta method.R
- (boxcox + theta) https://github.com/Mcompetitions/M4-methods/blob/master/260 - KaterinaKou/final_M4.R
- Theta in statsmodels https://www.statsmodels.org/devel/examples/notebooks/generated/theta-model.html
- differencing is implemented in https://alkaline-ml.com/pmdarima/_modules/pmdarima/utils/array.html#diff

**Comment by Lovkush-A** [comment]
@GuzalBulatova Very thorough description! I look forward to seeing how this progresses. Happy to help out if I can.

**Comment by GuzalBulatova** [comment]
@Lovkush-A Thank you Lovkush, I appreciate it, reviews and general feedback would help a lot! 🚀

**Comment by GuzalBulatova** [comment]
ThetaLines transformer is implemented: #923 (merged)
