### ISSUE TITLE
[DOC]Install requirements for WSL2 in installation guide

### ISSUE THREAD

**Issue by afzal442** [alan-turing-institute/sktime#924]
#### Describe the issue linked to the documentation
It has come to my attention that in order to run `sktime` under WSL2, we should follow the Ubuntu linux instructions.

We should include a `..note` directive in the windows instructions pointing to the linux ones for users of WSL2 as their platform.

**Comment by afzal442** [comment]
Closing for #1010

**Comment by fkiraly** [comment]
well, it hasn't been merged yet, so let's reopen but attach to the new PR, so it closes whan that gets merged.
