### ISSUE TITLE
Exposing AIC, BIC and HQIC from sktime models via get_fitted_params

### ISSUE THREAD

**Issue by zollen** [alan-turing-institute/sktime#931]
After fitting a time series model (i.e. ARIMA, AutoETS...etc), there is no way to retrieve individual fitting scores (i.e. AIC, BIC, HQIC..etc) for evaluation.

The following key does not exists
model.get_fitted_params()['aic']
model.get_fitted_params()['bic']
model.get_fitted_params()['hqic']

**Comment by ltsaprounis** [comment]
For both AutoETS and AutoARIMA you can view AIC, BIC and HQIC (and anything else you need to know) via the summary method: `forecaster.summary()`. For AutoETS models you can also get them through `forecaster._fitted_forecaster.bic`

**Comment by zollen** [comment]
I was hoping I am able to retrieve parameter for evaulation. Of course I knew about the summary()

**Comment by ltsaprounis** [comment]
OK that makes sense - You need to do some digging to reach the fitted forecaster class from statsmodels etc.
Here is a summary on how to access them for a few of the classes: 
- **AutoETS:** `forecaster._fitted_forecaster.bic` relevant class is [ETSResults](https://www.statsmodels.org/dev/generated/statsmodels.tsa.exponential_smoothing.ets.ETSResults.html?highlight=etsresults#statsmodels.tsa.exponential_smoothing.ets.ETSResults) from statsmodels
- **ExponentialSmoothing:** `forecaster._fitted_forecaster.bic` relevant class is [HoltWintersResults](https://www.statsmodels.org/dev/generated/statsmodels.tsa.holtwinters.HoltWintersResults.html) from statsmodels
- **AutoARIMA:** `forecaster._forecaster.model_.arima_res_.bic` relevant class is [SARIMAXResults](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.html) from statsmodels
- **ARIMA:** `forecaster._forecaster.arima_res_.bic`relevant class is [SARIMAXResults](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.html) from statsmodels

Hope this helps.

**Comment by zollen** [comment]
Good enough for me. Thanks.

**Comment by fkiraly** [comment]
But I think it should be possible using the commands as proposed initially - opening this back up hence.

I also think it´s a good first issue, since it just needs a loopthrough to `get_fitted_params` (plus documentation) which is straightforward to implement.

**Comment by fkiraly** [comment]
(no need for you to do this, @zollen, but so that someone else can pick this up)
