### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Vaderv** [alan-turing-institute/sktime#939]
Getting Error when running example from document AutoArima library 

from sktime.datasets import load_airline
from sktime.forecasting.arima import AutoARIMA
air_y = load_airline()
forecaster = AutoARIMA(sp=12, d=0, max_p=2, max_q=2, suppress_warnings=True)
forecaster.fit(air_y)
y_pred = forecaster.predict(fh=[1,2,3])

```python
from sktime.datasets import load_airline
from sktime.forecasting.arima import AutoARIMA
air_y = load_airline()
forecaster = AutoARIMA(sp=12, d=0, max_p=2, max_q=2, suppress_warnings=True)
forecaster.fit(air_y)
AutoARIMA(...)
y_pred = forecaster.predict(fh=[1,2,3])
```

**Expected behavior**

**Additional context**

**Versions**
<details>
0.6.1

</details>

**Comment by aiwalter** [comment]
pls provide the error message. An issue title might also help others to see what this issue is about.
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by aiwalter** [comment]
I am closing this, seems to be resolved
