### ISSUE TITLE
[BUG] ModuleNotFoundError, no module named 'sktime.classification.kernel_based' 

### ISSUE THREAD

**Issue by tabhishek432** [alan-turing-institute/sktime#946]
**Describe the bug**
There is an error while importing kernel_based classifiers, the error shown: ModuleNotFoundError: no module named 'sktime.classification.kernel_based' 

**To Reproduce**
 Wrote an example on my own

```python
from sklearn.model_selection import train_test_split
from sktime.classification.kernel_based import ROCKETClassifier
from sktime.datasets import load_basic_motions
X, y = load_basic_motions(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y)
clf = ROCKETClassifier(
		num_kernels=2000,
        n_jobs=1,
        random_state=42)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)
```

**Expected behavior**
It should work

**Additional context**

**Versions**
<details>

sktime: 0.6.1

</details>

**Comment by TonyBagnall** [comment]
hi, you might need to update to the latest version of sktime, its here 
![image](https://user-images.githubusercontent.com/9594042/122021118-47ad8800-cdbd-11eb-9498-e6e7aa9070a5.png)

**Comment by TonyBagnall** [comment]
hi @tabhishek432 did you fix this? Can I close this issue?

**Comment by TonyBagnall** [comment]
hi, I'm house keeping so will close this issue, if you still have problems feel free to reopen

**Comment by allenyllee** [comment]
I find the name was changed from `ROCKETClassifier` into `RocketClassifier`, in version 0.14.1
