### ISSUE TITLE
using fourier decomposition as part of auto-optimization for AutoARIMA

### ISSUE THREAD

**Issue by zollen** [alan-turing-institute/sktime#954]
I am thinking of using fourier decomposing for a time series data, the resulting base frequencies would be used for the exog of the AutoARIMA, do you think it would help improve the overall mean errors?

If the above approach is feasible, is it possible to built-in this features as part of internal/external auto-optimization of AutoARIMA?

**Comment by fkiraly** [comment]
This is possible using `DiscreteFourierTransformer` in a pipeline with `AutoARIMA`.
