### ISSUE TITLE
AutoARIMA should give access to pdq under `get_fitted_params`

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#962]
`AutoARIMA` is an ARIMA variant that automatically fits the pdq parameters.

Those parameters are likely of interest to practitioners, so `get_fitted_params` should be able to retrieve these?

**Comment by afzal442** [comment]
I would like to look into this.

https://github.com/alan-turing-institute/sktime/blob/ad82a2792b792c6357c8c0db815772bae04c86c1/sktime/forecasting/base/adapters/_pmdarima.py#L124

https://github.com/alan-turing-institute/sktime/blob/ad82a2792b792c6357c8c0db815772bae04c86c1/sktime/forecasting/base/adapters/_pmdarima.py#L136-L138

**Comment by ltsaprounis** [comment]
Was thinking about this the other day!
Same for AutoETS, it should return the Error Trend and Seasonal components of the chosen model e.g. AAA, ANN etc.

**Comment by ltsaprounis** [comment]
Yes there is a get_fitted_params function in the statsmodels adapter, but for now it returns nothing for AutoETS.  https://github.com/alan-turing-institute/sktime/blob/ad82a2792b792c6357c8c0db815772bae04c86c1/sktime/forecasting/base/adapters/_statsmodels.py#L87

I discovered that when working on #942. I think get_fitted_params should return the fitted parameters (level, smoothing parameters etc.) for ExponentialSmoothing and for AutoETS it should return those plus the selected model. Same behaviour should be expected for ARIMA and AutoARIMA.

**Comment by BINAYKUMAR943** [comment]
I would like to work on this issue.

**Comment by fkiraly** [comment]
@BINAYKUMAR943, @afzal442, have you been working on this?
Generally, the issue is yours (for a while) once you say

**Comment by afzal442** [comment]
Thanks @fkiraly , does that mean how to retrieve `pdq` from `order`? I am not sure but order gives pdq. Isn't that?

**Comment by BINAYKUMAR943** [comment]
@fkiraly sorry, it's my bad!. I missed this. 

> @BINAYKUMAR943, @afzal442, have you been working on this?
> Generally, the issue is yours (for a while) once you say

I didn't know that. I was waiting it to be assigned. I am currently working on some issues in the classification module.

**Comment by fkiraly** [comment]
>Thanks @fkiraly , does that mean how to retrieve pdq from max_p, max_d, max_q? I am not sure but that I understood.

Precisely!

**Comment by fkiraly** [comment]
>I didn't know that. I was waiting it to be assigned. I am currently working on some issues in the classification module.

Ah - sorry, should have made this clearer.

**Comment by fkiraly** [comment]
@BINAYKUMAR943, are you still working on this?

**Comment by AngelPone** [comment]
@fkiraly I can work on this. Please see #1641 .
