### ISSUE TITLE
AttributeError: module 'sktime.utils' has no attribute 'data_processing' for version 0.6.1

### ISSUE THREAD

**Issue by orko19** [alan-turing-institute/sktime#963]
I have a sktime version 0.6.1 but I get the 
```
dts = sktime.utils.data_processing.from_2d_array_to_nested(df)
AttributeError: module 'sktime.utils' has no attribute 'data_processing'
```
from the API doc I see that it should work.
Any idea?

Thanks

**Comment by mloning** [comment]
You're probably using an older version of sktime or sktime isn't properly installed in the Python environment that you're using.

**Comment by TonyBagnall** [comment]
was this with sktime-dl? If so, it was a bug introduced a couple of days ago, the requirements.txt was not updated, but I think its fixed now

**Comment by fkiraly** [comment]
no follow-up by original poster, closing
