### ISSUE TITLE
Update 'capabilities' tag for Mr-SEQL

### ISSUE THREAD

**Issue by luiseduve** [alan-turing-institute/sktime#966]
https://github.com/alan-turing-institute/sktime/blob/9f9bb9e7aeb135d5ca326c282c86a1c5aa0df28d/sktime/classification/shapelet_based/mrseql/mrseql.pyx#L227

According to the example .pynb, Mr-SEQL has multivariate capabilities: https://github.com/alan-turing-institute/sktime/blob/v0.6.1/examples/mrseql.ipynb

However, the internal 'capabilities' tag is still set to `"multivariate": False`

**Comment by mloning** [comment]
Thanks @luiseduve, would appreciate a quick PR to fix that!

**Comment by TonyBagnall** [comment]
hi, thanks for that, might be good to check first that it does actually work with multivariate

**Comment by aricooperdavis** [comment]
It looks like this was fixed in d69457b5fed7312df05420cb1d8bb6eb5bd195e9 👍
