### ISSUE TITLE
Implement consistent input checks

### ISSUE THREAD

**Issue by mloning** [alan-turing-institute/sktime#98]
Currently we have a number of [input validation functions](https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/validation.py), none of them are consistently enforced and some of them don't do anything. 

Related to #15

**Comment by TonyBagnall** [comment]
so what constraints on data/input checks do we want? I guess we need to check the data type of series (real valued or missing)?

**Comment by mloning** [comment]
On the low level interface, I think we agreed on the at least the following checks:
* `isinstance(X, pd.DataFrame)`
* `isinstance(y, (pd.Series, np.ndarray))`

They should be checked in all our methods I think.

A few other checks I can think of are:
* cells of X should contain either primitives or series in form of either `pd.Series` or `np.ndarray`
* series in cells of X should be of at least length >=2 
* missing values
* consistency of series within the same column (extending pandas column typing), including equal length, shared time index, consistent type of series within column

Not sure whether to check these in our methods, or delegate them to the data container and only query them if required.

**Comment by TonyBagnall** [comment]
so for full flexibility, we should allow meta data loading, and characteristics from the data. So checks

**Comment by mloning** [comment]
Yes, most of our methods assume univariate time series data (at least until we implement bespoke methods to handle these cases), that should also be consistently checked (related to multivariate composites, see #36), so `X.shape[1] == 1`.

**Comment by mloning** [comment]
We should use sklearn's `check_is_fitted` in predict/transform.

**Comment by mloning** [comment]
Another question is whether we want the `check_input` kwarg for estimators/transformers allowing users to disable input checks. I thought that would be a good idea initially, but I'm less sure now.

**Comment by TonyBagnall** [comment]
I dont know re check_input, but my opinion is that it is up to an estimator to check its capabilities, allowing user to disable checks sounds like it breaks encapsulation and may result in undetermined behaviour.

**Comment by mloning** [comment]
* common check if data (column typing) is series or primitives

**Comment by mloning** [comment]
Currently, error messages are not very helpful when passing tabular pandas dataframe (see e.g. #150). We need to add checks for nested format, either as part of the input validation functions or the pandas container.

**Comment by mloning** [comment]
Closed by #246
