### ISSUE TITLE
forecasting interval and probabilistic prediction interface refactor/re-design

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#984]
Let's think about a re-factoring of the forecasting interface for interval and probabilistic predictions.

I think we should have:

* `predict_interval`, this should take `alpha` as in `predict` and return quantiles; one should be able to pass lists of `alpha` too (if the forecaster supports it). If a list is passed, we need to think about the return object - perhaps a data frame, with nested column index if we are in the multivariate case? Or, we could annotate columns `[variablename]__[statistic]`, e.g., `temperature__P95` using the reserved double-underscore.
* `predict_var`, this should return predictive variance (not quantiles) - note that that's what comes out Gaussian process type regressors primarily.
* `predict_proba`, this returns a `skpro`-like distribution object. May requires work on `skpro`, or could use `tensorflow-probability` distributions.

For the first two, we could alternatively think about return flags and return objects in `predict`, but that just seems very messy to me.

Any opinions? @aiwalter, @mloning, @RNKuhns

**Comment by mloning** [comment]
I agree that we need to refactor this. 

The main reason for combining point predictions and prediction intervals was that intervals often rely on point predictions, so we would avoid computing point predictions twice. Any solution to that problem? Storing `y_pred` for a given cutoff and forecasting horizon in the forecaster like statsmodels doesn't seem right.

**Comment by fkiraly** [comment]
Looking through the base class, I think there are a number of unnecessary (or refactor worthy) methods in there:

* `compute_pred_int`, seems to duplicate the current interface point in `predict`, used only by `theta`
* `_compute_pred_int`, called by `compute_pred_int` only
* `_get_pred_int`, used only by `_tbats` - move to `_tbats`?
* `_compute_pred_err`, called by `compute_pred_err`, used for override in some descendants

**Comment by fkiraly** [comment]
>The main reason for combining point predictions and prediction intervals was that intervals often rely on point predictions, so we would avoid computing point predictions twice. Any solution to that problem? 

Two solutions I can see:

* caching the prediction it's called the first time
* the "interval" methods also return point predictions when called, so if you want both you just call the "interval" method

I think I prefer the second one.

**Comment by SveaMeyer13** [comment]
FYI: @mloning and I discussed that I could work on this. To get familiar with the current design I started by reviewing #775.

**Comment by fkiraly** [comment]
I made a STEP here, please review:
https://github.com/sktime/enhancement-proposals/pull/15

**Comment by fkiraly** [comment]
From the STEP, I would recommend to not implement everything at once - at first step, I'd focus on `predict_interval` and nothing else.

**Comment by mloning** [comment]
Yes I agree, let's start with `predict_interval`. For `predict_interval`, should we implement bootstrapping in the base class as the fallback option (following the `forecast` package in R and described in https://otexts.com/fpp3/prediction-intervals.html#prediction-intervals-from-bootstrapped-residuals)?

**Comment by fkiraly** [comment]
My preference would be to implement the various strategies as a `PredictionIntervalAdder(myest, strategy="hyndman-bootstrap")` or similar, since there are multiple ways to do this. I've described to @SveaMeyer13 a different way that makes less assumptions. The Hyndman way is a bit problematic imo since it seems to assume a generalized autoregressive model. But I think both should be options.

**Comment by fkiraly** [comment]
And, it should be noted, there are two things in here: the base class interface refactor (moving intervals out into another method), and adding concrete prediction interval functionality.

**Comment by mloning** [comment]
I agree, any reference to the other approach?

**Comment by fkiraly** [comment]
"quantiles from backtesting", I would consider this a more obvious approach if you can assume being close to stationary in residuals:

1. run sliding window backtesting to obtain predictions $\hat{y}_{ij}$, by i-th horizon, by j-th window
(H points in the horizon, W windows total, so there are H*W predictions)
2. compute residuals $r_{ij}$ for those predictions, by subtracting predicted from actuals, i.e., $r_{ij} = y_{ij} - \hat{y}_{ij}$ where $y_{ij}$ are observed actuals in backtesting
3. when asked for alpha-prediction threshold for the i-th horizon, return point prediction plus the alpha-quantile of the sample $\{r_{ij}, j varies\}$
number of windows is a parameter

So the code could look like `PredictionIntervalAdder(my_forecaster, sliding-params)`,

or `PredictionIntervalAdder(my_forecaster, sliding-params, strategy = "historical_quantiles")`
other option could be `strategy = "hyndman_simulation"`

**Comment by SveaMeyer13** [comment]
Alright, so if I understood correctly these would be the steps to go: 
1) Base class refactor that focusses only on `predict_interval` as described in this [STEP](https://github.com/sktime/enhancement-proposals/pull/15/files):
* splitting of the prediction interval return functionality from `predict` in a function `predict_interval` still ensuring downwards compatibility. Following the method signatures for `predict` and `predict interval` as described in the STEP
* Removal/refactor of unnecessary `BaseForecaster` methods (also as described in the STEP. 
* For now, have `predict_interval`as an abstract method in the base class. 
2) Add model agnostic default functionality in the base class (e.g. bootstrapping and quantiles from backtesting)
3) Add model-specific `prediction_interval` functionality in the corresponding classes (still giving the user the option of choosing a strategy, which may also be one of the default strategies).
4) Continue with `predict_proba` and `predict_var` as described in the STEP

Would this summarize what you discussed so far @mloning and @fkiraly?

What I haven't understood yet is where the `PredictionIntervalAdder` comes in, it is not part of the STEP. I see how smth like that is needed to specify the strategy with which the prediction_interval should be obtained and to pass parameters for that strategy. But I wonder if you couldn't just add that to the method signature of `predict_interval(self, fh=None, X=None, alpha=Union[float, np.ndarray[float,dim=1]])`

**Comment by fkiraly** [comment]
I think this is accurate in understanding what @mloning wants?

My proposed way forward would be different in step 2:

2. implement a `PredictionIntervalAdder` that adds/replaces `predict_interval` with bootstrapping/quantiles functionality.

>But I wonder if you couldn't just add that to the method signature of `predict_interval(self, fh=None, X=None, alpha=Union[float, np.ndarray[float,dim=1]])`

That would "run" but violate the "unified interface" aka "strategy pattern" that we are using in `sktime` - all estimators of the same (sci)type must have exactly the same core method signature; any parameters, e.g., choice of prediction interval strategy, must be specified as `__init__` arguments in some estimator.

**Comment by mloning** [comment]
Yes @SveaMeyer13, let's start with 1, by then we may already have a better view on 2. 

Instead of adding the strategy argument to the `predict_interval` method, we could add it to the constructor. But I'm not sure which is preferable. I like the `PredictionIntervalAdder` because it's modular and nicely separates functionality into different classes. On the other hands, it adds an additional class that users need to know about.

**Comment by SveaMeyer13** [comment]
Cool! Thanks both, the discussion around `PredictionIntervalAdder` now became a lot clearer to me.  

Is there any other PR that I should wait for to be merged before creating a PR on 1? 

Also, do you think it's better to have everything of the first part of the refactor (as described in my last comment) in one big PR or should I still split it into smaller chunks?

**Comment by mloning** [comment]
I'm not aware of any other refactoring that's ongoing that would interfere with this. It's hard to say whether to split it up further. We could add the new interface point while maintaining the old one for now, perhaps that's a first step. Then if everything works, we could deprecate the old way of generating prediction intervals (i.e. via the `return_pred_int` argument in `predict`).

**Comment by fkiraly** [comment]
>I'm not aware of any other refactoring that's ongoing that would interfere with this. 

Not refactoring, but a minor interface change, #1410, might interfere, since it also changes the base forecasters' `predict`. It's probably not going to touch the same lines though, in `predict`, but worth being aware.

>We could add the new interface point while maintaining the old one for now, perhaps that's a first step.

That's precisely what my STEP suggests in the "downwards compatibility" section 😃

**Comment by SveaMeyer13** [comment]
One more question: Currently we also have `compute_pred_int(self, y_pred, alpha=DEFAULT_ALPHA)`, I'll leave it there for downwards compatibility and just create the new method `predict_interval(self, fh=None, X=None, alpha=Union[float, np.ndarray[float, dim=1]]) -> pd.DataFrame` in addition to that, right?

**Comment by mloning** [comment]
@SveaMeyer13 yes, let's leave everything as it is for now and only add the new interface point. Once that's merged, we can deprecate the old stuff. 👍

**Comment by fkiraly** [comment]
>Once that's merged, we can deprecate the old stuff. 

I would not deprecate the old stuff, just move it to the classes where they are called. They are not "actually public" interface points, and I think no one is using them anyway, since they are specific to some concrete classes and not useable outside those.

See the "removal/refactor of unnecessary `BaseForecaster` methods" in the STEP - is anyone reading this 😠 ... 😄

**Comment by SveaMeyer13** [comment]
Ahh sorry, when I asked the question I wasn't aware that `compute_pred_int(self, y_pred, alpha=DEFAULT_ALPHA)` is part of the unnecessary BaseForecaster methods in the STEP. In my PR I followed the suggestions in the STEP :D

**Comment by fkiraly** [comment]
Well, it might be worth briefly thinking about whether people *could* be using this, and whether applying the deprecation mechanism isn't still the better way to deal with it.

**Comment by mloning** [comment]
> Well, it might be worth briefly thinking about whether people _could_ be using this, and whether applying the deprecation mechanism isn't still the better way to deal with it.

Yes. And I was also referring to the `return_pred_int` parameter in `predict` which we should deprecate properly.

**Comment by fkiraly** [comment]
>And I was also referring to the return_pred_int parameter in predict which we should deprecate properly.

Well, that one I've factored in in the STEP, but I was "ignoring" the "weird unnecessary functions that should be in a child class".

**Comment by fkiraly** [comment]
adopted and implemented in versions 0.10 amd 0.11
