### ISSUE TITLE
forecasting: pretty-plotting for predictive interval forecasts

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#985]
There should be pretty-plotting functionality for predictive intervals in forecasting.

Something like `plot_series`, but adapted to the return pair when `return_pred_int=True` in `predict`.

This could be easily adapted from the code in the tutorial notebook.

**Comment by mloning** [comment]
See #802

**Comment by fkiraly** [comment]
yes, it's a duplicate of issue #541, closing
