### ISSUE TITLE
all-contributors - providing links/evidence

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#987]
I've just looked at the all-contributors spec, and we are using the symbols but not links to evidence of contributions.

Perhaps going forward we can try to be more systematic here, going forward?
Such as, adding instructions to PR to add links to contributions.

As convention, I think the first contribution that qualifies for a given symbol is enough here.

In terms of actions, we may also like to start filling these in for existing contribs?

**Comment by TonyBagnall** [comment]
where are these?

**Comment by fkiraly** [comment]
here: https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc

**Comment by fkiraly** [comment]
Not adopted
