### ISSUE TITLE
[DOC] forecasting tutorial: advanced pipeline construction

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/sktime#988]
As @aiwalter suggested in discussion in PR #972, it would be great to have a sub-section showcasing advanced pipelining functionality in `sktime`.

Citing @aiwalter:
"I would like to see also a more sophisticated tuning part including `MultiplexForecaster`, `TransformedTargetForecaster` or the new `ForecastingPipeline`, some transformers, `OptionalPassthrough`, `TabularToSeriesAdaptor`. Maybe this can be a separate page/Notebook on the website then."

The "obvious" person to write this is perhaps @aiwalter who wrote much of this functionality, or @koralturkk - but I also think anyone should be able to do it with occasional guidance from the two.

Should probably be done after #972 is merged, would fit nicely as section 3.2.4 "advanced pipeline construction" or similar (after "complex composites and parameter inspection"). Could also be a separate notebook, as @aiwalter suggests; though I would find it nicely fitting in the 101 tutorial.

**Comment by aiwalter** [comment]
its in progress, but I have issues with `pre-commit` to and `nbqa`, nedd to get this fixed before I can push sth.
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by fkiraly** [comment]
done in #1047
